import type { Serializable } from '../../../java/io/Serializable.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { Function } from '../../../kotlin/Function.d.ts'
export abstract class FunctionImpl extends Object implements Serializable, Function<Object> {
    constructor()
    // private checkArity(arg0: number): void;
    getArity(): number;
    invoke(): Object | null;
    invoke(arg0: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null, arg9: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null, arg9: Object | null, arg10: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null, arg9: Object | null, arg10: Object | null, arg11: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null, arg9: Object | null, arg10: Object | null, arg11: Object | null, arg12: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null, arg9: Object | null, arg10: Object | null, arg11: Object | null, arg12: Object | null, arg13: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null, arg9: Object | null, arg10: Object | null, arg11: Object | null, arg12: Object | null, arg13: Object | null, arg14: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null, arg9: Object | null, arg10: Object | null, arg11: Object | null, arg12: Object | null, arg13: Object | null, arg14: Object | null, arg15: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null, arg9: Object | null, arg10: Object | null, arg11: Object | null, arg12: Object | null, arg13: Object | null, arg14: Object | null, arg15: Object | null, arg16: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null, arg9: Object | null, arg10: Object | null, arg11: Object | null, arg12: Object | null, arg13: Object | null, arg14: Object | null, arg15: Object | null, arg16: Object | null, arg17: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null, arg9: Object | null, arg10: Object | null, arg11: Object | null, arg12: Object | null, arg13: Object | null, arg14: Object | null, arg15: Object | null, arg16: Object | null, arg17: Object | null, arg18: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null, arg9: Object | null, arg10: Object | null, arg11: Object | null, arg12: Object | null, arg13: Object | null, arg14: Object | null, arg15: Object | null, arg16: Object | null, arg17: Object | null, arg18: Object | null, arg19: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null, arg9: Object | null, arg10: Object | null, arg11: Object | null, arg12: Object | null, arg13: Object | null, arg14: Object | null, arg15: Object | null, arg16: Object | null, arg17: Object | null, arg18: Object | null, arg19: Object | null, arg20: Object | null): Object | null;
    invoke(arg0: Object | null, arg1: Object | null, arg2: Object | null, arg3: Object | null, arg4: Object | null, arg5: Object | null, arg6: Object | null, arg7: Object | null, arg8: Object | null, arg9: Object | null, arg10: Object | null, arg11: Object | null, arg12: Object | null, arg13: Object | null, arg14: Object | null, arg15: Object | null, arg16: Object | null, arg17: Object | null, arg18: Object | null, arg19: Object | null, arg20: Object | null, arg21: Object | null): Object | null;
    invokeVararg(arg0: Object[]): Object;
    // private throwWrongArity(arg0: number): void;
}