import type { JavaMap } from '../../../../../JavaMap.d.ts'
import type { Serializable } from '../../../../../java/io/Serializable.d.ts'
import type { Class } from '../../../../../java/lang/Class.d.ts'
import type { StringBuffer } from '../../../../../java/lang/StringBuffer.d.ts'
import type { Object } from '../../../../../java/lang/Object.d.ts'
export abstract class ToStringStyle extends Object implements Serializable {
    static DEFAULT_STYLE: ToStringStyle;
    static JSON_STYLE: ToStringStyle;
    static MULTI_LINE_STYLE: ToStringStyle;
    static NO_CLASS_NAME_STYLE: ToStringStyle;
    static NO_FIELD_NAMES_STYLE: ToStringStyle;
    static SHORT_PREFIX_STYLE: ToStringStyle;
    static SIMPLE_STYLE: ToStringStyle;
    static getRegistry(): JavaMap<Object, Object>;
    constructor()
    // private arrayContentDetail: boolean;
    // private arrayEnd: string;
    // private arraySeparator: string;
    // private arrayStart: string;
    // private contentEnd: string;
    // private contentStart: string;
    // private defaultFullDetail: boolean;
    // private fieldNameValueSeparator: string;
    // private fieldSeparator: string;
    // private fieldSeparatorAtEnd: boolean;
    // private fieldSeparatorAtStart: boolean;
    // private nullText: string;
    // private sizeEndText: string;
    // private sizeStartText: string;
    // private summaryObjectEndText: string;
    // private summaryObjectStartText: string;
    // private useClassName: boolean;
    // private useFieldNames: boolean;
    // private useIdentityHashCode: boolean;
    // private useShortClassName: boolean;
    append(arg0: StringBuffer, arg1: string, arg2: Object, arg3: boolean): void;
    append(arg0: StringBuffer, arg1: string, arg2: Object[], arg3: boolean): void;
    append(arg0: StringBuffer, arg1: string, arg2: boolean): void;
    append(arg0: StringBuffer, arg1: string, arg2: boolean[], arg3: boolean): void;
    append(arg0: StringBuffer, arg1: string, arg2: number): void;
    append(arg0: StringBuffer, arg1: string, arg2: number[], arg3: boolean): void;
    append(arg0: StringBuffer, arg1: string, arg2: string): void;
    append(arg0: StringBuffer, arg1: string, arg2: string[], arg3: boolean): void;
    appendClassName(arg0: StringBuffer, arg1: Object): void;
    appendContentEnd(arg0: StringBuffer): void;
    appendContentStart(arg0: StringBuffer): void;
    appendCyclicObject(arg0: StringBuffer, arg1: string, arg2: Object): void;
    appendDetail(arg0: StringBuffer, arg1: string, arg2: Object): void;
    appendDetail(arg0: StringBuffer, arg1: string, arg2: Object[]): void;
    appendDetail(arg0: StringBuffer, arg1: string, arg2: boolean): void;
    appendDetail(arg0: StringBuffer, arg1: string, arg2: boolean[]): void;
    appendDetail(arg0: StringBuffer, arg1: string, arg2: number): void;
    appendDetail(arg0: StringBuffer, arg1: string, arg2: number[]): void;
    appendDetail(arg0: StringBuffer, arg1: string, arg2: string): void;
    appendDetail(arg0: StringBuffer, arg1: string, arg2: string[]): void;
    appendDetail(arg0: StringBuffer, arg1: string, arg2: number, arg3: Object): void;
    appendDetail(arg0: StringBuffer, arg1: string, arg2: (Object | null)[]): void;
    appendDetail(arg0: StringBuffer, arg1: string, arg2: JavaMap<Object | null, Object | null>): void;
    appendEnd(arg0: StringBuffer, arg1: Object): void;
    appendFieldEnd(arg0: StringBuffer, arg1: string): void;
    appendFieldSeparator(arg0: StringBuffer): void;
    appendFieldStart(arg0: StringBuffer, arg1: string): void;
    appendIdentityHashCode(arg0: StringBuffer, arg1: Object): void;
    appendInternal(arg0: StringBuffer, arg1: string, arg2: Object, arg3: boolean): void;
    appendNullText(arg0: StringBuffer, arg1: string): void;
    appendStart(arg0: StringBuffer, arg1: Object): void;
    appendSummary(arg0: StringBuffer, arg1: string, arg2: Object): void;
    appendSummary(arg0: StringBuffer, arg1: string, arg2: Object[]): void;
    appendSummary(arg0: StringBuffer, arg1: string, arg2: boolean[]): void;
    appendSummary(arg0: StringBuffer, arg1: string, arg2: number[]): void;
    appendSummary(arg0: StringBuffer, arg1: string, arg2: string[]): void;
    appendSummarySize(arg0: StringBuffer, arg1: string, arg2: number): void;
    appendSuper(arg0: StringBuffer, arg1: string): void;
    appendToString(arg0: StringBuffer, arg1: string): void;
    getArrayEnd(): string;
    getArraySeparator(): string;
    getArrayStart(): string;
    getContentEnd(): string;
    getContentStart(): string;
    getFieldNameValueSeparator(): string;
    getFieldSeparator(): string;
    getNullText(): string;
    getShortClassName(arg0: Class<Object>): string;
    getSizeEndText(): string;
    getSizeStartText(): string;
    getSummaryObjectEndText(): string;
    getSummaryObjectStartText(): string;
    isArrayContentDetail(): boolean;
    isDefaultFullDetail(): boolean;
    isFieldSeparatorAtEnd(): boolean;
    isFieldSeparatorAtStart(): boolean;
    isFullDetail(arg0: boolean): boolean;
    isUseClassName(): boolean;
    isUseFieldNames(): boolean;
    isUseIdentityHashCode(): boolean;
    isUseShortClassName(): boolean;
    reflectionAppendArrayDetail(arg0: StringBuffer, arg1: string, arg2: Object): void;
    removeLastFieldSeparator(arg0: StringBuffer): void;
    setArrayContentDetail(arg0: boolean): void;
    setArrayEnd(arg0: string): void;
    setArraySeparator(arg0: string): void;
    setArrayStart(arg0: string): void;
    setContentEnd(arg0: string): void;
    setContentStart(arg0: string): void;
    setDefaultFullDetail(arg0: boolean): void;
    setFieldNameValueSeparator(arg0: string): void;
    setFieldSeparator(arg0: string): void;
    setFieldSeparatorAtEnd(arg0: boolean): void;
    setFieldSeparatorAtStart(arg0: boolean): void;
    setNullText(arg0: string): void;
    setSizeEndText(arg0: string): void;
    setSizeStartText(arg0: string): void;
    setSummaryObjectEndText(arg0: string): void;
    setSummaryObjectStartText(arg0: string): void;
    setUseClassName(arg0: boolean): void;
    setUseFieldNames(arg0: boolean): void;
    setUseIdentityHashCode(arg0: boolean): void;
    setUseShortClassName(arg0: boolean): void;
}