import type { JSContextOptions$UnhandledRejectionsTrackingMode } from '../../../../../com/oracle/truffle/js/runtime/JSContextOptions$UnhandledRejectionsTrackingMode.d.ts'
import type { Object } from '../../../../../java/lang/Object.d.ts'
import type { OptionKey } from '../../../../../org/graalvm/options/OptionKey.d.ts'
import type { OptionValues } from '../../../../../org/graalvm/options/OptionValues.d.ts'
import type { SandboxPolicy } from '../../../../../org/graalvm/polyglot/SandboxPolicy.d.ts'
export class JSContextOptions extends Object {
    static AGENT_CAN_BLOCK: OptionKey<boolean>;
    static AGENT_CAN_BLOCK_NAME: string;
    static ALLOW_EVAL: OptionKey<boolean>;
    static ALLOW_EVAL_NAME: string;
    static ALLOW_NARROW_SPACES_IN_DATE_FORMAT: OptionKey<boolean>;
    static ALLOW_NARROW_SPACES_IN_DATE_FORMAT_NAME: string;
    static ANNEX_B: OptionKey<boolean>;
    static ANNEX_B_NAME: string;
    static ARRAY_ELEMENTS_AMONG_MEMBERS: OptionKey<boolean>;
    static ARRAY_ELEMENTS_AMONG_MEMBERS_NAME: string;
    static ASYNC_CONTEXT: OptionKey<boolean>;
    static ASYNC_CONTEXT_NAME: string;
    static ASYNC_ITERATOR_HELPERS: OptionKey<boolean>;
    static ASYNC_ITERATOR_HELPERS_NAME: string;
    static ASYNC_STACK_TRACES: OptionKey<boolean>;
    static ASYNC_STACK_TRACES_NAME: string;
    static ATOMICS: OptionKey<boolean>;
    static ATOMICS_NAME: string;
    static ATOMICS_WAIT_ASYNC: OptionKey<boolean>;
    static ATOMICS_WAIT_ASYNC_NAME: string;
    static AWAIT_OPTIMIZATION: OptionKey<boolean>;
    static AWAIT_OPTIMIZATION_NAME: string;
    static BIGINT: OptionKey<boolean>;
    static BIGINT_NAME: string;
    static BIND_MEMBER_FUNCTIONS: OptionKey<boolean>;
    static BIND_MEMBER_FUNCTIONS_NAME: string;
    static CHARSET: OptionKey<string>;
    static CHARSET_NAME: string;
    static CLASS_FIELDS: OptionKey<boolean>;
    static CLASS_FIELDS_ES_VERSION: number;
    static CLASS_FIELDS_NAME: string;
    static COMMONJS_CORE_MODULES_REPLACEMENTS: OptionKey<{ [key: string]: string }>;
    static COMMONJS_CORE_MODULES_REPLACEMENTS_NAME: string;
    static COMMONJS_REQUIRE: OptionKey<boolean>;
    static COMMONJS_REQUIRE_CWD: OptionKey<string>;
    static COMMONJS_REQUIRE_CWD_NAME: string;
    static COMMONJS_REQUIRE_NAME: string;
    static CONSOLE: OptionKey<boolean>;
    static CONSOLE_NAME: string;
    static CONST_AS_VAR: OptionKey<boolean>;
    static CONST_AS_VAR_NAME: string;
    static DEBUG_BUILTIN: OptionKey<boolean>;
    static DEBUG_BUILTIN_NAME: string;
    static DEBUG_PROPERTY_NAME: OptionKey<string>;
    static DEBUG_PROPERTY_NAME_NAME: string;
    static DIRECT_BYTE_BUFFER: OptionKey<boolean>;
    static DIRECT_BYTE_BUFFER_NAME: string;
    static DISABLE_EVAL: OptionKey<boolean>;
    static DISABLE_EVAL_NAME: string;
    static DISABLE_WITH: OptionKey<boolean>;
    static DISABLE_WITH_NAME: string;
    static ECMASCRIPT_VERSION: OptionKey<number>;
    static ECMASCRIPT_VERSION_LATEST: string;
    static ECMASCRIPT_VERSION_NAME: string;
    static ECMASCRIPT_VERSION_STAGING: string;
    static ERROR_CAUSE: OptionKey<boolean>;
    static ERROR_CAUSE_NAME: string;
    static ESM_BARE_SPECIFIER_RELATIVE_LOOKUP: OptionKey<boolean>;
    static ESM_BARE_SPECIFIER_RELATIVE_LOOKUP_NAME: string;
    static ESM_EVAL_RETURNS_EXPORTS: OptionKey<boolean>;
    static ESM_EVAL_RETURNS_EXPORTS_NAME: string;
    static FOREIGN_HASH_PROPERTIES: OptionKey<boolean>;
    static FOREIGN_HASH_PROPERTIES_NAME: string;
    static FOREIGN_OBJECT_PROTOTYPE: OptionKey<boolean>;
    static FOREIGN_OBJECT_PROTOTYPE_NAME: string;
    static FREQUENCY_BASED_PROPERTY_CACHE_LIMIT: OptionKey<number>;
    static FREQUENCY_BASED_PROPERTY_CACHE_LIMIT_NAME: string;
    static FUNCTION_ARGUMENTS_LIMIT: OptionKey<number>;
    static FUNCTION_ARGUMENTS_LIMIT_NAME: string;
    static FUNCTION_CACHE_LIMIT: OptionKey<number>;
    static FUNCTION_CACHE_LIMIT_NAME: string;
    static FUNCTION_CONSTRUCTOR_CACHE_SIZE: OptionKey<number>;
    static FUNCTION_CONSTRUCTOR_CACHE_SIZE_NAME: string;
    static FUNCTION_STATEMENT_ERROR: OptionKey<boolean>;
    static FUNCTION_STATEMENT_ERROR_NAME: string;
    static GLOBAL_ARGUMENTS: OptionKey<boolean>;
    static GLOBAL_ARGUMENTS_NAME: string;
    static GLOBAL_PROPERTY: OptionKey<boolean>;
    static GLOBAL_PROPERTY_NAME: string;
    static GRAAL_BUILTIN: OptionKey<boolean>;
    static GRAAL_BUILTIN_NAME: string;
    static IMPORT_ASSERTIONS: OptionKey<boolean>;
    static IMPORT_ASSERTIONS_NAME: string;
    static IMPORT_ATTRIBUTES: OptionKey<boolean>;
    static IMPORT_ATTRIBUTES_NAME: string;
    static INTEROP_COMPLETE_PROMISES: OptionKey<boolean>;
    static INTEROP_COMPLETE_PROMISES_NAME: string;
    static INTL_402: OptionKey<boolean>;
    static INTL_402_NAME: string;
    static ITERATOR_HELPERS: OptionKey<boolean>;
    static ITERATOR_HELPERS_NAME: string;
    static JAVA_PACKAGE_GLOBALS: OptionKey<boolean>;
    static JAVA_PACKAGE_GLOBALS_NAME: string;
    static JSON_MODULES: OptionKey<boolean>;
    static JSON_MODULES_NAME: string;
    static JS_OPTION_PREFIX: string;
    static LAZY_TRANSLATION: OptionKey<boolean>;
    static LAZY_TRANSLATION_NAME: string;
    static LOAD: OptionKey<boolean>;
    static LOAD_FROM_CLASSPATH: OptionKey<boolean>;
    static LOAD_FROM_CLASSPATH_NAME: string;
    static LOAD_FROM_URL: OptionKey<boolean>;
    static LOAD_FROM_URL_NAME: string;
    static LOAD_NAME: string;
    static LOCALE: OptionKey<string>;
    static LOCALE_NAME: string;
    static MAX_APPLY_ARGUMENT_LENGTH: OptionKey<number>;
    static MAX_APPLY_ARGUMENT_LENGTH_NAME: string;
    static MAX_PROTOTYPE_CHAIN_LENGTH: OptionKey<number>;
    static MAX_PROTOTYPE_CHAIN_LENGTH_NAME: string;
    static MAX_TYPED_ARRAY_LENGTH: OptionKey<number>;
    static MAX_TYPED_ARRAY_LENGTH_NAME: string;
    static MLE_MODE: OptionKey<boolean>;
    static MLE_MODE_NAME: string;
    static MLE_PROPERTY_NAME: string;
    static NASHORN_COMPATIBILITY_MODE: OptionKey<boolean>;
    static NASHORN_COMPATIBILITY_MODE_NAME: string;
    static NEW_SET_METHODS: OptionKey<boolean>;
    static NEW_SET_METHODS_NAME: string;
    static OPERATOR_OVERLOADING: OptionKey<boolean>;
    static OPERATOR_OVERLOADING_NAME: string;
    static PARSE_ONLY: OptionKey<boolean>;
    static PARSE_ONLY_NAME: string;
    static PERFORMANCE: OptionKey<boolean>;
    static PERFORMANCE_NAME: string;
    static POLYGLOT_BUILTIN: OptionKey<boolean>;
    static POLYGLOT_BUILTIN_NAME: string;
    static POLYGLOT_EVALFILE: OptionKey<boolean>;
    static POLYGLOT_EVALFILE_NAME: string;
    static PRINT: OptionKey<boolean>;
    static PRINT_NAME: string;
    static PRINT_NO_NEWLINE: OptionKey<boolean>;
    static PRINT_NO_NEWLINE_NAME: string;
    static PRIVATE_FIELDS_IN: OptionKey<boolean>;
    static PRIVATE_FIELDS_IN_NAME: string;
    static PROFILE_TIME: OptionKey<boolean>;
    static PROFILE_TIME_NAME: string;
    static PROFILE_TIME_PRINT_CUMULATIVE: OptionKey<boolean>;
    static PROFILE_TIME_PRINT_CUMULATIVE_NAME: string;
    static PROPERTY_CACHE_LIMIT: OptionKey<number>;
    static PROPERTY_CACHE_LIMIT_NAME: string;
    static REGEXP_MATCH_INDICES: OptionKey<boolean>;
    static REGEXP_MATCH_INDICES_NAME: string;
    static REGEXP_STATIC_RESULT: OptionKey<boolean>;
    static REGEXP_STATIC_RESULT_NAME: string;
    static REGEXP_UNICODE_SETS: OptionKey<boolean>;
    static REGEXP_UNICODE_SETS_NAME: string;
    static REGEX_ALWAYS_EAGER: OptionKey<boolean>;
    static REGEX_ALWAYS_EAGER_NAME: string;
    static REGEX_CACHE_SIZE: OptionKey<number>;
    static REGEX_CACHE_SIZE_NAME: string;
    static REGEX_DUMP_AUTOMATA: OptionKey<boolean>;
    static REGEX_DUMP_AUTOMATA_NAME: string;
    static REGEX_REGRESSION_TEST_MODE: OptionKey<boolean>;
    static REGEX_REGRESSION_TEST_MODE_NAME: string;
    static REGEX_STEP_EXECUTION: OptionKey<boolean>;
    static REGEX_STEP_EXECUTION_NAME: string;
    static SCOPE_OPTIMIZATION: OptionKey<boolean>;
    static SCOPE_OPTIMIZATION_NAME: string;
    static SCRIPTING: OptionKey<boolean>;
    static SCRIPTING_NAME: string;
    static SCRIPT_ENGINE_GLOBAL_SCOPE_IMPORT: OptionKey<boolean>;
    static SCRIPT_ENGINE_GLOBAL_SCOPE_IMPORT_NAME: string;
    static SHADOW_REALM: OptionKey<boolean>;
    static SHADOW_REALM_NAME: string;
    static SHARED_ARRAY_BUFFER: OptionKey<boolean>;
    static SHARED_ARRAY_BUFFER_NAME: string;
    static SHEBANG: OptionKey<boolean>;
    static SHEBANG_NAME: string;
    static SHELL: OptionKey<boolean>;
    static SHELL_NAME: string;
    static SOURCE_PHASE_IMPORTS: OptionKey<boolean>;
    static SOURCE_PHASE_IMPORTS_NAME: string;
    static STACK_TRACE_API: OptionKey<boolean>;
    static STACK_TRACE_API_NAME: string;
    static STACK_TRACE_LIMIT: OptionKey<number>;
    static STACK_TRACE_LIMIT_NAME: string;
    static STRICT: OptionKey<boolean>;
    static STRICT_NAME: string;
    static STRING_LAZY_SUBSTRINGS: OptionKey<boolean>;
    static STRING_LAZY_SUBSTRINGS_NAME: string;
    static STRING_LENGTH_LIMIT: OptionKey<number>;
    static STRING_LENGTH_LIMIT_NAME: string;
    static SYNTAX_EXTENSIONS: OptionKey<boolean>;
    static SYNTAX_EXTENSIONS_NAME: string;
    static TEMPORAL: OptionKey<boolean>;
    static TEMPORAL_NAME: string;
    static TEST262_MODE: OptionKey<boolean>;
    static TEST262_MODE_NAME: string;
    static TESTV8_MODE: OptionKey<boolean>;
    static TESTV8_MODE_NAME: string;
    static TEST_CLONE_UNINITIALIZED: OptionKey<boolean>;
    static TEST_CLONE_UNINITIALIZED_NAME: string;
    static TEXT_ENCODING: OptionKey<boolean>;
    static TEXT_ENCODING_NAME: string;
    static TIMER_RESOLUTION: OptionKey<number>;
    static TIMER_RESOLUTION_NAME: string;
    static TIME_ZONE: OptionKey<string>;
    static TIME_ZONE_NAME: string;
    static TOP_LEVEL_AWAIT_NAME: string;
    static UNHANDLED_REJECTIONS: OptionKey<JSContextOptions$UnhandledRejectionsTrackingMode>;
    static UNHANDLED_REJECTIONS_NAME: string;
    static USE_UTC_FOR_LEGACY_DATES: OptionKey<boolean>;
    static USE_UTC_FOR_LEGACY_DATES_NAME: string;
    static V8_COMPATIBILITY_MODE: OptionKey<boolean>;
    static V8_COMPATIBILITY_MODE_NAME: string;
    static V8_INTRINSICS: OptionKey<boolean>;
    static V8_INTRINSICS_NAME: string;
    static V8_REALM_BUILTIN: OptionKey<boolean>;
    static V8_REALM_BUILTIN_NAME: string;
    static VALIDATE_REGEXP_LITERALS: OptionKey<boolean>;
    static VALIDATE_REGEXP_LITERALS_NAME: string;
    static WASM_BIG_INT: OptionKey<boolean>;
    static WASM_BIG_INT_NAME: string;
    static WEBASSEMBLY: OptionKey<boolean>;
    static WEBASSEMBLY_NAME: string;
    static WORKER: OptionKey<boolean>;
    static WORKER_NAME: string;
    static ZONE_RULES_BASED_TIME_ZONES: OptionKey<boolean>;
    static ZONE_RULES_BASED_TIME_ZONES_NAME: string;
    static fromOptionValues(paramsandboxPolicy: SandboxPolicy, paramoptionValues: OptionValues): JSContextOptions;
    static optionDescriptorsWithDefaultValues(): (Object | null)[];
    constructor(sandboxPolicy: SandboxPolicy, optionValues: OptionValues)
    // private agentCanBlock: boolean;
    // private allowEval: boolean;
    // private allowNarrowSpacesInDateFormat: boolean;
    readonly annexB: boolean;
    readonly arrayElementsAmongMembers: boolean;
    readonly asyncContext: boolean;
    readonly asyncIteratorHelpers: boolean;
    readonly asyncStackTraces: boolean;
    readonly atomicsWaitAsync: boolean;
    readonly awaitOptimization: boolean;
    // private bindMemberFunctions: boolean;
    readonly commonJSRequire: boolean;
    // private debug: boolean;
    readonly directByteBuffer: boolean;
    readonly disableWith: boolean;
    // private ecmascriptVersion: number;
    // private errorCause: boolean;
    readonly esmBareSpecifierRelativeLookup: boolean;
    readonly esmEvalReturnsExports: boolean;
    readonly frequencyBasedPropertyCacheLimit: number;
    readonly functionArgumentsLimit: number;
    readonly functionCacheLimit: number;
    readonly functionConstructorCacheSize: number;
    // private hasForeignHashProperties: boolean;
    // private hasForeignObjectPrototype: boolean;
    readonly importAssertions: boolean;
    readonly importAttributes: boolean;
    readonly intl402: boolean;
    readonly iteratorHelpers: boolean;
    readonly jsonModules: boolean;
    readonly lazyTranslation: boolean;
    readonly maxApplyArgumentLength: number;
    readonly maxPrototypeChainLength: number;
    readonly maxTypedArrayLength: number;
    // private mleMode: boolean;
    readonly nashornCompatibilityMode: boolean;
    readonly newSetMethods: boolean;
    readonly operatorOverloading: boolean;
    // private optionValues: OptionValues;
    readonly parseOnly: boolean;
    readonly printNoNewline: boolean;
    readonly privateFieldsIn: boolean;
    readonly propertyCacheLimit: number;
    readonly regexAlwaysEager: boolean;
    readonly regexCacheSize: number;
    readonly regexDumpAutomata: boolean;
    readonly regexRegressionTestMode: boolean;
    readonly regexStepExecution: boolean;
    readonly regexpMatchIndices: boolean;
    readonly regexpStaticResult: boolean;
    readonly regexpUnicodeSets: boolean;
    readonly scopeOptimization: boolean;
    readonly scriptEngineGlobalScopeImport: boolean;
    readonly shadowRealm: boolean;
    readonly sharedArrayBuffer: boolean;
    readonly sourcePhaseImports: boolean;
    readonly stackTraceAPI: boolean;
    readonly stackTraceLimit: number;
    readonly stringLazySubstrings: boolean;
    readonly stringLengthLimit: number;
    readonly temporal: boolean;
    readonly test262Mode: boolean;
    readonly testCloneUninitialized: boolean;
    readonly testV8Mode: boolean;
    readonly textEncoding: boolean;
    readonly timerResolution: number;
    readonly topLevelAwait: boolean;
    readonly unhandledRejectionsMode: JSContextOptions$UnhandledRejectionsTrackingMode;
    // private useUTCForLegacyDates: boolean;
    readonly v8CompatibilityMode: boolean;
    readonly v8Intrinsics: boolean;
    readonly v8RealmBuiltin: boolean;
    readonly validateRegExpLiterals: boolean;
    readonly wasmBigInt: boolean;
    readonly webAssembly: boolean;
    readonly worker: boolean;
    // private zoneRulesBasedTimeZones: boolean;
    allowEval(): boolean;
    allowNarrowSpacesInDateFormat(): boolean;
    bindMemberFunctions(): boolean;
    // private cacheOptions(sandboxPolicy: SandboxPolicy): void;
    canAgentBlock(): boolean;
    getCharset(): string;
    getCommonJSRequireBuiltins(): { [key: string]: string };
    getDebugPropertyName(): string;
    getEcmaScriptVersion(): number;
    getFrequencyBasedPropertyCacheLimit(): number;
    getFunctionArgumentsLimit(): number;
    getFunctionCacheLimit(): number;
    getFunctionConstructorCacheSize(): number;
    getLocale(): string;
    getMaxApplyArgumentLength(): number;
    getMaxPrototypeChainLength(): number;
    getMaxTypedArrayLength(): number;
    getPropertyCacheLimit(): number;
    getRegexCacheSize(): number;
    getRequireCwd(): string;
    getStackTraceLimit(): number;
    getStringLengthLimit(): number;
    getTimerResolution(): number;
    getUnhandledRejectionsMode(): JSContextOptions$UnhandledRejectionsTrackingMode;
    hasForeignHashProperties(): boolean;
    hasForeignObjectPrototype(): boolean;
    hasZoneRulesBasedTimeZones(): boolean;
    isAnnexB(): boolean;
    isArrayElementsAmongMembers(): boolean;
    isAsyncContext(): boolean;
    isAsyncIteratorHelpers(): boolean;
    isAsyncStackTraces(): boolean;
    isAtomics(): boolean;
    isAtomicsWaitAsync(): boolean;
    isAwaitOptimization(): boolean;
    isBigInt(): boolean;
    isClassFields(): boolean;
    isCommonJSRequire(): boolean;
    isConsole(): boolean;
    isConstAsVar(): boolean;
    isDebugBuiltin(): boolean;
    isDirectByteBuffer(): boolean;
    isDisableWith(): boolean;
    isErrorCauseEnabled(): boolean;
    isEsmBareSpecifierRelativeLookup(): boolean;
    isEsmEvalReturnsExports(): boolean;
    isFunctionStatementError(): boolean;
    isGlobalArguments(): boolean;
    isGlobalProperty(): boolean;
    isGraalBuiltin(): boolean;
    isImportAssertions(): boolean;
    isImportAttributes(): boolean;
    isIntl402(): boolean;
    isIteratorHelpers(): boolean;
    isJsonModules(): boolean;
    isLazyTranslation(): boolean;
    isLoad(): boolean;
    isLoadFromClasspath(): boolean;
    isLoadFromURL(): boolean;
    isMLEMode(): boolean;
    isNashornCompatibilityMode(): boolean;
    isNewSetMethods(): boolean;
    isOperatorOverloading(): boolean;
    isParseOnly(): boolean;
    isPerformance(): boolean;
    isPolyglotBuiltin(): boolean;
    isPolyglotEvalFile(): boolean;
    isPrint(): boolean;
    isPrintNoNewline(): boolean;
    isPrivateFieldsIn(): boolean;
    isProfileTime(): boolean;
    isProfileTimePrintCumulative(): boolean;
    isRegexAlwaysEager(): boolean;
    isRegexDumpAutomata(): boolean;
    isRegexRegressionTestMode(): boolean;
    isRegexStepExecution(): boolean;
    isRegexpMatchIndices(): boolean;
    isRegexpStaticResult(): boolean;
    isRegexpUnicodeSets(): boolean;
    isScopeOptimization(): boolean;
    isScriptEngineGlobalScopeImport(): boolean;
    isScripting(): boolean;
    isShadowRealm(): boolean;
    isSharedArrayBuffer(): boolean;
    isShebang(): boolean;
    isShell(): boolean;
    isSourcePhaseImports(): boolean;
    isStackTraceAPI(): boolean;
    isStrict(): boolean;
    isStringLazySubstrings(): boolean;
    isSyntaxExtensions(): boolean;
    isTemporal(): boolean;
    isTest262Mode(): boolean;
    isTestCloneUninitialized(): boolean;
    isTestV8Mode(): boolean;
    isTextEncoding(): boolean;
    isTopLevelAwait(): boolean;
    isV8CompatibilityMode(): boolean;
    isV8Intrinsics(): boolean;
    isV8RealmBuiltin(): boolean;
    isValidateRegExpLiterals(): boolean;
    isWasmBigInt(): boolean;
    isWebAssembly(): boolean;
    isWorker(): boolean;
    // private readBooleanOption(key: OptionKey<boolean>): boolean;
    // private readBooleanOption(key: OptionKey<boolean>, finishedESVersion: number): boolean;
    // private readIntegerOption(key: OptionKey<number>): number;
    // private readLongOption(key: OptionKey<number>): number;
    // private readUnhandledRejectionsMode(): JSContextOptions$UnhandledRejectionsTrackingMode;
    setOptionValues(sandboxPolicy: SandboxPolicy, newOptions: OptionValues): void;
    shouldUseUTCForLegacyDates(): boolean;
}