import type { JSContextOptions } from '../../../../../com/oracle/truffle/js/runtime/JSContextOptions.d.ts'
import type { JSContextOptions$UnhandledRejectionsTrackingMode } from '../../../../../com/oracle/truffle/js/runtime/JSContextOptions$UnhandledRejectionsTrackingMode.d.ts'
import type { Record } from '../../../../../java/lang/Record.d.ts'
import type { Object } from '../../../../../java/lang/Object.d.ts'
import type { OptionValues } from '../../../../../org/graalvm/options/OptionValues.d.ts'
import type { SandboxPolicy } from '../../../../../org/graalvm/polyglot/SandboxPolicy.d.ts'
export class JSLanguageOptions extends Record {
    static fromContextOptions(paramoptions: JSContextOptions): JSLanguageOptions;
    static fromOptionValues(paramsandboxPolicy: SandboxPolicy, paramoptionValues: OptionValues): JSLanguageOptions;
    constructor(ecmaScriptVersion: number, strict: boolean, annexB: boolean, intl402: boolean, regexpMatchIndices: boolean, regexpUnicodeSets: boolean, sharedArrayBuffer: boolean, v8RealmBuiltin: boolean, nashornCompatibilityMode: boolean, stackTraceLimit: number, parseOnly: boolean, zoneRulesBasedTimeZones: boolean, agentCanBlock: boolean, printNoNewline: boolean, commonJSRequire: boolean, awaitOptimization: boolean, allowEval: boolean, disableWith: boolean, regexDumpAutomata: boolean, regexStepExecution: boolean, regexAlwaysEager: boolean, scriptEngineGlobalScopeImport: boolean, hasForeignObjectPrototype: boolean, hasForeignHashProperties: boolean, functionArgumentsLimit: number, test262Mode: boolean, testV8Mode: boolean, validateRegExpLiterals: boolean, functionConstructorCacheSize: number, regexCacheSize: number, stringLengthLimit: number, stringLazySubstrings: boolean, bindMemberFunctions: boolean, regexRegressionTestMode: boolean, testCloneUninitialized: boolean, lazyTranslation: boolean, maxTypedArrayLength: number, maxApplyArgumentLength: number, maxPrototypeChainLength: number, asyncStackTraces: boolean, propertyCacheLimit: number, functionCacheLimit: number, frequencyBasedPropertyCacheLimit: number, topLevelAwait: boolean, useUTCForLegacyDates: boolean, webAssembly: boolean, newSetMethods: boolean, temporal: boolean, iteratorHelpers: boolean, asyncIteratorHelpers: boolean, shadowRealm: boolean, asyncContext: boolean, explicitResourceManagement: boolean, v8Intrinsics: boolean, unhandledRejectionsMode: JSContextOptions$UnhandledRejectionsTrackingMode, operatorOverloading: boolean, errorCause: boolean, importAttributes: boolean, jsonModules: boolean, sourcePhaseImports: boolean, wasmBigInt: boolean, esmEvalReturnsExports: boolean, isMLEMode: boolean, privateFieldsIn: boolean, esmBareSpecifierRelativeLookup: boolean, scopeOptimization: boolean, bigInt: boolean, classFields: boolean, shebang: boolean, syntaxExtensions: boolean, scripting: boolean, functionStatementError: boolean, constAsVar: boolean, profileTime: boolean, arrayElementsAmongMembers: boolean, errorStackAccessor: boolean, stackTraceAPI: boolean, worker: boolean, locale: string)
    // private agentCanBlock: boolean;
    // private allowEval: boolean;
    // private annexB: boolean;
    // private arrayElementsAmongMembers: boolean;
    // private asyncContext: boolean;
    // private asyncIteratorHelpers: boolean;
    // private asyncStackTraces: boolean;
    // private awaitOptimization: boolean;
    // private bigInt: boolean;
    // private bindMemberFunctions: boolean;
    // private classFields: boolean;
    // private commonJSRequire: boolean;
    // private constAsVar: boolean;
    // private disableWith: boolean;
    // private ecmaScriptVersion: number;
    // private errorCause: boolean;
    // private errorStackAccessor: boolean;
    // private esmBareSpecifierRelativeLookup: boolean;
    // private esmEvalReturnsExports: boolean;
    // private explicitResourceManagement: boolean;
    // private frequencyBasedPropertyCacheLimit: number;
    // private functionArgumentsLimit: number;
    // private functionCacheLimit: number;
    // private functionConstructorCacheSize: number;
    // private functionStatementError: boolean;
    // private hasForeignHashProperties: boolean;
    // private hasForeignObjectPrototype: boolean;
    // private importAttributes: boolean;
    // private intl402: boolean;
    // private isMLEMode: boolean;
    // private iteratorHelpers: boolean;
    // private jsonModules: boolean;
    // private lazyTranslation: boolean;
    // private locale: string;
    // private maxApplyArgumentLength: number;
    // private maxPrototypeChainLength: number;
    // private maxTypedArrayLength: number;
    // private nashornCompatibilityMode: boolean;
    // private newSetMethods: boolean;
    // private operatorOverloading: boolean;
    // private parseOnly: boolean;
    // private printNoNewline: boolean;
    // private privateFieldsIn: boolean;
    // private profileTime: boolean;
    // private propertyCacheLimit: number;
    // private regexAlwaysEager: boolean;
    // private regexCacheSize: number;
    // private regexDumpAutomata: boolean;
    // private regexRegressionTestMode: boolean;
    // private regexStepExecution: boolean;
    // private regexpMatchIndices: boolean;
    // private regexpUnicodeSets: boolean;
    // private scopeOptimization: boolean;
    // private scriptEngineGlobalScopeImport: boolean;
    // private scripting: boolean;
    // private shadowRealm: boolean;
    // private sharedArrayBuffer: boolean;
    // private shebang: boolean;
    // private sourcePhaseImports: boolean;
    // private stackTraceAPI: boolean;
    // private stackTraceLimit: number;
    // private strict: boolean;
    // private stringLazySubstrings: boolean;
    // private stringLengthLimit: number;
    // private syntaxExtensions: boolean;
    // private temporal: boolean;
    // private test262Mode: boolean;
    // private testCloneUninitialized: boolean;
    // private testV8Mode: boolean;
    // private topLevelAwait: boolean;
    // private unhandledRejectionsMode: JSContextOptions$UnhandledRejectionsTrackingMode;
    // private useUTCForLegacyDates: boolean;
    // private v8Intrinsics: boolean;
    // private v8RealmBuiltin: boolean;
    // private validateRegExpLiterals: boolean;
    // private wasmBigInt: boolean;
    // private webAssembly: boolean;
    // private worker: boolean;
    // private zoneRulesBasedTimeZones: boolean;
    agentCanBlock(): boolean;
    allowEval(): boolean;
    annexB(): boolean;
    arrayElementsAmongMembers(): boolean;
    asyncContext(): boolean;
    asyncIteratorHelpers(): boolean;
    asyncStackTraces(): boolean;
    awaitOptimization(): boolean;
    bigInt(): boolean;
    bindMemberFunctions(): boolean;
    classFields(): boolean;
    commonJSRequire(): boolean;
    constAsVar(): boolean;
    disableWith(): boolean;
    ecmaScriptVersion(): number;
    equals(o: Object | null): boolean;
    errorCause(): boolean;
    errorStackAccessor(): boolean;
    esmBareSpecifierRelativeLookup(): boolean;
    esmEvalReturnsExports(): boolean;
    explicitResourceManagement(): boolean;
    frequencyBasedPropertyCacheLimit(): number;
    functionArgumentsLimit(): number;
    functionCacheLimit(): number;
    functionConstructorCacheSize(): number;
    functionStatementError(): boolean;
    hasForeignHashProperties(): boolean;
    hasForeignObjectPrototype(): boolean;
    hashCode(): number;
    importAttributes(): boolean;
    intl402(): boolean;
    isMLEMode(): boolean;
    iteratorHelpers(): boolean;
    jsonModules(): boolean;
    lazyTranslation(): boolean;
    locale(): string;
    maxApplyArgumentLength(): number;
    maxPrototypeChainLength(): number;
    maxTypedArrayLength(): number;
    nashornCompatibilityMode(): boolean;
    newSetMethods(): boolean;
    operatorOverloading(): boolean;
    parseOnly(): boolean;
    printNoNewline(): boolean;
    privateFieldsIn(): boolean;
    profileTime(): boolean;
    propertyCacheLimit(): number;
    regexAlwaysEager(): boolean;
    regexCacheSize(): number;
    regexDumpAutomata(): boolean;
    regexRegressionTestMode(): boolean;
    regexStepExecution(): boolean;
    regexpMatchIndices(): boolean;
    regexpUnicodeSets(): boolean;
    scopeOptimization(): boolean;
    scriptEngineGlobalScopeImport(): boolean;
    scripting(): boolean;
    shadowRealm(): boolean;
    sharedArrayBuffer(): boolean;
    shebang(): boolean;
    sourcePhaseImports(): boolean;
    stackTraceAPI(): boolean;
    stackTraceLimit(): number;
    strict(): boolean;
    stringLazySubstrings(): boolean;
    stringLengthLimit(): number;
    syntaxExtensions(): boolean;
    temporal(): boolean;
    test262Mode(): boolean;
    testCloneUninitialized(): boolean;
    testV8Mode(): boolean;
    toString(): string;
    topLevelAwait(): boolean;
    unhandledRejectionsMode(): JSContextOptions$UnhandledRejectionsTrackingMode;
    useUTCForLegacyDates(): boolean;
    v8Intrinsics(): boolean;
    v8RealmBuiltin(): boolean;
    validateRegExpLiterals(): boolean;
    wasmBigInt(): boolean;
    webAssembly(): boolean;
    worker(): boolean;
    zoneRulesBasedTimeZones(): boolean;
}