import type { InteropLibrary } from '../../../../../com/oracle/truffle/api/interop/InteropLibrary.d.ts'
import type { TruffleString } from '../../../../../com/oracle/truffle/api/strings/TruffleString.d.ts'
import type { TruffleString$ByteIndexOfCodePointNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$ByteIndexOfCodePointNode.d.ts'
import type { TruffleString$ByteIndexOfStringNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$ByteIndexOfStringNode.d.ts'
import type { TruffleString$ByteLengthOfCodePointNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$ByteLengthOfCodePointNode.d.ts'
import type { TruffleString$CharIndexOfAnyCharUTF16Node } from '../../../../../com/oracle/truffle/api/strings/TruffleString$CharIndexOfAnyCharUTF16Node.d.ts'
import type { TruffleString$CodePointAtByteIndexNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$CodePointAtByteIndexNode.d.ts'
import type { TruffleString$CompareCharsUTF16Node } from '../../../../../com/oracle/truffle/api/strings/TruffleString$CompareCharsUTF16Node.d.ts'
import type { TruffleString$ConcatNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$ConcatNode.d.ts'
import type { TruffleString$EqualNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$EqualNode.d.ts'
import type { TruffleString$FromCharArrayUTF16Node } from '../../../../../com/oracle/truffle/api/strings/TruffleString$FromCharArrayUTF16Node.d.ts'
import type { TruffleString$FromCodePointNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$FromCodePointNode.d.ts'
import type { TruffleString$FromJavaStringNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$FromJavaStringNode.d.ts'
import type { TruffleString$FromLongNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$FromLongNode.d.ts'
import type { TruffleString$LastByteIndexOfCodePointNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$LastByteIndexOfCodePointNode.d.ts'
import type { TruffleString$LastByteIndexOfStringNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$LastByteIndexOfStringNode.d.ts'
import type { TruffleString$MaterializeNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$MaterializeNode.d.ts'
import type { TruffleString$ParseDoubleNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$ParseDoubleNode.d.ts'
import type { TruffleString$ParseLongNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$ParseLongNode.d.ts'
import type { TruffleString$ReadCharUTF16Node } from '../../../../../com/oracle/truffle/api/strings/TruffleString$ReadCharUTF16Node.d.ts'
import type { TruffleString$RegionEqualByteIndexNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$RegionEqualByteIndexNode.d.ts'
import type { TruffleString$SubstringByteIndexNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$SubstringByteIndexNode.d.ts'
import type { TruffleString$SwitchEncodingNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$SwitchEncodingNode.d.ts'
import type { TruffleString$ToJavaStringNode } from '../../../../../com/oracle/truffle/api/strings/TruffleString$ToJavaStringNode.d.ts'
import type { TruffleStringBuilder$AppendCharUTF16Node } from '../../../../../com/oracle/truffle/api/strings/TruffleStringBuilder$AppendCharUTF16Node.d.ts'
import type { TruffleStringBuilder$AppendCodePointNode } from '../../../../../com/oracle/truffle/api/strings/TruffleStringBuilder$AppendCodePointNode.d.ts'
import type { TruffleStringBuilder$AppendIntNumberNode } from '../../../../../com/oracle/truffle/api/strings/TruffleStringBuilder$AppendIntNumberNode.d.ts'
import type { TruffleStringBuilder$AppendJavaStringUTF16Node } from '../../../../../com/oracle/truffle/api/strings/TruffleStringBuilder$AppendJavaStringUTF16Node.d.ts'
import type { TruffleStringBuilder$AppendLongNumberNode } from '../../../../../com/oracle/truffle/api/strings/TruffleStringBuilder$AppendLongNumberNode.d.ts'
import type { TruffleStringBuilder$AppendStringNode } from '../../../../../com/oracle/truffle/api/strings/TruffleStringBuilder$AppendStringNode.d.ts'
import type { TruffleStringBuilder$AppendSubstringByteIndexNode } from '../../../../../com/oracle/truffle/api/strings/TruffleStringBuilder$AppendSubstringByteIndexNode.d.ts'
import type { TruffleStringBuilder$ToStringNode } from '../../../../../com/oracle/truffle/api/strings/TruffleStringBuilder$ToStringNode.d.ts'
import type { TruffleStringBuilderUTF16 } from '../../../../../com/oracle/truffle/api/strings/TruffleStringBuilderUTF16.d.ts'
import type { BigInt } from '../../../../../com/oracle/truffle/js/runtime/BigInt.d.ts'
import type { JSContext } from '../../../../../com/oracle/truffle/js/runtime/JSContext.d.ts'
import type { BigInteger } from '../../../../../java/math/BigInteger.d.ts'
import type { Locale } from '../../../../../java/util/Locale.d.ts'
import type { Object } from '../../../../../java/lang/Object.d.ts'
import type { Number } from '../../../../../java/lang/Number.d.ts'
export class Strings extends Object {
    static $_ARG: TruffleString;
    static $_ERR: TruffleString;
    static $_EXEC: TruffleString;
    static $_EXIT: TruffleString;
    static $_OPTIONS: TruffleString;
    static $_OUT: TruffleString;
    static A: TruffleString;
    static ACCESSOR: TruffleString;
    static ADD: TruffleString;
    static AGENT: TruffleString;
    static AGENT_BROADCAST: TruffleString;
    static AGENT_GET_REPORT: TruffleString;
    static AGENT_LEAVING: TruffleString;
    static AGENT_RECEIVE_BROADCAST: TruffleString;
    static AGENT_REPORT: TruffleString;
    static AGENT_SLEEP: TruffleString;
    static AGENT_START: TruffleString;
    static ALL: TruffleString;
    static ALPHABET: TruffleString;
    static ANGLE_BRACKET_CLOSE: TruffleString;
    static ANGLE_BRACKET_CLOSE_2: TruffleString;
    static ANGLE_BRACKET_CLOSE_3: TruffleString;
    static ANGLE_BRACKET_OPEN: TruffleString;
    static ANGLE_BRACKET_OPEN_2: TruffleString;
    static ANGLE_BRACKET_OPEN_SLASH: TruffleString;
    static ANY: TruffleString;
    static APPLY: TruffleString;
    static ARGUMENTS: TruffleString;
    static ARRAY_PAREN_OPEN: TruffleString;
    static ASYNC: TruffleString;
    static ASYNC_ITERATOR: TruffleString;
    static ASYNC_PROMISE_ALL_BEGIN: TruffleString;
    static ASYNC_SPC: TruffleString;
    static AT: TruffleString;
    static B: TruffleString;
    static BACKSLASH: TruffleString;
    static BACKSLASH_B: TruffleString;
    static BACKSLASH_BACKSLASH: TruffleString;
    static BACKSLASH_DOUBLE_QUOTE: TruffleString;
    static BACKSLASH_F: TruffleString;
    static BACKSLASH_N: TruffleString;
    static BACKSLASH_R: TruffleString;
    static BACKSLASH_T: TruffleString;
    static BACKSLASH_U: TruffleString;
    static BACKSLASH_U00: TruffleString;
    static BACKSLASH_UD: TruffleString;
    static BIG: TruffleString;
    static BIG_ARROW_SPACES: TruffleString;
    static BLINK: TruffleString;
    static BOOLEAN_PROTOTYPE: TruffleString;
    static BOUND: TruffleString;
    static BOUND_SPC: TruffleString;
    static BRACKET_BOOLEAN_SPC: TruffleString;
    static BRACKET_CLOSE: TruffleString;
    static BRACKET_CLOSE_2_COLON: TruffleString;
    static BRACKET_DATE_SPC: TruffleString;
    static BRACKET_OBJECT_SPC: TruffleString;
    static BRACKET_OPEN: TruffleString;
    static BRACKET_OPEN_2: TruffleString;
    static BRACKET_SYMBOL_DOT: TruffleString;
    static BROADCAST: TruffleString;
    static CALENDAR: TruffleString;
    static CALL: TruffleString;
    static CALLEE: TruffleString;
    static CALLER: TruffleString;
    static CAPS_EPSILON: TruffleString;
    static CAPS_ID: TruffleString;
    static CAPS_MAX_SAFE_INTEGER: TruffleString;
    static CAPS_MAX_VALUE: TruffleString;
    static CAPS_MIN_SAFE_INTEGER: TruffleString;
    static CAPS_MIN_VALUE: TruffleString;
    static CAPS_NEGATIVE_INFINITY: TruffleString;
    static CAPS_POSITIVE_INFINITY: TruffleString;
    static CAPS_PWD: TruffleString;
    static CAUSE: TruffleString;
    static CLOSE: TruffleString;
    static COLON: TruffleString;
    static COLON_SPACE: TruffleString;
    static COLOR: TruffleString;
    static COM: TruffleString;
    static COMMA: TruffleString;
    static COMMA_ANONYMOUS_BRACKETS: TruffleString;
    static COMMA_NEWLINE: TruffleString;
    static COMMA_SPC: TruffleString;
    static COMPARE: TruffleString;
    static CONSOLE: TruffleString;
    static CONSTRUCT: TruffleString;
    static COPY_WITHIN: TruffleString;
    static CREATE_REALM: TruffleString;
    static DASH: TruffleString;
    static DAY: TruffleString;
    static DEFAULT: TruffleString;
    static DEFAULT_VALUE: TruffleString;
    static DELETE: TruffleString;
    static DETACH_ARRAY_BUFFER: TruffleString;
    static DIRNAME_VAR_NAME: TruffleString;
    static DOLLAR_ENV: TruffleString;
    static DONE: TruffleString;
    static DOT: TruffleString;
    static DOT_DOT_DOT: TruffleString;
    static DOT_DOT_SLASH: TruffleString;
    static DOT_PROTOTYPE: TruffleString;
    static DOT_SLASH: TruffleString;
    static DOUBLE_QUOTE: TruffleString;
    static DYNAMIC_FUNCTION_NAME: TruffleString;
    static E: TruffleString;
    static EDU: TruffleString;
    static ELEMENT: TruffleString;
    static EMPTY: TruffleString;
    static EMPTY_ARRAY: TruffleString;
    static EMPTY_ARRAY_DOTS: TruffleString;
    static EMPTY_OBJECT: TruffleString;
    static EMPTY_OBJECT_DOTS: TruffleString;
    static EMPTY_STRING: TruffleString;
    static EMPTY_X: TruffleString;
    static ENTRIES: TruffleString;
    static ENV_PROPERTY_NAME: TruffleString;
    static EQUALS_DOUBLE_QUOTE: TruffleString;
    static ERA: TruffleString;
    static EVAL: TruffleString;
    static EVAL_FILE: TruffleString;
    static EVAL_OBJ_FILE_NAME: TruffleString;
    static EVAL_OBJ_SOURCE: TruffleString;
    static EVAL_SCRIPT: TruffleString;
    static EXCLAMATION_MARK: TruffleString;
    static EXEC: TruffleString;
    static EXIT: TruffleString;
    static EXPORTS_PROPERTY_NAME: TruffleString;
    static FALSE: TruffleString;
    static FILE: TruffleString;
    static FILENAME_PROPERTY_NAME: TruffleString;
    static FILENAME_VAR_NAME: TruffleString;
    static FILL: TruffleString;
    static FIND: TruffleString;
    static FIND_INDEX: TruffleString;
    static FIND_LAST: TruffleString;
    static FIND_LAST_INDEX: TruffleString;
    static FLAT: TruffleString;
    static FLAT_MAP: TruffleString;
    static FONT: TruffleString;
    static FORMAT: TruffleString;
    static FRACTIONAL_SECOND_DIGITS: TruffleString;
    static FULFILLED: TruffleString;
    static FUNCTION: TruffleString;
    static FUNCTION_BODY_DOTS: TruffleString;
    static FUNCTION_BODY_OMITTED: TruffleString;
    static FUNCTION_NATIVE_CODE: TruffleString;
    static FUNCTION_NATIVE_CODE_BODY: TruffleString;
    static FUNCTION_SPC: TruffleString;
    static G: TruffleString;
    static GC: TruffleString;
    static GET: TruffleString;
    static GET_DOLLAR_UNDERSCORE: TruffleString;
    static GET_REPORT: TruffleString;
    static GET_SPC: TruffleString;
    static GLOBAL: TruffleString;
    static GLOBAL_THIS: TruffleString;
    static GLOBAL__DIR__: TruffleString;
    static GLOBAL__FILE__: TruffleString;
    static GLOBAL__LINE__: TruffleString;
    static GRAAL: TruffleString;
    static HAS: TruffleString;
    static HAS_INSTANCE: TruffleString;
    static HINT_DEFAULT: TruffleString;
    static HINT_NUMBER: TruffleString;
    static HINT_STRING: TruffleString;
    static HOUR: TruffleString;
    static HREF: TruffleString;
    static HTML_QUOT: TruffleString;
    static I: TruffleString;
    static ID_PROPERTY_NAME: TruffleString;
    static IMPORT_SCRIPT_ENGINE_GLOBAL_BINDINGS: TruffleString;
    static INCLUDES: TruffleString;
    static INDEX: TruffleString;
    static INFINITY: TruffleString;
    static INIT: TruffleString;
    static INITIAL: TruffleString;
    static INPUT: TruffleString;
    static INSTANCE: TruffleString;
    static IS: TruffleString;
    static IS_CONCAT_SPREADABLE: TruffleString;
    static IS_GRAAL_RUNTIME: TruffleString;
    static IS_VIEW: TruffleString;
    static ITERATOR: TruffleString;
    static JAVA: TruffleString;
    static JAVAFX: TruffleString;
    static JAVAX: TruffleString;
    static JAVA_CLASS_BRACKET: TruffleString;
    static JAVA_OBJECT_BRACKET: TruffleString;
    static JOIN: TruffleString;
    static JOIN_JLS: string;
    static JSON: TruffleString;
    static KEY: TruffleString;
    static KEYS: TruffleString;
    static LANGUAGE: TruffleString;
    static LAST_CHUNK_HANDLING: TruffleString;
    static LC_0X: TruffleString;
    static LC_BOOLEAN: TruffleString;
    static LEAVING: TruffleString;
    static LENGTH: TruffleString;
    static LINE_SEPARATOR: TruffleString;
    static LINE_SEPARATOR_JLS: string;
    static LN_10: TruffleString;
    static LN_2: TruffleString;
    static LOAD: TruffleString;
    static LOADED_PROPERTY_NAME: TruffleString;
    static LOAD_WITH_NEW_GLOBAL: TruffleString;
    static LOG_10_E: TruffleString;
    static LOG_2_E: TruffleString;
    static MATCH: TruffleString;
    static MATCH_ALL: TruffleString;
    static MAXIMUM: TruffleString;
    static MEMORY: TruffleString;
    static MESSAGE: TruffleString;
    static MINUTE: TruffleString;
    static MODULE: TruffleString;
    static MODULE_PROPERTY_NAME: TruffleString;
    static MONOTONIC_NOW: TruffleString;
    static MONTH: TruffleString;
    static MS: TruffleString;
    static MUTABLE: TruffleString;
    static N: TruffleString;
    static NAME: TruffleString;
    static NAN: TruffleString;
    static NATIVE: TruffleString;
    static NEG: TruffleString;
    static NEGATIVE_INFINITY: TruffleString;
    static NEGATIVE_ZERO: TruffleString;
    static NEW_SPACE: TruffleString;
    static NEXT: TruffleString;
    static NFC: TruffleString;
    static NFD: TruffleString;
    static NFKC: TruffleString;
    static NFKD: TruffleString;
    static NOT_EQUAL: TruffleString;
    static NOW: TruffleString;
    static NULL: TruffleString;
    static OBJECT: TruffleString;
    static OK: TruffleString;
    static OMIT_PADDING: TruffleString;
    static ONMESSAGE: TruffleString;
    static ORG: TruffleString;
    static PACKAGE_JSON_MAIN_PROPERTY_NAME: TruffleString;
    static PACKAGE_JSON_TYPE_PROPERTY_NAME: TruffleString;
    static PARENS_THIS: TruffleString;
    static PAREN_CLOSE: TruffleString;
    static PAREN_OPEN: TruffleString;
    static PARSE: TruffleString;
    static PARSE_FLOAT: TruffleString;
    static PARSE_INT: TruffleString;
    static PARSE_TO_JSON: TruffleString;
    static PENDING: TruffleString;
    static PI: TruffleString;
    static POS: TruffleString;
    static POSITIVE_INFINITY: TruffleString;
    static POST_MESSAGE: TruffleString;
    static PRIMITIVE_VALUE: TruffleString;
    static PRINT: TruffleString;
    static PRINT_ERR: TruffleString;
    static PRIVATE: TruffleString;
    static PROMISE: TruffleString;
    static PROMISE_STATUS: TruffleString;
    static PROMISE_VALUE: TruffleString;
    static PROXY: TruffleString;
    static PROXY_PAREN: TruffleString;
    static QUIT: TruffleString;
    static RAW: TruffleString;
    static RAW_JSON: TruffleString;
    static READ: TruffleString;
    static READ_FULLY: TruffleString;
    static READ_LINE: TruffleString;
    static REASON: TruffleString;
    static RECEIVE_BROADCAST: TruffleString;
    static REGEXP_OTHER_PUNCTUATORS: TruffleString;
    static REGEXP_SYNTAX_CHARS_WITH_SOLIDUS: TruffleString;
    static REJECT: TruffleString;
    static REJECTED: TruffleString;
    static REPLACE: TruffleString;
    static REPORT: TruffleString;
    static REQUIRE_PROPERTY_NAME: TruffleString;
    static RESOLVE: TruffleString;
    static RESOLVED: TruffleString;
    static RESOLVE_PROPERTY_NAME: TruffleString;
    static RETURN: TruffleString;
    static REVOCABLE: TruffleString;
    static REVOKE: TruffleString;
    static ROUNDING_INCREMENT: TruffleString;
    static ROUNDING_MODE: TruffleString;
    static SCRIPT: TruffleString;
    static SEARCH: TruffleString;
    static SECOND: TruffleString;
    static SET: TruffleString;
    static SET_SPC: TruffleString;
    static SET_UNHANDLED_PROMISE_REJECTION_HANDLER: TruffleString;
    static SHARED: TruffleString;
    static SINGLE_QUOTE: TruffleString;
    static SIZE: TruffleString;
    static SLASH: TruffleString;
    static SLEEP: TruffleString;
    static SLICE: TruffleString;
    static SMALL: TruffleString;
    static SOURCE: TruffleString;
    static SPACE: TruffleString;
    static SPACE_PAREN_OPEN: TruffleString;
    static SPECIES: TruffleString;
    static SPLIT: TruffleString;
    static SQRT_1_2: TruffleString;
    static SQRT_2: TruffleString;
    static START: TruffleString;
    static STATIC: TruffleString;
    static STATUS: TruffleString;
    static STRIKE: TruffleString;
    static STRING: TruffleString;
    static STRING_MAX_LENGTH: TruffleString;
    static SUB: TruffleString;
    static SUP: TruffleString;
    static SUPER: TruffleString;
    static SWITCH: TruffleString;
    static SYMBOL: TruffleString;
    static SYMBOL_AMPERSAND: TruffleString;
    static SYMBOL_CARET: TruffleString;
    static SYMBOL_EQUALS_EQUALS: TruffleString;
    static SYMBOL_MINUS: TruffleString;
    static SYMBOL_MINUS_MINUS: TruffleString;
    static SYMBOL_PAREN_OPEN: TruffleString;
    static SYMBOL_PERCENT: TruffleString;
    static SYMBOL_PIPE: TruffleString;
    static SYMBOL_PLUS: TruffleString;
    static SYMBOL_PLUS_PLUS: TruffleString;
    static SYMBOL_STAR: TruffleString;
    static SYMBOL_STAR_STAR: TruffleString;
    static SYMBOL_TILDE: TruffleString;
    static TABLE: TruffleString;
    static TEST: TruffleString;
    static THEN: TruffleString;
    static THIS: TruffleString;
    static THROW: TruffleString;
    static TIMED_OUT: TruffleString;
    static TIME_ZONE: TruffleString;
    static TIME_ZONE_NAME: TruffleString;
    static TO_GMT_STRING: TruffleString;
    static TO_ISO_STRING: TruffleString;
    static TO_JSON: TruffleString;
    static TO_LOCALE_STRING: TruffleString;
    static TO_PRIMITIVE: TruffleString;
    static TO_REVERSED: TruffleString;
    static TO_SORTED: TruffleString;
    static TO_SPLICED: TruffleString;
    static TO_STRING: TruffleString;
    static TO_STRING_JLS: string;
    static TO_STRING_TAG: TruffleString;
    static TO_STRING_VALUE_ARRAY: TruffleString;
    static TO_STRING_VALUE_DATE: TruffleString;
    static TO_STRING_VALUE_FUNCTION: TruffleString;
    static TO_STRING_VALUE_NULL: TruffleString;
    static TO_STRING_VALUE_OBJECT: TruffleString;
    static TO_STRING_VALUE_UNDEFINED: TruffleString;
    static TO_TEMPORAL_INSTANT: TruffleString;
    static TO_UTC_STRING: TruffleString;
    static TRUE: TruffleString;
    static TT: TruffleString;
    static TYPE: TruffleString;
    static UC_0X: TruffleString;
    static UC_ARRAY: TruffleString;
    static UC_BOOLEAN: TruffleString;
    static UC_ERROR: TruffleString;
    static UC_ETC: TruffleString;
    static UC_M: TruffleString;
    static UC_M0: TruffleString;
    static UC_MODULE: TruffleString;
    static UC_NUMBER: TruffleString;
    static UC_OBJECT: TruffleString;
    static UC_PACKAGES: TruffleString;
    static UC_STRING: TruffleString;
    static UC_SYMBOL: TruffleString;
    static UC_Z: TruffleString;
    static UND: TruffleString;
    static UNDEFINED: TruffleString;
    static UNDERSCORE: TruffleString;
    static UNDERSCORE_2: TruffleString;
    static UNIT: TruffleString;
    static UNKNOWN: TruffleString;
    static UNKNOWN_FILENAME: TruffleString;
    static UNSCOPABLES: TruffleString;
    static URL: TruffleString;
    static VALUE: TruffleString;
    static VALUES: TruffleString;
    static VALUE_JLS: string;
    static VALUE_OF: TruffleString;
    static VALUE_OF_JLS: string;
    static VERSION_ECMA_SCRIPT: TruffleString;
    static VERSION_GRAAL_VM: TruffleString;
    static WITH: TruffleString;
    static WRITTEN: TruffleString;
    static Y: TruffleString;
    static YEAR: TruffleString;
    static Z: TruffleString;
    static ZERO: TruffleString;
    static _COMPILE_ONLY: TruffleString;
    static _SCRIPTING: TruffleString;
    static _TIMEZONE: TruffleString;
    static addBrackets(paramstr: TruffleString): TruffleString;
    static builderAppend(paramnode: TruffleStringBuilder$AppendCharUTF16Node, paramsb: TruffleStringBuilderUTF16, paramchr: string): void;
    static builderAppend(paramnode: TruffleStringBuilder$AppendCodePointNode, paramsb: TruffleStringBuilderUTF16, paramcp: number): void;
    static builderAppend(paramnode: TruffleStringBuilder$AppendCodePointNode, paramsb: TruffleStringBuilderUTF16, paramcp: number, paramrepeat: number): void;
    static builderAppend(paramnode: TruffleStringBuilder$AppendIntNumberNode, paramsb: TruffleStringBuilderUTF16, parami: number): void;
    static builderAppend(paramnode: TruffleStringBuilder$AppendJavaStringUTF16Node, paramsb: TruffleStringBuilderUTF16, paramstr: string): void;
    static builderAppend(paramnode: TruffleStringBuilder$AppendLongNumberNode, paramsb: TruffleStringBuilderUTF16, parami: number): void;
    static builderAppend(paramnode: TruffleStringBuilder$AppendStringNode, paramsb: TruffleStringBuilderUTF16, paramstr: TruffleString): void;
    static builderAppend(paramnode: TruffleStringBuilder$AppendSubstringByteIndexNode, paramsb: TruffleStringBuilderUTF16, paramstr: TruffleString, paramstart: number, paramend: number): void;
    static builderAppend(paramsb: TruffleStringBuilderUTF16, paramchr: string): void;
    static builderAppend(paramsb: TruffleStringBuilderUTF16, paramstr: TruffleString): void;
    static builderAppend(paramsb: TruffleStringBuilderUTF16, paramstr: TruffleString, paramstart: number, paramend: number): void;
    static builderAppend(paramsb: TruffleStringBuilderUTF16, parami: number): void;
    static builderAppend(paramsb: TruffleStringBuilderUTF16, paramstr: string): void;
    static builderAppend(paramsb: TruffleStringBuilderUTF16, parami: number): void;
    static builderAppendLen(paramnode: TruffleStringBuilder$AppendSubstringByteIndexNode, paramsb: TruffleStringBuilderUTF16, paramstr: TruffleString, paramstart: number, paramlen: number): void;
    static builderAppendLen(paramsb: TruffleStringBuilderUTF16, paramstr: TruffleString, paramstart: number, paramlen: number): void;
    static builderCreate(): TruffleStringBuilderUTF16;
    static builderCreate(paramcapacity: number): TruffleStringBuilderUTF16;
    static builderLength(paramsb: TruffleStringBuilderUTF16): number;
    static builderToJavaString(paramsb: TruffleStringBuilderUTF16): string;
    static builderToString(paramnode: TruffleStringBuilder$ToStringNode, paramsb: TruffleStringBuilderUTF16): TruffleString;
    static builderToString(paramsb: TruffleStringBuilderUTF16): TruffleString;
    static charAt(paramreadRawNode: TruffleString$ReadCharUTF16Node, params: TruffleString, parami: number): string;
    static charAt(params: TruffleString, parami: number): string;
    static codePointAt(paramnode: TruffleString$CodePointAtByteIndexNode, params: TruffleString, parami: number): number;
    static compareTo(paramnode: TruffleString$CompareCharsUTF16Node, parama: TruffleString, paramb: TruffleString): number;
    static compareTo(parama: TruffleString, paramb: TruffleString): number;
    static concat(paramnode: TruffleString$ConcatNode, params1: TruffleString, params2: TruffleString): TruffleString;
    static concat(params1: TruffleString, params2: TruffleString): TruffleString;
    static concatAll(params: TruffleString, ...paramconcat: (Object | null)[]): TruffleString;
    static constant(params: string): TruffleString;
    static contains(params: TruffleString, paramc: string): boolean;
    static convertJavaStringArray(paramarray: (Object | null)[]): (Object | null)[];
    static endsWith(paramregionEqualsNode: TruffleString$RegionEqualByteIndexNode, params1: TruffleString, params2: TruffleString): boolean;
    static endsWith(params1: TruffleString, params2: TruffleString): boolean;
    static equals(paramnode: TruffleString$EqualNode, params1: TruffleString, params2: TruffleString): boolean;
    static equals(params1: TruffleString, params2: TruffleString): boolean;
    static flatten(parammaterializeNode: TruffleString$MaterializeNode, paramvalue: TruffleString): TruffleString;
    static format(paramformatString: string, ...paramargs: (Object | null)[]): TruffleString;
    static fromBigInt(parambi: BigInt): TruffleString;
    static fromBigInt(parambi: BigInt, paramradix: number): TruffleString;
    static fromBoolean(paramb: boolean): TruffleString;
    static fromCharArray(paramchars: string[], paramfromIndex: number, paramlength: number): TruffleString;
    static fromCharArray(paramnode: TruffleString$FromCharArrayUTF16Node, paramchars: string[]): TruffleString;
    static fromCharArray(paramnode: TruffleString$FromCharArrayUTF16Node, paramchars: string[], paramfromIndex: number, paramlength: number): TruffleString;
    static fromCodePoint(paramnode: TruffleString$FromCodePointNode, paramc: number): TruffleString;
    static fromDouble(paramd: number): TruffleString;
    static fromInt(paramintValue: number): TruffleString;
    static fromJavaString(paramnode: TruffleString$FromJavaStringNode, paramstr: string): TruffleString;
    static fromJavaString(paramstr: string): TruffleString;
    static fromJavaStringArray(...paramstrings: (Object | null)[]): (Object | null)[];
    static fromLong(paramnode: TruffleString$FromLongNode, paramlongValue: number): TruffleString;
    static fromLong(paramlongValue: number): TruffleString;
    static fromNumber(paramnumber: Number): TruffleString;
    static fromObject(paramo: Object): TruffleString;
    static indexOf(paramnode: TruffleString$ByteIndexOfCodePointNode, params: TruffleString, paramcodepoint: number): number;
    static indexOf(paramnode: TruffleString$ByteIndexOfCodePointNode, params: TruffleString, paramcodepoint: number, paramfromIndex: number): number;
    static indexOf(paramnode: TruffleString$ByteIndexOfStringNode, params1: TruffleString, params2: TruffleString): number;
    static indexOf(paramnode: TruffleString$ByteIndexOfStringNode, params1: TruffleString, params2: TruffleString, paramfromIndex: number): number;
    static indexOf(paramnode: TruffleString$ByteIndexOfStringNode, params1: TruffleString, params2: TruffleString, paramfromIndex: number, paramtoIndex: number): number;
    static indexOf(paramstring: TruffleString, paramc: string): number;
    static indexOf(params1: TruffleString, params2: TruffleString): number;
    static indexOf(params1: TruffleString, params2: TruffleString, paramfromIndex: number): number;
    static indexOf(params1: TruffleString, params2: TruffleString, paramfromIndex: number, paramtoIndex: number): number;
    static indexOf(params: TruffleString, paramcodepoint: number, paramfromIndex: number): number;
    static indexOfAny(paramnode: TruffleString$CharIndexOfAnyCharUTF16Node, params: TruffleString, ...paramchars: string[]): number;
    static interopAsString(paramstringInterop: InteropLibrary, paramkey: Object): string;
    static interopAsString(paramkey: Object): string;
    static interopAsTruffleString(paramkey: Object): TruffleString;
    static interopAsTruffleString(paramkey: Object, paramstringInterop: InteropLibrary): TruffleString;
    static interopAsTruffleString(paramkey: Object, paramstringInterop: InteropLibrary, paramswitchEncodingNode: TruffleString$SwitchEncodingNode): TruffleString;
    static isEmpty(params: TruffleString): boolean;
    static isTString(paramstring: Object): boolean;
    static javaStringToLowerCase(params: string, paramlocale: Locale): string;
    static javaStringToUpperCase(params: string, paramlocale: Locale): string;
    static lastIndexOf(paramnode: TruffleString$LastByteIndexOfCodePointNode, params: TruffleString, paramcodePoint: number): number;
    static lastIndexOf(paramlastIndexOfNode: TruffleString$LastByteIndexOfStringNode, params1: TruffleString, params2: TruffleString, paramfromIndex: number): number;
    static lastIndexOf(params: TruffleString, paramcodePoint: number): number;
    static lazySubstring(paramnode: TruffleString$SubstringByteIndexNode, params: TruffleString, paramfromIndex: number, paramlength: number): TruffleString;
    static lazySubstring(params: TruffleString, paramfromIndex: number): TruffleString;
    static lazySubstring(params: TruffleString, paramfromIndex: number, paramlength: number): TruffleString;
    static lazyTrim(params: TruffleString): TruffleString;
    static length(params: TruffleString): number;
    static lengthOfCodePointAt(paramnode: TruffleString$ByteLengthOfCodePointNode, params: TruffleString, parami: number): number;
    static parseBigInt(params: TruffleString): BigInt;
    static parseBigInteger(params: TruffleString, paramradix: number): BigInteger;
    static parseDouble(paramnode: TruffleString$ParseDoubleNode, params: TruffleString): number;
    static parseDouble(params: TruffleString): number;
    static parseLong(paramnode: TruffleString$ParseLongNode, params: TruffleString, paramradix: number): number;
    static parseLong(params: TruffleString): number;
    static parseLong(params: TruffleString, paramradix: number): number;
    static regionEquals(paramregionEqualsNode: TruffleString$RegionEqualByteIndexNode, params1: TruffleString, paramoffset1: number, params2: TruffleString, paramoffset2: number, paramlength: number): boolean;
    static regionEquals(params1: TruffleString, paramoffset1: number, params2: TruffleString, paramoffset2: number, paramlength: number): boolean;
    static replace(params: TruffleString, paramsearch: TruffleString, paramreplace: TruffleString): TruffleString;
    static split(paramcontext: JSContext, paramstr: TruffleString, paramdelimiter: TruffleString): (Object | null)[];
    static startsWith(paramregionEqualsNode: TruffleString$RegionEqualByteIndexNode, params1: TruffleString, params2: TruffleString): boolean;
    static startsWith(paramregionEqualsNode: TruffleString$RegionEqualByteIndexNode, params1: TruffleString, params2: TruffleString, paramstartPos: number): boolean;
    static startsWith(params1: TruffleString, params2: TruffleString): boolean;
    static startsWith(params1: TruffleString, params2: TruffleString, paramstartPos: number): boolean;
    static substring(paramlazy: boolean, paramnode: TruffleString$SubstringByteIndexNode, params: TruffleString, paramfromIndex: number, paramlength: number): TruffleString;
    static substring(paramcontext: JSContext, paramnode: TruffleString$SubstringByteIndexNode, params: TruffleString, paramfromIndex: number): TruffleString;
    static substring(paramcontext: JSContext, paramnode: TruffleString$SubstringByteIndexNode, params: TruffleString, paramfromIndex: number, paramlength: number): TruffleString;
    static substring(paramcontext: JSContext, params: TruffleString, paramfromIndex: number): TruffleString;
    static substring(paramcontext: JSContext, params: TruffleString, paramfromIndex: number, paramlength: number): TruffleString;
    static toJavaString(paramnode: TruffleString$ToJavaStringNode, params: TruffleString): string;
    static toJavaString(params: TruffleString): string;
    static toUpperCase(params: TruffleString, paramlocale: Locale): TruffleString;
    private constructor()
}