import type { Object } from '../../../../java/lang/Object.d.ts'
export class Preconditions extends Object {
    static checkArgument(paramexpression: boolean): void;
    static checkArgument(paramexpression: boolean, paramerrorMessage: Object): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: string): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: string, paramp2: string): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: string, paramp2: number): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: string, paramp2: Object): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: number): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: number, paramp2: string): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: number, paramp2: number): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: number, paramp2: Object): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: Object): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: Object, paramp2: string): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: Object, paramp2: number): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: Object, paramp2: Object): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: Object, paramp2: Object, paramp3: Object): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: Object, paramp2: Object, paramp3: Object, paramp4: Object): void;
    static checkArgument(paramexpression: boolean, paramerrorMessageTemplate: string, ...paramerrorMessageArgs: Object[]): void;
    static checkElementIndex(paramindex: number, paramsize: number): number;
    static checkElementIndex(paramindex: number, paramsize: number, paramdesc: string): number;
    static checkNotNull<T extends unknown>(paramreference: T): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessage: Object): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: string): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: string, paramp2: string): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: string, paramp2: number): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: string, paramp2: Object): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: number): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: number, paramp2: string): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: number, paramp2: number): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: number, paramp2: Object): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: Object): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: Object, paramp2: string): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: Object, paramp2: number): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: Object, paramp2: Object): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: Object, paramp2: Object, paramp3: Object): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, paramp1: Object, paramp2: Object, paramp3: Object, paramp4: Object): T;
    static checkNotNull<T extends unknown>(paramreference: T, paramerrorMessageTemplate: string, ...paramerrorMessageArgs: Object[]): T;
    static checkPositionIndex(paramindex: number, paramsize: number): number;
    static checkPositionIndex(paramindex: number, paramsize: number, paramdesc: string): number;
    static checkPositionIndexes(paramstart: number, paramend: number, paramsize: number): void;
    static checkState(paramexpression: boolean): void;
    static checkState(paramexpression: boolean, paramerrorMessage: Object): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: string): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: string, paramp2: string): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: string, paramp2: number): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: string, paramp2: Object): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: number): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: number, paramp2: string): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: number, paramp2: number): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: number, paramp2: Object): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: Object): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: Object, paramp2: string): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: Object, paramp2: number): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: Object, paramp2: Object): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: Object, paramp2: Object, paramp3: Object): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, paramp1: Object, paramp2: Object, paramp3: Object, paramp4: Object): void;
    static checkState(paramexpression: boolean, paramerrorMessageTemplate: string, ...paramerrorMessageArgs: Object[]): void;
    private constructor()
}