import type { Object } from '../../../../../java/lang/Object.d.ts'
import type { MapColor$Brightness } from '../../../../../net/minecraft/world/level/material/MapColor$Brightness.d.ts'
export class MapColor extends Object {
    static CLAY: MapColor;
    static COLOR_BLACK: MapColor;
    static COLOR_BLUE: MapColor;
    static COLOR_BROWN: MapColor;
    static COLOR_CYAN: MapColor;
    static COLOR_GRAY: MapColor;
    static COLOR_GREEN: MapColor;
    static COLOR_LIGHT_BLUE: MapColor;
    static COLOR_LIGHT_GRAY: MapColor;
    static COLOR_LIGHT_GREEN: MapColor;
    static COLOR_MAGENTA: MapColor;
    static COLOR_ORANGE: MapColor;
    static COLOR_PINK: MapColor;
    static COLOR_PURPLE: MapColor;
    static COLOR_RED: MapColor;
    static COLOR_YELLOW: MapColor;
    static CRIMSON_HYPHAE: MapColor;
    static CRIMSON_NYLIUM: MapColor;
    static CRIMSON_STEM: MapColor;
    static DEEPSLATE: MapColor;
    static DIAMOND: MapColor;
    static DIRT: MapColor;
    static EMERALD: MapColor;
    static FIRE: MapColor;
    static GLOW_LICHEN: MapColor;
    static GOLD: MapColor;
    static GRASS: MapColor;
    static ICE: MapColor;
    static LAPIS: MapColor;
    static METAL: MapColor;
    static NETHER: MapColor;
    static NONE: MapColor;
    static PLANT: MapColor;
    static PODZOL: MapColor;
    static QUARTZ: MapColor;
    static RAW_IRON: MapColor;
    static SAND: MapColor;
    static SNOW: MapColor;
    static STONE: MapColor;
    static TERRACOTTA_BLACK: MapColor;
    static TERRACOTTA_BLUE: MapColor;
    static TERRACOTTA_BROWN: MapColor;
    static TERRACOTTA_CYAN: MapColor;
    static TERRACOTTA_GRAY: MapColor;
    static TERRACOTTA_GREEN: MapColor;
    static TERRACOTTA_LIGHT_BLUE: MapColor;
    static TERRACOTTA_LIGHT_GRAY: MapColor;
    static TERRACOTTA_LIGHT_GREEN: MapColor;
    static TERRACOTTA_MAGENTA: MapColor;
    static TERRACOTTA_ORANGE: MapColor;
    static TERRACOTTA_PINK: MapColor;
    static TERRACOTTA_PURPLE: MapColor;
    static TERRACOTTA_RED: MapColor;
    static TERRACOTTA_WHITE: MapColor;
    static TERRACOTTA_YELLOW: MapColor;
    static WARPED_HYPHAE: MapColor;
    static WARPED_NYLIUM: MapColor;
    static WARPED_STEM: MapColor;
    static WARPED_WART_BLOCK: MapColor;
    static WATER: MapColor;
    static WOOD: MapColor;
    static WOOL: MapColor;
    static byId(paramid: number): MapColor;
    static getColorFromPackedId(parampackedId: number): number;
    private constructor(id: number, col: number)
    col: number;
    id: number;
    calculateARGBColor(brightness: MapColor$Brightness): number;
    getPackedId(brightness: MapColor$Brightness): number;
}