import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { IntBuffer } from '../../../../java/nio/IntBuffer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../../java/lang/CharSequence.d.ts'
export class FCNTL extends Object {
    static DN_ACCESS: number;
    static DN_ATTRIB: number;
    static DN_CREATE: number;
    static DN_DELETE: number;
    static DN_MODIFY: number;
    static DN_MULTISHOT: number;
    static DN_RENAME: number;
    static FD_CLOEXEC: number;
    static F_ADD_SEALS: number;
    static F_DUPFD: number;
    static F_DUPFD_CLOEXEC: number;
    static F_EXLCK: number;
    static F_GETFD: number;
    static F_GETFL: number;
    static F_GETLEASE: number;
    static F_GETLK: number;
    static F_GETOWN: number;
    static F_GETOWN_EX: number;
    static F_GETPIPE_SZ: number;
    static F_GETSIG: number;
    static F_GET_FILE_RW_HINT: number;
    static F_GET_RW_HINT: number;
    static F_GET_SEALS: number;
    static F_NOTIFY: number;
    static F_OFD_GETLK: number;
    static F_OFD_SETLK: number;
    static F_OFD_SETLKW: number;
    static F_OWNER_PGRP: number;
    static F_OWNER_PID: number;
    static F_OWNER_TID: number;
    static F_RDLCK: number;
    static F_SEAL_FUTURE_WRITE: number;
    static F_SEAL_GROW: number;
    static F_SEAL_SEAL: number;
    static F_SEAL_SHRINK: number;
    static F_SEAL_WRITE: number;
    static F_SETFD: number;
    static F_SETFL: number;
    static F_SETLEASE: number;
    static F_SETLK: number;
    static F_SETLKW: number;
    static F_SETOWN: number;
    static F_SETOWN_EX: number;
    static F_SETPIPE_SZ: number;
    static F_SETSIG: number;
    static F_SET_FILE_RW_HINT: number;
    static F_SET_RW_HINT: number;
    static F_SHLCK: number;
    static F_UNLCK: number;
    static F_WRLCK: number;
    static LOCK_EX: number;
    static LOCK_MAND: number;
    static LOCK_NB: number;
    static LOCK_READ: number;
    static LOCK_RW: number;
    static LOCK_SH: number;
    static LOCK_UN: number;
    static LOCK_WRITE: number;
    static O_ACCMODE: number;
    static O_APPEND: number;
    static O_ASYNC: number;
    static O_CLOEXEC: number;
    static O_CREAT: number;
    static O_DIRECT: number;
    static O_DIRECTORY: number;
    static O_DSYNC: number;
    static O_EXCL: number;
    static O_LARGEFILE: number;
    static O_NDELAY: number;
    static O_NOATIME: number;
    static O_NOCTTY: number;
    static O_NOFOLLOW: number;
    static O_NONBLOCK: number;
    static O_PATH: number;
    static O_RDONLY: number;
    static O_RDWR: number;
    static O_SYNC: number;
    static O_TMPFILE: number;
    static O_TRUNC: number;
    static O_WRONLY: number;
    static RWH_WRITE_LIFE_EXTREME: number;
    static RWH_WRITE_LIFE_LONG: number;
    static RWH_WRITE_LIFE_MEDIUM: number;
    static RWH_WRITE_LIFE_NONE: number;
    static RWH_WRITE_LIFE_NOT_SET: number;
    static RWH_WRITE_LIFE_SHORT: number;
    static S_IFBLK: number;
    static S_IFCHR: number;
    static S_IFDIR: number;
    static S_IFIFO: number;
    static S_IFLNK: number;
    static S_IFMT: number;
    static S_IFREG: number;
    static S_IFSOCK: number;
    static S_IRGRP: number;
    static S_IROTH: number;
    static S_IRUSR: number;
    static S_IRWXG: number;
    static S_IRWXO: number;
    static S_IRWXU: number;
    static S_ISGID: number;
    static S_ISUID: number;
    static S_ISVTX: number;
    static S_IWGRP: number;
    static S_IWOTH: number;
    static S_IWUSR: number;
    static S_IXGRP: number;
    static S_IXOTH: number;
    static S_IXUSR: number;
    static creat(paramarg0: IntBuffer, paramarg1: CharSequence, paramarg2: number): number;
    static creat(paramarg0: IntBuffer, paramarg1: ByteBuffer, paramarg2: number): number;
    static fcntl(paramarg0: IntBuffer, paramarg1: number, paramarg2: number): number;
    static fcntli(paramarg0: IntBuffer, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static fcntlp(paramarg0: IntBuffer, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static ncreat(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nfcntl(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nfcntli(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nfcntlp(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nopen(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nopenat(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static open(paramarg0: IntBuffer, paramarg1: CharSequence, paramarg2: number, paramarg3: number): number;
    static open(paramarg0: IntBuffer, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number): number;
    static openat(paramarg0: IntBuffer, paramarg1: number, paramarg2: CharSequence, paramarg3: number, paramarg4: number): number;
    static openat(paramarg0: IntBuffer, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number): number;
    constructor()
}