import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class StdVideoDecodeAV1PictureInfoFlags extends Struct<StdVideoDecodeAV1PictureInfoFlags> implements NativeResource {
    static ALIGNOF: number;
    static BITFIELD0: number;
    static BITFIELD1: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static SIZEOF: number;
    static calloc(): StdVideoDecodeAV1PictureInfoFlags;
    static calloc(paramarg0: MemoryStack): StdVideoDecodeAV1PictureInfoFlags;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): StdVideoDecodeAV1PictureInfoFlags;
    static create(paramarg0: number): StdVideoDecodeAV1PictureInfoFlags;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): StdVideoDecodeAV1PictureInfoFlags;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): StdVideoDecodeAV1PictureInfoFlags;
    static malloc(paramarg0: MemoryStack): StdVideoDecodeAV1PictureInfoFlags;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static nUsesLr(paramarg0: number): number;
    static nUsesLr(paramarg0: number, paramarg1: number): void;
    static nallow_high_precision_mv(paramarg0: number): number;
    static nallow_high_precision_mv(paramarg0: number, paramarg1: number): void;
    static nallow_intrabc(paramarg0: number): number;
    static nallow_intrabc(paramarg0: number, paramarg1: number): void;
    static nallow_screen_content_tools(paramarg0: number): number;
    static nallow_screen_content_tools(paramarg0: number, paramarg1: number): void;
    static nallow_warped_motion(paramarg0: number): number;
    static nallow_warped_motion(paramarg0: number, paramarg1: number): void;
    static napply_grain(paramarg0: number): number;
    static napply_grain(paramarg0: number, paramarg1: number): void;
    static nbitfield0(paramarg0: number): number;
    static nbitfield0(paramarg0: number, paramarg1: number): void;
    static nbitfield1(paramarg0: number): number;
    static nbitfield1(paramarg0: number, paramarg1: number): void;
    static nbuffer_removal_time_present_flag(paramarg0: number): number;
    static nbuffer_removal_time_present_flag(paramarg0: number, paramarg1: number): void;
    static ndelta_lf_multi(paramarg0: number): number;
    static ndelta_lf_multi(paramarg0: number, paramarg1: number): void;
    static ndelta_lf_present(paramarg0: number): number;
    static ndelta_lf_present(paramarg0: number, paramarg1: number): void;
    static ndelta_q_present(paramarg0: number): number;
    static ndelta_q_present(paramarg0: number, paramarg1: number): void;
    static ndisable_cdf_update(paramarg0: number): number;
    static ndisable_cdf_update(paramarg0: number, paramarg1: number): void;
    static ndisable_frame_end_update_cdf(paramarg0: number): number;
    static ndisable_frame_end_update_cdf(paramarg0: number, paramarg1: number): void;
    static nerror_resilient_mode(paramarg0: number): number;
    static nerror_resilient_mode(paramarg0: number, paramarg1: number): void;
    static nforce_integer_mv(paramarg0: number): number;
    static nforce_integer_mv(paramarg0: number, paramarg1: number): void;
    static nframe_refs_short_signaling(paramarg0: number): number;
    static nframe_refs_short_signaling(paramarg0: number, paramarg1: number): void;
    static nframe_size_override_flag(paramarg0: number): number;
    static nframe_size_override_flag(paramarg0: number, paramarg1: number): void;
    static nis_filter_switchable(paramarg0: number): number;
    static nis_filter_switchable(paramarg0: number, paramarg1: number): void;
    static nis_motion_mode_switchable(paramarg0: number): number;
    static nis_motion_mode_switchable(paramarg0: number, paramarg1: number): void;
    static nreduced_tx_set(paramarg0: number): number;
    static nreduced_tx_set(paramarg0: number, paramarg1: number): void;
    static nreference_select(paramarg0: number): number;
    static nreference_select(paramarg0: number, paramarg1: number): void;
    static nrender_and_frame_size_different(paramarg0: number): number;
    static nrender_and_frame_size_different(paramarg0: number, paramarg1: number): void;
    static nreserved(paramarg0: number): number;
    static nreserved(paramarg0: number, paramarg1: number): void;
    static nsegmentation_enabled(paramarg0: number): number;
    static nsegmentation_enabled(paramarg0: number, paramarg1: number): void;
    static nsegmentation_temporal_update(paramarg0: number): number;
    static nsegmentation_temporal_update(paramarg0: number, paramarg1: number): void;
    static nsegmentation_update_data(paramarg0: number): number;
    static nsegmentation_update_data(paramarg0: number, paramarg1: number): void;
    static nsegmentation_update_map(paramarg0: number): number;
    static nsegmentation_update_map(paramarg0: number, paramarg1: number): void;
    static nskip_mode_present(paramarg0: number): number;
    static nskip_mode_present(paramarg0: number, paramarg1: number): void;
    static nuse_ref_frame_mvs(paramarg0: number): number;
    static nuse_ref_frame_mvs(paramarg0: number, paramarg1: number): void;
    static nuse_superres(paramarg0: number): number;
    static nuse_superres(paramarg0: number, paramarg1: number): void;
    static nusesChromaLr(paramarg0: number): number;
    static nusesChromaLr(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    UsesLr(): boolean;
    UsesLr(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    allow_high_precision_mv(): boolean;
    allow_high_precision_mv(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    allow_intrabc(): boolean;
    allow_intrabc(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    allow_screen_content_tools(): boolean;
    allow_screen_content_tools(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    allow_warped_motion(): boolean;
    allow_warped_motion(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    apply_grain(): boolean;
    apply_grain(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    buffer_removal_time_present_flag(): boolean;
    buffer_removal_time_present_flag(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    close(): void;
    create(arg0: number, arg1: ByteBuffer): StdVideoDecodeAV1PictureInfoFlags;
    delta_lf_multi(): boolean;
    delta_lf_multi(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    delta_lf_present(): boolean;
    delta_lf_present(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    delta_q_present(): boolean;
    delta_q_present(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    disable_cdf_update(): boolean;
    disable_cdf_update(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    disable_frame_end_update_cdf(): boolean;
    disable_frame_end_update_cdf(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    error_resilient_mode(): boolean;
    error_resilient_mode(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    force_integer_mv(): boolean;
    force_integer_mv(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    frame_refs_short_signaling(): boolean;
    frame_refs_short_signaling(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    frame_size_override_flag(): boolean;
    frame_size_override_flag(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    is_filter_switchable(): boolean;
    is_filter_switchable(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    is_motion_mode_switchable(): boolean;
    is_motion_mode_switchable(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    reduced_tx_set(): boolean;
    reduced_tx_set(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    reference_select(): boolean;
    reference_select(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    render_and_frame_size_different(): boolean;
    render_and_frame_size_different(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    segmentation_enabled(): boolean;
    segmentation_enabled(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    segmentation_temporal_update(): boolean;
    segmentation_temporal_update(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    segmentation_update_data(): boolean;
    segmentation_update_data(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    segmentation_update_map(): boolean;
    segmentation_update_map(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    set(arg0: boolean, arg1: boolean, arg2: boolean, arg3: boolean, arg4: boolean, arg5: boolean, arg6: boolean, arg7: boolean, arg8: boolean, arg9: boolean, arg10: boolean, arg11: boolean, arg12: boolean, arg13: boolean, arg14: boolean, arg15: boolean, arg16: boolean, arg17: boolean, arg18: boolean, arg19: boolean, arg20: boolean, arg21: boolean, arg22: boolean, arg23: boolean, arg24: boolean, arg25: boolean, arg26: boolean, arg27: boolean, arg28: boolean): StdVideoDecodeAV1PictureInfoFlags;
    set(arg0: StdVideoDecodeAV1PictureInfoFlags): StdVideoDecodeAV1PictureInfoFlags;
    sizeof(): number;
    skip_mode_present(): boolean;
    skip_mode_present(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    use_ref_frame_mvs(): boolean;
    use_ref_frame_mvs(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    use_superres(): boolean;
    use_superres(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
    usesChromaLr(): boolean;
    usesChromaLr(arg0: boolean): StdVideoDecodeAV1PictureInfoFlags;
}