import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { Consumer } from '../../../../java/util/function/Consumer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../../org/lwjgl/system/Struct$StructValidation.d.ts'
import type { StdVideoAV1FilmGrainFlags } from '../../../../org/lwjgl/vulkan/video/StdVideoAV1FilmGrainFlags.d.ts'
export class StdVideoAV1FilmGrain extends Struct<StdVideoAV1FilmGrain> implements NativeResource {
    static ALIGNOF: number;
    static AR_COEFFS_CB_PLUS_128: number;
    static AR_COEFFS_CR_PLUS_128: number;
    static AR_COEFFS_Y_PLUS_128: number;
    static AR_COEFF_LAG: number;
    static AR_COEFF_SHIFT_MINUS_6: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CB_LUMA_MULT: number;
    static CB_MULT: number;
    static CB_OFFSET: number;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static CR_LUMA_MULT: number;
    static CR_MULT: number;
    static CR_OFFSET: number;
    static FILM_GRAIN_PARAMS_REF_IDX: number;
    static FLAGS: number;
    static GRAIN_SCALE_SHIFT: number;
    static GRAIN_SCALING_MINUS_8: number;
    static GRAIN_SEED: number;
    static NUM_CB_POINTS: number;
    static NUM_CR_POINTS: number;
    static NUM_Y_POINTS: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static POINT_CB_SCALING: number;
    static POINT_CB_VALUE: number;
    static POINT_CR_SCALING: number;
    static POINT_CR_VALUE: number;
    static POINT_Y_SCALING: number;
    static POINT_Y_VALUE: number;
    static SIZEOF: number;
    static calloc(): StdVideoAV1FilmGrain;
    static calloc(paramarg0: MemoryStack): StdVideoAV1FilmGrain;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): StdVideoAV1FilmGrain;
    static create(paramarg0: number): StdVideoAV1FilmGrain;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): StdVideoAV1FilmGrain;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): StdVideoAV1FilmGrain;
    static malloc(paramarg0: MemoryStack): StdVideoAV1FilmGrain;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static nar_coeff_lag(paramarg0: number): number;
    static nar_coeff_lag(paramarg0: number, paramarg1: number): void;
    static nar_coeff_shift_minus_6(paramarg0: number): number;
    static nar_coeff_shift_minus_6(paramarg0: number, paramarg1: number): void;
    static nar_coeffs_cb_plus_128(paramarg0: number, paramarg1: number): number;
    static nar_coeffs_cb_plus_128(paramarg0: number): ByteBuffer;
    static nar_coeffs_cb_plus_128(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nar_coeffs_cb_plus_128(paramarg0: number, paramarg1: ByteBuffer): void;
    static nar_coeffs_cr_plus_128(paramarg0: number, paramarg1: number): number;
    static nar_coeffs_cr_plus_128(paramarg0: number): ByteBuffer;
    static nar_coeffs_cr_plus_128(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nar_coeffs_cr_plus_128(paramarg0: number, paramarg1: ByteBuffer): void;
    static nar_coeffs_y_plus_128(paramarg0: number, paramarg1: number): number;
    static nar_coeffs_y_plus_128(paramarg0: number): ByteBuffer;
    static nar_coeffs_y_plus_128(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nar_coeffs_y_plus_128(paramarg0: number, paramarg1: ByteBuffer): void;
    static ncb_luma_mult(paramarg0: number): number;
    static ncb_luma_mult(paramarg0: number, paramarg1: number): void;
    static ncb_mult(paramarg0: number): number;
    static ncb_mult(paramarg0: number, paramarg1: number): void;
    static ncb_offset(paramarg0: number): number;
    static ncb_offset(paramarg0: number, paramarg1: number): void;
    static ncr_luma_mult(paramarg0: number): number;
    static ncr_luma_mult(paramarg0: number, paramarg1: number): void;
    static ncr_mult(paramarg0: number): number;
    static ncr_mult(paramarg0: number, paramarg1: number): void;
    static ncr_offset(paramarg0: number): number;
    static ncr_offset(paramarg0: number, paramarg1: number): void;
    static nfilm_grain_params_ref_idx(paramarg0: number): number;
    static nfilm_grain_params_ref_idx(paramarg0: number, paramarg1: number): void;
    static nflags(paramarg0: number): StdVideoAV1FilmGrainFlags;
    static nflags(paramarg0: number, paramarg1: StdVideoAV1FilmGrainFlags): void;
    static ngrain_scale_shift(paramarg0: number): number;
    static ngrain_scale_shift(paramarg0: number, paramarg1: number): void;
    static ngrain_scaling_minus_8(paramarg0: number): number;
    static ngrain_scaling_minus_8(paramarg0: number, paramarg1: number): void;
    static ngrain_seed(paramarg0: number): number;
    static ngrain_seed(paramarg0: number, paramarg1: number): void;
    static nnum_cb_points(paramarg0: number): number;
    static nnum_cb_points(paramarg0: number, paramarg1: number): void;
    static nnum_cr_points(paramarg0: number): number;
    static nnum_cr_points(paramarg0: number, paramarg1: number): void;
    static nnum_y_points(paramarg0: number): number;
    static nnum_y_points(paramarg0: number, paramarg1: number): void;
    static npoint_cb_scaling(paramarg0: number, paramarg1: number): number;
    static npoint_cb_scaling(paramarg0: number): ByteBuffer;
    static npoint_cb_scaling(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static npoint_cb_scaling(paramarg0: number, paramarg1: ByteBuffer): void;
    static npoint_cb_value(paramarg0: number, paramarg1: number): number;
    static npoint_cb_value(paramarg0: number): ByteBuffer;
    static npoint_cb_value(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static npoint_cb_value(paramarg0: number, paramarg1: ByteBuffer): void;
    static npoint_cr_scaling(paramarg0: number, paramarg1: number): number;
    static npoint_cr_scaling(paramarg0: number): ByteBuffer;
    static npoint_cr_scaling(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static npoint_cr_scaling(paramarg0: number, paramarg1: ByteBuffer): void;
    static npoint_cr_value(paramarg0: number, paramarg1: number): number;
    static npoint_cr_value(paramarg0: number): ByteBuffer;
    static npoint_cr_value(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static npoint_cr_value(paramarg0: number, paramarg1: ByteBuffer): void;
    static npoint_y_scaling(paramarg0: number, paramarg1: number): number;
    static npoint_y_scaling(paramarg0: number): ByteBuffer;
    static npoint_y_scaling(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static npoint_y_scaling(paramarg0: number, paramarg1: ByteBuffer): void;
    static npoint_y_value(paramarg0: number, paramarg1: number): number;
    static npoint_y_value(paramarg0: number): ByteBuffer;
    static npoint_y_value(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static npoint_y_value(paramarg0: number, paramarg1: ByteBuffer): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    ar_coeff_lag(): number;
    ar_coeff_lag(arg0: number): StdVideoAV1FilmGrain;
    ar_coeff_shift_minus_6(): number;
    ar_coeff_shift_minus_6(arg0: number): StdVideoAV1FilmGrain;
    ar_coeffs_cb_plus_128(): ByteBuffer;
    ar_coeffs_cb_plus_128(arg0: ByteBuffer): StdVideoAV1FilmGrain;
    ar_coeffs_cb_plus_128(arg0: number): number;
    ar_coeffs_cb_plus_128(arg0: number, arg1: number): StdVideoAV1FilmGrain;
    ar_coeffs_cr_plus_128(): ByteBuffer;
    ar_coeffs_cr_plus_128(arg0: ByteBuffer): StdVideoAV1FilmGrain;
    ar_coeffs_cr_plus_128(arg0: number): number;
    ar_coeffs_cr_plus_128(arg0: number, arg1: number): StdVideoAV1FilmGrain;
    ar_coeffs_y_plus_128(): ByteBuffer;
    ar_coeffs_y_plus_128(arg0: ByteBuffer): StdVideoAV1FilmGrain;
    ar_coeffs_y_plus_128(arg0: number): number;
    ar_coeffs_y_plus_128(arg0: number, arg1: number): StdVideoAV1FilmGrain;
    cb_luma_mult(): number;
    cb_luma_mult(arg0: number): StdVideoAV1FilmGrain;
    cb_mult(): number;
    cb_mult(arg0: number): StdVideoAV1FilmGrain;
    cb_offset(): number;
    cb_offset(arg0: number): StdVideoAV1FilmGrain;
    close(): void;
    cr_luma_mult(): number;
    cr_luma_mult(arg0: number): StdVideoAV1FilmGrain;
    cr_mult(): number;
    cr_mult(arg0: number): StdVideoAV1FilmGrain;
    cr_offset(): number;
    cr_offset(arg0: number): StdVideoAV1FilmGrain;
    create(arg0: number, arg1: ByteBuffer): StdVideoAV1FilmGrain;
    film_grain_params_ref_idx(): number;
    film_grain_params_ref_idx(arg0: number): StdVideoAV1FilmGrain;
    flags(): StdVideoAV1FilmGrainFlags;
    flags(arg0: (param0: StdVideoAV1FilmGrainFlags) => void): StdVideoAV1FilmGrain;
    flags(arg0: StdVideoAV1FilmGrainFlags): StdVideoAV1FilmGrain;
    grain_scale_shift(): number;
    grain_scale_shift(arg0: number): StdVideoAV1FilmGrain;
    grain_scaling_minus_8(): number;
    grain_scaling_minus_8(arg0: number): StdVideoAV1FilmGrain;
    grain_seed(): number;
    grain_seed(arg0: number): StdVideoAV1FilmGrain;
    num_cb_points(): number;
    num_cb_points(arg0: number): StdVideoAV1FilmGrain;
    num_cr_points(): number;
    num_cr_points(arg0: number): StdVideoAV1FilmGrain;
    num_y_points(): number;
    num_y_points(arg0: number): StdVideoAV1FilmGrain;
    point_cb_scaling(): ByteBuffer;
    point_cb_scaling(arg0: ByteBuffer): StdVideoAV1FilmGrain;
    point_cb_scaling(arg0: number): number;
    point_cb_scaling(arg0: number, arg1: number): StdVideoAV1FilmGrain;
    point_cb_value(): ByteBuffer;
    point_cb_value(arg0: ByteBuffer): StdVideoAV1FilmGrain;
    point_cb_value(arg0: number): number;
    point_cb_value(arg0: number, arg1: number): StdVideoAV1FilmGrain;
    point_cr_scaling(): ByteBuffer;
    point_cr_scaling(arg0: ByteBuffer): StdVideoAV1FilmGrain;
    point_cr_scaling(arg0: number): number;
    point_cr_scaling(arg0: number, arg1: number): StdVideoAV1FilmGrain;
    point_cr_value(): ByteBuffer;
    point_cr_value(arg0: ByteBuffer): StdVideoAV1FilmGrain;
    point_cr_value(arg0: number): number;
    point_cr_value(arg0: number, arg1: number): StdVideoAV1FilmGrain;
    point_y_scaling(): ByteBuffer;
    point_y_scaling(arg0: ByteBuffer): StdVideoAV1FilmGrain;
    point_y_scaling(arg0: number): number;
    point_y_scaling(arg0: number, arg1: number): StdVideoAV1FilmGrain;
    point_y_value(): ByteBuffer;
    point_y_value(arg0: ByteBuffer): StdVideoAV1FilmGrain;
    point_y_value(arg0: number): number;
    point_y_value(arg0: number, arg1: number): StdVideoAV1FilmGrain;
    set(arg0: StdVideoAV1FilmGrain): StdVideoAV1FilmGrain;
    set(arg0: StdVideoAV1FilmGrainFlags, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: ByteBuffer, arg9: ByteBuffer, arg10: number, arg11: ByteBuffer, arg12: ByteBuffer, arg13: number, arg14: ByteBuffer, arg15: ByteBuffer, arg16: ByteBuffer, arg17: ByteBuffer, arg18: ByteBuffer, arg19: number, arg20: number, arg21: number, arg22: number, arg23: number, arg24: number): StdVideoAV1FilmGrain;
    sizeof(): number;
}