import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class StdVideoH265SpsVuiFlags extends Struct<StdVideoH265SpsVuiFlags> implements NativeResource {
    static ALIGNOF: number;
    static BITFIELD0: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static SIZEOF: number;
    static calloc(): StdVideoH265SpsVuiFlags;
    static calloc(paramarg0: MemoryStack): StdVideoH265SpsVuiFlags;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): StdVideoH265SpsVuiFlags;
    static create(paramarg0: number): StdVideoH265SpsVuiFlags;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): StdVideoH265SpsVuiFlags;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): StdVideoH265SpsVuiFlags;
    static malloc(paramarg0: MemoryStack): StdVideoH265SpsVuiFlags;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static naspect_ratio_info_present_flag(paramarg0: number): number;
    static naspect_ratio_info_present_flag(paramarg0: number, paramarg1: number): void;
    static nbitfield0(paramarg0: number): number;
    static nbitfield0(paramarg0: number, paramarg1: number): void;
    static nbitstream_restriction_flag(paramarg0: number): number;
    static nbitstream_restriction_flag(paramarg0: number, paramarg1: number): void;
    static nchroma_loc_info_present_flag(paramarg0: number): number;
    static nchroma_loc_info_present_flag(paramarg0: number, paramarg1: number): void;
    static ncolour_description_present_flag(paramarg0: number): number;
    static ncolour_description_present_flag(paramarg0: number, paramarg1: number): void;
    static ndefault_display_window_flag(paramarg0: number): number;
    static ndefault_display_window_flag(paramarg0: number, paramarg1: number): void;
    static nfield_seq_flag(paramarg0: number): number;
    static nfield_seq_flag(paramarg0: number, paramarg1: number): void;
    static nframe_field_info_present_flag(paramarg0: number): number;
    static nframe_field_info_present_flag(paramarg0: number, paramarg1: number): void;
    static nmotion_vectors_over_pic_boundaries_flag(paramarg0: number): number;
    static nmotion_vectors_over_pic_boundaries_flag(paramarg0: number, paramarg1: number): void;
    static nneutral_chroma_indication_flag(paramarg0: number): number;
    static nneutral_chroma_indication_flag(paramarg0: number, paramarg1: number): void;
    static noverscan_appropriate_flag(paramarg0: number): number;
    static noverscan_appropriate_flag(paramarg0: number, paramarg1: number): void;
    static noverscan_info_present_flag(paramarg0: number): number;
    static noverscan_info_present_flag(paramarg0: number, paramarg1: number): void;
    static nrestricted_ref_pic_lists_flag(paramarg0: number): number;
    static nrestricted_ref_pic_lists_flag(paramarg0: number, paramarg1: number): void;
    static ntiles_fixed_structure_flag(paramarg0: number): number;
    static ntiles_fixed_structure_flag(paramarg0: number, paramarg1: number): void;
    static nvideo_full_range_flag(paramarg0: number): number;
    static nvideo_full_range_flag(paramarg0: number, paramarg1: number): void;
    static nvideo_signal_type_present_flag(paramarg0: number): number;
    static nvideo_signal_type_present_flag(paramarg0: number, paramarg1: number): void;
    static nvui_hrd_parameters_present_flag(paramarg0: number): number;
    static nvui_hrd_parameters_present_flag(paramarg0: number, paramarg1: number): void;
    static nvui_poc_proportional_to_timing_flag(paramarg0: number): number;
    static nvui_poc_proportional_to_timing_flag(paramarg0: number, paramarg1: number): void;
    static nvui_timing_info_present_flag(paramarg0: number): number;
    static nvui_timing_info_present_flag(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    aspect_ratio_info_present_flag(): boolean;
    aspect_ratio_info_present_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    bitstream_restriction_flag(): boolean;
    bitstream_restriction_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    chroma_loc_info_present_flag(): boolean;
    chroma_loc_info_present_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    close(): void;
    colour_description_present_flag(): boolean;
    colour_description_present_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    create(arg0: number, arg1: ByteBuffer): StdVideoH265SpsVuiFlags;
    default_display_window_flag(): boolean;
    default_display_window_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    field_seq_flag(): boolean;
    field_seq_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    frame_field_info_present_flag(): boolean;
    frame_field_info_present_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    motion_vectors_over_pic_boundaries_flag(): boolean;
    motion_vectors_over_pic_boundaries_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    neutral_chroma_indication_flag(): boolean;
    neutral_chroma_indication_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    overscan_appropriate_flag(): boolean;
    overscan_appropriate_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    overscan_info_present_flag(): boolean;
    overscan_info_present_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    restricted_ref_pic_lists_flag(): boolean;
    restricted_ref_pic_lists_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    set(arg0: boolean, arg1: boolean, arg2: boolean, arg3: boolean, arg4: boolean, arg5: boolean, arg6: boolean, arg7: boolean, arg8: boolean, arg9: boolean, arg10: boolean, arg11: boolean, arg12: boolean, arg13: boolean, arg14: boolean, arg15: boolean, arg16: boolean, arg17: boolean): StdVideoH265SpsVuiFlags;
    set(arg0: StdVideoH265SpsVuiFlags): StdVideoH265SpsVuiFlags;
    sizeof(): number;
    tiles_fixed_structure_flag(): boolean;
    tiles_fixed_structure_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    video_full_range_flag(): boolean;
    video_full_range_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    video_signal_type_present_flag(): boolean;
    video_signal_type_present_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    vui_hrd_parameters_present_flag(): boolean;
    vui_hrd_parameters_present_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    vui_poc_proportional_to_timing_flag(): boolean;
    vui_poc_proportional_to_timing_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
    vui_timing_info_present_flag(): boolean;
    vui_timing_info_present_flag(arg0: boolean): StdVideoH265SpsVuiFlags;
}