import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class StdVideoH265SpsFlags extends Struct<StdVideoH265SpsFlags> implements NativeResource {
    static ALIGNOF: number;
    static BITFIELD0: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static SIZEOF: number;
    static calloc(): StdVideoH265SpsFlags;
    static calloc(paramarg0: MemoryStack): StdVideoH265SpsFlags;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): StdVideoH265SpsFlags;
    static create(paramarg0: number): StdVideoH265SpsFlags;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): StdVideoH265SpsFlags;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): StdVideoH265SpsFlags;
    static malloc(paramarg0: MemoryStack): StdVideoH265SpsFlags;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static namp_enabled_flag(paramarg0: number): number;
    static namp_enabled_flag(paramarg0: number, paramarg1: number): void;
    static nbitfield0(paramarg0: number): number;
    static nbitfield0(paramarg0: number, paramarg1: number): void;
    static ncabac_bypass_alignment_enabled_flag(paramarg0: number): number;
    static ncabac_bypass_alignment_enabled_flag(paramarg0: number, paramarg1: number): void;
    static nconformance_window_flag(paramarg0: number): number;
    static nconformance_window_flag(paramarg0: number, paramarg1: number): void;
    static nexplicit_rdpcm_enabled_flag(paramarg0: number): number;
    static nexplicit_rdpcm_enabled_flag(paramarg0: number, paramarg1: number): void;
    static nextended_precision_processing_flag(paramarg0: number): number;
    static nextended_precision_processing_flag(paramarg0: number, paramarg1: number): void;
    static nhigh_precision_offsets_enabled_flag(paramarg0: number): number;
    static nhigh_precision_offsets_enabled_flag(paramarg0: number, paramarg1: number): void;
    static nimplicit_rdpcm_enabled_flag(paramarg0: number): number;
    static nimplicit_rdpcm_enabled_flag(paramarg0: number, paramarg1: number): void;
    static nintra_boundary_filtering_disabled_flag(paramarg0: number): number;
    static nintra_boundary_filtering_disabled_flag(paramarg0: number, paramarg1: number): void;
    static nintra_smoothing_disabled_flag(paramarg0: number): number;
    static nintra_smoothing_disabled_flag(paramarg0: number, paramarg1: number): void;
    static nlong_term_ref_pics_present_flag(paramarg0: number): number;
    static nlong_term_ref_pics_present_flag(paramarg0: number, paramarg1: number): void;
    static npalette_mode_enabled_flag(paramarg0: number): number;
    static npalette_mode_enabled_flag(paramarg0: number, paramarg1: number): void;
    static npcm_enabled_flag(paramarg0: number): number;
    static npcm_enabled_flag(paramarg0: number, paramarg1: number): void;
    static npcm_loop_filter_disabled_flag(paramarg0: number): number;
    static npcm_loop_filter_disabled_flag(paramarg0: number, paramarg1: number): void;
    static npersistent_rice_adaptation_enabled_flag(paramarg0: number): number;
    static npersistent_rice_adaptation_enabled_flag(paramarg0: number, paramarg1: number): void;
    static nsample_adaptive_offset_enabled_flag(paramarg0: number): number;
    static nsample_adaptive_offset_enabled_flag(paramarg0: number, paramarg1: number): void;
    static nscaling_list_enabled_flag(paramarg0: number): number;
    static nscaling_list_enabled_flag(paramarg0: number, paramarg1: number): void;
    static nseparate_colour_plane_flag(paramarg0: number): number;
    static nseparate_colour_plane_flag(paramarg0: number, paramarg1: number): void;
    static nsps_curr_pic_ref_enabled_flag(paramarg0: number): number;
    static nsps_curr_pic_ref_enabled_flag(paramarg0: number, paramarg1: number): void;
    static nsps_extension_present_flag(paramarg0: number): number;
    static nsps_extension_present_flag(paramarg0: number, paramarg1: number): void;
    static nsps_palette_predictor_initializer_present_flag(paramarg0: number): number;
    static nsps_palette_predictor_initializer_present_flag(paramarg0: number, paramarg1: number): void;
    static nsps_palette_predictor_initializers_present_flag(paramarg0: number): number;
    static nsps_palette_predictor_initializers_present_flag(paramarg0: number, paramarg1: number): void;
    static nsps_range_extension_flag(paramarg0: number): number;
    static nsps_range_extension_flag(paramarg0: number, paramarg1: number): void;
    static nsps_scaling_list_data_present_flag(paramarg0: number): number;
    static nsps_scaling_list_data_present_flag(paramarg0: number, paramarg1: number): void;
    static nsps_scc_extension_flag(paramarg0: number): number;
    static nsps_scc_extension_flag(paramarg0: number, paramarg1: number): void;
    static nsps_sub_layer_ordering_info_present_flag(paramarg0: number): number;
    static nsps_sub_layer_ordering_info_present_flag(paramarg0: number, paramarg1: number): void;
    static nsps_temporal_id_nesting_flag(paramarg0: number): number;
    static nsps_temporal_id_nesting_flag(paramarg0: number, paramarg1: number): void;
    static nsps_temporal_mvp_enabled_flag(paramarg0: number): number;
    static nsps_temporal_mvp_enabled_flag(paramarg0: number, paramarg1: number): void;
    static nstrong_intra_smoothing_enabled_flag(paramarg0: number): number;
    static nstrong_intra_smoothing_enabled_flag(paramarg0: number, paramarg1: number): void;
    static ntransform_skip_context_enabled_flag(paramarg0: number): number;
    static ntransform_skip_context_enabled_flag(paramarg0: number, paramarg1: number): void;
    static ntransform_skip_rotation_enabled_flag(paramarg0: number): number;
    static ntransform_skip_rotation_enabled_flag(paramarg0: number, paramarg1: number): void;
    static nvui_parameters_present_flag(paramarg0: number): number;
    static nvui_parameters_present_flag(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    amp_enabled_flag(): boolean;
    amp_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    cabac_bypass_alignment_enabled_flag(): boolean;
    cabac_bypass_alignment_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    close(): void;
    conformance_window_flag(): boolean;
    conformance_window_flag(arg0: boolean): StdVideoH265SpsFlags;
    create(arg0: number, arg1: ByteBuffer): StdVideoH265SpsFlags;
    explicit_rdpcm_enabled_flag(): boolean;
    explicit_rdpcm_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    extended_precision_processing_flag(): boolean;
    extended_precision_processing_flag(arg0: boolean): StdVideoH265SpsFlags;
    high_precision_offsets_enabled_flag(): boolean;
    high_precision_offsets_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    implicit_rdpcm_enabled_flag(): boolean;
    implicit_rdpcm_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    intra_boundary_filtering_disabled_flag(): boolean;
    intra_boundary_filtering_disabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    intra_smoothing_disabled_flag(): boolean;
    intra_smoothing_disabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    long_term_ref_pics_present_flag(): boolean;
    long_term_ref_pics_present_flag(arg0: boolean): StdVideoH265SpsFlags;
    palette_mode_enabled_flag(): boolean;
    palette_mode_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    pcm_enabled_flag(): boolean;
    pcm_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    pcm_loop_filter_disabled_flag(): boolean;
    pcm_loop_filter_disabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    persistent_rice_adaptation_enabled_flag(): boolean;
    persistent_rice_adaptation_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    sample_adaptive_offset_enabled_flag(): boolean;
    sample_adaptive_offset_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    scaling_list_enabled_flag(): boolean;
    scaling_list_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    separate_colour_plane_flag(): boolean;
    separate_colour_plane_flag(arg0: boolean): StdVideoH265SpsFlags;
    set(arg0: boolean, arg1: boolean, arg2: boolean, arg3: boolean, arg4: boolean, arg5: boolean, arg6: boolean, arg7: boolean, arg8: boolean, arg9: boolean, arg10: boolean, arg11: boolean, arg12: boolean, arg13: boolean, arg14: boolean, arg15: boolean, arg16: boolean, arg17: boolean, arg18: boolean, arg19: boolean, arg20: boolean, arg21: boolean, arg22: boolean, arg23: boolean, arg24: boolean, arg25: boolean, arg26: boolean, arg27: boolean, arg28: boolean, arg29: boolean, arg30: boolean): StdVideoH265SpsFlags;
    set(arg0: StdVideoH265SpsFlags): StdVideoH265SpsFlags;
    sizeof(): number;
    sps_curr_pic_ref_enabled_flag(): boolean;
    sps_curr_pic_ref_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    sps_extension_present_flag(): boolean;
    sps_extension_present_flag(arg0: boolean): StdVideoH265SpsFlags;
    sps_palette_predictor_initializer_present_flag(): boolean;
    sps_palette_predictor_initializer_present_flag(arg0: boolean): StdVideoH265SpsFlags;
    sps_palette_predictor_initializers_present_flag(): boolean;
    sps_palette_predictor_initializers_present_flag(arg0: boolean): StdVideoH265SpsFlags;
    sps_range_extension_flag(): boolean;
    sps_range_extension_flag(arg0: boolean): StdVideoH265SpsFlags;
    sps_scaling_list_data_present_flag(): boolean;
    sps_scaling_list_data_present_flag(arg0: boolean): StdVideoH265SpsFlags;
    sps_scc_extension_flag(): boolean;
    sps_scc_extension_flag(arg0: boolean): StdVideoH265SpsFlags;
    sps_sub_layer_ordering_info_present_flag(): boolean;
    sps_sub_layer_ordering_info_present_flag(arg0: boolean): StdVideoH265SpsFlags;
    sps_temporal_id_nesting_flag(): boolean;
    sps_temporal_id_nesting_flag(arg0: boolean): StdVideoH265SpsFlags;
    sps_temporal_mvp_enabled_flag(): boolean;
    sps_temporal_mvp_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    strong_intra_smoothing_enabled_flag(): boolean;
    strong_intra_smoothing_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    transform_skip_context_enabled_flag(): boolean;
    transform_skip_context_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    transform_skip_rotation_enabled_flag(): boolean;
    transform_skip_rotation_enabled_flag(arg0: boolean): StdVideoH265SpsFlags;
    vui_parameters_present_flag(): boolean;
    vui_parameters_present_flag(arg0: boolean): StdVideoH265SpsFlags;
}