import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { Consumer } from '../../../../java/util/function/Consumer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../../org/lwjgl/system/Struct$StructValidation.d.ts'
import type { StdVideoH265HrdParameters } from '../../../../org/lwjgl/vulkan/video/StdVideoH265HrdParameters.d.ts'
import type { StdVideoH265SpsVuiFlags } from '../../../../org/lwjgl/vulkan/video/StdVideoH265SpsVuiFlags.d.ts'
export class StdVideoH265SequenceParameterSetVui extends Struct<StdVideoH265SequenceParameterSetVui> implements NativeResource {
    static ALIGNOF: number;
    static ASPECT_RATIO_IDC: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CHROMA_SAMPLE_LOC_TYPE_BOTTOM_FIELD: number;
    static CHROMA_SAMPLE_LOC_TYPE_TOP_FIELD: number;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static COLOUR_PRIMARIES: number;
    static DEF_DISP_WIN_BOTTOM_OFFSET: number;
    static DEF_DISP_WIN_LEFT_OFFSET: number;
    static DEF_DISP_WIN_RIGHT_OFFSET: number;
    static DEF_DISP_WIN_TOP_OFFSET: number;
    static FLAGS: number;
    static LOG2_MAX_MV_LENGTH_HORIZONTAL: number;
    static LOG2_MAX_MV_LENGTH_VERTICAL: number;
    static MATRIX_COEFFS: number;
    static MAX_BITS_PER_MIN_CU_DENOM: number;
    static MAX_BYTES_PER_PIC_DENOM: number;
    static MIN_SPATIAL_SEGMENTATION_IDC: number;
    static PHRDPARAMETERS: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static RESERVED1: number;
    static RESERVED2: number;
    static RESERVED3: number;
    static SAR_HEIGHT: number;
    static SAR_WIDTH: number;
    static SIZEOF: number;
    static TRANSFER_CHARACTERISTICS: number;
    static VIDEO_FORMAT: number;
    static VUI_NUM_TICKS_POC_DIFF_ONE_MINUS1: number;
    static VUI_NUM_UNITS_IN_TICK: number;
    static VUI_TIME_SCALE: number;
    static calloc(): StdVideoH265SequenceParameterSetVui;
    static calloc(paramarg0: MemoryStack): StdVideoH265SequenceParameterSetVui;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): StdVideoH265SequenceParameterSetVui;
    static create(paramarg0: number): StdVideoH265SequenceParameterSetVui;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): StdVideoH265SequenceParameterSetVui;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): StdVideoH265SequenceParameterSetVui;
    static malloc(paramarg0: MemoryStack): StdVideoH265SequenceParameterSetVui;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static naspect_ratio_idc(paramarg0: number): number;
    static naspect_ratio_idc(paramarg0: number, paramarg1: number): void;
    static nchroma_sample_loc_type_bottom_field(paramarg0: number): number;
    static nchroma_sample_loc_type_bottom_field(paramarg0: number, paramarg1: number): void;
    static nchroma_sample_loc_type_top_field(paramarg0: number): number;
    static nchroma_sample_loc_type_top_field(paramarg0: number, paramarg1: number): void;
    static ncolour_primaries(paramarg0: number): number;
    static ncolour_primaries(paramarg0: number, paramarg1: number): void;
    static ndef_disp_win_bottom_offset(paramarg0: number): number;
    static ndef_disp_win_bottom_offset(paramarg0: number, paramarg1: number): void;
    static ndef_disp_win_left_offset(paramarg0: number): number;
    static ndef_disp_win_left_offset(paramarg0: number, paramarg1: number): void;
    static ndef_disp_win_right_offset(paramarg0: number): number;
    static ndef_disp_win_right_offset(paramarg0: number, paramarg1: number): void;
    static ndef_disp_win_top_offset(paramarg0: number): number;
    static ndef_disp_win_top_offset(paramarg0: number, paramarg1: number): void;
    static nflags(paramarg0: number): StdVideoH265SpsVuiFlags;
    static nflags(paramarg0: number, paramarg1: StdVideoH265SpsVuiFlags): void;
    static nlog2_max_mv_length_horizontal(paramarg0: number): number;
    static nlog2_max_mv_length_horizontal(paramarg0: number, paramarg1: number): void;
    static nlog2_max_mv_length_vertical(paramarg0: number): number;
    static nlog2_max_mv_length_vertical(paramarg0: number, paramarg1: number): void;
    static nmatrix_coeffs(paramarg0: number): number;
    static nmatrix_coeffs(paramarg0: number, paramarg1: number): void;
    static nmax_bits_per_min_cu_denom(paramarg0: number): number;
    static nmax_bits_per_min_cu_denom(paramarg0: number, paramarg1: number): void;
    static nmax_bytes_per_pic_denom(paramarg0: number): number;
    static nmax_bytes_per_pic_denom(paramarg0: number, paramarg1: number): void;
    static nmin_spatial_segmentation_idc(paramarg0: number): number;
    static nmin_spatial_segmentation_idc(paramarg0: number, paramarg1: number): void;
    static npHrdParameters(paramarg0: number): StdVideoH265HrdParameters;
    static npHrdParameters(paramarg0: number, paramarg1: StdVideoH265HrdParameters): void;
    static nreserved1(paramarg0: number): number;
    static nreserved1(paramarg0: number, paramarg1: number): void;
    static nreserved2(paramarg0: number): number;
    static nreserved2(paramarg0: number, paramarg1: number): void;
    static nreserved3(paramarg0: number): number;
    static nreserved3(paramarg0: number, paramarg1: number): void;
    static nsar_height(paramarg0: number): number;
    static nsar_height(paramarg0: number, paramarg1: number): void;
    static nsar_width(paramarg0: number): number;
    static nsar_width(paramarg0: number, paramarg1: number): void;
    static ntransfer_characteristics(paramarg0: number): number;
    static ntransfer_characteristics(paramarg0: number, paramarg1: number): void;
    static nvideo_format(paramarg0: number): number;
    static nvideo_format(paramarg0: number, paramarg1: number): void;
    static nvui_num_ticks_poc_diff_one_minus1(paramarg0: number): number;
    static nvui_num_ticks_poc_diff_one_minus1(paramarg0: number, paramarg1: number): void;
    static nvui_num_units_in_tick(paramarg0: number): number;
    static nvui_num_units_in_tick(paramarg0: number, paramarg1: number): void;
    static nvui_time_scale(paramarg0: number): number;
    static nvui_time_scale(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    aspect_ratio_idc(): number;
    aspect_ratio_idc(arg0: number): StdVideoH265SequenceParameterSetVui;
    chroma_sample_loc_type_bottom_field(): number;
    chroma_sample_loc_type_bottom_field(arg0: number): StdVideoH265SequenceParameterSetVui;
    chroma_sample_loc_type_top_field(): number;
    chroma_sample_loc_type_top_field(arg0: number): StdVideoH265SequenceParameterSetVui;
    close(): void;
    colour_primaries(): number;
    colour_primaries(arg0: number): StdVideoH265SequenceParameterSetVui;
    create(arg0: number, arg1: ByteBuffer): StdVideoH265SequenceParameterSetVui;
    def_disp_win_bottom_offset(): number;
    def_disp_win_bottom_offset(arg0: number): StdVideoH265SequenceParameterSetVui;
    def_disp_win_left_offset(): number;
    def_disp_win_left_offset(arg0: number): StdVideoH265SequenceParameterSetVui;
    def_disp_win_right_offset(): number;
    def_disp_win_right_offset(arg0: number): StdVideoH265SequenceParameterSetVui;
    def_disp_win_top_offset(): number;
    def_disp_win_top_offset(arg0: number): StdVideoH265SequenceParameterSetVui;
    flags(): StdVideoH265SpsVuiFlags;
    flags(arg0: (param0: StdVideoH265SpsVuiFlags) => void): StdVideoH265SequenceParameterSetVui;
    flags(arg0: StdVideoH265SpsVuiFlags): StdVideoH265SequenceParameterSetVui;
    log2_max_mv_length_horizontal(): number;
    log2_max_mv_length_horizontal(arg0: number): StdVideoH265SequenceParameterSetVui;
    log2_max_mv_length_vertical(): number;
    log2_max_mv_length_vertical(arg0: number): StdVideoH265SequenceParameterSetVui;
    matrix_coeffs(): number;
    matrix_coeffs(arg0: number): StdVideoH265SequenceParameterSetVui;
    max_bits_per_min_cu_denom(): number;
    max_bits_per_min_cu_denom(arg0: number): StdVideoH265SequenceParameterSetVui;
    max_bytes_per_pic_denom(): number;
    max_bytes_per_pic_denom(arg0: number): StdVideoH265SequenceParameterSetVui;
    min_spatial_segmentation_idc(): number;
    min_spatial_segmentation_idc(arg0: number): StdVideoH265SequenceParameterSetVui;
    pHrdParameters(): StdVideoH265HrdParameters;
    pHrdParameters(arg0: StdVideoH265HrdParameters): StdVideoH265SequenceParameterSetVui;
    sar_height(): number;
    sar_height(arg0: number): StdVideoH265SequenceParameterSetVui;
    sar_width(): number;
    sar_width(arg0: number): StdVideoH265SequenceParameterSetVui;
    set(arg0: StdVideoH265SequenceParameterSetVui): StdVideoH265SequenceParameterSetVui;
    set(arg0: StdVideoH265SpsVuiFlags, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number, arg15: number, arg16: number, arg17: number, arg18: number, arg19: number, arg20: number, arg21: number, arg22: StdVideoH265HrdParameters): StdVideoH265SequenceParameterSetVui;
    sizeof(): number;
    transfer_characteristics(): number;
    transfer_characteristics(arg0: number): StdVideoH265SequenceParameterSetVui;
    video_format(): number;
    video_format(arg0: number): StdVideoH265SequenceParameterSetVui;
    vui_num_ticks_poc_diff_one_minus1(): number;
    vui_num_ticks_poc_diff_one_minus1(arg0: number): StdVideoH265SequenceParameterSetVui;
    vui_num_units_in_tick(): number;
    vui_num_units_in_tick(arg0: number): StdVideoH265SequenceParameterSetVui;
    vui_time_scale(): number;
    vui_time_scale(arg0: number): StdVideoH265SequenceParameterSetVui;
}