import type { TruffleString } from '../../../../../../../com/oracle/truffle/api/strings/TruffleString.d.ts'
import type { IntRingBuffer } from '../../../../../../../com/oracle/truffle/regex/tregex/buffer/IntRingBuffer.d.ts'
import type { PureNFATransition } from '../../../../../../../com/oracle/truffle/regex/tregex/nfa/PureNFATransition.d.ts'
import type { TRegexExecutorLocals } from '../../../../../../../com/oracle/truffle/regex/tregex/nodes/TRegexExecutorLocals.d.ts'
import type { TRegexBacktrackingNFAExecutorLocals$Stack } from '../../../../../../../com/oracle/truffle/regex/tregex/nodes/nfa/TRegexBacktrackingNFAExecutorLocals$Stack.d.ts'
export class TRegexBacktrackingNFAExecutorLocals extends TRegexExecutorLocals {
    static create(paraminput: TruffleString, paramfromIndex: number, parammaxIndex: number, paramregionFrom: number, paramregionTo: number, paramindex: number, paramnCaptureGroups: number, paramnQuantifiers: number, paramnZeroWidthQuantifiers: number, paramzeroWidthTermEnclosedCGLow: number[], paramzeroWidthQuantifierCGOffsets: number[], paramallocateStackFrameBuffer: boolean, parammaxNTransitions: number, paramtrackLastGroup: boolean, paramdontOverwriteLastGroup: boolean, paramrecursiveBackrefs: boolean, parambackrefMultiCharExpansion: boolean, parammatchBoundaryAssertions: boolean): TRegexBacktrackingNFAExecutorLocals;
    private constructor(input: TruffleString, fromIndex: number, maxIndex: number, regionFrom: number, regionTo: number, index: number, nCaptureGroups: number, nQuantifiers: number, nZeroWidthQuantifiers: number, zeroWidthTermEnclosedCGLow: number[], zeroWidthQuantifierCGOffsets: number[], stackFrameBuffer: number[], stack: TRegexBacktrackingNFAExecutorLocals$Stack, stackBase: number, stackFrameSize: number, transitionBitSet: number[], trackLastGroup: boolean, dontOverwriteLastGroup: boolean, recursiveBackReferences: boolean, matchBoundaryAssertions: boolean, backrefMultiCharExpansionBufferA: IntRingBuffer, backrefMultiCharExpansionBufferB: IntRingBuffer)
    readonly backrefMultiCharExpansionBufferA: IntRingBuffer;
    readonly backrefMultiCharExpansionBufferB: IntRingBuffer;
    // private dontOverwriteLastGroup: boolean;
    readonly lastInitialStateIndex: number;
    readonly lastInnerLiteralIndex: number;
    // private lastResultIndex: number;
    // private lastResultSp: number;
    // private matchBoundaryAssertions: boolean;
    // private nQuantifierCounts: number;
    // private nZeroWidthQuantifiers: number;
    // private recursiveBackReferences: boolean;
    // private result: number[];
    // private sp: number;
    // private stack: TRegexBacktrackingNFAExecutorLocals$Stack;
    // private stackBase: number;
    readonly stackFrameBuffer: number[];
    // private stackFrameSize: number;
    // private trackLastGroup: boolean;
    readonly transitionBitSet: number[];
    // private zeroWidthQuantifierCGOffsets: number[];
    // private zeroWidthTermEnclosedCGLow: number[];
    apply(t: PureNFATransition, index: number): void;
    canPop(): boolean;
    canPopResult(): boolean;
    // private clearCaptureGroups(): void;
    // private clearFlag(flag: number): void;
    clearMatchEndAssertionTraversed(): void;
    // private clearQuantifierCounts(): void;
    // private clearRecursiveCaptureGroups(): void;
    createSubNFALocals(t: PureNFATransition, newDontOverwriteLastGroup: boolean): TRegexBacktrackingNFAExecutorLocals;
    createSubNFALocals(newDontOverwriteLastGroup: boolean): TRegexBacktrackingNFAExecutorLocals;
    dupFrame(): void;
    dupFrame(n: number): void;
    // private ensureSize(minSize: number): void;
    getBackrefMultiCharExpansionBufferA(): IntRingBuffer;
    getBackrefMultiCharExpansionBufferB(): IntRingBuffer;
    getCaptureGroupBoundary(boundary: number): number;
    getCaptureGroupEnd(groupNumber: number): number;
    getCaptureGroupStart(groupNumber: number): number;
    getLastInitialStateIndex(): number;
    getLastInnerLiteralIndex(): number;
    getPc(): number;
    getQuantifierCount(quantifierIndex: number): number;
    getRecursiveCaptureGroupStart(groupNumber: number): number;
    getStackFrameBuffer(): number[];
    getTransitionBitSet(): number[];
    getZeroWidthQuantifierGuardIndex(quantifierZeroWidthIndex: number): number;
    incQuantifierCount(quantifierIndex: number): void;
    // private isFlagSet(flag: number): boolean;
    isMatchEndAssertionTraversed(): boolean;
    isResultUnmodifiedByZeroWidthQuantifier(quantifierZeroWidthIndex: number): boolean;
    // private newSubLocals(newDontOverwriteLastGroup: boolean): TRegexBacktrackingNFAExecutorLocals;
    // private offsetCaptureGroups(): number;
    // private offsetCaptureGroups(framePointer: number): number;
    // private offsetFlags(): number;
    // private offsetIP(): number;
    // private offsetLastGroup(): number;
    // private offsetQuantifierCount(quantifierIndex: number): number;
    // private offsetQuantifierCounts(): number;
    // private offsetRecursiveBackReferences(): number;
    // private offsetZeroWidthQuantifierCG(): number;
    // private offsetZeroWidthQuantifierCG(zeroWidthIndex: number): number;
    // private offsetZeroWidthQuantifierIndex(quantifierZeroWidthIndex: number): number;
    // private offsetZeroWidthQuantifierIndices(): number;
    overwriteCaptureGroups(captureGroups: number[]): void;
    pop(): number;
    popResult(): number[];
    printStack(curPc: number): void;
    push(): void;
    pushFrame(frame: number[]): void;
    pushResult(): void;
    pushResult(t: PureNFATransition, index: number): void;
    readFrame(to: number[]): void;
    resetToInitialState(): void;
    restoreIndex(): void;
    saveIndex(index: number): void;
    saveRecursiveBackrefGroupStart(groupNumber: number): void;
    setCaptureGroupBoundary(boundary: number, index: number): void;
    // private setFlag(flag: number): void;
    setLastGroup(newLastGroup: number): void;
    setLastInitialStateIndex(i: number): void;
    setLastInnerLiteralIndex(i: number): void;
    setMatchEndAssertionTraversed(): void;
    setPc(pc: number): number;
    setQuantifierCount(quantifierIndex: number, count: number): void;
    setResult(): void;
    setZeroWidthQuantifierGuardIndex(quantifierZeroWidthIndex: number): void;
    setZeroWidthQuantifierResults(quantifierZeroWidthIndex: number): void;
    // private stack(): number[];
    writeFrame(from: number[]): void;
}