import type { Pointer } from '../../../../../../com/sun/jna/Pointer.d.ts'
import type { Structure } from '../../../../../../com/sun/jna/Structure.d.ts'
import type { Class } from '../../../../../../java/lang/Class.d.ts'
import type { Object } from '../../../../../../java/lang/Object.d.ts'
export class Perfstat$perfstat_cpu_t extends Structure {
    static ALIGN_DEFAULT: number;
    static ALIGN_GNUC: number;
    static ALIGN_MSVC: number;
    static ALIGN_NONE: number;
    static autoRead(paramarg0: (Object | null)[]): void;
    static autoWrite(paramarg0: (Object | null)[]): void;
    static createFieldsOrder(paramarg0: string): string[];
    static createFieldsOrder(paramarg0: (Object | null)[]): string[];
    static createFieldsOrder(paramarg0: string[], paramarg1: (Object | null)[]): string[];
    static createFieldsOrder(paramarg0: string[], paramarg1: string[]): string[];
    static newInstance(paramarg0: Class<Object>): Object | null;
    static newInstance(paramarg0: Class<Object>, paramarg1: Pointer): Object | null;
    constructor()
    bound: number;
    bread: number;
    busy_donated_purr: number;
    busy_donated_spurr: number;
    busy_stolen_purr: number;
    busy_stolen_spurr: number;
    bwrite: number;
    cswitches: number;
    decrintrs: number;
    devintrs: number;
    dirblk: number;
    fardispatch: number;
    hpi: number;
    hpit: number;
    idle: number;
    idle_donated_purr: number;
    idle_donated_spurr: number;
    idle_stolen_purr: number;
    idle_stolen_spurr: number;
    iget: number;
    invol_cswitch: number;
    localdispatch: number;
    lread: number;
    lwrite: number;
    majfaults: number;
    migration_S3grq: number;
    migration_S3pul: number;
    migration_push: number;
    minfaults: number;
    mpcrintrs: number;
    mpcsintrs: number;
    msg: number;
    name: number[];
    namei: number;
    neardispatch: number;
    phantintrs: number;
    phread: number;
    phwrite: number;
    pidle: number;
    pidle_spurr: number;
    pswitch: number;
    psys: number;
    psys_spurr: number;
    puser: number;
    puser_spurr: number;
    pwait: number;
    pwait_spurr: number;
    readch: number;
    redisp_sd0: number;
    redisp_sd1: number;
    redisp_sd2: number;
    redisp_sd3: number;
    redisp_sd4: number;
    redisp_sd5: number;
    runque: number;
    sema: number;
    softintrs: number;
    spurrflag: number;
    sys: number;
    syscall: number;
    sysexec: number;
    sysfork: number;
    sysread: number;
    syswrite: number;
    tb_last: number;
    user: number;
    version: number;
    vol_cswitch: number;
    wait: number;
    writech: number;
}