import type { AttributedCharacterIterator$Attribute } from '../../../java/text/AttributedCharacterIterator$Attribute.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
export class TextAttribute extends AttributedCharacterIterator$Attribute {
    static BACKGROUND: TextAttribute;
    static BIDI_EMBEDDING: TextAttribute;
    static CHAR_REPLACEMENT: TextAttribute;
    static FAMILY: TextAttribute;
    static FONT: TextAttribute;
    static FOREGROUND: TextAttribute;
    static INPUT_METHOD_HIGHLIGHT: TextAttribute;
    static INPUT_METHOD_SEGMENT: AttributedCharacterIterator$Attribute;
    static INPUT_METHOD_UNDERLINE: TextAttribute;
    static JUSTIFICATION: TextAttribute;
    static JUSTIFICATION_FULL: number;
    static JUSTIFICATION_NONE: number;
    static KERNING: TextAttribute;
    static KERNING_ON: number;
    static LANGUAGE: AttributedCharacterIterator$Attribute;
    static LIGATURES: TextAttribute;
    static LIGATURES_ON: number;
    static NUMERIC_SHAPING: TextAttribute;
    static POSTURE: TextAttribute;
    static POSTURE_OBLIQUE: number;
    static POSTURE_REGULAR: number;
    static READING: AttributedCharacterIterator$Attribute;
    static RUN_DIRECTION: TextAttribute;
    static RUN_DIRECTION_LTR: boolean;
    static RUN_DIRECTION_RTL: boolean;
    static SIZE: TextAttribute;
    static STRIKETHROUGH: TextAttribute;
    static STRIKETHROUGH_ON: boolean;
    static SUPERSCRIPT: TextAttribute;
    static SUPERSCRIPT_SUB: number;
    static SUPERSCRIPT_SUPER: number;
    static SWAP_COLORS: TextAttribute;
    static SWAP_COLORS_ON: boolean;
    static TRACKING: TextAttribute;
    static TRACKING_LOOSE: number;
    static TRACKING_TIGHT: number;
    static TRANSFORM: TextAttribute;
    static UNDERLINE: TextAttribute;
    static UNDERLINE_LOW_DASHED: number;
    static UNDERLINE_LOW_DOTTED: number;
    static UNDERLINE_LOW_GRAY: number;
    static UNDERLINE_LOW_ONE_PIXEL: number;
    static UNDERLINE_LOW_TWO_PIXEL: number;
    static UNDERLINE_ON: number;
    static WEIGHT: TextAttribute;
    static WEIGHT_BOLD: number;
    static WEIGHT_DEMIBOLD: number;
    static WEIGHT_DEMILIGHT: number;
    static WEIGHT_EXTRABOLD: number;
    static WEIGHT_EXTRA_LIGHT: number;
    static WEIGHT_HEAVY: number;
    static WEIGHT_LIGHT: number;
    static WEIGHT_MEDIUM: number;
    static WEIGHT_REGULAR: number;
    static WEIGHT_SEMIBOLD: number;
    static WEIGHT_ULTRABOLD: number;
    static WIDTH: TextAttribute;
    static WIDTH_CONDENSED: number;
    static WIDTH_EXTENDED: number;
    static WIDTH_REGULAR: number;
    static WIDTH_SEMI_CONDENSED: number;
    static WIDTH_SEMI_EXTENDED: number;
    constructor(arg0: string)
    readResolve(): Object;
}