import type { Device } from '../../../../ai/djl/Device.d.ts'
import type { NDIndex } from '../../../../ai/djl/ndarray/index/NDIndex.d.ts'
import type { DataType } from '../../../../ai/djl/ndarray/types/DataType.d.ts'
import type { Shape } from '../../../../ai/djl/ndarray/types/Shape.d.ts'
import type { SparseFormat } from '../../../../ai/djl/ndarray/types/SparseFormat.d.ts'
import type { RNN$Activation } from '../../../../ai/djl/nn/recurrent/RNN$Activation.d.ts'
import type { PtNDArray } from '../../../../ai/djl/pytorch/engine/PtNDArray.d.ts'
import type { PtNDManager } from '../../../../ai/djl/pytorch/engine/PtNDManager.d.ts'
import type { PtSymbolBlock } from '../../../../ai/djl/pytorch/engine/PtSymbolBlock.d.ts'
import type { InputStream } from '../../../../java/io/InputStream.d.ts'
import type { OutputStream } from '../../../../java/io/OutputStream.d.ts'
import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { Path } from '../../../../java/nio/file/Path.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { Number } from '../../../../java/lang/Number.d.ts'
export class JniUtils extends Object {
    static abs(paramarg0: PtNDArray): PtNDArray;
    static acos(paramarg0: PtNDArray): PtNDArray;
    static adamUpdate(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: PtNDArray, paramarg3: PtNDArray, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number, paramarg12: boolean): void;
    static adaptiveAvgPool(paramarg0: PtNDArray, paramarg1: Shape): PtNDArray;
    static adaptiveMaxPool(paramarg0: PtNDArray, paramarg1: Shape): PtNDArray;
    static add(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static addi(paramarg0: PtNDArray, paramarg1: PtNDArray): void;
    static all(paramarg0: PtNDArray): PtNDArray;
    static any(paramarg0: PtNDArray): PtNDArray;
    static arange(paramarg0: PtNDManager, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: DataType, paramarg5: Device, paramarg6: SparseFormat): PtNDArray;
    static argMax(paramarg0: PtNDArray): PtNDArray;
    static argMax(paramarg0: PtNDArray, paramarg1: number, paramarg2: boolean): PtNDArray;
    static argMin(paramarg0: PtNDArray): PtNDArray;
    static argMin(paramarg0: PtNDArray, paramarg1: number, paramarg2: boolean): PtNDArray;
    static argSort(paramarg0: PtNDArray, paramarg1: number, paramarg2: boolean): PtNDArray;
    static asin(paramarg0: PtNDArray): PtNDArray;
    static atan(paramarg0: PtNDArray): PtNDArray;
    static atan2(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static attachGradient(paramarg0: PtNDArray, paramarg1: boolean): void;
    static avgPool(paramarg0: PtNDArray, paramarg1: Shape, paramarg2: Shape, paramarg3: Shape, paramarg4: boolean, paramarg5: boolean): PtNDArray;
    static backward(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: boolean, paramarg3: boolean): void;
    static batchNorm(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: PtNDArray, paramarg3: PtNDArray, paramarg4: PtNDArray, paramarg5: boolean, paramarg6: number, paramarg7: number): PtNDArray;
    static bmm(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static booleanMask(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static booleanMaskSet(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: PtNDArray): void;
    static broadcast(paramarg0: PtNDArray, paramarg1: Shape): PtNDArray;
    static cat(paramarg0: (Object | null)[], paramarg1: number): PtNDArray;
    static ceil(paramarg0: PtNDArray): PtNDArray;
    static clip(paramarg0: PtNDArray, paramarg1: Number, paramarg2: Number): PtNDArray;
    static clone(paramarg0: PtNDArray): PtNDArray;
    static complex(paramarg0: PtNDArray): PtNDArray;
    static conj(paramarg0: PtNDArray): PtNDArray;
    static contentEqual(paramarg0: PtNDArray, paramarg1: PtNDArray): boolean;
    static convolution(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: PtNDArray, paramarg3: Shape, paramarg4: Shape, paramarg5: Shape, paramarg6: number): PtNDArray;
    static cos(paramarg0: PtNDArray): PtNDArray;
    static cosh(paramarg0: PtNDArray): PtNDArray;
    static createEmptyNdArray(paramarg0: PtNDManager, paramarg1: Shape, paramarg2: DataType, paramarg3: Device, paramarg4: SparseFormat): PtNDArray;
    static createNdFromByteBuffer(paramarg0: PtNDManager, paramarg1: ByteBuffer, paramarg2: Shape, paramarg3: DataType, paramarg4: SparseFormat, paramarg5: Device): PtNDArray;
    static createOnesNdArray(paramarg0: PtNDManager, paramarg1: Shape, paramarg2: DataType, paramarg3: Device, paramarg4: SparseFormat): PtNDArray;
    static createSparseCoo(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: Shape): PtNDArray;
    static createZerosNdArray(paramarg0: PtNDManager, paramarg1: Shape, paramarg2: DataType, paramarg3: Device, paramarg4: SparseFormat): PtNDArray;
    static cumProd(paramarg0: PtNDArray, paramarg1: number, paramarg2: DataType): PtNDArray;
    static cumSum(paramarg0: PtNDArray, paramarg1: number): PtNDArray;
    static deleteModule(paramarg0: number): void;
    static deleteNDArray(paramarg0: number): void;
    static detachGradient(paramarg0: PtNDArray): PtNDArray;
    static diagonal(paramarg0: PtNDArray, paramarg1: number, paramarg2: number, paramarg3: number): PtNDArray;
    static diff(paramarg0: PtNDArray, paramarg1: number, paramarg2: number): PtNDArray;
    static div(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static divi(paramarg0: PtNDArray, paramarg1: PtNDArray): void;
    static dot(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static dropout(paramarg0: PtNDArray, paramarg1: number, paramarg2: boolean): PtNDArray;
    static elu(paramarg0: PtNDArray, paramarg1: number): PtNDArray;
    static embedding(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: boolean): PtNDArray;
    static emptyCudaCache(): void;
    static enableInferenceMode(paramarg0: PtSymbolBlock): void;
    static enableTrainingMode(paramarg0: PtSymbolBlock): void;
    static eq(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static erf(paramarg0: PtNDArray): PtNDArray;
    static erfinv(paramarg0: PtNDArray): PtNDArray;
    static exp(paramarg0: PtNDArray): PtNDArray;
    static eye(paramarg0: PtNDManager, paramarg1: number, paramarg2: number, paramarg3: DataType, paramarg4: Device, paramarg5: SparseFormat): PtNDArray;
    static fft(paramarg0: PtNDArray, paramarg1: number, paramarg2: number): PtNDArray;
    static fft2(paramarg0: PtNDArray, paramarg1: number[], paramarg2: number[]): PtNDArray;
    static flatten(paramarg0: PtNDArray, paramarg1: number, paramarg2: number): PtNDArray;
    static flip(paramarg0: PtNDArray, paramarg1: number[]): PtNDArray;
    static floor(paramarg0: PtNDArray): PtNDArray;
    static full(paramarg0: PtNDManager, paramarg1: Shape, paramarg2: number, paramarg3: DataType, paramarg4: Device, paramarg5: SparseFormat): PtNDArray;
    static gammaln(paramarg0: PtNDArray): PtNDArray;
    static gather(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: number): PtNDArray;
    static gelu(paramarg0: PtNDArray): PtNDArray;
    static getByteBuffer(paramarg0: PtNDArray, paramarg1: boolean): ByteBuffer;
    static getDataType(paramarg0: PtNDArray): DataType;
    static getDevice(paramarg0: PtNDArray): Device;
    static getFeatures(): string[];
    static getGradient(paramarg0: PtNDArray): PtNDArray;
    static getGradientFunctionNames(paramarg0: PtNDArray): string;
    static getItem(paramarg0: PtNDArray, paramarg1: number[], paramarg2: PtNDManager): PtNDArray;
    static getLayout(paramarg0: PtNDArray): number;
    static getMethodNames(paramarg0: PtSymbolBlock): (Object | null)[];
    static getNumInteropThreads(): number;
    static getNumThreads(): number;
    static getShape(paramarg0: PtNDArray): Shape;
    static getSparseFormat(paramarg0: PtNDArray): SparseFormat;
    static gru(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: (Object | null)[], paramarg3: boolean, paramarg4: number, paramarg5: number, paramarg6: boolean, paramarg7: boolean, paramarg8: boolean): (Object | null)[];
    static gt(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static gte(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static hannWindow(paramarg0: PtNDManager, paramarg1: number, paramarg2: boolean, paramarg3: Device): PtNDArray;
    static ifft(paramarg0: PtNDArray, paramarg1: number, paramarg2: number): PtNDArray;
    static ifft2(paramarg0: PtNDArray, paramarg1: number[], paramarg2: number[]): PtNDArray;
    static index(paramarg0: PtNDArray, paramarg1: number[], paramarg2: number[], paramarg3: number[], paramarg4: PtNDManager): PtNDArray;
    static indexAdv(paramarg0: PtNDArray, paramarg1: NDIndex, paramarg2: PtNDManager): PtNDArray;
    static indexAdvPut(paramarg0: PtNDArray, paramarg1: NDIndex, paramarg2: PtNDArray): void;
    static indexSet(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: number[], paramarg3: number[], paramarg4: number[]): void;
    static interpolate(paramarg0: PtNDArray, paramarg1: number[], paramarg2: number, paramarg3: boolean): PtNDArray;
    static inverse(paramarg0: PtNDArray): PtNDArray;
    static irfft(paramarg0: PtNDArray, paramarg1: number, paramarg2: number): PtNDArray;
    static isGradMode(): boolean;
    static isInf(paramarg0: PtNDArray): PtNDArray;
    static isNaN(paramarg0: PtNDArray): PtNDArray;
    static layerNorm(paramarg0: PtNDArray, paramarg1: Shape, paramarg2: PtNDArray, paramarg3: PtNDArray, paramarg4: number): PtNDArray;
    static leakyRelu(paramarg0: PtNDArray, paramarg1: number): PtNDArray;
    static linear(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: PtNDArray): PtNDArray;
    static linspace(paramarg0: PtNDManager, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: DataType, paramarg5: Device, paramarg6: SparseFormat): PtNDArray;
    static loadModule(paramarg0: PtNDManager, paramarg1: InputStream, paramarg2: boolean, paramarg3: boolean): PtSymbolBlock;
    static loadModule(paramarg0: PtNDManager, paramarg1: Path[][], paramarg2: boolean, paramarg3: (Object | null)[], paramarg4: (Object | null)[], paramarg5: boolean): PtSymbolBlock;
    static loadModuleHandle(paramarg0: InputStream, paramarg1: Device, paramarg2: boolean, paramarg3: boolean): number;
    static log(paramarg0: PtNDArray): PtNDArray;
    static log10(paramarg0: PtNDArray): PtNDArray;
    static log2(paramarg0: PtNDArray): PtNDArray;
    static logSoftmax(paramarg0: PtNDArray, paramarg1: number, paramarg2: DataType): PtNDArray;
    static logicalAnd(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static logicalNot(paramarg0: PtNDArray): PtNDArray;
    static logicalOr(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static logicalXor(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static lpPool(paramarg0: PtNDArray, paramarg1: number, paramarg2: Shape, paramarg3: Shape, paramarg4: boolean): PtNDArray;
    static lstm(paramarg0: PtNDArray, paramarg1: (Object | null)[], paramarg2: (Object | null)[], paramarg3: boolean, paramarg4: number, paramarg5: number, paramarg6: boolean, paramarg7: boolean, paramarg8: boolean): (Object | null)[];
    static lt(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static lte(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static matmul(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static max(paramarg0: PtNDArray): PtNDArray;
    static max(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static max(paramarg0: PtNDArray, paramarg1: number, paramarg2: boolean): PtNDArray;
    static maxPool(paramarg0: PtNDArray, paramarg1: Shape, paramarg2: Shape, paramarg3: Shape, paramarg4: boolean): PtNDArray;
    static mean(paramarg0: PtNDArray): PtNDArray;
    static mean(paramarg0: PtNDArray, paramarg1: number, paramarg2: boolean): PtNDArray;
    static median(paramarg0: PtNDArray, paramarg1: number, paramarg2: boolean): (Object | null)[];
    static min(paramarg0: PtNDArray): PtNDArray;
    static min(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static min(paramarg0: PtNDArray, paramarg1: number, paramarg2: boolean): PtNDArray;
    static moduleGetParams(paramarg0: PtSymbolBlock, paramarg1: PtNDManager): (Object | null)[];
    static mul(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static muli(paramarg0: PtNDArray, paramarg1: PtNDArray): void;
    static neg(paramarg0: PtNDArray): PtNDArray;
    static negi(paramarg0: PtNDArray): void;
    static neq(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static nonZeros(paramarg0: PtNDArray): PtNDArray;
    static none(paramarg0: PtNDArray): PtNDArray;
    static norm(paramarg0: PtNDArray, paramarg1: number, paramarg2: number[], paramarg3: boolean): PtNDArray;
    static normal(paramarg0: PtNDManager, paramarg1: number, paramarg2: number, paramarg3: Shape, paramarg4: DataType, paramarg5: Device): PtNDArray;
    static normalize(paramarg0: PtNDArray, paramarg1: number, paramarg2: number, paramarg3: number): PtNDArray;
    static oneHot(paramarg0: PtNDArray, paramarg1: number, paramarg2: DataType): PtNDArray;
    static onesLike(paramarg0: PtNDArray, paramarg1: DataType, paramarg2: Device, paramarg3: SparseFormat): PtNDArray;
    static pad(paramarg0: PtNDArray, paramarg1: number[], paramarg2: number): PtNDArray;
    static percentile(paramarg0: PtNDArray, paramarg1: Number, paramarg2: number, paramarg3: boolean): PtNDArray;
    static permute(paramarg0: PtNDArray, paramarg1: number[]): PtNDArray;
    static pick(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: number): PtNDArray;
    static pow(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static powi(paramarg0: PtNDArray, paramarg1: PtNDArray): void;
    static prod(paramarg0: PtNDArray): PtNDArray;
    static prod(paramarg0: PtNDArray, paramarg1: number, paramarg2: boolean): PtNDArray;
    static put(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: PtNDArray): PtNDArray;
    static randint(paramarg0: PtNDManager, paramarg1: number, paramarg2: number, paramarg3: Shape, paramarg4: DataType, paramarg5: Device): PtNDArray;
    static randperm(paramarg0: PtNDManager, paramarg1: number, paramarg2: DataType, paramarg3: Device): PtNDArray;
    static real(paramarg0: PtNDArray): PtNDArray;
    static relu(paramarg0: PtNDArray): PtNDArray;
    static remainder(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static remainderi(paramarg0: PtNDArray, paramarg1: PtNDArray): void;
    static repeat(paramarg0: PtNDArray, paramarg1: number, paramarg2: number): PtNDArray;
    static requiresGrad(paramarg0: PtNDArray): boolean;
    static reshape(paramarg0: PtNDArray, paramarg1: number[]): PtNDArray;
    static rfft(paramarg0: PtNDArray, paramarg1: number, paramarg2: number): PtNDArray;
    static rnn(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: (Object | null)[], paramarg3: boolean, paramarg4: number, paramarg5: RNN$Activation, paramarg6: number, paramarg7: boolean, paramarg8: boolean, paramarg9: boolean): (Object | null)[];
    static rot90(paramarg0: PtNDArray, paramarg1: number, paramarg2: number[]): PtNDArray;
    static round(paramarg0: PtNDArray): PtNDArray;
    static scatter(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: PtNDArray, paramarg3: number): PtNDArray;
    static selu(paramarg0: PtNDArray): PtNDArray;
    static set(paramarg0: PtNDArray, paramarg1: ByteBuffer): void;
    static setBenchmarkCuDNN(paramarg0: boolean): void;
    static setGradMode(paramarg0: boolean): void;
    static setGraphExecutorOptimize(paramarg0: boolean): void;
    static setNumInteropThreads(paramarg0: number): void;
    static setNumThreads(paramarg0: number): void;
    static setSeed(paramarg0: number): void;
    static sgdUpdate(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: PtNDArray, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static sigmoid(paramarg0: PtNDArray): PtNDArray;
    static sign(paramarg0: PtNDArray): PtNDArray;
    static signi(paramarg0: PtNDArray): void;
    static sin(paramarg0: PtNDArray): PtNDArray;
    static sinh(paramarg0: PtNDArray): PtNDArray;
    static slice(paramarg0: PtNDArray, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): PtNDArray;
    static softPlus(paramarg0: PtNDArray): PtNDArray;
    static softSign(paramarg0: PtNDArray): PtNDArray;
    static softmax(paramarg0: PtNDArray, paramarg1: number, paramarg2: DataType): PtNDArray;
    static sort(paramarg0: PtNDArray, paramarg1: number, paramarg2: boolean): PtNDArray;
    static split(paramarg0: PtNDArray, paramarg1: number, paramarg2: number): (Object | null)[];
    static split(paramarg0: PtNDArray, paramarg1: number[], paramarg2: number): (Object | null)[];
    static sqrt(paramarg0: PtNDArray): PtNDArray;
    static square(paramarg0: PtNDArray): PtNDArray;
    static squeeze(paramarg0: PtNDArray): PtNDArray;
    static squeeze(paramarg0: PtNDArray, paramarg1: number): PtNDArray;
    static stack(paramarg0: (Object | null)[], paramarg1: number): PtNDArray;
    static startProfile(paramarg0: boolean, paramarg1: boolean, paramarg2: boolean): void;
    static stft(paramarg0: PtNDArray, paramarg1: number, paramarg2: number, paramarg3: PtNDArray, paramarg4: boolean, paramarg5: boolean, paramarg6: boolean): PtNDArray;
    static stopProfile(paramarg0: string): void;
    static sub(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static subi(paramarg0: PtNDArray, paramarg1: PtNDArray): void;
    static sum(paramarg0: PtNDArray): PtNDArray;
    static sum(paramarg0: PtNDArray, paramarg1: number[], paramarg2: boolean): PtNDArray;
    static take(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: PtNDManager): PtNDArray;
    static tan(paramarg0: PtNDArray): PtNDArray;
    static tanh(paramarg0: PtNDArray): PtNDArray;
    static tile(paramarg0: PtNDArray, paramarg1: number[]): PtNDArray;
    static to(paramarg0: PtNDArray, paramarg1: DataType, paramarg2: Device): PtNDArray;
    static toDense(paramarg0: PtNDArray): PtNDArray;
    static toSparse(paramarg0: PtNDArray): PtNDArray;
    static topK(paramarg0: PtNDArray, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: boolean): (Object | null)[];
    static transpose(paramarg0: PtNDArray, paramarg1: number, paramarg2: number): PtNDArray;
    static trunc(paramarg0: PtNDArray): PtNDArray;
    static uniform(paramarg0: PtNDManager, paramarg1: number, paramarg2: number, paramarg3: Shape, paramarg4: DataType, paramarg5: Device): PtNDArray;
    static unique(paramarg0: PtNDArray, paramarg1: number, paramarg2: boolean, paramarg3: boolean, paramarg4: boolean): (Object | null)[];
    static unsqueeze(paramarg0: PtNDArray, paramarg1: number): PtNDArray;
    static where(paramarg0: PtNDArray, paramarg1: PtNDArray, paramarg2: PtNDArray): PtNDArray;
    static writeModule(paramarg0: PtSymbolBlock, paramarg1: OutputStream, paramarg2: boolean): void;
    static xlogy(paramarg0: PtNDArray, paramarg1: PtNDArray): PtNDArray;
    static zeroGrad(paramarg0: PtNDArray): void;
    static zerosLike(paramarg0: PtNDArray, paramarg1: DataType, paramarg2: Device, paramarg3: SparseFormat): PtNDArray;
    private constructor()
}