import type { NativeLong } from '../../../../../../com/sun/jna/NativeLong.d.ts'
import type { Pointer } from '../../../../../../com/sun/jna/Pointer.d.ts'
import type { Structure } from '../../../../../../com/sun/jna/Structure.d.ts'
import type { Class } from '../../../../../../java/lang/Class.d.ts'
import type { Object } from '../../../../../../java/lang/Object.d.ts'
export class Perfstat$perfstat_cpu_total_t extends Structure {
    static ALIGN_DEFAULT: number;
    static ALIGN_GNUC: number;
    static ALIGN_MSVC: number;
    static ALIGN_NONE: number;
    static autoRead(paramarg0: (Object | null)[]): void;
    static autoWrite(paramarg0: (Object | null)[]): void;
    static createFieldsOrder(paramarg0: string): string[];
    static createFieldsOrder(paramarg0: (Object | null)[]): string[];
    static createFieldsOrder(paramarg0: string[], paramarg1: (Object | null)[]): string[];
    static createFieldsOrder(paramarg0: string[], paramarg1: string[]): string[];
    static newInstance(paramarg0: Class<Object>): Object | null;
    static newInstance(paramarg0: Class<Object>, paramarg1: Pointer): Object | null;
    constructor()
    bread: number;
    busy_donated_purr: number;
    busy_donated_spurr: number;
    busy_stolen_purr: number;
    busy_stolen_spurr: number;
    bwrite: number;
    decrintrs: number;
    description: number[];
    devintrs: number;
    dirblk: number;
    hpi: number;
    hpit: number;
    idle: number;
    idle_donated_purr: number;
    idle_donated_spurr: number;
    idle_stolen_purr: number;
    idle_stolen_spurr: number;
    iget: number;
    iowait: number;
    kexit: number;
    koverf: number;
    ksched: number;
    lbolt: NativeLong;
    loadavg: number[];
    lread: number;
    lwrite: number;
    mdmint: number;
    mpcrintrs: number;
    mpcsintrs: number;
    msg: number;
    namei: number;
    ncpus: number;
    ncpus_cfg: number;
    ncpus_high: number;
    phantintrs: number;
    phread: number;
    phwrite: number;
    physio: number;
    pidle: number;
    pidle_spurr: number;
    processorHZ: number;
    pswitch: number;
    psys: number;
    psys_spurr: number;
    purr_coalescing: number;
    puser: number;
    puser_spurr: number;
    pwait: number;
    pwait_spurr: number;
    rbread: number;
    rbwrt: number;
    rcread: number;
    rcvint: number;
    rcwrt: number;
    readch: number;
    runocc: number;
    runque: number;
    sema: number;
    softintrs: number;
    spurr_coalescing: number;
    spurrflag: number;
    swpocc: number;
    swpque: number;
    sys: number;
    syscall: number;
    sysexec: number;
    sysfork: number;
    sysread: number;
    syswrite: number;
    tb_last: number;
    traps: number;
    tty_caninch: number;
    tty_rawinch: number;
    tty_rawoutch: number;
    twait: number;
    user: number;
    version: number;
    wait: number;
    writech: number;
    xmtint: number;
}