import type { Function10 } from '../../../../../com/mojang/datafixers/util/Function10.d.ts'
import type { Function11 } from '../../../../../com/mojang/datafixers/util/Function11.d.ts'
import type { Function12 } from '../../../../../com/mojang/datafixers/util/Function12.d.ts'
import type { Function3 } from '../../../../../com/mojang/datafixers/util/Function3.d.ts'
import type { Function4 } from '../../../../../com/mojang/datafixers/util/Function4.d.ts'
import type { Function5 } from '../../../../../com/mojang/datafixers/util/Function5.d.ts'
import type { Function6 } from '../../../../../com/mojang/datafixers/util/Function6.d.ts'
import type { Function7 } from '../../../../../com/mojang/datafixers/util/Function7.d.ts'
import type { Function8 } from '../../../../../com/mojang/datafixers/util/Function8.d.ts'
import type { Function9 } from '../../../../../com/mojang/datafixers/util/Function9.d.ts'
import type { BiFunction } from '../../../../../java/util/function/BiFunction.d.ts'
import type { Function } from '../../../../../java/util/function/Function.d.ts'
import type { UnaryOperator } from '../../../../../java/util/function/UnaryOperator.d.ts'
import type { Object } from '../../../../../java/lang/Object.d.ts'
import type { BlockParticleOption } from '../../../../../net/minecraft/core/particles/BlockParticleOption.d.ts'
import type { RegistryFriendlyByteBuf } from '../../../../../net/minecraft/network/RegistryFriendlyByteBuf.d.ts'
import type { StreamCodec } from '../../../../../net/minecraft/network/codec/StreamCodec.d.ts'
import type { StreamCodec$CodecOperation } from '../../../../../net/minecraft/network/codec/StreamCodec$CodecOperation.d.ts'
import type { StreamDecoder } from '../../../../../net/minecraft/network/codec/StreamDecoder.d.ts'
import type { StreamEncoder } from '../../../../../net/minecraft/network/codec/StreamEncoder.d.ts'
import type { StreamMemberEncoder } from '../../../../../net/minecraft/network/codec/StreamMemberEncoder.d.ts'
export class ExtendedBlockParticleOptionStreamCodec extends Object implements StreamCodec<RegistryFriendlyByteBuf, BlockParticleOption> {
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramcodec7: StreamCodec<Object, Object>, paramgetter7: (param0: Object | null) => Object | null, paramcodec8: StreamCodec<Object, Object>, paramgetter8: (param0: Object | null) => Object | null, paramcodec9: StreamCodec<Object, Object>, paramgetter9: (param0: Object | null) => Object | null, paramcodec10: StreamCodec<Object, Object>, paramgetter10: (param0: Object | null) => Object | null, paramcodec11: StreamCodec<Object, Object>, paramgetter11: (param0: Object | null) => Object | null, paramcodec12: StreamCodec<Object, Object>, paramgetter12: (param0: Object | null) => Object | null, paramconstructor: Function12<Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramcodec7: StreamCodec<Object, Object>, paramgetter7: (param0: Object | null) => Object | null, paramcodec8: StreamCodec<Object, Object>, paramgetter8: (param0: Object | null) => Object | null, paramcodec9: StreamCodec<Object, Object>, paramgetter9: (param0: Object | null) => Object | null, paramcodec10: StreamCodec<Object, Object>, paramgetter10: (param0: Object | null) => Object | null, paramcodec11: StreamCodec<Object, Object>, paramgetter11: (param0: Object | null) => Object | null, paramconstructor: Function11<Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramcodec7: StreamCodec<Object, Object>, paramgetter7: (param0: Object | null) => Object | null, paramcodec8: StreamCodec<Object, Object>, paramgetter8: (param0: Object | null) => Object | null, paramcodec9: StreamCodec<Object, Object>, paramgetter9: (param0: Object | null) => Object | null, paramcodec10: StreamCodec<Object, Object>, paramgetter10: (param0: Object | null) => Object | null, paramconstructor: Function10<Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramcodec7: StreamCodec<Object, Object>, paramgetter7: (param0: Object | null) => Object | null, paramcodec8: StreamCodec<Object, Object>, paramgetter8: (param0: Object | null) => Object | null, paramcodec9: StreamCodec<Object, Object>, paramgetter9: (param0: Object | null) => Object | null, paramconstructor: Function9<Object, Object, Object, Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramcodec7: StreamCodec<Object, Object>, paramgetter7: (param0: Object | null) => Object | null, paramcodec8: StreamCodec<Object, Object>, paramgetter8: (param0: Object | null) => Object | null, paramconstructor: Function8<Object, Object, Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramcodec7: StreamCodec<Object, Object>, paramgetter7: (param0: Object | null) => Object | null, paramconstructor: Function7<Object, Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramconstructor: Function6<Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramconstructor: Function5<Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramconstructor: Function4<Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramconstructor: Function3<Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramconstructor: (param0: Object | null, param1: Object | null) => Object | null): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramconstructor: (param0: Object | null) => Object | null): StreamCodec<Object, Object>;
    static of(paramencoder: (param0: Object | null, param1: Object | null) => void, paramdecoder: (param0: Object | null) => Object | null): StreamCodec<Object, Object>;
    static ofMember(paramencoder: (param0: Object | null, param1: Object | null) => void, paramdecoder: (param0: Object | null) => Object | null): StreamCodec<Object, Object>;
    static recursive(paramfactory: (param0: Object | null) => unknown): StreamCodec<Object, Object>;
    static unit(paraminstance: Object | null): StreamCodec<Object, Object>;
    constructor(arg0: StreamCodec<RegistryFriendlyByteBuf, BlockParticleOption>)
    // private fallback: StreamCodec<RegistryFriendlyByteBuf, BlockParticleOption>;
    apply(operation: (param0: B) => O): StreamCodec<B, O>;
    cast(): StreamCodec<S, V>;
    decode(arg0: RegistryFriendlyByteBuf): BlockParticleOption;
    dispatch(type: (param0: U) => V, codec: (param0: V) => StreamCodec<B, U>): StreamCodec<B, U>;
    encode(arg0: RegistryFriendlyByteBuf, arg1: BlockParticleOption): void;
    map(to: (param0: V) => O, from: (param0: O) => V): StreamCodec<B, O>;
    mapStream(operation: (param0: O) => B): StreamCodec<O, V>;
}