import type { Handle } from '../../../../../../../com/oracle/truffle/api/impl/asm/Handle.d.ts'
import type { Label } from '../../../../../../../com/oracle/truffle/api/impl/asm/Label.d.ts'
import type { MethodVisitor } from '../../../../../../../com/oracle/truffle/api/impl/asm/MethodVisitor.d.ts'
import type { Opcodes } from '../../../../../../../com/oracle/truffle/api/impl/asm/Opcodes.d.ts'
import type { GeneratorAdapter } from '../../../../../../../com/oracle/truffle/api/impl/asm/commons/GeneratorAdapter.d.ts'
import type { Object } from '../../../../../../../java/lang/Object.d.ts'
export abstract class AdviceAdapter extends GeneratorAdapter implements Opcodes {
    static AALOAD: number;
    static AASTORE: number;
    static ACC_ABSTRACT: number;
    static ACC_ANNOTATION: number;
    static ACC_BRIDGE: number;
    static ACC_DEPRECATED: number;
    static ACC_ENUM: number;
    static ACC_FINAL: number;
    static ACC_INTERFACE: number;
    static ACC_MANDATED: number;
    static ACC_MODULE: number;
    static ACC_NATIVE: number;
    static ACC_OPEN: number;
    static ACC_PRIVATE: number;
    static ACC_PROTECTED: number;
    static ACC_PUBLIC: number;
    static ACC_RECORD: number;
    static ACC_STATIC: number;
    static ACC_STATIC_PHASE: number;
    static ACC_STRICT: number;
    static ACC_SUPER: number;
    static ACC_SYNCHRONIZED: number;
    static ACC_SYNTHETIC: number;
    static ACC_TRANSIENT: number;
    static ACC_TRANSITIVE: number;
    static ACC_VARARGS: number;
    static ACC_VOLATILE: number;
    static ACONST_NULL: number;
    static ADD: number;
    static ALOAD: number;
    static AND: number;
    static ANEWARRAY: number;
    static ARETURN: number;
    static ARRAYLENGTH: number;
    static ASM10_EXPERIMENTAL: number;
    static ASM4: number;
    static ASM5: number;
    static ASM6: number;
    static ASM7: number;
    static ASM8: number;
    static ASM9: number;
    static ASTORE: number;
    static ATHROW: number;
    static BALOAD: number;
    static BASTORE: number;
    static BIPUSH: number;
    static CALOAD: number;
    static CASTORE: number;
    static CHECKCAST: number;
    static D2F: number;
    static D2I: number;
    static D2L: number;
    static DADD: number;
    static DALOAD: number;
    static DASTORE: number;
    static DCMPG: number;
    static DCMPL: number;
    static DCONST_0: number;
    static DCONST_1: number;
    static DDIV: number;
    static DIV: number;
    static DLOAD: number;
    static DMUL: number;
    static DNEG: number;
    static DOUBLE: number;
    static DREM: number;
    static DRETURN: number;
    static DSTORE: number;
    static DSUB: number;
    static DUP: number;
    static DUP2: number;
    static DUP2_X1: number;
    static DUP2_X2: number;
    static DUP_X1: number;
    static DUP_X2: number;
    static EQ: number;
    static F2D: number;
    static F2I: number;
    static F2L: number;
    static FADD: number;
    static FALOAD: number;
    static FASTORE: number;
    static FCMPG: number;
    static FCMPL: number;
    static FCONST_0: number;
    static FCONST_1: number;
    static FCONST_2: number;
    static FDIV: number;
    static FLOAD: number;
    static FLOAT: number;
    static FMUL: number;
    static FNEG: number;
    static FREM: number;
    static FRETURN: number;
    static FSTORE: number;
    static FSUB: number;
    static F_APPEND: number;
    static F_CHOP: number;
    static F_FULL: number;
    static F_NEW: number;
    static F_SAME: number;
    static F_SAME1: number;
    static GE: number;
    static GETFIELD: number;
    static GETSTATIC: number;
    static GOTO: number;
    static GT: number;
    static H_GETFIELD: number;
    static H_GETSTATIC: number;
    static H_INVOKEINTERFACE: number;
    static H_INVOKESPECIAL: number;
    static H_INVOKESTATIC: number;
    static H_INVOKEVIRTUAL: number;
    static H_NEWINVOKESPECIAL: number;
    static H_PUTFIELD: number;
    static H_PUTSTATIC: number;
    static I2B: number;
    static I2C: number;
    static I2D: number;
    static I2F: number;
    static I2L: number;
    static I2S: number;
    static IADD: number;
    static IALOAD: number;
    static IAND: number;
    static IASTORE: number;
    static ICONST_0: number;
    static ICONST_1: number;
    static ICONST_2: number;
    static ICONST_3: number;
    static ICONST_4: number;
    static ICONST_5: number;
    static ICONST_M1: number;
    static IDIV: number;
    static IFEQ: number;
    static IFGE: number;
    static IFGT: number;
    static IFLE: number;
    static IFLT: number;
    static IFNE: number;
    static IFNONNULL: number;
    static IFNULL: number;
    static IF_ACMPEQ: number;
    static IF_ACMPNE: number;
    static IF_ICMPEQ: number;
    static IF_ICMPGE: number;
    static IF_ICMPGT: number;
    static IF_ICMPLE: number;
    static IF_ICMPLT: number;
    static IF_ICMPNE: number;
    static IINC: number;
    static ILOAD: number;
    static IMUL: number;
    static INEG: number;
    static INSTANCEOF: number;
    static INTEGER: number;
    static INVOKEDYNAMIC: number;
    static INVOKEINTERFACE: number;
    static INVOKESPECIAL: number;
    static INVOKESTATIC: number;
    static INVOKEVIRTUAL: number;
    static IOR: number;
    static IREM: number;
    static IRETURN: number;
    static ISHL: number;
    static ISHR: number;
    static ISTORE: number;
    static ISUB: number;
    static IUSHR: number;
    static IXOR: number;
    static JSR: number;
    static L2D: number;
    static L2F: number;
    static L2I: number;
    static LADD: number;
    static LALOAD: number;
    static LAND: number;
    static LASTORE: number;
    static LCMP: number;
    static LCONST_0: number;
    static LCONST_1: number;
    static LDC: number;
    static LDIV: number;
    static LE: number;
    static LLOAD: number;
    static LMUL: number;
    static LNEG: number;
    static LONG: number;
    static LOOKUPSWITCH: number;
    static LOR: number;
    static LREM: number;
    static LRETURN: number;
    static LSHL: number;
    static LSHR: number;
    static LSTORE: number;
    static LSUB: number;
    static LT: number;
    static LUSHR: number;
    static LXOR: number;
    static MONITORENTER: number;
    static MONITOREXIT: number;
    static MUL: number;
    static MULTIANEWARRAY: number;
    static NE: number;
    static NEG: number;
    static NEW: number;
    static NEWARRAY: number;
    static NOP: number;
    static NULL: number;
    static OR: number;
    static POP: number;
    static POP2: number;
    static PUTFIELD: number;
    static PUTSTATIC: number;
    static REM: number;
    static RET: number;
    static RETURN: number;
    static SALOAD: number;
    static SASTORE: number;
    static SHL: number;
    static SHR: number;
    static SIPUSH: number;
    static SOURCE_DEPRECATED: number;
    static SOURCE_MASK: number;
    static SUB: number;
    static SWAP: number;
    static TABLESWITCH: number;
    static TOP: number;
    static T_BOOLEAN: number;
    static T_BYTE: number;
    static T_CHAR: number;
    static T_DOUBLE: number;
    static T_FLOAT: number;
    static T_INT: number;
    static T_LONG: number;
    static T_SHORT: number;
    static UNINITIALIZED_THIS: number;
    static USHR: number;
    static V10: number;
    static V11: number;
    static V12: number;
    static V13: number;
    static V14: number;
    static V15: number;
    static V16: number;
    static V17: number;
    static V18: number;
    static V19: number;
    static V1_1: number;
    static V1_2: number;
    static V1_3: number;
    static V1_4: number;
    static V1_5: number;
    static V1_6: number;
    static V1_7: number;
    static V1_8: number;
    static V20: number;
    static V21: number;
    static V22: number;
    static V23: number;
    static V24: number;
    static V25: number;
    static V9: number;
    static V_PREVIEW: number;
    static XOR: number;
    constructor(api: number, methodVisitor: MethodVisitor, access: number, name: string, descriptor: string)
    // private forwardJumpStackFrames: Map<Label, Object[]>;
    // private isConstructor: boolean;
    // private methodAccess: number;
    // private methodDesc: string;
    // private stackFrame: Object[];
    // private superClassConstructorCalled: boolean;
    // private addForwardJump(label: Label): void;
    // private addForwardJumps(dflt: Label, labels: Label[]): void;
    // private doVisitMethodInsn(opcode: number, name: string, descriptor: string): void;
    // private endConstructorBasicBlockWithoutSuccessor(): void;
    onMethodEnter(): void;
    onMethodExit(opcode: number): void;
    // private peekValue(): Object;
    // private popValue(): Object;
    // private pushValue(value: Object): void;
    visitCode(): void;
    visitFieldInsn(opcode: number, owner: string, name: string, descriptor: string): void;
    visitInsn(opcode: number): void;
    visitIntInsn(opcode: number, operand: number): void;
    visitInvokeDynamicInsn(name: string, descriptor: string, bootstrapMethodHandle: Handle, ...bootstrapMethodArguments: Object[]): void;
    visitJumpInsn(opcode: number, label: Label): void;
    visitLabel(label: Label): void;
    visitLdcInsn(value: Object): void;
    visitLookupSwitchInsn(dflt: Label, keys: number[], labels: Label[]): void;
    visitMethodInsn(opcode: number, owner: string, name: string, descriptor: string): void;
    visitMethodInsn(opcodeAndSource: number, owner: string, name: string, descriptor: string, isInterface: boolean): void;
    visitMultiANewArrayInsn(descriptor: string, numDimensions: number): void;
    visitTableSwitchInsn(min: number, max: number, dflt: Label, ...labels: Label[]): void;
    visitTryCatchBlock(start: Label, end: Label, handler: Label, type: string): void;
    visitTypeInsn(opcode: number, type: string): void;
    visitVarInsn(opcode: number, varIndex: number): void;
}