import type { Function10 } from '../../../../com/mojang/datafixers/util/Function10.d.ts'
import type { Function11 } from '../../../../com/mojang/datafixers/util/Function11.d.ts'
import type { Function12 } from '../../../../com/mojang/datafixers/util/Function12.d.ts'
import type { Function3 } from '../../../../com/mojang/datafixers/util/Function3.d.ts'
import type { Function4 } from '../../../../com/mojang/datafixers/util/Function4.d.ts'
import type { Function5 } from '../../../../com/mojang/datafixers/util/Function5.d.ts'
import type { Function6 } from '../../../../com/mojang/datafixers/util/Function6.d.ts'
import type { Function7 } from '../../../../com/mojang/datafixers/util/Function7.d.ts'
import type { Function8 } from '../../../../com/mojang/datafixers/util/Function8.d.ts'
import type { Function9 } from '../../../../com/mojang/datafixers/util/Function9.d.ts'
import type { ByteBuf } from '../../../../io/netty/buffer/ByteBuf.d.ts'
import type { BiFunction } from '../../../../java/util/function/BiFunction.d.ts'
import type { Function } from '../../../../java/util/function/Function.d.ts'
import type { UnaryOperator } from '../../../../java/util/function/UnaryOperator.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { IdDispatchCodec$Builder } from '../../../../net/minecraft/network/codec/IdDispatchCodec$Builder.d.ts'
import type { IdDispatchCodec$Entry } from '../../../../net/minecraft/network/codec/IdDispatchCodec$Entry.d.ts'
import type { StreamCodec } from '../../../../net/minecraft/network/codec/StreamCodec.d.ts'
import type { StreamCodec$CodecOperation } from '../../../../net/minecraft/network/codec/StreamCodec$CodecOperation.d.ts'
import type { StreamDecoder } from '../../../../net/minecraft/network/codec/StreamDecoder.d.ts'
import type { StreamEncoder } from '../../../../net/minecraft/network/codec/StreamEncoder.d.ts'
import type { StreamMemberEncoder } from '../../../../net/minecraft/network/codec/StreamMemberEncoder.d.ts'
export class IdDispatchCodec<B extends ByteBuf, V extends Object | number | string | boolean, T extends Object | number | string | boolean> extends Object implements StreamCodec<B, V> {
    static builder(paramtypeGetter: (param0: Object | null) => Object | null): IdDispatchCodec$Builder<ByteBuf, Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramcodec7: StreamCodec<Object, Object>, paramgetter7: (param0: Object | null) => Object | null, paramcodec8: StreamCodec<Object, Object>, paramgetter8: (param0: Object | null) => Object | null, paramcodec9: StreamCodec<Object, Object>, paramgetter9: (param0: Object | null) => Object | null, paramcodec10: StreamCodec<Object, Object>, paramgetter10: (param0: Object | null) => Object | null, paramcodec11: StreamCodec<Object, Object>, paramgetter11: (param0: Object | null) => Object | null, paramcodec12: StreamCodec<Object, Object>, paramgetter12: (param0: Object | null) => Object | null, paramconstructor: Function12<Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramcodec7: StreamCodec<Object, Object>, paramgetter7: (param0: Object | null) => Object | null, paramcodec8: StreamCodec<Object, Object>, paramgetter8: (param0: Object | null) => Object | null, paramcodec9: StreamCodec<Object, Object>, paramgetter9: (param0: Object | null) => Object | null, paramcodec10: StreamCodec<Object, Object>, paramgetter10: (param0: Object | null) => Object | null, paramcodec11: StreamCodec<Object, Object>, paramgetter11: (param0: Object | null) => Object | null, paramconstructor: Function11<Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramcodec7: StreamCodec<Object, Object>, paramgetter7: (param0: Object | null) => Object | null, paramcodec8: StreamCodec<Object, Object>, paramgetter8: (param0: Object | null) => Object | null, paramcodec9: StreamCodec<Object, Object>, paramgetter9: (param0: Object | null) => Object | null, paramcodec10: StreamCodec<Object, Object>, paramgetter10: (param0: Object | null) => Object | null, paramconstructor: Function10<Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramcodec7: StreamCodec<Object, Object>, paramgetter7: (param0: Object | null) => Object | null, paramcodec8: StreamCodec<Object, Object>, paramgetter8: (param0: Object | null) => Object | null, paramcodec9: StreamCodec<Object, Object>, paramgetter9: (param0: Object | null) => Object | null, paramconstructor: Function9<Object, Object, Object, Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramcodec7: StreamCodec<Object, Object>, paramgetter7: (param0: Object | null) => Object | null, paramcodec8: StreamCodec<Object, Object>, paramgetter8: (param0: Object | null) => Object | null, paramconstructor: Function8<Object, Object, Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramcodec7: StreamCodec<Object, Object>, paramgetter7: (param0: Object | null) => Object | null, paramconstructor: Function7<Object, Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramcodec6: StreamCodec<Object, Object>, paramgetter6: (param0: Object | null) => Object | null, paramconstructor: Function6<Object, Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramcodec5: StreamCodec<Object, Object>, paramgetter5: (param0: Object | null) => Object | null, paramconstructor: Function5<Object, Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramcodec4: StreamCodec<Object, Object>, paramgetter4: (param0: Object | null) => Object | null, paramconstructor: Function4<Object, Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramcodec3: StreamCodec<Object, Object>, paramgetter3: (param0: Object | null) => Object | null, paramconstructor: Function3<Object, Object, Object, Object>): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramcodec2: StreamCodec<Object, Object>, paramgetter2: (param0: Object | null) => Object | null, paramconstructor: (param0: Object | null, param1: Object | null) => Object | null): StreamCodec<Object, Object>;
    static composite(paramcodec1: StreamCodec<Object, Object>, paramgetter1: (param0: Object | null) => Object | null, paramconstructor: (param0: Object | null) => Object | null): StreamCodec<Object, Object>;
    static of(paramencoder: (param0: Object | null, param1: Object | null) => void, paramdecoder: (param0: Object | null) => Object | null): StreamCodec<Object, Object>;
    static ofMember(paramencoder: (param0: Object | null, param1: Object | null) => void, paramdecoder: (param0: Object | null) => Object | null): StreamCodec<Object, Object>;
    static recursive(paramfactory: (param0: StreamCodec<Object, Object>) => Object | null): StreamCodec<Object, Object>;
    static unit(paraminstance: Object | null): StreamCodec<Object, Object>;
    private constructor(typeGetter: (param0: V) => T, byId: IdDispatchCodec$Entry<B, V, T>[], toId: Object2IntMap<T>)
    // private byId: IdDispatchCodec$Entry<B, V, T>[];
    // private toId: Object2IntMap<T>;
    // private typeGetter: (param0: V) => T;
    apply<O extends Object | number | string | boolean>(operation: (param0: StreamCodec<B, V>) => StreamCodec<B, O>): StreamCodec<B, O>;
    cast<S extends B>(): StreamCodec<S, V>;
    decode(input: B): V;
    dispatch<U extends Object | number | string | boolean>(type: (param0: U) => V, codec: (param0: V) => StreamCodec<B, U>): StreamCodec<B, U>;
    encode(output: B, value: V): void;
    map<O extends Object | number | string | boolean>(to: (param0: V) => O, from: (param0: O) => V): StreamCodec<B, O>;
    mapStream<O extends ByteBuf>(operation: (param0: O) => B): StreamCodec<O, V>;
}