import type { Function10 } from '../../../../com/mojang/datafixers/util/Function10.d.ts'
import type { Function11 } from '../../../../com/mojang/datafixers/util/Function11.d.ts'
import type { Function12 } from '../../../../com/mojang/datafixers/util/Function12.d.ts'
import type { Function3 } from '../../../../com/mojang/datafixers/util/Function3.d.ts'
import type { Function4 } from '../../../../com/mojang/datafixers/util/Function4.d.ts'
import type { Function5 } from '../../../../com/mojang/datafixers/util/Function5.d.ts'
import type { Function6 } from '../../../../com/mojang/datafixers/util/Function6.d.ts'
import type { Function7 } from '../../../../com/mojang/datafixers/util/Function7.d.ts'
import type { Function8 } from '../../../../com/mojang/datafixers/util/Function8.d.ts'
import type { Function9 } from '../../../../com/mojang/datafixers/util/Function9.d.ts'
import type { ByteBuf } from '../../../../io/netty/buffer/ByteBuf.d.ts'
import type { BiFunction } from '../../../../java/util/function/BiFunction.d.ts'
import type { Function } from '../../../../java/util/function/Function.d.ts'
import type { UnaryOperator } from '../../../../java/util/function/UnaryOperator.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { IdDispatchCodec$Builder } from '../../../../net/minecraft/network/codec/IdDispatchCodec$Builder.d.ts'
import type { IdDispatchCodec$Entry } from '../../../../net/minecraft/network/codec/IdDispatchCodec$Entry.d.ts'
import type { StreamCodec } from '../../../../net/minecraft/network/codec/StreamCodec.d.ts'
import type { StreamCodec$CodecOperation } from '../../../../net/minecraft/network/codec/StreamCodec$CodecOperation.d.ts'
import type { StreamDecoder } from '../../../../net/minecraft/network/codec/StreamDecoder.d.ts'
import type { StreamEncoder } from '../../../../net/minecraft/network/codec/StreamEncoder.d.ts'
import type { StreamMemberEncoder } from '../../../../net/minecraft/network/codec/StreamMemberEncoder.d.ts'
export class IdDispatchCodec<B extends ByteBuf, V extends unknown, T extends unknown> extends Object implements StreamCodec<B, V> {
    static builder<B extends ByteBuf, V extends unknown, T extends unknown>(paramtypeGetter: (param0: V) => T): IdDispatchCodec$Builder<B, V, T>;
    static composite<B extends unknown, C extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown, T12 extends unknown>(paramcodec1: StreamCodec<Object, T1>, paramgetter1: (param0: C) => T1, paramcodec2: StreamCodec<Object, T2>, paramgetter2: (param0: C) => T2, paramcodec3: StreamCodec<Object, T3>, paramgetter3: (param0: C) => T3, paramcodec4: StreamCodec<Object, T4>, paramgetter4: (param0: C) => T4, paramcodec5: StreamCodec<Object, T5>, paramgetter5: (param0: C) => T5, paramcodec6: StreamCodec<Object, T6>, paramgetter6: (param0: C) => T6, paramcodec7: StreamCodec<Object, T7>, paramgetter7: (param0: C) => T7, paramcodec8: StreamCodec<Object, T8>, paramgetter8: (param0: C) => T8, paramcodec9: StreamCodec<Object, T9>, paramgetter9: (param0: C) => T9, paramcodec10: StreamCodec<Object, T10>, paramgetter10: (param0: C) => T10, paramcodec11: StreamCodec<Object, T11>, paramgetter11: (param0: C) => T11, paramcodec12: StreamCodec<Object, T12>, paramgetter12: (param0: C) => T12, paramconstructor: Function12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, C>): StreamCodec<B, C>;
    static composite<B extends unknown, C extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown>(paramcodec1: StreamCodec<Object, T1>, paramgetter1: (param0: C) => T1, paramcodec2: StreamCodec<Object, T2>, paramgetter2: (param0: C) => T2, paramcodec3: StreamCodec<Object, T3>, paramgetter3: (param0: C) => T3, paramcodec4: StreamCodec<Object, T4>, paramgetter4: (param0: C) => T4, paramcodec5: StreamCodec<Object, T5>, paramgetter5: (param0: C) => T5, paramcodec6: StreamCodec<Object, T6>, paramgetter6: (param0: C) => T6, paramcodec7: StreamCodec<Object, T7>, paramgetter7: (param0: C) => T7, paramcodec8: StreamCodec<Object, T8>, paramgetter8: (param0: C) => T8, paramcodec9: StreamCodec<Object, T9>, paramgetter9: (param0: C) => T9, paramcodec10: StreamCodec<Object, T10>, paramgetter10: (param0: C) => T10, paramcodec11: StreamCodec<Object, T11>, paramgetter11: (param0: C) => T11, paramconstructor: Function11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, C>): StreamCodec<B, C>;
    static composite<B extends unknown, C extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown>(paramcodec1: StreamCodec<Object, T1>, paramgetter1: (param0: C) => T1, paramcodec2: StreamCodec<Object, T2>, paramgetter2: (param0: C) => T2, paramcodec3: StreamCodec<Object, T3>, paramgetter3: (param0: C) => T3, paramcodec4: StreamCodec<Object, T4>, paramgetter4: (param0: C) => T4, paramcodec5: StreamCodec<Object, T5>, paramgetter5: (param0: C) => T5, paramcodec6: StreamCodec<Object, T6>, paramgetter6: (param0: C) => T6, paramcodec7: StreamCodec<Object, T7>, paramgetter7: (param0: C) => T7, paramcodec8: StreamCodec<Object, T8>, paramgetter8: (param0: C) => T8, paramcodec9: StreamCodec<Object, T9>, paramgetter9: (param0: C) => T9, paramcodec10: StreamCodec<Object, T10>, paramgetter10: (param0: C) => T10, paramconstructor: Function10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, C>): StreamCodec<B, C>;
    static composite<B extends unknown, C extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown>(paramcodec1: StreamCodec<Object, T1>, paramgetter1: (param0: C) => T1, paramcodec2: StreamCodec<Object, T2>, paramgetter2: (param0: C) => T2, paramcodec3: StreamCodec<Object, T3>, paramgetter3: (param0: C) => T3, paramcodec4: StreamCodec<Object, T4>, paramgetter4: (param0: C) => T4, paramcodec5: StreamCodec<Object, T5>, paramgetter5: (param0: C) => T5, paramcodec6: StreamCodec<Object, T6>, paramgetter6: (param0: C) => T6, paramcodec7: StreamCodec<Object, T7>, paramgetter7: (param0: C) => T7, paramcodec8: StreamCodec<Object, T8>, paramgetter8: (param0: C) => T8, paramcodec9: StreamCodec<Object, T9>, paramgetter9: (param0: C) => T9, paramconstructor: Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, C>): StreamCodec<B, C>;
    static composite<B extends unknown, C extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown>(paramcodec1: StreamCodec<Object, T1>, paramgetter1: (param0: C) => T1, paramcodec2: StreamCodec<Object, T2>, paramgetter2: (param0: C) => T2, paramcodec3: StreamCodec<Object, T3>, paramgetter3: (param0: C) => T3, paramcodec4: StreamCodec<Object, T4>, paramgetter4: (param0: C) => T4, paramcodec5: StreamCodec<Object, T5>, paramgetter5: (param0: C) => T5, paramcodec6: StreamCodec<Object, T6>, paramgetter6: (param0: C) => T6, paramcodec7: StreamCodec<Object, T7>, paramgetter7: (param0: C) => T7, paramcodec8: StreamCodec<Object, T8>, paramgetter8: (param0: C) => T8, paramconstructor: Function8<T1, T2, T3, T4, T5, T6, T7, T8, C>): StreamCodec<B, C>;
    static composite<B extends unknown, C extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown>(paramcodec1: StreamCodec<Object, T1>, paramgetter1: (param0: C) => T1, paramcodec2: StreamCodec<Object, T2>, paramgetter2: (param0: C) => T2, paramcodec3: StreamCodec<Object, T3>, paramgetter3: (param0: C) => T3, paramcodec4: StreamCodec<Object, T4>, paramgetter4: (param0: C) => T4, paramcodec5: StreamCodec<Object, T5>, paramgetter5: (param0: C) => T5, paramcodec6: StreamCodec<Object, T6>, paramgetter6: (param0: C) => T6, paramcodec7: StreamCodec<Object, T7>, paramgetter7: (param0: C) => T7, paramconstructor: Function7<T1, T2, T3, T4, T5, T6, T7, C>): StreamCodec<B, C>;
    static composite<B extends unknown, C extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown>(paramcodec1: StreamCodec<Object, T1>, paramgetter1: (param0: C) => T1, paramcodec2: StreamCodec<Object, T2>, paramgetter2: (param0: C) => T2, paramcodec3: StreamCodec<Object, T3>, paramgetter3: (param0: C) => T3, paramcodec4: StreamCodec<Object, T4>, paramgetter4: (param0: C) => T4, paramcodec5: StreamCodec<Object, T5>, paramgetter5: (param0: C) => T5, paramcodec6: StreamCodec<Object, T6>, paramgetter6: (param0: C) => T6, paramconstructor: Function6<T1, T2, T3, T4, T5, T6, C>): StreamCodec<B, C>;
    static composite<B extends unknown, C extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown>(paramcodec1: StreamCodec<Object, T1>, paramgetter1: (param0: C) => T1, paramcodec2: StreamCodec<Object, T2>, paramgetter2: (param0: C) => T2, paramcodec3: StreamCodec<Object, T3>, paramgetter3: (param0: C) => T3, paramcodec4: StreamCodec<Object, T4>, paramgetter4: (param0: C) => T4, paramcodec5: StreamCodec<Object, T5>, paramgetter5: (param0: C) => T5, paramconstructor: Function5<T1, T2, T3, T4, T5, C>): StreamCodec<B, C>;
    static composite<B extends unknown, C extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown>(paramcodec1: StreamCodec<Object, T1>, paramgetter1: (param0: C) => T1, paramcodec2: StreamCodec<Object, T2>, paramgetter2: (param0: C) => T2, paramcodec3: StreamCodec<Object, T3>, paramgetter3: (param0: C) => T3, paramcodec4: StreamCodec<Object, T4>, paramgetter4: (param0: C) => T4, paramconstructor: Function4<T1, T2, T3, T4, C>): StreamCodec<B, C>;
    static composite<B extends unknown, C extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown>(paramcodec1: StreamCodec<Object, T1>, paramgetter1: (param0: C) => T1, paramcodec2: StreamCodec<Object, T2>, paramgetter2: (param0: C) => T2, paramcodec3: StreamCodec<Object, T3>, paramgetter3: (param0: C) => T3, paramconstructor: Function3<T1, T2, T3, C>): StreamCodec<B, C>;
    static composite<B extends unknown, C extends unknown, T1 extends unknown, T2 extends unknown>(paramcodec1: StreamCodec<Object, T1>, paramgetter1: (param0: C) => T1, paramcodec2: StreamCodec<Object, T2>, paramgetter2: (param0: C) => T2, paramconstructor: (param0: T1, param1: T2) => C): StreamCodec<B, C>;
    static composite<B extends unknown, C extends unknown, T1 extends unknown>(paramcodec1: StreamCodec<Object, T1>, paramgetter1: (param0: C) => T1, paramconstructor: (param0: T1) => C): StreamCodec<B, C>;
    static of<B extends unknown, V extends unknown>(paramencoder: (param0: B, param1: V) => void, paramdecoder: (param0: B) => V): StreamCodec<B, V>;
    static ofMember<B extends unknown, V extends unknown>(paramencoder: (param0: V, param1: B) => void, paramdecoder: (param0: B) => V): StreamCodec<B, V>;
    static recursive<B extends unknown, T extends unknown>(paramfactory: (param0: StreamCodec<B, T>) => StreamCodec<B, T>): StreamCodec<B, T>;
    static unit<B extends unknown, V extends unknown>(paraminstance: V): StreamCodec<B, V>;
    private constructor(typeGetter: (param0: V) => T, byId: IdDispatchCodec$Entry<B, V, T>[], toId: { [key: string]: any })
    // private byId: IdDispatchCodec$Entry<B, V, T>[];
    // private toId: { [key: string]: any };
    // private typeGetter: (param0: V) => T;
    apply<O extends unknown>(operation: (param0: StreamCodec<B, V>) => StreamCodec<B, O>): StreamCodec<B, O>;
    cast<S extends B>(): StreamCodec<S, V>;
    decode(input: B): V;
    dispatch<U extends unknown>(type: (param0: U) => V, codec: (param0: V) => StreamCodec<B, U>): StreamCodec<B, U>;
    encode(output: B, value: V): void;
    map<O extends unknown>(to: (param0: V) => O, from: (param0: O) => V): StreamCodec<B, O>;
    mapStream<O extends ByteBuf>(operation: (param0: O) => B): StreamCodec<O, V>;
}