import type { Direction } from '../../../../../../com/viaversion/viaversion/api/protocol/packet/Direction.d.ts'
import type { State } from '../../../../../../com/viaversion/viaversion/api/protocol/packet/State.d.ts'
import type { ClientboundPacket26_1 } from '../../../../../../com/viaversion/viaversion/protocols/v1_21_11to26_1/packet/ClientboundPacket26_1.d.ts'
import type { Class } from '../../../../../../java/lang/Class.d.ts'
import type { Object } from '../../../../../../java/lang/Object.d.ts'
import type { Enum } from '../../../../../../java/lang/Enum.d.ts'
export class ClientboundPackets26_1 extends Enum<ClientboundPackets26_1> implements ClientboundPacket26_1 {
    static ADD_ENTITY: ClientboundPackets26_1;
    static ANIMATE: ClientboundPackets26_1;
    static AWARD_STATS: ClientboundPackets26_1;
    static BLOCK_CHANGED_ACK: ClientboundPackets26_1;
    static BLOCK_DESTRUCTION: ClientboundPackets26_1;
    static BLOCK_ENTITY_DATA: ClientboundPackets26_1;
    static BLOCK_EVENT: ClientboundPackets26_1;
    static BLOCK_UPDATE: ClientboundPackets26_1;
    static BOSS_EVENT: ClientboundPackets26_1;
    static BUNDLE_DELIMITER: ClientboundPackets26_1;
    static CHANGE_DIFFICULTY: ClientboundPackets26_1;
    static CHUNKS_BIOMES: ClientboundPackets26_1;
    static CHUNK_BATCH_FINISHED: ClientboundPackets26_1;
    static CHUNK_BATCH_START: ClientboundPackets26_1;
    static CLEAR_DIALOG: ClientboundPackets26_1;
    static CLEAR_TITLES: ClientboundPackets26_1;
    static COMMANDS: ClientboundPackets26_1;
    static COMMAND_SUGGESTIONS: ClientboundPackets26_1;
    static CONTAINER_CLOSE: ClientboundPackets26_1;
    static CONTAINER_SET_CONTENT: ClientboundPackets26_1;
    static CONTAINER_SET_DATA: ClientboundPackets26_1;
    static CONTAINER_SET_SLOT: ClientboundPackets26_1;
    static COOKIE_REQUEST: ClientboundPackets26_1;
    static COOLDOWN: ClientboundPackets26_1;
    static CUSTOM_CHAT_COMPLETIONS: ClientboundPackets26_1;
    static CUSTOM_PAYLOAD: ClientboundPackets26_1;
    static CUSTOM_REPORT_DETAILS: ClientboundPackets26_1;
    static DAMAGE_EVENT: ClientboundPackets26_1;
    static DEBUG_BLOCK_VALUE: ClientboundPackets26_1;
    static DEBUG_CHUNK_VALUE: ClientboundPackets26_1;
    static DEBUG_ENTITY_VALUE: ClientboundPackets26_1;
    static DEBUG_EVENT: ClientboundPackets26_1;
    static DEBUG_SAMPLE: ClientboundPackets26_1;
    static DELETE_CHAT: ClientboundPackets26_1;
    static DISCONNECT: ClientboundPackets26_1;
    static DISGUISED_CHAT: ClientboundPackets26_1;
    static ENTITY_EVENT: ClientboundPackets26_1;
    static ENTITY_POSITION_SYNC: ClientboundPackets26_1;
    static EXPLODE: ClientboundPackets26_1;
    static FORGET_LEVEL_CHUNK: ClientboundPackets26_1;
    static GAME_EVENT: ClientboundPackets26_1;
    static GAME_EVENT_TEST_HIGHLIGHT_POS: ClientboundPackets26_1;
    static GAME_RULE_VALUES: ClientboundPackets26_1;
    static HURT_ANIMATION: ClientboundPackets26_1;
    static INITIALIZE_BORDER: ClientboundPackets26_1;
    static KEEP_ALIVE: ClientboundPackets26_1;
    static LEVEL_CHUNK_WITH_LIGHT: ClientboundPackets26_1;
    static LEVEL_EVENT: ClientboundPackets26_1;
    static LEVEL_PARTICLES: ClientboundPackets26_1;
    static LIGHT_UPDATE: ClientboundPackets26_1;
    static LOGIN: ClientboundPackets26_1;
    static LOW_DISK_SPACE_WARNING: ClientboundPackets26_1;
    static MAP_ITEM_DATA: ClientboundPackets26_1;
    static MERCHANT_OFFERS: ClientboundPackets26_1;
    static MOUNT_SCREEN_OPEN: ClientboundPackets26_1;
    static MOVE_ENTITY_POS: ClientboundPackets26_1;
    static MOVE_ENTITY_POS_ROT: ClientboundPackets26_1;
    static MOVE_ENTITY_ROT: ClientboundPackets26_1;
    static MOVE_MINECART_ALONG_TRACK: ClientboundPackets26_1;
    static MOVE_VEHICLE: ClientboundPackets26_1;
    static OPEN_BOOK: ClientboundPackets26_1;
    static OPEN_SCREEN: ClientboundPackets26_1;
    static OPEN_SIGN_EDITOR: ClientboundPackets26_1;
    static PING: ClientboundPackets26_1;
    static PLACE_GHOST_RECIPE: ClientboundPackets26_1;
    static PLAYER_ABILITIES: ClientboundPackets26_1;
    static PLAYER_CHAT: ClientboundPackets26_1;
    static PLAYER_COMBAT_END: ClientboundPackets26_1;
    static PLAYER_COMBAT_ENTER: ClientboundPackets26_1;
    static PLAYER_COMBAT_KILL: ClientboundPackets26_1;
    static PLAYER_INFO_REMOVE: ClientboundPackets26_1;
    static PLAYER_INFO_UPDATE: ClientboundPackets26_1;
    static PLAYER_LOOK_AT: ClientboundPackets26_1;
    static PLAYER_POSITION: ClientboundPackets26_1;
    static PLAYER_ROTATION: ClientboundPackets26_1;
    static PONG_RESPONSE: ClientboundPackets26_1;
    static PROJECTILE_POWER: ClientboundPackets26_1;
    static RECIPE_BOOK_ADD: ClientboundPackets26_1;
    static RECIPE_BOOK_REMOVE: ClientboundPackets26_1;
    static RECIPE_BOOK_SETTINGS: ClientboundPackets26_1;
    static REMOVE_ENTITIES: ClientboundPackets26_1;
    static REMOVE_MOB_EFFECT: ClientboundPackets26_1;
    static RESET_SCORE: ClientboundPackets26_1;
    static RESOURCE_PACK_POP: ClientboundPackets26_1;
    static RESOURCE_PACK_PUSH: ClientboundPackets26_1;
    static RESPAWN: ClientboundPackets26_1;
    static ROTATE_HEAD: ClientboundPackets26_1;
    static SECTION_BLOCKS_UPDATE: ClientboundPackets26_1;
    static SELECT_ADVANCEMENTS_TAB: ClientboundPackets26_1;
    static SERVER_DATA: ClientboundPackets26_1;
    static SERVER_LINKS: ClientboundPackets26_1;
    static SET_ACTION_BAR_TEXT: ClientboundPackets26_1;
    static SET_BORDER_CENTER: ClientboundPackets26_1;
    static SET_BORDER_LERP_SIZE: ClientboundPackets26_1;
    static SET_BORDER_SIZE: ClientboundPackets26_1;
    static SET_BORDER_WARNING_DELAY: ClientboundPackets26_1;
    static SET_BORDER_WARNING_DISTANCE: ClientboundPackets26_1;
    static SET_CAMERA: ClientboundPackets26_1;
    static SET_CHUNK_CACHE_CENTER: ClientboundPackets26_1;
    static SET_CHUNK_CACHE_RADIUS: ClientboundPackets26_1;
    static SET_CURSOR_ITEM: ClientboundPackets26_1;
    static SET_DEFAULT_SPAWN_POSITION: ClientboundPackets26_1;
    static SET_DISPLAY_OBJECTIVE: ClientboundPackets26_1;
    static SET_ENTITY_DATA: ClientboundPackets26_1;
    static SET_ENTITY_LINK: ClientboundPackets26_1;
    static SET_ENTITY_MOTION: ClientboundPackets26_1;
    static SET_EQUIPMENT: ClientboundPackets26_1;
    static SET_EXPERIENCE: ClientboundPackets26_1;
    static SET_HEALTH: ClientboundPackets26_1;
    static SET_HELD_SLOT: ClientboundPackets26_1;
    static SET_OBJECTIVE: ClientboundPackets26_1;
    static SET_PASSENGERS: ClientboundPackets26_1;
    static SET_PLAYER_INVENTORY: ClientboundPackets26_1;
    static SET_PLAYER_TEAM: ClientboundPackets26_1;
    static SET_SCORE: ClientboundPackets26_1;
    static SET_SIMULATION_DISTANCE: ClientboundPackets26_1;
    static SET_SUBTITLE_TEXT: ClientboundPackets26_1;
    static SET_TIME: ClientboundPackets26_1;
    static SET_TITLES_ANIMATION: ClientboundPackets26_1;
    static SET_TITLE_TEXT: ClientboundPackets26_1;
    static SHOW_DIALOG: ClientboundPackets26_1;
    static SOUND: ClientboundPackets26_1;
    static SOUND_ENTITY: ClientboundPackets26_1;
    static START_CONFIGURATION: ClientboundPackets26_1;
    static STOP_SOUND: ClientboundPackets26_1;
    static STORE_COOKIE: ClientboundPackets26_1;
    static SYSTEM_CHAT: ClientboundPackets26_1;
    static TAB_LIST: ClientboundPackets26_1;
    static TAG_QUERY: ClientboundPackets26_1;
    static TAKE_ITEM_ENTITY: ClientboundPackets26_1;
    static TELEPORT_ENTITY: ClientboundPackets26_1;
    static TEST_INSTANCE_BLOCK_STATUS: ClientboundPackets26_1;
    static TICKING_STATE: ClientboundPackets26_1;
    static TICKING_STEP: ClientboundPackets26_1;
    static TRACKED_WAYPOINT: ClientboundPackets26_1;
    static TRANSFER: ClientboundPackets26_1;
    static UPDATE_ADVANCEMENTS: ClientboundPackets26_1;
    static UPDATE_ATTRIBUTES: ClientboundPackets26_1;
    static UPDATE_MOB_EFFECT: ClientboundPackets26_1;
    static UPDATE_RECIPES: ClientboundPackets26_1;
    static UPDATE_TAGS: ClientboundPackets26_1;
    static valueOf(paramarg0: Class<Object>, paramarg1: string): Object | null;
    static valueOf(paramarg0: string): ClientboundPackets26_1;
    static values(): (Object | null)[];
    private constructor()
    direction(): Direction;
    getId(): number;
    getName(): string;
    state(): State;
    name(): "BUNDLE_DELIMITER" | "ADD_ENTITY" | "ANIMATE" | "AWARD_STATS" | "BLOCK_CHANGED_ACK" | "BLOCK_DESTRUCTION" | "BLOCK_ENTITY_DATA" | "BLOCK_EVENT" | "BLOCK_UPDATE" | "BOSS_EVENT" | "CHANGE_DIFFICULTY" | "CHUNK_BATCH_FINISHED" | "CHUNK_BATCH_START" | "CHUNKS_BIOMES" | "CLEAR_TITLES" | "COMMAND_SUGGESTIONS" | "COMMANDS" | "CONTAINER_CLOSE" | "CONTAINER_SET_CONTENT" | "CONTAINER_SET_DATA" | "CONTAINER_SET_SLOT" | "COOKIE_REQUEST" | "COOLDOWN" | "CUSTOM_CHAT_COMPLETIONS" | "CUSTOM_PAYLOAD" | "DAMAGE_EVENT" | "DEBUG_BLOCK_VALUE" | "DEBUG_CHUNK_VALUE" | "DEBUG_ENTITY_VALUE" | "DEBUG_EVENT" | "DEBUG_SAMPLE" | "DELETE_CHAT" | "DISCONNECT" | "DISGUISED_CHAT" | "ENTITY_EVENT" | "ENTITY_POSITION_SYNC" | "EXPLODE" | "FORGET_LEVEL_CHUNK" | "GAME_EVENT" | "GAME_RULE_VALUES" | "GAME_EVENT_TEST_HIGHLIGHT_POS" | "MOUNT_SCREEN_OPEN" | "HURT_ANIMATION" | "INITIALIZE_BORDER" | "KEEP_ALIVE" | "LEVEL_CHUNK_WITH_LIGHT" | "LEVEL_EVENT" | "LEVEL_PARTICLES" | "LIGHT_UPDATE" | "LOGIN" | "LOW_DISK_SPACE_WARNING" | "MAP_ITEM_DATA" | "MERCHANT_OFFERS" | "MOVE_ENTITY_POS" | "MOVE_ENTITY_POS_ROT" | "MOVE_MINECART_ALONG_TRACK" | "MOVE_ENTITY_ROT" | "MOVE_VEHICLE" | "OPEN_BOOK" | "OPEN_SCREEN" | "OPEN_SIGN_EDITOR" | "PING" | "PONG_RESPONSE" | "PLACE_GHOST_RECIPE" | "PLAYER_ABILITIES" | "PLAYER_CHAT" | "PLAYER_COMBAT_END" | "PLAYER_COMBAT_ENTER" | "PLAYER_COMBAT_KILL" | "PLAYER_INFO_REMOVE" | "PLAYER_INFO_UPDATE" | "PLAYER_LOOK_AT" | "PLAYER_POSITION" | "PLAYER_ROTATION" | "RECIPE_BOOK_ADD" | "RECIPE_BOOK_REMOVE" | "RECIPE_BOOK_SETTINGS" | "REMOVE_ENTITIES" | "REMOVE_MOB_EFFECT" | "RESET_SCORE" | "RESOURCE_PACK_POP" | "RESOURCE_PACK_PUSH" | "RESPAWN" | "ROTATE_HEAD" | "SECTION_BLOCKS_UPDATE" | "SELECT_ADVANCEMENTS_TAB" | "SERVER_DATA" | "SET_ACTION_BAR_TEXT" | "SET_BORDER_CENTER" | "SET_BORDER_LERP_SIZE" | "SET_BORDER_SIZE" | "SET_BORDER_WARNING_DELAY" | "SET_BORDER_WARNING_DISTANCE" | "SET_CAMERA" | "SET_CHUNK_CACHE_CENTER" | "SET_CHUNK_CACHE_RADIUS" | "SET_CURSOR_ITEM" | "SET_DEFAULT_SPAWN_POSITION" | "SET_DISPLAY_OBJECTIVE" | "SET_ENTITY_DATA" | "SET_ENTITY_LINK" | "SET_ENTITY_MOTION" | "SET_EQUIPMENT" | "SET_EXPERIENCE" | "SET_HEALTH" | "SET_HELD_SLOT" | "SET_OBJECTIVE" | "SET_PASSENGERS" | "SET_PLAYER_INVENTORY" | "SET_PLAYER_TEAM" | "SET_SCORE" | "SET_SIMULATION_DISTANCE" | "SET_SUBTITLE_TEXT" | "SET_TIME" | "SET_TITLE_TEXT" | "SET_TITLES_ANIMATION" | "SOUND_ENTITY" | "SOUND" | "START_CONFIGURATION" | "STOP_SOUND" | "STORE_COOKIE" | "SYSTEM_CHAT" | "TAB_LIST" | "TAG_QUERY" | "TAKE_ITEM_ENTITY" | "TELEPORT_ENTITY" | "TEST_INSTANCE_BLOCK_STATUS" | "TICKING_STATE" | "TICKING_STEP" | "TRANSFER" | "UPDATE_ADVANCEMENTS" | "UPDATE_ATTRIBUTES" | "UPDATE_MOB_EFFECT" | "UPDATE_RECIPES" | "UPDATE_TAGS" | "PROJECTILE_POWER" | "CUSTOM_REPORT_DETAILS" | "SERVER_LINKS" | "TRACKED_WAYPOINT" | "CLEAR_DIALOG" | "SHOW_DIALOG";
}