import type { StackTraceElement } from '../../../../java/lang/StackTraceElement.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../../java/lang/CharSequence.d.ts'
import type { Throwable } from '../../../../java/lang/Throwable.d.ts'
import type { Level } from '../../../../org/apache/logging/log4j/Level.d.ts'
import type { LogBuilder } from '../../../../org/apache/logging/log4j/LogBuilder.d.ts'
import type { Marker } from '../../../../org/apache/logging/log4j/Marker.d.ts'
import type { EntryMessage } from '../../../../org/apache/logging/log4j/message/EntryMessage.d.ts'
import type { FlowMessageFactory } from '../../../../org/apache/logging/log4j/message/FlowMessageFactory.d.ts'
import type { Message } from '../../../../org/apache/logging/log4j/message/Message.d.ts'
import type { MessageFactory } from '../../../../org/apache/logging/log4j/message/MessageFactory.d.ts'
import type { MessageSupplier } from '../../../../org/apache/logging/log4j/util/MessageSupplier.d.ts'
import type { Supplier } from '../../../../org/apache/logging/log4j/util/Supplier.d.ts'
export interface Logger extends Object {
    always(): LogBuilder;
    atDebug(): LogBuilder;
    atError(): LogBuilder;
    atFatal(): LogBuilder;
    atInfo(): LogBuilder;
    atLevel(level: Level): LogBuilder;
    atTrace(): LogBuilder;
    atWarn(): LogBuilder;
    catching(throwable: Throwable): void;
    catching(level: Level, throwable: Throwable): void;
    debug(message: Object): void;
    debug(message: Object, throwable: Throwable): void;
    debug(message: CharSequence): void;
    debug(message: CharSequence, throwable: Throwable): void;
    debug(message: string): void;
    debug(message: string, p0: Object): void;
    debug(message: string, p0: Object, p1: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    debug(message: string, params: Object[]): void;
    debug(message: string, paramSuppliers: () => Object | null[]): void;
    debug(message: string, throwable: Throwable): void;
    debug(marker: Marker, message: Object): void;
    debug(marker: Marker, message: Object, throwable: Throwable): void;
    debug(marker: Marker, message: CharSequence): void;
    debug(marker: Marker, message: CharSequence, throwable: Throwable): void;
    debug(marker: Marker, message: string): void;
    debug(marker: Marker, message: string, p0: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    debug(marker: Marker, message: string, params: Object[]): void;
    debug(marker: Marker, message: string, paramSuppliers: () => Object | null[]): void;
    debug(marker: Marker, message: string, throwable: Throwable): void;
    debug(marker: Marker, message: Message): void;
    debug(marker: Marker, message: Message, throwable: Throwable): void;
    debug(marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    debug(marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    debug(marker: Marker, messageSupplier: () => Object | null): void;
    debug(marker: Marker, messageSupplier: () => Object | null, throwable: Throwable): void;
    debug(message: Message): void;
    debug(message: Message, throwable: Throwable): void;
    debug(messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    debug(messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    debug(messageSupplier: () => Object | null): void;
    debug(messageSupplier: () => Object | null, throwable: Throwable): void;
    entry(): void;
    entry(params: Object[]): void;
    error(message: Object): void;
    error(message: Object, throwable: Throwable): void;
    error(message: CharSequence): void;
    error(message: CharSequence, throwable: Throwable): void;
    error(message: string): void;
    error(message: string, p0: Object): void;
    error(message: string, p0: Object, p1: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    error(message: string, params: Object[]): void;
    error(message: string, paramSuppliers: () => Object | null[]): void;
    error(message: string, throwable: Throwable): void;
    error(marker: Marker, message: Object): void;
    error(marker: Marker, message: Object, throwable: Throwable): void;
    error(marker: Marker, message: CharSequence): void;
    error(marker: Marker, message: CharSequence, throwable: Throwable): void;
    error(marker: Marker, message: string): void;
    error(marker: Marker, message: string, p0: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    error(marker: Marker, message: string, params: Object[]): void;
    error(marker: Marker, message: string, paramSuppliers: () => Object | null[]): void;
    error(marker: Marker, message: string, throwable: Throwable): void;
    error(marker: Marker, message: Message): void;
    error(marker: Marker, message: Message, throwable: Throwable): void;
    error(marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    error(marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    error(marker: Marker, messageSupplier: () => Object | null): void;
    error(marker: Marker, messageSupplier: () => Object | null, throwable: Throwable): void;
    error(message: Message): void;
    error(message: Message, throwable: Throwable): void;
    error(messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    error(messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    error(messageSupplier: () => Object | null): void;
    error(messageSupplier: () => Object | null, throwable: Throwable): void;
    exit(): void;
    exit<R extends Object | number | string | boolean>(result: R): R;
    fatal(message: Object): void;
    fatal(message: Object, throwable: Throwable): void;
    fatal(message: CharSequence): void;
    fatal(message: CharSequence, throwable: Throwable): void;
    fatal(message: string): void;
    fatal(message: string, p0: Object): void;
    fatal(message: string, p0: Object, p1: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    fatal(message: string, params: Object[]): void;
    fatal(message: string, paramSuppliers: () => Object | null[]): void;
    fatal(message: string, throwable: Throwable): void;
    fatal(marker: Marker, message: Object): void;
    fatal(marker: Marker, message: Object, throwable: Throwable): void;
    fatal(marker: Marker, message: CharSequence): void;
    fatal(marker: Marker, message: CharSequence, throwable: Throwable): void;
    fatal(marker: Marker, message: string): void;
    fatal(marker: Marker, message: string, p0: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    fatal(marker: Marker, message: string, params: Object[]): void;
    fatal(marker: Marker, message: string, paramSuppliers: () => Object | null[]): void;
    fatal(marker: Marker, message: string, throwable: Throwable): void;
    fatal(marker: Marker, message: Message): void;
    fatal(marker: Marker, message: Message, throwable: Throwable): void;
    fatal(marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    fatal(marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    fatal(marker: Marker, messageSupplier: () => Object | null): void;
    fatal(marker: Marker, messageSupplier: () => Object | null, throwable: Throwable): void;
    fatal(message: Message): void;
    fatal(message: Message, throwable: Throwable): void;
    fatal(messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    fatal(messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    fatal(messageSupplier: () => Object | null): void;
    fatal(messageSupplier: () => Object | null, throwable: Throwable): void;
    getFlowMessageFactory(): FlowMessageFactory;
    getLevel(): Level;
    getMessageFactory<MF extends MessageFactory>(): MF;
    getName(): string;
    info(message: Object): void;
    info(message: Object, throwable: Throwable): void;
    info(message: CharSequence): void;
    info(message: CharSequence, throwable: Throwable): void;
    info(message: string): void;
    info(message: string, p0: Object): void;
    info(message: string, p0: Object, p1: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    info(message: string, params: Object[]): void;
    info(message: string, paramSuppliers: () => Object | null[]): void;
    info(message: string, throwable: Throwable): void;
    info(marker: Marker, message: Object): void;
    info(marker: Marker, message: Object, throwable: Throwable): void;
    info(marker: Marker, message: CharSequence): void;
    info(marker: Marker, message: CharSequence, throwable: Throwable): void;
    info(marker: Marker, message: string): void;
    info(marker: Marker, message: string, p0: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    info(marker: Marker, message: string, params: Object[]): void;
    info(marker: Marker, message: string, paramSuppliers: () => Object | null[]): void;
    info(marker: Marker, message: string, throwable: Throwable): void;
    info(marker: Marker, message: Message): void;
    info(marker: Marker, message: Message, throwable: Throwable): void;
    info(marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    info(marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    info(marker: Marker, messageSupplier: () => Object | null): void;
    info(marker: Marker, messageSupplier: () => Object | null, throwable: Throwable): void;
    info(message: Message): void;
    info(message: Message, throwable: Throwable): void;
    info(messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    info(messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    info(messageSupplier: () => Object | null): void;
    info(messageSupplier: () => Object | null, throwable: Throwable): void;
    isDebugEnabled(): boolean;
    isDebugEnabled(marker: Marker): boolean;
    isEnabled(level: Level): boolean;
    isEnabled(level: Level, marker: Marker): boolean;
    isErrorEnabled(): boolean;
    isErrorEnabled(marker: Marker): boolean;
    isFatalEnabled(): boolean;
    isFatalEnabled(marker: Marker): boolean;
    isInfoEnabled(): boolean;
    isInfoEnabled(marker: Marker): boolean;
    isTraceEnabled(): boolean;
    isTraceEnabled(marker: Marker): boolean;
    isWarnEnabled(): boolean;
    isWarnEnabled(marker: Marker): boolean;
    log(level: Level, message: Object): void;
    log(level: Level, message: Object, throwable: Throwable): void;
    log(level: Level, message: CharSequence): void;
    log(level: Level, message: CharSequence, throwable: Throwable): void;
    log(level: Level, message: string): void;
    log(level: Level, message: string, p0: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    log(level: Level, message: string, params: Object[]): void;
    log(level: Level, message: string, paramSuppliers: () => Object | null[]): void;
    log(level: Level, message: string, throwable: Throwable): void;
    log(level: Level, marker: Marker, message: Object): void;
    log(level: Level, marker: Marker, message: Object, throwable: Throwable): void;
    log(level: Level, marker: Marker, message: CharSequence): void;
    log(level: Level, marker: Marker, message: CharSequence, throwable: Throwable): void;
    log(level: Level, marker: Marker, message: string): void;
    log(level: Level, marker: Marker, message: string, p0: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    log(level: Level, marker: Marker, message: string, params: Object[]): void;
    log(level: Level, marker: Marker, message: string, paramSuppliers: () => Object | null[]): void;
    log(level: Level, marker: Marker, message: string, throwable: Throwable): void;
    log(level: Level, marker: Marker, message: Message): void;
    log(level: Level, marker: Marker, message: Message, throwable: Throwable): void;
    log(level: Level, marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    log(level: Level, marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    log(level: Level, marker: Marker, messageSupplier: () => Object | null): void;
    log(level: Level, marker: Marker, messageSupplier: () => Object | null, throwable: Throwable): void;
    log(level: Level, message: Message): void;
    log(level: Level, message: Message, throwable: Throwable): void;
    log(level: Level, messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    log(level: Level, messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    log(level: Level, messageSupplier: () => Object | null): void;
    log(level: Level, messageSupplier: () => Object | null, throwable: Throwable): void;
    logMessage(level: Level, marker: Marker, fqcn: string, location: StackTraceElement, message: Message, throwable: Throwable): void;
    printf(level: Level, format: string, params: Object[]): void;
    printf(level: Level, marker: Marker, format: string, params: Object[]): void;
    throwing<T extends Throwable>(throwable: T): T;
    throwing<T extends Throwable>(level: Level, throwable: T): T;
    trace(message: Object): void;
    trace(message: Object, throwable: Throwable): void;
    trace(message: CharSequence): void;
    trace(message: CharSequence, throwable: Throwable): void;
    trace(message: string): void;
    trace(message: string, p0: Object): void;
    trace(message: string, p0: Object, p1: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    trace(message: string, params: Object[]): void;
    trace(message: string, paramSuppliers: () => Object | null[]): void;
    trace(message: string, throwable: Throwable): void;
    trace(marker: Marker, message: Object): void;
    trace(marker: Marker, message: Object, throwable: Throwable): void;
    trace(marker: Marker, message: CharSequence): void;
    trace(marker: Marker, message: CharSequence, throwable: Throwable): void;
    trace(marker: Marker, message: string): void;
    trace(marker: Marker, message: string, p0: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    trace(marker: Marker, message: string, params: Object[]): void;
    trace(marker: Marker, message: string, paramSuppliers: () => Object | null[]): void;
    trace(marker: Marker, message: string, throwable: Throwable): void;
    trace(marker: Marker, message: Message): void;
    trace(marker: Marker, message: Message, throwable: Throwable): void;
    trace(marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    trace(marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    trace(marker: Marker, messageSupplier: () => Object | null): void;
    trace(marker: Marker, messageSupplier: () => Object | null, throwable: Throwable): void;
    trace(message: Message): void;
    trace(message: Message, throwable: Throwable): void;
    trace(messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    trace(messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    trace(messageSupplier: () => Object | null): void;
    trace(messageSupplier: () => Object | null, throwable: Throwable): void;
    traceEntry(): EntryMessage;
    traceEntry(paramSuppliers: () => Object | null[]): EntryMessage;
    traceEntry(format: string, params: Object[]): EntryMessage;
    traceEntry(format: string, paramSuppliers: () => Object | null[]): EntryMessage;
    traceEntry(message: Message): EntryMessage;
    traceExit(): void;
    traceExit<R extends Object | number | string | boolean>(result: R): R;
    traceExit<R extends Object | number | string | boolean>(format: string, result: R): R;
    traceExit(message: EntryMessage): void;
    traceExit<R extends Object | number | string | boolean>(message: EntryMessage, result: R): R;
    traceExit<R extends Object | number | string | boolean>(message: Message, result: R): R;
    warn(message: Object): void;
    warn(message: Object, throwable: Throwable): void;
    warn(message: CharSequence): void;
    warn(message: CharSequence, throwable: Throwable): void;
    warn(message: string): void;
    warn(message: string, p0: Object): void;
    warn(message: string, p0: Object, p1: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    warn(message: string, params: Object[]): void;
    warn(message: string, paramSuppliers: () => Object | null[]): void;
    warn(message: string, throwable: Throwable): void;
    warn(marker: Marker, message: Object): void;
    warn(marker: Marker, message: Object, throwable: Throwable): void;
    warn(marker: Marker, message: CharSequence): void;
    warn(marker: Marker, message: CharSequence, throwable: Throwable): void;
    warn(marker: Marker, message: string): void;
    warn(marker: Marker, message: string, p0: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    warn(marker: Marker, message: string, params: Object[]): void;
    warn(marker: Marker, message: string, paramSuppliers: () => Object | null[]): void;
    warn(marker: Marker, message: string, throwable: Throwable): void;
    warn(marker: Marker, message: Message): void;
    warn(marker: Marker, message: Message, throwable: Throwable): void;
    warn(marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    warn(marker: Marker, messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    warn(marker: Marker, messageSupplier: () => Object | null): void;
    warn(marker: Marker, messageSupplier: () => Object | null, throwable: Throwable): void;
    warn(message: Message): void;
    warn(message: Message, throwable: Throwable): void;
    warn(messageSupplier: () => org.apache.logging.log4j.message.Message): void;
    warn(messageSupplier: () => org.apache.logging.log4j.message.Message, throwable: Throwable): void;
    warn(messageSupplier: () => Object | null): void;
    warn(messageSupplier: () => Object | null, throwable: Throwable): void;
}