import type { StackTraceElement } from '../../../../../java/lang/StackTraceElement.d.ts'
import type { Object } from '../../../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../../../java/lang/CharSequence.d.ts'
import type { Throwable } from '../../../../../java/lang/Throwable.d.ts'
import type { Level } from '../../../../../org/apache/logging/log4j/Level.d.ts'
import type { LogBuilder } from '../../../../../org/apache/logging/log4j/LogBuilder.d.ts'
import type { Logger } from '../../../../../org/apache/logging/log4j/Logger.d.ts'
import type { Marker } from '../../../../../org/apache/logging/log4j/Marker.d.ts'
import type { EntryMessage } from '../../../../../org/apache/logging/log4j/message/EntryMessage.d.ts'
import type { FlowMessageFactory } from '../../../../../org/apache/logging/log4j/message/FlowMessageFactory.d.ts'
import type { Message } from '../../../../../org/apache/logging/log4j/message/Message.d.ts'
import type { MessageSupplier } from '../../../../../org/apache/logging/log4j/util/MessageSupplier.d.ts'
import type { Supplier } from '../../../../../org/apache/logging/log4j/util/Supplier.d.ts'
export interface ExtendedLogger extends Object, Logger {
    always(): LogBuilder;
    atDebug(): LogBuilder;
    atError(): LogBuilder;
    atFatal(): LogBuilder;
    atInfo(): LogBuilder;
    atLevel(level: Level): LogBuilder;
    atTrace(): LogBuilder;
    atWarn(): LogBuilder;
    catching(throwable: Throwable): void;
    catching(level: Level, throwable: Throwable): void;
    debug(message: Object): void;
    debug(message: Object, throwable: Throwable): void;
    debug(message: CharSequence): void;
    debug(message: CharSequence, throwable: Throwable): void;
    debug(message: string): void;
    debug(message: string, p0: Object): void;
    debug(message: string, p0: Object, p1: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    debug(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    debug(message: string, throwable: Throwable): void;
    debug(marker: Marker, message: Object): void;
    debug(marker: Marker, message: Object, throwable: Throwable): void;
    debug(marker: Marker, message: CharSequence): void;
    debug(marker: Marker, message: CharSequence, throwable: Throwable): void;
    debug(marker: Marker, message: string): void;
    debug(marker: Marker, message: string, p0: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    debug(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    debug(marker: Marker, message: string, throwable: Throwable): void;
    debug(marker: Marker, message: Message): void;
    debug(marker: Marker, message: Message, throwable: Throwable): void;
    debug(marker: Marker, messageSupplier: () => Message): void;
    debug(marker: Marker, messageSupplier: () => Message, throwable: Throwable): void;
    debug(message: Message): void;
    debug(message: Message, throwable: Throwable): void;
    debug(messageSupplier: () => Message): void;
    debug(messageSupplier: () => Message, throwable: Throwable): void;
    entry(): void;
    error(message: Object): void;
    error(message: Object, throwable: Throwable): void;
    error(message: CharSequence): void;
    error(message: CharSequence, throwable: Throwable): void;
    error(message: string): void;
    error(message: string, p0: Object): void;
    error(message: string, p0: Object, p1: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    error(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    error(message: string, throwable: Throwable): void;
    error(marker: Marker, message: Object): void;
    error(marker: Marker, message: Object, throwable: Throwable): void;
    error(marker: Marker, message: CharSequence): void;
    error(marker: Marker, message: CharSequence, throwable: Throwable): void;
    error(marker: Marker, message: string): void;
    error(marker: Marker, message: string, p0: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    error(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    error(marker: Marker, message: string, throwable: Throwable): void;
    error(marker: Marker, message: Message): void;
    error(marker: Marker, message: Message, throwable: Throwable): void;
    error(marker: Marker, messageSupplier: () => Message): void;
    error(marker: Marker, messageSupplier: () => Message, throwable: Throwable): void;
    error(message: Message): void;
    error(message: Message, throwable: Throwable): void;
    error(messageSupplier: () => Message): void;
    error(messageSupplier: () => Message, throwable: Throwable): void;
    exit(): void;
    fatal(message: Object): void;
    fatal(message: Object, throwable: Throwable): void;
    fatal(message: CharSequence): void;
    fatal(message: CharSequence, throwable: Throwable): void;
    fatal(message: string): void;
    fatal(message: string, p0: Object): void;
    fatal(message: string, p0: Object, p1: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    fatal(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    fatal(message: string, throwable: Throwable): void;
    fatal(marker: Marker, message: Object): void;
    fatal(marker: Marker, message: Object, throwable: Throwable): void;
    fatal(marker: Marker, message: CharSequence): void;
    fatal(marker: Marker, message: CharSequence, throwable: Throwable): void;
    fatal(marker: Marker, message: string): void;
    fatal(marker: Marker, message: string, p0: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    fatal(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    fatal(marker: Marker, message: string, throwable: Throwable): void;
    fatal(marker: Marker, message: Message): void;
    fatal(marker: Marker, message: Message, throwable: Throwable): void;
    fatal(marker: Marker, messageSupplier: () => Message): void;
    fatal(marker: Marker, messageSupplier: () => Message, throwable: Throwable): void;
    fatal(message: Message): void;
    fatal(message: Message, throwable: Throwable): void;
    fatal(messageSupplier: () => Message): void;
    fatal(messageSupplier: () => Message, throwable: Throwable): void;
    getFlowMessageFactory(): FlowMessageFactory;
    getLevel(): Level;
    getName(): string;
    info(message: Object): void;
    info(message: Object, throwable: Throwable): void;
    info(message: CharSequence): void;
    info(message: CharSequence, throwable: Throwable): void;
    info(message: string): void;
    info(message: string, p0: Object): void;
    info(message: string, p0: Object, p1: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    info(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    info(message: string, throwable: Throwable): void;
    info(marker: Marker, message: Object): void;
    info(marker: Marker, message: Object, throwable: Throwable): void;
    info(marker: Marker, message: CharSequence): void;
    info(marker: Marker, message: CharSequence, throwable: Throwable): void;
    info(marker: Marker, message: string): void;
    info(marker: Marker, message: string, p0: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    info(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    info(marker: Marker, message: string, throwable: Throwable): void;
    info(marker: Marker, message: Message): void;
    info(marker: Marker, message: Message, throwable: Throwable): void;
    info(marker: Marker, messageSupplier: () => Message): void;
    info(marker: Marker, messageSupplier: () => Message, throwable: Throwable): void;
    info(message: Message): void;
    info(message: Message, throwable: Throwable): void;
    info(messageSupplier: () => Message): void;
    info(messageSupplier: () => Message, throwable: Throwable): void;
    isDebugEnabled(): boolean;
    isDebugEnabled(marker: Marker): boolean;
    isEnabled(level: Level): boolean;
    isEnabled(level: Level, marker: Marker): boolean;
    isEnabled(level: Level, marker: Marker, message: Object, t: Throwable): boolean;
    isEnabled(level: Level, marker: Marker, message: CharSequence, t: Throwable): boolean;
    isEnabled(level: Level, marker: Marker, message: string): boolean;
    isEnabled(level: Level, marker: Marker, message: string, p0: Object): boolean;
    isEnabled(level: Level, marker: Marker, message: string, p0: Object, p1: Object): boolean;
    isEnabled(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object): boolean;
    isEnabled(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): boolean;
    isEnabled(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): boolean;
    isEnabled(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): boolean;
    isEnabled(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): boolean;
    isEnabled(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): boolean;
    isEnabled(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): boolean;
    isEnabled(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): boolean;
    isEnabled(level: Level, marker: Marker, message: string, params: Object[]): boolean;
    isEnabled(level: Level, marker: Marker, message: string, t: Throwable): boolean;
    isEnabled(level: Level, marker: Marker, message: Message, t: Throwable): boolean;
    isErrorEnabled(): boolean;
    isErrorEnabled(marker: Marker): boolean;
    isFatalEnabled(): boolean;
    isFatalEnabled(marker: Marker): boolean;
    isInfoEnabled(): boolean;
    isInfoEnabled(marker: Marker): boolean;
    isTraceEnabled(): boolean;
    isTraceEnabled(marker: Marker): boolean;
    isWarnEnabled(): boolean;
    isWarnEnabled(marker: Marker): boolean;
    log(level: Level, message: Object): void;
    log(level: Level, message: Object, throwable: Throwable): void;
    log(level: Level, message: CharSequence): void;
    log(level: Level, message: CharSequence, throwable: Throwable): void;
    log(level: Level, message: string): void;
    log(level: Level, message: string, p0: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    log(level: Level, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    log(level: Level, message: string, throwable: Throwable): void;
    log(level: Level, marker: Marker, message: Object): void;
    log(level: Level, marker: Marker, message: Object, throwable: Throwable): void;
    log(level: Level, marker: Marker, message: CharSequence): void;
    log(level: Level, marker: Marker, message: CharSequence, throwable: Throwable): void;
    log(level: Level, marker: Marker, message: string): void;
    log(level: Level, marker: Marker, message: string, p0: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    log(level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    log(level: Level, marker: Marker, message: string, throwable: Throwable): void;
    log(level: Level, marker: Marker, message: Message): void;
    log(level: Level, marker: Marker, message: Message, throwable: Throwable): void;
    log(level: Level, marker: Marker, messageSupplier: () => Message): void;
    log(level: Level, marker: Marker, messageSupplier: () => Message, throwable: Throwable): void;
    log(level: Level, message: Message): void;
    log(level: Level, message: Message, throwable: Throwable): void;
    log(level: Level, messageSupplier: () => Message): void;
    log(level: Level, messageSupplier: () => Message, throwable: Throwable): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: Object, t: Throwable): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: CharSequence, t: Throwable): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string, p0: Object): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string, p0: Object, p1: Object): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string, params: Object[]): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string, paramSuppliers: () => Object | null[]): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: string, t: Throwable): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, message: Message, t: Throwable): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, msgSupplier: () => Message, t: Throwable): void;
    logIfEnabled(fqcn: string, level: Level, marker: Marker, msgSupplier: () => Object | null, t: Throwable): void;
    logMessage(level: Level, marker: Marker, fqcn: string, location: StackTraceElement, message: Message, throwable: Throwable): void;
    logMessage(fqcn: string, level: Level, marker: Marker, message: Message, t: Throwable): void;
    trace(message: Object): void;
    trace(message: Object, throwable: Throwable): void;
    trace(message: CharSequence): void;
    trace(message: CharSequence, throwable: Throwable): void;
    trace(message: string): void;
    trace(message: string, p0: Object): void;
    trace(message: string, p0: Object, p1: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    trace(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    trace(message: string, throwable: Throwable): void;
    trace(marker: Marker, message: Object): void;
    trace(marker: Marker, message: Object, throwable: Throwable): void;
    trace(marker: Marker, message: CharSequence): void;
    trace(marker: Marker, message: CharSequence, throwable: Throwable): void;
    trace(marker: Marker, message: string): void;
    trace(marker: Marker, message: string, p0: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    trace(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    trace(marker: Marker, message: string, throwable: Throwable): void;
    trace(marker: Marker, message: Message): void;
    trace(marker: Marker, message: Message, throwable: Throwable): void;
    trace(marker: Marker, messageSupplier: () => Message): void;
    trace(marker: Marker, messageSupplier: () => Message, throwable: Throwable): void;
    trace(message: Message): void;
    trace(message: Message, throwable: Throwable): void;
    trace(messageSupplier: () => Message): void;
    trace(messageSupplier: () => Message, throwable: Throwable): void;
    traceEntry(): EntryMessage;
    traceEntry(message: Message): EntryMessage;
    traceExit(): void;
    traceExit(message: EntryMessage): void;
    warn(message: Object): void;
    warn(message: Object, throwable: Throwable): void;
    warn(message: CharSequence): void;
    warn(message: CharSequence, throwable: Throwable): void;
    warn(message: string): void;
    warn(message: string, p0: Object): void;
    warn(message: string, p0: Object, p1: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    warn(message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    warn(message: string, throwable: Throwable): void;
    warn(marker: Marker, message: Object): void;
    warn(marker: Marker, message: Object, throwable: Throwable): void;
    warn(marker: Marker, message: CharSequence): void;
    warn(marker: Marker, message: CharSequence, throwable: Throwable): void;
    warn(marker: Marker, message: string): void;
    warn(marker: Marker, message: string, p0: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object): void;
    warn(marker: Marker, message: string, p0: Object, p1: Object, p2: Object, p3: Object, p4: Object, p5: Object, p6: Object, p7: Object, p8: Object, p9: Object): void;
    warn(marker: Marker, message: string, throwable: Throwable): void;
    warn(marker: Marker, message: Message): void;
    warn(marker: Marker, message: Message, throwable: Throwable): void;
    warn(marker: Marker, messageSupplier: () => Message): void;
    warn(marker: Marker, messageSupplier: () => Message, throwable: Throwable): void;
    warn(message: Message): void;
    warn(message: Message, throwable: Throwable): void;
    warn(messageSupplier: () => Message): void;
    warn(messageSupplier: () => Message, throwable: Throwable): void;
}