import type { CefMenuModel } from '../../../org/cef/callback/CefMenuModel.d.ts'
import type { CefMenuModel$MenuItemType } from '../../../org/cef/callback/CefMenuModel$MenuItemType.d.ts'
import type { CefNativeAdapter } from '../../../org/cef/callback/CefNativeAdapter.d.ts'
import type { BoolRef } from '../../../org/cef/misc/BoolRef.d.ts'
import type { IntRef } from '../../../org/cef/misc/IntRef.d.ts'
export class CefMenuModel_N extends CefNativeAdapter implements CefMenuModel {
    constructor()
    // private N_AddCheckItem(arg0: number, arg1: number, arg2: string): boolean;
    // private N_AddItem(arg0: number, arg1: number, arg2: string): boolean;
    // private N_AddRadioItem(arg0: number, arg1: number, arg2: string, arg3: number): boolean;
    // private N_AddSeparator(arg0: number): boolean;
    // private N_AddSubMenu(arg0: number, arg1: number, arg2: string): CefMenuModel;
    // private N_Clear(arg0: number): boolean;
    // private N_GetAccelerator(arg0: number, arg1: number, arg2: IntRef, arg3: BoolRef, arg4: BoolRef, arg5: BoolRef): boolean;
    // private N_GetAcceleratorAt(arg0: number, arg1: number, arg2: IntRef, arg3: BoolRef, arg4: BoolRef, arg5: BoolRef): boolean;
    // private N_GetCommandIdAt(arg0: number, arg1: number): number;
    // private N_GetCount(arg0: number): number;
    // private N_GetGroupId(arg0: number, arg1: number): number;
    // private N_GetGroupIdAt(arg0: number, arg1: number): number;
    // private N_GetIndexOf(arg0: number, arg1: number): number;
    // private N_GetLabel(arg0: number, arg1: number): string;
    // private N_GetLabelAt(arg0: number, arg1: number): string;
    // private N_GetSubMenu(arg0: number, arg1: number): CefMenuModel;
    // private N_GetSubMenuAt(arg0: number, arg1: number): CefMenuModel;
    // private N_GetType(arg0: number, arg1: number): CefMenuModel$MenuItemType;
    // private N_GetTypeAt(arg0: number, arg1: number): CefMenuModel$MenuItemType;
    // private N_HasAccelerator(arg0: number, arg1: number): boolean;
    // private N_HasAcceleratorAt(arg0: number, arg1: number): boolean;
    // private N_InsertCheckItemAt(arg0: number, arg1: number, arg2: number, arg3: string): boolean;
    // private N_InsertItemAt(arg0: number, arg1: number, arg2: number, arg3: string): boolean;
    // private N_InsertRadioItemAt(arg0: number, arg1: number, arg2: number, arg3: string, arg4: number): boolean;
    // private N_InsertSeparatorAt(arg0: number, arg1: number): boolean;
    // private N_InsertSubMenuAt(arg0: number, arg1: number, arg2: number, arg3: string): CefMenuModel;
    // private N_IsChecked(arg0: number, arg1: number): boolean;
    // private N_IsCheckedAt(arg0: number, arg1: number): boolean;
    // private N_IsEnabled(arg0: number, arg1: number): boolean;
    // private N_IsEnabledAt(arg0: number, arg1: number): boolean;
    // private N_IsVisible(arg0: number, arg1: number): boolean;
    // private N_IsVisibleAt(arg0: number, arg1: number): boolean;
    // private N_Remove(arg0: number, arg1: number): boolean;
    // private N_RemoveAccelerator(arg0: number, arg1: number): boolean;
    // private N_RemoveAcceleratorAt(arg0: number, arg1: number): boolean;
    // private N_RemoveAt(arg0: number, arg1: number): boolean;
    // private N_SetAccelerator(arg0: number, arg1: number, arg2: number, arg3: boolean, arg4: boolean, arg5: boolean): boolean;
    // private N_SetAcceleratorAt(arg0: number, arg1: number, arg2: number, arg3: boolean, arg4: boolean, arg5: boolean): boolean;
    // private N_SetChecked(arg0: number, arg1: number, arg2: boolean): boolean;
    // private N_SetCheckedAt(arg0: number, arg1: number, arg2: boolean): boolean;
    // private N_SetCommandIdAt(arg0: number, arg1: number, arg2: number): boolean;
    // private N_SetEnabled(arg0: number, arg1: number, arg2: boolean): boolean;
    // private N_SetEnabledAt(arg0: number, arg1: number, arg2: boolean): boolean;
    // private N_SetGroupId(arg0: number, arg1: number, arg2: number): boolean;
    // private N_SetGroupIdAt(arg0: number, arg1: number, arg2: number): boolean;
    // private N_SetLabel(arg0: number, arg1: number, arg2: string): boolean;
    // private N_SetLabelAt(arg0: number, arg1: number, arg2: string): boolean;
    // private N_SetVisible(arg0: number, arg1: number, arg2: boolean): boolean;
    // private N_SetVisibleAt(arg0: number, arg1: number, arg2: boolean): boolean;
    addCheckItem(arg0: number, arg1: string): boolean;
    addItem(arg0: number, arg1: string): boolean;
    addRadioItem(arg0: number, arg1: string, arg2: number): boolean;
    addSeparator(): boolean;
    addSubMenu(arg0: number, arg1: string): CefMenuModel;
    clear(): boolean;
    getAccelerator(arg0: number, arg1: IntRef, arg2: BoolRef, arg3: BoolRef, arg4: BoolRef): boolean;
    getAcceleratorAt(arg0: number, arg1: IntRef, arg2: BoolRef, arg3: BoolRef, arg4: BoolRef): boolean;
    getCommandIdAt(arg0: number): number;
    getCount(): number;
    getGroupId(arg0: number): number;
    getGroupIdAt(arg0: number): number;
    getIndexOf(arg0: number): number;
    getLabel(arg0: number): string;
    getLabelAt(arg0: number): string;
    getSubMenu(arg0: number): CefMenuModel;
    getSubMenuAt(arg0: number): CefMenuModel;
    getType(arg0: number): CefMenuModel$MenuItemType;
    getTypeAt(arg0: number): CefMenuModel$MenuItemType;
    hasAccelerator(arg0: number): boolean;
    hasAcceleratorAt(arg0: number): boolean;
    insertCheckItemAt(arg0: number, arg1: number, arg2: string): boolean;
    insertItemAt(arg0: number, arg1: number, arg2: string): boolean;
    insertRadioItemAt(arg0: number, arg1: number, arg2: string, arg3: number): boolean;
    insertSeparatorAt(arg0: number): boolean;
    insertSubMenuAt(arg0: number, arg1: number, arg2: string): CefMenuModel;
    isChecked(arg0: number): boolean;
    isCheckedAt(arg0: number): boolean;
    isEnabled(arg0: number): boolean;
    isEnabledAt(arg0: number): boolean;
    isVisible(arg0: number): boolean;
    isVisibleAt(arg0: number): boolean;
    remove(arg0: number): boolean;
    removeAccelerator(arg0: number): boolean;
    removeAcceleratorAt(arg0: number): boolean;
    removeAt(arg0: number): boolean;
    setAccelerator(arg0: number, arg1: number, arg2: boolean, arg3: boolean, arg4: boolean): boolean;
    setAcceleratorAt(arg0: number, arg1: number, arg2: boolean, arg3: boolean, arg4: boolean): boolean;
    setChecked(arg0: number, arg1: boolean): boolean;
    setCheckedAt(arg0: number, arg1: boolean): boolean;
    setCommandIdAt(arg0: number, arg1: number): boolean;
    setEnabled(arg0: number, arg1: boolean): boolean;
    setEnabledAt(arg0: number, arg1: boolean): boolean;
    setGroupId(arg0: number, arg1: number): boolean;
    setGroupIdAt(arg0: number, arg1: number): boolean;
    setLabel(arg0: number, arg1: string): boolean;
    setLabelAt(arg0: number, arg1: string): boolean;
    setVisible(arg0: number, arg1: boolean): boolean;
    setVisibleAt(arg0: number, arg1: boolean): boolean;
}