import type { Class } from '../../../../../../../java/lang/Class.d.ts'
import type { Enum } from '../../../../../../../java/lang/Enum.d.ts'
export class NumberSkeletonImpl$StemEnum extends Enum<NumberSkeletonImpl$StemEnum> {
    static STEM_BASE_UNIT: NumberSkeletonImpl$StemEnum;
    static STEM_COMPACT_LONG: NumberSkeletonImpl$StemEnum;
    static STEM_COMPACT_SHORT: NumberSkeletonImpl$StemEnum;
    static STEM_CURRENCY: NumberSkeletonImpl$StemEnum;
    static STEM_DECIMAL_ALWAYS: NumberSkeletonImpl$StemEnum;
    static STEM_DECIMAL_AUTO: NumberSkeletonImpl$StemEnum;
    static STEM_ENGINEERING: NumberSkeletonImpl$StemEnum;
    static STEM_GROUP_AUTO: NumberSkeletonImpl$StemEnum;
    static STEM_GROUP_MIN2: NumberSkeletonImpl$StemEnum;
    static STEM_GROUP_OFF: NumberSkeletonImpl$StemEnum;
    static STEM_GROUP_ON_ALIGNED: NumberSkeletonImpl$StemEnum;
    static STEM_GROUP_THOUSANDS: NumberSkeletonImpl$StemEnum;
    static STEM_INTEGER_WIDTH: NumberSkeletonImpl$StemEnum;
    static STEM_INTEGER_WIDTH_TRUNC: NumberSkeletonImpl$StemEnum;
    static STEM_LATIN: NumberSkeletonImpl$StemEnum;
    static STEM_MEASURE_UNIT: NumberSkeletonImpl$StemEnum;
    static STEM_NOTATION_SIMPLE: NumberSkeletonImpl$StemEnum;
    static STEM_NUMBERING_SYSTEM: NumberSkeletonImpl$StemEnum;
    static STEM_PERCENT: NumberSkeletonImpl$StemEnum;
    static STEM_PERCENT_100: NumberSkeletonImpl$StemEnum;
    static STEM_PERMILLE: NumberSkeletonImpl$StemEnum;
    static STEM_PER_MEASURE_UNIT: NumberSkeletonImpl$StemEnum;
    static STEM_PRECISION_CURRENCY_CASH: NumberSkeletonImpl$StemEnum;
    static STEM_PRECISION_CURRENCY_STANDARD: NumberSkeletonImpl$StemEnum;
    static STEM_PRECISION_INCREMENT: NumberSkeletonImpl$StemEnum;
    static STEM_PRECISION_INTEGER: NumberSkeletonImpl$StemEnum;
    static STEM_PRECISION_UNLIMITED: NumberSkeletonImpl$StemEnum;
    static STEM_ROUNDING_MODE_CEILING: NumberSkeletonImpl$StemEnum;
    static STEM_ROUNDING_MODE_DOWN: NumberSkeletonImpl$StemEnum;
    static STEM_ROUNDING_MODE_FLOOR: NumberSkeletonImpl$StemEnum;
    static STEM_ROUNDING_MODE_HALF_DOWN: NumberSkeletonImpl$StemEnum;
    static STEM_ROUNDING_MODE_HALF_EVEN: NumberSkeletonImpl$StemEnum;
    static STEM_ROUNDING_MODE_HALF_UP: NumberSkeletonImpl$StemEnum;
    static STEM_ROUNDING_MODE_UNNECESSARY: NumberSkeletonImpl$StemEnum;
    static STEM_ROUNDING_MODE_UP: NumberSkeletonImpl$StemEnum;
    static STEM_SCALE: NumberSkeletonImpl$StemEnum;
    static STEM_SCIENTIFIC: NumberSkeletonImpl$StemEnum;
    static STEM_SIGN_ACCOUNTING: NumberSkeletonImpl$StemEnum;
    static STEM_SIGN_ACCOUNTING_ALWAYS: NumberSkeletonImpl$StemEnum;
    static STEM_SIGN_ACCOUNTING_EXCEPT_ZERO: NumberSkeletonImpl$StemEnum;
    static STEM_SIGN_ACCOUNTING_NEGATIVE: NumberSkeletonImpl$StemEnum;
    static STEM_SIGN_ALWAYS: NumberSkeletonImpl$StemEnum;
    static STEM_SIGN_AUTO: NumberSkeletonImpl$StemEnum;
    static STEM_SIGN_EXCEPT_ZERO: NumberSkeletonImpl$StemEnum;
    static STEM_SIGN_NEGATIVE: NumberSkeletonImpl$StemEnum;
    static STEM_SIGN_NEVER: NumberSkeletonImpl$StemEnum;
    static STEM_UNIT: NumberSkeletonImpl$StemEnum;
    static STEM_UNIT_USAGE: NumberSkeletonImpl$StemEnum;
    static STEM_UNIT_WIDTH_FORMAL: NumberSkeletonImpl$StemEnum;
    static STEM_UNIT_WIDTH_FULL_NAME: NumberSkeletonImpl$StemEnum;
    static STEM_UNIT_WIDTH_HIDDEN: NumberSkeletonImpl$StemEnum;
    static STEM_UNIT_WIDTH_ISO_CODE: NumberSkeletonImpl$StemEnum;
    static STEM_UNIT_WIDTH_NARROW: NumberSkeletonImpl$StemEnum;
    static STEM_UNIT_WIDTH_SHORT: NumberSkeletonImpl$StemEnum;
    static STEM_UNIT_WIDTH_VARIANT: NumberSkeletonImpl$StemEnum;
    static valueOf<T extends Enum<T>>(paramarg0: Class<T>, paramarg1: string): T;
    static valueOf(paramname: string): NumberSkeletonImpl$StemEnum;
    static values(): NumberSkeletonImpl$StemEnum[];
    private constructor()
    name(): "STEM_COMPACT_SHORT" | "STEM_COMPACT_LONG" | "STEM_SCIENTIFIC" | "STEM_ENGINEERING" | "STEM_NOTATION_SIMPLE" | "STEM_BASE_UNIT" | "STEM_PERCENT" | "STEM_PERMILLE" | "STEM_PERCENT_100" | "STEM_PRECISION_INTEGER" | "STEM_PRECISION_UNLIMITED" | "STEM_PRECISION_CURRENCY_STANDARD" | "STEM_PRECISION_CURRENCY_CASH" | "STEM_ROUNDING_MODE_CEILING" | "STEM_ROUNDING_MODE_FLOOR" | "STEM_ROUNDING_MODE_DOWN" | "STEM_ROUNDING_MODE_UP" | "STEM_ROUNDING_MODE_HALF_EVEN" | "STEM_ROUNDING_MODE_HALF_DOWN" | "STEM_ROUNDING_MODE_HALF_UP" | "STEM_ROUNDING_MODE_UNNECESSARY" | "STEM_INTEGER_WIDTH_TRUNC" | "STEM_GROUP_OFF" | "STEM_GROUP_MIN2" | "STEM_GROUP_AUTO" | "STEM_GROUP_ON_ALIGNED" | "STEM_GROUP_THOUSANDS" | "STEM_LATIN" | "STEM_UNIT_WIDTH_NARROW" | "STEM_UNIT_WIDTH_SHORT" | "STEM_UNIT_WIDTH_FULL_NAME" | "STEM_UNIT_WIDTH_ISO_CODE" | "STEM_UNIT_WIDTH_FORMAL" | "STEM_UNIT_WIDTH_VARIANT" | "STEM_UNIT_WIDTH_HIDDEN" | "STEM_SIGN_AUTO" | "STEM_SIGN_ALWAYS" | "STEM_SIGN_NEVER" | "STEM_SIGN_ACCOUNTING" | "STEM_SIGN_ACCOUNTING_ALWAYS" | "STEM_SIGN_EXCEPT_ZERO" | "STEM_SIGN_ACCOUNTING_EXCEPT_ZERO" | "STEM_SIGN_NEGATIVE" | "STEM_SIGN_ACCOUNTING_NEGATIVE" | "STEM_DECIMAL_AUTO" | "STEM_DECIMAL_ALWAYS" | "STEM_PRECISION_INCREMENT" | "STEM_MEASURE_UNIT" | "STEM_PER_MEASURE_UNIT" | "STEM_UNIT" | "STEM_UNIT_USAGE" | "STEM_CURRENCY" | "STEM_INTEGER_WIDTH" | "STEM_NUMBERING_SYSTEM" | "STEM_SCALE";
}