import type { Comparator } from '../../../java/util/Comparator.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { Pair } from '../../../kotlin/Pair.d.ts'
import type { UByte } from '../../../kotlin/UByte.d.ts'
import type { UInt } from '../../../kotlin/UInt.d.ts'
import type { ULong } from '../../../kotlin/ULong.d.ts'
import type { UShort } from '../../../kotlin/UShort.d.ts'
import type { IndexedValue } from '../../../kotlin/collections/IndexedValue.d.ts'
import type { UArraysKt___UArraysKt } from '../../../kotlin/collections/unsigned/UArraysKt___UArraysKt.d.ts'
import type { Random } from '../../../kotlin/random/Random.d.ts'
export class UArraysKt extends UArraysKt___UArraysKt {
// (invalid TS: name contains '-')     static asList--ajY-9A(paramarg0: number[]): UInt[];
// (invalid TS: name contains '-')     static asList-GBYM_sE(paramarg0: number[]): UByte[];
// (invalid TS: name contains '-')     static asList-QwZRm1k(paramarg0: number[]): ULong[];
// (invalid TS: name contains '-')     static asList-rL5Bavg(paramarg0: number[]): UShort[];
// (invalid TS: name contains '-')     static binarySearch-2fe2U9s(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
// (invalid TS: name contains '-')     static binarySearch-EtDCXyQ(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
// (invalid TS: name contains '-')     static binarySearch-K6DWlUc(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
// (invalid TS: name contains '-')     static binarySearch-WpHrYlw(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
// (invalid TS: name contains '-')     static contentEquals-FGO6Aew(paramarg0: number[], paramarg1: number[]): boolean;
// (invalid TS: name contains '-')     static contentEquals-KJPZfPQ(paramarg0: number[], paramarg1: number[]): boolean;
// (invalid TS: name contains '-')     static contentEquals-kV0jMPg(paramarg0: number[], paramarg1: number[]): boolean;
// (invalid TS: name contains '-')     static contentEquals-lec5QzE(paramarg0: number[], paramarg1: number[]): boolean;
// (invalid TS: name contains '-')     static contentHashCode-2csIQuQ(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static contentHashCode-XUkPCBk(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static contentHashCode-d-6D3K8(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static contentHashCode-uLth9ew(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static contentToString-2csIQuQ(paramarg0: number[]): string;
// (invalid TS: name contains '-')     static contentToString-XUkPCBk(paramarg0: number[]): string;
// (invalid TS: name contains '-')     static contentToString-d-6D3K8(paramarg0: number[]): string;
// (invalid TS: name contains '-')     static contentToString-uLth9ew(paramarg0: number[]): string;
// (invalid TS: name contains '-')     static drop-PpDY95g(paramarg0: number[], paramarg1: number): UByte[];
// (invalid TS: name contains '-')     static drop-nggk6HY(paramarg0: number[], paramarg1: number): UShort[];
// (invalid TS: name contains '-')     static drop-qFRl0hI(paramarg0: number[], paramarg1: number): UInt[];
// (invalid TS: name contains '-')     static drop-r7IrZao(paramarg0: number[], paramarg1: number): ULong[];
// (invalid TS: name contains '-')     static dropLast-PpDY95g(paramarg0: number[], paramarg1: number): UByte[];
// (invalid TS: name contains '-')     static dropLast-nggk6HY(paramarg0: number[], paramarg1: number): UShort[];
// (invalid TS: name contains '-')     static dropLast-qFRl0hI(paramarg0: number[], paramarg1: number): UInt[];
// (invalid TS: name contains '-')     static dropLast-r7IrZao(paramarg0: number[], paramarg1: number): ULong[];
// (invalid TS: name contains '-')     static fill-2fe2U9s(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
// (invalid TS: name contains '-')     static fill-EtDCXyQ(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
// (invalid TS: name contains '-')     static fill-K6DWlUc(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
// (invalid TS: name contains '-')     static fill-WpHrYlw(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
// (invalid TS: name contains '-')     static firstOrNull--ajY-9A(paramarg0: number[]): UInt;
// (invalid TS: name contains '-')     static firstOrNull-GBYM_sE(paramarg0: number[]): UByte;
// (invalid TS: name contains '-')     static firstOrNull-QwZRm1k(paramarg0: number[]): ULong;
// (invalid TS: name contains '-')     static firstOrNull-rL5Bavg(paramarg0: number[]): UShort;
// (invalid TS: name contains '-')     static getIndices--ajY-9A(paramarg0: number[]): { start: number; endInclusive: number; step: number };
// (invalid TS: name contains '-')     static getIndices-GBYM_sE(paramarg0: number[]): { start: number; endInclusive: number; step: number };
// (invalid TS: name contains '-')     static getIndices-QwZRm1k(paramarg0: number[]): { start: number; endInclusive: number; step: number };
// (invalid TS: name contains '-')     static getIndices-rL5Bavg(paramarg0: number[]): { start: number; endInclusive: number; step: number };
// (invalid TS: name contains '-')     static getLastIndex--ajY-9A(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static getLastIndex-GBYM_sE(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static getLastIndex-QwZRm1k(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static getLastIndex-rL5Bavg(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static getOrNull-PpDY95g(paramarg0: number[], paramarg1: number): UByte;
// (invalid TS: name contains '-')     static getOrNull-nggk6HY(paramarg0: number[], paramarg1: number): UShort;
// (invalid TS: name contains '-')     static getOrNull-qFRl0hI(paramarg0: number[], paramarg1: number): UInt;
// (invalid TS: name contains '-')     static getOrNull-r7IrZao(paramarg0: number[], paramarg1: number): ULong;
// (invalid TS: name contains '-')     static lastOrNull--ajY-9A(paramarg0: number[]): UInt;
// (invalid TS: name contains '-')     static lastOrNull-GBYM_sE(paramarg0: number[]): UByte;
// (invalid TS: name contains '-')     static lastOrNull-QwZRm1k(paramarg0: number[]): ULong;
// (invalid TS: name contains '-')     static lastOrNull-rL5Bavg(paramarg0: number[]): UShort;
// (invalid TS: name contains '-')     static max--ajY-9A(paramarg0: number[]): UInt;
// (invalid TS: name contains '-')     static max-GBYM_sE(paramarg0: number[]): UByte;
// (invalid TS: name contains '-')     static max-QwZRm1k(paramarg0: number[]): ULong;
// (invalid TS: name contains '-')     static max-rL5Bavg(paramarg0: number[]): UShort;
// (invalid TS: name contains '-')     static maxOrNull--ajY-9A(paramarg0: number[]): UInt;
// (invalid TS: name contains '-')     static maxOrNull-GBYM_sE(paramarg0: number[]): UByte;
// (invalid TS: name contains '-')     static maxOrNull-QwZRm1k(paramarg0: number[]): ULong;
// (invalid TS: name contains '-')     static maxOrNull-rL5Bavg(paramarg0: number[]): UShort;
// (invalid TS: name contains '-')     static maxOrThrow-U(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static maxOrThrow-U(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static maxOrThrow-U(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static maxOrThrow-U(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static maxWith-XMRcp5o(paramarg0: number[], paramarg1: (param0: Object) => boolean): UByte;
// (invalid TS: name contains '-')     static maxWith-YmdZ_VM(paramarg0: number[], paramarg1: (param0: Object) => boolean): UInt;
// (invalid TS: name contains '-')     static maxWith-eOHTfZs(paramarg0: number[], paramarg1: (param0: Object) => boolean): UShort;
// (invalid TS: name contains '-')     static maxWith-zrEWJaI(paramarg0: number[], paramarg1: (param0: Object) => boolean): ULong;
// (invalid TS: name contains '-')     static maxWithOrNull-XMRcp5o(paramarg0: number[], paramarg1: (param0: Object) => boolean): UByte;
// (invalid TS: name contains '-')     static maxWithOrNull-YmdZ_VM(paramarg0: number[], paramarg1: (param0: Object) => boolean): UInt;
// (invalid TS: name contains '-')     static maxWithOrNull-eOHTfZs(paramarg0: number[], paramarg1: (param0: Object) => boolean): UShort;
// (invalid TS: name contains '-')     static maxWithOrNull-zrEWJaI(paramarg0: number[], paramarg1: (param0: Object) => boolean): ULong;
// (invalid TS: name contains '-')     static maxWithOrThrow-U(paramarg0: number[], paramarg1: (param0: Object) => boolean): number;
// (invalid TS: name contains '-')     static maxWithOrThrow-U(paramarg0: number[], paramarg1: (param0: Object) => boolean): number;
// (invalid TS: name contains '-')     static maxWithOrThrow-U(paramarg0: number[], paramarg1: (param0: Object) => boolean): number;
// (invalid TS: name contains '-')     static maxWithOrThrow-U(paramarg0: number[], paramarg1: (param0: Object) => boolean): number;
// (invalid TS: name contains '-')     static min--ajY-9A(paramarg0: number[]): UInt;
// (invalid TS: name contains '-')     static min-GBYM_sE(paramarg0: number[]): UByte;
// (invalid TS: name contains '-')     static min-QwZRm1k(paramarg0: number[]): ULong;
// (invalid TS: name contains '-')     static min-rL5Bavg(paramarg0: number[]): UShort;
// (invalid TS: name contains '-')     static minOrNull--ajY-9A(paramarg0: number[]): UInt;
// (invalid TS: name contains '-')     static minOrNull-GBYM_sE(paramarg0: number[]): UByte;
// (invalid TS: name contains '-')     static minOrNull-QwZRm1k(paramarg0: number[]): ULong;
// (invalid TS: name contains '-')     static minOrNull-rL5Bavg(paramarg0: number[]): UShort;
// (invalid TS: name contains '-')     static minOrThrow-U(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static minOrThrow-U(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static minOrThrow-U(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static minOrThrow-U(paramarg0: number[]): number;
// (invalid TS: name contains '-')     static minWith-XMRcp5o(paramarg0: number[], paramarg1: (param0: Object) => boolean): UByte;
// (invalid TS: name contains '-')     static minWith-YmdZ_VM(paramarg0: number[], paramarg1: (param0: Object) => boolean): UInt;
// (invalid TS: name contains '-')     static minWith-eOHTfZs(paramarg0: number[], paramarg1: (param0: Object) => boolean): UShort;
// (invalid TS: name contains '-')     static minWith-zrEWJaI(paramarg0: number[], paramarg1: (param0: Object) => boolean): ULong;
// (invalid TS: name contains '-')     static minWithOrNull-XMRcp5o(paramarg0: number[], paramarg1: (param0: Object) => boolean): UByte;
// (invalid TS: name contains '-')     static minWithOrNull-YmdZ_VM(paramarg0: number[], paramarg1: (param0: Object) => boolean): UInt;
// (invalid TS: name contains '-')     static minWithOrNull-eOHTfZs(paramarg0: number[], paramarg1: (param0: Object) => boolean): UShort;
// (invalid TS: name contains '-')     static minWithOrNull-zrEWJaI(paramarg0: number[], paramarg1: (param0: Object) => boolean): ULong;
// (invalid TS: name contains '-')     static minWithOrThrow-U(paramarg0: number[], paramarg1: (param0: Object) => boolean): number;
// (invalid TS: name contains '-')     static minWithOrThrow-U(paramarg0: number[], paramarg1: (param0: Object) => boolean): number;
// (invalid TS: name contains '-')     static minWithOrThrow-U(paramarg0: number[], paramarg1: (param0: Object) => boolean): number;
// (invalid TS: name contains '-')     static minWithOrThrow-U(paramarg0: number[], paramarg1: (param0: Object) => boolean): number;
// (invalid TS: name contains '-')     static plus-CFIt9YE(paramarg0: number[], paramarg1: UInt[]): number[];
// (invalid TS: name contains '-')     static plus-kzHmqpY(paramarg0: number[], paramarg1: ULong[]): number[];
// (invalid TS: name contains '-')     static plus-ojwP5H8(paramarg0: number[], paramarg1: UShort[]): number[];
// (invalid TS: name contains '-')     static plus-xo_DsdI(paramarg0: number[], paramarg1: UByte[]): number[];
// (invalid TS: name contains '-')     static random-2D5oskM(paramarg0: number[], paramarg1: Random): number;
// (invalid TS: name contains '-')     static random-JzugnMA(paramarg0: number[], paramarg1: Random): number;
// (invalid TS: name contains '-')     static random-oSF2wD8(paramarg0: number[], paramarg1: Random): number;
// (invalid TS: name contains '-')     static random-s5X_as8(paramarg0: number[], paramarg1: Random): number;
// (invalid TS: name contains '-')     static randomOrNull-2D5oskM(paramarg0: number[], paramarg1: Random): UInt;
// (invalid TS: name contains '-')     static randomOrNull-JzugnMA(paramarg0: number[], paramarg1: Random): ULong;
// (invalid TS: name contains '-')     static randomOrNull-oSF2wD8(paramarg0: number[], paramarg1: Random): UByte;
// (invalid TS: name contains '-')     static randomOrNull-s5X_as8(paramarg0: number[], paramarg1: Random): UShort;
// (invalid TS: name contains '-')     static reversed--ajY-9A(paramarg0: number[]): UInt[];
// (invalid TS: name contains '-')     static reversed-GBYM_sE(paramarg0: number[]): UByte[];
// (invalid TS: name contains '-')     static reversed-QwZRm1k(paramarg0: number[]): ULong[];
// (invalid TS: name contains '-')     static reversed-rL5Bavg(paramarg0: number[]): UShort[];
// (invalid TS: name contains '-')     static shuffle--ajY-9A(paramarg0: number[]): void;
// (invalid TS: name contains '-')     static shuffle-2D5oskM(paramarg0: number[], paramarg1: Random): void;
// (invalid TS: name contains '-')     static shuffle-GBYM_sE(paramarg0: number[]): void;
// (invalid TS: name contains '-')     static shuffle-JzugnMA(paramarg0: number[], paramarg1: Random): void;
// (invalid TS: name contains '-')     static shuffle-QwZRm1k(paramarg0: number[]): void;
// (invalid TS: name contains '-')     static shuffle-oSF2wD8(paramarg0: number[], paramarg1: Random): void;
// (invalid TS: name contains '-')     static shuffle-rL5Bavg(paramarg0: number[]): void;
// (invalid TS: name contains '-')     static shuffle-s5X_as8(paramarg0: number[], paramarg1: Random): void;
// (invalid TS: name contains '-')     static singleOrNull--ajY-9A(paramarg0: number[]): UInt;
// (invalid TS: name contains '-')     static singleOrNull-GBYM_sE(paramarg0: number[]): UByte;
// (invalid TS: name contains '-')     static singleOrNull-QwZRm1k(paramarg0: number[]): ULong;
// (invalid TS: name contains '-')     static singleOrNull-rL5Bavg(paramarg0: number[]): UShort;
// (invalid TS: name contains '-')     static slice-F7u83W8(paramarg0: number[], paramarg1: number[]): ULong[];
// (invalid TS: name contains '-')     static slice-HwE9HBo(paramarg0: number[], paramarg1: number[]): UInt[];
// (invalid TS: name contains '-')     static slice-JGPC0-M(paramarg0: number[], paramarg1: number[]): UShort[];
// (invalid TS: name contains '-')     static slice-JQknh5Q(paramarg0: number[], paramarg1: number[]): UByte[];
// (invalid TS: name contains '-')     static slice-Q6IL4kU(paramarg0: number[], paramarg1: { start: number; endInclusive: number; step: number }): UShort[];
// (invalid TS: name contains '-')     static slice-ZRhS8yI(paramarg0: number[], paramarg1: { start: number; endInclusive: number; step: number }): ULong[];
// (invalid TS: name contains '-')     static slice-c0bezYM(paramarg0: number[], paramarg1: { start: number; endInclusive: number; step: number }): UByte[];
// (invalid TS: name contains '-')     static slice-tAntMlw(paramarg0: number[], paramarg1: { start: number; endInclusive: number; step: number }): UInt[];
// (invalid TS: name contains '-')     static sliceArray-CFIt9YE(paramarg0: number[], paramarg1: number[]): number[];
// (invalid TS: name contains '-')     static sliceArray-Q6IL4kU(paramarg0: number[], paramarg1: { start: number; endInclusive: number; step: number }): number[];
// (invalid TS: name contains '-')     static sliceArray-ZRhS8yI(paramarg0: number[], paramarg1: { start: number; endInclusive: number; step: number }): number[];
// (invalid TS: name contains '-')     static sliceArray-c0bezYM(paramarg0: number[], paramarg1: { start: number; endInclusive: number; step: number }): number[];
// (invalid TS: name contains '-')     static sliceArray-kzHmqpY(paramarg0: number[], paramarg1: number[]): number[];
// (invalid TS: name contains '-')     static sliceArray-ojwP5H8(paramarg0: number[], paramarg1: number[]): number[];
// (invalid TS: name contains '-')     static sliceArray-tAntMlw(paramarg0: number[], paramarg1: { start: number; endInclusive: number; step: number }): number[];
// (invalid TS: name contains '-')     static sliceArray-xo_DsdI(paramarg0: number[], paramarg1: number[]): number[];
// (invalid TS: name contains '-')     static sort--ajY-9A(paramarg0: number[]): void;
// (invalid TS: name contains '-')     static sort--nroSd4(paramarg0: number[], paramarg1: number, paramarg2: number): void;
// (invalid TS: name contains '-')     static sort-4UcCI2c(paramarg0: number[], paramarg1: number, paramarg2: number): void;
// (invalid TS: name contains '-')     static sort-Aa5vz7o(paramarg0: number[], paramarg1: number, paramarg2: number): void;
// (invalid TS: name contains '-')     static sort-GBYM_sE(paramarg0: number[]): void;
// (invalid TS: name contains '-')     static sort-QwZRm1k(paramarg0: number[]): void;
// (invalid TS: name contains '-')     static sort-oBK06Vg(paramarg0: number[], paramarg1: number, paramarg2: number): void;
// (invalid TS: name contains '-')     static sort-rL5Bavg(paramarg0: number[]): void;
// (invalid TS: name contains '-')     static sortDescending--ajY-9A(paramarg0: number[]): void;
// (invalid TS: name contains '-')     static sortDescending--nroSd4(paramarg0: number[], paramarg1: number, paramarg2: number): void;
// (invalid TS: name contains '-')     static sortDescending-4UcCI2c(paramarg0: number[], paramarg1: number, paramarg2: number): void;
// (invalid TS: name contains '-')     static sortDescending-Aa5vz7o(paramarg0: number[], paramarg1: number, paramarg2: number): void;
// (invalid TS: name contains '-')     static sortDescending-GBYM_sE(paramarg0: number[]): void;
// (invalid TS: name contains '-')     static sortDescending-QwZRm1k(paramarg0: number[]): void;
// (invalid TS: name contains '-')     static sortDescending-oBK06Vg(paramarg0: number[], paramarg1: number, paramarg2: number): void;
// (invalid TS: name contains '-')     static sortDescending-rL5Bavg(paramarg0: number[]): void;
// (invalid TS: name contains '-')     static sorted--ajY-9A(paramarg0: number[]): UInt[];
// (invalid TS: name contains '-')     static sorted-GBYM_sE(paramarg0: number[]): UByte[];
// (invalid TS: name contains '-')     static sorted-QwZRm1k(paramarg0: number[]): ULong[];
// (invalid TS: name contains '-')     static sorted-rL5Bavg(paramarg0: number[]): UShort[];
// (invalid TS: name contains '-')     static sortedArray--ajY-9A(paramarg0: number[]): number[];
// (invalid TS: name contains '-')     static sortedArray-GBYM_sE(paramarg0: number[]): number[];
// (invalid TS: name contains '-')     static sortedArray-QwZRm1k(paramarg0: number[]): number[];
// (invalid TS: name contains '-')     static sortedArray-rL5Bavg(paramarg0: number[]): number[];
// (invalid TS: name contains '-')     static sortedArrayDescending--ajY-9A(paramarg0: number[]): number[];
// (invalid TS: name contains '-')     static sortedArrayDescending-GBYM_sE(paramarg0: number[]): number[];
// (invalid TS: name contains '-')     static sortedArrayDescending-QwZRm1k(paramarg0: number[]): number[];
// (invalid TS: name contains '-')     static sortedArrayDescending-rL5Bavg(paramarg0: number[]): number[];
// (invalid TS: name contains '-')     static sortedDescending--ajY-9A(paramarg0: number[]): UInt[];
// (invalid TS: name contains '-')     static sortedDescending-GBYM_sE(paramarg0: number[]): UByte[];
// (invalid TS: name contains '-')     static sortedDescending-QwZRm1k(paramarg0: number[]): ULong[];
// (invalid TS: name contains '-')     static sortedDescending-rL5Bavg(paramarg0: number[]): UShort[];
    static sumOfUByte(paramarg0: (Object | null)[]): number;
    static sumOfUInt(paramarg0: (Object | null)[]): number;
    static sumOfULong(paramarg0: (Object | null)[]): number;
    static sumOfUShort(paramarg0: (Object | null)[]): number;
// (invalid TS: name contains '-')     static take-PpDY95g(paramarg0: number[], paramarg1: number): UByte[];
// (invalid TS: name contains '-')     static take-nggk6HY(paramarg0: number[], paramarg1: number): UShort[];
// (invalid TS: name contains '-')     static take-qFRl0hI(paramarg0: number[], paramarg1: number): UInt[];
// (invalid TS: name contains '-')     static take-r7IrZao(paramarg0: number[], paramarg1: number): ULong[];
// (invalid TS: name contains '-')     static takeLast-PpDY95g(paramarg0: number[], paramarg1: number): UByte[];
// (invalid TS: name contains '-')     static takeLast-nggk6HY(paramarg0: number[], paramarg1: number): UShort[];
// (invalid TS: name contains '-')     static takeLast-qFRl0hI(paramarg0: number[], paramarg1: number): UInt[];
// (invalid TS: name contains '-')     static takeLast-r7IrZao(paramarg0: number[], paramarg1: number): ULong[];
// (invalid TS: name contains '-')     static toTypedArray--ajY-9A(paramarg0: number[]): (Object | null)[];
// (invalid TS: name contains '-')     static toTypedArray-GBYM_sE(paramarg0: number[]): (Object | null)[];
// (invalid TS: name contains '-')     static toTypedArray-QwZRm1k(paramarg0: number[]): (Object | null)[];
// (invalid TS: name contains '-')     static toTypedArray-rL5Bavg(paramarg0: number[]): (Object | null)[];
    static toUByteArray(paramarg0: (Object | null)[]): number[];
    static toUIntArray(paramarg0: (Object | null)[]): number[];
    static toULongArray(paramarg0: (Object | null)[]): number[];
    static toUShortArray(paramarg0: (Object | null)[]): number[];
// (invalid TS: name contains '-')     static withIndex--ajY-9A(paramarg0: number[]): IndexedValue<UInt>[];
// (invalid TS: name contains '-')     static withIndex-GBYM_sE(paramarg0: number[]): IndexedValue<UByte>[];
// (invalid TS: name contains '-')     static withIndex-QwZRm1k(paramarg0: number[]): IndexedValue<ULong>[];
// (invalid TS: name contains '-')     static withIndex-rL5Bavg(paramarg0: number[]): IndexedValue<UShort>[];
// (invalid TS: name contains '-')     static zip-C-E_24M(paramarg0: number[], paramarg1: Object | null): Pair<UInt, Object>[];
// (invalid TS: name contains '-')     static zip-F7u83W8(paramarg0: number[], paramarg1: (Object | null)[]): Pair<ULong, Object>[];
// (invalid TS: name contains '-')     static zip-HwE9HBo(paramarg0: number[], paramarg1: (Object | null)[]): Pair<UInt, Object>[];
// (invalid TS: name contains '-')     static zip-JGPC0-M(paramarg0: number[], paramarg1: (Object | null)[]): Pair<UShort, Object>[];
// (invalid TS: name contains '-')     static zip-JQknh5Q(paramarg0: number[], paramarg1: (Object | null)[]): Pair<UByte, Object>[];
// (invalid TS: name contains '-')     static zip-ctEhBpI(paramarg0: number[], paramarg1: number[]): Pair<UInt, UInt>[];
// (invalid TS: name contains '-')     static zip-f7H3mmw(paramarg0: number[], paramarg1: Object | null): Pair<ULong, Object>[];
// (invalid TS: name contains '-')     static zip-kdPth3s(paramarg0: number[], paramarg1: number[]): Pair<UByte, UByte>[];
// (invalid TS: name contains '-')     static zip-mazbYpA(paramarg0: number[], paramarg1: number[]): Pair<UShort, UShort>[];
// (invalid TS: name contains '-')     static zip-nl983wc(paramarg0: number[], paramarg1: Object | null): Pair<UByte, Object>[];
// (invalid TS: name contains '-')     static zip-uaTIQ5s(paramarg0: number[], paramarg1: Object | null): Pair<UShort, Object>[];
// (invalid TS: name contains '-')     static zip-us8wMrg(paramarg0: number[], paramarg1: number[]): Pair<ULong, ULong>[];
}