import type { FloatBuffer } from '../../../java/nio/FloatBuffer.d.ts'
import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
export class EXTEfx extends Object {
    static ALC_EFX_MAJOR_VERSION: number;
    static ALC_EFX_MINOR_VERSION: number;
    static ALC_MAX_AUXILIARY_SENDS: number;
    static AL_AIR_ABSORPTION_FACTOR: number;
    static AL_AUTOWAH_ATTACK_TIME: number;
    static AL_AUTOWAH_DEFAULT_ATTACK_TIME: number;
    static AL_AUTOWAH_DEFAULT_PEAK_GAIN: number;
    static AL_AUTOWAH_DEFAULT_RELEASE_TIME: number;
    static AL_AUTOWAH_DEFAULT_RESONANCE: number;
    static AL_AUTOWAH_MAX_ATTACK_TIME: number;
    static AL_AUTOWAH_MAX_PEAK_GAIN: number;
    static AL_AUTOWAH_MAX_RELEASE_TIME: number;
    static AL_AUTOWAH_MAX_RESONANCE: number;
    static AL_AUTOWAH_MIN_ATTACK_TIME: number;
    static AL_AUTOWAH_MIN_PEAK_GAIN: number;
    static AL_AUTOWAH_MIN_RELEASE_TIME: number;
    static AL_AUTOWAH_MIN_RESONANCE: number;
    static AL_AUTOWAH_PEAK_GAIN: number;
    static AL_AUTOWAH_RELEASE_TIME: number;
    static AL_AUTOWAH_RESONANCE: number;
    static AL_AUXILIARY_SEND_FILTER: number;
    static AL_AUXILIARY_SEND_FILTER_GAINHF_AUTO: number;
    static AL_AUXILIARY_SEND_FILTER_GAIN_AUTO: number;
    static AL_BANDPASS_DEFAULT_GAIN: number;
    static AL_BANDPASS_DEFAULT_GAINHF: number;
    static AL_BANDPASS_DEFAULT_GAINLF: number;
    static AL_BANDPASS_GAIN: number;
    static AL_BANDPASS_GAINHF: number;
    static AL_BANDPASS_GAINLF: number;
    static AL_BANDPASS_MAX_GAIN: number;
    static AL_BANDPASS_MAX_GAINHF: number;
    static AL_BANDPASS_MAX_GAINLF: number;
    static AL_BANDPASS_MIN_GAIN: number;
    static AL_BANDPASS_MIN_GAINHF: number;
    static AL_BANDPASS_MIN_GAINLF: number;
    static AL_CHORUS_DEFAULT_DELAY: number;
    static AL_CHORUS_DEFAULT_DEPTH: number;
    static AL_CHORUS_DEFAULT_FEEDBACK: number;
    static AL_CHORUS_DEFAULT_PHASE: number;
    static AL_CHORUS_DEFAULT_RATE: number;
    static AL_CHORUS_DEFAULT_WAVEFORM: number;
    static AL_CHORUS_DELAY: number;
    static AL_CHORUS_DEPTH: number;
    static AL_CHORUS_FEEDBACK: number;
    static AL_CHORUS_MAX_DELAY: number;
    static AL_CHORUS_MAX_DEPTH: number;
    static AL_CHORUS_MAX_FEEDBACK: number;
    static AL_CHORUS_MAX_PHASE: number;
    static AL_CHORUS_MAX_RATE: number;
    static AL_CHORUS_MAX_WAVEFORM: number;
    static AL_CHORUS_MIN_DELAY: number;
    static AL_CHORUS_MIN_DEPTH: number;
    static AL_CHORUS_MIN_FEEDBACK: number;
    static AL_CHORUS_MIN_PHASE: number;
    static AL_CHORUS_MIN_RATE: number;
    static AL_CHORUS_MIN_WAVEFORM: number;
    static AL_CHORUS_PHASE: number;
    static AL_CHORUS_RATE: number;
    static AL_CHORUS_WAVEFORM: number;
    static AL_CHORUS_WAVEFORM_SINUSOID: number;
    static AL_CHORUS_WAVEFORM_TRIANGLE: number;
    static AL_COMPRESSOR_DEFAULT_ONOFF: number;
    static AL_COMPRESSOR_MAX_ONOFF: number;
    static AL_COMPRESSOR_MIN_ONOFF: number;
    static AL_COMPRESSOR_ONOFF: number;
    static AL_CONE_OUTER_GAINHF: number;
    static AL_DEFAULT_AIR_ABSORPTION_FACTOR: number;
    static AL_DEFAULT_AUXILIARY_SEND_FILTER_GAINHF_AUTO: number;
    static AL_DEFAULT_AUXILIARY_SEND_FILTER_GAIN_AUTO: number;
    static AL_DEFAULT_CONE_OUTER_GAINHF: number;
    static AL_DEFAULT_DIRECT_FILTER_GAINHF_AUTO: number;
    static AL_DEFAULT_METERS_PER_UNIT: number;
    static AL_DEFAULT_ROOM_ROLLOFF_FACTOR: number;
    static AL_DIRECT_FILTER: number;
    static AL_DIRECT_FILTER_GAINHF_AUTO: number;
    static AL_DISTORTION_DEFAULT_EDGE: number;
    static AL_DISTORTION_DEFAULT_EQBANDWIDTH: number;
    static AL_DISTORTION_DEFAULT_EQCENTER: number;
    static AL_DISTORTION_DEFAULT_GAIN: number;
    static AL_DISTORTION_DEFAULT_LOWPASS_CUTOFF: number;
    static AL_DISTORTION_EDGE: number;
    static AL_DISTORTION_EQBANDWIDTH: number;
    static AL_DISTORTION_EQCENTER: number;
    static AL_DISTORTION_GAIN: number;
    static AL_DISTORTION_LOWPASS_CUTOFF: number;
    static AL_DISTORTION_MAX_EDGE: number;
    static AL_DISTORTION_MAX_EQBANDWIDTH: number;
    static AL_DISTORTION_MAX_EQCENTER: number;
    static AL_DISTORTION_MAX_GAIN: number;
    static AL_DISTORTION_MAX_LOWPASS_CUTOFF: number;
    static AL_DISTORTION_MIN_EDGE: number;
    static AL_DISTORTION_MIN_EQBANDWIDTH: number;
    static AL_DISTORTION_MIN_EQCENTER: number;
    static AL_DISTORTION_MIN_GAIN: number;
    static AL_DISTORTION_MIN_LOWPASS_CUTOFF: number;
    static AL_EAXREVERB_AIR_ABSORPTION_GAINHF: number;
    static AL_EAXREVERB_DECAY_HFLIMIT: number;
    static AL_EAXREVERB_DECAY_HFRATIO: number;
    static AL_EAXREVERB_DECAY_LFRATIO: number;
    static AL_EAXREVERB_DECAY_TIME: number;
    static AL_EAXREVERB_DEFAULT_AIR_ABSORPTION_GAINHF: number;
    static AL_EAXREVERB_DEFAULT_DECAY_HFLIMIT: number;
    static AL_EAXREVERB_DEFAULT_DECAY_HFRATIO: number;
    static AL_EAXREVERB_DEFAULT_DECAY_LFRATIO: number;
    static AL_EAXREVERB_DEFAULT_DECAY_TIME: number;
    static AL_EAXREVERB_DEFAULT_DENSITY: number;
    static AL_EAXREVERB_DEFAULT_DIFFUSION: number;
    static AL_EAXREVERB_DEFAULT_ECHO_DEPTH: number;
    static AL_EAXREVERB_DEFAULT_ECHO_TIME: number;
    static AL_EAXREVERB_DEFAULT_GAIN: number;
    static AL_EAXREVERB_DEFAULT_GAINHF: number;
    static AL_EAXREVERB_DEFAULT_GAINLF: number;
    static AL_EAXREVERB_DEFAULT_HFREFERENCE: number;
    static AL_EAXREVERB_DEFAULT_LATE_REVERB_DELAY: number;
    static AL_EAXREVERB_DEFAULT_LATE_REVERB_GAIN: number;
    static AL_EAXREVERB_DEFAULT_LATE_REVERB_PAN_XYZ: number;
    static AL_EAXREVERB_DEFAULT_LFREFERENCE: number;
    static AL_EAXREVERB_DEFAULT_MODULATION_DEPTH: number;
    static AL_EAXREVERB_DEFAULT_MODULATION_TIME: number;
    static AL_EAXREVERB_DEFAULT_REFLECTIONS_DELAY: number;
    static AL_EAXREVERB_DEFAULT_REFLECTIONS_GAIN: number;
    static AL_EAXREVERB_DEFAULT_REFLECTIONS_PAN_XYZ: number;
    static AL_EAXREVERB_DEFAULT_ROOM_ROLLOFF_FACTOR: number;
    static AL_EAXREVERB_DENSITY: number;
    static AL_EAXREVERB_DIFFUSION: number;
    static AL_EAXREVERB_ECHO_DEPTH: number;
    static AL_EAXREVERB_ECHO_TIME: number;
    static AL_EAXREVERB_GAIN: number;
    static AL_EAXREVERB_GAINHF: number;
    static AL_EAXREVERB_GAINLF: number;
    static AL_EAXREVERB_HFREFERENCE: number;
    static AL_EAXREVERB_LATE_REVERB_DELAY: number;
    static AL_EAXREVERB_LATE_REVERB_GAIN: number;
    static AL_EAXREVERB_LATE_REVERB_PAN: number;
    static AL_EAXREVERB_LFREFERENCE: number;
    static AL_EAXREVERB_MAX_AIR_ABSORPTION_GAINHF: number;
    static AL_EAXREVERB_MAX_DECAY_HFLIMIT: number;
    static AL_EAXREVERB_MAX_DECAY_HFRATIO: number;
    static AL_EAXREVERB_MAX_DECAY_LFRATIO: number;
    static AL_EAXREVERB_MAX_DECAY_TIME: number;
    static AL_EAXREVERB_MAX_DENSITY: number;
    static AL_EAXREVERB_MAX_DIFFUSION: number;
    static AL_EAXREVERB_MAX_ECHO_DEPTH: number;
    static AL_EAXREVERB_MAX_ECHO_TIME: number;
    static AL_EAXREVERB_MAX_GAIN: number;
    static AL_EAXREVERB_MAX_GAINHF: number;
    static AL_EAXREVERB_MAX_GAINLF: number;
    static AL_EAXREVERB_MAX_HFREFERENCE: number;
    static AL_EAXREVERB_MAX_LATE_REVERB_DELAY: number;
    static AL_EAXREVERB_MAX_LATE_REVERB_GAIN: number;
    static AL_EAXREVERB_MAX_LFREFERENCE: number;
    static AL_EAXREVERB_MAX_MODULATION_DEPTH: number;
    static AL_EAXREVERB_MAX_MODULATION_TIME: number;
    static AL_EAXREVERB_MAX_REFLECTIONS_DELAY: number;
    static AL_EAXREVERB_MAX_REFLECTIONS_GAIN: number;
    static AL_EAXREVERB_MAX_ROOM_ROLLOFF_FACTOR: number;
    static AL_EAXREVERB_MIN_AIR_ABSORPTION_GAINHF: number;
    static AL_EAXREVERB_MIN_DECAY_HFLIMIT: number;
    static AL_EAXREVERB_MIN_DECAY_HFRATIO: number;
    static AL_EAXREVERB_MIN_DECAY_LFRATIO: number;
    static AL_EAXREVERB_MIN_DECAY_TIME: number;
    static AL_EAXREVERB_MIN_DENSITY: number;
    static AL_EAXREVERB_MIN_DIFFUSION: number;
    static AL_EAXREVERB_MIN_ECHO_DEPTH: number;
    static AL_EAXREVERB_MIN_ECHO_TIME: number;
    static AL_EAXREVERB_MIN_GAIN: number;
    static AL_EAXREVERB_MIN_GAINHF: number;
    static AL_EAXREVERB_MIN_GAINLF: number;
    static AL_EAXREVERB_MIN_HFREFERENCE: number;
    static AL_EAXREVERB_MIN_LATE_REVERB_DELAY: number;
    static AL_EAXREVERB_MIN_LATE_REVERB_GAIN: number;
    static AL_EAXREVERB_MIN_LFREFERENCE: number;
    static AL_EAXREVERB_MIN_MODULATION_DEPTH: number;
    static AL_EAXREVERB_MIN_MODULATION_TIME: number;
    static AL_EAXREVERB_MIN_REFLECTIONS_DELAY: number;
    static AL_EAXREVERB_MIN_REFLECTIONS_GAIN: number;
    static AL_EAXREVERB_MIN_ROOM_ROLLOFF_FACTOR: number;
    static AL_EAXREVERB_MODULATION_DEPTH: number;
    static AL_EAXREVERB_MODULATION_TIME: number;
    static AL_EAXREVERB_REFLECTIONS_DELAY: number;
    static AL_EAXREVERB_REFLECTIONS_GAIN: number;
    static AL_EAXREVERB_REFLECTIONS_PAN: number;
    static AL_EAXREVERB_ROOM_ROLLOFF_FACTOR: number;
    static AL_ECHO_DAMPING: number;
    static AL_ECHO_DEFAULT_DAMPING: number;
    static AL_ECHO_DEFAULT_DELAY: number;
    static AL_ECHO_DEFAULT_FEEDBACK: number;
    static AL_ECHO_DEFAULT_LRDELAY: number;
    static AL_ECHO_DEFAULT_SPREAD: number;
    static AL_ECHO_DELAY: number;
    static AL_ECHO_FEEDBACK: number;
    static AL_ECHO_LRDELAY: number;
    static AL_ECHO_MAX_DAMPING: number;
    static AL_ECHO_MAX_DELAY: number;
    static AL_ECHO_MAX_FEEDBACK: number;
    static AL_ECHO_MAX_LRDELAY: number;
    static AL_ECHO_MAX_SPREAD: number;
    static AL_ECHO_MIN_DAMPING: number;
    static AL_ECHO_MIN_DELAY: number;
    static AL_ECHO_MIN_FEEDBACK: number;
    static AL_ECHO_MIN_LRDELAY: number;
    static AL_ECHO_MIN_SPREAD: number;
    static AL_ECHO_SPREAD: number;
    static AL_EFFECTSLOT_AUXILIARY_SEND_AUTO: number;
    static AL_EFFECTSLOT_EFFECT: number;
    static AL_EFFECTSLOT_GAIN: number;
    static AL_EFFECTSLOT_NULL: number;
    static AL_EFFECT_AUTOWAH: number;
    static AL_EFFECT_CHORUS: number;
    static AL_EFFECT_COMPRESSOR: number;
    static AL_EFFECT_DISTORTION: number;
    static AL_EFFECT_EAXREVERB: number;
    static AL_EFFECT_ECHO: number;
    static AL_EFFECT_EQUALIZER: number;
    static AL_EFFECT_FIRST_PARAMETER: number;
    static AL_EFFECT_FLANGER: number;
    static AL_EFFECT_FREQUENCY_SHIFTER: number;
    static AL_EFFECT_LAST_PARAMETER: number;
    static AL_EFFECT_NULL: number;
    static AL_EFFECT_PITCH_SHIFTER: number;
    static AL_EFFECT_REVERB: number;
    static AL_EFFECT_RING_MODULATOR: number;
    static AL_EFFECT_TYPE: number;
    static AL_EFFECT_VOCAL_MORPHER: number;
    static AL_EQUALIZER_DEFAULT_HIGH_CUTOFF: number;
    static AL_EQUALIZER_DEFAULT_HIGH_GAIN: number;
    static AL_EQUALIZER_DEFAULT_LOW_CUTOFF: number;
    static AL_EQUALIZER_DEFAULT_LOW_GAIN: number;
    static AL_EQUALIZER_DEFAULT_MID1_CENTER: number;
    static AL_EQUALIZER_DEFAULT_MID1_GAIN: number;
    static AL_EQUALIZER_DEFAULT_MID1_WIDTH: number;
    static AL_EQUALIZER_DEFAULT_MID2_CENTER: number;
    static AL_EQUALIZER_DEFAULT_MID2_GAIN: number;
    static AL_EQUALIZER_DEFAULT_MID2_WIDTH: number;
    static AL_EQUALIZER_HIGH_CUTOFF: number;
    static AL_EQUALIZER_HIGH_GAIN: number;
    static AL_EQUALIZER_LOW_CUTOFF: number;
    static AL_EQUALIZER_LOW_GAIN: number;
    static AL_EQUALIZER_MAX_HIGH_CUTOFF: number;
    static AL_EQUALIZER_MAX_HIGH_GAIN: number;
    static AL_EQUALIZER_MAX_LOW_CUTOFF: number;
    static AL_EQUALIZER_MAX_LOW_GAIN: number;
    static AL_EQUALIZER_MAX_MID1_CENTER: number;
    static AL_EQUALIZER_MAX_MID1_GAIN: number;
    static AL_EQUALIZER_MAX_MID1_WIDTH: number;
    static AL_EQUALIZER_MAX_MID2_CENTER: number;
    static AL_EQUALIZER_MAX_MID2_GAIN: number;
    static AL_EQUALIZER_MAX_MID2_WIDTH: number;
    static AL_EQUALIZER_MID1_CENTER: number;
    static AL_EQUALIZER_MID1_GAIN: number;
    static AL_EQUALIZER_MID1_WIDTH: number;
    static AL_EQUALIZER_MID2_CENTER: number;
    static AL_EQUALIZER_MID2_GAIN: number;
    static AL_EQUALIZER_MID2_WIDTH: number;
    static AL_EQUALIZER_MIN_HIGH_CUTOFF: number;
    static AL_EQUALIZER_MIN_HIGH_GAIN: number;
    static AL_EQUALIZER_MIN_LOW_CUTOFF: number;
    static AL_EQUALIZER_MIN_LOW_GAIN: number;
    static AL_EQUALIZER_MIN_MID1_CENTER: number;
    static AL_EQUALIZER_MIN_MID1_GAIN: number;
    static AL_EQUALIZER_MIN_MID1_WIDTH: number;
    static AL_EQUALIZER_MIN_MID2_CENTER: number;
    static AL_EQUALIZER_MIN_MID2_GAIN: number;
    static AL_EQUALIZER_MIN_MID2_WIDTH: number;
    static AL_FILTER_BANDPASS: number;
    static AL_FILTER_FIRST_PARAMETER: number;
    static AL_FILTER_HIGHPASS: number;
    static AL_FILTER_LAST_PARAMETER: number;
    static AL_FILTER_LOWPASS: number;
    static AL_FILTER_NULL: number;
    static AL_FILTER_TYPE: number;
    static AL_FLANGER_DEFAULT_DELAY: number;
    static AL_FLANGER_DEFAULT_DEPTH: number;
    static AL_FLANGER_DEFAULT_FEEDBACK: number;
    static AL_FLANGER_DEFAULT_PHASE: number;
    static AL_FLANGER_DEFAULT_RATE: number;
    static AL_FLANGER_DEFAULT_WAVEFORM: number;
    static AL_FLANGER_DELAY: number;
    static AL_FLANGER_DEPTH: number;
    static AL_FLANGER_FEEDBACK: number;
    static AL_FLANGER_MAX_DELAY: number;
    static AL_FLANGER_MAX_DEPTH: number;
    static AL_FLANGER_MAX_FEEDBACK: number;
    static AL_FLANGER_MAX_PHASE: number;
    static AL_FLANGER_MAX_RATE: number;
    static AL_FLANGER_MAX_WAVEFORM: number;
    static AL_FLANGER_MIN_DELAY: number;
    static AL_FLANGER_MIN_DEPTH: number;
    static AL_FLANGER_MIN_FEEDBACK: number;
    static AL_FLANGER_MIN_PHASE: number;
    static AL_FLANGER_MIN_RATE: number;
    static AL_FLANGER_MIN_WAVEFORM: number;
    static AL_FLANGER_PHASE: number;
    static AL_FLANGER_RATE: number;
    static AL_FLANGER_WAVEFORM: number;
    static AL_FLANGER_WAVEFORM_SINUSOID: number;
    static AL_FLANGER_WAVEFORM_TRIANGLE: number;
    static AL_FREQUENCY_SHIFTER_DEFAULT_FREQUENCY: number;
    static AL_FREQUENCY_SHIFTER_DEFAULT_LEFT_DIRECTION: number;
    static AL_FREQUENCY_SHIFTER_DEFAULT_RIGHT_DIRECTION: number;
    static AL_FREQUENCY_SHIFTER_DIRECTION_DOWN: number;
    static AL_FREQUENCY_SHIFTER_DIRECTION_OFF: number;
    static AL_FREQUENCY_SHIFTER_DIRECTION_UP: number;
    static AL_FREQUENCY_SHIFTER_FREQUENCY: number;
    static AL_FREQUENCY_SHIFTER_LEFT_DIRECTION: number;
    static AL_FREQUENCY_SHIFTER_MAX_FREQUENCY: number;
    static AL_FREQUENCY_SHIFTER_MAX_LEFT_DIRECTION: number;
    static AL_FREQUENCY_SHIFTER_MAX_RIGHT_DIRECTION: number;
    static AL_FREQUENCY_SHIFTER_MIN_FREQUENCY: number;
    static AL_FREQUENCY_SHIFTER_MIN_LEFT_DIRECTION: number;
    static AL_FREQUENCY_SHIFTER_MIN_RIGHT_DIRECTION: number;
    static AL_FREQUENCY_SHIFTER_RIGHT_DIRECTION: number;
    static AL_HIGHPASS_DEFAULT_GAIN: number;
    static AL_HIGHPASS_DEFAULT_GAINLF: number;
    static AL_HIGHPASS_GAIN: number;
    static AL_HIGHPASS_GAINLF: number;
    static AL_HIGHPASS_MAX_GAIN: number;
    static AL_HIGHPASS_MAX_GAINLF: number;
    static AL_HIGHPASS_MIN_GAIN: number;
    static AL_HIGHPASS_MIN_GAINLF: number;
    static AL_LOWPASS_DEFAULT_GAIN: number;
    static AL_LOWPASS_DEFAULT_GAINHF: number;
    static AL_LOWPASS_GAIN: number;
    static AL_LOWPASS_GAINHF: number;
    static AL_LOWPASS_MAX_GAIN: number;
    static AL_LOWPASS_MAX_GAINHF: number;
    static AL_LOWPASS_MIN_GAIN: number;
    static AL_LOWPASS_MIN_GAINHF: number;
    static AL_MAX_AIR_ABSORPTION_FACTOR: number;
    static AL_MAX_AUXILIARY_SEND_FILTER_GAINHF_AUTO: number;
    static AL_MAX_AUXILIARY_SEND_FILTER_GAIN_AUTO: number;
    static AL_MAX_CONE_OUTER_GAINHF: number;
    static AL_MAX_DIRECT_FILTER_GAINHF_AUTO: number;
    static AL_MAX_METERS_PER_UNIT: number;
    static AL_MAX_ROOM_ROLLOFF_FACTOR: number;
    static AL_METERS_PER_UNIT: number;
    static AL_MIN_AIR_ABSORPTION_FACTOR: number;
    static AL_MIN_AUXILIARY_SEND_FILTER_GAINHF_AUTO: number;
    static AL_MIN_AUXILIARY_SEND_FILTER_GAIN_AUTO: number;
    static AL_MIN_CONE_OUTER_GAINHF: number;
    static AL_MIN_DIRECT_FILTER_GAINHF_AUTO: number;
    static AL_MIN_METERS_PER_UNIT: number;
    static AL_MIN_ROOM_ROLLOFF_FACTOR: number;
    static AL_PITCH_SHIFTER_COARSE_TUNE: number;
    static AL_PITCH_SHIFTER_DEFAULT_COARSE_TUNE: number;
    static AL_PITCH_SHIFTER_DEFAULT_FINE_TUNE: number;
    static AL_PITCH_SHIFTER_FINE_TUNE: number;
    static AL_PITCH_SHIFTER_MAX_COARSE_TUNE: number;
    static AL_PITCH_SHIFTER_MAX_FINE_TUNE: number;
    static AL_PITCH_SHIFTER_MIN_COARSE_TUNE: number;
    static AL_PITCH_SHIFTER_MIN_FINE_TUNE: number;
    static AL_REVERB_AIR_ABSORPTION_GAINHF: number;
    static AL_REVERB_DECAY_HFLIMIT: number;
    static AL_REVERB_DECAY_HFRATIO: number;
    static AL_REVERB_DECAY_TIME: number;
    static AL_REVERB_DEFAULT_AIR_ABSORPTION_GAINHF: number;
    static AL_REVERB_DEFAULT_DECAY_HFLIMIT: number;
    static AL_REVERB_DEFAULT_DECAY_HFRATIO: number;
    static AL_REVERB_DEFAULT_DECAY_TIME: number;
    static AL_REVERB_DEFAULT_DENSITY: number;
    static AL_REVERB_DEFAULT_DIFFUSION: number;
    static AL_REVERB_DEFAULT_GAIN: number;
    static AL_REVERB_DEFAULT_GAINHF: number;
    static AL_REVERB_DEFAULT_LATE_REVERB_DELAY: number;
    static AL_REVERB_DEFAULT_LATE_REVERB_GAIN: number;
    static AL_REVERB_DEFAULT_REFLECTIONS_DELAY: number;
    static AL_REVERB_DEFAULT_REFLECTIONS_GAIN: number;
    static AL_REVERB_DEFAULT_ROOM_ROLLOFF_FACTOR: number;
    static AL_REVERB_DENSITY: number;
    static AL_REVERB_DIFFUSION: number;
    static AL_REVERB_GAIN: number;
    static AL_REVERB_GAINHF: number;
    static AL_REVERB_LATE_REVERB_DELAY: number;
    static AL_REVERB_LATE_REVERB_GAIN: number;
    static AL_REVERB_MAX_AIR_ABSORPTION_GAINHF: number;
    static AL_REVERB_MAX_DECAY_HFLIMIT: number;
    static AL_REVERB_MAX_DECAY_HFRATIO: number;
    static AL_REVERB_MAX_DECAY_TIME: number;
    static AL_REVERB_MAX_DENSITY: number;
    static AL_REVERB_MAX_DIFFUSION: number;
    static AL_REVERB_MAX_GAIN: number;
    static AL_REVERB_MAX_GAINHF: number;
    static AL_REVERB_MAX_LATE_REVERB_DELAY: number;
    static AL_REVERB_MAX_LATE_REVERB_GAIN: number;
    static AL_REVERB_MAX_REFLECTIONS_DELAY: number;
    static AL_REVERB_MAX_REFLECTIONS_GAIN: number;
    static AL_REVERB_MAX_ROOM_ROLLOFF_FACTOR: number;
    static AL_REVERB_MIN_AIR_ABSORPTION_GAINHF: number;
    static AL_REVERB_MIN_DECAY_HFLIMIT: number;
    static AL_REVERB_MIN_DECAY_HFRATIO: number;
    static AL_REVERB_MIN_DECAY_TIME: number;
    static AL_REVERB_MIN_DENSITY: number;
    static AL_REVERB_MIN_DIFFUSION: number;
    static AL_REVERB_MIN_GAIN: number;
    static AL_REVERB_MIN_GAINHF: number;
    static AL_REVERB_MIN_LATE_REVERB_DELAY: number;
    static AL_REVERB_MIN_LATE_REVERB_GAIN: number;
    static AL_REVERB_MIN_REFLECTIONS_DELAY: number;
    static AL_REVERB_MIN_REFLECTIONS_GAIN: number;
    static AL_REVERB_MIN_ROOM_ROLLOFF_FACTOR: number;
    static AL_REVERB_REFLECTIONS_DELAY: number;
    static AL_REVERB_REFLECTIONS_GAIN: number;
    static AL_REVERB_ROOM_ROLLOFF_FACTOR: number;
    static AL_RING_MODULATOR_DEFAULT_FREQUENCY: number;
    static AL_RING_MODULATOR_DEFAULT_HIGHPASS_CUTOFF: number;
    static AL_RING_MODULATOR_DEFAULT_WAVEFORM: number;
    static AL_RING_MODULATOR_FREQUENCY: number;
    static AL_RING_MODULATOR_HIGHPASS_CUTOFF: number;
    static AL_RING_MODULATOR_MAX_FREQUENCY: number;
    static AL_RING_MODULATOR_MAX_HIGHPASS_CUTOFF: number;
    static AL_RING_MODULATOR_MAX_WAVEFORM: number;
    static AL_RING_MODULATOR_MIN_FREQUENCY: number;
    static AL_RING_MODULATOR_MIN_HIGHPASS_CUTOFF: number;
    static AL_RING_MODULATOR_MIN_WAVEFORM: number;
    static AL_RING_MODULATOR_SAWTOOTH: number;
    static AL_RING_MODULATOR_SINUSOID: number;
    static AL_RING_MODULATOR_SQUARE: number;
    static AL_RING_MODULATOR_WAVEFORM: number;
    static AL_ROOM_ROLLOFF_FACTOR: number;
    static AL_VOCAL_MORPHER_DEFAULT_PHONEMEA: number;
    static AL_VOCAL_MORPHER_DEFAULT_PHONEMEA_COARSE_TUNING: number;
    static AL_VOCAL_MORPHER_DEFAULT_PHONEMEB: number;
    static AL_VOCAL_MORPHER_DEFAULT_PHONEMEB_COARSE_TUNING: number;
    static AL_VOCAL_MORPHER_DEFAULT_RATE: number;
    static AL_VOCAL_MORPHER_DEFAULT_WAVEFORM: number;
    static AL_VOCAL_MORPHER_MAX_PHONEMEA: number;
    static AL_VOCAL_MORPHER_MAX_PHONEMEA_COARSE_TUNING: number;
    static AL_VOCAL_MORPHER_MAX_PHONEMEB: number;
    static AL_VOCAL_MORPHER_MAX_PHONEMEB_COARSE_TUNING: number;
    static AL_VOCAL_MORPHER_MAX_RATE: number;
    static AL_VOCAL_MORPHER_MAX_WAVEFORM: number;
    static AL_VOCAL_MORPHER_MIN_PHONEMEA: number;
    static AL_VOCAL_MORPHER_MIN_PHONEMEA_COARSE_TUNING: number;
    static AL_VOCAL_MORPHER_MIN_PHONEMEB: number;
    static AL_VOCAL_MORPHER_MIN_PHONEMEB_COARSE_TUNING: number;
    static AL_VOCAL_MORPHER_MIN_RATE: number;
    static AL_VOCAL_MORPHER_MIN_WAVEFORM: number;
    static AL_VOCAL_MORPHER_PHONEME_A: number;
    static AL_VOCAL_MORPHER_PHONEME_AA: number;
    static AL_VOCAL_MORPHER_PHONEME_AE: number;
    static AL_VOCAL_MORPHER_PHONEME_AH: number;
    static AL_VOCAL_MORPHER_PHONEME_AO: number;
    static AL_VOCAL_MORPHER_PHONEME_B: number;
    static AL_VOCAL_MORPHER_PHONEME_D: number;
    static AL_VOCAL_MORPHER_PHONEME_E: number;
    static AL_VOCAL_MORPHER_PHONEME_EH: number;
    static AL_VOCAL_MORPHER_PHONEME_ER: number;
    static AL_VOCAL_MORPHER_PHONEME_F: number;
    static AL_VOCAL_MORPHER_PHONEME_G: number;
    static AL_VOCAL_MORPHER_PHONEME_I: number;
    static AL_VOCAL_MORPHER_PHONEME_IH: number;
    static AL_VOCAL_MORPHER_PHONEME_IY: number;
    static AL_VOCAL_MORPHER_PHONEME_J: number;
    static AL_VOCAL_MORPHER_PHONEME_K: number;
    static AL_VOCAL_MORPHER_PHONEME_L: number;
    static AL_VOCAL_MORPHER_PHONEME_M: number;
    static AL_VOCAL_MORPHER_PHONEME_N: number;
    static AL_VOCAL_MORPHER_PHONEME_O: number;
    static AL_VOCAL_MORPHER_PHONEME_P: number;
    static AL_VOCAL_MORPHER_PHONEME_R: number;
    static AL_VOCAL_MORPHER_PHONEME_S: number;
    static AL_VOCAL_MORPHER_PHONEME_T: number;
    static AL_VOCAL_MORPHER_PHONEME_U: number;
    static AL_VOCAL_MORPHER_PHONEME_UH: number;
    static AL_VOCAL_MORPHER_PHONEME_UW: number;
    static AL_VOCAL_MORPHER_PHONEME_V: number;
    static AL_VOCAL_MORPHER_PHONEME_Z: number;
    static AL_VOCAL_MORPHER_WAVEFORM_SAWTOOTH: number;
    static AL_VOCAL_MORPHER_WAVEFORM_SINUSOID: number;
    static AL_VOCAL_MORPHER_WAVEFORM_TRIANGLE: number;
    static AL_VOCMORPHER_PHONEMEA: number;
    static AL_VOCMORPHER_PHONEMEA_COARSE_TUNING: number;
    static AL_VOCMORPHER_PHONEMEB: number;
    static AL_VOCMORPHER_PHONEMEB_COARSE_TUNING: number;
    static AL_VOCMORPHER_RATE: number;
    static AL_VOCMORPHER_WAVEFORM: number;
    static alAuxiliaryEffectSlotf(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static alAuxiliaryEffectSlotfDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static alAuxiliaryEffectSlotfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alAuxiliaryEffectSlotfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static alAuxiliaryEffectSlotfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alAuxiliaryEffectSlotfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static alAuxiliaryEffectSloti(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static alAuxiliaryEffectSlotiDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static alAuxiliaryEffectSlotiv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alAuxiliaryEffectSlotiv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static alAuxiliaryEffectSlotivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alAuxiliaryEffectSlotivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static alDeleteAuxiliaryEffectSlots(paramarg0: number): void;
    static alDeleteAuxiliaryEffectSlots(paramarg0: number[]): void;
    static alDeleteAuxiliaryEffectSlots(paramarg0: IntBuffer): void;
    static alDeleteAuxiliaryEffectSlotsDirect(paramarg0: number, paramarg1: number): void;
    static alDeleteAuxiliaryEffectSlotsDirect(paramarg0: number, paramarg1: number[]): void;
    static alDeleteAuxiliaryEffectSlotsDirect(paramarg0: number, paramarg1: IntBuffer): void;
    static alDeleteEffects(paramarg0: number): void;
    static alDeleteEffects(paramarg0: number[]): void;
    static alDeleteEffects(paramarg0: IntBuffer): void;
    static alDeleteEffectsDirect(paramarg0: number, paramarg1: number): void;
    static alDeleteEffectsDirect(paramarg0: number, paramarg1: number[]): void;
    static alDeleteEffectsDirect(paramarg0: number, paramarg1: IntBuffer): void;
    static alDeleteFilters(paramarg0: number): void;
    static alDeleteFilters(paramarg0: number[]): void;
    static alDeleteFilters(paramarg0: IntBuffer): void;
    static alDeleteFiltersDirect(paramarg0: number, paramarg1: number): void;
    static alDeleteFiltersDirect(paramarg0: number, paramarg1: number[]): void;
    static alDeleteFiltersDirect(paramarg0: number, paramarg1: IntBuffer): void;
    static alEffectf(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static alEffectfDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static alEffectfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alEffectfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static alEffectfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alEffectfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static alEffecti(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static alEffectiDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static alEffectiv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alEffectiv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static alEffectivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alEffectivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static alFilterf(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static alFilterfDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static alFilterfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alFilterfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static alFilterfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alFilterfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static alFilteri(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static alFilteriDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static alFilteriv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alFilteriv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static alFilterivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alFilterivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static alGenAuxiliaryEffectSlots(): number;
    static alGenAuxiliaryEffectSlots(paramarg0: number[]): void;
    static alGenAuxiliaryEffectSlots(paramarg0: IntBuffer): void;
    static alGenAuxiliaryEffectSlotsDirect(paramarg0: number): number;
    static alGenAuxiliaryEffectSlotsDirect(paramarg0: number, paramarg1: number[]): void;
    static alGenAuxiliaryEffectSlotsDirect(paramarg0: number, paramarg1: IntBuffer): void;
    static alGenEffects(): number;
    static alGenEffects(paramarg0: number[]): void;
    static alGenEffects(paramarg0: IntBuffer): void;
    static alGenEffectsDirect(paramarg0: number): number;
    static alGenEffectsDirect(paramarg0: number, paramarg1: number[]): void;
    static alGenEffectsDirect(paramarg0: number, paramarg1: IntBuffer): void;
    static alGenFilters(): number;
    static alGenFilters(paramarg0: number[]): void;
    static alGenFilters(paramarg0: IntBuffer): void;
    static alGenFiltersDirect(paramarg0: number): number;
    static alGenFiltersDirect(paramarg0: number, paramarg1: number[]): void;
    static alGenFiltersDirect(paramarg0: number, paramarg1: IntBuffer): void;
    static alGetAuxiliaryEffectSlotf(paramarg0: number, paramarg1: number): number;
    static alGetAuxiliaryEffectSlotf(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alGetAuxiliaryEffectSlotf(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static alGetAuxiliaryEffectSlotfDirect(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static alGetAuxiliaryEffectSlotfDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alGetAuxiliaryEffectSlotfDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static alGetAuxiliaryEffectSlotfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alGetAuxiliaryEffectSlotfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static alGetAuxiliaryEffectSlotfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alGetAuxiliaryEffectSlotfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static alGetAuxiliaryEffectSloti(paramarg0: number, paramarg1: number): number;
    static alGetAuxiliaryEffectSloti(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alGetAuxiliaryEffectSloti(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static alGetAuxiliaryEffectSlotiDirect(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static alGetAuxiliaryEffectSlotiDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alGetAuxiliaryEffectSlotiDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static alGetAuxiliaryEffectSlotiv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alGetAuxiliaryEffectSlotiv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static alGetAuxiliaryEffectSlotivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alGetAuxiliaryEffectSlotivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static alGetEffectf(paramarg0: number, paramarg1: number): number;
    static alGetEffectf(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alGetEffectf(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static alGetEffectfDirect(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static alGetEffectfDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alGetEffectfDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static alGetEffectfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alGetEffectfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static alGetEffectfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alGetEffectfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static alGetEffecti(paramarg0: number, paramarg1: number): number;
    static alGetEffecti(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alGetEffecti(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static alGetEffectiDirect(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static alGetEffectiDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alGetEffectiDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static alGetEffectiv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alGetEffectiv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static alGetEffectivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alGetEffectivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static alGetFilterf(paramarg0: number, paramarg1: number): number;
    static alGetFilterf(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alGetFilterf(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static alGetFilterfDirect(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static alGetFilterfDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alGetFilterfDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static alGetFilterfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alGetFilterfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static alGetFilterfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alGetFilterfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static alGetFilteri(paramarg0: number, paramarg1: number): number;
    static alGetFilteri(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alGetFilteri(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static alGetFilteriDirect(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static alGetFilteriDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alGetFilteriDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static alGetFilteriv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static alGetFilteriv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static alGetFilterivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static alGetFilterivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static alIsAuxiliaryEffectSlot(paramarg0: number): boolean;
    static alIsAuxiliaryEffectSlotDirect(paramarg0: number, paramarg1: number): boolean;
    static alIsEffect(paramarg0: number): boolean;
    static alIsEffectDirect(paramarg0: number, paramarg1: number): boolean;
    static alIsFilter(paramarg0: number): boolean;
    static alIsFilterDirect(paramarg0: number, paramarg1: number): boolean;
    static nalAuxiliaryEffectSlotfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalAuxiliaryEffectSlotfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalAuxiliaryEffectSlotiv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalAuxiliaryEffectSlotivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalDeleteAuxiliaryEffectSlots(paramarg0: number, paramarg1: number): void;
    static nalDeleteAuxiliaryEffectSlotsDirect(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalDeleteEffects(paramarg0: number, paramarg1: number): void;
    static nalDeleteEffectsDirect(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalDeleteFilters(paramarg0: number, paramarg1: number): void;
    static nalDeleteFiltersDirect(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalEffectfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalEffectfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalEffectiv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalEffectivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalFilterfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalFilterfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalFilteriv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalFilterivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalGenAuxiliaryEffectSlots(paramarg0: number, paramarg1: number): void;
    static nalGenAuxiliaryEffectSlotsDirect(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGenEffects(paramarg0: number, paramarg1: number): void;
    static nalGenEffectsDirect(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGenFilters(paramarg0: number, paramarg1: number): void;
    static nalGenFiltersDirect(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGetAuxiliaryEffectSlotf(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGetAuxiliaryEffectSlotfDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalGetAuxiliaryEffectSlotfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGetAuxiliaryEffectSlotfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalGetAuxiliaryEffectSloti(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGetAuxiliaryEffectSlotiDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalGetAuxiliaryEffectSlotiv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGetAuxiliaryEffectSlotivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalGetEffectf(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGetEffectfDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalGetEffectfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGetEffectfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalGetEffecti(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGetEffectiDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalGetEffectiv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGetEffectivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalGetFilterf(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGetFilterfDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalGetFilterfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGetFilterfvDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalGetFilteri(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGetFilteriDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nalGetFilteriv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nalGetFilterivDirect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    constructor()
}