import type { Class } from '../../../java/lang/Class.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { ComparableWord } from '../../../org/graalvm/word/ComparableWord.d.ts'
import type { LocationIdentity } from '../../../org/graalvm/word/LocationIdentity.d.ts'
import type { Pointer } from '../../../org/graalvm/word/Pointer.d.ts'
import type { SignedWord } from '../../../org/graalvm/word/SignedWord.d.ts'
import type { UnsignedWord } from '../../../org/graalvm/word/UnsignedWord.d.ts'
import type { WordBase } from '../../../org/graalvm/word/WordBase.d.ts'
export class Word extends Object implements Pointer, SignedWord, UnsignedWord {
    constructor(val: number)
    // private rawValue: number;
    aboveOrEqual(val: number): boolean;
    aboveOrEqual(val: UnsignedWord): boolean;
    aboveThan(val: number): boolean;
    aboveThan(val: UnsignedWord): boolean;
    add(val: number): Word;
    add(val: SignedWord): SignedWord;
    add(val: UnsignedWord): Pointer;
    and(val: number): Word;
    and(val: SignedWord): SignedWord;
    and(val: UnsignedWord): Pointer;
    belowOrEqual(val: number): boolean;
    belowOrEqual(val: UnsignedWord): boolean;
    belowThan(val: number): boolean;
    belowThan(val: UnsignedWord): boolean;
    compareAndSwapInt(offset: number, expectedValue: number, newValue: number, locationIdentity: LocationIdentity): number;
    compareAndSwapInt(offset: WordBase, expectedValue: number, newValue: number, locationIdentity: LocationIdentity): number;
    compareAndSwapLong(offset: number, expectedValue: number, newValue: number, locationIdentity: LocationIdentity): number;
    compareAndSwapLong(offset: WordBase, expectedValue: number, newValue: number, locationIdentity: LocationIdentity): number;
    compareAndSwapObject(offset: number, expectedValue: Object, newValue: Object, locationIdentity: LocationIdentity): Object;
    compareAndSwapObject(offset: WordBase, expectedValue: Object, newValue: Object, locationIdentity: LocationIdentity): Object;
    compareAndSwapWord<T extends WordBase>(offset: number, expectedValue: T, newValue: T, locationIdentity: LocationIdentity): T;
    compareAndSwapWord<T extends WordBase>(offset: WordBase, expectedValue: T, newValue: T, locationIdentity: LocationIdentity): T;
    equal(val: number): boolean;
    equal(val: ComparableWord): boolean;
    equal(val: SignedWord): boolean;
    equal(val: UnsignedWord): boolean;
    greaterOrEqual(val: number): boolean;
    greaterOrEqual(val: SignedWord): boolean;
    greaterThan(val: number): boolean;
    greaterThan(val: SignedWord): boolean;
    initializeLong(offset: number, val: number, locationIdentity: LocationIdentity): void;
    initializeLong(offset: WordBase, val: number, locationIdentity: LocationIdentity): void;
    isNonNull(): boolean;
    isNull(): boolean;
    lessOrEqual(val: number): boolean;
    lessOrEqual(val: SignedWord): boolean;
    lessThan(val: number): boolean;
    lessThan(val: SignedWord): boolean;
    logicCompareAndSwapInt(offset: number, expectedValue: number, newValue: number, locationIdentity: LocationIdentity): boolean;
    logicCompareAndSwapInt(offset: WordBase, expectedValue: number, newValue: number, locationIdentity: LocationIdentity): boolean;
    logicCompareAndSwapLong(offset: number, expectedValue: number, newValue: number, locationIdentity: LocationIdentity): boolean;
    logicCompareAndSwapLong(offset: WordBase, expectedValue: number, newValue: number, locationIdentity: LocationIdentity): boolean;
    logicCompareAndSwapObject(offset: number, expectedValue: Object, newValue: Object, locationIdentity: LocationIdentity): boolean;
    logicCompareAndSwapObject(offset: WordBase, expectedValue: Object, newValue: Object, locationIdentity: LocationIdentity): boolean;
    logicCompareAndSwapWord(offset: number, expectedValue: WordBase, newValue: WordBase, locationIdentity: LocationIdentity): boolean;
    logicCompareAndSwapWord(offset: WordBase, expectedValue: WordBase, newValue: WordBase, locationIdentity: LocationIdentity): boolean;
    multiply(val: number): Word;
    multiply(val: SignedWord): SignedWord;
    multiply(val: UnsignedWord): UnsignedWord;
    not(): Word;
    notEqual(val: number): boolean;
    notEqual(val: ComparableWord): boolean;
    notEqual(val: SignedWord): boolean;
    notEqual(val: UnsignedWord): boolean;
    or(val: number): Word;
    or(val: SignedWord): SignedWord;
    or(val: UnsignedWord): Pointer;
    rawValue(): number;
    readByte(offset: number): number;
    readByte(offset: number, locationIdentity: LocationIdentity): number;
    readByte(offset: WordBase): number;
    readByte(offset: WordBase, locationIdentity: LocationIdentity): number;
    readChar(offset: number): string;
    readChar(offset: number, locationIdentity: LocationIdentity): string;
    readChar(offset: WordBase): string;
    readChar(offset: WordBase, locationIdentity: LocationIdentity): string;
    readDouble(offset: number): number;
    readDouble(offset: number, locationIdentity: LocationIdentity): number;
    readDouble(offset: WordBase): number;
    readDouble(offset: WordBase, locationIdentity: LocationIdentity): number;
    readFloat(offset: number): number;
    readFloat(offset: number, locationIdentity: LocationIdentity): number;
    readFloat(offset: WordBase): number;
    readFloat(offset: WordBase, locationIdentity: LocationIdentity): number;
    readInt(offset: number): number;
    readInt(offset: number, locationIdentity: LocationIdentity): number;
    readInt(offset: WordBase): number;
    readInt(offset: WordBase, locationIdentity: LocationIdentity): number;
    readLong(offset: number): number;
    readLong(offset: number, locationIdentity: LocationIdentity): number;
    readLong(offset: WordBase): number;
    readLong(offset: WordBase, locationIdentity: LocationIdentity): number;
    readObject(offset: number): Object;
    readObject(offset: number, locationIdentity: LocationIdentity): Object;
    readObject(offset: WordBase): Object;
    readObject(offset: WordBase, locationIdentity: LocationIdentity): Object;
    readShort(offset: number): number;
    readShort(offset: number, locationIdentity: LocationIdentity): number;
    readShort(offset: WordBase): number;
    readShort(offset: WordBase, locationIdentity: LocationIdentity): number;
    readWord<T extends WordBase>(offset: number): T;
    readWord<T extends WordBase>(offset: number, locationIdentity: LocationIdentity): T;
    readWord<T extends WordBase>(offset: WordBase): T;
    readWord<T extends WordBase>(offset: WordBase, locationIdentity: LocationIdentity): T;
    readWordVolatile<T extends WordBase>(offset: number, locationIdentity: LocationIdentity): T;
    shiftLeft(n: number): Word;
    shiftLeft(n: UnsignedWord): Word;
    signedDivide(val: number): SignedWord;
    signedDivide(val: SignedWord): SignedWord;
    signedRemainder(val: number): SignedWord;
    signedRemainder(val: SignedWord): SignedWord;
    signedShiftRight(n: number): SignedWord;
    signedShiftRight(n: UnsignedWord): SignedWord;
    subtract(val: number): Word;
    subtract(val: SignedWord): SignedWord;
    subtract(val: UnsignedWord): Pointer;
    toObject(): Object;
    toObject<T extends unknown>(clazz: Class<T>, nonNull: boolean): T;
    toObjectNonNull(): Object;
    unsignedDivide(val: number): UnsignedWord;
    unsignedDivide(val: UnsignedWord): UnsignedWord;
    unsignedRemainder(val: number): UnsignedWord;
    unsignedRemainder(val: UnsignedWord): UnsignedWord;
    unsignedShiftRight(n: number): UnsignedWord;
    unsignedShiftRight(n: UnsignedWord): UnsignedWord;
    writeByte(offset: number, val: number): void;
    writeByte(offset: number, val: number, locationIdentity: LocationIdentity): void;
    writeByte(offset: WordBase, val: number): void;
    writeByte(offset: WordBase, val: number, locationIdentity: LocationIdentity): void;
    writeChar(offset: number, val: string): void;
    writeChar(offset: number, val: string, locationIdentity: LocationIdentity): void;
    writeChar(offset: WordBase, val: string): void;
    writeChar(offset: WordBase, val: string, locationIdentity: LocationIdentity): void;
    writeDouble(offset: number, val: number): void;
    writeDouble(offset: number, val: number, locationIdentity: LocationIdentity): void;
    writeDouble(offset: WordBase, val: number): void;
    writeDouble(offset: WordBase, val: number, locationIdentity: LocationIdentity): void;
    writeFloat(offset: number, val: number): void;
    writeFloat(offset: number, val: number, locationIdentity: LocationIdentity): void;
    writeFloat(offset: WordBase, val: number): void;
    writeFloat(offset: WordBase, val: number, locationIdentity: LocationIdentity): void;
    writeInt(offset: number, val: number): void;
    writeInt(offset: number, val: number, locationIdentity: LocationIdentity): void;
    writeInt(offset: WordBase, val: number): void;
    writeInt(offset: WordBase, val: number, locationIdentity: LocationIdentity): void;
    writeLong(offset: number, val: number): void;
    writeLong(offset: number, val: number, locationIdentity: LocationIdentity): void;
    writeLong(offset: WordBase, val: number): void;
    writeLong(offset: WordBase, val: number, locationIdentity: LocationIdentity): void;
    writeObject(offset: number, val: Object): void;
    writeObject(offset: number, val: Object, locationIdentity: LocationIdentity): void;
    writeObject(offset: WordBase, val: Object): void;
    writeObject(offset: WordBase, val: Object, locationIdentity: LocationIdentity): void;
    writeShort(offset: number, val: number): void;
    writeShort(offset: number, val: number, locationIdentity: LocationIdentity): void;
    writeShort(offset: WordBase, val: number): void;
    writeShort(offset: WordBase, val: number, locationIdentity: LocationIdentity): void;
    writeWord(offset: number, val: WordBase): void;
    writeWord(offset: number, val: WordBase, locationIdentity: LocationIdentity): void;
    writeWord(offset: WordBase, val: WordBase): void;
    writeWord(offset: WordBase, val: WordBase, locationIdentity: LocationIdentity): void;
    writeWordVolatile(offset: number, val: WordBase): void;
    xor(val: number): Word;
    xor(val: SignedWord): SignedWord;
    xor(val: UnsignedWord): UnsignedWord;
}