import type { App } from '../../../../com/mojang/datafixers/kinds/App.d.ts'
import type { Applicative } from '../../../../com/mojang/datafixers/kinds/Applicative.d.ts'
import type { Applicative$Mu } from '../../../../com/mojang/datafixers/kinds/Applicative$Mu.d.ts'
import type { CocartesianLike } from '../../../../com/mojang/datafixers/kinds/CocartesianLike.d.ts'
import type { CocartesianLike$Mu } from '../../../../com/mojang/datafixers/kinds/CocartesianLike$Mu.d.ts'
import type { K1 } from '../../../../com/mojang/datafixers/kinds/K1.d.ts'
import type { Traversable } from '../../../../com/mojang/datafixers/kinds/Traversable.d.ts'
import type { Traversable$Mu } from '../../../../com/mojang/datafixers/kinds/Traversable$Mu.d.ts'
import type { Either$Instance$Mu } from '../../../../com/mojang/datafixers/util/Either$Instance$Mu.d.ts'
import type { Either$Mu } from '../../../../com/mojang/datafixers/util/Either$Mu.d.ts'
import type { Function10 } from '../../../../com/mojang/datafixers/util/Function10.d.ts'
import type { Function11 } from '../../../../com/mojang/datafixers/util/Function11.d.ts'
import type { Function12 } from '../../../../com/mojang/datafixers/util/Function12.d.ts'
import type { Function13 } from '../../../../com/mojang/datafixers/util/Function13.d.ts'
import type { Function14 } from '../../../../com/mojang/datafixers/util/Function14.d.ts'
import type { Function15 } from '../../../../com/mojang/datafixers/util/Function15.d.ts'
import type { Function16 } from '../../../../com/mojang/datafixers/util/Function16.d.ts'
import type { Function3 } from '../../../../com/mojang/datafixers/util/Function3.d.ts'
import type { Function4 } from '../../../../com/mojang/datafixers/util/Function4.d.ts'
import type { Function5 } from '../../../../com/mojang/datafixers/util/Function5.d.ts'
import type { Function6 } from '../../../../com/mojang/datafixers/util/Function6.d.ts'
import type { Function7 } from '../../../../com/mojang/datafixers/util/Function7.d.ts'
import type { Function8 } from '../../../../com/mojang/datafixers/util/Function8.d.ts'
import type { Function9 } from '../../../../com/mojang/datafixers/util/Function9.d.ts'
import type { BiFunction } from '../../../../java/util/function/BiFunction.d.ts'
import type { Function } from '../../../../java/util/function/Function.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
export class Either$Instance<R2 extends Object | number | string | boolean> extends Object implements Applicative<Either$Mu<R2>, Either$Instance$Mu<R2>>, CocartesianLike<Either$Mu<R2>, R2, Either$Instance$Mu<R2>>, Traversable<Either$Mu<R2>, Either$Instance$Mu<R2>> {
    static unbox(paramarg0: App<CocartesianLike$Mu, K1>): CocartesianLike<K1, Object, CocartesianLike$Mu>;
    static unbox(paramarg0: App<Applicative$Mu, K1>): Applicative<K1, Applicative$Mu>;
    static unbox(paramarg0: App<Traversable$Mu, K1>): Traversable<K1, Traversable$Mu>;
    constructor()
    ap<R extends Object | number | string | boolean, A extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, (param0: A) => R>, arg1: App<Either$Mu<R2>, A>): App<Either$Mu<R2>, R>;
    ap<R extends Object | number | string | boolean, A extends Object | number | string | boolean>(arg0: (param0: A) => R, arg1: App<Either$Mu<R2>, A>): App<Either$Mu<R2>, R>;
    ap10<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>, arg7: App<Either$Mu<R2>, T7>, arg8: App<Either$Mu<R2>, T8>, arg9: App<Either$Mu<R2>, T9>, arg10: App<Either$Mu<R2>, T10>): App<Either$Mu<R2>, R>;
    ap11<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>, arg7: App<Either$Mu<R2>, T7>, arg8: App<Either$Mu<R2>, T8>, arg9: App<Either$Mu<R2>, T9>, arg10: App<Either$Mu<R2>, T10>, arg11: App<Either$Mu<R2>, T11>): App<Either$Mu<R2>, R>;
    ap12<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>, arg7: App<Either$Mu<R2>, T7>, arg8: App<Either$Mu<R2>, T8>, arg9: App<Either$Mu<R2>, T9>, arg10: App<Either$Mu<R2>, T10>, arg11: App<Either$Mu<R2>, T11>, arg12: App<Either$Mu<R2>, T12>): App<Either$Mu<R2>, R>;
    ap13<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>, arg7: App<Either$Mu<R2>, T7>, arg8: App<Either$Mu<R2>, T8>, arg9: App<Either$Mu<R2>, T9>, arg10: App<Either$Mu<R2>, T10>, arg11: App<Either$Mu<R2>, T11>, arg12: App<Either$Mu<R2>, T12>, arg13: App<Either$Mu<R2>, T13>): App<Either$Mu<R2>, R>;
    ap14<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>, arg7: App<Either$Mu<R2>, T7>, arg8: App<Either$Mu<R2>, T8>, arg9: App<Either$Mu<R2>, T9>, arg10: App<Either$Mu<R2>, T10>, arg11: App<Either$Mu<R2>, T11>, arg12: App<Either$Mu<R2>, T12>, arg13: App<Either$Mu<R2>, T13>, arg14: App<Either$Mu<R2>, T14>): App<Either$Mu<R2>, R>;
    ap15<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean, T15 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>, arg7: App<Either$Mu<R2>, T7>, arg8: App<Either$Mu<R2>, T8>, arg9: App<Either$Mu<R2>, T9>, arg10: App<Either$Mu<R2>, T10>, arg11: App<Either$Mu<R2>, T11>, arg12: App<Either$Mu<R2>, T12>, arg13: App<Either$Mu<R2>, T13>, arg14: App<Either$Mu<R2>, T14>, arg15: App<Either$Mu<R2>, T15>): App<Either$Mu<R2>, R>;
    ap16<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean, T15 extends Object | number | string | boolean, T16 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>, arg7: App<Either$Mu<R2>, T7>, arg8: App<Either$Mu<R2>, T8>, arg9: App<Either$Mu<R2>, T9>, arg10: App<Either$Mu<R2>, T10>, arg11: App<Either$Mu<R2>, T11>, arg12: App<Either$Mu<R2>, T12>, arg13: App<Either$Mu<R2>, T13>, arg14: App<Either$Mu<R2>, T14>, arg15: App<Either$Mu<R2>, T15>, arg16: App<Either$Mu<R2>, T16>): App<Either$Mu<R2>, R>;
    ap2<R extends Object | number | string | boolean, A extends Object | number | string | boolean, B extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, (param0: A, param1: B) => R>, arg1: App<Either$Mu<R2>, A>, arg2: App<Either$Mu<R2>, B>): App<Either$Mu<R2>, R>;
    ap3<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function3<T1, T2, T3, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>): App<Either$Mu<R2>, R>;
    ap4<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function4<T1, T2, T3, T4, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>): App<Either$Mu<R2>, R>;
    ap5<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function5<T1, T2, T3, T4, T5, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>): App<Either$Mu<R2>, R>;
    ap6<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function6<T1, T2, T3, T4, T5, T6, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>): App<Either$Mu<R2>, R>;
    ap7<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function7<T1, T2, T3, T4, T5, T6, T7, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>, arg7: App<Either$Mu<R2>, T7>): App<Either$Mu<R2>, R>;
    ap8<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>, arg7: App<Either$Mu<R2>, T7>, arg8: App<Either$Mu<R2>, T8>): App<Either$Mu<R2>, R>;
    ap9<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>, arg7: App<Either$Mu<R2>, T7>, arg8: App<Either$Mu<R2>, T8>, arg9: App<Either$Mu<R2>, T9>): App<Either$Mu<R2>, R>;
    apply2<R extends Object | number | string | boolean, A extends Object | number | string | boolean, B extends Object | number | string | boolean>(arg0: (param0: A, param1: B) => R, arg1: App<Either$Mu<R2>, A>, arg2: App<Either$Mu<R2>, B>): App<Either$Mu<R2>, R>;
    apply3<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean>(arg0: Function3<T1, T2, T3, R>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>): App<Either$Mu<R2>, R>;
    apply4<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean>(arg0: Function4<T1, T2, T3, T4, R>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>): App<Either$Mu<R2>, R>;
    apply5<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean>(arg0: Function5<T1, T2, T3, T4, T5, R>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>): App<Either$Mu<R2>, R>;
    apply6<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean>(arg0: Function6<T1, T2, T3, T4, T5, T6, R>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>): App<Either$Mu<R2>, R>;
    apply7<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean>(arg0: Function7<T1, T2, T3, T4, T5, T6, T7, R>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>, arg7: App<Either$Mu<R2>, T7>): App<Either$Mu<R2>, R>;
    apply8<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean>(arg0: Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>, arg7: App<Either$Mu<R2>, T7>, arg8: App<Either$Mu<R2>, T8>): App<Either$Mu<R2>, R>;
    apply9<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean>(arg0: Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>, arg1: App<Either$Mu<R2>, T1>, arg2: App<Either$Mu<R2>, T2>, arg3: App<Either$Mu<R2>, T3>, arg4: App<Either$Mu<R2>, T4>, arg5: App<Either$Mu<R2>, T5>, arg6: App<Either$Mu<R2>, T6>, arg7: App<Either$Mu<R2>, T7>, arg8: App<Either$Mu<R2>, T8>, arg9: App<Either$Mu<R2>, T9>): App<Either$Mu<R2>, R>;
    flip<F extends K1, A extends Object | number | string | boolean>(arg0: Applicative<F, any>, arg1: App<Either$Mu<R2>, App<F, A>>): App<F, App<Either$Mu<R2>, A>>;
    from<A extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, A>): App<Either$Mu<R2>, A>;
    lift1<A extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, (param0: A) => R>): (param0: App<Either$Mu<R2>, A>) => App<Either$Mu<R2>, R>;
    lift2<A extends Object | number | string | boolean, B extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, (param0: A, param1: B) => R>): (param0: App<Either$Mu<R2>, A>, param1: App<Either$Mu<R2>, B>) => App<Either$Mu<R2>, R>;
    lift3<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function3<T1, T2, T3, R>>): Function3<App<Either$Mu<R2>, T1>, App<Either$Mu<R2>, T2>, App<Either$Mu<R2>, T3>, App<Either$Mu<R2>, R>>;
    lift4<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function4<T1, T2, T3, T4, R>>): Function4<App<Either$Mu<R2>, T1>, App<Either$Mu<R2>, T2>, App<Either$Mu<R2>, T3>, App<Either$Mu<R2>, T4>, App<Either$Mu<R2>, R>>;
    lift5<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function5<T1, T2, T3, T4, T5, R>>): Function5<App<Either$Mu<R2>, T1>, App<Either$Mu<R2>, T2>, App<Either$Mu<R2>, T3>, App<Either$Mu<R2>, T4>, App<Either$Mu<R2>, T5>, App<Either$Mu<R2>, R>>;
    lift6<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function6<T1, T2, T3, T4, T5, T6, R>>): Function6<App<Either$Mu<R2>, T1>, App<Either$Mu<R2>, T2>, App<Either$Mu<R2>, T3>, App<Either$Mu<R2>, T4>, App<Either$Mu<R2>, T5>, App<Either$Mu<R2>, T6>, App<Either$Mu<R2>, R>>;
    lift7<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function7<T1, T2, T3, T4, T5, T6, T7, R>>): Function7<App<Either$Mu<R2>, T1>, App<Either$Mu<R2>, T2>, App<Either$Mu<R2>, T3>, App<Either$Mu<R2>, T4>, App<Either$Mu<R2>, T5>, App<Either$Mu<R2>, T6>, App<Either$Mu<R2>, T7>, App<Either$Mu<R2>, R>>;
    lift8<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>>): Function8<App<Either$Mu<R2>, T1>, App<Either$Mu<R2>, T2>, App<Either$Mu<R2>, T3>, App<Either$Mu<R2>, T4>, App<Either$Mu<R2>, T5>, App<Either$Mu<R2>, T6>, App<Either$Mu<R2>, T7>, App<Either$Mu<R2>, T8>, App<Either$Mu<R2>, R>>;
    lift9<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>>): Function9<App<Either$Mu<R2>, T1>, App<Either$Mu<R2>, T2>, App<Either$Mu<R2>, T3>, App<Either$Mu<R2>, T4>, App<Either$Mu<R2>, T5>, App<Either$Mu<R2>, T6>, App<Either$Mu<R2>, T7>, App<Either$Mu<R2>, T8>, App<Either$Mu<R2>, T9>, App<Either$Mu<R2>, R>>;
    map<R extends Object | number | string | boolean, T extends Object | number | string | boolean>(arg0: (param0: T) => R, arg1: App<Either$Mu<R2>, T>): App<Either$Mu<R2>, R>;
    point<A extends Object | number | string | boolean>(arg0: A): App<Either$Mu<R2>, A>;
    to<A extends Object | number | string | boolean>(arg0: App<Either$Mu<R2>, A>): App<Either$Mu<R2>, A>;
    traverse<F extends K1, B extends Object | number | string | boolean, A extends Object | number | string | boolean>(arg0: Applicative<F, any>, arg1: (param0: A) => App<F, B>, arg2: App<Either$Mu<R2>, A>): App<F, App<Either$Mu<R2>, B>>;
}