import type { Class } from '../../java/lang/Class.d.ts'
import type { Comparator } from '../../java/util/Comparator.d.ts'
import type { Object } from '../../java/lang/Object.d.ts'
import type { Comparable } from '../../java/lang/Comparable.d.ts'
import type { Function1 } from '../../kotlin/jvm/functions/Function1.d.ts'
import type { Pair } from '../../kotlin/Pair.d.ts'
import type { ArraysKt__ArraysKt } from '../../kotlin/collections/ArraysKt__ArraysKt.d.ts'
export class ArraysKt___ArraysJvmKt extends ArraysKt__ArraysKt {
    static arrayOfNulls(paramarg0: Object | null, paramarg1: number): Object | null;
    static asList(paramarg0: Object | null): (Object | null)[];
    static asList(paramarg0: (Object | null)[]): boolean[];
    static asList(paramarg0: number[]): number[];
    static asList(paramarg0: string[]): string[];
    static asList(paramarg0: number[]): number[];
    static asList(paramarg0: number[]): number[];
    static asList(paramarg0: number[]): number[];
    static asList(paramarg0: number[]): number[];
    static asList(paramarg0: number[]): number[];
    static binarySearch(paramarg0: Object | null, paramarg1: Object | null, paramarg2: number, paramarg3: number): number;
    static binarySearch(paramarg0: Object | null, paramarg1: Object | null, paramarg2: (param0: Object | null) => kotlin.Boolean, paramarg3: number, paramarg4: number): number;
    static binarySearch(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
    static binarySearch(paramarg0: string[], paramarg1: string, paramarg2: number, paramarg3: number): number;
    static binarySearch(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
    static binarySearch(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
    static binarySearch(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
    static binarySearch(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
    static binarySearch(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
    static contentDeepEquals(paramarg0: Object | null, paramarg1: Object | null): boolean;
    static contentDeepHashCode(paramarg0: Object | null): number;
    static contentDeepToString(paramarg0: Object | null): string;
    static copyInto(paramarg0: Object | null, paramarg1: Object | null, paramarg2: number, paramarg3: number, paramarg4: number): Object | null;
    static copyInto(paramarg0: (Object | null)[], paramarg1: (Object | null)[], paramarg2: number, paramarg3: number, paramarg4: number): (Object | null)[];
    static copyInto(paramarg0: number[], paramarg1: number[], paramarg2: number, paramarg3: number, paramarg4: number): number[];
    static copyInto(paramarg0: string[], paramarg1: string[], paramarg2: number, paramarg3: number, paramarg4: number): string[];
    static copyInto(paramarg0: number[], paramarg1: number[], paramarg2: number, paramarg3: number, paramarg4: number): number[];
    static copyInto(paramarg0: number[], paramarg1: number[], paramarg2: number, paramarg3: number, paramarg4: number): number[];
    static copyInto(paramarg0: number[], paramarg1: number[], paramarg2: number, paramarg3: number, paramarg4: number): number[];
    static copyInto(paramarg0: number[], paramarg1: number[], paramarg2: number, paramarg3: number, paramarg4: number): number[];
    static copyInto(paramarg0: number[], paramarg1: number[], paramarg2: number, paramarg3: number, paramarg4: number): number[];
    static copyOfRange(paramarg0: Object | null, paramarg1: number, paramarg2: number): Object | null;
    static copyOfRange(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number): (Object | null)[];
    static copyOfRange(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static copyOfRange(paramarg0: string[], paramarg1: number, paramarg2: number): string[];
    static copyOfRange(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static copyOfRange(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static copyOfRange(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static copyOfRange(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static copyOfRange(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static copyOfRangeToIndexCheck(paramarg0: number, paramarg1: number): void;
    static fill(paramarg0: Object | null, paramarg1: Object | null, paramarg2: number, paramarg3: number): void;
    static fill(paramarg0: (Object | null)[], paramarg1: boolean, paramarg2: number, paramarg3: number): void;
    static fill(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static fill(paramarg0: string[], paramarg1: string, paramarg2: number, paramarg3: number): void;
    static fill(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static fill(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static fill(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static fill(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static fill(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static filterIsInstance(paramarg0: (Object | null)[], paramarg1: Class<Object>): (Object | null)[];
    static filterIsInstanceTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: Class<Object>): Object | null;
    static flatten(paramarg0: Object | null): (Object | null)[];
    static max(paramarg0: number[]): number;
    static max(paramarg0: string[]): string;
    static max(paramarg0: (Object | null)[]): Comparable<Object>;
    static max(paramarg0: number[]): number;
    static max(paramarg0: (Object | null)[]): number;
    static max(paramarg0: number[]): number;
    static max(paramarg0: (Object | null)[]): number;
    static max(paramarg0: number[]): number;
    static max(paramarg0: number[]): number;
    static max(paramarg0: number[]): number;
    static maxBy(paramarg0: (Object | null)[], paramarg1: Function1<Object, Object>): boolean;
    static maxBy(paramarg0: number[], paramarg1: Function1<Object, Object>): number;
    static maxBy(paramarg0: string[], paramarg1: Function1<Object, Object>): string;
    static maxBy(paramarg0: number[], paramarg1: Function1<Object, Object>): number;
    static maxBy(paramarg0: number[], paramarg1: Function1<Object, Object>): number;
    static maxBy(paramarg0: number[], paramarg1: Function1<Object, Object>): number;
    static maxBy(paramarg0: number[], paramarg1: Function1<Object, Object>): number;
    static maxBy(paramarg0: number[], paramarg1: Function1<Object, Object>): number;
    static maxBy(paramarg0: Object | null, paramarg1: Function1<Object, Object>): Object | null;
    static maxWith(paramarg0: (Object | null)[], paramarg1: (param0: Object | null) => kotlin.Boolean): boolean;
    static maxWith(paramarg0: number[], paramarg1: (param0: Object | null) => kotlin.Boolean): number;
    static maxWith(paramarg0: string[], paramarg1: (param0: Object | null) => kotlin.Boolean): string;
    static maxWith(paramarg0: number[], paramarg1: (param0: Object | null) => kotlin.Boolean): number;
    static maxWith(paramarg0: number[], paramarg1: (param0: Object | null) => kotlin.Boolean): number;
    static maxWith(paramarg0: number[], paramarg1: (param0: Object | null) => kotlin.Boolean): number;
    static maxWith(paramarg0: number[], paramarg1: (param0: Object | null) => kotlin.Boolean): number;
    static maxWith(paramarg0: (Object | null)[], paramarg1: (param0: Object | null) => kotlin.Boolean): Object;
    static maxWith(paramarg0: number[], paramarg1: (param0: Object | null) => kotlin.Boolean): number;
    static min(paramarg0: number[]): number;
    static min(paramarg0: string[]): string;
    static min(paramarg0: (Object | null)[]): Comparable<Object>;
    static min(paramarg0: number[]): number;
    static min(paramarg0: (Object | null)[]): number;
    static min(paramarg0: number[]): number;
    static min(paramarg0: (Object | null)[]): number;
    static min(paramarg0: number[]): number;
    static min(paramarg0: number[]): number;
    static min(paramarg0: number[]): number;
    static minBy(paramarg0: (Object | null)[], paramarg1: Function1<Object, Object>): boolean;
    static minBy(paramarg0: number[], paramarg1: Function1<Object, Object>): number;
    static minBy(paramarg0: string[], paramarg1: Function1<Object, Object>): string;
    static minBy(paramarg0: number[], paramarg1: Function1<Object, Object>): number;
    static minBy(paramarg0: number[], paramarg1: Function1<Object, Object>): number;
    static minBy(paramarg0: number[], paramarg1: Function1<Object, Object>): number;
    static minBy(paramarg0: number[], paramarg1: Function1<Object, Object>): number;
    static minBy(paramarg0: number[], paramarg1: Function1<Object, Object>): number;
    static minBy(paramarg0: Object | null, paramarg1: Function1<Object, Object>): Object | null;
    static minWith(paramarg0: (Object | null)[], paramarg1: (param0: Object | null) => kotlin.Boolean): boolean;
    static minWith(paramarg0: number[], paramarg1: (param0: Object | null) => kotlin.Boolean): number;
    static minWith(paramarg0: string[], paramarg1: (param0: Object | null) => kotlin.Boolean): string;
    static minWith(paramarg0: number[], paramarg1: (param0: Object | null) => kotlin.Boolean): number;
    static minWith(paramarg0: number[], paramarg1: (param0: Object | null) => kotlin.Boolean): number;
    static minWith(paramarg0: number[], paramarg1: (param0: Object | null) => kotlin.Boolean): number;
    static minWith(paramarg0: number[], paramarg1: (param0: Object | null) => kotlin.Boolean): number;
    static minWith(paramarg0: (Object | null)[], paramarg1: (param0: Object | null) => kotlin.Boolean): Object;
    static minWith(paramarg0: number[], paramarg1: (param0: Object | null) => kotlin.Boolean): number;
    static orEmpty(paramarg0: Object | null): Object | null;
    static plus(paramarg0: Object | null, paramarg1: Object | null): Object | null;
    static plus(paramarg0: Object | null, paramarg1: Object | null): Object | null;
    static plus(paramarg0: Object | null, paramarg1: E[]): Object | null;
    static plus(paramarg0: (Object | null)[], paramarg1: boolean): (Object | null)[];
    static plus(paramarg0: (Object | null)[], paramarg1: (Object | null)[]): (Object | null)[];
    static plus(paramarg0: (Object | null)[], paramarg1: E[]): (Object | null)[];
    static plus(paramarg0: number[], paramarg1: number): number[];
    static plus(paramarg0: number[], paramarg1: number[]): number[];
    static plus(paramarg0: number[], paramarg1: E[]): number[];
    static plus(paramarg0: string[], paramarg1: string): string[];
    static plus(paramarg0: string[], paramarg1: string[]): string[];
    static plus(paramarg0: string[], paramarg1: E[]): string[];
    static plus(paramarg0: number[], paramarg1: number): number[];
    static plus(paramarg0: number[], paramarg1: number[]): number[];
    static plus(paramarg0: number[], paramarg1: E[]): number[];
    static plus(paramarg0: number[], paramarg1: number): number[];
    static plus(paramarg0: number[], paramarg1: number[]): number[];
    static plus(paramarg0: number[], paramarg1: E[]): number[];
    static plus(paramarg0: number[], paramarg1: number): number[];
    static plus(paramarg0: number[], paramarg1: number[]): number[];
    static plus(paramarg0: number[], paramarg1: E[]): number[];
    static plus(paramarg0: number[], paramarg1: E[]): number[];
    static plus(paramarg0: number[], paramarg1: number): number[];
    static plus(paramarg0: number[], paramarg1: number[]): number[];
    static plus(paramarg0: number[], paramarg1: E[]): number[];
    static plus(paramarg0: number[], paramarg1: number): number[];
    static plus(paramarg0: number[], paramarg1: number[]): number[];
    static sort(paramarg0: Object | null, paramarg1: number, paramarg2: number): void;
    static sort(paramarg0: Object | null): void;
    static sort(paramarg0: Object | null, paramarg1: number, paramarg2: number): void;
    static sort(paramarg0: number[]): void;
    static sort(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static sort(paramarg0: string[]): void;
    static sort(paramarg0: string[], paramarg1: number, paramarg2: number): void;
    static sort(paramarg0: number[]): void;
    static sort(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static sort(paramarg0: number[]): void;
    static sort(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static sort(paramarg0: number[]): void;
    static sort(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static sort(paramarg0: number[]): void;
    static sort(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static sort(paramarg0: number[]): void;
    static sort(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static sortWith(paramarg0: Object | null, paramarg1: (param0: Object | null) => kotlin.Boolean): void;
    static sortWith(paramarg0: Object | null, paramarg1: (param0: Object | null) => kotlin.Boolean, paramarg2: number, paramarg3: number): void;
    static toSortedSet(paramarg0: Object | null): (Object | null)[];
    static toSortedSet(paramarg0: Object | null, paramarg1: (param0: Object | null) => kotlin.Boolean): (Object | null)[];
    static toSortedSet(paramarg0: (Object | null)[]): boolean[];
    static toSortedSet(paramarg0: number[]): number[];
    static toSortedSet(paramarg0: string[]): string[];
    static toSortedSet(paramarg0: number[]): number[];
    static toSortedSet(paramarg0: number[]): number[];
    static toSortedSet(paramarg0: number[]): number[];
    static toSortedSet(paramarg0: number[]): number[];
    static toSortedSet(paramarg0: number[]): number[];
    static toTypedArray(paramarg0: E[]): Object | null;
    static toTypedArray(paramarg0: (Object | null)[]): (Object | null)[];
    static toTypedArray(paramarg0: number[]): (Object | null)[];
    static toTypedArray(paramarg0: string[]): (Object | null)[];
    static toTypedArray(paramarg0: number[]): (Object | null)[];
    static toTypedArray(paramarg0: number[]): (Object | null)[];
    static toTypedArray(paramarg0: number[]): (Object | null)[];
    static toTypedArray(paramarg0: number[]): (Object | null)[];
    static toTypedArray(paramarg0: number[]): (Object | null)[];
    static unzip(paramarg0: Object | null): Pair<Object, Object>;
}