import type { Appendable } from '../../java/lang/Appendable.d.ts'
import type { Class } from '../../java/lang/Class.d.ts'
import type { Comparator } from '../../java/util/Comparator.d.ts'
import type { Enumeration } from '../../java/util/Enumeration.d.ts'
import type { Random } from '../../java/util/Random.d.ts'
import type { Object } from '../../java/lang/Object.d.ts'
import type { CharSequence } from '../../java/lang/CharSequence.d.ts'
import type { Comparable } from '../../java/lang/Comparable.d.ts'
import type { Pair } from '../../kotlin/Pair.d.ts'
import type { CollectionsKt___CollectionsJvmKt } from '../../kotlin/collections/CollectionsKt___CollectionsJvmKt.d.ts'
import type { Grouping } from '../../kotlin/collections/Grouping.d.ts'
import type { IndexedValue } from '../../kotlin/collections/IndexedValue.d.ts'
import type { Iterator } from '../../java/util/Iterator.d.ts'
import type { Random as Random_2 } from '../../kotlin/random/Random.d.ts'
import type { Sequence } from '../../kotlin/sequences/Sequence.d.ts'
export class CollectionsKt___CollectionsKt extends CollectionsKt___CollectionsJvmKt {
    static addAll(paramarg0: Object[], paramarg1: Object | null): boolean;
    static addAll(paramarg0: Object[], paramarg1: (Object | null)[]): boolean;
    static addAll(paramarg0: Object[], paramarg1: Sequence<Object>): boolean;
    static all(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): boolean;
    static any(paramarg0: (Object | null)[]): boolean;
    static any(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): boolean;
    static arrayListOf(...paramarg0: Object | null): (Object | null)[];
    static asCollection(paramarg0: Object | null, paramarg1: boolean): (Object | null)[];
    static asReversed(paramarg0: (Object | null)[]): (Object | null)[];
    static asReversedMutable(paramarg0: (Object | null)[]): (Object | null)[];
    static asSequence(paramarg0: (Object | null)[]): Sequence<Object>;
    static associate(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Pair<Object, Object>): Map<Object | null, Object | null>;
    static associateBy(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null, paramarg2: (param0: Object) => Object | null): Map<Object | null, Object | null>;
    static associateBy(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): Map<Object | null, Object | null>;
    static associateByTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object) => Object | null): Object | null;
    static associateByTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object) => Object | null, paramarg3: (param0: Object) => Object | null): Object | null;
    static associateTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object) => Pair<Object, Object>): Object | null;
    static associateWith(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): Map<Object | null, Object | null>;
    static associateWithTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object) => Object | null): Object | null;
    static averageOfByte(paramarg0: number[]): number;
    static averageOfDouble(paramarg0: number[]): number;
    static averageOfFloat(paramarg0: number[]): number;
    static averageOfInt(paramarg0: number[]): number;
    static averageOfLong(paramarg0: number[]): number;
    static averageOfShort(paramarg0: number[]): number;
    static binarySearch(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: number, paramarg3: number): number;
    static binarySearch(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object) => boolean, paramarg3: number, paramarg4: number): number;
    static binarySearch(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: (param0: Object) => number): number;
    static binarySearchBy(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: number, paramarg3: number, paramarg4: (param0: Object) => Object | null): number;
    static build(paramarg0: (Object | null)[]): (Object | null)[];
    static chunked(paramarg0: (Object | null)[], paramarg1: number, paramarg2: (param0: Object) => Object | null): (Object | null)[];
    static chunked(paramarg0: (Object | null)[], paramarg1: number): (Object | null)[][];
    static collectionSizeOrDefault(paramarg0: (Object | null)[], paramarg1: number): number;
    static collectionSizeOrNull(paramarg0: (Object | null)[]): number;
    static collectionToArrayCommonImpl(paramarg0: Object[], paramarg1: Object | null): Object | null;
    static collectionToArrayCommonImpl(paramarg0: Object[]): (Object | null)[];
    static contains(paramarg0: (Object | null)[], paramarg1: Object | null): boolean;
    static convertToListIfNotCollection(paramarg0: (Object | null)[]): (Object | null)[];
    static copyToArrayOfAny(paramarg0: Object | null, paramarg1: boolean): (Object | null)[];
    static count(paramarg0: (Object | null)[]): number;
    static count(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): number;
    static createListBuilder(): (Object | null)[];
    static createListBuilder(paramarg0: number): (Object | null)[];
    static distinct(paramarg0: (Object | null)[]): (Object | null)[];
    static distinctBy(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): (Object | null)[];
    static drop(paramarg0: (Object | null)[], paramarg1: number): (Object | null)[];
    static dropLast(paramarg0: (Object | null)[], paramarg1: number): (Object | null)[];
    static dropLastWhile(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): (Object | null)[];
    static dropWhile(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): (Object | null)[];
    static elementAt(paramarg0: (Object | null)[], paramarg1: number): Object | null;
    static elementAtOrElse(paramarg0: (Object | null)[], paramarg1: number, paramarg2: (param0: Object) => Object | null): Object | null;
    static elementAtOrNull(paramarg0: (Object | null)[], paramarg1: number): Object | null;
    static emptyList(): (Object | null)[];
    static filter(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): (Object | null)[];
    static filterIndexed(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object) => boolean): (Object | null)[];
    static filterIndexedTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => boolean): Object | null;
    static filterIsInstance(paramarg0: Object[], paramarg1: Class<Object>): (Object | null)[];
    static filterIsInstance(paramarg0: Object[]): (Object | null)[];
    static filterIsInstanceTo(paramarg0: Object[], paramarg1: Object | null, paramarg2: Class<Object>): Object | null;
    static filterIsInstanceTo(paramarg0: Object[], paramarg1: Object | null): Object | null;
    static filterNot(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): (Object | null)[];
    static filterNotNull(paramarg0: (Object | null)[]): (Object | null)[];
    static filterNotNullTo(paramarg0: (Object | null)[], paramarg1: Object | null): Object | null;
    static filterNotTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object) => boolean): Object | null;
    static filterTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object) => boolean): Object | null;
    static first(paramarg0: (Object | null)[]): Object | null;
    static first(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object | null;
    static first(paramarg0: (Object | null)[]): Object | null;
    static firstOrNull(paramarg0: (Object | null)[]): Object | null;
    static firstOrNull(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object | null;
    static firstOrNull(paramarg0: (Object | null)[]): Object | null;
    static flatMap(paramarg0: (Object | null)[], paramarg1: (param0: Object) => (Object | null)[]): (Object | null)[];
    static flatMapSequence(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Sequence<Object>): (Object | null)[];
    static flatMapSequenceTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object) => Sequence<Object>): Object | null;
    static flatMapTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object) => (Object | null)[]): Object | null;
    static flatten(paramarg0: (Object | null)[][]): (Object | null)[];
    static fold(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => Object | null): Object | null;
    static foldIndexed(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object, param1: Object, param2: Object) => Object | null): Object | null;
    static foldRight(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => Object | null): Object | null;
    static foldRightIndexed(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object, param1: Object, param2: Object) => Object | null): Object | null;
    static forEach(paramarg0: Iterator<Object>, paramarg1: (param0: Object) => void): void;
    static forEach(paramarg0: (Object | null)[], paramarg1: (param0: Object) => void): void;
    static forEachIndexed(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object) => void): void;
    static getIndices(paramarg0: Object[]): { start: number; endInclusive: number; step: number };
    static getLastIndex(paramarg0: (Object | null)[]): number;
    static getOrNull(paramarg0: (Object | null)[], paramarg1: number): Object | null;
    static groupBy(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null, paramarg2: (param0: Object) => Object | null): Map<Object | null, (Object | null)[]>;
    static groupBy(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): Map<Object | null, (Object | null)[]>;
    static groupByTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object) => Object | null): Object | null;
    static groupByTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object) => Object | null, paramarg3: (param0: Object) => Object | null): Object | null;
    static groupingBy(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): Grouping<Object, Object>;
    static indexOf(paramarg0: (Object | null)[], paramarg1: Object | null): number;
    static indexOf(paramarg0: (Object | null)[], paramarg1: Object | null): number;
    static indexOfFirst(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): number;
    static indexOfFirst(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): number;
    static indexOfLast(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): number;
    static indexOfLast(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): number;
    static intersect(paramarg0: (Object | null)[], paramarg1: (Object | null)[]): (Object | null)[];
    static isSorted(paramarg0: (Object | null)[]): boolean;
    static isSortedBy(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): boolean;
    static isSortedByDescending(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): boolean;
    static isSortedDescending(paramarg0: (Object | null)[]): boolean;
    static isSortedWith(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): boolean;
    static iterator(paramarg0: Enumeration<Object>): Iterator<Object>;
    static joinTo(paramarg0: (Object | null)[], paramarg1: Appendable | null, paramarg2: CharSequence, paramarg3: CharSequence, paramarg4: CharSequence, paramarg5: number, paramarg6: CharSequence, paramarg7: (param0: Object) => CharSequence): Appendable | null;
    static joinToString(paramarg0: (Object | null)[], paramarg1: CharSequence, paramarg2: CharSequence, paramarg3: CharSequence, paramarg4: number, paramarg5: CharSequence, paramarg6: (param0: Object) => CharSequence): string;
    static last(paramarg0: (Object | null)[]): Object | null;
    static last(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object | null;
    static last(paramarg0: (Object | null)[]): Object | null;
    static last(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object | null;
    static lastIndexOf(paramarg0: (Object | null)[], paramarg1: Object | null): number;
    static lastIndexOf(paramarg0: (Object | null)[], paramarg1: Object | null): number;
    static lastOrNull(paramarg0: (Object | null)[]): Object | null;
    static lastOrNull(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object | null;
    static lastOrNull(paramarg0: (Object | null)[]): Object | null;
    static lastOrNull(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object | null;
    static listOf(paramarg0: Object | null): (Object | null)[];
    static listOf(...paramarg0: Object | null): (Object | null)[];
    static listOfNotNull(paramarg0: Object | null): (Object | null)[];
    static listOfNotNull(...paramarg0: Object | null): (Object | null)[];
    static map(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): (Object | null)[];
    static mapIndexed(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static mapIndexedNotNull(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static mapIndexedNotNullTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => Object | null): Object | null;
    static mapIndexedTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => Object | null): Object | null;
    static mapNotNull(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): (Object | null)[];
    static mapNotNullTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object) => Object | null): Object | null;
    static mapTo(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object) => Object | null): Object | null;
    static max(paramarg0: (Object | null)[]): Comparable<Object>;
    static max(paramarg0: (Object | null)[]): number;
    static max(paramarg0: (Object | null)[]): number;
    static maxBy(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): Object | null;
    static maxByOrNull(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): Object | null;
    static maxByOrThrow(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): Object | null;
    static maxOrNull(paramarg0: (Object | null)[]): Object | null;
    static maxOrNull(paramarg0: number[]): number;
    static maxOrNull(paramarg0: number[]): number;
    static maxOrThrow(paramarg0: (Object | null)[]): Object | null;
    static maxOrThrow(paramarg0: number[]): number;
    static maxOrThrow(paramarg0: number[]): number;
    static maxWith(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object;
    static maxWithOrNull(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object | null;
    static maxWithOrThrow(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object | null;
    static min(paramarg0: (Object | null)[]): Comparable<Object>;
    static min(paramarg0: (Object | null)[]): number;
    static min(paramarg0: (Object | null)[]): number;
    static minBy(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): Object | null;
    static minByOrNull(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): Object | null;
    static minByOrThrow(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): Object | null;
    static minOrNull(paramarg0: (Object | null)[]): Object | null;
    static minOrNull(paramarg0: number[]): number;
    static minOrNull(paramarg0: number[]): number;
    static minOrThrow(paramarg0: (Object | null)[]): Object | null;
    static minOrThrow(paramarg0: number[]): number;
    static minOrThrow(paramarg0: number[]): number;
    static minWith(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object;
    static minWithOrNull(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object | null;
    static minWithOrThrow(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object | null;
    static minus(paramarg0: (Object | null)[], paramarg1: Object | null): (Object | null)[];
    static minus(paramarg0: (Object | null)[], paramarg1: Object | null): (Object | null)[];
    static minus(paramarg0: (Object | null)[], paramarg1: (Object | null)[]): (Object | null)[];
    static minus(paramarg0: (Object | null)[], paramarg1: Sequence<Object>): (Object | null)[];
    static mutableListOf(...paramarg0: Object | null): (Object | null)[];
    static none(paramarg0: (Object | null)[]): boolean;
    static none(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): boolean;
    static onEach(paramarg0: Object | null, paramarg1: (param0: Object) => void): Object | null;
    static onEachIndexed(paramarg0: Object | null, paramarg1: (param0: Object, param1: Object) => void): Object | null;
    static optimizeReadOnlyList(paramarg0: (Object | null)[]): (Object | null)[];
    static partition(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Pair<(Object | null)[], (Object | null)[]>;
    static plus(paramarg0: (Object | null)[], paramarg1: Object | null): (Object | null)[];
    static plus(paramarg0: (Object | null)[], paramarg1: Object | null): (Object | null)[];
    static plus(paramarg0: (Object | null)[], paramarg1: (Object | null)[]): (Object | null)[];
    static plus(paramarg0: (Object | null)[], paramarg1: Sequence<Object>): (Object | null)[];
    static plus(paramarg0: (Object | null)[], paramarg1: Object | null): (Object | null)[];
    static plus(paramarg0: (Object | null)[], paramarg1: Object | null): (Object | null)[];
    static plus(paramarg0: (Object | null)[], paramarg1: (Object | null)[]): (Object | null)[];
    static plus(paramarg0: (Object | null)[], paramarg1: Sequence<Object>): (Object | null)[];
    static random(paramarg0: (Object | null)[], paramarg1: Random_2): Object | null;
    static randomOrNull(paramarg0: (Object | null)[], paramarg1: Random_2): Object | null;
    static reduce(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object) => Object | null): Object | null;
    static reduceIndexed(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object, param2: Object) => Object | null): Object | null;
    static reduceIndexedOrNull(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object, param2: Object) => Object | null): Object | null;
    static reduceOrNull(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object) => Object | null): Object | null;
    static reduceRight(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object) => Object | null): Object | null;
    static reduceRightIndexed(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object, param2: Object) => Object | null): Object | null;
    static reduceRightIndexedOrNull(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object, param2: Object) => Object | null): Object | null;
    static reduceRightOrNull(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object) => Object | null): Object | null;
    static removeAll(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): boolean;
    static removeAll(paramarg0: Object[], paramarg1: Object | null): boolean;
    static removeAll(paramarg0: Object[], paramarg1: (Object | null)[]): boolean;
    static removeAll(paramarg0: Object[], paramarg1: Sequence<Object>): boolean;
    static removeAll(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): boolean;
    static removeFirst(paramarg0: (Object | null)[]): Object | null;
    static removeFirstOrNull(paramarg0: (Object | null)[]): Object | null;
    static removeLast(paramarg0: (Object | null)[]): Object | null;
    static removeLastOrNull(paramarg0: (Object | null)[]): Object | null;
    static requireNoNulls(paramarg0: (Object | null)[]): (Object | null)[];
    static requireNoNulls(paramarg0: (Object | null)[]): (Object | null)[];
    static retainAll(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): boolean;
    static retainAll(paramarg0: Object[], paramarg1: Object | null): boolean;
    static retainAll(paramarg0: Object[], paramarg1: (Object | null)[]): boolean;
    static retainAll(paramarg0: Object[], paramarg1: Sequence<Object>): boolean;
    static retainAll(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): boolean;
    static reverse(paramarg0: (Object | null)[]): void;
    static reversed(paramarg0: (Object | null)[]): (Object | null)[];
    static runningFold(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static runningFoldIndexed(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object, param1: Object, param2: Object) => Object | null): (Object | null)[];
    static runningReduce(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static runningReduceIndexed(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object, param2: Object) => Object | null): (Object | null)[];
    static scan(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static scanIndexed(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object, param1: Object, param2: Object) => Object | null): (Object | null)[];
    static shuffle(paramarg0: (Object | null)[], paramarg1: Random_2): void;
    static shuffled(paramarg0: (Object | null)[]): (Object | null)[];
    static shuffled(paramarg0: (Object | null)[], paramarg1: Random): (Object | null)[];
    static shuffled(paramarg0: (Object | null)[], paramarg1: Random_2): (Object | null)[];
    static single(paramarg0: (Object | null)[]): Object | null;
    static single(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object | null;
    static single(paramarg0: (Object | null)[]): Object | null;
    static singleOrNull(paramarg0: (Object | null)[]): Object | null;
    static singleOrNull(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): Object | null;
    static singleOrNull(paramarg0: (Object | null)[]): Object | null;
    static slice(paramarg0: (Object | null)[], paramarg1: number[]): (Object | null)[];
    static slice(paramarg0: (Object | null)[], paramarg1: { start: number; endInclusive: number; step: number }): (Object | null)[];
    static sort(paramarg0: (Object | null)[]): void;
    static sortBy(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): void;
    static sortByDescending(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): void;
    static sortDescending(paramarg0: (Object | null)[]): void;
    static sortWith(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): void;
    static sorted(paramarg0: (Object | null)[]): (Object | null)[];
    static sortedBy(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): (Object | null)[];
    static sortedByDescending(paramarg0: (Object | null)[], paramarg1: (param0: Object) => Object | null): (Object | null)[];
    static sortedDescending(paramarg0: (Object | null)[]): (Object | null)[];
    static sortedWith(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): (Object | null)[];
    static subtract(paramarg0: (Object | null)[], paramarg1: (Object | null)[]): (Object | null)[];
    static sumBy(paramarg0: (Object | null)[], paramarg1: (param0: Object) => number): number;
    static sumByDouble(paramarg0: (Object | null)[], paramarg1: (param0: Object) => number): number;
    static sumOfByte(paramarg0: number[]): number;
    static sumOfDouble(paramarg0: number[]): number;
    static sumOfFloat(paramarg0: number[]): number;
    static sumOfInt(paramarg0: number[]): number;
    static sumOfLong(paramarg0: number[]): number;
    static sumOfShort(paramarg0: number[]): number;
    static take(paramarg0: (Object | null)[], paramarg1: number): (Object | null)[];
    static takeLast(paramarg0: (Object | null)[], paramarg1: number): (Object | null)[];
    static takeLastWhile(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): (Object | null)[];
    static takeWhile(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): (Object | null)[];
    static terminateCollectionToArray(paramarg0: number, paramarg1: Object | null): Object | null;
    static throwCountOverflow(): void;
    static throwIndexOverflow(): void;
    static toBooleanArray(paramarg0: boolean[]): (Object | null)[];
    static toByteArray(paramarg0: number[]): number[];
    static toCharArray(paramarg0: string[]): string[];
    static toCollection(paramarg0: (Object | null)[], paramarg1: Object | null): Object | null;
    static toDoubleArray(paramarg0: number[]): number[];
    static toFloatArray(paramarg0: number[]): number[];
    static toHashSet(paramarg0: (Object | null)[]): (Object | null)[];
    static toIntArray(paramarg0: number[]): number[];
    static toList(paramarg0: (Object | null)[]): (Object | null)[];
    static toLongArray(paramarg0: number[]): number[];
    static toMutableList(paramarg0: (Object | null)[]): (Object | null)[];
    static toMutableList(paramarg0: (Object | null)[]): (Object | null)[];
    static toMutableSet(paramarg0: (Object | null)[]): (Object | null)[];
    static toSet(paramarg0: (Object | null)[]): (Object | null)[];
    static toShortArray(paramarg0: number[]): number[];
    static toSortedSet(paramarg0: (Object | null)[]): (Object | null)[];
    static toSortedSet(paramarg0: (Object | null)[], paramarg1: (param0: Object) => boolean): (Object | null)[];
    static union(paramarg0: (Object | null)[], paramarg1: (Object | null)[]): (Object | null)[];
    static unzip(paramarg0: Pair<Object, Object>[]): Pair<(Object | null)[], (Object | null)[]>;
    static windowed(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: (param0: Object) => Object | null): (Object | null)[];
    static windowed(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: boolean): (Object | null)[][];
    static withIndex(paramarg0: (Object | null)[]): IndexedValue<Object>[];
    static withIndex(paramarg0: Iterator<Object>): Iterator<IndexedValue<Object>>;
    static zip(paramarg0: (Object | null)[], paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static zip(paramarg0: (Object | null)[], paramarg1: (Object | null)[], paramarg2: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static zip(paramarg0: (Object | null)[], paramarg1: Object | null): Pair<Object, Object>[];
    static zip(paramarg0: (Object | null)[], paramarg1: (Object | null)[]): Pair<Object, Object>[];
    static zipWithNext(paramarg0: (Object | null)[], paramarg1: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static zipWithNext(paramarg0: (Object | null)[]): Pair<Object, Object>[];
}