import type { Appendable } from '../../java/lang/Appendable.d.ts'
import type { Class } from '../../java/lang/Class.d.ts'
import type { Comparator } from '../../java/util/Comparator.d.ts'
import type { Enumeration } from '../../java/util/Enumeration.d.ts'
import type { Random } from '../../java/util/Random.d.ts'
import type { Object } from '../../java/lang/Object.d.ts'
import type { CharSequence } from '../../java/lang/CharSequence.d.ts'
import type { Comparable } from '../../java/lang/Comparable.d.ts'
import type { Pair } from '../../kotlin/Pair.d.ts'
import type { CollectionsKt___CollectionsKt } from '../../kotlin/collections/CollectionsKt___CollectionsKt.d.ts'
import type { Grouping } from '../../kotlin/collections/Grouping.d.ts'
import type { IndexedValue } from '../../kotlin/collections/IndexedValue.d.ts'
import type { Iterator } from '../../java/util/Iterator.d.ts'
import type { Random as Random_2 } from '../../kotlin/random/Random.d.ts'
import type { Sequence } from '../../kotlin/sequences/Sequence.d.ts'
export class CollectionsKt extends CollectionsKt___CollectionsKt {
    static addAll<T extends unknown>(self: T[], elements: T[]): boolean;
    static addAll<T extends unknown>(self: T[], elements: Sequence<T>): boolean;
    static all<T extends unknown>(self: T[], predicate: (param0: T) => boolean): boolean;
    static any<T extends unknown>(self: T[]): boolean;
    static any<T extends unknown>(self: T[], predicate: (param0: T) => boolean): boolean;
    static arrayListOf<T extends unknown>(...elements: T[]): T[];
    static asCollection<T extends unknown>(self: T[], isVarargs: boolean): T[];
    static asReversed<T extends unknown>(self: T[]): T[];
    static asReversedMutable<T extends unknown>(self: T[]): T[];
    static asSequence<T extends unknown>(self: T[]): Sequence<T>;
    static associate<K extends unknown, V extends unknown, T extends unknown>(self: T[], transform: (param0: T) => Pair<K, V>): Map<K, V>;
    static associateBy<K extends unknown, V extends unknown, T extends unknown>(self: T[], keySelector: (param0: T) => K, valueTransform: (param0: T) => V): Map<K, V>;
    static associateBy<K extends unknown, T extends unknown>(self: T[], keySelector: (param0: T) => K): Map<K, T>;
    static associateByTo<M extends Map<K, T>, T extends unknown, K extends unknown>(self: T[], destination: M, keySelector: (param0: T) => K): M;
    static associateByTo<M extends Map<K, V>, T extends unknown, K extends unknown, V extends unknown>(self: T[], destination: M, keySelector: (param0: T) => K, valueTransform: (param0: T) => V): M;
    static associateTo<M extends Map<K, V>, T extends unknown, K extends unknown, V extends unknown>(self: T[], destination: M, transform: (param0: T) => Pair<K, V>): M;
    static associateWith<K extends unknown, V extends unknown>(self: K[], valueSelector: (param0: K) => V): Map<K, V>;
    static associateWithTo<M extends Map<K, V>, K extends unknown, V extends unknown>(self: K[], destination: M, valueSelector: (param0: K) => V): M;
    static averageOfByte(self: number[]): number;
    static averageOfDouble(self: number[]): number;
    static averageOfFloat(self: number[]): number;
    static averageOfInt(self: number[]): number;
    static averageOfLong(self: number[]): number;
    static averageOfShort(self: number[]): number;
    static binarySearch<T extends Comparable<T>>(self: (T | null)[], element: T | null, fromIndex: number, toIndex: number): number;
    static binarySearch<T extends unknown>(self: T[], element: T, comparator: (param0: T, param1: T) => number, fromIndex: number, toIndex: number): number;
    static binarySearch<T extends unknown>(self: T[], fromIndex: number, toIndex: number, comparison: (param0: T) => number): number;
    static binarySearchBy<T extends unknown, K extends Comparable<K>>(self: T[], key: K | null, fromIndex: number, toIndex: number, selector: (param0: T) => K | null): number;
    static build<E extends unknown>(builder: E[]): E[];
    static chunked<R extends unknown, T extends unknown>(self: T[], size: number, transform: (param0: T[]) => R): R[];
    static chunked<T extends unknown>(self: T[], size: number): T[][];
    static collectionSizeOrDefault<T extends unknown>(self: T[], default_: number): number;
    static collectionSizeOrNull<T extends unknown>(self: T[]): number | null;
    static collectionToArrayCommonImpl<T extends unknown>(collection: (Object | null)[], array: T[]): T[];
    static collectionToArrayCommonImpl(collection: (Object | null)[]): (Object | null)[];
    static contains<T extends unknown>(self: T[], element: T): boolean;
    static convertToListIfNotCollection<T extends unknown>(self: T[]): T[];
    static copyToArrayOfAny<T extends unknown>(self: T[], isVarargs: boolean): (Object | null)[];
    static count<T extends unknown>(self: T[]): number;
    static count<T extends unknown>(self: T[], predicate: (param0: T) => boolean): number;
    static createListBuilder<E extends unknown>(): E[];
    static createListBuilder<E extends unknown>(capacity: number): E[];
    static distinct<T extends unknown>(self: T[]): T[];
    static distinctBy<T extends unknown, K extends unknown>(self: T[], selector: (param0: T) => K): T[];
    static drop<T extends unknown>(self: T[], n: number): T[];
    static dropLast<T extends unknown>(self: T[], n: number): T[];
    static dropLastWhile<T extends unknown>(self: T[], predicate: (param0: T) => boolean): T[];
    static dropWhile<T extends unknown>(self: T[], predicate: (param0: T) => boolean): T[];
    static elementAt<T extends unknown>(self: T[], index: number): T;
    static elementAtOrElse<T extends unknown>(self: T[], index: number, defaultValue: (param0: number) => T): T;
    static elementAtOrNull<T extends unknown>(self: T[], index: number): T | null;
    static emptyList<T extends unknown>(): T[];
    static filter<T extends unknown>(self: T[], predicate: (param0: T) => boolean): T[];
    static filterIndexed<T extends unknown>(self: T[], predicate: (param0: number, param1: T) => boolean): T[];
    static filterIndexedTo<C extends T[], T extends unknown>(self: T[], destination: C, predicate: (param0: number, param1: T) => boolean): C;
    static filterIsInstance<R extends unknown>(self: (Object | null)[], klass: Class<R>): R[];
    static filterIsInstance<R extends unknown>(self: (Object | null)[]): R[];
    static filterIsInstanceTo<C extends R[], R extends unknown>(self: (Object | null)[], destination: C, klass: Class<R>): C;
    static filterIsInstanceTo<C extends R[]>(self: (Object | null)[], destination: C): C;
    static filterNot<T extends unknown>(self: T[], predicate: (param0: T) => boolean): T[];
    static filterNotNull<T extends unknown>(self: (T | null)[]): T[];
    static filterNotNullTo<C extends T[], T extends unknown>(self: (T | null)[], destination: C): C;
    static filterNotTo<C extends T[], T extends unknown>(self: T[], destination: C, predicate: (param0: T) => boolean): C;
    static filterTo<C extends T[], T extends unknown>(self: T[], destination: C, predicate: (param0: T) => boolean): C;
    static first<T extends unknown>(self: T[]): T;
    static first<T extends unknown>(self: T[], predicate: (param0: T) => boolean): T;
    static firstOrNull<T extends unknown>(self: T[]): T | null;
    static firstOrNull<T extends unknown>(self: T[], predicate: (param0: T) => boolean): T | null;
    static flatMap<R extends unknown, T extends unknown>(self: T[], transform: (param0: T) => R[]): R[];
    static flatMapSequence<R extends unknown, T extends unknown>(self: T[], transform: (param0: T) => Sequence<R>): R[];
    static flatMapSequenceTo<C extends R[], T extends unknown, R extends unknown>(self: T[], destination: C, transform: (param0: T) => Sequence<R>): C;
    static flatMapTo<C extends R[], T extends unknown, R extends unknown>(self: T[], destination: C, transform: (param0: T) => R[]): C;
    static flatten<T extends unknown>(self: T[][]): T[];
    static fold<R extends unknown, T extends unknown>(self: T[], initial: R, operation: (param0: R, param1: T) => R): R;
    static foldIndexed<R extends unknown, T extends unknown>(self: T[], initial: R, operation: (param0: number, param1: R, param2: T) => R): R;
    static foldRight<R extends unknown, T extends unknown>(self: T[], initial: R, operation: (param0: T, param1: R) => R): R;
    static foldRightIndexed<R extends unknown, T extends unknown>(self: T[], initial: R, operation: (param0: number, param1: T, param2: R) => R): R;
    static forEach<T extends unknown>(self: Iterator<T>, operation: (param0: T) => void): void;
    static forEach<T extends unknown>(self: T[], action: (param0: T) => void): void;
    static forEachIndexed<T extends unknown>(self: T[], action: (param0: number, param1: T) => void): void;
    static getIndices(paramarg0: Object[]): { start: number; endInclusive: number; step: number };
    static getLastIndex<T extends unknown>(paramarg0: T[]): number;
    static getOrNull<T extends unknown>(self: T[], index: number): T | null;
    static groupBy<K extends unknown, V extends unknown, T extends unknown>(self: T[], keySelector: (param0: T) => K, valueTransform: (param0: T) => V): Map<K, V[]>;
    static groupBy<K extends unknown, T extends unknown>(self: T[], keySelector: (param0: T) => K): Map<K, T[]>;
    static groupByTo<M extends Map<K, T[]>, T extends unknown, K extends unknown>(self: T[], destination: M, keySelector: (param0: T) => K): M;
    static groupByTo<M extends Map<K, V[]>, T extends unknown, K extends unknown, V extends unknown>(self: T[], destination: M, keySelector: (param0: T) => K, valueTransform: (param0: T) => V): M;
    static groupingBy<T extends unknown, K extends unknown>(self: T[], keySelector: (param0: T) => K): Grouping<T, K>;
    static indexOf<T extends unknown>(self: T[], element: T): number;
    static indexOfFirst<T extends unknown>(self: T[], predicate: (param0: T) => boolean): number;
    static indexOfLast<T extends unknown>(self: T[], predicate: (param0: T) => boolean): number;
    static intersect<T extends unknown>(self: T[], other: T[]): T[];
    static isSorted<T extends Comparable<T>>(self: T[]): boolean;
    static isSortedBy<T extends unknown, R extends Comparable<R>>(self: T[], selector: (param0: T) => R | null): boolean;
    static isSortedByDescending<T extends unknown, R extends Comparable<R>>(self: T[], selector: (param0: T) => R | null): boolean;
    static isSortedDescending<T extends Comparable<T>>(self: T[]): boolean;
    static isSortedWith<T extends unknown>(self: T[], comparator: (param0: T, param1: T) => number): boolean;
    static iterator<T extends unknown>(self: Enumeration<T>): Iterator<T>;
    static joinTo<A extends Appendable, T extends unknown>(self: T[], buffer: A, separator: CharSequence, prefix: CharSequence, postfix: CharSequence, limit: number, truncated: CharSequence, transform: ((param0: T) => CharSequence) | null): A;
    static joinToString<T extends unknown>(self: T[], separator: CharSequence, prefix: CharSequence, postfix: CharSequence, limit: number, truncated: CharSequence, transform: ((param0: T) => CharSequence) | null): string;
    static last<T extends unknown>(self: T[]): T;
    static last<T extends unknown>(self: T[], predicate: (param0: T) => boolean): T;
    static lastIndexOf<T extends unknown>(self: T[], element: T): number;
    static lastOrNull<T extends unknown>(self: T[]): T | null;
    static lastOrNull<T extends unknown>(self: T[], predicate: (param0: T) => boolean): T | null;
    static listOf<T extends unknown>(element: T): T[];
    static listOf<T extends unknown>(...elements: T[]): T[];
    static listOfNotNull<T extends unknown>(element: T | null): T[];
    static listOfNotNull<T extends unknown>(...elements: (T | null)[]): T[];
    static map<R extends unknown, T extends unknown>(self: T[], transform: (param0: T) => R): R[];
    static mapIndexed<R extends unknown, T extends unknown>(self: T[], transform: (param0: number, param1: T) => R): R[];
    static mapIndexedNotNull<R extends unknown, T extends unknown>(self: T[], transform: (param0: number, param1: T) => R | null): R[];
    static mapIndexedNotNullTo<C extends R[], T extends unknown, R extends unknown>(self: T[], destination: C, transform: (param0: number, param1: T) => R | null): C;
    static mapIndexedTo<C extends R[], T extends unknown, R extends unknown>(self: T[], destination: C, transform: (param0: number, param1: T) => R): C;
    static mapNotNull<R extends unknown, T extends unknown>(self: T[], transform: (param0: T) => R | null): R[];
    static mapNotNullTo<C extends R[], T extends unknown, R extends unknown>(self: T[], destination: C, transform: (param0: T) => R | null): C;
    static mapTo<C extends R[], T extends unknown, R extends unknown>(self: T[], destination: C, transform: (param0: T) => R): C;
    static max<T extends Comparable<T>>(self: T[]): T | null;
    static max(self: number[]): number | null;
    static maxBy<T extends unknown, R extends Comparable<R>>(self: T[], selector: (param0: T) => R): T | null;
    static maxByOrNull<T extends unknown, R extends Comparable<R>>(self: T[], selector: (param0: T) => R): T | null;
    static maxByOrThrow<T extends unknown, R extends Comparable<R>>(self: T[], selector: (param0: T) => R): T;
    static maxOrNull<T extends Comparable<T>>(self: T[]): T | null;
    static maxOrNull(self: number[]): number | null;
    static maxOrThrow<T extends Comparable<T>>(self: T[]): T;
    static maxOrThrow(self: number[]): number;
    static maxWith<T extends unknown>(self: T[], comparator: (param0: T, param1: T) => number): T | null;
    static maxWithOrNull<T extends unknown>(self: T[], comparator: (param0: T, param1: T) => number): T | null;
    static maxWithOrThrow<T extends unknown>(self: T[], comparator: (param0: T, param1: T) => number): T;
    static min<T extends Comparable<T>>(self: T[]): T | null;
    static min(self: number[]): number | null;
    static minBy<T extends unknown, R extends Comparable<R>>(self: T[], selector: (param0: T) => R): T | null;
    static minByOrNull<T extends unknown, R extends Comparable<R>>(self: T[], selector: (param0: T) => R): T | null;
    static minByOrThrow<T extends unknown, R extends Comparable<R>>(self: T[], selector: (param0: T) => R): T;
    static minOrNull<T extends Comparable<T>>(self: T[]): T | null;
    static minOrNull(self: number[]): number | null;
    static minOrThrow<T extends Comparable<T>>(self: T[]): T;
    static minOrThrow(self: number[]): number;
    static minWith<T extends unknown>(self: T[], comparator: (param0: T, param1: T) => number): T | null;
    static minWithOrNull<T extends unknown>(self: T[], comparator: (param0: T, param1: T) => number): T | null;
    static minWithOrThrow<T extends unknown>(self: T[], comparator: (param0: T, param1: T) => number): T;
    static minus<T extends unknown>(self: T[], element: T): T[];
    static minus<T extends unknown>(self: T[], elements: T[]): T[];
    static minus<T extends unknown>(self: T[], elements: Sequence<T>): T[];
    static mutableListOf<T extends unknown>(...elements: T[]): T[];
    static none<T extends unknown>(self: T[]): boolean;
    static none<T extends unknown>(self: T[], predicate: (param0: T) => boolean): boolean;
    static onEach<C extends T[], T extends unknown>(self: C, action: (param0: T) => void): C;
    static onEachIndexed<C extends T[], T extends unknown>(self: C, action: (param0: number, param1: T) => void): C;
    static optimizeReadOnlyList<T extends unknown>(self: T[]): T[];
    static partition<T extends unknown>(self: T[], predicate: (param0: T) => boolean): Pair<T[], T[]>;
    static plus<T extends unknown>(self: T[], element: T): T[];
    static plus<T extends unknown>(self: T[], elements: T[]): T[];
    static plus<T extends unknown>(self: T[], elements: Sequence<T>): T[];
    static random<T extends unknown>(self: T[], random: Random_2): T;
    static randomOrNull<T extends unknown>(self: T[], random: Random_2): T | null;
    static reduce<S extends unknown, T extends S>(self: T[], operation: (param0: S, param1: T) => S): S;
    static reduceIndexed<S extends unknown, T extends S>(self: T[], operation: (param0: number, param1: S, param2: T) => S): S;
    static reduceIndexedOrNull<S extends unknown, T extends S>(self: T[], operation: (param0: number, param1: S, param2: T) => S): S | null;
    static reduceOrNull<S extends unknown, T extends S>(self: T[], operation: (param0: S, param1: T) => S): S | null;
    static reduceRight<S extends unknown, T extends S>(self: T[], operation: (param0: T, param1: S) => S): S;
    static reduceRightIndexed<S extends unknown, T extends S>(self: T[], operation: (param0: number, param1: T, param2: S) => S): S;
    static reduceRightIndexedOrNull<S extends unknown, T extends S>(self: T[], operation: (param0: number, param1: T, param2: S) => S): S | null;
    static reduceRightOrNull<S extends unknown, T extends S>(self: T[], operation: (param0: T, param1: S) => S): S | null;
    static removeAll<T extends unknown>(self: T[], predicate: (param0: T) => boolean): boolean;
    static removeAll<T extends unknown>(self: T[], elements: T[]): boolean;
    static removeAll<T extends unknown>(self: T[], elements: Sequence<T>): boolean;
    static removeFirst<T extends unknown>(self: T[]): T;
    static removeFirstOrNull<T extends unknown>(self: T[]): T | null;
    static removeLast<T extends unknown>(self: T[]): T;
    static removeLastOrNull<T extends unknown>(self: T[]): T | null;
    static requireNoNulls<T extends unknown>(self: (T | null)[]): T[];
    static retainAll<T extends unknown>(self: T[], predicate: (param0: T) => boolean): boolean;
    static retainAll<T extends unknown>(self: T[], elements: T[]): boolean;
    static retainAll<T extends unknown>(self: T[], elements: Sequence<T>): boolean;
    static reverse<T extends unknown>(self: T[]): void;
    static reversed<T extends unknown>(self: T[]): T[];
    static runningFold<R extends unknown, T extends unknown>(self: T[], initial: R, operation: (param0: R, param1: T) => R): R[];
    static runningFoldIndexed<R extends unknown, T extends unknown>(self: T[], initial: R, operation: (param0: number, param1: R, param2: T) => R): R[];
    static runningReduce<S extends unknown, T extends S>(self: T[], operation: (param0: S, param1: T) => S): S[];
    static runningReduceIndexed<S extends unknown, T extends S>(self: T[], operation: (param0: number, param1: S, param2: T) => S): S[];
    static scan<R extends unknown, T extends unknown>(self: T[], initial: R, operation: (param0: R, param1: T) => R): R[];
    static scanIndexed<R extends unknown, T extends unknown>(self: T[], initial: R, operation: (param0: number, param1: R, param2: T) => R): R[];
    static shuffle<T extends unknown>(self: T[], random: Random_2): void;
    static shuffled<T extends unknown>(self: T[]): T[];
    static shuffled<T extends unknown>(self: T[], random: Random): T[];
    static shuffled<T extends unknown>(self: T[], random: Random_2): T[];
    static single<T extends unknown>(self: T[]): T;
    static single<T extends unknown>(self: T[], predicate: (param0: T) => boolean): T;
    static singleOrNull<T extends unknown>(self: T[]): T | null;
    static singleOrNull<T extends unknown>(self: T[], predicate: (param0: T) => boolean): T | null;
    static slice<T extends unknown>(self: T[], indices: number[]): T[];
    static slice<T extends unknown>(self: T[], indices: { start: number; endInclusive: number; step: number }): T[];
    static sort<T extends Comparable<T>>(self: T[]): void;
    static sortBy<T extends unknown, R extends Comparable<R>>(self: T[], selector: (param0: T) => R | null): void;
    static sortByDescending<T extends unknown, R extends Comparable<R>>(self: T[], selector: (param0: T) => R | null): void;
    static sortDescending<T extends Comparable<T>>(self: T[]): void;
    static sortWith<T extends unknown>(self: T[], comparator: (param0: T, param1: T) => number): void;
    static sorted<T extends Comparable<T>>(self: T[]): T[];
    static sortedBy<T extends unknown, R extends Comparable<R>>(self: T[], selector: (param0: T) => R | null): T[];
    static sortedByDescending<T extends unknown, R extends Comparable<R>>(self: T[], selector: (param0: T) => R | null): T[];
    static sortedDescending<T extends Comparable<T>>(self: T[]): T[];
    static sortedWith<T extends unknown>(self: T[], comparator: (param0: T, param1: T) => number): T[];
    static subtract<T extends unknown>(self: T[], other: T[]): T[];
    static sumBy<T extends unknown>(self: T[], selector: (param0: T) => number): number;
    static sumByDouble<T extends unknown>(self: T[], selector: (param0: T) => number): number;
    static sumOfByte(self: number[]): number;
    static sumOfDouble(self: number[]): number;
    static sumOfFloat(self: number[]): number;
    static sumOfInt(self: number[]): number;
    static sumOfLong(self: number[]): number;
    static sumOfShort(self: number[]): number;
    static take<T extends unknown>(self: T[], n: number): T[];
    static takeLast<T extends unknown>(self: T[], n: number): T[];
    static takeLastWhile<T extends unknown>(self: T[], predicate: (param0: T) => boolean): T[];
    static takeWhile<T extends unknown>(self: T[], predicate: (param0: T) => boolean): T[];
    static terminateCollectionToArray<T extends unknown>(collectionSize: number, array: T[]): T[];
    static throwCountOverflow(): void;
    static throwIndexOverflow(): void;
    static toBooleanArray(self: boolean[]): boolean[];
    static toByteArray(self: number[]): number[];
    static toCharArray(self: string[]): string[];
    static toCollection<C extends T[], T extends unknown>(self: T[], destination: C): C;
    static toDoubleArray(self: number[]): number[];
    static toFloatArray(self: number[]): number[];
    static toHashSet<T extends unknown>(self: T[]): T[];
    static toIntArray(self: number[]): number[];
    static toList<T extends unknown>(self: T[]): T[];
    static toLongArray(self: number[]): number[];
    static toMutableList<T extends unknown>(self: T[]): T[];
    static toMutableSet<T extends unknown>(self: T[]): T[];
    static toSet<T extends unknown>(self: T[]): T[];
    static toShortArray(self: number[]): number[];
    static toSortedSet<T extends Comparable<T>>(self: T[]): T[];
    static toSortedSet<T extends unknown>(self: T[], comparator: (param0: T, param1: T) => number): T[];
    static union<T extends unknown>(self: T[], other: T[]): T[];
    static unzip<T extends unknown, R extends unknown>(self: Pair<T, R>[]): Pair<T[], R[]>;
    static windowed<R extends unknown, T extends unknown>(self: T[], size: number, step: number, partialWindows: boolean, transform: (param0: T[]) => R): R[];
    static windowed<T extends unknown>(self: T[], size: number, step: number, partialWindows: boolean): T[][];
    static withIndex<T extends unknown>(self: T[]): IndexedValue<T>[];
    static withIndex<T extends unknown>(self: Iterator<T>): Iterator<IndexedValue<T>>;
    static zip<V extends unknown, T extends unknown, R extends unknown>(self: T[], other: R[], transform: (param0: T, param1: R) => V): V[];
    static zip<T extends unknown, R extends unknown>(self: T[], other: R[]): Pair<T, R>[];
    static zipWithNext<R extends unknown, T extends unknown>(self: T[], transform: (param0: T, param1: T) => R): R[];
    static zipWithNext<T extends unknown>(self: T[]): Pair<T, T>[];
}