import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { PointerBuffer } from '../../../org/lwjgl/PointerBuffer.d.ts'
import type { MemoryStack } from '../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class STBIR_RESIZE extends Struct<STBIR_RESIZE> implements NativeResource {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CALLED_ALLOC: number;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static FAST_ALPHA: number;
    static HORIZONTAL_EDGE: number;
    static HORIZONTAL_FILTER: number;
    static HORIZONTAL_FILTER_KERNEL: number;
    static HORIZONTAL_FILTER_SUPPORT: number;
    static INPUT_CB: number;
    static INPUT_DATA_TYPE: number;
    static INPUT_H: number;
    static INPUT_PIXELS: number;
    static INPUT_PIXEL_LAYOUT_PUBLIC: number;
    static INPUT_S0: number;
    static INPUT_S1: number;
    static INPUT_STRIDE_IN_BYTES: number;
    static INPUT_T0: number;
    static INPUT_T1: number;
    static INPUT_W: number;
    static NEEDS_REBUILD: number;
    static OUTPUT_CB: number;
    static OUTPUT_DATA_TYPE: number;
    static OUTPUT_H: number;
    static OUTPUT_PIXELS: number;
    static OUTPUT_PIXEL_LAYOUT_PUBLIC: number;
    static OUTPUT_STRIDE_IN_BYTES: number;
    static OUTPUT_SUBH: number;
    static OUTPUT_SUBW: number;
    static OUTPUT_SUBX: number;
    static OUTPUT_SUBY: number;
    static OUTPUT_W: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static SAMPLERS: number;
    static SIZEOF: number;
    static SPLITS: number;
    static USER_DATA: number;
    static VERTICAL_EDGE: number;
    static VERTICAL_FILTER: number;
    static VERTICAL_FILTER_KERNEL: number;
    static VERTICAL_FILTER_SUPPORT: number;
    static calloc(): STBIR_RESIZE;
    static calloc(paramarg0: MemoryStack): STBIR_RESIZE;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): STBIR_RESIZE;
    static create(paramarg0: number): STBIR_RESIZE;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): STBIR_RESIZE;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): STBIR_RESIZE;
    static malloc(paramarg0: MemoryStack): STBIR_RESIZE;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static ncalled_alloc(paramarg0: number): number;
    static ncalled_alloc(paramarg0: number, paramarg1: number): void;
    static nfast_alpha(paramarg0: number): number;
    static nfast_alpha(paramarg0: number, paramarg1: number): void;
    static nhorizontal_edge(paramarg0: number): number;
    static nhorizontal_edge(paramarg0: number, paramarg1: number): void;
    static nhorizontal_filter(paramarg0: number): number;
    static nhorizontal_filter(paramarg0: number, paramarg1: number): void;
    static nhorizontal_filter_kernel(paramarg0: number, paramarg1: number): PointerBuffer;
    static nhorizontal_filter_kernel(paramarg0: number, paramarg1: PointerBuffer): void;
    static nhorizontal_filter_support(paramarg0: number, paramarg1: number): PointerBuffer;
    static nhorizontal_filter_support(paramarg0: number, paramarg1: PointerBuffer): void;
    static ninput_cb(paramarg0: number, paramarg1: number): PointerBuffer;
    static ninput_cb(paramarg0: number, paramarg1: PointerBuffer): void;
    static ninput_data_type(paramarg0: number): number;
    static ninput_data_type(paramarg0: number, paramarg1: number): void;
    static ninput_h(paramarg0: number): number;
    static ninput_h(paramarg0: number, paramarg1: number): void;
    static ninput_pixel_layout_public(paramarg0: number): number;
    static ninput_pixel_layout_public(paramarg0: number, paramarg1: number): void;
    static ninput_pixels(paramarg0: number, paramarg1: number): ByteBuffer;
    static ninput_pixels(paramarg0: number, paramarg1: ByteBuffer): void;
    static ninput_s0(paramarg0: number): number;
    static ninput_s0(paramarg0: number, paramarg1: number): void;
    static ninput_s1(paramarg0: number): number;
    static ninput_s1(paramarg0: number, paramarg1: number): void;
    static ninput_stride_in_bytes(paramarg0: number): number;
    static ninput_stride_in_bytes(paramarg0: number, paramarg1: number): void;
    static ninput_t0(paramarg0: number): number;
    static ninput_t0(paramarg0: number, paramarg1: number): void;
    static ninput_t1(paramarg0: number): number;
    static ninput_t1(paramarg0: number, paramarg1: number): void;
    static ninput_w(paramarg0: number): number;
    static ninput_w(paramarg0: number, paramarg1: number): void;
    static nneeds_rebuild(paramarg0: number): number;
    static nneeds_rebuild(paramarg0: number, paramarg1: number): void;
    static noutput_cb(paramarg0: number, paramarg1: number): PointerBuffer;
    static noutput_cb(paramarg0: number, paramarg1: PointerBuffer): void;
    static noutput_data_type(paramarg0: number): number;
    static noutput_data_type(paramarg0: number, paramarg1: number): void;
    static noutput_h(paramarg0: number): number;
    static noutput_h(paramarg0: number, paramarg1: number): void;
    static noutput_pixel_layout_public(paramarg0: number): number;
    static noutput_pixel_layout_public(paramarg0: number, paramarg1: number): void;
    static noutput_pixels(paramarg0: number, paramarg1: number): ByteBuffer;
    static noutput_pixels(paramarg0: number, paramarg1: ByteBuffer): void;
    static noutput_stride_in_bytes(paramarg0: number): number;
    static noutput_stride_in_bytes(paramarg0: number, paramarg1: number): void;
    static noutput_subh(paramarg0: number): number;
    static noutput_subh(paramarg0: number, paramarg1: number): void;
    static noutput_subw(paramarg0: number): number;
    static noutput_subw(paramarg0: number, paramarg1: number): void;
    static noutput_subx(paramarg0: number): number;
    static noutput_subx(paramarg0: number, paramarg1: number): void;
    static noutput_suby(paramarg0: number): number;
    static noutput_suby(paramarg0: number, paramarg1: number): void;
    static noutput_w(paramarg0: number): number;
    static noutput_w(paramarg0: number, paramarg1: number): void;
    static nsamplers(paramarg0: number): number;
    static nsamplers(paramarg0: number, paramarg1: number): void;
    static nsplits(paramarg0: number): number;
    static nsplits(paramarg0: number, paramarg1: number): void;
    static nuser_data(paramarg0: number): number;
    static nuser_data(paramarg0: number, paramarg1: number): void;
    static nvertical_edge(paramarg0: number): number;
    static nvertical_edge(paramarg0: number, paramarg1: number): void;
    static nvertical_filter(paramarg0: number): number;
    static nvertical_filter(paramarg0: number, paramarg1: number): void;
    static nvertical_filter_kernel(paramarg0: number, paramarg1: number): PointerBuffer;
    static nvertical_filter_kernel(paramarg0: number, paramarg1: PointerBuffer): void;
    static nvertical_filter_support(paramarg0: number, paramarg1: number): PointerBuffer;
    static nvertical_filter_support(paramarg0: number, paramarg1: PointerBuffer): void;
    static validate(paramarg0: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    called_alloc(): boolean;
    called_alloc(arg0: boolean): STBIR_RESIZE;
    close(): void;
    create(arg0: number, arg1: ByteBuffer): STBIR_RESIZE;
    fast_alpha(): boolean;
    fast_alpha(arg0: boolean): STBIR_RESIZE;
    horizontal_edge(): number;
    horizontal_edge(arg0: number): STBIR_RESIZE;
    horizontal_filter(): number;
    horizontal_filter(arg0: number): STBIR_RESIZE;
    horizontal_filter_kernel(arg0: number): PointerBuffer;
    horizontal_filter_kernel(arg0: PointerBuffer): STBIR_RESIZE;
    horizontal_filter_support(arg0: number): PointerBuffer;
    horizontal_filter_support(arg0: PointerBuffer): STBIR_RESIZE;
    input_cb(arg0: number): PointerBuffer;
    input_cb(arg0: PointerBuffer): STBIR_RESIZE;
    input_data_type(): number;
    input_data_type(arg0: number): STBIR_RESIZE;
    input_h(): number;
    input_h(arg0: number): STBIR_RESIZE;
    input_pixel_layout_public(): number;
    input_pixel_layout_public(arg0: number): STBIR_RESIZE;
    input_pixels(arg0: ByteBuffer): STBIR_RESIZE;
    input_pixels(arg0: number): ByteBuffer;
    input_s0(): number;
    input_s0(arg0: number): STBIR_RESIZE;
    input_s1(): number;
    input_s1(arg0: number): STBIR_RESIZE;
    input_stride_in_bytes(): number;
    input_stride_in_bytes(arg0: number): STBIR_RESIZE;
    input_t0(): number;
    input_t0(arg0: number): STBIR_RESIZE;
    input_t1(): number;
    input_t1(arg0: number): STBIR_RESIZE;
    input_w(): number;
    input_w(arg0: number): STBIR_RESIZE;
    needs_rebuild(): boolean;
    needs_rebuild(arg0: boolean): STBIR_RESIZE;
    output_cb(arg0: number): PointerBuffer;
    output_cb(arg0: PointerBuffer): STBIR_RESIZE;
    output_data_type(): number;
    output_data_type(arg0: number): STBIR_RESIZE;
    output_h(): number;
    output_h(arg0: number): STBIR_RESIZE;
    output_pixel_layout_public(): number;
    output_pixel_layout_public(arg0: number): STBIR_RESIZE;
    output_pixels(arg0: ByteBuffer): STBIR_RESIZE;
    output_pixels(arg0: number): ByteBuffer;
    output_stride_in_bytes(): number;
    output_stride_in_bytes(arg0: number): STBIR_RESIZE;
    output_subh(): number;
    output_subh(arg0: number): STBIR_RESIZE;
    output_subw(): number;
    output_subw(arg0: number): STBIR_RESIZE;
    output_subx(): number;
    output_subx(arg0: number): STBIR_RESIZE;
    output_suby(): number;
    output_suby(arg0: number): STBIR_RESIZE;
    output_w(): number;
    output_w(arg0: number): STBIR_RESIZE;
    samplers(): number;
    samplers(arg0: number): STBIR_RESIZE;
    set(arg0: number, arg1: ByteBuffer, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: PointerBuffer, arg9: ByteBuffer, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number, arg15: number, arg16: PointerBuffer, arg17: number, arg18: number, arg19: number, arg20: boolean, arg21: boolean, arg22: boolean, arg23: number, arg24: number, arg25: number, arg26: number, arg27: number, arg28: number, arg29: number, arg30: number, arg31: PointerBuffer, arg32: PointerBuffer, arg33: PointerBuffer, arg34: PointerBuffer, arg35: number): STBIR_RESIZE;
    set(arg0: STBIR_RESIZE): STBIR_RESIZE;
    sizeof(): number;
    splits(): number;
    splits(arg0: number): STBIR_RESIZE;
    user_data(): number;
    user_data(arg0: number): STBIR_RESIZE;
    vertical_edge(): number;
    vertical_edge(arg0: number): STBIR_RESIZE;
    vertical_filter(): number;
    vertical_filter(arg0: number): STBIR_RESIZE;
    vertical_filter_kernel(arg0: number): PointerBuffer;
    vertical_filter_kernel(arg0: PointerBuffer): STBIR_RESIZE;
    vertical_filter_support(arg0: number): PointerBuffer;
    vertical_filter_support(arg0: PointerBuffer): STBIR_RESIZE;
}