import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { FloatBuffer } from '../../../java/nio/FloatBuffer.d.ts'
import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../java/lang/CharSequence.d.ts'
import type { PointerBuffer } from '../../../org/lwjgl/PointerBuffer.d.ts'
import type { STBTTAlignedQuad } from '../../../org/lwjgl/stb/STBTTAlignedQuad.d.ts'
import type { STBTTBitmap } from '../../../org/lwjgl/stb/STBTTBitmap.d.ts'
import type { STBTTFontinfo } from '../../../org/lwjgl/stb/STBTTFontinfo.d.ts'
import type { STBTTPackContext } from '../../../org/lwjgl/stb/STBTTPackContext.d.ts'
export class STBTruetype extends Object {
    static STBTT_MACSTYLE_BOLD: number;
    static STBTT_MACSTYLE_DONTCARE: number;
    static STBTT_MACSTYLE_ITALIC: number;
    static STBTT_MACSTYLE_NONE: number;
    static STBTT_MACSTYLE_UNDERSCORE: number;
    static STBTT_MAC_EID_ARABIC: number;
    static STBTT_MAC_EID_CHINESE_TRAD: number;
    static STBTT_MAC_EID_GREEK: number;
    static STBTT_MAC_EID_HEBREW: number;
    static STBTT_MAC_EID_JAPANESE: number;
    static STBTT_MAC_EID_KOREAN: number;
    static STBTT_MAC_EID_ROMAN: number;
    static STBTT_MAC_EID_RUSSIAN: number;
    static STBTT_MAC_LANG_ARABIC: number;
    static STBTT_MAC_LANG_CHINESE_SIMPLIFIED: number;
    static STBTT_MAC_LANG_CHINESE_TRAD: number;
    static STBTT_MAC_LANG_DUTCH: number;
    static STBTT_MAC_LANG_ENGLISH: number;
    static STBTT_MAC_LANG_FRENCH: number;
    static STBTT_MAC_LANG_GERMAN: number;
    static STBTT_MAC_LANG_HEBREW: number;
    static STBTT_MAC_LANG_ITALIAN: number;
    static STBTT_MAC_LANG_JAPANESE: number;
    static STBTT_MAC_LANG_KOREAN: number;
    static STBTT_MAC_LANG_RUSSIAN: number;
    static STBTT_MAC_LANG_SPANISH: number;
    static STBTT_MAC_LANG_SWEDISH: number;
    static STBTT_MS_EID_SHIFTJIS: number;
    static STBTT_MS_EID_SYMBOL: number;
    static STBTT_MS_EID_UNICODE_BMP: number;
    static STBTT_MS_EID_UNICODE_FULL: number;
    static STBTT_MS_LANG_CHINESE: number;
    static STBTT_MS_LANG_DUTCH: number;
    static STBTT_MS_LANG_ENGLISH: number;
    static STBTT_MS_LANG_FRENCH: number;
    static STBTT_MS_LANG_GERMAN: number;
    static STBTT_MS_LANG_HEBREW: number;
    static STBTT_MS_LANG_ITALIAN: number;
    static STBTT_MS_LANG_JAPANESE: number;
    static STBTT_MS_LANG_KOREAN: number;
    static STBTT_MS_LANG_RUSSIAN: number;
    static STBTT_MS_LANG_SPANISH: number;
    static STBTT_MS_LANG_SWEDISH: number;
    static STBTT_PLATFORM_ID_ISO: number;
    static STBTT_PLATFORM_ID_MAC: number;
    static STBTT_PLATFORM_ID_MICROSOFT: number;
    static STBTT_PLATFORM_ID_UNICODE: number;
    static STBTT_UNICODE_EID_ISO_10646: number;
    static STBTT_UNICODE_EID_UNICODE_1_0: number;
    static STBTT_UNICODE_EID_UNICODE_1_1: number;
    static STBTT_UNICODE_EID_UNICODE_2_0_BMP: number;
    static STBTT_UNICODE_EID_UNICODE_2_0_FULL: number;
    static STBTT_vcubic: number;
    static STBTT_vcurve: number;
    static STBTT_vline: number;
    static STBTT_vmove: number;
    static STBTT_POINT_SIZE(paramarg0: number): number;
    static nstbtt_BakeFontBitmap(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): number;
    static nstbtt_CompareUTF8toUTF16_bigendian(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nstbtt_FindGlyphIndex(paramarg0: number, paramarg1: number): number;
    static nstbtt_FindMatchingFont(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nstbtt_FindSVGDoc(paramarg0: number, paramarg1: number): number;
    static nstbtt_FreeBitmap(paramarg0: number, paramarg1: number): void;
    static nstbtt_FreeSDF(paramarg0: number, paramarg1: number): void;
    static nstbtt_FreeShape(paramarg0: number, paramarg1: number): void;
    static nstbtt_GetBakedQuad(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[], paramarg5: number[], paramarg6: number, paramarg7: number): void;
    static nstbtt_GetBakedQuad(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nstbtt_GetCodepointBitmap(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[], paramarg5: number[], paramarg6: number[], paramarg7: number[]): number;
    static nstbtt_GetCodepointBitmap(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): number;
    static nstbtt_GetCodepointBitmapBox(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[], paramarg5: number[], paramarg6: number[], paramarg7: number[]): void;
    static nstbtt_GetCodepointBitmapBox(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nstbtt_GetCodepointBitmapBoxSubpixel(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[], paramarg7: number[], paramarg8: number[], paramarg9: number[]): void;
    static nstbtt_GetCodepointBitmapBoxSubpixel(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static nstbtt_GetCodepointBitmapSubpixel(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[], paramarg7: number[], paramarg8: number[], paramarg9: number[]): number;
    static nstbtt_GetCodepointBitmapSubpixel(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): number;
    static nstbtt_GetCodepointBox(paramarg0: number, paramarg1: number, paramarg2: number[], paramarg3: number[], paramarg4: number[], paramarg5: number[]): number;
    static nstbtt_GetCodepointBox(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): number;
    static nstbtt_GetCodepointHMetrics(paramarg0: number, paramarg1: number, paramarg2: number[], paramarg3: number[]): void;
    static nstbtt_GetCodepointHMetrics(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nstbtt_GetCodepointKernAdvance(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nstbtt_GetCodepointSDF(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[], paramarg7: number[], paramarg8: number[], paramarg9: number[]): number;
    static nstbtt_GetCodepointSDF(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): number;
    static nstbtt_GetCodepointSVG(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nstbtt_GetCodepointShape(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nstbtt_GetFontBoundingBox(paramarg0: number, paramarg1: number[], paramarg2: number[], paramarg3: number[], paramarg4: number[]): void;
    static nstbtt_GetFontBoundingBox(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nstbtt_GetFontNameString(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): number;
    static nstbtt_GetFontOffsetForIndex(paramarg0: number, paramarg1: number): number;
    static nstbtt_GetFontVMetrics(paramarg0: number, paramarg1: number[], paramarg2: number[], paramarg3: number[]): void;
    static nstbtt_GetFontVMetrics(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nstbtt_GetFontVMetricsOS2(paramarg0: number, paramarg1: number[], paramarg2: number[], paramarg3: number[]): number;
    static nstbtt_GetFontVMetricsOS2(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nstbtt_GetGlyphBitmap(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[], paramarg5: number[], paramarg6: number[], paramarg7: number[]): number;
    static nstbtt_GetGlyphBitmap(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): number;
    static nstbtt_GetGlyphBitmapBox(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[], paramarg5: number[], paramarg6: number[], paramarg7: number[]): void;
    static nstbtt_GetGlyphBitmapBox(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nstbtt_GetGlyphBitmapBoxSubpixel(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[], paramarg7: number[], paramarg8: number[], paramarg9: number[]): void;
    static nstbtt_GetGlyphBitmapBoxSubpixel(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static nstbtt_GetGlyphBitmapSubpixel(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[], paramarg7: number[], paramarg8: number[], paramarg9: number[]): number;
    static nstbtt_GetGlyphBitmapSubpixel(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): number;
    static nstbtt_GetGlyphBox(paramarg0: number, paramarg1: number, paramarg2: number[], paramarg3: number[], paramarg4: number[], paramarg5: number[]): number;
    static nstbtt_GetGlyphBox(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): number;
    static nstbtt_GetGlyphHMetrics(paramarg0: number, paramarg1: number, paramarg2: number[], paramarg3: number[]): void;
    static nstbtt_GetGlyphHMetrics(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nstbtt_GetGlyphKernAdvance(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nstbtt_GetGlyphSDF(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[], paramarg7: number[], paramarg8: number[], paramarg9: number[]): number;
    static nstbtt_GetGlyphSDF(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): number;
    static nstbtt_GetGlyphSVG(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nstbtt_GetGlyphShape(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nstbtt_GetKerningTable(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nstbtt_GetKerningTableLength(paramarg0: number): number;
    static nstbtt_GetNumberOfFonts(paramarg0: number): number;
    static nstbtt_GetPackedQuad(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[], paramarg5: number[], paramarg6: number, paramarg7: number): void;
    static nstbtt_GetPackedQuad(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nstbtt_GetScaledFontVMetrics(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[], paramarg4: number[], paramarg5: number[]): void;
    static nstbtt_GetScaledFontVMetrics(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nstbtt_InitFont(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nstbtt_IsGlyphEmpty(paramarg0: number, paramarg1: number): number;
    static nstbtt_MakeCodepointBitmap(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nstbtt_MakeCodepointBitmapSubpixel(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static nstbtt_MakeCodepointBitmapSubpixelPrefilter(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number[], paramarg12: number[], paramarg13: number): void;
    static nstbtt_MakeCodepointBitmapSubpixelPrefilter(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number, paramarg12: number, paramarg13: number): void;
    static nstbtt_MakeGlyphBitmap(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nstbtt_MakeGlyphBitmapSubpixel(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static nstbtt_MakeGlyphBitmapSubpixelPrefilter(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number[], paramarg12: number[], paramarg13: number): void;
    static nstbtt_MakeGlyphBitmapSubpixelPrefilter(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number, paramarg12: number, paramarg13: number): void;
    static nstbtt_PackBegin(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): number;
    static nstbtt_PackEnd(paramarg0: number): void;
    static nstbtt_PackFontRange(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): number;
    static nstbtt_PackFontRanges(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nstbtt_PackFontRangesGatherRects(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nstbtt_PackFontRangesPackRects(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nstbtt_PackFontRangesRenderIntoRects(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nstbtt_PackSetOversampling(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nstbtt_PackSetSkipMissingCodepoints(paramarg0: number, paramarg1: number): void;
    static nstbtt_Rasterize(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number): void;
    static nstbtt_ScaleForMappingEmToPixels(paramarg0: number, paramarg1: number): number;
    static nstbtt_ScaleForPixelHeight(paramarg0: number, paramarg1: number): number;
    static stbtt_BakeFontBitmap(paramarg0: ByteBuffer, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: (Object | null)[]): number;
    static stbtt_CompareUTF8toUTF16_bigendian(paramarg0: ByteBuffer, paramarg1: ByteBuffer): boolean;
    static stbtt_FindGlyphIndex(paramarg0: STBTTFontinfo, paramarg1: number): number;
    static stbtt_FindMatchingFont(paramarg0: ByteBuffer, paramarg1: CharSequence, paramarg2: number): number;
    static stbtt_FindMatchingFont(paramarg0: ByteBuffer, paramarg1: ByteBuffer, paramarg2: number): number;
    static stbtt_FindSVGDoc(paramarg0: STBTTFontinfo, paramarg1: number): number;
    static stbtt_FreeBitmap(paramarg0: ByteBuffer): void;
    static stbtt_FreeBitmap(paramarg0: ByteBuffer, paramarg1: number): void;
    static stbtt_FreeSDF(paramarg0: ByteBuffer): void;
    static stbtt_FreeSDF(paramarg0: ByteBuffer, paramarg1: number): void;
    static stbtt_FreeShape(paramarg0: STBTTFontinfo, paramarg1: (Object | null)[]): void;
    static stbtt_GetBakedQuad(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[], paramarg5: number[], paramarg6: STBTTAlignedQuad, paramarg7: boolean): void;
    static stbtt_GetBakedQuad(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: FloatBuffer, paramarg5: FloatBuffer, paramarg6: STBTTAlignedQuad, paramarg7: boolean): void;
    static stbtt_GetCodepointBitmap(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[], paramarg5: number[], paramarg6: number[], paramarg7: number[]): ByteBuffer;
    static stbtt_GetCodepointBitmap(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: IntBuffer, paramarg5: IntBuffer, paramarg6: IntBuffer, paramarg7: IntBuffer): ByteBuffer;
    static stbtt_GetCodepointBitmapBox(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[], paramarg5: number[], paramarg6: number[], paramarg7: number[]): void;
    static stbtt_GetCodepointBitmapBox(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: IntBuffer, paramarg5: IntBuffer, paramarg6: IntBuffer, paramarg7: IntBuffer): void;
    static stbtt_GetCodepointBitmapBoxSubpixel(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[], paramarg7: number[], paramarg8: number[], paramarg9: number[]): void;
    static stbtt_GetCodepointBitmapBoxSubpixel(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: IntBuffer, paramarg7: IntBuffer, paramarg8: IntBuffer, paramarg9: IntBuffer): void;
    static stbtt_GetCodepointBitmapSubpixel(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[], paramarg7: number[], paramarg8: number[], paramarg9: number[]): ByteBuffer;
    static stbtt_GetCodepointBitmapSubpixel(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: IntBuffer, paramarg7: IntBuffer, paramarg8: IntBuffer, paramarg9: IntBuffer): ByteBuffer;
    static stbtt_GetCodepointBox(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number[], paramarg3: number[], paramarg4: number[], paramarg5: number[]): boolean;
    static stbtt_GetCodepointBox(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: IntBuffer, paramarg3: IntBuffer, paramarg4: IntBuffer, paramarg5: IntBuffer): boolean;
    static stbtt_GetCodepointHMetrics(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number[], paramarg3: number[]): void;
    static stbtt_GetCodepointHMetrics(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: IntBuffer, paramarg3: IntBuffer): void;
    static stbtt_GetCodepointKernAdvance(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number): number;
    static stbtt_GetCodepointSDF(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[], paramarg7: number[], paramarg8: number[], paramarg9: number[]): ByteBuffer;
    static stbtt_GetCodepointSDF(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: IntBuffer, paramarg7: IntBuffer, paramarg8: IntBuffer, paramarg9: IntBuffer): ByteBuffer;
    static stbtt_GetCodepointSVG(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: PointerBuffer): number;
    static stbtt_GetCodepointShape(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: PointerBuffer): number;
    static stbtt_GetCodepointShape(paramarg0: STBTTFontinfo, paramarg1: number): (Object | null)[];
    static stbtt_GetFontBoundingBox(paramarg0: STBTTFontinfo, paramarg1: number[], paramarg2: number[], paramarg3: number[], paramarg4: number[]): void;
    static stbtt_GetFontBoundingBox(paramarg0: STBTTFontinfo, paramarg1: IntBuffer, paramarg2: IntBuffer, paramarg3: IntBuffer, paramarg4: IntBuffer): void;
    static stbtt_GetFontNameString(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): ByteBuffer;
    static stbtt_GetFontOffsetForIndex(paramarg0: ByteBuffer, paramarg1: number): number;
    static stbtt_GetFontVMetrics(paramarg0: STBTTFontinfo, paramarg1: number[], paramarg2: number[], paramarg3: number[]): void;
    static stbtt_GetFontVMetrics(paramarg0: STBTTFontinfo, paramarg1: IntBuffer, paramarg2: IntBuffer, paramarg3: IntBuffer): void;
    static stbtt_GetFontVMetricsOS2(paramarg0: STBTTFontinfo, paramarg1: number[], paramarg2: number[], paramarg3: number[]): boolean;
    static stbtt_GetFontVMetricsOS2(paramarg0: STBTTFontinfo, paramarg1: IntBuffer, paramarg2: IntBuffer, paramarg3: IntBuffer): boolean;
    static stbtt_GetGlyphBitmap(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[], paramarg5: number[], paramarg6: number[], paramarg7: number[]): ByteBuffer;
    static stbtt_GetGlyphBitmap(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: IntBuffer, paramarg5: IntBuffer, paramarg6: IntBuffer, paramarg7: IntBuffer): ByteBuffer;
    static stbtt_GetGlyphBitmapBox(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[], paramarg5: number[], paramarg6: number[], paramarg7: number[]): void;
    static stbtt_GetGlyphBitmapBox(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: IntBuffer, paramarg5: IntBuffer, paramarg6: IntBuffer, paramarg7: IntBuffer): void;
    static stbtt_GetGlyphBitmapBoxSubpixel(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[], paramarg7: number[], paramarg8: number[], paramarg9: number[]): void;
    static stbtt_GetGlyphBitmapBoxSubpixel(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: IntBuffer, paramarg7: IntBuffer, paramarg8: IntBuffer, paramarg9: IntBuffer): void;
    static stbtt_GetGlyphBitmapSubpixel(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[], paramarg7: number[], paramarg8: number[], paramarg9: number[]): ByteBuffer;
    static stbtt_GetGlyphBitmapSubpixel(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: IntBuffer, paramarg7: IntBuffer, paramarg8: IntBuffer, paramarg9: IntBuffer): ByteBuffer;
    static stbtt_GetGlyphBox(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number[], paramarg3: number[], paramarg4: number[], paramarg5: number[]): boolean;
    static stbtt_GetGlyphBox(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: IntBuffer, paramarg3: IntBuffer, paramarg4: IntBuffer, paramarg5: IntBuffer): boolean;
    static stbtt_GetGlyphHMetrics(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number[], paramarg3: number[]): void;
    static stbtt_GetGlyphHMetrics(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: IntBuffer, paramarg3: IntBuffer): void;
    static stbtt_GetGlyphKernAdvance(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number): number;
    static stbtt_GetGlyphSDF(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[], paramarg7: number[], paramarg8: number[], paramarg9: number[]): ByteBuffer;
    static stbtt_GetGlyphSDF(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: IntBuffer, paramarg7: IntBuffer, paramarg8: IntBuffer, paramarg9: IntBuffer): ByteBuffer;
    static stbtt_GetGlyphSVG(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: PointerBuffer): number;
    static stbtt_GetGlyphShape(paramarg0: STBTTFontinfo, paramarg1: number, paramarg2: PointerBuffer): number;
    static stbtt_GetGlyphShape(paramarg0: STBTTFontinfo, paramarg1: number): (Object | null)[];
    static stbtt_GetKerningTable(paramarg0: STBTTFontinfo, paramarg1: (Object | null)[]): number;
    static stbtt_GetKerningTableLength(paramarg0: STBTTFontinfo): number;
    static stbtt_GetNumberOfFonts(paramarg0: ByteBuffer): number;
    static stbtt_GetPackedQuad(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[], paramarg5: number[], paramarg6: STBTTAlignedQuad, paramarg7: boolean): void;
    static stbtt_GetPackedQuad(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: FloatBuffer, paramarg5: FloatBuffer, paramarg6: STBTTAlignedQuad, paramarg7: boolean): void;
    static stbtt_GetScaledFontVMetrics(paramarg0: ByteBuffer, paramarg1: number, paramarg2: number, paramarg3: number[], paramarg4: number[], paramarg5: number[]): void;
    static stbtt_GetScaledFontVMetrics(paramarg0: ByteBuffer, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer, paramarg4: FloatBuffer, paramarg5: FloatBuffer): void;
    static stbtt_InitFont(paramarg0: STBTTFontinfo, paramarg1: ByteBuffer): boolean;
    static stbtt_InitFont(paramarg0: STBTTFontinfo, paramarg1: ByteBuffer, paramarg2: number): boolean;
    static stbtt_IsGlyphEmpty(paramarg0: STBTTFontinfo, paramarg1: number): boolean;
    static stbtt_MakeCodepointBitmap(paramarg0: STBTTFontinfo, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static stbtt_MakeCodepointBitmapSubpixel(paramarg0: STBTTFontinfo, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static stbtt_MakeCodepointBitmapSubpixelPrefilter(paramarg0: STBTTFontinfo, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number[], paramarg12: number[], paramarg13: number): void;
    static stbtt_MakeCodepointBitmapSubpixelPrefilter(paramarg0: STBTTFontinfo, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: FloatBuffer, paramarg12: FloatBuffer, paramarg13: number): void;
    static stbtt_MakeGlyphBitmap(paramarg0: STBTTFontinfo, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static stbtt_MakeGlyphBitmapSubpixel(paramarg0: STBTTFontinfo, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static stbtt_MakeGlyphBitmapSubpixelPrefilter(paramarg0: STBTTFontinfo, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number[], paramarg12: number[], paramarg13: number): void;
    static stbtt_MakeGlyphBitmapSubpixelPrefilter(paramarg0: STBTTFontinfo, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: FloatBuffer, paramarg12: FloatBuffer, paramarg13: number): void;
    static stbtt_PackBegin(paramarg0: STBTTPackContext, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): boolean;
    static stbtt_PackBegin(paramarg0: STBTTPackContext, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): boolean;
    static stbtt_PackEnd(paramarg0: STBTTPackContext): void;
    static stbtt_PackFontRange(paramarg0: STBTTPackContext, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: (Object | null)[]): boolean;
    static stbtt_PackFontRanges(paramarg0: STBTTPackContext, paramarg1: ByteBuffer, paramarg2: number, paramarg3: (Object | null)[]): boolean;
    static stbtt_PackFontRangesGatherRects(paramarg0: STBTTPackContext, paramarg1: STBTTFontinfo, paramarg2: (Object | null)[], paramarg3: (Object | null)[]): number;
    static stbtt_PackFontRangesPackRects(paramarg0: STBTTPackContext, paramarg1: (Object | null)[]): void;
    static stbtt_PackFontRangesRenderIntoRects(paramarg0: STBTTPackContext, paramarg1: STBTTFontinfo, paramarg2: (Object | null)[], paramarg3: (Object | null)[]): boolean;
    static stbtt_PackSetOversampling(paramarg0: STBTTPackContext, paramarg1: number, paramarg2: number): void;
    static stbtt_PackSetSkipMissingCodepoints(paramarg0: STBTTPackContext, paramarg1: boolean): void;
    static stbtt_Rasterize(paramarg0: STBTTBitmap, paramarg1: number, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: boolean): void;
    static stbtt_ScaleForMappingEmToPixels(paramarg0: STBTTFontinfo, paramarg1: number): number;
    static stbtt_ScaleForPixelHeight(paramarg0: STBTTFontinfo, paramarg1: number): number;
    constructor()
}