import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../../org/lwjgl/system/Struct$StructValidation.d.ts'
import type { POINTL } from '../../../../org/lwjgl/system/windows/POINTL.d.ts'
export class DEVMODE extends Struct<DEVMODE> implements NativeResource {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static DMBITSPERPEL: number;
    static DMCOLLATE: number;
    static DMCOLOR: number;
    static DMCOPIES: number;
    static DMDEFAULTSOURCE: number;
    static DMDEVICENAME: number;
    static DMDISPLAYFIXEDOUTPUT: number;
    static DMDISPLAYFLAGS: number;
    static DMDISPLAYFREQUENCY: number;
    static DMDISPLAYORIENTATION: number;
    static DMDITHERTYPE: number;
    static DMDRIVEREXTRA: number;
    static DMDRIVERVERSION: number;
    static DMDUPLEX: number;
    static DMFIELDS: number;
    static DMFORMNAME: number;
    static DMICMINTENT: number;
    static DMICMMETHOD: number;
    static DMLOGPIXELS: number;
    static DMMEDIATYPE: number;
    static DMNUP: number;
    static DMORIENTATION: number;
    static DMPANNINGHEIGHT: number;
    static DMPANNINGWIDTH: number;
    static DMPAPERLENGTH: number;
    static DMPAPERSIZE: number;
    static DMPAPERWIDTH: number;
    static DMPELSHEIGHT: number;
    static DMPELSWIDTH: number;
    static DMPOSITION: number;
    static DMPRINTQUALITY: number;
    static DMRESERVED1: number;
    static DMRESERVED2: number;
    static DMSCALE: number;
    static DMSIZE: number;
    static DMSPECVERSION: number;
    static DMTTOPTION: number;
    static DMYRESOLUTION: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static SIZEOF: number;
    static calloc(): DEVMODE;
    static calloc(paramarg0: MemoryStack): DEVMODE;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): DEVMODE;
    static create(paramarg0: number): DEVMODE;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): DEVMODE;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): DEVMODE;
    static malloc(paramarg0: MemoryStack): DEVMODE;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static ndmBitsPerPel(paramarg0: number): number;
    static ndmCollate(paramarg0: number): number;
    static ndmColor(paramarg0: number): number;
    static ndmCopies(paramarg0: number): number;
    static ndmDefaultSource(paramarg0: number): number;
    static ndmDeviceName(paramarg0: number): ByteBuffer;
    static ndmDeviceNameString(paramarg0: number): string;
    static ndmDisplayFixedOutput(paramarg0: number): number;
    static ndmDisplayFlags(paramarg0: number): number;
    static ndmDisplayFrequency(paramarg0: number): number;
    static ndmDisplayOrientation(paramarg0: number): number;
    static ndmDitherType(paramarg0: number): number;
    static ndmDriverExtra(paramarg0: number): number;
    static ndmDriverExtra(paramarg0: number, paramarg1: number): void;
    static ndmDriverVersion(paramarg0: number): number;
    static ndmDuplex(paramarg0: number): number;
    static ndmFields(paramarg0: number): number;
    static ndmFormName(paramarg0: number): ByteBuffer;
    static ndmFormNameString(paramarg0: number): string;
    static ndmICMIntent(paramarg0: number): number;
    static ndmICMMethod(paramarg0: number): number;
    static ndmLogPixels(paramarg0: number): number;
    static ndmMediaType(paramarg0: number): number;
    static ndmNup(paramarg0: number): number;
    static ndmOrientation(paramarg0: number): number;
    static ndmPanningHeight(paramarg0: number): number;
    static ndmPanningWidth(paramarg0: number): number;
    static ndmPaperLength(paramarg0: number): number;
    static ndmPaperSize(paramarg0: number): number;
    static ndmPaperWidth(paramarg0: number): number;
    static ndmPelsHeight(paramarg0: number): number;
    static ndmPelsWidth(paramarg0: number): number;
    static ndmPosition(paramarg0: number): POINTL;
    static ndmPrintQuality(paramarg0: number): number;
    static ndmReserved1(paramarg0: number): number;
    static ndmReserved2(paramarg0: number): number;
    static ndmScale(paramarg0: number): number;
    static ndmSize(paramarg0: number): number;
    static ndmSize(paramarg0: number, paramarg1: number): void;
    static ndmSpecVersion(paramarg0: number): number;
    static ndmSpecVersion(paramarg0: number, paramarg1: number): void;
    static ndmTTOption(paramarg0: number): number;
    static ndmYResolution(paramarg0: number): number;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    close(): void;
    create(arg0: number, arg1: ByteBuffer): DEVMODE;
    dmBitsPerPel(): number;
    dmCollate(): number;
    dmColor(): number;
    dmCopies(): number;
    dmDefaultSource(): number;
    dmDeviceName(): ByteBuffer;
    dmDeviceNameString(): string;
    dmDisplayFixedOutput(): number;
    dmDisplayFlags(): number;
    dmDisplayFrequency(): number;
    dmDisplayOrientation(): number;
    dmDitherType(): number;
    dmDriverExtra(): number;
    dmDriverExtra(arg0: number): DEVMODE;
    dmDriverVersion(): number;
    dmDuplex(): number;
    dmFields(): number;
    dmFormName(): ByteBuffer;
    dmFormNameString(): string;
    dmICMIntent(): number;
    dmICMMethod(): number;
    dmLogPixels(): number;
    dmMediaType(): number;
    dmNup(): number;
    dmOrientation(): number;
    dmPanningHeight(): number;
    dmPanningWidth(): number;
    dmPaperLength(): number;
    dmPaperSize(): number;
    dmPaperWidth(): number;
    dmPelsHeight(): number;
    dmPelsWidth(): number;
    dmPosition(): POINTL;
    dmPrintQuality(): number;
    dmReserved1(): number;
    dmReserved2(): number;
    dmScale(): number;
    dmSize(): number;
    dmSize(arg0: number): DEVMODE;
    dmSpecVersion(): number;
    dmSpecVersion(arg0: number): DEVMODE;
    dmTTOption(): number;
    dmYResolution(): number;
    set(arg0: DEVMODE): DEVMODE;
    sizeof(): number;
}