import type { ClientboundPacketType } from '../../../../../../com/viaversion/viaversion/api/protocol/packet/ClientboundPacketType.d.ts'
import type { Direction } from '../../../../../../com/viaversion/viaversion/api/protocol/packet/Direction.d.ts'
import type { State } from '../../../../../../com/viaversion/viaversion/api/protocol/packet/State.d.ts'
import type { Class } from '../../../../../../java/lang/Class.d.ts'
import type { Object } from '../../../../../../java/lang/Object.d.ts'
import type { Enum } from '../../../../../../java/lang/Enum.d.ts'
export class ClientboundPackets1_15 extends Enum<ClientboundPackets1_15> implements ClientboundPacketType {
    static ADD_ENTITY: ClientboundPackets1_15;
    static ADD_EXPERIENCE_ORB: ClientboundPackets1_15;
    static ADD_GLOBAL_ENTITY: ClientboundPackets1_15;
    static ADD_MOB: ClientboundPackets1_15;
    static ADD_PAINTING: ClientboundPackets1_15;
    static ADD_PLAYER: ClientboundPackets1_15;
    static ANIMATE: ClientboundPackets1_15;
    static AWARD_STATS: ClientboundPackets1_15;
    static BLOCK_BREAK_ACK: ClientboundPackets1_15;
    static BLOCK_DESTRUCTION: ClientboundPackets1_15;
    static BLOCK_ENTITY_DATA: ClientboundPackets1_15;
    static BLOCK_EVENT: ClientboundPackets1_15;
    static BLOCK_UPDATE: ClientboundPackets1_15;
    static BOSS_EVENT: ClientboundPackets1_15;
    static CHANGE_DIFFICULTY: ClientboundPackets1_15;
    static CHAT: ClientboundPackets1_15;
    static CHUNK_BLOCKS_UPDATE: ClientboundPackets1_15;
    static COMMANDS: ClientboundPackets1_15;
    static COMMAND_SUGGESTIONS: ClientboundPackets1_15;
    static CONTAINER_ACK: ClientboundPackets1_15;
    static CONTAINER_CLOSE: ClientboundPackets1_15;
    static CONTAINER_SET_CONTENT: ClientboundPackets1_15;
    static CONTAINER_SET_DATA: ClientboundPackets1_15;
    static CONTAINER_SET_SLOT: ClientboundPackets1_15;
    static COOLDOWN: ClientboundPackets1_15;
    static CUSTOM_PAYLOAD: ClientboundPackets1_15;
    static CUSTOM_SOUND: ClientboundPackets1_15;
    static DISCONNECT: ClientboundPackets1_15;
    static ENTITY_EVENT: ClientboundPackets1_15;
    static EXPLODE: ClientboundPackets1_15;
    static FORGET_LEVEL_CHUNK: ClientboundPackets1_15;
    static GAME_EVENT: ClientboundPackets1_15;
    static HORSE_SCREEN_OPEN: ClientboundPackets1_15;
    static KEEP_ALIVE: ClientboundPackets1_15;
    static LEVEL_CHUNK: ClientboundPackets1_15;
    static LEVEL_EVENT: ClientboundPackets1_15;
    static LEVEL_PARTICLES: ClientboundPackets1_15;
    static LIGHT_UPDATE: ClientboundPackets1_15;
    static LOGIN: ClientboundPackets1_15;
    static MAP_ITEM_DATA: ClientboundPackets1_15;
    static MERCHANT_OFFERS: ClientboundPackets1_15;
    static MOVE_ENTITY: ClientboundPackets1_15;
    static MOVE_ENTITY_POS: ClientboundPackets1_15;
    static MOVE_ENTITY_POS_ROT: ClientboundPackets1_15;
    static MOVE_ENTITY_ROT: ClientboundPackets1_15;
    static MOVE_VEHICLE: ClientboundPackets1_15;
    static OPEN_BOOK: ClientboundPackets1_15;
    static OPEN_SCREEN: ClientboundPackets1_15;
    static OPEN_SIGN_EDITOR: ClientboundPackets1_15;
    static PLACE_GHOST_RECIPE: ClientboundPackets1_15;
    static PLAYER_ABILITIES: ClientboundPackets1_15;
    static PLAYER_COMBAT: ClientboundPackets1_15;
    static PLAYER_INFO: ClientboundPackets1_15;
    static PLAYER_LOOK_AT: ClientboundPackets1_15;
    static PLAYER_POSITION: ClientboundPackets1_15;
    static RECIPE: ClientboundPackets1_15;
    static REMOVE_ENTITIES: ClientboundPackets1_15;
    static REMOVE_MOB_EFFECT: ClientboundPackets1_15;
    static RESOURCE_PACK: ClientboundPackets1_15;
    static RESPAWN: ClientboundPackets1_15;
    static ROTATE_HEAD: ClientboundPackets1_15;
    static SELECT_ADVANCEMENTS_TAB: ClientboundPackets1_15;
    static SET_BORDER: ClientboundPackets1_15;
    static SET_CAMERA: ClientboundPackets1_15;
    static SET_CARRIED_ITEM: ClientboundPackets1_15;
    static SET_CHUNK_CACHE_CENTER: ClientboundPackets1_15;
    static SET_CHUNK_CACHE_RADIUS: ClientboundPackets1_15;
    static SET_DEFAULT_SPAWN_POSITION: ClientboundPackets1_15;
    static SET_DISPLAY_OBJECTIVE: ClientboundPackets1_15;
    static SET_ENTITY_DATA: ClientboundPackets1_15;
    static SET_ENTITY_LINK: ClientboundPackets1_15;
    static SET_ENTITY_MOTION: ClientboundPackets1_15;
    static SET_EQUIPPED_ITEM: ClientboundPackets1_15;
    static SET_EXPERIENCE: ClientboundPackets1_15;
    static SET_HEALTH: ClientboundPackets1_15;
    static SET_OBJECTIVE: ClientboundPackets1_15;
    static SET_PASSENGERS: ClientboundPackets1_15;
    static SET_PLAYER_TEAM: ClientboundPackets1_15;
    static SET_SCORE: ClientboundPackets1_15;
    static SET_TIME: ClientboundPackets1_15;
    static SET_TITLES: ClientboundPackets1_15;
    static SOUND: ClientboundPackets1_15;
    static SOUND_ENTITY: ClientboundPackets1_15;
    static STOP_SOUND: ClientboundPackets1_15;
    static TAB_LIST: ClientboundPackets1_15;
    static TAG_QUERY: ClientboundPackets1_15;
    static TAKE_ITEM_ENTITY: ClientboundPackets1_15;
    static TELEPORT_ENTITY: ClientboundPackets1_15;
    static UPDATE_ADVANCEMENTS: ClientboundPackets1_15;
    static UPDATE_ATTRIBUTES: ClientboundPackets1_15;
    static UPDATE_MOB_EFFECT: ClientboundPackets1_15;
    static UPDATE_RECIPES: ClientboundPackets1_15;
    static UPDATE_TAGS: ClientboundPackets1_15;
    static valueOf(paramarg0: Class<Object>, paramarg1: string): Object | null;
    static valueOf(paramarg0: string): ClientboundPackets1_15;
    static values(): ClientboundPackets1_15[];
    private constructor()
    direction(): Direction;
    getId(): number;
    getName(): string;
    state(): State;
    name(): "ADD_ENTITY" | "ADD_EXPERIENCE_ORB" | "ADD_GLOBAL_ENTITY" | "ADD_MOB" | "ADD_PAINTING" | "ADD_PLAYER" | "ANIMATE" | "AWARD_STATS" | "BLOCK_BREAK_ACK" | "BLOCK_DESTRUCTION" | "BLOCK_ENTITY_DATA" | "BLOCK_EVENT" | "BLOCK_UPDATE" | "BOSS_EVENT" | "CHANGE_DIFFICULTY" | "CHAT" | "CHUNK_BLOCKS_UPDATE" | "COMMAND_SUGGESTIONS" | "COMMANDS" | "CONTAINER_ACK" | "CONTAINER_CLOSE" | "CONTAINER_SET_CONTENT" | "CONTAINER_SET_DATA" | "CONTAINER_SET_SLOT" | "COOLDOWN" | "CUSTOM_PAYLOAD" | "CUSTOM_SOUND" | "DISCONNECT" | "ENTITY_EVENT" | "EXPLODE" | "FORGET_LEVEL_CHUNK" | "GAME_EVENT" | "HORSE_SCREEN_OPEN" | "KEEP_ALIVE" | "LEVEL_CHUNK" | "LEVEL_EVENT" | "LEVEL_PARTICLES" | "LIGHT_UPDATE" | "LOGIN" | "MAP_ITEM_DATA" | "MERCHANT_OFFERS" | "MOVE_ENTITY_POS" | "MOVE_ENTITY_POS_ROT" | "MOVE_ENTITY_ROT" | "MOVE_ENTITY" | "MOVE_VEHICLE" | "OPEN_BOOK" | "OPEN_SCREEN" | "OPEN_SIGN_EDITOR" | "PLACE_GHOST_RECIPE" | "PLAYER_ABILITIES" | "PLAYER_COMBAT" | "PLAYER_INFO" | "PLAYER_LOOK_AT" | "PLAYER_POSITION" | "RECIPE" | "REMOVE_ENTITIES" | "REMOVE_MOB_EFFECT" | "RESOURCE_PACK" | "RESPAWN" | "ROTATE_HEAD" | "SELECT_ADVANCEMENTS_TAB" | "SET_BORDER" | "SET_CAMERA" | "SET_CARRIED_ITEM" | "SET_CHUNK_CACHE_CENTER" | "SET_CHUNK_CACHE_RADIUS" | "SET_DISPLAY_OBJECTIVE" | "SET_ENTITY_DATA" | "SET_ENTITY_LINK" | "SET_ENTITY_MOTION" | "SET_EQUIPPED_ITEM" | "SET_EXPERIENCE" | "SET_HEALTH" | "SET_OBJECTIVE" | "SET_PASSENGERS" | "SET_PLAYER_TEAM" | "SET_SCORE" | "SET_DEFAULT_SPAWN_POSITION" | "SET_TIME" | "SET_TITLES" | "SOUND_ENTITY" | "SOUND" | "STOP_SOUND" | "TAB_LIST" | "TAG_QUERY" | "TAKE_ITEM_ENTITY" | "TELEPORT_ENTITY" | "UPDATE_ADVANCEMENTS" | "UPDATE_ATTRIBUTES" | "UPDATE_MOB_EFFECT" | "UPDATE_RECIPES" | "UPDATE_TAGS";
}