import type { BranchProfile } from '../../../../../../com/oracle/truffle/api/profiles/BranchProfile.d.ts'
import type { TruffleString } from '../../../../../../com/oracle/truffle/api/strings/TruffleString.d.ts'
import type { JSContext } from '../../../../../../com/oracle/truffle/js/runtime/JSContext.d.ts'
import type { JSRealm } from '../../../../../../com/oracle/truffle/js/runtime/JSRealm.d.ts'
import type { JSObject } from '../../../../../../com/oracle/truffle/js/runtime/objects/JSObject.d.ts'
import type { ZoneId } from '../../../../../../java/time/ZoneId.d.ts'
import type { Locale } from '../../../../../../java/util/Locale.d.ts'
import type { Object } from '../../../../../../java/lang/Object.d.ts'
import type { DateFormat$HourCycle } from '../../../../../../org/graalvm/shadowed/com/ibm/icu/text/DateFormat$HourCycle.d.ts'
import type { Calendar } from '../../../../../../org/graalvm/shadowed/com/ibm/icu/util/Calendar.d.ts'
import type { TimeZone } from '../../../../../../org/graalvm/shadowed/com/ibm/icu/util/TimeZone.d.ts'
import type { ULocale } from '../../../../../../org/graalvm/shadowed/com/ibm/icu/util/ULocale.d.ts'
export class IntlUtil extends Object {
    static AA: TruffleString;
    static ACCENT: string;
    static ACCOUNTING: string;
    static AD: TruffleString;
    static AH: TruffleString;
    static ALWAYS: string;
    static AM: TruffleString;
    static AP: TruffleString;
    static AUTO: string;
    static BASE: string;
    static BASIC: string;
    static BC: TruffleString;
    static BCE: TruffleString;
    static BE: TruffleString;
    static BEFORE_ROC: TruffleString;
    static BEST_FIT: string;
    static BH: TruffleString;
    static BROC: TruffleString;
    static CALENDAR: string;
    static CARDINAL: string;
    static CASE: string;
    static CASE_FIRST: string;
    static CE: TruffleString;
    static CEIL: string;
    static CODE: string;
    static COLLATION: string;
    static COMPACT: string;
    static COMPACT_DISPLAY: string;
    static CONJUNCTION: string;
    static CURRENCY: string;
    static CURRENCY_DISPLAY: string;
    static CURRENCY_SIGN: string;
    static DATE_STYLE: string;
    static DATE_TIME_FIELD: string;
    static DAY: string;
    static DAYS: string;
    static DAYS_DISPLAY: string;
    static DAY_PERIOD: string;
    static DECIMAL: string;
    static DEFAULT: string;
    static DIALECT: string;
    static DIGITAL: string;
    static DIRECTION: string;
    static DISJUNCTION: string;
    static ELEMENT: string;
    static END_RANGE: string;
    static ENGINEERING: string;
    static ERA: string;
    static EXCEPT_ZERO: string;
    static EXPAND: string;
    static FALLBACK: string;
    static FALSE: string;
    static FIRST_DAY: string;
    static FIRST_DAY_OF_WEEK: string;
    static FLOOR: string;
    static FORMAT_MATCHER: string;
    static FRACTIONAL: string;
    static FRACTIONAL_DIGITS: string;
    static FRACTIONAL_SECOND_DIGITS: string;
    static FRACTION_DIGITS: string;
    static FULL: string;
    static GRANULARITY: string;
    static GRAPHEME: string;
    static H11: string;
    static H12: string;
    static H23: string;
    static H24: string;
    static HALF_CEIL: string;
    static HALF_EVEN: string;
    static HALF_EXPAND: string;
    static HALF_FLOOR: string;
    static HALF_TRUNC: string;
    static HEISEI: TruffleString;
    static HOUR: string;
    static HOUR12: string;
    static HOURS: string;
    static HOURS_DISPLAY: string;
    static HOUR_CYCLE: string;
    static IGNORE_PUNCTUATION: string;
    static INCAR: TruffleString;
    static INDEX: string;
    static INFINITY: string;
    static INPUT: string;
    static INTEGER: string;
    static IS_WORD_LIKE: string;
    static KEY_CALENDAR: TruffleString;
    static KEY_CASE_FIRST: TruffleString;
    static KEY_COLLATION: TruffleString;
    static KEY_COMPACT_DISPLAY: TruffleString;
    static KEY_CURRENCY: TruffleString;
    static KEY_CURRENCY_DISPLAY: TruffleString;
    static KEY_CURRENCY_SIGN: TruffleString;
    static KEY_DATE_STYLE: TruffleString;
    static KEY_DAY: TruffleString;
    static KEY_DAYS: TruffleString;
    static KEY_DAYS_DISPLAY: TruffleString;
    static KEY_DAY_PERIOD: TruffleString;
    static KEY_DIRECTION: TruffleString;
    static KEY_ERA: TruffleString;
    static KEY_FALLBACK: TruffleString;
    static KEY_FIRST_DAY: TruffleString;
    static KEY_FIRST_DAY_OF_WEEK: TruffleString;
    static KEY_FORMAT_MATCHER: TruffleString;
    static KEY_FRACTIONAL_DIGITS: TruffleString;
    static KEY_FRACTIONAL_SECOND_DIGITS: TruffleString;
    static KEY_GRANULARITY: TruffleString;
    static KEY_HOUR: TruffleString;
    static KEY_HOUR12: TruffleString;
    static KEY_HOURS: TruffleString;
    static KEY_HOURS_DISPLAY: TruffleString;
    static KEY_HOUR_CYCLE: TruffleString;
    static KEY_IGNORE_PUNCTUATION: TruffleString;
    static KEY_INDEX: TruffleString;
    static KEY_INPUT: TruffleString;
    static KEY_IS_WORD_LIKE: TruffleString;
    static KEY_LANGUAGE: TruffleString;
    static KEY_LANGUAGE_DISPLAY: TruffleString;
    static KEY_LOCALE: TruffleString;
    static KEY_LOCALE_MATCHER: TruffleString;
    static KEY_LTR: TruffleString;
    static KEY_MAXIMUM_FRACTION_DIGITS: TruffleString;
    static KEY_MAXIMUM_SIGNIFICANT_DIGITS: TruffleString;
    static KEY_MICROSECONDS: TruffleString;
    static KEY_MICROSECONDS_DISPLAY: TruffleString;
    static KEY_MILLISECONDS: TruffleString;
    static KEY_MILLISECONDS_DISPLAY: TruffleString;
    static KEY_MINIMUM_FRACTION_DIGITS: TruffleString;
    static KEY_MINIMUM_INTEGER_DIGITS: TruffleString;
    static KEY_MINIMUM_SIGNIFICANT_DIGITS: TruffleString;
    static KEY_MINUTE: TruffleString;
    static KEY_MINUTES: TruffleString;
    static KEY_MINUTES_DISPLAY: TruffleString;
    static KEY_MONTH: TruffleString;
    static KEY_MONTHS: TruffleString;
    static KEY_MONTHS_DISPLAY: TruffleString;
    static KEY_NANOSECONDS: TruffleString;
    static KEY_NANOSECONDS_DISPLAY: TruffleString;
    static KEY_NOTATION: TruffleString;
    static KEY_NUMBERING_SYSTEM: TruffleString;
    static KEY_NUMERIC: TruffleString;
    static KEY_PLURAL_CATEGORIES: TruffleString;
    static KEY_REGION: TruffleString;
    static KEY_ROUNDING_INCREMENT: TruffleString;
    static KEY_ROUNDING_MODE: TruffleString;
    static KEY_ROUNDING_PRIORITY: TruffleString;
    static KEY_RTL: TruffleString;
    static KEY_SCRIPT: TruffleString;
    static KEY_SECOND: TruffleString;
    static KEY_SECONDS: TruffleString;
    static KEY_SECONDS_DISPLAY: TruffleString;
    static KEY_SEGMENT: TruffleString;
    static KEY_SENSITIVITY: TruffleString;
    static KEY_SIGN_DISPLAY: TruffleString;
    static KEY_SOURCE: TruffleString;
    static KEY_STYLE: TruffleString;
    static KEY_TIME_STYLE: TruffleString;
    static KEY_TIME_ZONE: TruffleString;
    static KEY_TIME_ZONE_NAME: TruffleString;
    static KEY_TRAILING_ZERO_DISPLAY: TruffleString;
    static KEY_TYPE: TruffleString;
    static KEY_UNIT: TruffleString;
    static KEY_UNIT_DISPLAY: TruffleString;
    static KEY_USAGE: TruffleString;
    static KEY_USE_GROUPING: TruffleString;
    static KEY_VALUE: TruffleString;
    static KEY_VARIANTS: TruffleString;
    static KEY_WEEKDAY: TruffleString;
    static KEY_WEEKEND: TruffleString;
    static KEY_WEEKS: TruffleString;
    static KEY_WEEKS_DISPLAY: TruffleString;
    static KEY_YEAR: TruffleString;
    static KEY_YEARS: TruffleString;
    static KEY_YEARS_DISPLAY: TruffleString;
    static LANGUAGE: string;
    static LANGUAGE_DISPLAY: string;
    static LESS_PRECISION: string;
    static LITERAL: string;
    static LOCALE: string;
    static LOCALE_MATCHER: string;
    static LONG: string;
    static LONG_GENERIC: string;
    static LONG_OFFSET: string;
    static LOOKUP: string;
    static LOWER: string;
    static LTR: string;
    static MAXIMUM_FRACTION_DIGITS: string;
    static MAXIMUM_SIGNIFICANT_DIGITS: string;
    static MEDIUM: string;
    static MEIJI: TruffleString;
    static MICROSECONDS: string;
    static MICROSECONDS_DISPLAY: string;
    static MILLISECONDS: string;
    static MILLISECONDS_DISPLAY: string;
    static MIN2: string;
    static MINGUO: TruffleString;
    static MINGUO_QIAN: TruffleString;
    static MINIMUM_FRACTION_DIGITS: string;
    static MINIMUM_INTEGER_DIGITS: string;
    static MINIMUM_SIGNIFICANT_DIGITS: string;
    static MINUS_SIGN: string;
    static MINUTE: string;
    static MINUTES: string;
    static MINUTES_DISPLAY: string;
    static MONTH: string;
    static MONTHS: string;
    static MONTHS_DISPLAY: string;
    static MORE_PRECISION: string;
    static MUNDI: TruffleString;
    static NAME: string;
    static NANOSECONDS: string;
    static NANOSECONDS_DISPLAY: string;
    static NARROW: string;
    static NARROW_SYMBOL: string;
    static NEGATIVE: string;
    static NEVER: string;
    static NEXT: string;
    static NONE: string;
    static NOTATION: string;
    static NUMBERING_SYSTEM: string;
    static NUMERIC: string;
    static ORDINAL: string;
    static PERCENT: string;
    static PLURAL_CATEGORIES: string;
    static PLUS_SIGN: string;
    static PREVIOUS: string;
    static QUARTER: string;
    static REGION: string;
    static REIWA: TruffleString;
    static ROC: TruffleString;
    static ROUNDING_INCREMENT: string;
    static ROUNDING_MODE: string;
    static ROUNDING_PRIORITY: string;
    static RTL: string;
    static SCIENTIFIC: string;
    static SCRIPT: string;
    static SEARCH: string;
    static SECOND: string;
    static SECONDS: string;
    static SECONDS_DISPLAY: string;
    static SEGMENT: string;
    static SENSITIVITY: string;
    static SENTENCE: string;
    static SHAKA: TruffleString;
    static SHARED: string;
    static SHORT: string;
    static SHORT_GENERIC: string;
    static SHORT_OFFSET: string;
    static SHOWA: TruffleString;
    static SIGNIFICANT_DIGITS: string;
    static SIGN_DISPLAY: string;
    static SORT: string;
    static SOURCE: string;
    static STANDARD: string;
    static START_RANGE: string;
    static STRICT: string;
    static STRIP_IF_INTEGER: string;
    static STYLE: string;
    static SYMBOL: string;
    static TAISHO: TruffleString;
    static TIME_STYLE: string;
    static TIME_ZONE: string;
    static TIME_ZONE_NAME: string;
    static TRAILING_ZERO_DISPLAY: string;
    static TRUNC: string;
    static TYPE: string;
    static UND: string;
    static UNIT: string;
    static UNIT_DISPLAY: string;
    static UPPER: string;
    static USAGE: string;
    static USE_GROUPING: string;
    static VALUE: string;
    static VARIANT: string;
    static VARIANTS: string;
    static WEEKDAY: string;
    static WEEKEND: string;
    static WEEKS: string;
    static WEEKS_DISPLAY: string;
    static WEEK_OF_YEAR: string;
    static WORD: string;
    static YEAR: string;
    static YEARS: string;
    static YEARS_DISPLAY: string;
    static YEAR_NAME: string;
    static _2_DIGIT: string;
    static availableCalendars(): string[];
    static availableCalendars(paramlocale: ULocale, paramcommonlyUsed: boolean): string[];
    static availableCollations(): string[];
    static availableCollations(paramlocale: ULocale, paramcommonOnly: boolean): string[];
    static availableCurrencies(): string[];
    static availableNumberingSystems(paramcontext: JSContext): string[];
    static availableTimeZones(): string[];
    static availableUnits(): string[];
    static bestAvailableLocale(paramcontext: JSContext, paramlocale: Locale): Locale;
    static calendarSupportsEra(paramcalendarID: TruffleString): boolean;
    static calendarSupportsEra(paramcal: Calendar): boolean;
    static canonicalizeCalendar(paramid: string): string;
    static canonicalizeCalendar(paramid: string, paramthrowForUnsupported: boolean): string;
    static canonicalizeEraInCalendar(paramcal: Calendar, paramera: TruffleString): number;
    static canonicalizeLanguageTag(paramlanguageTag: string): string;
    static defaultNumberingSystemName(paramcontext: JSContext, paramlocale: Locale): string;
    static ensureIsStructurallyValidCalendar(paramcalendar: string): void;
    static ensureIsStructurallyValidLanguageId(paramlanguageId: string): void;
    static ensureIsStructurallyValidLanguageSubtag(paramregion: string): void;
    static ensureIsStructurallyValidRegionSubtag(paramregion: string): void;
    static ensureIsStructurallyValidScriptSubtag(paramscript: string): void;
    static ensureIsStructurallyValidVariantSubtag(paramvariant: string): void;
    static ensureIsWellFormedCurrencyCode(paramcurrency: string): void;
    static ensureIsWellFormedUnitIdentifier(paramunitIdentifier: string): void;
    static getCalendar(paramcalendarID: TruffleString): Calendar;
    static getCalendar(paramcalendarID: TruffleString, paramyear: number, parammonth: number, paramday: number): Calendar;
    static getCalendarField(paramcal: Calendar, paramfield: number): number;
    static getCalendarFieldMax(paramcal: Calendar, paramfield: number): number;
    static getDayOfWeek(paramcal: Calendar): number;
    static getEra(paramcal: Calendar): Object;
    static getEraYear(paramcal: Calendar): Object;
    static getExtendedYear(paramcal: Calendar): number;
    static getICUTimeZone(paramtzId: string, paramcontext: JSContext): TimeZone;
    static getICUTimeZone(paramzoneId: ZoneId, paramcontext: JSContext): TimeZone;
    static getICUTimeZoneForOffset(paramtzOffset: string): TimeZone;
    static getTemporalMonthCode(paramcal: Calendar): string;
    static hasLeapYears(paramcal: Calendar): boolean;
    static isLeapYear(paramcal: Calendar): boolean;
    static isValidNumberingSystem(paramnumberingSystem: string): boolean;
    static isWellFormedCurrencyCode(paramcurrency: string): boolean;
    static lookupMatcher(paramctx: JSContext, paramrequestedLocales: string[]): Locale;
    static makePart(paramcontext: JSContext, paramrealm: JSRealm, paramtype: string, paramvalue: string): JSObject;
    static makePart(paramcontext: JSContext, paramrealm: JSRealm, paramtype: string, paramvalue: string, paramunit: string): JSObject;
    static makePart(paramcontext: JSContext, paramrealm: JSRealm, paramtype: string, paramvalue: string, paramunit: string, paramsource: string): JSObject;
    static maybeAppendMissingLanguageSubTag(paramtag: string): string;
    static normalizeCAType(paramtype: string): string;
    static normalizeCAType(paramtype: string, paramfallbackForIslamic: boolean): string;
    static normalizeCollation(paramcollation: string): string;
    static normalizeUnicodeLocaleIdentifierType(paramtype: string): string;
    static selectedLocale(paramctx: JSContext, paramlocales: string[]): Locale;
    static selectedLocaleStripped(paramctx: JSContext, paramlocales: string[]): Locale;
    static setExtendedYear(paramcal: Calendar, paramyear: number): void;
    static setOrdinalMonth(paramcal: Calendar, parammonth: number): void;
    static sourceString(paramstart: number, paramlimit: number, paramstartRangeStart: number, paramstartRangeLimit: number, paramendRangeStart: number, paramendRangeLimit: number): string;
    static supportedLocales(paramctx: JSContext, paramrequestedLocales: string[], parammatcher: string): Object[];
    static toJSHourCycle(paramhourCycle: DateFormat$HourCycle): string;
    static toLowerCase(paramctx: JSContext, params: string, paramlocales: string[]): string;
    static toUpperCase(paramctx: JSContext, params: string, paramlocales: string[]): string;
    static toUpperCase(paramin: string): string;
    static validateAndCanonicalizeLanguageTag(paramlanguageTag: string): string;
    static validateUnicodeLocaleIdentifierType(paramtype: string, paramerrorBranch: BranchProfile): void;
    private constructor()
}