import type { Externalizable } from '../../java/io/Externalizable.d.ts'
import type { ObjectInput } from '../../java/io/ObjectInput.d.ts'
import type { ObjectOutput } from '../../java/io/ObjectOutput.d.ts'
import type { ByteBuffer } from '../../java/nio/ByteBuffer.d.ts'
import type { DoubleBuffer } from '../../java/nio/DoubleBuffer.d.ts'
import type { FloatBuffer } from '../../java/nio/FloatBuffer.d.ts'
import type { NumberFormat } from '../../java/text/NumberFormat.d.ts'
import type { Object } from '../../java/lang/Object.d.ts'
import type { Cloneable } from '../../java/lang/Cloneable.d.ts'
import type { AxisAngle4d } from '../../org/joml/AxisAngle4d.d.ts'
import type { AxisAngle4f } from '../../org/joml/AxisAngle4f.d.ts'
import type { Matrix3d } from '../../org/joml/Matrix3d.d.ts'
import type { Matrix3dc } from '../../org/joml/Matrix3dc.d.ts'
import type { Matrix3fc } from '../../org/joml/Matrix3fc.d.ts'
import type { Matrix4d } from '../../org/joml/Matrix4d.d.ts'
import type { Matrix4dc } from '../../org/joml/Matrix4dc.d.ts'
import type { Matrix4x3dc } from '../../org/joml/Matrix4x3dc.d.ts'
import type { Matrix4x3fc } from '../../org/joml/Matrix4x3fc.d.ts'
import type { Quaterniond } from '../../org/joml/Quaterniond.d.ts'
import type { Quaterniondc } from '../../org/joml/Quaterniondc.d.ts'
import type { Quaternionf } from '../../org/joml/Quaternionf.d.ts'
import type { Quaternionfc } from '../../org/joml/Quaternionfc.d.ts'
import type { Vector3d } from '../../org/joml/Vector3d.d.ts'
import type { Vector3dc } from '../../org/joml/Vector3dc.d.ts'
import type { Vector3fc } from '../../org/joml/Vector3fc.d.ts'
import type { Vector4d } from '../../org/joml/Vector4d.d.ts'
import type { Vector4dc } from '../../org/joml/Vector4dc.d.ts'
export class Matrix4x3d extends Object implements Externalizable, Cloneable, Matrix4x3dc {
    static PLANE_NX: number;
    static PLANE_NY: number;
    static PLANE_NZ: number;
    static PLANE_PX: number;
    static PLANE_PY: number;
    static PLANE_PZ: number;
    static PROPERTY_IDENTITY: number;
    static PROPERTY_ORTHONORMAL: number;
    static PROPERTY_TRANSLATION: number;
    static PROPERTY_UNKNOWN: number;
    constructor()
    constructor(arg0: DoubleBuffer)
    constructor(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number)
    constructor(arg0: Matrix3dc)
    constructor(arg0: Matrix3fc)
    constructor(arg0: Matrix4x3dc)
    constructor(arg0: Matrix4x3fc)
    // private m00: number;
    // private m01: number;
    // private m02: number;
    // private m10: number;
    // private m11: number;
    // private m12: number;
    // private m20: number;
    // private m21: number;
    // private m22: number;
    // private m30: number;
    // private m31: number;
    // private m32: number;
    // private properties: number;
    _m00(arg0: number): Matrix4x3d;
    _m01(arg0: number): Matrix4x3d;
    _m02(arg0: number): Matrix4x3d;
    _m10(arg0: number): Matrix4x3d;
    _m11(arg0: number): Matrix4x3d;
    _m12(arg0: number): Matrix4x3d;
    _m20(arg0: number): Matrix4x3d;
    _m21(arg0: number): Matrix4x3d;
    _m22(arg0: number): Matrix4x3d;
    _m30(arg0: number): Matrix4x3d;
    _m31(arg0: number): Matrix4x3d;
    _m32(arg0: number): Matrix4x3d;
    _properties(arg0: number): Matrix4x3d;
    add(arg0: Matrix4x3dc): Matrix4x3d;
    add(arg0: Matrix4x3dc, arg1: Matrix4x3d): Matrix4x3d;
    add(arg0: Matrix4x3fc): Matrix4x3d;
    add(arg0: Matrix4x3fc, arg1: Matrix4x3d): Matrix4x3d;
    arcball(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix4x3d;
    arcball(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4x3d): Matrix4x3d;
    arcball(arg0: number, arg1: Vector3dc, arg2: number, arg3: number): Matrix4x3d;
    arcball(arg0: number, arg1: Vector3dc, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    assume(arg0: number): Matrix4x3d;
    billboardCylindrical(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3dc): Matrix4x3d;
    billboardSpherical(arg0: Vector3dc, arg1: Vector3dc): Matrix4x3d;
    billboardSpherical(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3dc): Matrix4x3d;
    protected clone(): Object;
    clone(): Object;
    cofactor3x3(): Matrix4x3d;
    cofactor3x3(arg0: Matrix3d): Matrix3d;
    cofactor3x3(arg0: Matrix4x3d): Matrix4x3d;
    determinant(): number;
    determineProperties(): Matrix4x3d;
    equals(arg0: Object | null): boolean;
    equals(arg0: Matrix4x3dc, arg1: number): boolean;
    fma(arg0: Matrix4x3dc, arg1: number): Matrix4x3d;
    fma(arg0: Matrix4x3dc, arg1: number, arg2: Matrix4x3d): Matrix4x3d;
    fma(arg0: Matrix4x3fc, arg1: number): Matrix4x3d;
    fma(arg0: Matrix4x3fc, arg1: number, arg2: Matrix4x3d): Matrix4x3d;
    frustumPlane(arg0: number, arg1: Vector4d): Vector4d;
    get(arg0: ByteBuffer): ByteBuffer;
    get(arg0: DoubleBuffer): DoubleBuffer;
    get(arg0: FloatBuffer): FloatBuffer;
    get(arg0: number[]): number[];
    get(arg0: number[], arg1: number): number[];
    get(arg0: number, arg1: ByteBuffer): ByteBuffer;
    get(arg0: number, arg1: DoubleBuffer): DoubleBuffer;
    get(arg0: number, arg1: FloatBuffer): FloatBuffer;
    get(arg0: Matrix4d): Matrix4d;
    get(arg0: Matrix4x3d): Matrix4x3d;
    get4x4(arg0: ByteBuffer): ByteBuffer;
    get4x4(arg0: DoubleBuffer): DoubleBuffer;
    get4x4(arg0: number[]): number[];
    get4x4(arg0: number[], arg1: number): number[];
    get4x4(arg0: number, arg1: ByteBuffer): ByteBuffer;
    get4x4(arg0: number, arg1: DoubleBuffer): DoubleBuffer;
    getColumn(arg0: number, arg1: Vector3d): Vector3d;
    getEulerAnglesXYZ(arg0: Vector3d): Vector3d;
    getEulerAnglesYXZ(arg0: Vector3d): Vector3d;
    getEulerAnglesZYX(arg0: Vector3d): Vector3d;
    getFloats(arg0: ByteBuffer): ByteBuffer;
    getFloats(arg0: number, arg1: ByteBuffer): ByteBuffer;
    getNormalizedRotation(arg0: Quaterniond): Quaterniond;
    getNormalizedRotation(arg0: Quaternionf): Quaternionf;
    getRow(arg0: number, arg1: Vector4d): Vector4d;
    getScale(arg0: Vector3d): Vector3d;
    getToAddress(arg0: number): Matrix4x3dc;
    getTranslation(arg0: Vector3d): Vector3d;
    getTransposed(arg0: ByteBuffer): ByteBuffer;
    getTransposed(arg0: DoubleBuffer): DoubleBuffer;
    getTransposed(arg0: FloatBuffer): FloatBuffer;
    getTransposed(arg0: number[]): number[];
    getTransposed(arg0: number[], arg1: number): number[];
    getTransposed(arg0: number, arg1: ByteBuffer): ByteBuffer;
    getTransposed(arg0: number, arg1: DoubleBuffer): DoubleBuffer;
    getTransposed(arg0: number, arg1: FloatBuffer): FloatBuffer;
    getTransposedFloats(arg0: ByteBuffer): ByteBuffer;
    getTransposedFloats(arg0: number, arg1: ByteBuffer): ByteBuffer;
    getTransposedToAddress(arg0: number): Matrix4x3dc;
    getUnnormalizedRotation(arg0: Quaterniond): Quaterniond;
    getUnnormalizedRotation(arg0: Quaternionf): Quaternionf;
    hashCode(): number;
    identity(): Matrix4x3d;
    invert(): Matrix4x3d;
    invert(arg0: Matrix4x3d): Matrix4x3d;
    // private invertGeneric(arg0: Matrix4x3d): Matrix4x3d;
    invertOrtho(): Matrix4x3d;
    invertOrtho(arg0: Matrix4x3d): Matrix4x3d;
    // private invertOrthonormal(arg0: Matrix4x3d): Matrix4x3d;
    isFinite(): boolean;
    lerp(arg0: Matrix4x3dc, arg1: number): Matrix4x3d;
    lerp(arg0: Matrix4x3dc, arg1: number, arg2: Matrix4x3d): Matrix4x3d;
    lookAlong(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix4x3d;
    lookAlong(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4x3d): Matrix4x3d;
    lookAlong(arg0: Vector3dc, arg1: Vector3dc): Matrix4x3d;
    lookAlong(arg0: Vector3dc, arg1: Vector3dc, arg2: Matrix4x3d): Matrix4x3d;
    lookAt(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Matrix4x3d;
    lookAt(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4x3d): Matrix4x3d;
    lookAt(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3dc): Matrix4x3d;
    lookAt(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3dc, arg3: Matrix4x3d): Matrix4x3d;
    // private lookAtGeneric(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4x3d): Matrix4x3d;
    lookAtLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Matrix4x3d;
    lookAtLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4x3d): Matrix4x3d;
    lookAtLH(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3dc): Matrix4x3d;
    lookAtLH(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3dc, arg3: Matrix4x3d): Matrix4x3d;
    // private lookAtLHGeneric(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4x3d): Matrix4x3d;
    m00(): number;
    m00(arg0: number): Matrix4x3d;
    m01(): number;
    m01(arg0: number): Matrix4x3d;
    m02(): number;
    m02(arg0: number): Matrix4x3d;
    m10(): number;
    m10(arg0: number): Matrix4x3d;
    m11(): number;
    m11(arg0: number): Matrix4x3d;
    m12(): number;
    m12(arg0: number): Matrix4x3d;
    m20(): number;
    m20(arg0: number): Matrix4x3d;
    m21(): number;
    m21(arg0: number): Matrix4x3d;
    m22(): number;
    m22(arg0: number): Matrix4x3d;
    m30(): number;
    m30(arg0: number): Matrix4x3d;
    m31(): number;
    m31(arg0: number): Matrix4x3d;
    m32(): number;
    m32(arg0: number): Matrix4x3d;
    mapXZY(): Matrix4x3d;
    mapXZY(arg0: Matrix4x3d): Matrix4x3d;
    mapXZnY(): Matrix4x3d;
    mapXZnY(arg0: Matrix4x3d): Matrix4x3d;
    mapXnYnZ(): Matrix4x3d;
    mapXnYnZ(arg0: Matrix4x3d): Matrix4x3d;
    mapXnZY(): Matrix4x3d;
    mapXnZY(arg0: Matrix4x3d): Matrix4x3d;
    mapXnZnY(): Matrix4x3d;
    mapXnZnY(arg0: Matrix4x3d): Matrix4x3d;
    mapYXZ(): Matrix4x3d;
    mapYXZ(arg0: Matrix4x3d): Matrix4x3d;
    mapYXnZ(): Matrix4x3d;
    mapYXnZ(arg0: Matrix4x3d): Matrix4x3d;
    mapYZX(): Matrix4x3d;
    mapYZX(arg0: Matrix4x3d): Matrix4x3d;
    mapYZnX(): Matrix4x3d;
    mapYZnX(arg0: Matrix4x3d): Matrix4x3d;
    mapYnXZ(): Matrix4x3d;
    mapYnXZ(arg0: Matrix4x3d): Matrix4x3d;
    mapYnXnZ(): Matrix4x3d;
    mapYnXnZ(arg0: Matrix4x3d): Matrix4x3d;
    mapYnZX(): Matrix4x3d;
    mapYnZX(arg0: Matrix4x3d): Matrix4x3d;
    mapYnZnX(): Matrix4x3d;
    mapYnZnX(arg0: Matrix4x3d): Matrix4x3d;
    mapZXY(): Matrix4x3d;
    mapZXY(arg0: Matrix4x3d): Matrix4x3d;
    mapZXnY(): Matrix4x3d;
    mapZXnY(arg0: Matrix4x3d): Matrix4x3d;
    mapZYX(): Matrix4x3d;
    mapZYX(arg0: Matrix4x3d): Matrix4x3d;
    mapZYnX(): Matrix4x3d;
    mapZYnX(arg0: Matrix4x3d): Matrix4x3d;
    mapZnXY(): Matrix4x3d;
    mapZnXY(arg0: Matrix4x3d): Matrix4x3d;
    mapZnXnY(): Matrix4x3d;
    mapZnXnY(arg0: Matrix4x3d): Matrix4x3d;
    mapZnYX(): Matrix4x3d;
    mapZnYX(arg0: Matrix4x3d): Matrix4x3d;
    mapZnYnX(): Matrix4x3d;
    mapZnYnX(arg0: Matrix4x3d): Matrix4x3d;
    mapnXYnZ(): Matrix4x3d;
    mapnXYnZ(arg0: Matrix4x3d): Matrix4x3d;
    mapnXZY(): Matrix4x3d;
    mapnXZY(arg0: Matrix4x3d): Matrix4x3d;
    mapnXZnY(): Matrix4x3d;
    mapnXZnY(arg0: Matrix4x3d): Matrix4x3d;
    mapnXnYZ(): Matrix4x3d;
    mapnXnYZ(arg0: Matrix4x3d): Matrix4x3d;
    mapnXnYnZ(): Matrix4x3d;
    mapnXnYnZ(arg0: Matrix4x3d): Matrix4x3d;
    mapnXnZY(): Matrix4x3d;
    mapnXnZY(arg0: Matrix4x3d): Matrix4x3d;
    mapnXnZnY(): Matrix4x3d;
    mapnXnZnY(arg0: Matrix4x3d): Matrix4x3d;
    mapnYXZ(): Matrix4x3d;
    mapnYXZ(arg0: Matrix4x3d): Matrix4x3d;
    mapnYXnZ(): Matrix4x3d;
    mapnYXnZ(arg0: Matrix4x3d): Matrix4x3d;
    mapnYZX(): Matrix4x3d;
    mapnYZX(arg0: Matrix4x3d): Matrix4x3d;
    mapnYZnX(): Matrix4x3d;
    mapnYZnX(arg0: Matrix4x3d): Matrix4x3d;
    mapnYnXZ(): Matrix4x3d;
    mapnYnXZ(arg0: Matrix4x3d): Matrix4x3d;
    mapnYnXnZ(): Matrix4x3d;
    mapnYnXnZ(arg0: Matrix4x3d): Matrix4x3d;
    mapnYnZX(): Matrix4x3d;
    mapnYnZX(arg0: Matrix4x3d): Matrix4x3d;
    mapnYnZnX(): Matrix4x3d;
    mapnYnZnX(arg0: Matrix4x3d): Matrix4x3d;
    mapnZXY(): Matrix4x3d;
    mapnZXY(arg0: Matrix4x3d): Matrix4x3d;
    mapnZXnY(): Matrix4x3d;
    mapnZXnY(arg0: Matrix4x3d): Matrix4x3d;
    mapnZYX(): Matrix4x3d;
    mapnZYX(arg0: Matrix4x3d): Matrix4x3d;
    mapnZYnX(): Matrix4x3d;
    mapnZYnX(arg0: Matrix4x3d): Matrix4x3d;
    mapnZnXY(): Matrix4x3d;
    mapnZnXY(arg0: Matrix4x3d): Matrix4x3d;
    mapnZnXnY(): Matrix4x3d;
    mapnZnXnY(arg0: Matrix4x3d): Matrix4x3d;
    mapnZnYX(): Matrix4x3d;
    mapnZnYX(arg0: Matrix4x3d): Matrix4x3d;
    mapnZnYnX(): Matrix4x3d;
    mapnZnYnX(arg0: Matrix4x3d): Matrix4x3d;
    mul(arg0: Matrix4x3dc): Matrix4x3d;
    mul(arg0: Matrix4x3dc, arg1: Matrix4x3d): Matrix4x3d;
    mul(arg0: Matrix4x3fc): Matrix4x3d;
    mul(arg0: Matrix4x3fc, arg1: Matrix4x3d): Matrix4x3d;
    mul3x3(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Matrix4x3d;
    mul3x3(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4x3d): Matrix4x3d;
    mulComponentWise(arg0: Matrix4x3dc): Matrix4x3d;
    mulComponentWise(arg0: Matrix4x3dc, arg1: Matrix4x3d): Matrix4x3d;
    // private mulGeneric(arg0: Matrix4x3dc, arg1: Matrix4x3d): Matrix4x3d;
    // private mulGeneric(arg0: Matrix4x3fc, arg1: Matrix4x3d): Matrix4x3d;
    mulOrtho(arg0: Matrix4x3dc): Matrix4x3d;
    mulOrtho(arg0: Matrix4x3dc, arg1: Matrix4x3d): Matrix4x3d;
    mulTranslation(arg0: Matrix4x3dc, arg1: Matrix4x3d): Matrix4x3d;
    mulTranslation(arg0: Matrix4x3fc, arg1: Matrix4x3d): Matrix4x3d;
    negateX(): Matrix4x3d;
    negateX(arg0: Matrix4x3d): Matrix4x3d;
    negateY(): Matrix4x3d;
    negateY(arg0: Matrix4x3d): Matrix4x3d;
    negateZ(): Matrix4x3d;
    negateZ(arg0: Matrix4x3d): Matrix4x3d;
    normal(): Matrix4x3d;
    normal(arg0: Matrix3d): Matrix3d;
    normal(arg0: Matrix4x3d): Matrix4x3d;
    // private normalGeneric(arg0: Matrix3d): Matrix3d;
    // private normalGeneric(arg0: Matrix4x3d): Matrix4x3d;
    // private normalOrthonormal(arg0: Matrix3d): Matrix3d;
    // private normalOrthonormal(arg0: Matrix4x3d): Matrix4x3d;
    normalize3x3(): Matrix4x3d;
    normalize3x3(arg0: Matrix3d): Matrix3d;
    normalize3x3(arg0: Matrix4x3d): Matrix4x3d;
    normalizedPositiveX(arg0: Vector3d): Vector3d;
    normalizedPositiveY(arg0: Vector3d): Vector3d;
    normalizedPositiveZ(arg0: Vector3d): Vector3d;
    obliqueZ(arg0: number, arg1: number): Matrix4x3d;
    obliqueZ(arg0: number, arg1: number, arg2: Matrix4x3d): Matrix4x3d;
    origin(arg0: Vector3d): Vector3d;
    ortho(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix4x3d;
    ortho(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean): Matrix4x3d;
    ortho(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4x3d): Matrix4x3d;
    ortho(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4x3d): Matrix4x3d;
    ortho2D(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    ortho2D(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    ortho2DLH(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    ortho2DLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    orthoLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix4x3d;
    orthoLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean): Matrix4x3d;
    orthoLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4x3d): Matrix4x3d;
    orthoLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4x3d): Matrix4x3d;
    orthoSymmetric(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    orthoSymmetric(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean): Matrix4x3d;
    orthoSymmetric(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean, arg5: Matrix4x3d): Matrix4x3d;
    orthoSymmetric(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    orthoSymmetricLH(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    orthoSymmetricLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean): Matrix4x3d;
    orthoSymmetricLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean, arg5: Matrix4x3d): Matrix4x3d;
    orthoSymmetricLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    pick(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number[]): Matrix4x3d;
    pick(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number[], arg5: Matrix4x3d): Matrix4x3d;
    positiveX(arg0: Vector3d): Vector3d;
    positiveY(arg0: Vector3d): Vector3d;
    positiveZ(arg0: Vector3d): Vector3d;
    properties(): number;
    readExternal(arg0: ObjectInput): void;
    reflect(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    reflect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix4x3d;
    reflect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4x3d): Matrix4x3d;
    reflect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    reflect(arg0: Quaterniondc, arg1: Vector3dc): Matrix4x3d;
    reflect(arg0: Quaterniondc, arg1: Vector3dc, arg2: Matrix4x3d): Matrix4x3d;
    reflect(arg0: Vector3dc, arg1: Vector3dc): Matrix4x3d;
    reflect(arg0: Vector3dc, arg1: Vector3dc, arg2: Matrix4x3d): Matrix4x3d;
    reflection(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    reflection(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix4x3d;
    reflection(arg0: Quaterniondc, arg1: Vector3dc): Matrix4x3d;
    reflection(arg0: Vector3dc, arg1: Vector3dc): Matrix4x3d;
    rotate(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    rotate(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    rotate(arg0: number, arg1: Vector3dc): Matrix4x3d;
    rotate(arg0: number, arg1: Vector3dc, arg2: Matrix4x3d): Matrix4x3d;
    rotate(arg0: number, arg1: Vector3fc): Matrix4x3d;
    rotate(arg0: number, arg1: Vector3fc, arg2: Matrix4x3d): Matrix4x3d;
    rotate(arg0: AxisAngle4d): Matrix4x3d;
    rotate(arg0: AxisAngle4d, arg1: Matrix4x3d): Matrix4x3d;
    rotate(arg0: AxisAngle4f): Matrix4x3d;
    rotate(arg0: AxisAngle4f, arg1: Matrix4x3d): Matrix4x3d;
    rotate(arg0: Quaterniondc): Matrix4x3d;
    rotate(arg0: Quaterniondc, arg1: Matrix4x3d): Matrix4x3d;
    rotate(arg0: Quaternionfc): Matrix4x3d;
    rotate(arg0: Quaternionfc, arg1: Matrix4x3d): Matrix4x3d;
    rotateAround(arg0: Quaterniondc, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    rotateAround(arg0: Quaterniondc, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    // private rotateAroundAffine(arg0: Quaterniondc, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    // private rotateGeneric(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    // private rotateGeneric(arg0: Quaterniondc, arg1: Matrix4x3d): Matrix4x3d;
    // private rotateGeneric(arg0: Quaternionfc, arg1: Matrix4x3d): Matrix4x3d;
    // private rotateGenericInternal(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    rotateLocal(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    rotateLocal(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    rotateLocal(arg0: Quaterniondc): Matrix4x3d;
    rotateLocal(arg0: Quaterniondc, arg1: Matrix4x3d): Matrix4x3d;
    rotateLocal(arg0: Quaternionfc): Matrix4x3d;
    rotateLocal(arg0: Quaternionfc, arg1: Matrix4x3d): Matrix4x3d;
    // private rotateLocalInternal(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    rotateLocalX(arg0: number): Matrix4x3d;
    rotateLocalX(arg0: number, arg1: Matrix4x3d): Matrix4x3d;
    rotateLocalY(arg0: number): Matrix4x3d;
    rotateLocalY(arg0: number, arg1: Matrix4x3d): Matrix4x3d;
    rotateLocalZ(arg0: number): Matrix4x3d;
    rotateLocalZ(arg0: number, arg1: Matrix4x3d): Matrix4x3d;
    rotateTowards(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix4x3d;
    rotateTowards(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4x3d): Matrix4x3d;
    rotateTowards(arg0: Vector3dc, arg1: Vector3dc): Matrix4x3d;
    rotateTowards(arg0: Vector3dc, arg1: Vector3dc, arg2: Matrix4x3d): Matrix4x3d;
    rotateTranslation(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    rotateTranslation(arg0: Quaterniondc, arg1: Matrix4x3d): Matrix4x3d;
    rotateTranslation(arg0: Quaternionfc, arg1: Matrix4x3d): Matrix4x3d;
    // private rotateTranslationInternal(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    rotateX(arg0: number): Matrix4x3d;
    rotateX(arg0: number, arg1: Matrix4x3d): Matrix4x3d;
    // private rotateXInternal(arg0: number, arg1: Matrix4x3d): Matrix4x3d;
    rotateXYZ(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    rotateXYZ(arg0: number, arg1: number, arg2: number, arg3: Matrix4x3d): Matrix4x3d;
    rotateXYZ(arg0: Vector3d): Matrix4x3d;
    // private rotateXYZInternal(arg0: number, arg1: number, arg2: number, arg3: Matrix4x3d): Matrix4x3d;
    rotateY(arg0: number): Matrix4x3d;
    rotateY(arg0: number, arg1: Matrix4x3d): Matrix4x3d;
    // private rotateYInternal(arg0: number, arg1: Matrix4x3d): Matrix4x3d;
    rotateYXZ(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    rotateYXZ(arg0: number, arg1: number, arg2: number, arg3: Matrix4x3d): Matrix4x3d;
    rotateYXZ(arg0: Vector3d): Matrix4x3d;
    // private rotateYXZInternal(arg0: number, arg1: number, arg2: number, arg3: Matrix4x3d): Matrix4x3d;
    rotateZ(arg0: number): Matrix4x3d;
    rotateZ(arg0: number, arg1: Matrix4x3d): Matrix4x3d;
    // private rotateZInternal(arg0: number, arg1: Matrix4x3d): Matrix4x3d;
    rotateZYX(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    rotateZYX(arg0: number, arg1: number, arg2: number, arg3: Matrix4x3d): Matrix4x3d;
    rotateZYX(arg0: Vector3d): Matrix4x3d;
    // private rotateZYXInternal(arg0: number, arg1: number, arg2: number, arg3: Matrix4x3d): Matrix4x3d;
    rotation(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    rotation(arg0: number, arg1: Vector3dc): Matrix4x3d;
    rotation(arg0: number, arg1: Vector3fc): Matrix4x3d;
    rotation(arg0: AxisAngle4d): Matrix4x3d;
    rotation(arg0: AxisAngle4f): Matrix4x3d;
    rotation(arg0: Quaterniondc): Matrix4x3d;
    rotation(arg0: Quaternionfc): Matrix4x3d;
    rotationAround(arg0: Quaterniondc, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    // private rotationInternal(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    rotationTowards(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix4x3d;
    rotationTowards(arg0: Vector3dc, arg1: Vector3dc): Matrix4x3d;
    rotationX(arg0: number): Matrix4x3d;
    rotationXYZ(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    rotationY(arg0: number): Matrix4x3d;
    rotationYXZ(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    rotationZ(arg0: number): Matrix4x3d;
    rotationZYX(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    scale(arg0: number): Matrix4x3d;
    scale(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    scale(arg0: number, arg1: number, arg2: number, arg3: Matrix4x3d): Matrix4x3d;
    scale(arg0: number, arg1: Matrix4x3d): Matrix4x3d;
    scale(arg0: Vector3dc): Matrix4x3d;
    scale(arg0: Vector3dc, arg1: Matrix4x3d): Matrix4x3d;
    scaleAround(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    scaleAround(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix4x3d;
    scaleAround(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4x3d): Matrix4x3d;
    scaleAround(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3d): Matrix4x3d;
    // private scaleGeneric(arg0: number, arg1: number, arg2: number, arg3: Matrix4x3d): Matrix4x3d;
    scaleLocal(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    scaleLocal(arg0: number, arg1: number, arg2: number, arg3: Matrix4x3d): Matrix4x3d;
    scaleXY(arg0: number, arg1: number): Matrix4x3d;
    scaleXY(arg0: number, arg1: number, arg2: Matrix4x3d): Matrix4x3d;
    scaling(arg0: number): Matrix4x3d;
    scaling(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    scaling(arg0: Vector3dc): Matrix4x3d;
    set(arg0: ByteBuffer): Matrix4x3d;
    set(arg0: DoubleBuffer): Matrix4x3d;
    set(arg0: FloatBuffer): Matrix4x3d;
    set(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number): Matrix4x3d;
    set(arg0: number[]): Matrix4x3d;
    set(arg0: number[], arg1: number): Matrix4x3d;
    set(arg0: number, arg1: ByteBuffer): Matrix4x3d;
    set(arg0: number, arg1: DoubleBuffer): Matrix4x3d;
    set(arg0: number, arg1: FloatBuffer): Matrix4x3d;
    set(arg0: AxisAngle4d): Matrix4x3d;
    set(arg0: AxisAngle4f): Matrix4x3d;
    set(arg0: Matrix3dc): Matrix4x3d;
    set(arg0: Matrix3fc): Matrix4x3d;
    set(arg0: Matrix4dc): Matrix4x3d;
    set(arg0: Matrix4x3dc): Matrix4x3d;
    set(arg0: Matrix4x3fc): Matrix4x3d;
    set(arg0: Quaterniondc): Matrix4x3d;
    set(arg0: Quaternionfc): Matrix4x3d;
    set(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3dc, arg3: Vector3dc): Matrix4x3d;
    set3x3(arg0: Matrix3dc): Matrix4x3d;
    set3x3(arg0: Matrix3fc): Matrix4x3d;
    set3x3(arg0: Matrix4x3dc): Matrix4x3d;
    setColumn(arg0: number, arg1: Vector3dc): Matrix4x3d;
    setFloats(arg0: ByteBuffer): Matrix4x3d;
    setFloats(arg0: number, arg1: ByteBuffer): Matrix4x3d;
    setFromAddress(arg0: number): Matrix4x3d;
    setLookAlong(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix4x3d;
    setLookAlong(arg0: Vector3dc, arg1: Vector3dc): Matrix4x3d;
    setLookAt(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Matrix4x3d;
    setLookAt(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3dc): Matrix4x3d;
    setLookAtLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Matrix4x3d;
    setLookAtLH(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3dc): Matrix4x3d;
    setOrtho(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix4x3d;
    setOrtho(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean): Matrix4x3d;
    setOrtho2D(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    setOrtho2DLH(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    setOrthoLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix4x3d;
    setOrthoLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean): Matrix4x3d;
    setOrthoSymmetric(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    setOrthoSymmetric(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean): Matrix4x3d;
    setOrthoSymmetricLH(arg0: number, arg1: number, arg2: number, arg3: number): Matrix4x3d;
    setOrthoSymmetricLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean): Matrix4x3d;
    setRotationXYZ(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    setRotationYXZ(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    setRotationZYX(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    setRow(arg0: number, arg1: Vector4dc): Matrix4x3d;
    setTranslation(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    setTranslation(arg0: Vector3dc): Matrix4x3d;
    setTransposedFromAddress(arg0: number): Matrix4x3d;
    shadow(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number): Matrix4x3d;
    shadow(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: Matrix4x3d): Matrix4x3d;
    shadow(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3dc): Matrix4x3d;
    shadow(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4x3dc, arg5: Matrix4x3d): Matrix4x3d;
    shadow(arg0: Vector4dc, arg1: number, arg2: number, arg3: number, arg4: number): Matrix4x3d;
    shadow(arg0: Vector4dc, arg1: number, arg2: number, arg3: number, arg4: number, arg5: Matrix4x3d): Matrix4x3d;
    shadow(arg0: Vector4dc, arg1: Matrix4x3dc): Matrix4x3d;
    shadow(arg0: Vector4dc, arg1: Matrix4x3dc, arg2: Matrix4x3d): Matrix4x3d;
    sub(arg0: Matrix4x3dc): Matrix4x3d;
    sub(arg0: Matrix4x3dc, arg1: Matrix4x3d): Matrix4x3d;
    sub(arg0: Matrix4x3fc): Matrix4x3d;
    sub(arg0: Matrix4x3fc, arg1: Matrix4x3d): Matrix4x3d;
    swap(arg0: Matrix4x3d): Matrix4x3d;
    toString(): string;
    toString(arg0: NumberFormat): string;
    transform(arg0: Vector4d): Vector4d;
    transform(arg0: Vector4dc, arg1: Vector4d): Vector4d;
    transformAab(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Vector3d, arg7: Vector3d): Matrix4x3d;
    transformAab(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3d, arg3: Vector3d): Matrix4x3d;
    transformDirection(arg0: Vector3d): Vector3d;
    transformDirection(arg0: Vector3dc, arg1: Vector3d): Vector3d;
    transformPosition(arg0: Vector3d): Vector3d;
    transformPosition(arg0: Vector3dc, arg1: Vector3d): Vector3d;
    translate(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    translate(arg0: number, arg1: number, arg2: number, arg3: Matrix4x3d): Matrix4x3d;
    translate(arg0: Vector3dc): Matrix4x3d;
    translate(arg0: Vector3dc, arg1: Matrix4x3d): Matrix4x3d;
    translate(arg0: Vector3fc): Matrix4x3d;
    translate(arg0: Vector3fc, arg1: Matrix4x3d): Matrix4x3d;
    // private translateGeneric(arg0: number, arg1: number, arg2: number, arg3: Matrix4x3d): Matrix4x3d;
    translateLocal(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    translateLocal(arg0: number, arg1: number, arg2: number, arg3: Matrix4x3d): Matrix4x3d;
    translateLocal(arg0: Vector3dc): Matrix4x3d;
    translateLocal(arg0: Vector3dc, arg1: Matrix4x3d): Matrix4x3d;
    translateLocal(arg0: Vector3fc): Matrix4x3d;
    translateLocal(arg0: Vector3fc, arg1: Matrix4x3d): Matrix4x3d;
    translation(arg0: number, arg1: number, arg2: number): Matrix4x3d;
    translation(arg0: Vector3dc): Matrix4x3d;
    translation(arg0: Vector3fc): Matrix4x3d;
    translationRotate(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): Matrix4x3d;
    translationRotate(arg0: number, arg1: number, arg2: number, arg3: Quaterniondc): Matrix4x3d;
    translationRotate(arg0: Vector3dc, arg1: Quaterniondc): Matrix4x3d;
    translationRotateInvert(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): Matrix4x3d;
    translationRotateInvert(arg0: Vector3dc, arg1: Quaterniondc): Matrix4x3d;
    translationRotateMul(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: Matrix4x3dc): Matrix4x3d;
    translationRotateMul(arg0: number, arg1: number, arg2: number, arg3: Quaternionfc, arg4: Matrix4x3dc): Matrix4x3d;
    translationRotateScale(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number): Matrix4x3d;
    translationRotateScale(arg0: Vector3dc, arg1: Quaterniondc, arg2: Vector3dc): Matrix4x3d;
    translationRotateScale(arg0: Vector3fc, arg1: Quaternionfc, arg2: Vector3fc): Matrix4x3d;
    translationRotateScaleMul(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: Matrix4x3dc): Matrix4x3d;
    translationRotateScaleMul(arg0: Vector3dc, arg1: Quaterniondc, arg2: Vector3dc, arg3: Matrix4x3dc): Matrix4x3d;
    translationRotateTowards(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Matrix4x3d;
    translationRotateTowards(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3dc): Matrix4x3d;
    transpose3x3(): Matrix4x3d;
    transpose3x3(arg0: Matrix3d): Matrix3d;
    transpose3x3(arg0: Matrix4x3d): Matrix4x3d;
    writeExternal(arg0: ObjectOutput): void;
    zero(): Matrix4x3d;
}