import type { ByteBuffer } from '../../java/nio/ByteBuffer.d.ts'
import type { FloatBuffer } from '../../java/nio/FloatBuffer.d.ts'
import type { Object } from '../../java/lang/Object.d.ts'
import type { AxisAngle4d } from '../../org/joml/AxisAngle4d.d.ts'
import type { AxisAngle4f } from '../../org/joml/AxisAngle4f.d.ts'
import type { Matrix3d } from '../../org/joml/Matrix3d.d.ts'
import type { Matrix3f } from '../../org/joml/Matrix3f.d.ts'
import type { Matrix3x2fc } from '../../org/joml/Matrix3x2fc.d.ts'
import type { Matrix4d } from '../../org/joml/Matrix4d.d.ts'
import type { Matrix4f } from '../../org/joml/Matrix4f.d.ts'
import type { Matrix4x3f } from '../../org/joml/Matrix4x3f.d.ts'
import type { Matrix4x3fc } from '../../org/joml/Matrix4x3fc.d.ts'
import type { Quaterniond } from '../../org/joml/Quaterniond.d.ts'
import type { Quaternionf } from '../../org/joml/Quaternionf.d.ts'
import type { Quaternionfc } from '../../org/joml/Quaternionfc.d.ts'
import type { Vector2fc } from '../../org/joml/Vector2fc.d.ts'
import type { Vector3f } from '../../org/joml/Vector3f.d.ts'
import type { Vector3fc } from '../../org/joml/Vector3fc.d.ts'
import type { Vector4f } from '../../org/joml/Vector4f.d.ts'
import type { Vector4fc } from '../../org/joml/Vector4fc.d.ts'
export interface Matrix4fc extends Object{
    add(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    add4x3(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    arcball(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4f): Matrix4f;
    arcball(arg0: number, arg1: Vector3fc, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    cofactor3x3(arg0: Matrix3f): Matrix3f;
    cofactor3x3(arg0: Matrix4f): Matrix4f;
    determinant(): number;
    determinant3x3(): number;
    determinantAffine(): number;
    equals(arg0: Matrix4fc, arg1: number): boolean;
    fma4x3(arg0: Matrix4fc, arg1: number, arg2: Matrix4f): Matrix4f;
    frustum(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4f): Matrix4f;
    frustum(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4f): Matrix4f;
    frustumAabb(arg0: Vector3f, arg1: Vector3f): Matrix4f;
    frustumCorner(arg0: number, arg1: Vector3f): Vector3f;
    frustumLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4f): Matrix4f;
    frustumLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4f): Matrix4f;
    frustumPlane(arg0: number, arg1: Vector4f): Vector4f;
    frustumRayDir(arg0: number, arg1: number, arg2: Vector3f): Vector3f;
    get(arg0: ByteBuffer): ByteBuffer;
    get(arg0: FloatBuffer): FloatBuffer;
    get(arg0: number[]): number[];
    get(arg0: number[], arg1: number): number[];
    get(arg0: number, arg1: ByteBuffer): ByteBuffer;
    get(arg0: number, arg1: FloatBuffer): FloatBuffer;
    get(arg0: number, arg1: number): number;
    get(arg0: Matrix4d): Matrix4d;
    get(arg0: Matrix4f): Matrix4f;
    get3x3(arg0: Matrix3d): Matrix3d;
    get3x3(arg0: Matrix3f): Matrix3f;
    get3x4(arg0: ByteBuffer): ByteBuffer;
    get3x4(arg0: FloatBuffer): FloatBuffer;
    get3x4(arg0: number, arg1: ByteBuffer): ByteBuffer;
    get3x4(arg0: number, arg1: FloatBuffer): FloatBuffer;
    get4x3(arg0: ByteBuffer): ByteBuffer;
    get4x3(arg0: FloatBuffer): FloatBuffer;
    get4x3(arg0: number, arg1: ByteBuffer): ByteBuffer;
    get4x3(arg0: number, arg1: FloatBuffer): FloatBuffer;
    get4x3(arg0: Matrix4x3f): Matrix4x3f;
    get4x3Transposed(arg0: ByteBuffer): ByteBuffer;
    get4x3Transposed(arg0: FloatBuffer): FloatBuffer;
    get4x3Transposed(arg0: number, arg1: ByteBuffer): ByteBuffer;
    get4x3Transposed(arg0: number, arg1: FloatBuffer): FloatBuffer;
    getColumn(arg0: number, arg1: Vector3f): Vector3f;
    getColumn(arg0: number, arg1: Vector4f): Vector4f;
    getEulerAnglesXYZ(arg0: Vector3f): Vector3f;
    getEulerAnglesYXZ(arg0: Vector3f): Vector3f;
    getEulerAnglesZYX(arg0: Vector3f): Vector3f;
    getNormalizedRotation(arg0: Quaterniond): Quaterniond;
    getNormalizedRotation(arg0: Quaternionf): Quaternionf;
    getRotation(arg0: AxisAngle4d): AxisAngle4d;
    getRotation(arg0: AxisAngle4f): AxisAngle4f;
    getRow(arg0: number, arg1: Vector3f): Vector3f;
    getRow(arg0: number, arg1: Vector4f): Vector4f;
    getRowColumn(arg0: number, arg1: number): number;
    getScale(arg0: Vector3f): Vector3f;
    getToAddress(arg0: number): Matrix4fc;
    getTranslation(arg0: Vector3f): Vector3f;
    getTransposed(arg0: ByteBuffer): ByteBuffer;
    getTransposed(arg0: FloatBuffer): FloatBuffer;
    getTransposed(arg0: number, arg1: ByteBuffer): ByteBuffer;
    getTransposed(arg0: number, arg1: FloatBuffer): FloatBuffer;
    getTransposedToAddress(arg0: number): Matrix4fc;
    getUnnormalizedRotation(arg0: Quaterniond): Quaterniond;
    getUnnormalizedRotation(arg0: Quaternionf): Quaternionf;
    invert(arg0: Matrix4f): Matrix4f;
    invertAffine(arg0: Matrix4f): Matrix4f;
    invertFrustum(arg0: Matrix4f): Matrix4f;
    invertOrtho(arg0: Matrix4f): Matrix4f;
    invertPerspective(arg0: Matrix4f): Matrix4f;
    invertPerspectiveView(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    invertPerspectiveView(arg0: Matrix4x3fc, arg1: Matrix4f): Matrix4f;
    isAffine(): boolean;
    isFinite(): boolean;
    lerp(arg0: Matrix4fc, arg1: number, arg2: Matrix4f): Matrix4f;
    lookAlong(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4f): Matrix4f;
    lookAlong(arg0: Vector3fc, arg1: Vector3fc, arg2: Matrix4f): Matrix4f;
    lookAt(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4f): Matrix4f;
    lookAt(arg0: Vector3fc, arg1: Vector3fc, arg2: Vector3fc, arg3: Matrix4f): Matrix4f;
    lookAtLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4f): Matrix4f;
    lookAtLH(arg0: Vector3fc, arg1: Vector3fc, arg2: Vector3fc, arg3: Matrix4f): Matrix4f;
    lookAtPerspective(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4f): Matrix4f;
    lookAtPerspectiveLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4f): Matrix4f;
    m00(): number;
    m01(): number;
    m02(): number;
    m03(): number;
    m10(): number;
    m11(): number;
    m12(): number;
    m13(): number;
    m20(): number;
    m21(): number;
    m22(): number;
    m23(): number;
    m30(): number;
    m31(): number;
    m32(): number;
    m33(): number;
    mapXZY(arg0: Matrix4f): Matrix4f;
    mapXZnY(arg0: Matrix4f): Matrix4f;
    mapXnYnZ(arg0: Matrix4f): Matrix4f;
    mapXnZY(arg0: Matrix4f): Matrix4f;
    mapXnZnY(arg0: Matrix4f): Matrix4f;
    mapYXZ(arg0: Matrix4f): Matrix4f;
    mapYXnZ(arg0: Matrix4f): Matrix4f;
    mapYZX(arg0: Matrix4f): Matrix4f;
    mapYZnX(arg0: Matrix4f): Matrix4f;
    mapYnXZ(arg0: Matrix4f): Matrix4f;
    mapYnXnZ(arg0: Matrix4f): Matrix4f;
    mapYnZX(arg0: Matrix4f): Matrix4f;
    mapYnZnX(arg0: Matrix4f): Matrix4f;
    mapZXY(arg0: Matrix4f): Matrix4f;
    mapZXnY(arg0: Matrix4f): Matrix4f;
    mapZYX(arg0: Matrix4f): Matrix4f;
    mapZYnX(arg0: Matrix4f): Matrix4f;
    mapZnXY(arg0: Matrix4f): Matrix4f;
    mapZnXnY(arg0: Matrix4f): Matrix4f;
    mapZnYX(arg0: Matrix4f): Matrix4f;
    mapZnYnX(arg0: Matrix4f): Matrix4f;
    mapnXYnZ(arg0: Matrix4f): Matrix4f;
    mapnXZY(arg0: Matrix4f): Matrix4f;
    mapnXZnY(arg0: Matrix4f): Matrix4f;
    mapnXnYZ(arg0: Matrix4f): Matrix4f;
    mapnXnYnZ(arg0: Matrix4f): Matrix4f;
    mapnXnZY(arg0: Matrix4f): Matrix4f;
    mapnXnZnY(arg0: Matrix4f): Matrix4f;
    mapnYXZ(arg0: Matrix4f): Matrix4f;
    mapnYXnZ(arg0: Matrix4f): Matrix4f;
    mapnYZX(arg0: Matrix4f): Matrix4f;
    mapnYZnX(arg0: Matrix4f): Matrix4f;
    mapnYnXZ(arg0: Matrix4f): Matrix4f;
    mapnYnXnZ(arg0: Matrix4f): Matrix4f;
    mapnYnZX(arg0: Matrix4f): Matrix4f;
    mapnYnZnX(arg0: Matrix4f): Matrix4f;
    mapnZXY(arg0: Matrix4f): Matrix4f;
    mapnZXnY(arg0: Matrix4f): Matrix4f;
    mapnZYX(arg0: Matrix4f): Matrix4f;
    mapnZYnX(arg0: Matrix4f): Matrix4f;
    mapnZnXY(arg0: Matrix4f): Matrix4f;
    mapnZnXnY(arg0: Matrix4f): Matrix4f;
    mapnZnYX(arg0: Matrix4f): Matrix4f;
    mapnZnYnX(arg0: Matrix4f): Matrix4f;
    mul(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number, arg15: number, arg16: Matrix4f): Matrix4f;
    mul(arg0: Matrix3x2fc, arg1: Matrix4f): Matrix4f;
    mul(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    mul(arg0: Matrix4x3fc, arg1: Matrix4f): Matrix4f;
    mul0(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    mul3x3(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4f): Matrix4f;
    mul4x3ComponentWise(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    mulAffine(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    mulAffineR(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    mulComponentWise(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    mulLocal(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    mulLocalAffine(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    mulOrthoAffine(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    mulPerspectiveAffine(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    mulPerspectiveAffine(arg0: Matrix4x3fc, arg1: Matrix4f): Matrix4f;
    mulTranslationAffine(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    negateX(arg0: Matrix4f): Matrix4f;
    negateY(arg0: Matrix4f): Matrix4f;
    negateZ(arg0: Matrix4f): Matrix4f;
    normal(arg0: Matrix3f): Matrix3f;
    normal(arg0: Matrix4f): Matrix4f;
    normalize3x3(arg0: Matrix3f): Matrix3f;
    normalize3x3(arg0: Matrix4f): Matrix4f;
    normalizedPositiveX(arg0: Vector3f): Vector3f;
    normalizedPositiveY(arg0: Vector3f): Vector3f;
    normalizedPositiveZ(arg0: Vector3f): Vector3f;
    obliqueZ(arg0: number, arg1: number, arg2: Matrix4f): Matrix4f;
    origin(arg0: Vector3f): Vector3f;
    originAffine(arg0: Vector3f): Vector3f;
    ortho(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4f): Matrix4f;
    ortho(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4f): Matrix4f;
    ortho2D(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    ortho2DLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    orthoCrop(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    orthoLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4f): Matrix4f;
    orthoLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4f): Matrix4f;
    orthoSymmetric(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean, arg5: Matrix4f): Matrix4f;
    orthoSymmetric(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    orthoSymmetricLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean, arg5: Matrix4f): Matrix4f;
    orthoSymmetricLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    perspective(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean, arg5: Matrix4f): Matrix4f;
    perspective(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    perspectiveFar(): number;
    perspectiveFov(): number;
    perspectiveFrustumSlice(arg0: number, arg1: number, arg2: Matrix4f): Matrix4f;
    perspectiveInvOrigin(arg0: Vector3f): Vector3f;
    perspectiveLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean, arg5: Matrix4f): Matrix4f;
    perspectiveLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    perspectiveNear(): number;
    perspectiveOffCenter(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4f): Matrix4f;
    perspectiveOffCenter(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4f): Matrix4f;
    perspectiveOffCenterFov(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4f): Matrix4f;
    perspectiveOffCenterFov(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4f): Matrix4f;
    perspectiveOffCenterFovLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4f): Matrix4f;
    perspectiveOffCenterFovLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4f): Matrix4f;
    perspectiveOrigin(arg0: Vector3f): Vector3f;
    perspectiveRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean, arg5: Matrix4f): Matrix4f;
    perspectiveRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    pick(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number[], arg5: Matrix4f): Matrix4f;
    positiveX(arg0: Vector3f): Vector3f;
    positiveY(arg0: Vector3f): Vector3f;
    positiveZ(arg0: Vector3f): Vector3f;
    project(arg0: number, arg1: number, arg2: number, arg3: number[], arg4: Vector3f): Vector3f;
    project(arg0: number, arg1: number, arg2: number, arg3: number[], arg4: Vector4f): Vector4f;
    project(arg0: Vector3fc, arg1: number[], arg2: Vector3f): Vector3f;
    project(arg0: Vector3fc, arg1: number[], arg2: Vector4f): Vector4f;
    projectedGridRange(arg0: Matrix4fc, arg1: number, arg2: number, arg3: Matrix4f): Matrix4f;
    properties(): number;
    reflect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4f): Matrix4f;
    reflect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    reflect(arg0: Quaternionfc, arg1: Vector3fc, arg2: Matrix4f): Matrix4f;
    reflect(arg0: Vector3fc, arg1: Vector3fc, arg2: Matrix4f): Matrix4f;
    rotate(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    rotate(arg0: number, arg1: Vector3fc, arg2: Matrix4f): Matrix4f;
    rotate(arg0: AxisAngle4f, arg1: Matrix4f): Matrix4f;
    rotate(arg0: Quaternionfc, arg1: Matrix4f): Matrix4f;
    rotateAffine(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    rotateAffine(arg0: Quaternionfc, arg1: Matrix4f): Matrix4f;
    rotateAffineXYZ(arg0: number, arg1: number, arg2: number, arg3: Matrix4f): Matrix4f;
    rotateAffineYXZ(arg0: number, arg1: number, arg2: number, arg3: Matrix4f): Matrix4f;
    rotateAffineZYX(arg0: number, arg1: number, arg2: number, arg3: Matrix4f): Matrix4f;
    rotateAround(arg0: Quaternionfc, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    rotateAroundAffine(arg0: Quaternionfc, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    rotateAroundLocal(arg0: Quaternionfc, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    rotateLocal(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    rotateLocal(arg0: Quaternionfc, arg1: Matrix4f): Matrix4f;
    rotateLocalX(arg0: number, arg1: Matrix4f): Matrix4f;
    rotateLocalY(arg0: number, arg1: Matrix4f): Matrix4f;
    rotateLocalZ(arg0: number, arg1: Matrix4f): Matrix4f;
    rotateTowards(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4f): Matrix4f;
    rotateTowards(arg0: Vector3fc, arg1: Vector3fc, arg2: Matrix4f): Matrix4f;
    rotateTowardsXY(arg0: number, arg1: number, arg2: Matrix4f): Matrix4f;
    rotateTranslation(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    rotateTranslation(arg0: Quaternionfc, arg1: Matrix4f): Matrix4f;
    rotateX(arg0: number, arg1: Matrix4f): Matrix4f;
    rotateXYZ(arg0: number, arg1: number, arg2: number, arg3: Matrix4f): Matrix4f;
    rotateY(arg0: number, arg1: Matrix4f): Matrix4f;
    rotateYXZ(arg0: number, arg1: number, arg2: number, arg3: Matrix4f): Matrix4f;
    rotateZ(arg0: number, arg1: Matrix4f): Matrix4f;
    rotateZYX(arg0: number, arg1: number, arg2: number, arg3: Matrix4f): Matrix4f;
    scale(arg0: number, arg1: number, arg2: number, arg3: Matrix4f): Matrix4f;
    scale(arg0: number, arg1: Matrix4f): Matrix4f;
    scale(arg0: Vector3fc, arg1: Matrix4f): Matrix4f;
    scaleAround(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4f): Matrix4f;
    scaleAround(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    scaleAroundLocal(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4f): Matrix4f;
    scaleAroundLocal(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    scaleLocal(arg0: number, arg1: number, arg2: number, arg3: Matrix4f): Matrix4f;
    scaleLocal(arg0: number, arg1: Matrix4f): Matrix4f;
    scaleXY(arg0: number, arg1: number, arg2: Matrix4f): Matrix4f;
    shadow(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: Matrix4f): Matrix4f;
    shadow(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4fc, arg5: Matrix4f): Matrix4f;
    shadow(arg0: Vector4f, arg1: number, arg2: number, arg3: number, arg4: number, arg5: Matrix4f): Matrix4f;
    shadow(arg0: Vector4f, arg1: Matrix4fc, arg2: Matrix4f): Matrix4f;
    sub(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    sub4x3(arg0: Matrix4fc, arg1: Matrix4f): Matrix4f;
    testAab(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): boolean;
    testPoint(arg0: number, arg1: number, arg2: number): boolean;
    testSphere(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
    tile(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4f): Matrix4f;
    transform(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Vector4f): Vector4f;
    transform(arg0: Vector4f): Vector4f;
    transform(arg0: Vector4fc, arg1: Vector4f): Vector4f;
    transformAab(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Vector3f, arg7: Vector3f): Matrix4f;
    transformAab(arg0: Vector3fc, arg1: Vector3fc, arg2: Vector3f, arg3: Vector3f): Matrix4f;
    transformAffine(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Vector4f): Vector4f;
    transformAffine(arg0: Vector4f): Vector4f;
    transformAffine(arg0: Vector4fc, arg1: Vector4f): Vector4f;
    transformDirection(arg0: number, arg1: number, arg2: number, arg3: Vector3f): Vector3f;
    transformDirection(arg0: Vector3f): Vector3f;
    transformDirection(arg0: Vector3fc, arg1: Vector3f): Vector3f;
    transformPosition(arg0: number, arg1: number, arg2: number, arg3: Vector3f): Vector3f;
    transformPosition(arg0: Vector3f): Vector3f;
    transformPosition(arg0: Vector3fc, arg1: Vector3f): Vector3f;
    transformProject(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Vector3f): Vector3f;
    transformProject(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Vector4f): Vector4f;
    transformProject(arg0: number, arg1: number, arg2: number, arg3: Vector3f): Vector3f;
    transformProject(arg0: Vector3f): Vector3f;
    transformProject(arg0: Vector3fc, arg1: Vector3f): Vector3f;
    transformProject(arg0: Vector4f): Vector4f;
    transformProject(arg0: Vector4fc, arg1: Vector3f): Vector3f;
    transformProject(arg0: Vector4fc, arg1: Vector4f): Vector4f;
    transformTranspose(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Vector4f): Vector4f;
    transformTranspose(arg0: Vector4f): Vector4f;
    transformTranspose(arg0: Vector4fc, arg1: Vector4f): Vector4f;
    translate(arg0: number, arg1: number, arg2: number, arg3: Matrix4f): Matrix4f;
    translate(arg0: Vector3fc, arg1: Matrix4f): Matrix4f;
    translateLocal(arg0: number, arg1: number, arg2: number, arg3: Matrix4f): Matrix4f;
    translateLocal(arg0: Vector3fc, arg1: Matrix4f): Matrix4f;
    transpose(arg0: Matrix4f): Matrix4f;
    transpose3x3(arg0: Matrix3f): Matrix3f;
    transpose3x3(arg0: Matrix4f): Matrix4f;
    unproject(arg0: number, arg1: number, arg2: number, arg3: number[], arg4: Vector3f): Vector3f;
    unproject(arg0: number, arg1: number, arg2: number, arg3: number[], arg4: Vector4f): Vector4f;
    unproject(arg0: Vector3fc, arg1: number[], arg2: Vector3f): Vector3f;
    unproject(arg0: Vector3fc, arg1: number[], arg2: Vector4f): Vector4f;
    unprojectInv(arg0: number, arg1: number, arg2: number, arg3: number[], arg4: Vector3f): Vector3f;
    unprojectInv(arg0: number, arg1: number, arg2: number, arg3: number[], arg4: Vector4f): Vector4f;
    unprojectInv(arg0: Vector3fc, arg1: number[], arg2: Vector3f): Vector3f;
    unprojectInv(arg0: Vector3fc, arg1: number[], arg2: Vector4f): Vector4f;
    unprojectInvRay(arg0: number, arg1: number, arg2: number[], arg3: Vector3f, arg4: Vector3f): Matrix4f;
    unprojectInvRay(arg0: Vector2fc, arg1: number[], arg2: Vector3f, arg3: Vector3f): Matrix4f;
    unprojectRay(arg0: number, arg1: number, arg2: number[], arg3: Vector3f, arg4: Vector3f): Matrix4f;
    unprojectRay(arg0: Vector2fc, arg1: number[], arg2: Vector3f, arg3: Vector3f): Matrix4f;
    withLookAtUp(arg0: number, arg1: number, arg2: number, arg3: Matrix4f): Matrix4f;
    withLookAtUp(arg0: Vector3fc, arg1: Matrix4f): Matrix4f;
}