import type { Externalizable } from '../../java/io/Externalizable.d.ts'
import type { ObjectInput } from '../../java/io/ObjectInput.d.ts'
import type { ObjectOutput } from '../../java/io/ObjectOutput.d.ts'
import type { ByteBuffer } from '../../java/nio/ByteBuffer.d.ts'
import type { FloatBuffer } from '../../java/nio/FloatBuffer.d.ts'
import type { NumberFormat } from '../../java/text/NumberFormat.d.ts'
import type { Object } from '../../java/lang/Object.d.ts'
import type { Cloneable } from '../../java/lang/Cloneable.d.ts'
import type { AxisAngle4d } from '../../org/joml/AxisAngle4d.d.ts'
import type { AxisAngle4f } from '../../org/joml/AxisAngle4f.d.ts'
import type { Matrix2fc } from '../../org/joml/Matrix2fc.d.ts'
import type { Matrix3fc } from '../../org/joml/Matrix3fc.d.ts'
import type { Matrix4f } from '../../org/joml/Matrix4f.d.ts'
import type { Matrix4fc } from '../../org/joml/Matrix4fc.d.ts'
import type { Matrix4x3fc } from '../../org/joml/Matrix4x3fc.d.ts'
import type { Quaterniond } from '../../org/joml/Quaterniond.d.ts'
import type { Quaterniondc } from '../../org/joml/Quaterniondc.d.ts'
import type { Quaternionf } from '../../org/joml/Quaternionf.d.ts'
import type { Quaternionfc } from '../../org/joml/Quaternionfc.d.ts'
import type { Vector3f } from '../../org/joml/Vector3f.d.ts'
import type { Vector3fc } from '../../org/joml/Vector3fc.d.ts'
export class Matrix3f extends Object implements Externalizable, Cloneable, Matrix3fc {
    constructor()
    constructor(arg0: FloatBuffer)
    constructor(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number)
    constructor(arg0: Matrix2fc)
    constructor(arg0: Matrix3fc)
    constructor(arg0: Matrix4fc)
    constructor(arg0: Vector3fc, arg1: Vector3fc, arg2: Vector3fc)
    _m00(arg0: number): Matrix3f;
    _m01(arg0: number): Matrix3f;
    _m02(arg0: number): Matrix3f;
    _m10(arg0: number): Matrix3f;
    _m11(arg0: number): Matrix3f;
    _m12(arg0: number): Matrix3f;
    _m20(arg0: number): Matrix3f;
    _m21(arg0: number): Matrix3f;
    _m22(arg0: number): Matrix3f;
    add(arg0: Matrix3fc): Matrix3f;
    add(arg0: Matrix3fc, arg1: Matrix3f): Matrix3f;
    protected clone(): Object;
    clone(): Object;
    cofactor(): Matrix3f;
    cofactor(arg0: Matrix3f): Matrix3f;
    determinant(): number;
    equals(arg0: Object | null): boolean;
    equals(arg0: Matrix3fc, arg1: number): boolean;
    get(arg0: ByteBuffer): ByteBuffer;
    get(arg0: FloatBuffer): FloatBuffer;
    get(arg0: number[]): number[];
    get(arg0: number[], arg1: number): number[];
    get(arg0: number, arg1: ByteBuffer): ByteBuffer;
    get(arg0: number, arg1: FloatBuffer): FloatBuffer;
    get(arg0: number, arg1: number): number;
    get(arg0: Matrix3f): Matrix3f;
    get(arg0: Matrix4f): Matrix4f;
    get3x4(arg0: ByteBuffer): ByteBuffer;
    get3x4(arg0: FloatBuffer): FloatBuffer;
    get3x4(arg0: number, arg1: ByteBuffer): ByteBuffer;
    get3x4(arg0: number, arg1: FloatBuffer): FloatBuffer;
    getColumn(arg0: number, arg1: Vector3f): Vector3f;
    getEulerAnglesXYZ(arg0: Vector3f): Vector3f;
    getEulerAnglesYXZ(arg0: Vector3f): Vector3f;
    getEulerAnglesZYX(arg0: Vector3f): Vector3f;
    getNormalizedRotation(arg0: Quaterniond): Quaterniond;
    getNormalizedRotation(arg0: Quaternionf): Quaternionf;
    getRotation(arg0: AxisAngle4f): AxisAngle4f;
    getRow(arg0: number, arg1: Vector3f): Vector3f;
    getRowColumn(arg0: number, arg1: number): number;
    getScale(arg0: Vector3f): Vector3f;
    getToAddress(arg0: number): Matrix3fc;
    getTransposed(arg0: ByteBuffer): ByteBuffer;
    getTransposed(arg0: FloatBuffer): FloatBuffer;
    getTransposed(arg0: number, arg1: ByteBuffer): ByteBuffer;
    getTransposed(arg0: number, arg1: FloatBuffer): FloatBuffer;
    getTransposedToAddress(arg0: number): Matrix3fc;
    getUnnormalizedRotation(arg0: Quaterniond): Quaterniond;
    getUnnormalizedRotation(arg0: Quaternionf): Quaternionf;
    hashCode(): number;
    identity(): Matrix3f;
    invert(): Matrix3f;
    invert(arg0: Matrix3f): Matrix3f;
    isFinite(): boolean;
    lerp(arg0: Matrix3fc, arg1: number): Matrix3f;
    lerp(arg0: Matrix3fc, arg1: number, arg2: Matrix3f): Matrix3f;
    lookAlong(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix3f;
    lookAlong(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix3f): Matrix3f;
    lookAlong(arg0: Vector3fc, arg1: Vector3fc): Matrix3f;
    lookAlong(arg0: Vector3fc, arg1: Vector3fc, arg2: Matrix3f): Matrix3f;
    m00(): number;
    m00(arg0: number): Matrix3f;
    m01(): number;
    m01(arg0: number): Matrix3f;
    m02(): number;
    m02(arg0: number): Matrix3f;
    m10(): number;
    m10(arg0: number): Matrix3f;
    m11(): number;
    m11(arg0: number): Matrix3f;
    m12(): number;
    m12(arg0: number): Matrix3f;
    m20(): number;
    m20(arg0: number): Matrix3f;
    m21(): number;
    m21(arg0: number): Matrix3f;
    m22(): number;
    m22(arg0: number): Matrix3f;
    mapXZY(): Matrix3f;
    mapXZY(arg0: Matrix3f): Matrix3f;
    mapXZnY(): Matrix3f;
    mapXZnY(arg0: Matrix3f): Matrix3f;
    mapXnYnZ(): Matrix3f;
    mapXnYnZ(arg0: Matrix3f): Matrix3f;
    mapXnZY(): Matrix3f;
    mapXnZY(arg0: Matrix3f): Matrix3f;
    mapXnZnY(): Matrix3f;
    mapXnZnY(arg0: Matrix3f): Matrix3f;
    mapYXZ(): Matrix3f;
    mapYXZ(arg0: Matrix3f): Matrix3f;
    mapYXnZ(): Matrix3f;
    mapYXnZ(arg0: Matrix3f): Matrix3f;
    mapYZX(): Matrix3f;
    mapYZX(arg0: Matrix3f): Matrix3f;
    mapYZnX(): Matrix3f;
    mapYZnX(arg0: Matrix3f): Matrix3f;
    mapYnXZ(): Matrix3f;
    mapYnXZ(arg0: Matrix3f): Matrix3f;
    mapYnXnZ(): Matrix3f;
    mapYnXnZ(arg0: Matrix3f): Matrix3f;
    mapYnZX(): Matrix3f;
    mapYnZX(arg0: Matrix3f): Matrix3f;
    mapYnZnX(): Matrix3f;
    mapYnZnX(arg0: Matrix3f): Matrix3f;
    mapZXY(): Matrix3f;
    mapZXY(arg0: Matrix3f): Matrix3f;
    mapZXnY(): Matrix3f;
    mapZXnY(arg0: Matrix3f): Matrix3f;
    mapZYX(): Matrix3f;
    mapZYX(arg0: Matrix3f): Matrix3f;
    mapZYnX(): Matrix3f;
    mapZYnX(arg0: Matrix3f): Matrix3f;
    mapZnXY(): Matrix3f;
    mapZnXY(arg0: Matrix3f): Matrix3f;
    mapZnXnY(): Matrix3f;
    mapZnXnY(arg0: Matrix3f): Matrix3f;
    mapZnYX(): Matrix3f;
    mapZnYX(arg0: Matrix3f): Matrix3f;
    mapZnYnX(): Matrix3f;
    mapZnYnX(arg0: Matrix3f): Matrix3f;
    mapnXYnZ(): Matrix3f;
    mapnXYnZ(arg0: Matrix3f): Matrix3f;
    mapnXZY(): Matrix3f;
    mapnXZY(arg0: Matrix3f): Matrix3f;
    mapnXZnY(): Matrix3f;
    mapnXZnY(arg0: Matrix3f): Matrix3f;
    mapnXnYZ(): Matrix3f;
    mapnXnYZ(arg0: Matrix3f): Matrix3f;
    mapnXnYnZ(): Matrix3f;
    mapnXnYnZ(arg0: Matrix3f): Matrix3f;
    mapnXnZY(): Matrix3f;
    mapnXnZY(arg0: Matrix3f): Matrix3f;
    mapnXnZnY(): Matrix3f;
    mapnXnZnY(arg0: Matrix3f): Matrix3f;
    mapnYXZ(): Matrix3f;
    mapnYXZ(arg0: Matrix3f): Matrix3f;
    mapnYXnZ(): Matrix3f;
    mapnYXnZ(arg0: Matrix3f): Matrix3f;
    mapnYZX(): Matrix3f;
    mapnYZX(arg0: Matrix3f): Matrix3f;
    mapnYZnX(): Matrix3f;
    mapnYZnX(arg0: Matrix3f): Matrix3f;
    mapnYnXZ(): Matrix3f;
    mapnYnXZ(arg0: Matrix3f): Matrix3f;
    mapnYnXnZ(): Matrix3f;
    mapnYnXnZ(arg0: Matrix3f): Matrix3f;
    mapnYnZX(): Matrix3f;
    mapnYnZX(arg0: Matrix3f): Matrix3f;
    mapnYnZnX(): Matrix3f;
    mapnYnZnX(arg0: Matrix3f): Matrix3f;
    mapnZXY(): Matrix3f;
    mapnZXY(arg0: Matrix3f): Matrix3f;
    mapnZXnY(): Matrix3f;
    mapnZXnY(arg0: Matrix3f): Matrix3f;
    mapnZYX(): Matrix3f;
    mapnZYX(arg0: Matrix3f): Matrix3f;
    mapnZYnX(): Matrix3f;
    mapnZYnX(arg0: Matrix3f): Matrix3f;
    mapnZnXY(): Matrix3f;
    mapnZnXY(arg0: Matrix3f): Matrix3f;
    mapnZnXnY(): Matrix3f;
    mapnZnXnY(arg0: Matrix3f): Matrix3f;
    mapnZnYX(): Matrix3f;
    mapnZnYX(arg0: Matrix3f): Matrix3f;
    mapnZnYnX(): Matrix3f;
    mapnZnYnX(arg0: Matrix3f): Matrix3f;
    mul(arg0: Matrix3fc): Matrix3f;
    mul(arg0: Matrix3fc, arg1: Matrix3f): Matrix3f;
    mulComponentWise(arg0: Matrix3fc): Matrix3f;
    mulComponentWise(arg0: Matrix3fc, arg1: Matrix3f): Matrix3f;
    mulLocal(arg0: Matrix3fc): Matrix3f;
    mulLocal(arg0: Matrix3fc, arg1: Matrix3f): Matrix3f;
    negateX(): Matrix3f;
    negateX(arg0: Matrix3f): Matrix3f;
    negateY(): Matrix3f;
    negateY(arg0: Matrix3f): Matrix3f;
    negateZ(): Matrix3f;
    negateZ(arg0: Matrix3f): Matrix3f;
    normal(): Matrix3f;
    normal(arg0: Matrix3f): Matrix3f;
    normalizedPositiveX(arg0: Vector3f): Vector3f;
    normalizedPositiveY(arg0: Vector3f): Vector3f;
    normalizedPositiveZ(arg0: Vector3f): Vector3f;
    obliqueZ(arg0: number, arg1: number): Matrix3f;
    obliqueZ(arg0: number, arg1: number, arg2: Matrix3f): Matrix3f;
    positiveX(arg0: Vector3f): Vector3f;
    positiveY(arg0: Vector3f): Vector3f;
    positiveZ(arg0: Vector3f): Vector3f;
    quadraticFormProduct(arg0: number, arg1: number, arg2: number): number;
    quadraticFormProduct(arg0: Vector3fc): number;
    readExternal(arg0: ObjectInput): void;
    reflect(arg0: number, arg1: number, arg2: number): Matrix3f;
    reflect(arg0: number, arg1: number, arg2: number, arg3: Matrix3f): Matrix3f;
    reflect(arg0: Quaternionfc): Matrix3f;
    reflect(arg0: Quaternionfc, arg1: Matrix3f): Matrix3f;
    reflect(arg0: Vector3fc): Matrix3f;
    reflect(arg0: Vector3fc, arg1: Matrix3f): Matrix3f;
    reflection(arg0: number, arg1: number, arg2: number): Matrix3f;
    reflection(arg0: Quaternionfc): Matrix3f;
    reflection(arg0: Vector3fc): Matrix3f;
    rotate(arg0: number, arg1: number, arg2: number, arg3: number): Matrix3f;
    rotate(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix3f): Matrix3f;
    rotate(arg0: number, arg1: Vector3fc): Matrix3f;
    rotate(arg0: number, arg1: Vector3fc, arg2: Matrix3f): Matrix3f;
    rotate(arg0: AxisAngle4f): Matrix3f;
    rotate(arg0: AxisAngle4f, arg1: Matrix3f): Matrix3f;
    rotate(arg0: Quaternionfc): Matrix3f;
    rotate(arg0: Quaternionfc, arg1: Matrix3f): Matrix3f;
    rotateLocal(arg0: number, arg1: number, arg2: number, arg3: number): Matrix3f;
    rotateLocal(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix3f): Matrix3f;
    rotateLocal(arg0: Quaternionfc): Matrix3f;
    rotateLocal(arg0: Quaternionfc, arg1: Matrix3f): Matrix3f;
    rotateLocalX(arg0: number): Matrix3f;
    rotateLocalX(arg0: number, arg1: Matrix3f): Matrix3f;
    rotateLocalY(arg0: number): Matrix3f;
    rotateLocalY(arg0: number, arg1: Matrix3f): Matrix3f;
    rotateLocalZ(arg0: number): Matrix3f;
    rotateLocalZ(arg0: number, arg1: Matrix3f): Matrix3f;
    rotateTowards(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix3f;
    rotateTowards(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix3f): Matrix3f;
    rotateTowards(arg0: Vector3fc, arg1: Vector3fc): Matrix3f;
    rotateTowards(arg0: Vector3fc, arg1: Vector3fc, arg2: Matrix3f): Matrix3f;
    rotateX(arg0: number): Matrix3f;
    rotateX(arg0: number, arg1: Matrix3f): Matrix3f;
    rotateXYZ(arg0: number, arg1: number, arg2: number): Matrix3f;
    rotateXYZ(arg0: number, arg1: number, arg2: number, arg3: Matrix3f): Matrix3f;
    rotateXYZ(arg0: Vector3f): Matrix3f;
    rotateY(arg0: number): Matrix3f;
    rotateY(arg0: number, arg1: Matrix3f): Matrix3f;
    rotateYXZ(arg0: number, arg1: number, arg2: number): Matrix3f;
    rotateYXZ(arg0: number, arg1: number, arg2: number, arg3: Matrix3f): Matrix3f;
    rotateYXZ(arg0: Vector3f): Matrix3f;
    rotateZ(arg0: number): Matrix3f;
    rotateZ(arg0: number, arg1: Matrix3f): Matrix3f;
    rotateZYX(arg0: number, arg1: number, arg2: number): Matrix3f;
    rotateZYX(arg0: number, arg1: number, arg2: number, arg3: Matrix3f): Matrix3f;
    rotateZYX(arg0: Vector3f): Matrix3f;
    rotation(arg0: number, arg1: number, arg2: number, arg3: number): Matrix3f;
    rotation(arg0: number, arg1: Vector3fc): Matrix3f;
    rotation(arg0: AxisAngle4f): Matrix3f;
    rotation(arg0: Quaternionfc): Matrix3f;
    rotationTowards(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix3f;
    rotationTowards(arg0: Vector3fc, arg1: Vector3fc): Matrix3f;
    rotationX(arg0: number): Matrix3f;
    rotationXYZ(arg0: number, arg1: number, arg2: number): Matrix3f;
    rotationY(arg0: number): Matrix3f;
    rotationYXZ(arg0: number, arg1: number, arg2: number): Matrix3f;
    rotationZ(arg0: number): Matrix3f;
    rotationZYX(arg0: number, arg1: number, arg2: number): Matrix3f;
    scale(arg0: number): Matrix3f;
    scale(arg0: number, arg1: number, arg2: number): Matrix3f;
    scale(arg0: number, arg1: number, arg2: number, arg3: Matrix3f): Matrix3f;
    scale(arg0: number, arg1: Matrix3f): Matrix3f;
    scale(arg0: Vector3fc): Matrix3f;
    scale(arg0: Vector3fc, arg1: Matrix3f): Matrix3f;
    scaleLocal(arg0: number, arg1: number, arg2: number): Matrix3f;
    scaleLocal(arg0: number, arg1: number, arg2: number, arg3: Matrix3f): Matrix3f;
    scaling(arg0: number): Matrix3f;
    scaling(arg0: number, arg1: number, arg2: number): Matrix3f;
    scaling(arg0: Vector3fc): Matrix3f;
    set(arg0: ByteBuffer): Matrix3f;
    set(arg0: FloatBuffer): Matrix3f;
    set(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Matrix3f;
    set(arg0: number[]): Matrix3f;
    set(arg0: number[], arg1: number): Matrix3f;
    set(arg0: number, arg1: ByteBuffer): Matrix3f;
    set(arg0: number, arg1: FloatBuffer): Matrix3f;
    set(arg0: number, arg1: number, arg2: number): Matrix3f;
    set(arg0: AxisAngle4d): Matrix3f;
    set(arg0: AxisAngle4f): Matrix3f;
    set(arg0: Matrix2fc): Matrix3f;
    set(arg0: Matrix3fc): Matrix3f;
    set(arg0: Matrix4fc): Matrix3f;
    set(arg0: Matrix4x3fc): Matrix3f;
    set(arg0: Quaterniondc): Matrix3f;
    set(arg0: Quaternionfc): Matrix3f;
    set(arg0: Vector3fc, arg1: Vector3fc, arg2: Vector3fc): Matrix3f;
    setColumn(arg0: number, arg1: number, arg2: number, arg3: number): Matrix3f;
    setColumn(arg0: number, arg1: Vector3fc): Matrix3f;
    setFromAddress(arg0: number): Matrix3f;
    setLookAlong(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Matrix3f;
    setLookAlong(arg0: Vector3fc, arg1: Vector3fc): Matrix3f;
    setRow(arg0: number, arg1: number, arg2: number, arg3: number): Matrix3f;
    setRow(arg0: number, arg1: Vector3fc): Matrix3f;
    setRowColumn(arg0: number, arg1: number, arg2: number): Matrix3f;
    setSkewSymmetric(arg0: number, arg1: number, arg2: number): Matrix3f;
    setTransposed(arg0: Matrix3fc): Matrix3f;
    setTransposedFromAddress(arg0: number): Matrix3f;
    sub(arg0: Matrix3fc): Matrix3f;
    sub(arg0: Matrix3fc, arg1: Matrix3f): Matrix3f;
    swap(arg0: Matrix3f): Matrix3f;
    toString(): string;
    toString(arg0: NumberFormat): string;
    transform(arg0: number, arg1: number, arg2: number, arg3: Vector3f): Vector3f;
    transform(arg0: Vector3f): Vector3f;
    transform(arg0: Vector3fc, arg1: Vector3f): Vector3f;
    transformTranspose(arg0: number, arg1: number, arg2: number, arg3: Vector3f): Vector3f;
    transformTranspose(arg0: Vector3f): Vector3f;
    transformTranspose(arg0: Vector3fc, arg1: Vector3f): Vector3f;
    transpose(): Matrix3f;
    transpose(arg0: Matrix3f): Matrix3f;
    writeExternal(arg0: ObjectOutput): void;
    zero(): Matrix3f;
}