import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { ShortBuffer } from '../../../../java/nio/ShortBuffer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { Struct } from '../../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class PS_Private extends Struct<PS_Private> {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static BLUE_FUZZ: number;
    static BLUE_SCALE: number;
    static BLUE_SHIFT: number;
    static BLUE_VALUES: number;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static EXPANSION_FACTOR: number;
    static FAMILY_BLUES: number;
    static FAMILY_OTHER_BLUES: number;
    static FORCE_BOLD: number;
    static LANGUAGE_GROUP: number;
    static LENIV: number;
    static MIN_FEATURE: number;
    static NUM_BLUE_VALUES: number;
    static NUM_FAMILY_BLUES: number;
    static NUM_FAMILY_OTHER_BLUES: number;
    static NUM_OTHER_BLUES: number;
    static NUM_SNAP_HEIGHTS: number;
    static NUM_SNAP_WIDTHS: number;
    static OTHER_BLUES: number;
    static PASSWORD: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static ROUND_STEM_UP: number;
    static SIZEOF: number;
    static SNAP_HEIGHTS: number;
    static SNAP_WIDTHS: number;
    static STANDARD_HEIGHT: number;
    static STANDARD_WIDTH: number;
    static UNIQUE_ID: number;
    static create(paramarg0: number): PS_Private;
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): PS_Private;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static nblue_fuzz(paramarg0: number): number;
    static nblue_scale(paramarg0: number): number;
    static nblue_shift(paramarg0: number): number;
    static nblue_values(paramarg0: number): ShortBuffer;
    static nblue_values(paramarg0: number, paramarg1: number): number;
    static nexpansion_factor(paramarg0: number): number;
    static nfamily_blues(paramarg0: number): ShortBuffer;
    static nfamily_blues(paramarg0: number, paramarg1: number): number;
    static nfamily_other_blues(paramarg0: number): ShortBuffer;
    static nfamily_other_blues(paramarg0: number, paramarg1: number): number;
    static nforce_bold(paramarg0: number): boolean;
    static nlanguage_group(paramarg0: number): number;
    static nlenIV(paramarg0: number): number;
    static nmin_feature(paramarg0: number): ShortBuffer;
    static nmin_feature(paramarg0: number, paramarg1: number): number;
    static nnum_blue_values(paramarg0: number): number;
    static nnum_family_blues(paramarg0: number): number;
    static nnum_family_other_blues(paramarg0: number): number;
    static nnum_other_blues(paramarg0: number): number;
    static nnum_snap_heights(paramarg0: number): number;
    static nnum_snap_widths(paramarg0: number): number;
    static nother_blues(paramarg0: number): ShortBuffer;
    static nother_blues(paramarg0: number, paramarg1: number): number;
    static npassword(paramarg0: number): number;
    static nround_stem_up(paramarg0: number): boolean;
    static nsnap_heights(paramarg0: number): ShortBuffer;
    static nsnap_heights(paramarg0: number, paramarg1: number): number;
    static nsnap_widths(paramarg0: number): ShortBuffer;
    static nsnap_widths(paramarg0: number, paramarg1: number): number;
    static nstandard_height(paramarg0: number): ShortBuffer;
    static nstandard_height(paramarg0: number, paramarg1: number): number;
    static nstandard_width(paramarg0: number): ShortBuffer;
    static nstandard_width(paramarg0: number, paramarg1: number): number;
    static nunique_id(paramarg0: number): number;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    blue_fuzz(): number;
    blue_scale(): number;
    blue_shift(): number;
    blue_values(): ShortBuffer;
    blue_values(arg0: number): number;
    create(arg0: number, arg1: ByteBuffer): PS_Private;
    expansion_factor(): number;
    family_blues(): ShortBuffer;
    family_blues(arg0: number): number;
    family_other_blues(): ShortBuffer;
    family_other_blues(arg0: number): number;
    force_bold(): boolean;
    language_group(): number;
    lenIV(): number;
    min_feature(): ShortBuffer;
    min_feature(arg0: number): number;
    num_blue_values(): number;
    num_family_blues(): number;
    num_family_other_blues(): number;
    num_other_blues(): number;
    num_snap_heights(): number;
    num_snap_widths(): number;
    other_blues(): ShortBuffer;
    other_blues(arg0: number): number;
    password(): number;
    round_stem_up(): boolean;
    sizeof(): number;
    snap_heights(): ShortBuffer;
    snap_heights(arg0: number): number;
    snap_widths(): ShortBuffer;
    snap_widths(arg0: number): number;
    standard_height(): ShortBuffer;
    standard_height(arg0: number): number;
    standard_width(): ShortBuffer;
    standard_width(arg0: number): number;
    unique_id(): number;
}