import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { IntBuffer } from '../../../../java/nio/IntBuffer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../../java/lang/CharSequence.d.ts'
import type { PointerBuffer } from '../../../../org/lwjgl/PointerBuffer.d.ts'
import type { SharedLibrary } from '../../../../org/lwjgl/system/SharedLibrary.d.ts'
import type { SpvcErrorCallbackI } from '../../../../org/lwjgl/util/spvc/SpvcErrorCallbackI.d.ts'
import type { SpvcHLSLResourceBinding } from '../../../../org/lwjgl/util/spvc/SpvcHLSLResourceBinding.d.ts'
import type { SpvcHlslRootConstants } from '../../../../org/lwjgl/util/spvc/SpvcHlslRootConstants.d.ts'
import type { SpvcHlslVertexAttributeRemap } from '../../../../org/lwjgl/util/spvc/SpvcHlslVertexAttributeRemap.d.ts'
import type { SpvcMslConstexprSampler } from '../../../../org/lwjgl/util/spvc/SpvcMslConstexprSampler.d.ts'
import type { SpvcMslResourceBinding } from '../../../../org/lwjgl/util/spvc/SpvcMslResourceBinding.d.ts'
import type { SpvcMslResourceBinding2 } from '../../../../org/lwjgl/util/spvc/SpvcMslResourceBinding2.d.ts'
import type { SpvcMslSamplerYcbcrConversion } from '../../../../org/lwjgl/util/spvc/SpvcMslSamplerYcbcrConversion.d.ts'
import type { SpvcMslShaderInput } from '../../../../org/lwjgl/util/spvc/SpvcMslShaderInput.d.ts'
import type { SpvcMslShaderInterfaceVar } from '../../../../org/lwjgl/util/spvc/SpvcMslShaderInterfaceVar.d.ts'
import type { SpvcMslShaderInterfaceVar2 } from '../../../../org/lwjgl/util/spvc/SpvcMslShaderInterfaceVar2.d.ts'
import type { SpvcMslVertexAttribute } from '../../../../org/lwjgl/util/spvc/SpvcMslVertexAttribute.d.ts'
import type { SpvcSpecializationConstant } from '../../../../org/lwjgl/util/spvc/SpvcSpecializationConstant.d.ts'
export class Spvc extends Object {
    static SPVC_BACKEND_CPP: number;
    static SPVC_BACKEND_GLSL: number;
    static SPVC_BACKEND_HLSL: number;
    static SPVC_BACKEND_JSON: number;
    static SPVC_BACKEND_MSL: number;
    static SPVC_BACKEND_NONE: number;
    static SPVC_BASETYPE_ACCELERATION_STRUCTURE: number;
    static SPVC_BASETYPE_ATOMIC_COUNTER: number;
    static SPVC_BASETYPE_BOOLEAN: number;
    static SPVC_BASETYPE_FP16: number;
    static SPVC_BASETYPE_FP32: number;
    static SPVC_BASETYPE_FP64: number;
    static SPVC_BASETYPE_IMAGE: number;
    static SPVC_BASETYPE_INT16: number;
    static SPVC_BASETYPE_INT32: number;
    static SPVC_BASETYPE_INT64: number;
    static SPVC_BASETYPE_INT8: number;
    static SPVC_BASETYPE_SAMPLED_IMAGE: number;
    static SPVC_BASETYPE_SAMPLER: number;
    static SPVC_BASETYPE_STRUCT: number;
    static SPVC_BASETYPE_UINT16: number;
    static SPVC_BASETYPE_UINT32: number;
    static SPVC_BASETYPE_UINT64: number;
    static SPVC_BASETYPE_UINT8: number;
    static SPVC_BASETYPE_UNKNOWN: number;
    static SPVC_BASETYPE_VOID: number;
    static SPVC_BUILTIN_RESOURCE_TYPE_STAGE_INPUT: number;
    static SPVC_BUILTIN_RESOURCE_TYPE_STAGE_OUTPUT: number;
    static SPVC_BUILTIN_RESOURCE_TYPE_UNKNOWN: number;
    static SPVC_CAPTURE_MODE_COPY: number;
    static SPVC_CAPTURE_MODE_TAKE_OWNERSHIP: number;
    static SPVC_COMPILER_OPTION_COMMON_BIT: number;
    static SPVC_COMPILER_OPTION_EMIT_LINE_DIRECTIVES: number;
    static SPVC_COMPILER_OPTION_ENABLE_STORAGE_IMAGE_QUALIFIER_DEDUCTION: number;
    static SPVC_COMPILER_OPTION_ENUM_BITS: number;
    static SPVC_COMPILER_OPTION_FIXUP_DEPTH_CONVENTION: number;
    static SPVC_COMPILER_OPTION_FLATTEN_MULTIDIMENSIONAL_ARRAYS: number;
    static SPVC_COMPILER_OPTION_FLIP_VERTEX_Y: number;
    static SPVC_COMPILER_OPTION_FORCE_TEMPORARY: number;
    static SPVC_COMPILER_OPTION_FORCE_ZERO_INITIALIZED_VARIABLES: number;
    static SPVC_COMPILER_OPTION_GLSL_BIT: number;
    static SPVC_COMPILER_OPTION_GLSL_EMIT_PUSH_CONSTANT_AS_UNIFORM_BUFFER: number;
    static SPVC_COMPILER_OPTION_GLSL_EMIT_UNIFORM_BUFFER_AS_PLAIN_UNIFORMS: number;
    static SPVC_COMPILER_OPTION_GLSL_ENABLE_420PACK_EXTENSION: number;
    static SPVC_COMPILER_OPTION_GLSL_ENABLE_ROW_MAJOR_LOAD_WORKAROUND: number;
    static SPVC_COMPILER_OPTION_GLSL_ES: number;
    static SPVC_COMPILER_OPTION_GLSL_ES_DEFAULT_FLOAT_PRECISION_HIGHP: number;
    static SPVC_COMPILER_OPTION_GLSL_ES_DEFAULT_INT_PRECISION_HIGHP: number;
    static SPVC_COMPILER_OPTION_GLSL_FORCE_FLATTENED_IO_BLOCKS: number;
    static SPVC_COMPILER_OPTION_GLSL_OVR_MULTIVIEW_VIEW_COUNT: number;
    static SPVC_COMPILER_OPTION_GLSL_SEPARATE_SHADER_OBJECTS: number;
    static SPVC_COMPILER_OPTION_GLSL_SUPPORT_NONZERO_BASE_INSTANCE: number;
    static SPVC_COMPILER_OPTION_GLSL_VERSION: number;
    static SPVC_COMPILER_OPTION_GLSL_VULKAN_SEMANTICS: number;
    static SPVC_COMPILER_OPTION_HLSL_BIT: number;
    static SPVC_COMPILER_OPTION_HLSL_ENABLE_16BIT_TYPES: number;
    static SPVC_COMPILER_OPTION_HLSL_FLATTEN_MATRIX_VERTEX_INPUT_SEMANTICS: number;
    static SPVC_COMPILER_OPTION_HLSL_FORCE_STORAGE_BUFFER_AS_UAV: number;
    static SPVC_COMPILER_OPTION_HLSL_NONWRITABLE_UAV_TEXTURE_AS_SRV: number;
    static SPVC_COMPILER_OPTION_HLSL_POINT_COORD_COMPAT: number;
    static SPVC_COMPILER_OPTION_HLSL_POINT_SIZE_COMPAT: number;
    static SPVC_COMPILER_OPTION_HLSL_PRESERVE_STRUCTURED_BUFFERS: number;
    static SPVC_COMPILER_OPTION_HLSL_SHADER_MODEL: number;
    static SPVC_COMPILER_OPTION_HLSL_SUPPORT_NONZERO_BASE_VERTEX_BASE_INSTANCE: number;
    static SPVC_COMPILER_OPTION_HLSL_USER_SEMANTIC: number;
    static SPVC_COMPILER_OPTION_HLSL_USE_ENTRY_POINT_NAME: number;
    static SPVC_COMPILER_OPTION_LANG_BITS: number;
    static SPVC_COMPILER_OPTION_MSL_AGX_MANUAL_CUBE_GRAD_FIXUP: number;
    static SPVC_COMPILER_OPTION_MSL_ARGUMENT_BUFFERS: number;
    static SPVC_COMPILER_OPTION_MSL_ARGUMENT_BUFFERS_TIER: number;
    static SPVC_COMPILER_OPTION_MSL_ARRAYED_SUBPASS_INPUT: number;
    static SPVC_COMPILER_OPTION_MSL_AUTO_DISABLE_RASTERIZATION: number;
    static SPVC_COMPILER_OPTION_MSL_AUX_BUFFER_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_BIT: number;
    static SPVC_COMPILER_OPTION_MSL_BUFFER_SIZE_BUFFER_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_CAPTURE_OUTPUT_TO_BUFFER: number;
    static SPVC_COMPILER_OPTION_MSL_CHECK_DISCARDED_FRAG_STORES: number;
    static SPVC_COMPILER_OPTION_MSL_DEVICE_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_DISABLE_RASTERIZATION: number;
    static SPVC_COMPILER_OPTION_MSL_DISPATCH_BASE: number;
    static SPVC_COMPILER_OPTION_MSL_DYNAMIC_OFFSETS_BUFFER_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_EMULATE_CUBEMAP_ARRAY: number;
    static SPVC_COMPILER_OPTION_MSL_EMULATE_SUBGROUPS: number;
    static SPVC_COMPILER_OPTION_MSL_ENABLE_BASE_INDEX_ZERO: number;
    static SPVC_COMPILER_OPTION_MSL_ENABLE_CLIP_DISTANCE_USER_VARYING: number;
    static SPVC_COMPILER_OPTION_MSL_ENABLE_DECORATION_BINDING: number;
    static SPVC_COMPILER_OPTION_MSL_ENABLE_FRAG_DEPTH_BUILTIN: number;
    static SPVC_COMPILER_OPTION_MSL_ENABLE_FRAG_OUTPUT_MASK: number;
    static SPVC_COMPILER_OPTION_MSL_ENABLE_FRAG_STENCIL_REF_BUILTIN: number;
    static SPVC_COMPILER_OPTION_MSL_ENABLE_POINT_SIZE_BUILTIN: number;
    static SPVC_COMPILER_OPTION_MSL_ENABLE_POINT_SIZE_DEFAULT: number;
    static SPVC_COMPILER_OPTION_MSL_FIXED_SUBGROUP_SIZE: number;
    static SPVC_COMPILER_OPTION_MSL_FORCE_ACTIVE_ARGUMENT_BUFFER_RESOURCES: number;
    static SPVC_COMPILER_OPTION_MSL_FORCE_FRAGMENT_WITH_SIDE_EFFECTS_EXECUTION: number;
    static SPVC_COMPILER_OPTION_MSL_FORCE_NATIVE_ARRAYS: number;
    static SPVC_COMPILER_OPTION_MSL_FORCE_SAMPLE_RATE_SHADING: number;
    static SPVC_COMPILER_OPTION_MSL_FRAMEBUFFER_FETCH_SUBPASS: number;
    static SPVC_COMPILER_OPTION_MSL_INDIRECT_PARAMS_BUFFER_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_INVARIANT_FP_MATH: number;
    static SPVC_COMPILER_OPTION_MSL_IOS_FRAMEBUFFER_FETCH_SUBPASS: number;
    static SPVC_COMPILER_OPTION_MSL_IOS_SUPPORT_BASE_VERTEX_INSTANCE: number;
    static SPVC_COMPILER_OPTION_MSL_IOS_USE_SIMDGROUP_FUNCTIONS: number;
    static SPVC_COMPILER_OPTION_MSL_MANUAL_HELPER_INVOCATION_UPDATES: number;
    static SPVC_COMPILER_OPTION_MSL_MULTIVIEW: number;
    static SPVC_COMPILER_OPTION_MSL_MULTIVIEW_LAYERED_RENDERING: number;
    static SPVC_COMPILER_OPTION_MSL_MULTI_PATCH_WORKGROUP: number;
    static SPVC_COMPILER_OPTION_MSL_PAD_FRAGMENT_OUTPUT_COMPONENTS: number;
    static SPVC_COMPILER_OPTION_MSL_PLATFORM: number;
    static SPVC_COMPILER_OPTION_MSL_R32UI_ALIGNMENT_CONSTANT_ID: number;
    static SPVC_COMPILER_OPTION_MSL_R32UI_LINEAR_TEXTURE_ALIGNMENT: number;
    static SPVC_COMPILER_OPTION_MSL_RAW_BUFFER_TESE_INPUT: number;
    static SPVC_COMPILER_OPTION_MSL_READWRITE_TEXTURE_FENCES: number;
    static SPVC_COMPILER_OPTION_MSL_REPLACE_RECURSIVE_INPUTS: number;
    static SPVC_COMPILER_OPTION_MSL_SAMPLE_DREF_LOD_ARRAY_AS_GRAD: number;
    static SPVC_COMPILER_OPTION_MSL_SHADER_INDEX_BUFFER_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_SHADER_INPUT_BUFFER_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_SHADER_INPUT_WORKGROUP_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_SHADER_OUTPUT_BUFFER_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_SHADER_PATCH_INPUT_BUFFER_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_SHADER_PATCH_OUTPUT_BUFFER_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_SHADER_TESS_FACTOR_OUTPUT_BUFFER_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_SWIZZLE_BUFFER_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_SWIZZLE_TEXTURE_SAMPLES: number;
    static SPVC_COMPILER_OPTION_MSL_TESS_DOMAIN_ORIGIN_LOWER_LEFT: number;
    static SPVC_COMPILER_OPTION_MSL_TEXEL_BUFFER_TEXTURE_WIDTH: number;
    static SPVC_COMPILER_OPTION_MSL_TEXTURE_1D_AS_2D: number;
    static SPVC_COMPILER_OPTION_MSL_TEXTURE_BUFFER_NATIVE: number;
    static SPVC_COMPILER_OPTION_MSL_VERSION: number;
    static SPVC_COMPILER_OPTION_MSL_VERTEX_FOR_TESSELLATION: number;
    static SPVC_COMPILER_OPTION_MSL_VERTEX_INDEX_TYPE: number;
    static SPVC_COMPILER_OPTION_MSL_VIEW_INDEX_FROM_DEVICE_INDEX: number;
    static SPVC_COMPILER_OPTION_MSL_VIEW_MASK_BUFFER_INDEX: number;
    static SPVC_COMPILER_OPTION_RELAX_NAN_CHECKS: number;
    static SPVC_COMPILER_OPTION_UNKNOWN: number;
    static SPVC_C_API_VERSION_MAJOR: number;
    static SPVC_C_API_VERSION_MINOR: number;
    static SPVC_C_API_VERSION_PATCH: number;
    static SPVC_ERROR_INVALID_ARGUMENT: number;
    static SPVC_ERROR_INVALID_SPIRV: number;
    static SPVC_ERROR_OUT_OF_MEMORY: number;
    static SPVC_ERROR_UNSUPPORTED_SPIRV: number;
    static SPVC_HLSL_BINDING_AUTO_ALL: number;
    static SPVC_HLSL_BINDING_AUTO_CBV_BIT: number;
    static SPVC_HLSL_BINDING_AUTO_NONE_BIT: number;
    static SPVC_HLSL_BINDING_AUTO_PUSH_CONSTANT_BIT: number;
    static SPVC_HLSL_BINDING_AUTO_SAMPLER_BIT: number;
    static SPVC_HLSL_BINDING_AUTO_SRV_BIT: number;
    static SPVC_HLSL_BINDING_AUTO_UAV_BIT: number;
    static SPVC_HLSL_PUSH_CONSTANT_BINDING: number;
    static SPVC_HLSL_PUSH_CONSTANT_DESC_SET: number;
    static SPVC_MSL_ARGUMENT_BUFFER_BINDING: number;
    static SPVC_MSL_AUX_BUFFER_STRUCT_VERSION: number;
    static SPVC_MSL_BUFFER_SIZE_BUFFER_BINDING: number;
    static SPVC_MSL_CHROMA_LOCATION_COSITED_EVEN: number;
    static SPVC_MSL_CHROMA_LOCATION_MIDPOINT: number;
    static SPVC_MSL_COMPONENT_SWIZZLE_A: number;
    static SPVC_MSL_COMPONENT_SWIZZLE_B: number;
    static SPVC_MSL_COMPONENT_SWIZZLE_G: number;
    static SPVC_MSL_COMPONENT_SWIZZLE_IDENTITY: number;
    static SPVC_MSL_COMPONENT_SWIZZLE_ONE: number;
    static SPVC_MSL_COMPONENT_SWIZZLE_R: number;
    static SPVC_MSL_COMPONENT_SWIZZLE_ZERO: number;
    static SPVC_MSL_FORMAT_RESOLUTION_420: number;
    static SPVC_MSL_FORMAT_RESOLUTION_422: number;
    static SPVC_MSL_FORMAT_RESOLUTION_444: number;
    static SPVC_MSL_INDEX_TYPE_NONE: number;
    static SPVC_MSL_INDEX_TYPE_UINT16: number;
    static SPVC_MSL_INDEX_TYPE_UINT32: number;
    static SPVC_MSL_PLATFORM_IOS: number;
    static SPVC_MSL_PLATFORM_MACOS: number;
    static SPVC_MSL_PUSH_CONSTANT_BINDING: number;
    static SPVC_MSL_PUSH_CONSTANT_DESC_SET: number;
    static SPVC_MSL_SAMPLER_ADDRESS_CLAMP_TO_BORDER: number;
    static SPVC_MSL_SAMPLER_ADDRESS_CLAMP_TO_EDGE: number;
    static SPVC_MSL_SAMPLER_ADDRESS_CLAMP_TO_ZERO: number;
    static SPVC_MSL_SAMPLER_ADDRESS_MIRRORED_REPEAT: number;
    static SPVC_MSL_SAMPLER_ADDRESS_REPEAT: number;
    static SPVC_MSL_SAMPLER_BORDER_COLOR_OPAQUE_BLACK: number;
    static SPVC_MSL_SAMPLER_BORDER_COLOR_OPAQUE_WHITE: number;
    static SPVC_MSL_SAMPLER_BORDER_COLOR_TRANSPARENT_BLACK: number;
    static SPVC_MSL_SAMPLER_COMPARE_FUNC_ALWAYS: number;
    static SPVC_MSL_SAMPLER_COMPARE_FUNC_EQUAL: number;
    static SPVC_MSL_SAMPLER_COMPARE_FUNC_GREATER: number;
    static SPVC_MSL_SAMPLER_COMPARE_FUNC_GREATER_EQUAL: number;
    static SPVC_MSL_SAMPLER_COMPARE_FUNC_LESS: number;
    static SPVC_MSL_SAMPLER_COMPARE_FUNC_LESS_EQUAL: number;
    static SPVC_MSL_SAMPLER_COMPARE_FUNC_NEVER: number;
    static SPVC_MSL_SAMPLER_COMPARE_FUNC_NOT_EQUAL: number;
    static SPVC_MSL_SAMPLER_COORD_NORMALIZED: number;
    static SPVC_MSL_SAMPLER_COORD_PIXEL: number;
    static SPVC_MSL_SAMPLER_FILTER_LINEAR: number;
    static SPVC_MSL_SAMPLER_FILTER_NEAREST: number;
    static SPVC_MSL_SAMPLER_MIP_FILTER_LINEAR: number;
    static SPVC_MSL_SAMPLER_MIP_FILTER_NEAREST: number;
    static SPVC_MSL_SAMPLER_MIP_FILTER_NONE: number;
    static SPVC_MSL_SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY: number;
    static SPVC_MSL_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_BT_2020: number;
    static SPVC_MSL_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_BT_601: number;
    static SPVC_MSL_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_BT_709: number;
    static SPVC_MSL_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY: number;
    static SPVC_MSL_SAMPLER_YCBCR_RANGE_ITU_FULL: number;
    static SPVC_MSL_SAMPLER_YCBCR_RANGE_ITU_NARROW: number;
    static SPVC_MSL_SHADER_INPUT_FORMAT_ANY16: number;
    static SPVC_MSL_SHADER_INPUT_FORMAT_ANY32: number;
    static SPVC_MSL_SHADER_INPUT_FORMAT_OTHER: number;
    static SPVC_MSL_SHADER_INPUT_FORMAT_UINT16: number;
    static SPVC_MSL_SHADER_INPUT_FORMAT_UINT8: number;
    static SPVC_MSL_SHADER_VARIABLE_FORMAT_ANY16: number;
    static SPVC_MSL_SHADER_VARIABLE_FORMAT_ANY32: number;
    static SPVC_MSL_SHADER_VARIABLE_FORMAT_OTHER: number;
    static SPVC_MSL_SHADER_VARIABLE_FORMAT_UINT16: number;
    static SPVC_MSL_SHADER_VARIABLE_FORMAT_UINT8: number;
    static SPVC_MSL_SHADER_VARIABLE_RATE_PER_PATCH: number;
    static SPVC_MSL_SHADER_VARIABLE_RATE_PER_PRIMITIVE: number;
    static SPVC_MSL_SHADER_VARIABLE_RATE_PER_VERTEX: number;
    static SPVC_MSL_SWIZZLE_BUFFER_BINDING: number;
    static SPVC_MSL_VERTEX_FORMAT_OTHER: number;
    static SPVC_MSL_VERTEX_FORMAT_UINT16: number;
    static SPVC_MSL_VERTEX_FORMAT_UINT8: number;
    static SPVC_RESOURCE_TYPE_ACCELERATION_STRUCTURE: number;
    static SPVC_RESOURCE_TYPE_ATOMIC_COUNTER: number;
    static SPVC_RESOURCE_TYPE_GL_PLAIN_UNIFORM: number;
    static SPVC_RESOURCE_TYPE_PUSH_CONSTANT: number;
    static SPVC_RESOURCE_TYPE_RAY_QUERY: number;
    static SPVC_RESOURCE_TYPE_SAMPLED_IMAGE: number;
    static SPVC_RESOURCE_TYPE_SEPARATE_IMAGE: number;
    static SPVC_RESOURCE_TYPE_SEPARATE_SAMPLERS: number;
    static SPVC_RESOURCE_TYPE_SHADER_RECORD_BUFFER: number;
    static SPVC_RESOURCE_TYPE_STAGE_INPUT: number;
    static SPVC_RESOURCE_TYPE_STAGE_OUTPUT: number;
    static SPVC_RESOURCE_TYPE_STORAGE_BUFFER: number;
    static SPVC_RESOURCE_TYPE_STORAGE_IMAGE: number;
    static SPVC_RESOURCE_TYPE_SUBPASS_INPUT: number;
    static SPVC_RESOURCE_TYPE_TENSOR: number;
    static SPVC_RESOURCE_TYPE_UNIFORM_BUFFER: number;
    static SPVC_RESOURCE_TYPE_UNKNOWN: number;
    static SPVC_SUCCESS: number;
    static getLibrary(): SharedLibrary;
    static nspvc_compiler_add_header_line(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_buffer_get_hlsl_counter_buffer(paramarg0: number, paramarg1: number, paramarg2: number): boolean;
    static nspvc_compiler_build_dummy_sampler_for_combined_images(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_compile(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_create_compiler_options(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_create_shader_resources(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_create_shader_resources_for_active_variables(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_get_active_buffer_ranges(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_compiler_get_active_interface_variables(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_get_binary_offset_for_decoration(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static nspvc_compiler_get_buffer_block_decorations(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_compiler_get_cleansed_entry_point_name(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_get_combined_image_samplers(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_get_declared_capabilities(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_get_declared_extensions(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_get_declared_struct_member_size(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_compiler_get_declared_struct_size(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_get_declared_struct_size_runtime_array(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_compiler_get_decoration_string(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_get_entry_points(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_get_execution_modes(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_get_member_decoration_string(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_compiler_get_member_name(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_get_name(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_get_remapped_declared_block_name(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_get_required_extension(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_get_specialization_constants(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_get_work_group_size_specialization_constants(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_compiler_hlsl_add_resource_binding(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_hlsl_add_vertex_attribute_remap(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_hlsl_set_root_constants_layout(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_msl_add_resource_binding(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_msl_add_resource_binding_2(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_msl_add_shader_input(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_msl_add_shader_input_2(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_msl_add_shader_output(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_msl_add_shader_output_2(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_msl_add_vertex_attribute(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_msl_get_combined_sampler_suffix(paramarg0: number): number;
    static nspvc_compiler_msl_remap_constexpr_sampler(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_msl_remap_constexpr_sampler_by_binding(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_compiler_msl_remap_constexpr_sampler_by_binding_ycbcr(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nspvc_compiler_msl_remap_constexpr_sampler_ycbcr(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_compiler_msl_set_combined_sampler_suffix(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_rename_entry_point(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_compiler_require_extension(paramarg0: number, paramarg1: number): number;
    static nspvc_compiler_set_decoration_string(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nspvc_compiler_set_entry_point(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvc_compiler_set_member_decoration_string(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nspvc_compiler_set_member_name(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nspvc_compiler_set_name(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nspvc_compiler_type_struct_member_array_stride(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_compiler_type_struct_member_matrix_stride(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_compiler_type_struct_member_offset(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_constant_get_subconstants(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nspvc_context_create(paramarg0: number): number;
    static nspvc_context_create_compiler(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nspvc_context_get_last_error_string(paramarg0: number): number;
    static nspvc_context_parse_spirv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_context_set_error_callback(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nspvc_get_commit_revision_and_timestamp(): number;
    static nspvc_get_version(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nspvc_hlsl_resource_binding_init(paramarg0: number): void;
    static nspvc_msl_constexpr_sampler_init(paramarg0: number): void;
    static nspvc_msl_resource_binding_init(paramarg0: number): void;
    static nspvc_msl_resource_binding_init_2(paramarg0: number): void;
    static nspvc_msl_sampler_ycbcr_conversion_init(paramarg0: number): void;
    static nspvc_msl_shader_input_init(paramarg0: number): void;
    static nspvc_msl_shader_interface_var_init(paramarg0: number): void;
    static nspvc_msl_shader_interface_var_init_2(paramarg0: number): void;
    static nspvc_msl_vertex_attribute_init(paramarg0: number): void;
    static nspvc_resources_get_builtin_resource_list_for_type(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvc_resources_get_resource_list_for_type(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static spvc_compiler_add_header_line(paramarg0: number, paramarg1: CharSequence): number;
    static spvc_compiler_add_header_line(paramarg0: number, paramarg1: ByteBuffer): number;
    static spvc_compiler_buffer_get_hlsl_counter_buffer(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): boolean;
    static spvc_compiler_buffer_is_hlsl_counter_buffer(paramarg0: number, paramarg1: number): boolean;
    static spvc_compiler_build_combined_image_samplers(paramarg0: number): number;
    static spvc_compiler_build_dummy_sampler_for_combined_images(paramarg0: number, paramarg1: IntBuffer): number;
    static spvc_compiler_compile(paramarg0: number, paramarg1: PointerBuffer): number;
    static spvc_compiler_create_compiler_options(paramarg0: number, paramarg1: PointerBuffer): number;
    static spvc_compiler_create_shader_resources(paramarg0: number, paramarg1: PointerBuffer): number;
    static spvc_compiler_create_shader_resources_for_active_variables(paramarg0: number, paramarg1: PointerBuffer, paramarg2: number): number;
    static spvc_compiler_flatten_buffer_block(paramarg0: number, paramarg1: number): number;
    static spvc_compiler_get_active_buffer_ranges(paramarg0: number, paramarg1: number, paramarg2: PointerBuffer, paramarg3: PointerBuffer): number;
    static spvc_compiler_get_active_interface_variables(paramarg0: number, paramarg1: PointerBuffer): number;
    static spvc_compiler_get_binary_offset_for_decoration(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): boolean;
    static spvc_compiler_get_buffer_block_decorations(paramarg0: number, paramarg1: number, paramarg2: PointerBuffer, paramarg3: PointerBuffer): number;
    static spvc_compiler_get_cleansed_entry_point_name(paramarg0: number, paramarg1: CharSequence, paramarg2: number): string;
    static spvc_compiler_get_cleansed_entry_point_name(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number): string;
    static spvc_compiler_get_combined_image_samplers(paramarg0: number, paramarg1: PointerBuffer, paramarg2: PointerBuffer): number;
    static spvc_compiler_get_constant_handle(paramarg0: number, paramarg1: number): number;
    static spvc_compiler_get_current_id_bound(paramarg0: number): number;
    static spvc_compiler_get_declared_capabilities(paramarg0: number, paramarg1: PointerBuffer, paramarg2: PointerBuffer): number;
    static spvc_compiler_get_declared_extensions(paramarg0: number, paramarg1: PointerBuffer, paramarg2: PointerBuffer): number;
    static spvc_compiler_get_declared_struct_member_size(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: PointerBuffer): number;
    static spvc_compiler_get_declared_struct_size(paramarg0: number, paramarg1: number, paramarg2: PointerBuffer): number;
    static spvc_compiler_get_declared_struct_size_runtime_array(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: PointerBuffer): number;
    static spvc_compiler_get_decoration(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_compiler_get_decoration_string(paramarg0: number, paramarg1: number, paramarg2: number): string;
    static spvc_compiler_get_entry_points(paramarg0: number, paramarg1: PointerBuffer, paramarg2: PointerBuffer): number;
    static spvc_compiler_get_execution_mode_argument(paramarg0: number, paramarg1: number): number;
    static spvc_compiler_get_execution_mode_argument_by_index(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_compiler_get_execution_model(paramarg0: number): number;
    static spvc_compiler_get_execution_modes(paramarg0: number, paramarg1: PointerBuffer, paramarg2: PointerBuffer): number;
    static spvc_compiler_get_member_decoration(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static spvc_compiler_get_member_decoration_string(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): string;
    static spvc_compiler_get_member_name(paramarg0: number, paramarg1: number, paramarg2: number): string;
    static spvc_compiler_get_name(paramarg0: number, paramarg1: number): string;
    static spvc_compiler_get_num_required_extensions(paramarg0: number): number;
    static spvc_compiler_get_remapped_declared_block_name(paramarg0: number, paramarg1: number): string;
    static spvc_compiler_get_required_extension(paramarg0: number, paramarg1: number): string;
    static spvc_compiler_get_specialization_constants(paramarg0: number, paramarg1: PointerBuffer, paramarg2: PointerBuffer): number;
    static spvc_compiler_get_type_handle(paramarg0: number, paramarg1: number): number;
    static spvc_compiler_get_work_group_size_specialization_constants(paramarg0: number, paramarg1: SpvcSpecializationConstant, paramarg2: SpvcSpecializationConstant, paramarg3: SpvcSpecializationConstant): number;
    static spvc_compiler_has_active_builtin(paramarg0: number, paramarg1: number, paramarg2: number): boolean;
    static spvc_compiler_has_decoration(paramarg0: number, paramarg1: number, paramarg2: number): boolean;
    static spvc_compiler_has_member_decoration(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static spvc_compiler_hlsl_add_resource_binding(paramarg0: number, paramarg1: SpvcHLSLResourceBinding): number;
    static spvc_compiler_hlsl_add_vertex_attribute_remap(paramarg0: number, paramarg1: SpvcHlslVertexAttributeRemap, paramarg2: number): number;
    static spvc_compiler_hlsl_is_resource_used(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static spvc_compiler_hlsl_remap_num_workgroups_builtin(paramarg0: number): number;
    static spvc_compiler_hlsl_set_resource_binding_flags(paramarg0: number, paramarg1: number): number;
    static spvc_compiler_hlsl_set_root_constants_layout(paramarg0: number, paramarg1: SpvcHlslRootConstants, paramarg2: number): number;
    static spvc_compiler_install_compiler_options(paramarg0: number, paramarg1: number): number;
    static spvc_compiler_mask_stage_output_by_builtin(paramarg0: number, paramarg1: number): number;
    static spvc_compiler_mask_stage_output_by_location(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_compiler_msl_add_discrete_descriptor_set(paramarg0: number, paramarg1: number): number;
    static spvc_compiler_msl_add_dynamic_buffer(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static spvc_compiler_msl_add_inline_uniform_block(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_compiler_msl_add_resource_binding(paramarg0: number, paramarg1: SpvcMslResourceBinding): number;
    static spvc_compiler_msl_add_resource_binding_2(paramarg0: number, paramarg1: SpvcMslResourceBinding2): number;
    static spvc_compiler_msl_add_shader_input(paramarg0: number, paramarg1: SpvcMslShaderInterfaceVar): number;
    static spvc_compiler_msl_add_shader_input_2(paramarg0: number, paramarg1: SpvcMslShaderInterfaceVar2): number;
    static spvc_compiler_msl_add_shader_output(paramarg0: number, paramarg1: SpvcMslShaderInterfaceVar): number;
    static spvc_compiler_msl_add_shader_output_2(paramarg0: number, paramarg1: SpvcMslShaderInterfaceVar2): number;
    static spvc_compiler_msl_add_vertex_attribute(paramarg0: number, paramarg1: SpvcMslVertexAttribute): number;
    static spvc_compiler_msl_get_automatic_resource_binding(paramarg0: number, paramarg1: number): number;
    static spvc_compiler_msl_get_automatic_resource_binding_secondary(paramarg0: number, paramarg1: number): number;
    static spvc_compiler_msl_get_combined_sampler_suffix(paramarg0: number): string;
    static spvc_compiler_msl_is_rasterization_disabled(paramarg0: number): boolean;
    static spvc_compiler_msl_is_resource_used(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static spvc_compiler_msl_is_shader_input_used(paramarg0: number, paramarg1: number): boolean;
    static spvc_compiler_msl_is_shader_output_used(paramarg0: number, paramarg1: number): boolean;
    static spvc_compiler_msl_is_vertex_attribute_used(paramarg0: number, paramarg1: number): boolean;
    static spvc_compiler_msl_needs_buffer_size_buffer(paramarg0: number): boolean;
    static spvc_compiler_msl_needs_input_threadgroup_mem(paramarg0: number): boolean;
    static spvc_compiler_msl_needs_output_buffer(paramarg0: number): boolean;
    static spvc_compiler_msl_needs_patch_output_buffer(paramarg0: number): boolean;
    static spvc_compiler_msl_needs_swizzle_buffer(paramarg0: number): boolean;
    static spvc_compiler_msl_remap_constexpr_sampler(paramarg0: number, paramarg1: number, paramarg2: SpvcMslConstexprSampler): number;
    static spvc_compiler_msl_remap_constexpr_sampler_by_binding(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: SpvcMslConstexprSampler): number;
    static spvc_compiler_msl_remap_constexpr_sampler_by_binding_ycbcr(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: SpvcMslConstexprSampler, paramarg4: SpvcMslSamplerYcbcrConversion): number;
    static spvc_compiler_msl_remap_constexpr_sampler_ycbcr(paramarg0: number, paramarg1: number, paramarg2: SpvcMslConstexprSampler, paramarg3: SpvcMslSamplerYcbcrConversion): number;
    static spvc_compiler_msl_set_argument_buffer_device_address_space(paramarg0: number, paramarg1: number, paramarg2: boolean): number;
    static spvc_compiler_msl_set_combined_sampler_suffix(paramarg0: number, paramarg1: CharSequence): number;
    static spvc_compiler_msl_set_combined_sampler_suffix(paramarg0: number, paramarg1: ByteBuffer): number;
    static spvc_compiler_msl_set_fragment_output_components(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_compiler_options_set_bool(paramarg0: number, paramarg1: number, paramarg2: boolean): number;
    static spvc_compiler_options_set_uint(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_compiler_rename_entry_point(paramarg0: number, paramarg1: CharSequence, paramarg2: CharSequence, paramarg3: number): number;
    static spvc_compiler_rename_entry_point(paramarg0: number, paramarg1: ByteBuffer, paramarg2: ByteBuffer, paramarg3: number): number;
    static spvc_compiler_require_extension(paramarg0: number, paramarg1: CharSequence): number;
    static spvc_compiler_require_extension(paramarg0: number, paramarg1: ByteBuffer): number;
    static spvc_compiler_set_decoration(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static spvc_compiler_set_decoration_string(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static spvc_compiler_set_decoration_string(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer): void;
    static spvc_compiler_set_enabled_interface_variables(paramarg0: number, paramarg1: number): number;
    static spvc_compiler_set_entry_point(paramarg0: number, paramarg1: CharSequence, paramarg2: number): number;
    static spvc_compiler_set_entry_point(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number): number;
    static spvc_compiler_set_execution_mode(paramarg0: number, paramarg1: number): void;
    static spvc_compiler_set_execution_mode_with_arguments(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static spvc_compiler_set_member_decoration(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static spvc_compiler_set_member_decoration_string(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: CharSequence): void;
    static spvc_compiler_set_member_decoration_string(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: ByteBuffer): void;
    static spvc_compiler_set_member_name(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static spvc_compiler_set_member_name(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer): void;
    static spvc_compiler_set_name(paramarg0: number, paramarg1: number, paramarg2: CharSequence): void;
    static spvc_compiler_set_name(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer): void;
    static spvc_compiler_type_struct_member_array_stride(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): number;
    static spvc_compiler_type_struct_member_matrix_stride(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): number;
    static spvc_compiler_type_struct_member_offset(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): number;
    static spvc_compiler_unset_decoration(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static spvc_compiler_unset_execution_mode(paramarg0: number, paramarg1: number): void;
    static spvc_compiler_unset_member_decoration(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static spvc_compiler_update_active_builtins(paramarg0: number): void;
    static spvc_compiler_variable_is_depth_or_compare(paramarg0: number, paramarg1: number): boolean;
    static spvc_constant_get_scalar_fp16(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_constant_get_scalar_fp32(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_constant_get_scalar_fp64(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_constant_get_scalar_i16(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_constant_get_scalar_i32(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_constant_get_scalar_i64(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_constant_get_scalar_i8(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_constant_get_scalar_u16(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_constant_get_scalar_u32(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_constant_get_scalar_u64(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_constant_get_scalar_u8(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static spvc_constant_get_subconstants(paramarg0: number, paramarg1: PointerBuffer, paramarg2: PointerBuffer): void;
    static spvc_constant_get_type(paramarg0: number): number;
    static spvc_constant_set_scalar_fp16(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static spvc_constant_set_scalar_fp32(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static spvc_constant_set_scalar_fp64(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static spvc_constant_set_scalar_i16(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static spvc_constant_set_scalar_i32(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static spvc_constant_set_scalar_i64(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static spvc_constant_set_scalar_i8(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static spvc_constant_set_scalar_u16(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static spvc_constant_set_scalar_u32(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static spvc_constant_set_scalar_u64(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static spvc_constant_set_scalar_u8(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static spvc_context_create(paramarg0: PointerBuffer): number;
    static spvc_context_create_compiler(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: PointerBuffer): number;
    static spvc_context_destroy(paramarg0: number): void;
    static spvc_context_get_last_error_string(paramarg0: number): string;
    static spvc_context_parse_spirv(paramarg0: number, paramarg1: IntBuffer, paramarg2: number, paramarg3: PointerBuffer): number;
    static spvc_context_release_allocations(paramarg0: number): void;
    static spvc_context_set_error_callback(paramarg0: number, paramarg1: (param0: number, param1: number) => void, paramarg2: number): void;
    static spvc_get_commit_revision_and_timestamp(): string;
    static spvc_get_version(paramarg0: IntBuffer, paramarg1: IntBuffer, paramarg2: IntBuffer): void;
    static spvc_hlsl_resource_binding_init(paramarg0: SpvcHLSLResourceBinding): void;
    static spvc_msl_constexpr_sampler_init(paramarg0: SpvcMslConstexprSampler): void;
    static spvc_msl_get_aux_buffer_struct_version(): number;
    static spvc_msl_resource_binding_init(paramarg0: SpvcMslResourceBinding): void;
    static spvc_msl_resource_binding_init_2(paramarg0: SpvcMslResourceBinding2): void;
    static spvc_msl_sampler_ycbcr_conversion_init(paramarg0: SpvcMslSamplerYcbcrConversion): void;
    static spvc_msl_shader_input_init(paramarg0: SpvcMslShaderInput): void;
    static spvc_msl_shader_interface_var_init(paramarg0: SpvcMslShaderInterfaceVar): void;
    static spvc_msl_shader_interface_var_init_2(paramarg0: SpvcMslShaderInterfaceVar2): void;
    static spvc_msl_vertex_attribute_init(paramarg0: SpvcMslVertexAttribute): void;
    static spvc_resources_get_builtin_resource_list_for_type(paramarg0: number, paramarg1: number, paramarg2: PointerBuffer, paramarg3: PointerBuffer): number;
    static spvc_resources_get_resource_list_for_type(paramarg0: number, paramarg1: number, paramarg2: PointerBuffer, paramarg3: PointerBuffer): number;
    static spvc_type_array_dimension_is_literal(paramarg0: number, paramarg1: number): boolean;
    static spvc_type_get_array_dimension(paramarg0: number, paramarg1: number): number;
    static spvc_type_get_base_type_id(paramarg0: number): number;
    static spvc_type_get_basetype(paramarg0: number): number;
    static spvc_type_get_bit_width(paramarg0: number): number;
    static spvc_type_get_columns(paramarg0: number): number;
    static spvc_type_get_image_access_qualifier(paramarg0: number): number;
    static spvc_type_get_image_arrayed(paramarg0: number): boolean;
    static spvc_type_get_image_dimension(paramarg0: number): number;
    static spvc_type_get_image_is_depth(paramarg0: number): boolean;
    static spvc_type_get_image_is_storage(paramarg0: number): boolean;
    static spvc_type_get_image_multisampled(paramarg0: number): boolean;
    static spvc_type_get_image_sampled_type(paramarg0: number): number;
    static spvc_type_get_image_storage_format(paramarg0: number): number;
    static spvc_type_get_member_type(paramarg0: number, paramarg1: number): number;
    static spvc_type_get_num_array_dimensions(paramarg0: number): number;
    static spvc_type_get_num_member_types(paramarg0: number): number;
    static spvc_type_get_storage_class(paramarg0: number): number;
    static spvc_type_get_vector_size(paramarg0: number): number;
    constructor()
}