import type { Object } from '../../../../../../java/lang/Object.d.ts'
import type { TarArchiveStructSparse } from '../../../../../../org/apache/commons/compress/archivers/tar/TarArchiveStructSparse.d.ts'
import type { TarConstants } from '../../../../../../org/apache/commons/compress/archivers/tar/TarConstants.d.ts'
export class TarArchiveSparseEntry extends Object implements TarConstants {
    static ATIMELEN_GNU: number;
    static ATIMELEN_XSTAR: number;
    static CHKSUMLEN: number;
    static CHKSUM_OFFSET: number;
    static CTIMELEN_GNU: number;
    static CTIMELEN_XSTAR: number;
    static DEFAULT_BLKSIZE: number;
    static DEFAULT_RCDSIZE: number;
    static DEVLEN: number;
    static FORMAT_OLDGNU: number;
    static FORMAT_POSIX: number;
    static FORMAT_XSTAR: number;
    static GIDLEN: number;
    static GNAMELEN: number;
    static GNU_LONGLINK: string;
    static ISEXTENDEDLEN_GNU: number;
    static ISEXTENDEDLEN_GNU_SPARSE: number;
    static LF_BLK: number;
    static LF_CHR: number;
    static LF_CONTIG: number;
    static LF_DIR: number;
    static LF_FIFO: number;
    static LF_GNUTYPE_LONGLINK: number;
    static LF_GNUTYPE_LONGNAME: number;
    static LF_GNUTYPE_SPARSE: number;
    static LF_LINK: number;
    static LF_MULTIVOLUME: number;
    static LF_NORMAL: number;
    static LF_OFFSET: number;
    static LF_OLDNORM: number;
    static LF_PAX_EXTENDED_HEADER_LC: number;
    static LF_PAX_EXTENDED_HEADER_UC: number;
    static LF_PAX_GLOBAL_EXTENDED_HEADER: number;
    static LF_SYMLINK: number;
    static LONGNAMESLEN_GNU: number;
    static MAGICLEN: number;
    static MAGIC_ANT: string;
    static MAGIC_GNU: string;
    static MAGIC_OFFSET: number;
    static MAGIC_POSIX: string;
    static MAGIC_XSTAR: string;
    static MAXID: number;
    static MAXSIZE: number;
    static MODELEN: number;
    static MODTIMELEN: number;
    static NAMELEN: number;
    static OFFSETLEN_GNU: number;
    static PAD2LEN_GNU: number;
    static PREFIXLEN: number;
    static PREFIXLEN_XSTAR: number;
    static REALSIZELEN_GNU: number;
    static SIZELEN: number;
    static SPARSELEN_GNU: number;
    static SPARSELEN_GNU_SPARSE: number;
    static SPARSE_HEADERS_IN_EXTENSION_HEADER: number;
    static SPARSE_HEADERS_IN_OLDGNU_HEADER: number;
    static SPARSE_NUMBYTES_LEN: number;
    static SPARSE_OFFSET_LEN: number;
    static UIDLEN: number;
    static UNAMELEN: number;
    static VERSIONLEN: number;
    static VERSION_ANT: string;
    static VERSION_GNU_SPACE: string;
    static VERSION_GNU_ZERO: string;
    static VERSION_OFFSET: number;
    static VERSION_POSIX: string;
    static XSTAR_ATIME_OFFSET: number;
    static XSTAR_CTIME_OFFSET: number;
    static XSTAR_MAGIC_LEN: number;
    static XSTAR_MAGIC_OFFSET: number;
    static XSTAR_MULTIVOLUME_OFFSET: number;
    static XSTAR_PREFIX_OFFSET: number;
    constructor(arg0: number[])
    // private isExtended: boolean;
    readonly sparseHeaders: TarArchiveStructSparse[];
    getSparseHeaders(): TarArchiveStructSparse[];
    isExtended(): boolean;
}