import type { App } from '../../../../com/mojang/datafixers/kinds/App.d.ts'
import type { Applicative } from '../../../../com/mojang/datafixers/kinds/Applicative.d.ts'
import type { Applicative$Mu } from '../../../../com/mojang/datafixers/kinds/Applicative$Mu.d.ts'
import type { Const$Instance$Mu } from '../../../../com/mojang/datafixers/kinds/Const$Instance$Mu.d.ts'
import type { Const$Mu } from '../../../../com/mojang/datafixers/kinds/Const$Mu.d.ts'
import type { K1 } from '../../../../com/mojang/datafixers/kinds/K1.d.ts'
import type { Monoid } from '../../../../com/mojang/datafixers/kinds/Monoid.d.ts'
import type { Function10 } from '../../../../com/mojang/datafixers/util/Function10.d.ts'
import type { Function11 } from '../../../../com/mojang/datafixers/util/Function11.d.ts'
import type { Function12 } from '../../../../com/mojang/datafixers/util/Function12.d.ts'
import type { Function13 } from '../../../../com/mojang/datafixers/util/Function13.d.ts'
import type { Function14 } from '../../../../com/mojang/datafixers/util/Function14.d.ts'
import type { Function15 } from '../../../../com/mojang/datafixers/util/Function15.d.ts'
import type { Function16 } from '../../../../com/mojang/datafixers/util/Function16.d.ts'
import type { Function3 } from '../../../../com/mojang/datafixers/util/Function3.d.ts'
import type { Function4 } from '../../../../com/mojang/datafixers/util/Function4.d.ts'
import type { Function5 } from '../../../../com/mojang/datafixers/util/Function5.d.ts'
import type { Function6 } from '../../../../com/mojang/datafixers/util/Function6.d.ts'
import type { Function7 } from '../../../../com/mojang/datafixers/util/Function7.d.ts'
import type { Function8 } from '../../../../com/mojang/datafixers/util/Function8.d.ts'
import type { Function9 } from '../../../../com/mojang/datafixers/util/Function9.d.ts'
import type { BiFunction } from '../../../../java/util/function/BiFunction.d.ts'
import type { Function } from '../../../../java/util/function/Function.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
export class Const$Instance<C extends Object | number | string | boolean> extends Object implements Applicative<Const$Mu<C>, Const$Instance$Mu<C>> {
    static unbox(paramarg0: App<Applicative$Mu, K1>): Applicative<K1, Applicative$Mu>;
    constructor(arg0: Monoid<C>)
    // private monoid: Monoid<C>;
    ap<R extends Object | number | string | boolean, A extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, (param0: A) => R>, arg1: App<Const$Mu<C>, A>): App<Const$Mu<C>, R>;
    ap<R extends Object | number | string | boolean, A extends Object | number | string | boolean>(arg0: (param0: A) => R, arg1: App<Const$Mu<C>, A>): App<Const$Mu<C>, R>;
    ap10<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>, arg7: App<Const$Mu<C>, T7>, arg8: App<Const$Mu<C>, T8>, arg9: App<Const$Mu<C>, T9>, arg10: App<Const$Mu<C>, T10>): App<Const$Mu<C>, R>;
    ap11<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>, arg7: App<Const$Mu<C>, T7>, arg8: App<Const$Mu<C>, T8>, arg9: App<Const$Mu<C>, T9>, arg10: App<Const$Mu<C>, T10>, arg11: App<Const$Mu<C>, T11>): App<Const$Mu<C>, R>;
    ap12<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>, arg7: App<Const$Mu<C>, T7>, arg8: App<Const$Mu<C>, T8>, arg9: App<Const$Mu<C>, T9>, arg10: App<Const$Mu<C>, T10>, arg11: App<Const$Mu<C>, T11>, arg12: App<Const$Mu<C>, T12>): App<Const$Mu<C>, R>;
    ap13<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>, arg7: App<Const$Mu<C>, T7>, arg8: App<Const$Mu<C>, T8>, arg9: App<Const$Mu<C>, T9>, arg10: App<Const$Mu<C>, T10>, arg11: App<Const$Mu<C>, T11>, arg12: App<Const$Mu<C>, T12>, arg13: App<Const$Mu<C>, T13>): App<Const$Mu<C>, R>;
    ap14<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>, arg7: App<Const$Mu<C>, T7>, arg8: App<Const$Mu<C>, T8>, arg9: App<Const$Mu<C>, T9>, arg10: App<Const$Mu<C>, T10>, arg11: App<Const$Mu<C>, T11>, arg12: App<Const$Mu<C>, T12>, arg13: App<Const$Mu<C>, T13>, arg14: App<Const$Mu<C>, T14>): App<Const$Mu<C>, R>;
    ap15<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean, T15 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>, arg7: App<Const$Mu<C>, T7>, arg8: App<Const$Mu<C>, T8>, arg9: App<Const$Mu<C>, T9>, arg10: App<Const$Mu<C>, T10>, arg11: App<Const$Mu<C>, T11>, arg12: App<Const$Mu<C>, T12>, arg13: App<Const$Mu<C>, T13>, arg14: App<Const$Mu<C>, T14>, arg15: App<Const$Mu<C>, T15>): App<Const$Mu<C>, R>;
    ap16<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean, T15 extends Object | number | string | boolean, T16 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>, arg7: App<Const$Mu<C>, T7>, arg8: App<Const$Mu<C>, T8>, arg9: App<Const$Mu<C>, T9>, arg10: App<Const$Mu<C>, T10>, arg11: App<Const$Mu<C>, T11>, arg12: App<Const$Mu<C>, T12>, arg13: App<Const$Mu<C>, T13>, arg14: App<Const$Mu<C>, T14>, arg15: App<Const$Mu<C>, T15>, arg16: App<Const$Mu<C>, T16>): App<Const$Mu<C>, R>;
    ap2<R extends Object | number | string | boolean, A extends Object | number | string | boolean, B extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, (param0: A, param1: B) => R>, arg1: App<Const$Mu<C>, A>, arg2: App<Const$Mu<C>, B>): App<Const$Mu<C>, R>;
    ap3<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function3<T1, T2, T3, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>): App<Const$Mu<C>, R>;
    ap4<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function4<T1, T2, T3, T4, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>): App<Const$Mu<C>, R>;
    ap5<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function5<T1, T2, T3, T4, T5, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>): App<Const$Mu<C>, R>;
    ap6<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function6<T1, T2, T3, T4, T5, T6, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>): App<Const$Mu<C>, R>;
    ap7<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function7<T1, T2, T3, T4, T5, T6, T7, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>, arg7: App<Const$Mu<C>, T7>): App<Const$Mu<C>, R>;
    ap8<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>, arg7: App<Const$Mu<C>, T7>, arg8: App<Const$Mu<C>, T8>): App<Const$Mu<C>, R>;
    ap9<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>, arg7: App<Const$Mu<C>, T7>, arg8: App<Const$Mu<C>, T8>, arg9: App<Const$Mu<C>, T9>): App<Const$Mu<C>, R>;
    apply2<R extends Object | number | string | boolean, A extends Object | number | string | boolean, B extends Object | number | string | boolean>(arg0: (param0: A, param1: B) => R, arg1: App<Const$Mu<C>, A>, arg2: App<Const$Mu<C>, B>): App<Const$Mu<C>, R>;
    apply3<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean>(arg0: Function3<T1, T2, T3, R>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>): App<Const$Mu<C>, R>;
    apply4<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean>(arg0: Function4<T1, T2, T3, T4, R>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>): App<Const$Mu<C>, R>;
    apply5<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean>(arg0: Function5<T1, T2, T3, T4, T5, R>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>): App<Const$Mu<C>, R>;
    apply6<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean>(arg0: Function6<T1, T2, T3, T4, T5, T6, R>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>): App<Const$Mu<C>, R>;
    apply7<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean>(arg0: Function7<T1, T2, T3, T4, T5, T6, T7, R>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>, arg7: App<Const$Mu<C>, T7>): App<Const$Mu<C>, R>;
    apply8<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean>(arg0: Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>, arg7: App<Const$Mu<C>, T7>, arg8: App<Const$Mu<C>, T8>): App<Const$Mu<C>, R>;
    apply9<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean>(arg0: Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>, arg1: App<Const$Mu<C>, T1>, arg2: App<Const$Mu<C>, T2>, arg3: App<Const$Mu<C>, T3>, arg4: App<Const$Mu<C>, T4>, arg5: App<Const$Mu<C>, T5>, arg6: App<Const$Mu<C>, T6>, arg7: App<Const$Mu<C>, T7>, arg8: App<Const$Mu<C>, T8>, arg9: App<Const$Mu<C>, T9>): App<Const$Mu<C>, R>;
    lift1<A extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, (param0: A) => R>): (param0: App<Const$Mu<C>, A>) => App<Const$Mu<C>, R>;
    lift2<A extends Object | number | string | boolean, B extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, (param0: A, param1: B) => R>): (param0: App<Const$Mu<C>, A>, param1: App<Const$Mu<C>, B>) => App<Const$Mu<C>, R>;
    lift3<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function3<T1, T2, T3, R>>): Function3<App<Const$Mu<C>, T1>, App<Const$Mu<C>, T2>, App<Const$Mu<C>, T3>, App<Const$Mu<C>, R>>;
    lift4<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function4<T1, T2, T3, T4, R>>): Function4<App<Const$Mu<C>, T1>, App<Const$Mu<C>, T2>, App<Const$Mu<C>, T3>, App<Const$Mu<C>, T4>, App<Const$Mu<C>, R>>;
    lift5<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function5<T1, T2, T3, T4, T5, R>>): Function5<App<Const$Mu<C>, T1>, App<Const$Mu<C>, T2>, App<Const$Mu<C>, T3>, App<Const$Mu<C>, T4>, App<Const$Mu<C>, T5>, App<Const$Mu<C>, R>>;
    lift6<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function6<T1, T2, T3, T4, T5, T6, R>>): Function6<App<Const$Mu<C>, T1>, App<Const$Mu<C>, T2>, App<Const$Mu<C>, T3>, App<Const$Mu<C>, T4>, App<Const$Mu<C>, T5>, App<Const$Mu<C>, T6>, App<Const$Mu<C>, R>>;
    lift7<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function7<T1, T2, T3, T4, T5, T6, T7, R>>): Function7<App<Const$Mu<C>, T1>, App<Const$Mu<C>, T2>, App<Const$Mu<C>, T3>, App<Const$Mu<C>, T4>, App<Const$Mu<C>, T5>, App<Const$Mu<C>, T6>, App<Const$Mu<C>, T7>, App<Const$Mu<C>, R>>;
    lift8<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>>): Function8<App<Const$Mu<C>, T1>, App<Const$Mu<C>, T2>, App<Const$Mu<C>, T3>, App<Const$Mu<C>, T4>, App<Const$Mu<C>, T5>, App<Const$Mu<C>, T6>, App<Const$Mu<C>, T7>, App<Const$Mu<C>, T8>, App<Const$Mu<C>, R>>;
    lift9<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<Const$Mu<C>, Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>>): Function9<App<Const$Mu<C>, T1>, App<Const$Mu<C>, T2>, App<Const$Mu<C>, T3>, App<Const$Mu<C>, T4>, App<Const$Mu<C>, T5>, App<Const$Mu<C>, T6>, App<Const$Mu<C>, T7>, App<Const$Mu<C>, T8>, App<Const$Mu<C>, T9>, App<Const$Mu<C>, R>>;
    map<R extends Object | number | string | boolean, T extends Object | number | string | boolean>(arg0: (param0: T) => R, arg1: App<Const$Mu<C>, T>): App<Const$Mu<C>, R>;
    point<A extends Object | number | string | boolean>(arg0: A): App<Const$Mu<C>, A>;
}