import type { Products$P1 } from '../../../../com/mojang/datafixers/Products$P1.d.ts'
import type { Products$P10 } from '../../../../com/mojang/datafixers/Products$P10.d.ts'
import type { Products$P11 } from '../../../../com/mojang/datafixers/Products$P11.d.ts'
import type { Products$P12 } from '../../../../com/mojang/datafixers/Products$P12.d.ts'
import type { Products$P13 } from '../../../../com/mojang/datafixers/Products$P13.d.ts'
import type { Products$P14 } from '../../../../com/mojang/datafixers/Products$P14.d.ts'
import type { Products$P15 } from '../../../../com/mojang/datafixers/Products$P15.d.ts'
import type { Products$P16 } from '../../../../com/mojang/datafixers/Products$P16.d.ts'
import type { Products$P2 } from '../../../../com/mojang/datafixers/Products$P2.d.ts'
import type { Products$P3 } from '../../../../com/mojang/datafixers/Products$P3.d.ts'
import type { Products$P4 } from '../../../../com/mojang/datafixers/Products$P4.d.ts'
import type { Products$P5 } from '../../../../com/mojang/datafixers/Products$P5.d.ts'
import type { Products$P6 } from '../../../../com/mojang/datafixers/Products$P6.d.ts'
import type { Products$P7 } from '../../../../com/mojang/datafixers/Products$P7.d.ts'
import type { Products$P8 } from '../../../../com/mojang/datafixers/Products$P8.d.ts'
import type { Products$P9 } from '../../../../com/mojang/datafixers/Products$P9.d.ts'
import type { App } from '../../../../com/mojang/datafixers/kinds/App.d.ts'
import type { K1 } from '../../../../com/mojang/datafixers/kinds/K1.d.ts'
import type { Kind1$Mu } from '../../../../com/mojang/datafixers/kinds/Kind1$Mu.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
export interface Kind1<F extends K1, Mu extends Kind1$Mu> extends App<Mu, F>, Object{
    group<T1 extends Object | number | string | boolean>(arg0: App<F, T1>): Products$P1<F, T1>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>): Products$P2<F, T1, T2>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>): Products$P3<F, T1, T2, T3>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>, arg3: App<F, T4>): Products$P4<F, T1, T2, T3, T4>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>, arg3: App<F, T4>, arg4: App<F, T5>): Products$P5<F, T1, T2, T3, T4, T5>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>, arg3: App<F, T4>, arg4: App<F, T5>, arg5: App<F, T6>): Products$P6<F, T1, T2, T3, T4, T5, T6>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>, arg3: App<F, T4>, arg4: App<F, T5>, arg5: App<F, T6>, arg6: App<F, T7>): Products$P7<F, T1, T2, T3, T4, T5, T6, T7>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>, arg3: App<F, T4>, arg4: App<F, T5>, arg5: App<F, T6>, arg6: App<F, T7>, arg7: App<F, T8>): Products$P8<F, T1, T2, T3, T4, T5, T6, T7, T8>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>, arg3: App<F, T4>, arg4: App<F, T5>, arg5: App<F, T6>, arg6: App<F, T7>, arg7: App<F, T8>, arg8: App<F, T9>): Products$P9<F, T1, T2, T3, T4, T5, T6, T7, T8, T9>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>, arg3: App<F, T4>, arg4: App<F, T5>, arg5: App<F, T6>, arg6: App<F, T7>, arg7: App<F, T8>, arg8: App<F, T9>, arg9: App<F, T10>): Products$P10<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>, arg3: App<F, T4>, arg4: App<F, T5>, arg5: App<F, T6>, arg6: App<F, T7>, arg7: App<F, T8>, arg8: App<F, T9>, arg9: App<F, T10>, arg10: App<F, T11>): Products$P11<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>, arg3: App<F, T4>, arg4: App<F, T5>, arg5: App<F, T6>, arg6: App<F, T7>, arg7: App<F, T8>, arg8: App<F, T9>, arg9: App<F, T10>, arg10: App<F, T11>, arg11: App<F, T12>): Products$P12<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>, arg3: App<F, T4>, arg4: App<F, T5>, arg5: App<F, T6>, arg6: App<F, T7>, arg7: App<F, T8>, arg8: App<F, T9>, arg9: App<F, T10>, arg10: App<F, T11>, arg11: App<F, T12>, arg12: App<F, T13>): Products$P13<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>, arg3: App<F, T4>, arg4: App<F, T5>, arg5: App<F, T6>, arg6: App<F, T7>, arg7: App<F, T8>, arg8: App<F, T9>, arg9: App<F, T10>, arg10: App<F, T11>, arg11: App<F, T12>, arg12: App<F, T13>, arg13: App<F, T14>): Products$P14<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean, T15 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>, arg3: App<F, T4>, arg4: App<F, T5>, arg5: App<F, T6>, arg6: App<F, T7>, arg7: App<F, T8>, arg8: App<F, T9>, arg9: App<F, T10>, arg10: App<F, T11>, arg11: App<F, T12>, arg12: App<F, T13>, arg13: App<F, T14>, arg14: App<F, T15>): Products$P15<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>;
    group<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean, T15 extends Object | number | string | boolean, T16 extends Object | number | string | boolean>(arg0: App<F, T1>, arg1: App<F, T2>, arg2: App<F, T3>, arg3: App<F, T4>, arg4: App<F, T5>, arg5: App<F, T6>, arg6: App<F, T7>, arg7: App<F, T8>, arg8: App<F, T9>, arg9: App<F, T10>, arg10: App<F, T11>, arg11: App<F, T12>, arg12: App<F, T13>, arg13: App<F, T14>, arg14: App<F, T15>, arg15: App<F, T16>): Products$P16<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>;
}