import type { App } from '../../../../com/mojang/datafixers/kinds/App.d.ts'
import type { Applicative } from '../../../../com/mojang/datafixers/kinds/Applicative.d.ts'
import type { Applicative$Mu } from '../../../../com/mojang/datafixers/kinds/Applicative$Mu.d.ts'
import type { K1 } from '../../../../com/mojang/datafixers/kinds/K1.d.ts'
import type { OptionalBox$Instance$Mu } from '../../../../com/mojang/datafixers/kinds/OptionalBox$Instance$Mu.d.ts'
import type { OptionalBox$Mu } from '../../../../com/mojang/datafixers/kinds/OptionalBox$Mu.d.ts'
import type { Traversable } from '../../../../com/mojang/datafixers/kinds/Traversable.d.ts'
import type { Traversable$Mu } from '../../../../com/mojang/datafixers/kinds/Traversable$Mu.d.ts'
import type { Function10 } from '../../../../com/mojang/datafixers/util/Function10.d.ts'
import type { Function11 } from '../../../../com/mojang/datafixers/util/Function11.d.ts'
import type { Function12 } from '../../../../com/mojang/datafixers/util/Function12.d.ts'
import type { Function13 } from '../../../../com/mojang/datafixers/util/Function13.d.ts'
import type { Function14 } from '../../../../com/mojang/datafixers/util/Function14.d.ts'
import type { Function15 } from '../../../../com/mojang/datafixers/util/Function15.d.ts'
import type { Function16 } from '../../../../com/mojang/datafixers/util/Function16.d.ts'
import type { Function3 } from '../../../../com/mojang/datafixers/util/Function3.d.ts'
import type { Function4 } from '../../../../com/mojang/datafixers/util/Function4.d.ts'
import type { Function5 } from '../../../../com/mojang/datafixers/util/Function5.d.ts'
import type { Function6 } from '../../../../com/mojang/datafixers/util/Function6.d.ts'
import type { Function7 } from '../../../../com/mojang/datafixers/util/Function7.d.ts'
import type { Function8 } from '../../../../com/mojang/datafixers/util/Function8.d.ts'
import type { Function9 } from '../../../../com/mojang/datafixers/util/Function9.d.ts'
import type { Class } from '../../../../java/lang/Class.d.ts'
import type { BiFunction } from '../../../../java/util/function/BiFunction.d.ts'
import type { Function } from '../../../../java/util/function/Function.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { Enum } from '../../../../java/lang/Enum.d.ts'
export class OptionalBox$Instance extends Enum<OptionalBox$Instance> implements Applicative<OptionalBox$Mu, OptionalBox$Instance$Mu>, Traversable<OptionalBox$Mu, OptionalBox$Instance$Mu> {
    static INSTANCE: OptionalBox$Instance;
    static unbox(paramarg0: App<Applicative$Mu, K1>): Applicative<K1, Applicative$Mu>;
    static unbox(paramarg0: App<Traversable$Mu, K1>): Traversable<K1, Traversable$Mu>;
    static valueOf(paramarg0: Class<Object>, paramarg1: string): Object | null;
    static valueOf(paramarg0: string): OptionalBox$Instance;
    static values(): (Object | null)[];
    private constructor()
    ap<R extends Object | number | string | boolean, A extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, (param0: A) => R>, arg1: App<OptionalBox$Mu, A>): App<OptionalBox$Mu, R>;
    ap<R extends Object | number | string | boolean, A extends Object | number | string | boolean>(arg0: (param0: A) => R, arg1: App<OptionalBox$Mu, A>): App<OptionalBox$Mu, R>;
    ap10<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>, arg7: App<OptionalBox$Mu, T7>, arg8: App<OptionalBox$Mu, T8>, arg9: App<OptionalBox$Mu, T9>, arg10: App<OptionalBox$Mu, T10>): App<OptionalBox$Mu, R>;
    ap11<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>, arg7: App<OptionalBox$Mu, T7>, arg8: App<OptionalBox$Mu, T8>, arg9: App<OptionalBox$Mu, T9>, arg10: App<OptionalBox$Mu, T10>, arg11: App<OptionalBox$Mu, T11>): App<OptionalBox$Mu, R>;
    ap12<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>, arg7: App<OptionalBox$Mu, T7>, arg8: App<OptionalBox$Mu, T8>, arg9: App<OptionalBox$Mu, T9>, arg10: App<OptionalBox$Mu, T10>, arg11: App<OptionalBox$Mu, T11>, arg12: App<OptionalBox$Mu, T12>): App<OptionalBox$Mu, R>;
    ap13<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>, arg7: App<OptionalBox$Mu, T7>, arg8: App<OptionalBox$Mu, T8>, arg9: App<OptionalBox$Mu, T9>, arg10: App<OptionalBox$Mu, T10>, arg11: App<OptionalBox$Mu, T11>, arg12: App<OptionalBox$Mu, T12>, arg13: App<OptionalBox$Mu, T13>): App<OptionalBox$Mu, R>;
    ap14<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>, arg7: App<OptionalBox$Mu, T7>, arg8: App<OptionalBox$Mu, T8>, arg9: App<OptionalBox$Mu, T9>, arg10: App<OptionalBox$Mu, T10>, arg11: App<OptionalBox$Mu, T11>, arg12: App<OptionalBox$Mu, T12>, arg13: App<OptionalBox$Mu, T13>, arg14: App<OptionalBox$Mu, T14>): App<OptionalBox$Mu, R>;
    ap15<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean, T15 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>, arg7: App<OptionalBox$Mu, T7>, arg8: App<OptionalBox$Mu, T8>, arg9: App<OptionalBox$Mu, T9>, arg10: App<OptionalBox$Mu, T10>, arg11: App<OptionalBox$Mu, T11>, arg12: App<OptionalBox$Mu, T12>, arg13: App<OptionalBox$Mu, T13>, arg14: App<OptionalBox$Mu, T14>, arg15: App<OptionalBox$Mu, T15>): App<OptionalBox$Mu, R>;
    ap16<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean, T15 extends Object | number | string | boolean, T16 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>, arg7: App<OptionalBox$Mu, T7>, arg8: App<OptionalBox$Mu, T8>, arg9: App<OptionalBox$Mu, T9>, arg10: App<OptionalBox$Mu, T10>, arg11: App<OptionalBox$Mu, T11>, arg12: App<OptionalBox$Mu, T12>, arg13: App<OptionalBox$Mu, T13>, arg14: App<OptionalBox$Mu, T14>, arg15: App<OptionalBox$Mu, T15>, arg16: App<OptionalBox$Mu, T16>): App<OptionalBox$Mu, R>;
    ap2<R extends Object | number | string | boolean, A extends Object | number | string | boolean, B extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, (param0: A, param1: B) => R>, arg1: App<OptionalBox$Mu, A>, arg2: App<OptionalBox$Mu, B>): App<OptionalBox$Mu, R>;
    ap3<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function3<T1, T2, T3, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>): App<OptionalBox$Mu, R>;
    ap4<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function4<T1, T2, T3, T4, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>): App<OptionalBox$Mu, R>;
    ap5<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function5<T1, T2, T3, T4, T5, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>): App<OptionalBox$Mu, R>;
    ap6<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function6<T1, T2, T3, T4, T5, T6, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>): App<OptionalBox$Mu, R>;
    ap7<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function7<T1, T2, T3, T4, T5, T6, T7, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>, arg7: App<OptionalBox$Mu, T7>): App<OptionalBox$Mu, R>;
    ap8<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>, arg7: App<OptionalBox$Mu, T7>, arg8: App<OptionalBox$Mu, T8>): App<OptionalBox$Mu, R>;
    ap9<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>, arg7: App<OptionalBox$Mu, T7>, arg8: App<OptionalBox$Mu, T8>, arg9: App<OptionalBox$Mu, T9>): App<OptionalBox$Mu, R>;
    apply2<R extends Object | number | string | boolean, A extends Object | number | string | boolean, B extends Object | number | string | boolean>(arg0: (param0: A, param1: B) => R, arg1: App<OptionalBox$Mu, A>, arg2: App<OptionalBox$Mu, B>): App<OptionalBox$Mu, R>;
    apply3<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean>(arg0: Function3<T1, T2, T3, R>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>): App<OptionalBox$Mu, R>;
    apply4<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean>(arg0: Function4<T1, T2, T3, T4, R>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>): App<OptionalBox$Mu, R>;
    apply5<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean>(arg0: Function5<T1, T2, T3, T4, T5, R>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>): App<OptionalBox$Mu, R>;
    apply6<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean>(arg0: Function6<T1, T2, T3, T4, T5, T6, R>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>): App<OptionalBox$Mu, R>;
    apply7<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean>(arg0: Function7<T1, T2, T3, T4, T5, T6, T7, R>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>, arg7: App<OptionalBox$Mu, T7>): App<OptionalBox$Mu, R>;
    apply8<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean>(arg0: Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>, arg7: App<OptionalBox$Mu, T7>, arg8: App<OptionalBox$Mu, T8>): App<OptionalBox$Mu, R>;
    apply9<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean>(arg0: Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>, arg1: App<OptionalBox$Mu, T1>, arg2: App<OptionalBox$Mu, T2>, arg3: App<OptionalBox$Mu, T3>, arg4: App<OptionalBox$Mu, T4>, arg5: App<OptionalBox$Mu, T5>, arg6: App<OptionalBox$Mu, T6>, arg7: App<OptionalBox$Mu, T7>, arg8: App<OptionalBox$Mu, T8>, arg9: App<OptionalBox$Mu, T9>): App<OptionalBox$Mu, R>;
    flip<F extends K1, A extends Object | number | string | boolean>(arg0: Applicative<F, any>, arg1: App<OptionalBox$Mu, App<F, A>>): App<F, App<OptionalBox$Mu, A>>;
    lift1<A extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, (param0: A) => R>): (param0: App<OptionalBox$Mu, A>) => App<OptionalBox$Mu, R>;
    lift2<A extends Object | number | string | boolean, B extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, (param0: A, param1: B) => R>): (param0: App<OptionalBox$Mu, A>, param1: App<OptionalBox$Mu, B>) => App<OptionalBox$Mu, R>;
    lift3<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function3<T1, T2, T3, R>>): Function3<App<OptionalBox$Mu, T1>, App<OptionalBox$Mu, T2>, App<OptionalBox$Mu, T3>, App<OptionalBox$Mu, R>>;
    lift4<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function4<T1, T2, T3, T4, R>>): Function4<App<OptionalBox$Mu, T1>, App<OptionalBox$Mu, T2>, App<OptionalBox$Mu, T3>, App<OptionalBox$Mu, T4>, App<OptionalBox$Mu, R>>;
    lift5<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function5<T1, T2, T3, T4, T5, R>>): Function5<App<OptionalBox$Mu, T1>, App<OptionalBox$Mu, T2>, App<OptionalBox$Mu, T3>, App<OptionalBox$Mu, T4>, App<OptionalBox$Mu, T5>, App<OptionalBox$Mu, R>>;
    lift6<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function6<T1, T2, T3, T4, T5, T6, R>>): Function6<App<OptionalBox$Mu, T1>, App<OptionalBox$Mu, T2>, App<OptionalBox$Mu, T3>, App<OptionalBox$Mu, T4>, App<OptionalBox$Mu, T5>, App<OptionalBox$Mu, T6>, App<OptionalBox$Mu, R>>;
    lift7<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function7<T1, T2, T3, T4, T5, T6, T7, R>>): Function7<App<OptionalBox$Mu, T1>, App<OptionalBox$Mu, T2>, App<OptionalBox$Mu, T3>, App<OptionalBox$Mu, T4>, App<OptionalBox$Mu, T5>, App<OptionalBox$Mu, T6>, App<OptionalBox$Mu, T7>, App<OptionalBox$Mu, R>>;
    lift8<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>>): Function8<App<OptionalBox$Mu, T1>, App<OptionalBox$Mu, T2>, App<OptionalBox$Mu, T3>, App<OptionalBox$Mu, T4>, App<OptionalBox$Mu, T5>, App<OptionalBox$Mu, T6>, App<OptionalBox$Mu, T7>, App<OptionalBox$Mu, T8>, App<OptionalBox$Mu, R>>;
    lift9<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<OptionalBox$Mu, Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>>): Function9<App<OptionalBox$Mu, T1>, App<OptionalBox$Mu, T2>, App<OptionalBox$Mu, T3>, App<OptionalBox$Mu, T4>, App<OptionalBox$Mu, T5>, App<OptionalBox$Mu, T6>, App<OptionalBox$Mu, T7>, App<OptionalBox$Mu, T8>, App<OptionalBox$Mu, T9>, App<OptionalBox$Mu, R>>;
    map<R extends Object | number | string | boolean, T extends Object | number | string | boolean>(arg0: (param0: T) => R, arg1: App<OptionalBox$Mu, T>): App<OptionalBox$Mu, R>;
    point<A extends Object | number | string | boolean>(arg0: A): App<OptionalBox$Mu, A>;
    traverse<F extends K1, B extends Object | number | string | boolean, A extends Object | number | string | boolean>(arg0: Applicative<F, any>, arg1: (param0: A) => App<F, B>, arg2: App<OptionalBox$Mu, A>): App<F, App<OptionalBox$Mu, B>>;
    name(): "INSTANCE";
}