#!/usr/bin/env python3
"""Drift gate for `augmentations/ScriptModule.augmentation.d.ts`.

The augmentation file is regenerated by `tools/regen/ts-defgen.js`, which
runs *inside LiquidBounce*. We can't run that from check.sh — but we can
verify the committed augmentation matches the current LB source by
cross-referencing two sources of truth:

  • `references/liquidbounce/.../event/EventManager.kt` — `ALL_EVENT_CLASSES`
    array enumerates which Kotlin classes are scriptable events.
  • `references/liquidbounce/.../event/events/*.kt` — `@Tag("name")`
    annotations give the JS-side `eventName` string for each class.

The committed augmentation must:
  1. Import every class name listed in `ALL_EVENT_CLASSES`.
  2. Declare an `on("name", ...)` overload for every `@Tag` name.

Either side going stale (LB adds a new event class without us regening,
or a class is renamed) trips this gate.

Exit codes: 0 = OK, 1 = drift detected.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
LB_SRC = REPO / "references" / "liquidbounce" / "src" / "main" / "kotlin"
EVENT_MANAGER = LB_SRC / "net" / "ccbluex" / "liquidbounce" / "event" / "EventManager.kt"
EVENTS_DIR = LB_SRC / "net" / "ccbluex" / "liquidbounce" / "event" / "events"
AUGMENTATION = (
    REPO
    / "packages"
    / "script-api-types"
    / "augmentations"
    / "ScriptModule.augmentation.d.ts"
)


def read_all_event_classes() -> set[str]:
    """Extract simple class names from the `ALL_EVENT_CLASSES = arrayOf(...)` block."""
    text = EVENT_MANAGER.read_text(encoding="utf-8")
    m = re.search(
        r"ALL_EVENT_CLASSES[^=]*=\s*arrayOf\((.*?)\n\)",
        text,
        flags=re.DOTALL,
    )
    if not m:
        sys.exit(f"could not locate ALL_EVENT_CLASSES in {EVENT_MANAGER}")
    body = m.group(1)
    names = re.findall(r"([A-Za-z_$][A-Za-z0-9_$]*)::class\.java", body)
    return set(names)


def read_tag_names() -> set[str]:
    """Extract @Tag("name") values from every events/*.kt file."""
    names: set[str] = set()
    for path in EVENTS_DIR.rglob("*.kt"):
        for m in re.finditer(r'@Tag\(\s*"([^"]+)"\s*\)', path.read_text(encoding="utf-8")):
            names.add(m.group(1))
    return names


def read_augmentation_imports() -> set[str]:
    """Imports of the form `import type { X } from '../types/...';`."""
    text = AUGMENTATION.read_text(encoding="utf-8")
    return set(re.findall(r"import type \{\s*([A-Za-z_$][A-Za-z0-9_$]*)\s*\}", text))


def read_augmentation_event_names() -> set[str]:
    """Event-name literals in `on("name", handler)` overloads.

    Excludes the lifecycle pair `"enable" | "disable"` which is a synthesised
    overload outside of ALL_EVENT_CLASSES.
    """
    text = AUGMENTATION.read_text(encoding="utf-8")
    names = set(re.findall(r'on\(eventName:\s*"([^"]+)"', text))
    names.discard("enable")
    names.discard("disable")
    return names


def main() -> int:
    classes_kt = read_all_event_classes()
    tags_kt = read_tag_names()
    imports_aug = read_augmentation_imports()
    names_aug = read_augmentation_event_names()

    # Some imported types in the augmentation are NOT event classes — e.g.
    # supporting `$ChatType` enum-like helpers that show up as overload-payload
    # subtypes. We only check that every ALL_EVENT_CLASSES entry IS imported,
    # not the reverse.
    classes_missing = classes_kt - imports_aug
    # Likewise the augmentation can carry pseudo-events that came from
    # generator quirks (none currently, but be permissive).
    names_missing = tags_kt - names_aug
    names_unexpected = names_aug - tags_kt

    drifted = False

    if classes_missing:
        drifted = True
        print(
            "DRIFT: event class(es) in ALL_EVENT_CLASSES but not imported by "
            "ScriptModule.augmentation.d.ts:",
            file=sys.stderr,
        )
        for n in sorted(classes_missing):
            print(f"  - {n}", file=sys.stderr)

    if names_missing:
        drifted = True
        print(
            "DRIFT: @Tag name(s) in LB source but missing from "
            "ScriptModule.augmentation `on(eventName: ...)` overloads:",
            file=sys.stderr,
        )
        for n in sorted(names_missing):
            print(f"  - {n}", file=sys.stderr)

    if names_unexpected:
        drifted = True
        print(
            "DRIFT: `on(eventName: ...)` overload(s) in augmentation with no "
            "matching @Tag in LB source (renamed or removed upstream?):",
            file=sys.stderr,
        )
        for n in sorted(names_unexpected):
            print(f"  - {n}", file=sys.stderr)

    if drifted:
        print(
            "\nThe augmentation appears stale vs the current pinned LB submodule.\n"
            "Regenerate it by running tools/regen/ts-defgen.js inside LB, then\n"
            "copy the output back into typings/augmentations/.",
            file=sys.stderr,
        )
        return 1

    print(
        f"OK: {len(classes_kt)} event classes + {len(tags_kt)} @Tag names "
        f"match the committed augmentation."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
