import type { Object } from '../../../../../../../java/lang/Object.d.ts'
export class ArabicShaping extends Object {
    static DIGITS_AN2EN: number;
    static DIGITS_EN2AN: number;
    static DIGITS_EN2AN_INIT_AL: number;
    static DIGITS_EN2AN_INIT_LR: number;
    static DIGITS_MASK: number;
    static DIGITS_NOOP: number;
    static DIGIT_TYPE_AN: number;
    static DIGIT_TYPE_AN_EXTENDED: number;
    static DIGIT_TYPE_MASK: number;
    static LAMALEF_AUTO: number;
    static LAMALEF_BEGIN: number;
    static LAMALEF_END: number;
    static LAMALEF_MASK: number;
    static LAMALEF_NEAR: number;
    static LAMALEF_RESIZE: number;
    static LENGTH_FIXED_SPACES_AT_BEGINNING: number;
    static LENGTH_FIXED_SPACES_AT_END: number;
    static LENGTH_FIXED_SPACES_NEAR: number;
    static LENGTH_GROW_SHRINK: number;
    static LENGTH_MASK: number;
    static LETTERS_MASK: number;
    static LETTERS_NOOP: number;
    static LETTERS_SHAPE: number;
    static LETTERS_SHAPE_TASHKEEL_ISOLATED: number;
    static LETTERS_UNSHAPE: number;
    static SEEN_MASK: number;
    static SEEN_TWOCELL_NEAR: number;
    static SHAPE_TAIL_NEW_UNICODE: number;
    static SHAPE_TAIL_TYPE_MASK: number;
    static SPACES_RELATIVE_TO_TEXT_BEGIN_END: number;
    static SPACES_RELATIVE_TO_TEXT_MASK: number;
    static TASHKEEL_BEGIN: number;
    static TASHKEEL_END: number;
    static TASHKEEL_MASK: number;
    static TASHKEEL_REPLACE_BY_TATWEEL: number;
    static TASHKEEL_RESIZE: number;
    static TEXT_DIRECTION_LOGICAL: number;
    static TEXT_DIRECTION_MASK: number;
    static TEXT_DIRECTION_VISUAL_LTR: number;
    static TEXT_DIRECTION_VISUAL_RTL: number;
    static YEHHAMZA_MASK: number;
    static YEHHAMZA_TWOCELL_NEAR: number;
    constructor(options: number)
    // private isLogical: boolean;
    // private options: number;
    // private spacesRelativeToTextBeginEnd: boolean;
    // private tailChar: string;
    // private calculateSize(source: string[], sourceStart: number, sourceLength: number): number;
    // private deShapeUnicode(dest: string[], start: number, length: number, destSize: number): number;
    // private deshapeNormalize(dest: string[], start: number, length: number): number;
    equals(rhs: Object | null): boolean;
    // private expandCompositChar(dest: string[], start: number, length: number, lacount: number, shapingMode: number): number;
    // private expandCompositCharAtBegin(dest: string[], start: number, length: number, lacount: number): boolean;
    // private expandCompositCharAtEnd(dest: string[], start: number, length: number, lacount: number): boolean;
    // private expandCompositCharAtNear(dest: string[], start: number, length: number, yehHamzaOption: number, seenTailOption: number, lamAlefOption: number): boolean;
    // private handleGeneratedSpaces(dest: string[], start: number, length: number): number;
    hashCode(): number;
    // private internalShape(source: string[], sourceStart: number, sourceLength: number, dest: string[], destStart: number, destSize: number): number;
    // private normalize(dest: string[], start: number, length: number): number;
    shape(source: string[], start: number, length: number): void;
    shape(source: string[], sourceStart: number, sourceLength: number, dest: string[], destStart: number, destSize: number): number;
    shape(text: string): string;
    // private shapeToArabicDigitsWithContext(dest: string[], start: number, length: number, digitBase: string, lastStrongWasAL: boolean): void;
    // private shapeUnicode(dest: string[], start: number, length: number, destSize: number, tashkeelFlag: number): number;
    toString(): string;
}