import type { RateLimitConfig } from '../../../../com/viaversion/viaversion/api/configuration/RateLimitConfig.d.ts'
import type { ViaVersionConfig } from '../../../../com/viaversion/viaversion/api/configuration/ViaVersionConfig.d.ts'
import type { WorldIdentifiers } from '../../../../com/viaversion/viaversion/api/minecraft/WorldIdentifiers.d.ts'
import type { BlockedProtocolVersions } from '../../../../com/viaversion/viaversion/api/protocol/version/BlockedProtocolVersions.d.ts'
import type { ProtocolVersion } from '../../../../com/viaversion/viaversion/api/protocol/version/ProtocolVersion.d.ts'
import type { JsonElement } from '../../../../com/viaversion/viaversion/libs/gson/JsonElement.d.ts'
import type { Config } from '../../../../com/viaversion/viaversion/util/Config.d.ts'
import type { ConfigSection } from '../../../../com/viaversion/viaversion/util/ConfigSection.d.ts'
import type { File } from '../../../../java/io/File.d.ts'
import type { Logger } from '../../../../java/util/logging/Logger.d.ts'
export class AbstractViaConfig extends Config implements ViaVersionConfig {
    static BUKKIT_ONLY_OPTIONS: string[];
    static VELOCITY_ONLY_OPTIONS: string[];
    constructor(arg0: File, arg1: Logger)
    readonly autoTeam: boolean;
    // private blockedDisconnectMessage: string;
    // private blockedProtocolVersions: BlockedProtocolVersions;
    // private bossbarAntiFlicker: boolean;
    readonly bossbarPatch: boolean;
    // private cache1_17Light: boolean;
    // private cancelBlockSounds: boolean;
    // private cancelSwingInInventory: boolean;
    readonly checkForUpdates: boolean;
    readonly chunkBorderFix: boolean;
    // private disable1_13TabComplete: boolean;
    // private enforceSecureChat: boolean;
    // private fix1_21PlacementRotation: boolean;
    // private flowerStemWhenBlockAbove: boolean;
    readonly forcedUse1_17ResourcePack: boolean;
    // private fullBlockLightFix: boolean;
    // private handleInvalidItemCount: boolean;
    // private healthNaNFix: boolean;
    // private hideScoreboardNumbers: boolean;
    // private hologramOffset: number;
    readonly hologramPatch: boolean;
    // private ignoreLongChannelNames: boolean;
    readonly infestedBlocksFix: boolean;
    // private instantRespawn: boolean;
    readonly leftHandedHandling: boolean;
    // private logBlockedJoins: boolean;
    // private logEntityDataErrors: boolean;
    // private logOtherConversionErrors: boolean;
    // private logTextComponentConversionErrors: boolean;
    // private map1_16WorldNames: WorldIdentifiers;
    // private maxErrorLength: number;
    readonly multiReddustColorFix: boolean;
    readonly noDelayShieldBlocking: boolean;
    readonly packetSizeTrackerConfig: RateLimitConfig;
    readonly packetTrackerConfig: RateLimitConfig;
    readonly pistonAnimationPatch: boolean;
    readonly pistonReplacementId: number;
    readonly preventCollision: boolean;
    readonly reduceBlockStorageMemory: boolean;
    // private reloadDisconnectMessage: string;
    readonly replacePistons: boolean;
    // private resourcePack1_17PromptMessage: JsonElement;
    // private sendPlayerDetails: boolean;
    // private sendServerDetails: boolean;
    readonly sendSupportedVersions: boolean;
    readonly serversideBlockConnections: boolean;
    readonly shieldBlocking: boolean;
    readonly showShieldWhenSwordInHand: boolean;
    readonly simulatePlayerTick: boolean;
    readonly snowCollisionFix: boolean;
    // private tabCompleteDelay: number;
    // private teamColourFix: boolean;
    // private translateOcelotToCat: boolean;
    readonly truncate1_14Books: boolean;
    // private use1_8HitboxMargin: boolean;
    // private useNewEffectIndicator: boolean;
    readonly vineClimbFix: boolean;
    blockedProtocolVersions(): BlockedProtocolVersions;
    cache1_17Light(): boolean;
    cancelBlockSounds(): boolean;
    cancelSwingInInventory(): boolean;
    enforceSecureChat(): boolean;
    fix1_21PlacementRotation(): boolean;
    get1_13TabCompleteDelay(): number;
    get1_16WorldNamesMap(): WorldIdentifiers;
    get1_17ResourcePackPrompt(): JsonElement;
    getBlockConnectionMethod(): string;
    getBlockedDisconnectMsg(): string;
    getHologramYOffset(): number;
    getMaxPPS(): number;
    getMaxPPSKickMessage(): string;
    getMaxWarnings(): number;
    getMaxWarningsKickMessage(): string;
    getPacketSizeTrackerConfig(): RateLimitConfig;
    getPacketTrackerConfig(): RateLimitConfig;
    getPistonReplacementId(): number;
    getReloadDisconnectMsg(): string;
    getTrackingPeriod(): number;
    getUnsupportedOptions(): string[];
    getWarningPPS(): number;
    handleInvalidItemCount(): boolean;
    hideScoreboardNumbers(): boolean;
    is1_12QuickMoveActionFix(): boolean;
    is1_13TeamColourFix(): boolean;
    is1_14HealthNaNFix(): boolean;
    is1_14HitboxFix(): boolean;
    is1_15InstantRespawn(): boolean;
    is1_9HitboxFix(): boolean;
    isArmorToggleFix(): boolean;
    isAutoTeam(): boolean;
    isBossbarAntiflicker(): boolean;
    isBossbarPatch(): boolean;
    isCheckForUpdates(): boolean;
    isChunkBorderFix(): boolean;
    isDisable1_13AutoComplete(): boolean;
    isForcedUse1_17ResourcePack(): boolean;
    isHologramPatch(): boolean;
    isIgnoreLong1_16ChannelNames(): boolean;
    isInfestedBlocksFix(): boolean;
    isItemCache(): boolean;
    isLeftHandedHandling(): boolean;
    isMultiReddustColorFix(): boolean;
    isNMSPlayerTicking(): boolean;
    isNewEffectIndicator(): boolean;
    isNoDelayShieldBlocking(): boolean;
    isNonFullBlockLightFix(): boolean;
    isPistonAnimationPatch(): boolean;
    isPreventCollision(): boolean;
    isReduceBlockStorageMemory(): boolean;
    isReplacePistons(): boolean;
    isSendSupportedVersions(): boolean;
    isServersideBlockConnections(): boolean;
    isShieldBlocking(): boolean;
    isShowNewDeathMessages(): boolean;
    isShowShieldWhenSwordInHand(): boolean;
    isSimulatePlayerTick(): boolean;
    isSnowCollisionFix(): boolean;
    isStemWhenBlockAbove(): boolean;
    isSuppressConversionWarnings(): boolean;
    isSuppressMetadataErrors(): boolean;
    isSuppressTextComponentConversionWarnings(): boolean;
    isTruncate1_14Books(): boolean;
    isVineClimbFix(): boolean;
    // private loadBlockedProtocolVersions(): BlockedProtocolVersions;
    loadFields(): void;
    // private loadRateLimitConfig(arg0: ConfigSection, arg1: string, arg2: number): RateLimitConfig;
    logBlockedJoins(): boolean;
    logEntityDataErrors(): boolean;
    logOtherConversionWarnings(): boolean;
    logTextComponentConversionErrors(): boolean;
    maxErrorLength(): number;
    // private protocolVersion(arg0: string): ProtocolVersion;
    reload(): void;
    sendPlayerDetails(): boolean;
    sendServerDetails(): boolean;
    setCheckForUpdates(arg0: boolean): void;
    shouldRegisterUserConnectionOnJoin(): boolean;
    translateOcelotToCat(): boolean;
    updateConfig(): boolean;
    use1_8HitboxMargin(): boolean;
}