import type { TokenKind } from '../../../../com/oracle/js/parser/TokenKind.d.ts'
import type { TruffleString } from '../../../../com/oracle/truffle/api/strings/TruffleString.d.ts'
import type { Class } from '../../../../java/lang/Class.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { Enum } from '../../../../java/lang/Enum.d.ts'
export class TokenType extends Enum<TokenType> {
    static ACCESSOR: TokenType;
    static ADD: TokenType;
    static AND: TokenType;
    static ARRAY: TokenType;
    static ARROW: TokenType;
    static AS: TokenType;
    static ASSERT: TokenType;
    static ASSIGN: TokenType;
    static ASSIGN_ADD: TokenType;
    static ASSIGN_AND: TokenType;
    static ASSIGN_BIT_AND: TokenType;
    static ASSIGN_BIT_OR: TokenType;
    static ASSIGN_BIT_XOR: TokenType;
    static ASSIGN_DIV: TokenType;
    static ASSIGN_EXP: TokenType;
    static ASSIGN_INIT: TokenType;
    static ASSIGN_MOD: TokenType;
    static ASSIGN_MUL: TokenType;
    static ASSIGN_NULLCOAL: TokenType;
    static ASSIGN_OR: TokenType;
    static ASSIGN_SAR: TokenType;
    static ASSIGN_SHL: TokenType;
    static ASSIGN_SHR: TokenType;
    static ASSIGN_SUB: TokenType;
    static ASYNC: TokenType;
    static AT: TokenType;
    static AWAIT: TokenType;
    static BIGINT: TokenType;
    static BINARY_NUMBER: TokenType;
    static BIT_AND: TokenType;
    static BIT_NOT: TokenType;
    static BIT_OR: TokenType;
    static BIT_XOR: TokenType;
    static BREAK: TokenType;
    static CASE: TokenType;
    static CATCH: TokenType;
    static CLASS: TokenType;
    static COLON: TokenType;
    static COMMALEFT: TokenType;
    static COMMARIGHT: TokenType;
    static COMMENT: TokenType;
    static CONST: TokenType;
    static CONTINUE: TokenType;
    static DEBUGGER: TokenType;
    static DECIMAL: TokenType;
    static DECPOSTFIX: TokenType;
    static DECPREFIX: TokenType;
    static DEFAULT: TokenType;
    static DELETE: TokenType;
    static DIRECTIVE_COMMENT: TokenType;
    static DIV: TokenType;
    static DO: TokenType;
    static ELLIPSIS: TokenType;
    static ELSE: TokenType;
    static ENUM: TokenType;
    static EOF: TokenType;
    static EOL: TokenType;
    static EQ: TokenType;
    static EQ_STRICT: TokenType;
    static ERROR: TokenType;
    static ESCSTRING: TokenType;
    static EXP: TokenType;
    static EXPORT: TokenType;
    static EXTENDS: TokenType;
    static FALSE: TokenType;
    static FINALLY: TokenType;
    static FLOATING: TokenType;
    static FOR: TokenType;
    static FROM: TokenType;
    static FUNCTION: TokenType;
    static GE: TokenType;
    static GET: TokenType;
    static GT: TokenType;
    static HEXADECIMAL: TokenType;
    static IDENT: TokenType;
    static IF: TokenType;
    static IMPLEMENTS: TokenType;
    static IMPORT: TokenType;
    static IN: TokenType;
    static INCPOSTFIX: TokenType;
    static INCPREFIX: TokenType;
    static INSTANCEOF: TokenType;
    static INTERFACE: TokenType;
    static LBRACE: TokenType;
    static LBRACKET: TokenType;
    static LE: TokenType;
    static LET: TokenType;
    static LPAREN: TokenType;
    static LT: TokenType;
    static MOD: TokenType;
    static MUL: TokenType;
    static NAMEDEVALUATION: TokenType;
    static NE: TokenType;
    static NEW: TokenType;
    static NE_STRICT: TokenType;
    static NON_OCTAL_DECIMAL: TokenType;
    static NOT: TokenType;
    static NULL: TokenType;
    static NULLISHCOALESC: TokenType;
    static OBJECT: TokenType;
    static OCTAL: TokenType;
    static OCTAL_LEGACY: TokenType;
    static OF: TokenType;
    static OPTIONAL_CHAIN: TokenType;
    static OR: TokenType;
    static PACKAGE: TokenType;
    static PERIOD: TokenType;
    static PRIVATE: TokenType;
    static PRIVATE_IDENT: TokenType;
    static PROTECTED: TokenType;
    static PUBLIC: TokenType;
    static RBRACE: TokenType;
    static RBRACKET: TokenType;
    static REGEX: TokenType;
    static RETURN: TokenType;
    static RPAREN: TokenType;
    static SAR: TokenType;
    static SEMICOLON: TokenType;
    static SET: TokenType;
    static SHL: TokenType;
    static SHR: TokenType;
    static SPREAD_ARGUMENT: TokenType;
    static SPREAD_ARRAY: TokenType;
    static SPREAD_OBJECT: TokenType;
    static STATIC: TokenType;
    static STRING: TokenType;
    static SUB: TokenType;
    static SUPER: TokenType;
    static SWITCH: TokenType;
    static TEMPLATE: TokenType;
    static TEMPLATE_HEAD: TokenType;
    static TEMPLATE_MIDDLE: TokenType;
    static TEMPLATE_TAIL: TokenType;
    static TERNARY: TokenType;
    static THIS: TokenType;
    static THROW: TokenType;
    static TRUE: TokenType;
    static TRY: TokenType;
    static TYPEOF: TokenType;
    static VAR: TokenType;
    static VOID: TokenType;
    static WHILE: TokenType;
    static WITH: TokenType;
    static YIELD: TokenType;
    static YIELD_STAR: TokenType;
    static valueOf(paramarg0: Class<Object>, paramarg1: string): Object | null;
    static valueOf(paramname: string): TokenType;
    static values(): (Object | null)[];
    private constructor(kind: TokenKind, name: string)
    private constructor(kind: TokenKind, name: string, precedence: number, isLeftAssociative: boolean)
    private constructor(kind: TokenKind, name: string, precedence: number, isLeftAssociative: boolean, ecmaScriptVersion: number)
    // private ecmaScriptVersion: number;
    // private isLeftAssociative: boolean;
    readonly kind: TokenKind;
    readonly nameTS: TruffleString;
    readonly next: TokenType;
    readonly precedence: number;
    getECMAScriptVersion(): number;
    getKind(): TokenKind;
    getLength(): number;
    getName(): string;
    getNameOrType(): string;
    getNameTS(): TruffleString;
    getNext(): TokenType;
    getPrecedence(): number;
    isAssignment(): boolean;
    isContextualKeyword(): boolean;
    isFutureStrict(): boolean;
    isLeftAssociative(): boolean;
    isOperator(in_: boolean): boolean;
    needsParens(other: TokenType, isLeft: boolean): boolean;
    setNext(next: TokenType): void;
    startsWith(c: string): boolean;
    toString(): string;
    name(): "ERROR" | "EOF" | "EOL" | "COMMENT" | "DIRECTIVE_COMMENT" | "NOT" | "NE" | "NE_STRICT" | "MOD" | "ASSIGN_MOD" | "BIT_AND" | "AND" | "ASSIGN_BIT_AND" | "ASSIGN_AND" | "LPAREN" | "RPAREN" | "MUL" | "ASSIGN_MUL" | "EXP" | "ASSIGN_EXP" | "ADD" | "INCPREFIX" | "ASSIGN_ADD" | "COMMARIGHT" | "SUB" | "DECPREFIX" | "ASSIGN_SUB" | "PERIOD" | "DIV" | "ASSIGN_DIV" | "COLON" | "SEMICOLON" | "LT" | "SHL" | "ASSIGN_SHL" | "LE" | "ASSIGN" | "EQ" | "EQ_STRICT" | "ARROW" | "GT" | "GE" | "SAR" | "ASSIGN_SAR" | "SHR" | "ASSIGN_SHR" | "TERNARY" | "LBRACKET" | "RBRACKET" | "BIT_XOR" | "ASSIGN_BIT_XOR" | "LBRACE" | "BIT_OR" | "ASSIGN_BIT_OR" | "OR" | "ASSIGN_OR" | "RBRACE" | "BIT_NOT" | "ELLIPSIS" | "NULLISHCOALESC" | "ASSIGN_NULLCOAL" | "OPTIONAL_CHAIN" | "AT" | "ACCESSOR" | "AS" | "ASSERT" | "ASYNC" | "AWAIT" | "BREAK" | "CASE" | "CATCH" | "CLASS" | "CONST" | "CONTINUE" | "DEBUGGER" | "DEFAULT" | "DELETE" | "DO" | "ELSE" | "ENUM" | "EXPORT" | "EXTENDS" | "FALSE" | "FINALLY" | "FOR" | "FROM" | "FUNCTION" | "GET" | "IF" | "IMPLEMENTS" | "IMPORT" | "IN" | "INSTANCEOF" | "INTERFACE" | "LET" | "NEW" | "NULL" | "OF" | "PACKAGE" | "PRIVATE" | "PROTECTED" | "PUBLIC" | "RETURN" | "SET" | "STATIC" | "SUPER" | "SWITCH" | "THIS" | "THROW" | "TRUE" | "TRY" | "TYPEOF" | "VAR" | "VOID" | "WHILE" | "WITH" | "YIELD" | "DECIMAL" | "NON_OCTAL_DECIMAL" | "HEXADECIMAL" | "OCTAL_LEGACY" | "OCTAL" | "BINARY_NUMBER" | "BIGINT" | "FLOATING" | "STRING" | "ESCSTRING" | "IDENT" | "REGEX" | "OBJECT" | "ARRAY" | "TEMPLATE" | "TEMPLATE_HEAD" | "TEMPLATE_MIDDLE" | "TEMPLATE_TAIL" | "PRIVATE_IDENT" | "COMMALEFT" | "DECPOSTFIX" | "INCPOSTFIX" | "SPREAD_ARGUMENT" | "SPREAD_ARRAY" | "SPREAD_OBJECT" | "YIELD_STAR" | "ASSIGN_INIT" | "NAMEDEVALUATION";
}