import type { EntityType } from '../../../../../../com/viaversion/viaversion/api/minecraft/entities/EntityType.d.ts'
import type { Protocol } from '../../../../../../com/viaversion/viaversion/api/protocol/Protocol.d.ts'
import type { Class } from '../../../../../../java/lang/Class.d.ts'
import type { Object } from '../../../../../../java/lang/Object.d.ts'
import type { Enum } from '../../../../../../java/lang/Enum.d.ts'
export class EntityTypes1_15 extends Enum<EntityTypes1_15> implements EntityType {
    static ABSTRACT_AGEABLE: EntityTypes1_15;
    static ABSTRACT_ANIMAL: EntityTypes1_15;
    static ABSTRACT_ARROW: EntityTypes1_15;
    static ABSTRACT_CHESTED_HORSE: EntityTypes1_15;
    static ABSTRACT_FIREBALL: EntityTypes1_15;
    static ABSTRACT_FISH: EntityTypes1_15;
    static ABSTRACT_GOLEM: EntityTypes1_15;
    static ABSTRACT_HORSE: EntityTypes1_15;
    static ABSTRACT_ILLAGER: EntityTypes1_15;
    static ABSTRACT_MINECART: EntityTypes1_15;
    static ABSTRACT_MINECART_CONTAINER: EntityTypes1_15;
    static ABSTRACT_MONSTER: EntityTypes1_15;
    static ABSTRACT_RAIDER: EntityTypes1_15;
    static ABSTRACT_SCHOOLING_FISH: EntityTypes1_15;
    static ABSTRACT_SKELETON: EntityTypes1_15;
    static ABSTRACT_VILLAGER: EntityTypes1_15;
    static AMBIENT_CREATURE: EntityTypes1_15;
    static AREA_EFFECT_CLOUD: EntityTypes1_15;
    static ARMOR_STAND: EntityTypes1_15;
    static ARROW: EntityTypes1_15;
    static BAT: EntityTypes1_15;
    static BEE: EntityTypes1_15;
    static BLAZE: EntityTypes1_15;
    static BOAT: EntityTypes1_15;
    static CAT: EntityTypes1_15;
    static CAVE_SPIDER: EntityTypes1_15;
    static CHEST_MINECART: EntityTypes1_15;
    static CHICKEN: EntityTypes1_15;
    static COD: EntityTypes1_15;
    static COMMAND_BLOCK_MINECART: EntityTypes1_15;
    static COW: EntityTypes1_15;
    static CREEPER: EntityTypes1_15;
    static DOLPHIN: EntityTypes1_15;
    static DONKEY: EntityTypes1_15;
    static DRAGON_FIREBALL: EntityTypes1_15;
    static DROWNED: EntityTypes1_15;
    static EGG: EntityTypes1_15;
    static ELDER_GUARDIAN: EntityTypes1_15;
    static ENDERMAN: EntityTypes1_15;
    static ENDERMITE: EntityTypes1_15;
    static ENDER_DRAGON: EntityTypes1_15;
    static ENDER_PEARL: EntityTypes1_15;
    static END_CRYSTAL: EntityTypes1_15;
    static ENTITY: EntityTypes1_15;
    static EVOKER: EntityTypes1_15;
    static EVOKER_FANGS: EntityTypes1_15;
    static EXPERIENCE_BOTTLE: EntityTypes1_15;
    static EXPERIENCE_ORB: EntityTypes1_15;
    static EYE_OF_ENDER: EntityTypes1_15;
    static FALLING_BLOCK: EntityTypes1_15;
    static FIREBALL: EntityTypes1_15;
    static FIREWORK_ROCKET: EntityTypes1_15;
    static FISHING_BOBBER: EntityTypes1_15;
    static FLYING_MOB: EntityTypes1_15;
    static FOX: EntityTypes1_15;
    static FURNACE_MINECART: EntityTypes1_15;
    static GHAST: EntityTypes1_15;
    static GIANT: EntityTypes1_15;
    static GUARDIAN: EntityTypes1_15;
    static HANGING_ENTITY: EntityTypes1_15;
    static HOPPER_MINECART: EntityTypes1_15;
    static HORSE: EntityTypes1_15;
    static HUSK: EntityTypes1_15;
    static ILLUSIONER: EntityTypes1_15;
    static IRON_GOLEM: EntityTypes1_15;
    static ITEM: EntityTypes1_15;
    static ITEM_FRAME: EntityTypes1_15;
    static ITEM_PROJECTILE: EntityTypes1_15;
    static LEASH_KNOT: EntityTypes1_15;
    static LIGHTNING_BOLT: EntityTypes1_15;
    static LIVING_ENTITY: EntityTypes1_15;
    static LLAMA: EntityTypes1_15;
    static LLAMA_SPIT: EntityTypes1_15;
    static MAGMA_CUBE: EntityTypes1_15;
    static MINECART: EntityTypes1_15;
    static MOB: EntityTypes1_15;
    static MOOSHROOM: EntityTypes1_15;
    static MULE: EntityTypes1_15;
    static OCELOT: EntityTypes1_15;
    static PAINTING: EntityTypes1_15;
    static PANDA: EntityTypes1_15;
    static PARROT: EntityTypes1_15;
    static PATHFINDER_MOB: EntityTypes1_15;
    static PHANTOM: EntityTypes1_15;
    static PIG: EntityTypes1_15;
    static PILLAGER: EntityTypes1_15;
    static PLAYER: EntityTypes1_15;
    static POLAR_BEAR: EntityTypes1_15;
    static POTION: EntityTypes1_15;
    static PROJECTILE: EntityTypes1_15;
    static PUFFERFISH: EntityTypes1_15;
    static RABBIT: EntityTypes1_15;
    static RAVAGER: EntityTypes1_15;
    static SALMON: EntityTypes1_15;
    static SHEEP: EntityTypes1_15;
    static SHULKER: EntityTypes1_15;
    static SHULKER_BULLET: EntityTypes1_15;
    static SILVERFISH: EntityTypes1_15;
    static SKELETON: EntityTypes1_15;
    static SKELETON_HORSE: EntityTypes1_15;
    static SLIME: EntityTypes1_15;
    static SMALL_FIREBALL: EntityTypes1_15;
    static SNOWBALL: EntityTypes1_15;
    static SNOW_GOLEM: EntityTypes1_15;
    static SPAWNER_MINECART: EntityTypes1_15;
    static SPECTRAL_ARROW: EntityTypes1_15;
    static SPELLCASTER_ILLAGER: EntityTypes1_15;
    static SPIDER: EntityTypes1_15;
    static SQUID: EntityTypes1_15;
    static STRAY: EntityTypes1_15;
    static TAMABLE_ANIMAL: EntityTypes1_15;
    static TNT: EntityTypes1_15;
    static TNT_MINECART: EntityTypes1_15;
    static TRADER_LLAMA: EntityTypes1_15;
    static TRIDENT: EntityTypes1_15;
    static TROPICAL_FISH: EntityTypes1_15;
    static TURTLE: EntityTypes1_15;
    static VEHICLE: EntityTypes1_15;
    static VEX: EntityTypes1_15;
    static VILLAGER: EntityTypes1_15;
    static VINDICATOR: EntityTypes1_15;
    static WANDERING_TRADER: EntityTypes1_15;
    static WATER_ANIMAL: EntityTypes1_15;
    static WITCH: EntityTypes1_15;
    static WITHER: EntityTypes1_15;
    static WITHER_SKELETON: EntityTypes1_15;
    static WITHER_SKULL: EntityTypes1_15;
    static WOLF: EntityTypes1_15;
    static ZOMBIE: EntityTypes1_15;
    static ZOMBIE_HORSE: EntityTypes1_15;
    static ZOMBIE_PIGMAN: EntityTypes1_15;
    static ZOMBIE_VILLAGER: EntityTypes1_15;
    static getTypeFromId(paramarg0: number): EntityType;
    static initialize(paramarg0: Protocol<any, any, any, any>): void;
    static valueOf(paramarg0: Class<Object>, paramarg1: string): Object | null;
    static valueOf(paramarg0: string): EntityTypes1_15;
    static values(): (Object | null)[];
    private constructor(arg2: EntityType)
    private constructor(arg2: EntityType, arg3: string)
    readonly id: number;
    // private identifier: string;
    readonly parent: EntityType;
    getId(): number;
    getParent(): EntityType;
    identifier(): string;
    is(arg0: EntityType): boolean;
    isAbstractType(): boolean;
    isOrHasParent(arg0: EntityType): boolean;
    name(): string;
    name(): "ENTITY" | "AREA_EFFECT_CLOUD" | "END_CRYSTAL" | "EVOKER_FANGS" | "EXPERIENCE_ORB" | "EYE_OF_ENDER" | "FALLING_BLOCK" | "ITEM" | "TNT" | "LIGHTNING_BOLT" | "HANGING_ENTITY" | "LEASH_KNOT" | "PAINTING" | "ITEM_FRAME" | "PROJECTILE" | "ITEM_PROJECTILE" | "SNOWBALL" | "ENDER_PEARL" | "EGG" | "POTION" | "EXPERIENCE_BOTTLE" | "FIREWORK_ROCKET" | "LLAMA_SPIT" | "SHULKER_BULLET" | "FISHING_BOBBER" | "WITHER_SKULL" | "DRAGON_FIREBALL" | "ABSTRACT_ARROW" | "ARROW" | "SPECTRAL_ARROW" | "TRIDENT" | "ABSTRACT_FIREBALL" | "FIREBALL" | "SMALL_FIREBALL" | "VEHICLE" | "BOAT" | "ABSTRACT_MINECART" | "MINECART" | "FURNACE_MINECART" | "COMMAND_BLOCK_MINECART" | "TNT_MINECART" | "SPAWNER_MINECART" | "ABSTRACT_MINECART_CONTAINER" | "CHEST_MINECART" | "HOPPER_MINECART" | "LIVING_ENTITY" | "ARMOR_STAND" | "PLAYER" | "MOB" | "ENDER_DRAGON" | "SLIME" | "MAGMA_CUBE" | "AMBIENT_CREATURE" | "BAT" | "FLYING_MOB" | "GHAST" | "PHANTOM" | "PATHFINDER_MOB" | "ABSTRACT_GOLEM" | "SNOW_GOLEM" | "IRON_GOLEM" | "SHULKER" | "WATER_ANIMAL" | "DOLPHIN" | "SQUID" | "ABSTRACT_FISH" | "PUFFERFISH" | "ABSTRACT_SCHOOLING_FISH" | "COD" | "SALMON" | "TROPICAL_FISH" | "ABSTRACT_AGEABLE" | "ABSTRACT_VILLAGER" | "VILLAGER" | "WANDERING_TRADER" | "ABSTRACT_ANIMAL" | "CHICKEN" | "PANDA" | "PIG" | "POLAR_BEAR" | "RABBIT" | "SHEEP" | "BEE" | "TURTLE" | "FOX" | "OCELOT" | "COW" | "MOOSHROOM" | "TAMABLE_ANIMAL" | "CAT" | "WOLF" | "PARROT" | "ABSTRACT_HORSE" | "HORSE" | "SKELETON_HORSE" | "ZOMBIE_HORSE" | "ABSTRACT_CHESTED_HORSE" | "DONKEY" | "MULE" | "LLAMA" | "TRADER_LLAMA" | "ABSTRACT_MONSTER" | "BLAZE" | "CREEPER" | "ENDERMITE" | "ENDERMAN" | "GIANT" | "SILVERFISH" | "VEX" | "WITHER" | "ABSTRACT_SKELETON" | "SKELETON" | "STRAY" | "WITHER_SKELETON" | "ZOMBIE" | "DROWNED" | "HUSK" | "ZOMBIE_PIGMAN" | "ZOMBIE_VILLAGER" | "GUARDIAN" | "ELDER_GUARDIAN" | "SPIDER" | "CAVE_SPIDER" | "ABSTRACT_RAIDER" | "WITCH" | "RAVAGER" | "ABSTRACT_ILLAGER" | "SPELLCASTER_ILLAGER" | "VINDICATOR" | "PILLAGER" | "EVOKER" | "ILLUSIONER";
}