import type { Object } from '../../../java/lang/Object.d.ts'
import type { Configuration$StateInit } from '../../../org/lwjgl/system/Configuration$StateInit.d.ts'
export class Configuration<T extends Object | number | string | boolean> extends Object {
    static ARRAY_TLC_SIZE: Configuration<number>;
    static ASSIMP_DRACO_LIBRARY_NAME: Configuration<string>;
    static ASSIMP_LIBRARY_NAME: Configuration<string>;
    static BGFX_LIBRARY_NAME: Configuration<string>;
    static BUNDLED_LIBRARY_NAME_MAPPER: Configuration<Object>;
    static BUNDLED_LIBRARY_PATH_MAPPER: Configuration<Object>;
    static DEBUG: Configuration<boolean>;
    static DEBUG_FUNCTIONS: Configuration<boolean>;
    static DEBUG_GENERATOR: Configuration<boolean>;
    static DEBUG_LOADER: Configuration<boolean>;
    static DEBUG_MEMORY_ALLOCATOR: Configuration<boolean>;
    static DEBUG_MEMORY_ALLOCATOR_FAST: Configuration<boolean>;
    static DEBUG_MEMORY_ALLOCATOR_INTERNAL: Configuration<boolean>;
    static DEBUG_STACK: Configuration<boolean>;
    static DEBUG_STREAM: Configuration<Object>;
    static DISABLE_CHECKS: Configuration<boolean>;
    static DISABLE_FUNCTION_CHECKS: Configuration<boolean>;
    static DISABLE_HASH_CHECKS: Configuration<boolean>;
    static EGL_EXPLICIT_INIT: Configuration<boolean>;
    static EGL_EXTENSION_FILTER: Configuration<Object>;
    static EGL_LIBRARY_NAME: Configuration<string>;
    static EMULATE_SYSTEM_LOADLIBRARY: Configuration<boolean>;
    static FFM_DEFAULT_NULLABLE_ANNOTATION: Configuration<Object>;
    static FFM_UPCALL_ARENA: Configuration<string>;
    static FFM_UPCALL_EXCEPTION_CATCH: Configuration<boolean>;
    static FFM_UPCALL_EXCEPTION_HANDLER: Configuration<Object>;
    static FMOD_FSBANK_LIBRARY_NAME: Configuration<string>;
    static FMOD_LIBRARY_NAME: Configuration<string>;
    static FMOD_STUDIO_LIBRARY_NAME: Configuration<string>;
    static FREETYPE_LIBRARY_NAME: Configuration<string>;
    static GLFW_CHECK_THREAD0: Configuration<boolean>;
    static GLFW_LIBRARY_NAME: Configuration<string>;
    static GLSLANG_LIBRARY_NAME: Configuration<string>;
    static GLSLANG_RESOURCE_LIBRARY_NAME: Configuration<string>;
    static HARFBUZZ_LIBRARY_NAME: Configuration<Object>;
    static HWLOC_LIBRARY_NAME: Configuration<string>;
    static JAWT_LIBRARY_NAME: Configuration<string>;
    static JEMALLOC_LIBRARY_NAME: Configuration<string>;
    static JNI_NATIVE_INTERFACE_FUNCTION_COUNT: Configuration<number>;
    static KTX_LIBRARY_NAME: Configuration<string>;
    static LIBRARY_NAME: Configuration<string>;
    static LIBRARY_PATH: Configuration<string>;
    static LLVM_CLANG_LIBRARY_NAME: Configuration<string>;
    static LLVM_LIBRARY_NAME: Configuration<string>;
    static LLVM_LTO_LIBRARY_NAME: Configuration<string>;
    static MEMORY_ALLOCATOR: Configuration<Object>;
    static NFD_LINUX_PORTAL: Configuration<boolean>;
    static ODBC_LIBRARY_NAME: Configuration<string>;
    static OPENAL_EXPLICIT_INIT: Configuration<boolean>;
    static OPENAL_EXTENSION_FILTER: Configuration<Object>;
    static OPENAL_LIBRARY_NAME: Configuration<string>;
    static OPENCL_EXPLICIT_INIT: Configuration<boolean>;
    static OPENCL_EXTENSION_FILTER: Configuration<Object>;
    static OPENCL_LIBRARY_NAME: Configuration<string>;
    static OPENGLES_CONTEXT_API: Configuration<string>;
    static OPENGLES_EXPLICIT_INIT: Configuration<boolean>;
    static OPENGLES_EXTENSION_FILTER: Configuration<Object>;
    static OPENGLES_LIBRARY_NAME: Configuration<string>;
    static OPENGLES_MAXVERSION: Configuration<Object>;
    static OPENGL_CONTEXT_API: Configuration<string>;
    static OPENGL_EXPLICIT_INIT: Configuration<boolean>;
    static OPENGL_EXTENSION_FILTER: Configuration<Object>;
    static OPENGL_LIBRARY_NAME: Configuration<string>;
    static OPENGL_MAXVERSION: Configuration<Object>;
    static OPENGL_OSMESA_LIBRARY_NAME: Configuration<string>;
    static OPENXR_EXPLICIT_INIT: Configuration<boolean>;
    static OPENXR_LIBRARY_NAME: Configuration<string>;
    static OPUS_LIBRARY_NAME: Configuration<string>;
    static RENDERDOC_LIBRARY_NAME: Configuration<string>;
    static SDL_LIBRARY_NAME: Configuration<string>;
    static SHADERC_LIBRARY_NAME: Configuration<string>;
    static SHARED_LIBRARY_EXTRACT_DIRECTORY: Configuration<string>;
    static SHARED_LIBRARY_EXTRACT_FORCE: Configuration<boolean>;
    static SHARED_LIBRARY_EXTRACT_PATH: Configuration<string>;
    static SPIRV_TOOLS_LIBRARY_NAME: Configuration<string>;
    static SPIRV_TOOLS_OPTIMIZER_LIBRARY_NAME: Configuration<string>;
    static SPVC_LIBRARY_NAME: Configuration<string>;
    static STACK_SIZE: Configuration<number>;
    static VULKAN_EXPLICIT_INIT: Configuration<boolean>;
    static VULKAN_LIBRARY_NAME: Configuration<string>;
    static EGL_LIBRARY_NAME_DEFAULTS(): (Object | null)[];
    static OPENGLES_LIBRARY_NAME_DEFAULTS(): (Object | null)[];
    static OPENGL_LIBRARY_NAME_DEFAULTS(): (Object | null)[];
    static OPENGL_OSMESA_LIBRARY_NAME_DEFAULTS(): (Object | null)[];
    constructor(arg0: string, arg1: Configuration$StateInit<T>)
    readonly property: string;
    // private state: T;
    get(): T;
    get(arg0: T): T;
    getProperty(): string;
    set(arg0: T): void;
}