import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { LongBuffer } from '../../../../java/nio/LongBuffer.d.ts'
import type { ShortBuffer } from '../../../../java/nio/ShortBuffer.d.ts'
import type { Consumer } from '../../../../java/util/function/Consumer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../../org/lwjgl/system/Struct$StructValidation.d.ts'
import type { StatxTimestamp } from '../../../../org/lwjgl/system/linux/StatxTimestamp.d.ts'
export class Statx extends Struct<Statx> implements NativeResource {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static SIZEOF: number;
    static STX_ATIME: number;
    static STX_ATTRIBUTES: number;
    static STX_ATTRIBUTES_MASK: number;
    static STX_BLKSIZE: number;
    static STX_BLOCKS: number;
    static STX_BTIME: number;
    static STX_CTIME: number;
    static STX_DEV_MAJOR: number;
    static STX_DEV_MINOR: number;
    static STX_GID: number;
    static STX_INO: number;
    static STX_MASK: number;
    static STX_MNT_ID: number;
    static STX_MODE: number;
    static STX_MTIME: number;
    static STX_NLINK: number;
    static STX_RDEV_MAJOR: number;
    static STX_RDEV_MINOR: number;
    static STX_SIZE: number;
    static STX_UID: number;
    static __SPARE0: number;
    static __SPARE2: number;
    static __SPARE3: number;
    static calloc(): Statx;
    static calloc(paramarg0: MemoryStack): Statx;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): Statx;
    static create(paramarg0: number): Statx;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): Statx;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): Statx;
    static malloc(paramarg0: MemoryStack): Statx;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static n__spare0(paramarg0: number): ShortBuffer;
    static n__spare0(paramarg0: number, paramarg1: number): number;
    static n__spare0(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static n__spare0(paramarg0: number, paramarg1: ShortBuffer): void;
    static n__spare2(paramarg0: number): number;
    static n__spare2(paramarg0: number, paramarg1: number): void;
    static n__spare3(paramarg0: number): LongBuffer;
    static n__spare3(paramarg0: number, paramarg1: number): number;
    static n__spare3(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static n__spare3(paramarg0: number, paramarg1: LongBuffer): void;
    static nstx_atime(paramarg0: number): StatxTimestamp;
    static nstx_atime(paramarg0: number, paramarg1: StatxTimestamp): void;
    static nstx_attributes(paramarg0: number): number;
    static nstx_attributes(paramarg0: number, paramarg1: number): void;
    static nstx_attributes_mask(paramarg0: number): number;
    static nstx_attributes_mask(paramarg0: number, paramarg1: number): void;
    static nstx_blksize(paramarg0: number): number;
    static nstx_blksize(paramarg0: number, paramarg1: number): void;
    static nstx_blocks(paramarg0: number): number;
    static nstx_blocks(paramarg0: number, paramarg1: number): void;
    static nstx_btime(paramarg0: number): StatxTimestamp;
    static nstx_btime(paramarg0: number, paramarg1: StatxTimestamp): void;
    static nstx_ctime(paramarg0: number): StatxTimestamp;
    static nstx_ctime(paramarg0: number, paramarg1: StatxTimestamp): void;
    static nstx_dev_major(paramarg0: number): number;
    static nstx_dev_major(paramarg0: number, paramarg1: number): void;
    static nstx_dev_minor(paramarg0: number): number;
    static nstx_dev_minor(paramarg0: number, paramarg1: number): void;
    static nstx_gid(paramarg0: number): number;
    static nstx_gid(paramarg0: number, paramarg1: number): void;
    static nstx_ino(paramarg0: number): number;
    static nstx_ino(paramarg0: number, paramarg1: number): void;
    static nstx_mask(paramarg0: number): number;
    static nstx_mask(paramarg0: number, paramarg1: number): void;
    static nstx_mnt_id(paramarg0: number): number;
    static nstx_mnt_id(paramarg0: number, paramarg1: number): void;
    static nstx_mode(paramarg0: number): number;
    static nstx_mode(paramarg0: number, paramarg1: number): void;
    static nstx_mtime(paramarg0: number): StatxTimestamp;
    static nstx_mtime(paramarg0: number, paramarg1: StatxTimestamp): void;
    static nstx_nlink(paramarg0: number): number;
    static nstx_nlink(paramarg0: number, paramarg1: number): void;
    static nstx_rdev_major(paramarg0: number): number;
    static nstx_rdev_major(paramarg0: number, paramarg1: number): void;
    static nstx_rdev_minor(paramarg0: number): number;
    static nstx_rdev_minor(paramarg0: number, paramarg1: number): void;
    static nstx_size(paramarg0: number): number;
    static nstx_size(paramarg0: number, paramarg1: number): void;
    static nstx_uid(paramarg0: number): number;
    static nstx_uid(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    close(): void;
    create(arg0: number, arg1: ByteBuffer): Statx;
    set(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: StatxTimestamp, arg12: StatxTimestamp, arg13: StatxTimestamp, arg14: StatxTimestamp, arg15: number, arg16: number, arg17: number, arg18: number, arg19: number): Statx;
    set(arg0: Statx): Statx;
    sizeof(): number;
    stx_atime(): StatxTimestamp;
    stx_atime(arg0: (param0: StatxTimestamp) => void): Statx;
    stx_atime(arg0: StatxTimestamp): Statx;
    stx_attributes(): number;
    stx_attributes(arg0: number): Statx;
    stx_attributes_mask(): number;
    stx_attributes_mask(arg0: number): Statx;
    stx_blksize(): number;
    stx_blksize(arg0: number): Statx;
    stx_blocks(): number;
    stx_blocks(arg0: number): Statx;
    stx_btime(): StatxTimestamp;
    stx_btime(arg0: (param0: StatxTimestamp) => void): Statx;
    stx_btime(arg0: StatxTimestamp): Statx;
    stx_ctime(): StatxTimestamp;
    stx_ctime(arg0: (param0: StatxTimestamp) => void): Statx;
    stx_ctime(arg0: StatxTimestamp): Statx;
    stx_dev_major(): number;
    stx_dev_major(arg0: number): Statx;
    stx_dev_minor(): number;
    stx_dev_minor(arg0: number): Statx;
    stx_gid(): number;
    stx_gid(arg0: number): Statx;
    stx_ino(): number;
    stx_ino(arg0: number): Statx;
    stx_mask(): number;
    stx_mask(arg0: number): Statx;
    stx_mnt_id(): number;
    stx_mnt_id(arg0: number): Statx;
    stx_mode(): number;
    stx_mode(arg0: number): Statx;
    stx_mtime(): StatxTimestamp;
    stx_mtime(arg0: (param0: StatxTimestamp) => void): Statx;
    stx_mtime(arg0: StatxTimestamp): Statx;
    stx_nlink(): number;
    stx_nlink(arg0: number): Statx;
    stx_rdev_major(): number;
    stx_rdev_major(arg0: number): Statx;
    stx_rdev_minor(): number;
    stx_rdev_minor(arg0: number): Statx;
    stx_size(): number;
    stx_size(arg0: number): Statx;
    stx_uid(): number;
    stx_uid(arg0: number): Statx;
}