import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { IntBuffer } from '../../../../java/nio/IntBuffer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../../java/lang/CharSequence.d.ts'
import type { CLongBuffer } from '../../../../org/lwjgl/CLongBuffer.d.ts'
import type { PointerBuffer } from '../../../../org/lwjgl/PointerBuffer.d.ts'
import type { SharedLibrary } from '../../../../org/lwjgl/system/SharedLibrary.d.ts'
import type { Visual } from '../../../../org/lwjgl/system/linux/Visual.d.ts'
import type { XEvent } from '../../../../org/lwjgl/system/linux/XEvent.d.ts'
import type { XSetWindowAttributes } from '../../../../org/lwjgl/system/linux/XSetWindowAttributes.d.ts'
export class X11 extends Object {
    static Above: number;
    static AllTemporary: number;
    static AllocAll: number;
    static AllocNone: number;
    static AllowExposures: number;
    static AlreadyGrabbed: number;
    static AnyButton: number;
    static AnyKey: number;
    static AnyModifier: number;
    static AnyPropertyType: number;
    static ArcChord: number;
    static ArcPieSlice: number;
    static AsyncBoth: number;
    static AsyncKeyboard: number;
    static AsyncPointer: number;
    static BadAccess: number;
    static BadAlloc: number;
    static BadAtom: number;
    static BadColor: number;
    static BadCursor: number;
    static BadDrawable: number;
    static BadFont: number;
    static BadGC: number;
    static BadIDChoice: number;
    static BadImplementation: number;
    static BadLength: number;
    static BadMatch: number;
    static BadName: number;
    static BadPixmap: number;
    static BadRequest: number;
    static BadValue: number;
    static BadWindow: number;
    static Below: number;
    static BottomIf: number;
    static Button1: number;
    static Button1Mask: number;
    static Button1MotionMask: number;
    static Button2: number;
    static Button2Mask: number;
    static Button2MotionMask: number;
    static Button3: number;
    static Button3Mask: number;
    static Button3MotionMask: number;
    static Button4: number;
    static Button4Mask: number;
    static Button4MotionMask: number;
    static Button5: number;
    static Button5Mask: number;
    static Button5MotionMask: number;
    static ButtonMotionMask: number;
    static ButtonPress: number;
    static ButtonPressMask: number;
    static ButtonRelease: number;
    static ButtonReleaseMask: number;
    static CWBackPixel: number;
    static CWBackPixmap: number;
    static CWBackingPixel: number;
    static CWBackingPlanes: number;
    static CWBackingStore: number;
    static CWBitGravity: number;
    static CWBorderPixel: number;
    static CWBorderPixmap: number;
    static CWColormap: number;
    static CWCursor: number;
    static CWDontPropagate: number;
    static CWEventMask: number;
    static CWOverrideRedirect: number;
    static CWSaveUnder: number;
    static CWWinGravity: number;
    static CapButt: number;
    static CapNotLast: number;
    static CapProjecting: number;
    static CapRound: number;
    static CirculateNotify: number;
    static CirculateRequest: number;
    static ClientMessage: number;
    static ClipByChildren: number;
    static ColormapChangeMask: number;
    static ColormapInstalled: number;
    static ColormapNotify: number;
    static ColormapUninstalled: number;
    static Complex: number;
    static ConfigureNotify: number;
    static ConfigureRequest: number;
    static ControlMapIndex: number;
    static ControlMask: number;
    static Convex: number;
    static CoordModeOrigin: number;
    static CoordModePrevious: number;
    static CopyFromParent: number;
    static CreateNotify: number;
    static CurrentTime: number;
    static DefaultBlanking: number;
    static DefaultExposures: number;
    static DestroyNotify: number;
    static DisableScreenInterval: number;
    static DisableScreenSaver: number;
    static DontAllowExposures: number;
    static DontPreferBlanking: number;
    static EnterNotify: number;
    static EnterWindowMask: number;
    static EvenOddRule: number;
    static Expose: number;
    static ExposureMask: number;
    static False: number;
    static FillOpaqueStippled: number;
    static FillSolid: number;
    static FillStippled: number;
    static FillTiled: number;
    static FirstExtensionError: number;
    static FocusChangeMask: number;
    static FocusIn: number;
    static FocusOut: number;
    static GCArcMode: number;
    static GCBackground: number;
    static GCCapStyle: number;
    static GCClipMask: number;
    static GCClipXOrigin: number;
    static GCClipYOrigin: number;
    static GCDashList: number;
    static GCDashOffset: number;
    static GCFillRule: number;
    static GCFillStyle: number;
    static GCFont: number;
    static GCForeground: number;
    static GCFunction: number;
    static GCGraphicsExposures: number;
    static GCJoinStyle: number;
    static GCLastBit: number;
    static GCLineStyle: number;
    static GCLineWidth: number;
    static GCPlaneMask: number;
    static GCStipple: number;
    static GCSubwindowMode: number;
    static GCTile: number;
    static GCTileStipXOrigin: number;
    static GCTileStipYOrigin: number;
    static GXand: number;
    static GXandInverted: number;
    static GXandReverse: number;
    static GXclear: number;
    static GXcopy: number;
    static GXcopyInverted: number;
    static GXequiv: number;
    static GXinvert: number;
    static GXnand: number;
    static GXnoop: number;
    static GXnor: number;
    static GXor: number;
    static GXorInverted: number;
    static GXorReverse: number;
    static GXset: number;
    static GXxor: number;
    static GenericEvent: number;
    static GrabFrozen: number;
    static GrabInvalidTime: number;
    static GrabModeAsync: number;
    static GrabModeSync: number;
    static GrabNotViewable: number;
    static GrabSuccess: number;
    static GraphicsExpose: number;
    static GravityNotify: number;
    static IncludeInferiors: number;
    static InputFocus: number;
    static InputOnly: number;
    static InputOutput: number;
    static JoinBevel: number;
    static JoinMiter: number;
    static JoinRound: number;
    static KeyPress: number;
    static KeyPressMask: number;
    static KeyRelease: number;
    static KeyReleaseMask: number;
    static KeymapNotify: number;
    static KeymapStateMask: number;
    static LASTEvent: number;
    static LastExtensionError: number;
    static LeaveNotify: number;
    static LeaveWindowMask: number;
    static LineDoubleDash: number;
    static LineOnOffDash: number;
    static LineSolid: number;
    static LockMapIndex: number;
    static LockMask: number;
    static MapNotify: number;
    static MapRequest: number;
    static MappingKeyboard: number;
    static MappingModifier: number;
    static MappingNotify: number;
    static MappingPointer: number;
    static Mod1MapIndex: number;
    static Mod1Mask: number;
    static Mod2MapIndex: number;
    static Mod2Mask: number;
    static Mod3MapIndex: number;
    static Mod3Mask: number;
    static Mod4MapIndex: number;
    static Mod4Mask: number;
    static Mod5MapIndex: number;
    static Mod5Mask: number;
    static MotionNotify: number;
    static NoEventMask: number;
    static NoExpose: number;
    static NoSymbol: number;
    static Nonconvex: number;
    static None: number;
    static NotifyAncestor: number;
    static NotifyDetailNone: number;
    static NotifyGrab: number;
    static NotifyHint: number;
    static NotifyInferior: number;
    static NotifyNonlinear: number;
    static NotifyNonlinearVirtual: number;
    static NotifyNormal: number;
    static NotifyPointer: number;
    static NotifyPointerRoot: number;
    static NotifyUngrab: number;
    static NotifyVirtual: number;
    static NotifyWhileGrabbed: number;
    static Opposite: number;
    static OwnerGrabButtonMask: number;
    static ParentRelative: number;
    static PlaceOnBottom: number;
    static PlaceOnTop: number;
    static PointerMotionHintMask: number;
    static PointerMotionMask: number;
    static PointerRoot: number;
    static PointerWindow: number;
    static PreferBlanking: number;
    static PropModeAppend: number;
    static PropModePrepend: number;
    static PropModeReplace: number;
    static PropertyChangeMask: number;
    static PropertyDelete: number;
    static PropertyNewValue: number;
    static PropertyNotify: number;
    static ReparentNotify: number;
    static ReplayKeyboard: number;
    static ReplayPointer: number;
    static ResizeRedirectMask: number;
    static ResizeRequest: number;
    static RevertToNone: number;
    static RevertToParent: number;
    static RevertToPointerRoot: number;
    static ScreenSaverActive: number;
    static ScreenSaverReset: number;
    static SelectionClear: number;
    static SelectionNotify: number;
    static SelectionRequest: number;
    static ShiftMapIndex: number;
    static ShiftMask: number;
    static StructureNotifyMask: number;
    static SubstructureNotifyMask: number;
    static SubstructureRedirectMask: number;
    static Success: number;
    static SyncBoth: number;
    static SyncKeyboard: number;
    static SyncPointer: number;
    static TopIf: number;
    static True: number;
    static UnmapNotify: number;
    static Unsorted: number;
    static VisibilityChangeMask: number;
    static VisibilityFullyObscured: number;
    static VisibilityNotify: number;
    static VisibilityPartiallyObscured: number;
    static VisibilityUnobscured: number;
    static WindingRule: number;
    static YSorted: number;
    static YXBanded: number;
    static YXSorted: number;
    static XCloseDisplay(paramarg0: number): void;
    static XCreateColormap(paramarg0: number, paramarg1: number, paramarg2: Visual, paramarg3: number): number;
    static XCreateWindow(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: Visual, paramarg10: number, paramarg11: XSetWindowAttributes): number;
    static XDefaultScreen(paramarg0: number): number;
    static XDestroyWindow(paramarg0: number, paramarg1: number): number;
    static XDisplayMotionBufferSize(paramarg0: number): number;
    static XFree(paramarg0: ByteBuffer): number;
    static XFree(paramarg0: PointerBuffer): number;
    static XFreeColormap(paramarg0: number, paramarg1: number): number;
    static XGetMotionEvents(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): (Object | null)[];
    static XOpenDisplay(paramarg0: CharSequence): number;
    static XOpenDisplay(paramarg0: ByteBuffer): number;
    static XRootWindow(paramarg0: number, paramarg1: number): number;
    static XSendEvent(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number, paramarg4: XEvent): number;
    static XTranslateCoordinates(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number[], paramarg6: number[], paramarg7: CLongBuffer): boolean;
    static XTranslateCoordinates(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: IntBuffer, paramarg6: IntBuffer, paramarg7: CLongBuffer): boolean;
    static getLibrary(): SharedLibrary;
    static nXCreateColormap(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nXCreateWindow(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number): number;
    static nXFree(paramarg0: number): number;
    static nXGetMotionEvents(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nXOpenDisplay(paramarg0: number): number;
    static nXSendEvent(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nXTranslateCoordinates(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): number;
    constructor()
}