import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class XCrossingEvent extends Struct<XCrossingEvent> implements NativeResource {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static DETAIL: number;
    static DISPLAY: number;
    static FOCUS: number;
    static MODE: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static ROOT: number;
    static SAME_SCREEN: number;
    static SEND_EVENT: number;
    static SERIAL: number;
    static SIZEOF: number;
    static STATE: number;
    static SUBWINDOW: number;
    static TIME: number;
    static TYPE: number;
    static WINDOW: number;
    static X: number;
    static X_ROOT: number;
    static Y: number;
    static Y_ROOT: number;
    static calloc(): XCrossingEvent;
    static calloc(paramarg0: MemoryStack): XCrossingEvent;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): XCrossingEvent;
    static create(paramarg0: number): XCrossingEvent;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): XCrossingEvent;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): XCrossingEvent;
    static malloc(paramarg0: MemoryStack): XCrossingEvent;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static ndetail(paramarg0: number): number;
    static ndetail(paramarg0: number, paramarg1: number): void;
    static ndisplay(paramarg0: number): number;
    static ndisplay(paramarg0: number, paramarg1: number): void;
    static nfocus(paramarg0: number): number;
    static nfocus(paramarg0: number, paramarg1: number): void;
    static nmode(paramarg0: number): number;
    static nmode(paramarg0: number, paramarg1: number): void;
    static nroot(paramarg0: number): number;
    static nroot(paramarg0: number, paramarg1: number): void;
    static nsame_screen(paramarg0: number): number;
    static nsame_screen(paramarg0: number, paramarg1: number): void;
    static nsend_event(paramarg0: number): number;
    static nsend_event(paramarg0: number, paramarg1: number): void;
    static nserial(paramarg0: number): number;
    static nserial(paramarg0: number, paramarg1: number): void;
    static nstate(paramarg0: number): number;
    static nstate(paramarg0: number, paramarg1: number): void;
    static nsubwindow(paramarg0: number): number;
    static nsubwindow(paramarg0: number, paramarg1: number): void;
    static ntime(paramarg0: number): number;
    static ntime(paramarg0: number, paramarg1: number): void;
    static ntype(paramarg0: number): number;
    static ntype(paramarg0: number, paramarg1: number): void;
    static nwindow(paramarg0: number): number;
    static nwindow(paramarg0: number, paramarg1: number): void;
    static nx(paramarg0: number): number;
    static nx(paramarg0: number, paramarg1: number): void;
    static nx_root(paramarg0: number): number;
    static nx_root(paramarg0: number, paramarg1: number): void;
    static ny(paramarg0: number): number;
    static ny(paramarg0: number, paramarg1: number): void;
    static ny_root(paramarg0: number): number;
    static ny_root(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    close(): void;
    create(arg0: number, arg1: ByteBuffer): XCrossingEvent;
    detail(): number;
    detail(arg0: number): XCrossingEvent;
    display(): number;
    display(arg0: number): XCrossingEvent;
    focus(): number;
    focus(arg0: number): XCrossingEvent;
    mode(): number;
    mode(arg0: number): XCrossingEvent;
    root(): number;
    root(arg0: number): XCrossingEvent;
    same_screen(): number;
    same_screen(arg0: number): XCrossingEvent;
    send_event(): boolean;
    send_event(arg0: boolean): XCrossingEvent;
    serial(): number;
    serial(arg0: number): XCrossingEvent;
    set(arg0: number, arg1: number, arg2: boolean, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number, arg15: number, arg16: number): XCrossingEvent;
    set(arg0: XCrossingEvent): XCrossingEvent;
    sizeof(): number;
    state(): number;
    state(arg0: number): XCrossingEvent;
    subwindow(): number;
    subwindow(arg0: number): XCrossingEvent;
    time(): number;
    time(arg0: number): XCrossingEvent;
    type(): number;
    type(arg0: number): XCrossingEvent;
    window(): number;
    window(arg0: number): XCrossingEvent;
    x(): number;
    x(arg0: number): XCrossingEvent;
    x_root(): number;
    x_root(arg0: number): XCrossingEvent;
    y(): number;
    y(arg0: number): XCrossingEvent;
    y_root(): number;
    y_root(arg0: number): XCrossingEvent;
}