import type { App } from '../../../../../../../com/mojang/datafixers/kinds/App.d.ts'
import type { Applicative } from '../../../../../../../com/mojang/datafixers/kinds/Applicative.d.ts'
import type { Applicative$Mu } from '../../../../../../../com/mojang/datafixers/kinds/Applicative$Mu.d.ts'
import type { Const$Mu } from '../../../../../../../com/mojang/datafixers/kinds/Const$Mu.d.ts'
import type { IdF$Mu } from '../../../../../../../com/mojang/datafixers/kinds/IdF$Mu.d.ts'
import type { K1 } from '../../../../../../../com/mojang/datafixers/kinds/K1.d.ts'
import type { OptionalBox$Mu } from '../../../../../../../com/mojang/datafixers/kinds/OptionalBox$Mu.d.ts'
import type { Function10 } from '../../../../../../../com/mojang/datafixers/util/Function10.d.ts'
import type { Function11 } from '../../../../../../../com/mojang/datafixers/util/Function11.d.ts'
import type { Function12 } from '../../../../../../../com/mojang/datafixers/util/Function12.d.ts'
import type { Function13 } from '../../../../../../../com/mojang/datafixers/util/Function13.d.ts'
import type { Function14 } from '../../../../../../../com/mojang/datafixers/util/Function14.d.ts'
import type { Function15 } from '../../../../../../../com/mojang/datafixers/util/Function15.d.ts'
import type { Function16 } from '../../../../../../../com/mojang/datafixers/util/Function16.d.ts'
import type { Function3 } from '../../../../../../../com/mojang/datafixers/util/Function3.d.ts'
import type { Function4 } from '../../../../../../../com/mojang/datafixers/util/Function4.d.ts'
import type { Function5 } from '../../../../../../../com/mojang/datafixers/util/Function5.d.ts'
import type { Function6 } from '../../../../../../../com/mojang/datafixers/util/Function6.d.ts'
import type { Function7 } from '../../../../../../../com/mojang/datafixers/util/Function7.d.ts'
import type { Function8 } from '../../../../../../../com/mojang/datafixers/util/Function8.d.ts'
import type { Function9 } from '../../../../../../../com/mojang/datafixers/util/Function9.d.ts'
import type { Unit } from '../../../../../../../com/mojang/datafixers/util/Unit.d.ts'
import type { Optional } from '../../../../../../../java/util/Optional.d.ts'
import type { BiFunction } from '../../../../../../../java/util/function/BiFunction.d.ts'
import type { Function } from '../../../../../../../java/util/function/Function.d.ts'
import type { Supplier } from '../../../../../../../java/util/function/Supplier.d.ts'
import type { Object } from '../../../../../../../java/lang/Object.d.ts'
import type { LivingEntity } from '../../../../../../../net/minecraft/world/entity/LivingEntity.d.ts'
import type { BehaviorBuilder } from '../../../../../../../net/minecraft/world/entity/ai/behavior/declarative/BehaviorBuilder.d.ts'
import type { BehaviorBuilder$Instance$Mu } from '../../../../../../../net/minecraft/world/entity/ai/behavior/declarative/BehaviorBuilder$Instance$Mu.d.ts'
import type { BehaviorBuilder$Mu } from '../../../../../../../net/minecraft/world/entity/ai/behavior/declarative/BehaviorBuilder$Mu.d.ts'
import type { MemoryAccessor } from '../../../../../../../net/minecraft/world/entity/ai/behavior/declarative/MemoryAccessor.d.ts'
import type { Trigger } from '../../../../../../../net/minecraft/world/entity/ai/behavior/declarative/Trigger.d.ts'
import type { MemoryModuleType } from '../../../../../../../net/minecraft/world/entity/ai/memory/MemoryModuleType.d.ts'
export class BehaviorBuilder$Instance<E extends LivingEntity> extends Object implements Applicative<BehaviorBuilder$Mu<E>, BehaviorBuilder$Instance$Mu<E>> {
    static unbox(paramarg0: App<Applicative$Mu, K1>): Applicative<K1, Applicative$Mu>;
    constructor()
    absent<Value extends Object | number | string | boolean>(memory: MemoryModuleType<Value>): BehaviorBuilder<E, MemoryAccessor<Const$Mu<Unit>, Value>>;
    ap<R extends Object | number | string | boolean, A extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, (param0: A) => R>, arg1: App<BehaviorBuilder$Mu<E>, A>): App<BehaviorBuilder$Mu<E>, R>;
    ap<R extends Object | number | string | boolean, A extends Object | number | string | boolean>(arg0: (param0: A) => R, arg1: App<BehaviorBuilder$Mu<E>, A>): App<BehaviorBuilder$Mu<E>, R>;
    ap10<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>, arg7: App<BehaviorBuilder$Mu<E>, T7>, arg8: App<BehaviorBuilder$Mu<E>, T8>, arg9: App<BehaviorBuilder$Mu<E>, T9>, arg10: App<BehaviorBuilder$Mu<E>, T10>): App<BehaviorBuilder$Mu<E>, R>;
    ap11<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>, arg7: App<BehaviorBuilder$Mu<E>, T7>, arg8: App<BehaviorBuilder$Mu<E>, T8>, arg9: App<BehaviorBuilder$Mu<E>, T9>, arg10: App<BehaviorBuilder$Mu<E>, T10>, arg11: App<BehaviorBuilder$Mu<E>, T11>): App<BehaviorBuilder$Mu<E>, R>;
    ap12<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>, arg7: App<BehaviorBuilder$Mu<E>, T7>, arg8: App<BehaviorBuilder$Mu<E>, T8>, arg9: App<BehaviorBuilder$Mu<E>, T9>, arg10: App<BehaviorBuilder$Mu<E>, T10>, arg11: App<BehaviorBuilder$Mu<E>, T11>, arg12: App<BehaviorBuilder$Mu<E>, T12>): App<BehaviorBuilder$Mu<E>, R>;
    ap13<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>, arg7: App<BehaviorBuilder$Mu<E>, T7>, arg8: App<BehaviorBuilder$Mu<E>, T8>, arg9: App<BehaviorBuilder$Mu<E>, T9>, arg10: App<BehaviorBuilder$Mu<E>, T10>, arg11: App<BehaviorBuilder$Mu<E>, T11>, arg12: App<BehaviorBuilder$Mu<E>, T12>, arg13: App<BehaviorBuilder$Mu<E>, T13>): App<BehaviorBuilder$Mu<E>, R>;
    ap14<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>, arg7: App<BehaviorBuilder$Mu<E>, T7>, arg8: App<BehaviorBuilder$Mu<E>, T8>, arg9: App<BehaviorBuilder$Mu<E>, T9>, arg10: App<BehaviorBuilder$Mu<E>, T10>, arg11: App<BehaviorBuilder$Mu<E>, T11>, arg12: App<BehaviorBuilder$Mu<E>, T12>, arg13: App<BehaviorBuilder$Mu<E>, T13>, arg14: App<BehaviorBuilder$Mu<E>, T14>): App<BehaviorBuilder$Mu<E>, R>;
    ap15<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean, T15 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>, arg7: App<BehaviorBuilder$Mu<E>, T7>, arg8: App<BehaviorBuilder$Mu<E>, T8>, arg9: App<BehaviorBuilder$Mu<E>, T9>, arg10: App<BehaviorBuilder$Mu<E>, T10>, arg11: App<BehaviorBuilder$Mu<E>, T11>, arg12: App<BehaviorBuilder$Mu<E>, T12>, arg13: App<BehaviorBuilder$Mu<E>, T13>, arg14: App<BehaviorBuilder$Mu<E>, T14>, arg15: App<BehaviorBuilder$Mu<E>, T15>): App<BehaviorBuilder$Mu<E>, R>;
    ap16<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, T10 extends Object | number | string | boolean, T11 extends Object | number | string | boolean, T12 extends Object | number | string | boolean, T13 extends Object | number | string | boolean, T14 extends Object | number | string | boolean, T15 extends Object | number | string | boolean, T16 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>, arg7: App<BehaviorBuilder$Mu<E>, T7>, arg8: App<BehaviorBuilder$Mu<E>, T8>, arg9: App<BehaviorBuilder$Mu<E>, T9>, arg10: App<BehaviorBuilder$Mu<E>, T10>, arg11: App<BehaviorBuilder$Mu<E>, T11>, arg12: App<BehaviorBuilder$Mu<E>, T12>, arg13: App<BehaviorBuilder$Mu<E>, T13>, arg14: App<BehaviorBuilder$Mu<E>, T14>, arg15: App<BehaviorBuilder$Mu<E>, T15>, arg16: App<BehaviorBuilder$Mu<E>, T16>): App<BehaviorBuilder$Mu<E>, R>;
    ap2<R extends Object | number | string | boolean, A extends Object | number | string | boolean, B extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, (param0: A, param1: B) => R>, arg1: App<BehaviorBuilder$Mu<E>, A>, arg2: App<BehaviorBuilder$Mu<E>, B>): App<BehaviorBuilder$Mu<E>, R>;
    ap2<R extends Object | number | string | boolean, A extends Object | number | string | boolean, B extends Object | number | string | boolean>(func: App<BehaviorBuilder$Mu<E>, (param0: A, param1: B) => R>, a: App<BehaviorBuilder$Mu<E>, A>, b: App<BehaviorBuilder$Mu<E>, B>): BehaviorBuilder<E, R>;
    ap3<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function3<T1, T2, T3, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>): App<BehaviorBuilder$Mu<E>, R>;
    ap3<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean>(func: App<BehaviorBuilder$Mu<E>, Function3<T1, T2, T3, R>>, t1: App<BehaviorBuilder$Mu<E>, T1>, t2: App<BehaviorBuilder$Mu<E>, T2>, t3: App<BehaviorBuilder$Mu<E>, T3>): BehaviorBuilder<E, R>;
    ap4<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function4<T1, T2, T3, T4, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>): App<BehaviorBuilder$Mu<E>, R>;
    ap4<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean>(func: App<BehaviorBuilder$Mu<E>, Function4<T1, T2, T3, T4, R>>, t1: App<BehaviorBuilder$Mu<E>, T1>, t2: App<BehaviorBuilder$Mu<E>, T2>, t3: App<BehaviorBuilder$Mu<E>, T3>, t4: App<BehaviorBuilder$Mu<E>, T4>): BehaviorBuilder<E, R>;
    ap5<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function5<T1, T2, T3, T4, T5, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>): App<BehaviorBuilder$Mu<E>, R>;
    ap6<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function6<T1, T2, T3, T4, T5, T6, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>): App<BehaviorBuilder$Mu<E>, R>;
    ap7<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function7<T1, T2, T3, T4, T5, T6, T7, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>, arg7: App<BehaviorBuilder$Mu<E>, T7>): App<BehaviorBuilder$Mu<E>, R>;
    ap8<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>, arg7: App<BehaviorBuilder$Mu<E>, T7>, arg8: App<BehaviorBuilder$Mu<E>, T8>): App<BehaviorBuilder$Mu<E>, R>;
    ap9<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>, arg7: App<BehaviorBuilder$Mu<E>, T7>, arg8: App<BehaviorBuilder$Mu<E>, T8>, arg9: App<BehaviorBuilder$Mu<E>, T9>): App<BehaviorBuilder$Mu<E>, R>;
    apply2<R extends Object | number | string | boolean, A extends Object | number | string | boolean, B extends Object | number | string | boolean>(arg0: (param0: A, param1: B) => R, arg1: App<BehaviorBuilder$Mu<E>, A>, arg2: App<BehaviorBuilder$Mu<E>, B>): App<BehaviorBuilder$Mu<E>, R>;
    apply3<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean>(arg0: Function3<T1, T2, T3, R>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>): App<BehaviorBuilder$Mu<E>, R>;
    apply4<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean>(arg0: Function4<T1, T2, T3, T4, R>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>): App<BehaviorBuilder$Mu<E>, R>;
    apply5<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean>(arg0: Function5<T1, T2, T3, T4, T5, R>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>): App<BehaviorBuilder$Mu<E>, R>;
    apply6<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean>(arg0: Function6<T1, T2, T3, T4, T5, T6, R>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>): App<BehaviorBuilder$Mu<E>, R>;
    apply7<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean>(arg0: Function7<T1, T2, T3, T4, T5, T6, T7, R>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>, arg7: App<BehaviorBuilder$Mu<E>, T7>): App<BehaviorBuilder$Mu<E>, R>;
    apply8<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean>(arg0: Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>, arg7: App<BehaviorBuilder$Mu<E>, T7>, arg8: App<BehaviorBuilder$Mu<E>, T8>): App<BehaviorBuilder$Mu<E>, R>;
    apply9<R extends Object | number | string | boolean, T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean>(arg0: Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>, arg1: App<BehaviorBuilder$Mu<E>, T1>, arg2: App<BehaviorBuilder$Mu<E>, T2>, arg3: App<BehaviorBuilder$Mu<E>, T3>, arg4: App<BehaviorBuilder$Mu<E>, T4>, arg5: App<BehaviorBuilder$Mu<E>, T5>, arg6: App<BehaviorBuilder$Mu<E>, T6>, arg7: App<BehaviorBuilder$Mu<E>, T7>, arg8: App<BehaviorBuilder$Mu<E>, T8>, arg9: App<BehaviorBuilder$Mu<E>, T9>): App<BehaviorBuilder$Mu<E>, R>;
    get<Value extends Object | number | string | boolean>(box: MemoryAccessor<IdF$Mu, Value>): Value;
    ifTriggered(dependentTrigger: Trigger<E>): BehaviorBuilder<E, Unit>;
    lift1<A extends Object | number | string | boolean, R extends Object | number | string | boolean>(function_: App<BehaviorBuilder$Mu<E>, (param0: A) => R>): (param0: App<BehaviorBuilder$Mu<E>, A>) => App<BehaviorBuilder$Mu<E>, R>;
    lift2<A extends Object | number | string | boolean, B extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, (param0: A, param1: B) => R>): (param0: App<BehaviorBuilder$Mu<E>, A>, param1: App<BehaviorBuilder$Mu<E>, B>) => App<BehaviorBuilder$Mu<E>, R>;
    lift3<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function3<T1, T2, T3, R>>): Function3<App<BehaviorBuilder$Mu<E>, T1>, App<BehaviorBuilder$Mu<E>, T2>, App<BehaviorBuilder$Mu<E>, T3>, App<BehaviorBuilder$Mu<E>, R>>;
    lift4<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function4<T1, T2, T3, T4, R>>): Function4<App<BehaviorBuilder$Mu<E>, T1>, App<BehaviorBuilder$Mu<E>, T2>, App<BehaviorBuilder$Mu<E>, T3>, App<BehaviorBuilder$Mu<E>, T4>, App<BehaviorBuilder$Mu<E>, R>>;
    lift5<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function5<T1, T2, T3, T4, T5, R>>): Function5<App<BehaviorBuilder$Mu<E>, T1>, App<BehaviorBuilder$Mu<E>, T2>, App<BehaviorBuilder$Mu<E>, T3>, App<BehaviorBuilder$Mu<E>, T4>, App<BehaviorBuilder$Mu<E>, T5>, App<BehaviorBuilder$Mu<E>, R>>;
    lift6<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function6<T1, T2, T3, T4, T5, T6, R>>): Function6<App<BehaviorBuilder$Mu<E>, T1>, App<BehaviorBuilder$Mu<E>, T2>, App<BehaviorBuilder$Mu<E>, T3>, App<BehaviorBuilder$Mu<E>, T4>, App<BehaviorBuilder$Mu<E>, T5>, App<BehaviorBuilder$Mu<E>, T6>, App<BehaviorBuilder$Mu<E>, R>>;
    lift7<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function7<T1, T2, T3, T4, T5, T6, T7, R>>): Function7<App<BehaviorBuilder$Mu<E>, T1>, App<BehaviorBuilder$Mu<E>, T2>, App<BehaviorBuilder$Mu<E>, T3>, App<BehaviorBuilder$Mu<E>, T4>, App<BehaviorBuilder$Mu<E>, T5>, App<BehaviorBuilder$Mu<E>, T6>, App<BehaviorBuilder$Mu<E>, T7>, App<BehaviorBuilder$Mu<E>, R>>;
    lift8<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>>): Function8<App<BehaviorBuilder$Mu<E>, T1>, App<BehaviorBuilder$Mu<E>, T2>, App<BehaviorBuilder$Mu<E>, T3>, App<BehaviorBuilder$Mu<E>, T4>, App<BehaviorBuilder$Mu<E>, T5>, App<BehaviorBuilder$Mu<E>, T6>, App<BehaviorBuilder$Mu<E>, T7>, App<BehaviorBuilder$Mu<E>, T8>, App<BehaviorBuilder$Mu<E>, R>>;
    lift9<T1 extends Object | number | string | boolean, T2 extends Object | number | string | boolean, T3 extends Object | number | string | boolean, T4 extends Object | number | string | boolean, T5 extends Object | number | string | boolean, T6 extends Object | number | string | boolean, T7 extends Object | number | string | boolean, T8 extends Object | number | string | boolean, T9 extends Object | number | string | boolean, R extends Object | number | string | boolean>(arg0: App<BehaviorBuilder$Mu<E>, Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>>): Function9<App<BehaviorBuilder$Mu<E>, T1>, App<BehaviorBuilder$Mu<E>, T2>, App<BehaviorBuilder$Mu<E>, T3>, App<BehaviorBuilder$Mu<E>, T4>, App<BehaviorBuilder$Mu<E>, T5>, App<BehaviorBuilder$Mu<E>, T6>, App<BehaviorBuilder$Mu<E>, T7>, App<BehaviorBuilder$Mu<E>, T8>, App<BehaviorBuilder$Mu<E>, T9>, App<BehaviorBuilder$Mu<E>, R>>;
    map<R extends Object | number | string | boolean, T extends Object | number | string | boolean>(func: (param0: T) => R, ts: App<BehaviorBuilder$Mu<E>, T>): BehaviorBuilder<E, R>;
    point<A extends Object | number | string | boolean>(a: A): BehaviorBuilder<E, A>;
    point<A extends Object | number | string | boolean>(debugString: () => string, a: A): BehaviorBuilder<E, A>;
    present<Value extends Object | number | string | boolean>(memory: MemoryModuleType<Value>): BehaviorBuilder<E, MemoryAccessor<IdF$Mu, Value>>;
    registered<Value extends Object | number | string | boolean>(memory: MemoryModuleType<Value>): BehaviorBuilder<E, MemoryAccessor<OptionalBox$Mu, Value>>;
    tryGet<Value extends Object | number | string | boolean>(box: MemoryAccessor<OptionalBox$Mu, Value>): Optional<Value>;
}