import type { Direction } from '../../../../../../com/viaversion/viaversion/api/protocol/packet/Direction.d.ts'
import type { State } from '../../../../../../com/viaversion/viaversion/api/protocol/packet/State.d.ts'
import type { ClientboundPacket1_20_3 } from '../../../../../../com/viaversion/viaversion/protocols/v1_20_2to1_20_3/packet/ClientboundPacket1_20_3.d.ts'
import type { Class } from '../../../../../../java/lang/Class.d.ts'
import type { Object } from '../../../../../../java/lang/Object.d.ts'
import type { Enum } from '../../../../../../java/lang/Enum.d.ts'
export class ClientboundPackets1_20_3 extends Enum<ClientboundPackets1_20_3> implements ClientboundPacket1_20_3 {
    static ADD_ENTITY: ClientboundPackets1_20_3;
    static ADD_EXPERIENCE_ORB: ClientboundPackets1_20_3;
    static ANIMATE: ClientboundPackets1_20_3;
    static AWARD_STATS: ClientboundPackets1_20_3;
    static BLOCK_CHANGED_ACK: ClientboundPackets1_20_3;
    static BLOCK_DESTRUCTION: ClientboundPackets1_20_3;
    static BLOCK_ENTITY_DATA: ClientboundPackets1_20_3;
    static BLOCK_EVENT: ClientboundPackets1_20_3;
    static BLOCK_UPDATE: ClientboundPackets1_20_3;
    static BOSS_EVENT: ClientboundPackets1_20_3;
    static BUNDLE_DELIMITER: ClientboundPackets1_20_3;
    static CHANGE_DIFFICULTY: ClientboundPackets1_20_3;
    static CHUNKS_BIOMES: ClientboundPackets1_20_3;
    static CHUNK_BATCH_FINISHED: ClientboundPackets1_20_3;
    static CHUNK_BATCH_START: ClientboundPackets1_20_3;
    static CLEAR_TITLES: ClientboundPackets1_20_3;
    static COMMANDS: ClientboundPackets1_20_3;
    static COMMAND_SUGGESTIONS: ClientboundPackets1_20_3;
    static CONTAINER_CLOSE: ClientboundPackets1_20_3;
    static CONTAINER_SET_CONTENT: ClientboundPackets1_20_3;
    static CONTAINER_SET_DATA: ClientboundPackets1_20_3;
    static CONTAINER_SET_SLOT: ClientboundPackets1_20_3;
    static COOLDOWN: ClientboundPackets1_20_3;
    static CUSTOM_CHAT_COMPLETIONS: ClientboundPackets1_20_3;
    static CUSTOM_PAYLOAD: ClientboundPackets1_20_3;
    static DAMAGE_EVENT: ClientboundPackets1_20_3;
    static DELETE_CHAT: ClientboundPackets1_20_3;
    static DISCONNECT: ClientboundPackets1_20_3;
    static DISGUISED_CHAT: ClientboundPackets1_20_3;
    static ENTITY_EVENT: ClientboundPackets1_20_3;
    static EXPLODE: ClientboundPackets1_20_3;
    static FORGET_LEVEL_CHUNK: ClientboundPackets1_20_3;
    static GAME_EVENT: ClientboundPackets1_20_3;
    static HORSE_SCREEN_OPEN: ClientboundPackets1_20_3;
    static HURT_ANIMATION: ClientboundPackets1_20_3;
    static INITIALIZE_BORDER: ClientboundPackets1_20_3;
    static KEEP_ALIVE: ClientboundPackets1_20_3;
    static LEVEL_CHUNK_WITH_LIGHT: ClientboundPackets1_20_3;
    static LEVEL_EVENT: ClientboundPackets1_20_3;
    static LEVEL_PARTICLES: ClientboundPackets1_20_3;
    static LIGHT_UPDATE: ClientboundPackets1_20_3;
    static LOGIN: ClientboundPackets1_20_3;
    static MAP_ITEM_DATA: ClientboundPackets1_20_3;
    static MERCHANT_OFFERS: ClientboundPackets1_20_3;
    static MOVE_ENTITY_POS: ClientboundPackets1_20_3;
    static MOVE_ENTITY_POS_ROT: ClientboundPackets1_20_3;
    static MOVE_ENTITY_ROT: ClientboundPackets1_20_3;
    static MOVE_VEHICLE: ClientboundPackets1_20_3;
    static OPEN_BOOK: ClientboundPackets1_20_3;
    static OPEN_SCREEN: ClientboundPackets1_20_3;
    static OPEN_SIGN_EDITOR: ClientboundPackets1_20_3;
    static PING: ClientboundPackets1_20_3;
    static PLACE_GHOST_RECIPE: ClientboundPackets1_20_3;
    static PLAYER_ABILITIES: ClientboundPackets1_20_3;
    static PLAYER_CHAT: ClientboundPackets1_20_3;
    static PLAYER_COMBAT_END: ClientboundPackets1_20_3;
    static PLAYER_COMBAT_ENTER: ClientboundPackets1_20_3;
    static PLAYER_COMBAT_KILL: ClientboundPackets1_20_3;
    static PLAYER_INFO_REMOVE: ClientboundPackets1_20_3;
    static PLAYER_INFO_UPDATE: ClientboundPackets1_20_3;
    static PLAYER_LOOK_AT: ClientboundPackets1_20_3;
    static PLAYER_POSITION: ClientboundPackets1_20_3;
    static PONG_RESPONSE: ClientboundPackets1_20_3;
    static RECIPE: ClientboundPackets1_20_3;
    static REMOVE_ENTITIES: ClientboundPackets1_20_3;
    static REMOVE_MOB_EFFECT: ClientboundPackets1_20_3;
    static RESET_SCORE: ClientboundPackets1_20_3;
    static RESOURCE_PACK_POP: ClientboundPackets1_20_3;
    static RESOURCE_PACK_PUSH: ClientboundPackets1_20_3;
    static RESPAWN: ClientboundPackets1_20_3;
    static ROTATE_HEAD: ClientboundPackets1_20_3;
    static SECTION_BLOCKS_UPDATE: ClientboundPackets1_20_3;
    static SELECT_ADVANCEMENTS_TAB: ClientboundPackets1_20_3;
    static SERVER_DATA: ClientboundPackets1_20_3;
    static SET_ACTION_BAR_TEXT: ClientboundPackets1_20_3;
    static SET_BORDER_CENTER: ClientboundPackets1_20_3;
    static SET_BORDER_LERP_SIZE: ClientboundPackets1_20_3;
    static SET_BORDER_SIZE: ClientboundPackets1_20_3;
    static SET_BORDER_WARNING_DELAY: ClientboundPackets1_20_3;
    static SET_BORDER_WARNING_DISTANCE: ClientboundPackets1_20_3;
    static SET_CAMERA: ClientboundPackets1_20_3;
    static SET_CARRIED_ITEM: ClientboundPackets1_20_3;
    static SET_CHUNK_CACHE_CENTER: ClientboundPackets1_20_3;
    static SET_CHUNK_CACHE_RADIUS: ClientboundPackets1_20_3;
    static SET_DEFAULT_SPAWN_POSITION: ClientboundPackets1_20_3;
    static SET_DISPLAY_OBJECTIVE: ClientboundPackets1_20_3;
    static SET_ENTITY_DATA: ClientboundPackets1_20_3;
    static SET_ENTITY_LINK: ClientboundPackets1_20_3;
    static SET_ENTITY_MOTION: ClientboundPackets1_20_3;
    static SET_EQUIPMENT: ClientboundPackets1_20_3;
    static SET_EXPERIENCE: ClientboundPackets1_20_3;
    static SET_HEALTH: ClientboundPackets1_20_3;
    static SET_OBJECTIVE: ClientboundPackets1_20_3;
    static SET_PASSENGERS: ClientboundPackets1_20_3;
    static SET_PLAYER_TEAM: ClientboundPackets1_20_3;
    static SET_SCORE: ClientboundPackets1_20_3;
    static SET_SIMULATION_DISTANCE: ClientboundPackets1_20_3;
    static SET_SUBTITLE_TEXT: ClientboundPackets1_20_3;
    static SET_TIME: ClientboundPackets1_20_3;
    static SET_TITLES_ANIMATION: ClientboundPackets1_20_3;
    static SET_TITLE_TEXT: ClientboundPackets1_20_3;
    static SOUND: ClientboundPackets1_20_3;
    static SOUND_ENTITY: ClientboundPackets1_20_3;
    static START_CONFIGURATION: ClientboundPackets1_20_3;
    static STOP_SOUND: ClientboundPackets1_20_3;
    static SYSTEM_CHAT: ClientboundPackets1_20_3;
    static TAB_LIST: ClientboundPackets1_20_3;
    static TAG_QUERY: ClientboundPackets1_20_3;
    static TAKE_ITEM_ENTITY: ClientboundPackets1_20_3;
    static TELEPORT_ENTITY: ClientboundPackets1_20_3;
    static TICKING_STATE: ClientboundPackets1_20_3;
    static TICKING_STEP: ClientboundPackets1_20_3;
    static UPDATE_ADVANCEMENTS: ClientboundPackets1_20_3;
    static UPDATE_ATTRIBUTES: ClientboundPackets1_20_3;
    static UPDATE_MOB_EFFECT: ClientboundPackets1_20_3;
    static UPDATE_RECIPES: ClientboundPackets1_20_3;
    static UPDATE_TAGS: ClientboundPackets1_20_3;
    static valueOf(paramarg0: Class<Object>, paramarg1: string): Object | null;
    static valueOf(paramarg0: string): ClientboundPackets1_20_3;
    static values(): ClientboundPackets1_20_3[];
    private constructor()
    direction(): Direction;
    getId(): number;
    getName(): string;
    state(): State;
    name(): "BUNDLE_DELIMITER" | "ADD_ENTITY" | "ADD_EXPERIENCE_ORB" | "ANIMATE" | "AWARD_STATS" | "BLOCK_CHANGED_ACK" | "BLOCK_DESTRUCTION" | "BLOCK_ENTITY_DATA" | "BLOCK_EVENT" | "BLOCK_UPDATE" | "BOSS_EVENT" | "CHANGE_DIFFICULTY" | "CHUNK_BATCH_FINISHED" | "CHUNK_BATCH_START" | "CHUNKS_BIOMES" | "CLEAR_TITLES" | "COMMAND_SUGGESTIONS" | "COMMANDS" | "CONTAINER_CLOSE" | "CONTAINER_SET_CONTENT" | "CONTAINER_SET_DATA" | "CONTAINER_SET_SLOT" | "COOLDOWN" | "CUSTOM_CHAT_COMPLETIONS" | "CUSTOM_PAYLOAD" | "DAMAGE_EVENT" | "DELETE_CHAT" | "DISCONNECT" | "DISGUISED_CHAT" | "ENTITY_EVENT" | "EXPLODE" | "FORGET_LEVEL_CHUNK" | "GAME_EVENT" | "HORSE_SCREEN_OPEN" | "HURT_ANIMATION" | "INITIALIZE_BORDER" | "KEEP_ALIVE" | "LEVEL_CHUNK_WITH_LIGHT" | "LEVEL_EVENT" | "LEVEL_PARTICLES" | "LIGHT_UPDATE" | "LOGIN" | "MAP_ITEM_DATA" | "MERCHANT_OFFERS" | "MOVE_ENTITY_POS" | "MOVE_ENTITY_POS_ROT" | "MOVE_ENTITY_ROT" | "MOVE_VEHICLE" | "OPEN_BOOK" | "OPEN_SCREEN" | "OPEN_SIGN_EDITOR" | "PING" | "PONG_RESPONSE" | "PLACE_GHOST_RECIPE" | "PLAYER_ABILITIES" | "PLAYER_CHAT" | "PLAYER_COMBAT_END" | "PLAYER_COMBAT_ENTER" | "PLAYER_COMBAT_KILL" | "PLAYER_INFO_REMOVE" | "PLAYER_INFO_UPDATE" | "PLAYER_LOOK_AT" | "PLAYER_POSITION" | "RECIPE" | "REMOVE_ENTITIES" | "REMOVE_MOB_EFFECT" | "RESET_SCORE" | "RESOURCE_PACK_POP" | "RESOURCE_PACK_PUSH" | "RESPAWN" | "ROTATE_HEAD" | "SECTION_BLOCKS_UPDATE" | "SELECT_ADVANCEMENTS_TAB" | "SERVER_DATA" | "SET_ACTION_BAR_TEXT" | "SET_BORDER_CENTER" | "SET_BORDER_LERP_SIZE" | "SET_BORDER_SIZE" | "SET_BORDER_WARNING_DELAY" | "SET_BORDER_WARNING_DISTANCE" | "SET_CAMERA" | "SET_CARRIED_ITEM" | "SET_CHUNK_CACHE_CENTER" | "SET_CHUNK_CACHE_RADIUS" | "SET_DEFAULT_SPAWN_POSITION" | "SET_DISPLAY_OBJECTIVE" | "SET_ENTITY_DATA" | "SET_ENTITY_LINK" | "SET_ENTITY_MOTION" | "SET_EQUIPMENT" | "SET_EXPERIENCE" | "SET_HEALTH" | "SET_OBJECTIVE" | "SET_PASSENGERS" | "SET_PLAYER_TEAM" | "SET_SCORE" | "SET_SIMULATION_DISTANCE" | "SET_SUBTITLE_TEXT" | "SET_TIME" | "SET_TITLE_TEXT" | "SET_TITLES_ANIMATION" | "SOUND_ENTITY" | "SOUND" | "START_CONFIGURATION" | "STOP_SOUND" | "SYSTEM_CHAT" | "TAB_LIST" | "TAG_QUERY" | "TAKE_ITEM_ENTITY" | "TELEPORT_ENTITY" | "TICKING_STATE" | "TICKING_STEP" | "UPDATE_ADVANCEMENTS" | "UPDATE_ATTRIBUTES" | "UPDATE_MOB_EFFECT" | "UPDATE_RECIPES" | "UPDATE_TAGS";
}