import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { Consumer } from '../../../../java/util/function/Consumer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../../org/lwjgl/system/Struct$StructValidation.d.ts'
import type { GLSLangLimits } from '../../../../org/lwjgl/util/shaderc/GLSLangLimits.d.ts'
export class GLSLangResource extends Struct<GLSLangResource> implements NativeResource {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static LIMITS: number;
    static MAX_ATOMIC_COUNTER_BINDINGS: number;
    static MAX_ATOMIC_COUNTER_BUFFER_SIZE: number;
    static MAX_CLIP_DISTANCES: number;
    static MAX_CLIP_PLANES: number;
    static MAX_COMBINED_ATOMIC_COUNTERS: number;
    static MAX_COMBINED_ATOMIC_COUNTER_BUFFERS: number;
    static MAX_COMBINED_CLIP_AND_CULL_DISTANCES: number;
    static MAX_COMBINED_IMAGE_UNIFORMS: number;
    static MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS: number;
    static MAX_COMBINED_SHADER_OUTPUT_RESOURCES: number;
    static MAX_COMBINED_TEXTURE_IMAGE_UNITS: number;
    static MAX_COMPUTE_ATOMIC_COUNTERS: number;
    static MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS: number;
    static MAX_COMPUTE_IMAGE_UNIFORMS: number;
    static MAX_COMPUTE_TEXTURE_IMAGE_UNITS: number;
    static MAX_COMPUTE_UNIFORM_COMPONENTS: number;
    static MAX_COMPUTE_WORK_GROUP_COUNT_X: number;
    static MAX_COMPUTE_WORK_GROUP_COUNT_Y: number;
    static MAX_COMPUTE_WORK_GROUP_COUNT_Z: number;
    static MAX_COMPUTE_WORK_GROUP_SIZE_X: number;
    static MAX_COMPUTE_WORK_GROUP_SIZE_Y: number;
    static MAX_COMPUTE_WORK_GROUP_SIZE_Z: number;
    static MAX_CULL_DISTANCES: number;
    static MAX_DRAW_BUFFERS: number;
    static MAX_DUAL_SOURCE_DRAW_BUFFERS_EXT: number;
    static MAX_FRAGMENT_ATOMIC_COUNTERS: number;
    static MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS: number;
    static MAX_FRAGMENT_IMAGE_UNIFORMS: number;
    static MAX_FRAGMENT_INPUT_COMPONENTS: number;
    static MAX_FRAGMENT_INPUT_VECTORS: number;
    static MAX_FRAGMENT_UNIFORM_COMPONENTS: number;
    static MAX_FRAGMENT_UNIFORM_VECTORS: number;
    static MAX_GEOMETRY_ATOMIC_COUNTERS: number;
    static MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS: number;
    static MAX_GEOMETRY_IMAGE_UNIFORMS: number;
    static MAX_GEOMETRY_INPUT_COMPONENTS: number;
    static MAX_GEOMETRY_OUTPUT_COMPONENTS: number;
    static MAX_GEOMETRY_OUTPUT_VERTICES: number;
    static MAX_GEOMETRY_TEXTURE_IMAGE_UNITS: number;
    static MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS: number;
    static MAX_GEOMETRY_UNIFORM_COMPONENTS: number;
    static MAX_GEOMETRY_VARYING_COMPONENTS: number;
    static MAX_IMAGE_SAMPLES: number;
    static MAX_IMAGE_UNITS: number;
    static MAX_LIGHTS: number;
    static MAX_MESH_OUTPUT_PRIMITIVES_EXT: number;
    static MAX_MESH_OUTPUT_PRIMITIVES_NV: number;
    static MAX_MESH_OUTPUT_VERTICES_EXT: number;
    static MAX_MESH_OUTPUT_VERTICES_NV: number;
    static MAX_MESH_VIEW_COUNT_EXT: number;
    static MAX_MESH_VIEW_COUNT_NV: number;
    static MAX_MESH_WORK_GROUP_SIZE_X_EXT: number;
    static MAX_MESH_WORK_GROUP_SIZE_X_NV: number;
    static MAX_MESH_WORK_GROUP_SIZE_Y_EXT: number;
    static MAX_MESH_WORK_GROUP_SIZE_Y_NV: number;
    static MAX_MESH_WORK_GROUP_SIZE_Z_EXT: number;
    static MAX_MESH_WORK_GROUP_SIZE_Z_NV: number;
    static MAX_PATCH_VERTICES: number;
    static MAX_PROGRAM_TEXEL_OFFSET: number;
    static MAX_SAMPLES: number;
    static MAX_TASK_WORK_GROUP_SIZE_X_EXT: number;
    static MAX_TASK_WORK_GROUP_SIZE_X_NV: number;
    static MAX_TASK_WORK_GROUP_SIZE_Y_EXT: number;
    static MAX_TASK_WORK_GROUP_SIZE_Y_NV: number;
    static MAX_TASK_WORK_GROUP_SIZE_Z_EXT: number;
    static MAX_TASK_WORK_GROUP_SIZE_Z_NV: number;
    static MAX_TESS_CONTROL_ATOMIC_COUNTERS: number;
    static MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS: number;
    static MAX_TESS_CONTROL_IMAGE_UNIFORMS: number;
    static MAX_TESS_CONTROL_INPUT_COMPONENTS: number;
    static MAX_TESS_CONTROL_OUTPUT_COMPONENTS: number;
    static MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS: number;
    static MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS: number;
    static MAX_TESS_CONTROL_UNIFORM_COMPONENTS: number;
    static MAX_TESS_EVALUATION_ATOMIC_COUNTERS: number;
    static MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS: number;
    static MAX_TESS_EVALUATION_IMAGE_UNIFORMS: number;
    static MAX_TESS_EVALUATION_INPUT_COMPONENTS: number;
    static MAX_TESS_EVALUATION_OUTPUT_COMPONENTS: number;
    static MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS: number;
    static MAX_TESS_EVALUATION_UNIFORM_COMPONENTS: number;
    static MAX_TESS_GEN_LEVEL: number;
    static MAX_TESS_PATCH_COMPONENTS: number;
    static MAX_TEXTURE_COORDS: number;
    static MAX_TEXTURE_IMAGE_UNITS: number;
    static MAX_TEXTURE_UNITS: number;
    static MAX_TRANSFORM_FEEDBACK_BUFFERS: number;
    static MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS: number;
    static MAX_VARYING_COMPONENTS: number;
    static MAX_VARYING_FLOATS: number;
    static MAX_VARYING_VECTORS: number;
    static MAX_VERTEX_ATOMIC_COUNTERS: number;
    static MAX_VERTEX_ATOMIC_COUNTER_BUFFERS: number;
    static MAX_VERTEX_ATTRIBS: number;
    static MAX_VERTEX_IMAGE_UNIFORMS: number;
    static MAX_VERTEX_OUTPUT_COMPONENTS: number;
    static MAX_VERTEX_OUTPUT_VECTORS: number;
    static MAX_VERTEX_TEXTURE_IMAGE_UNITS: number;
    static MAX_VERTEX_UNIFORM_COMPONENTS: number;
    static MAX_VERTEX_UNIFORM_VECTORS: number;
    static MAX_VIEWPORTS: number;
    static MIN_PROGRAM_TEXEL_OFFSET: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static SIZEOF: number;
    static calloc(): GLSLangResource;
    static calloc(paramarg0: MemoryStack): GLSLangResource;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): GLSLangResource;
    static create(paramarg0: number): GLSLangResource;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): GLSLangResource;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): GLSLangResource;
    static malloc(paramarg0: MemoryStack): GLSLangResource;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static nlimits(paramarg0: number): GLSLangLimits;
    static nlimits(paramarg0: number, paramarg1: GLSLangLimits): void;
    static nmax_atomic_counter_bindings(paramarg0: number): number;
    static nmax_atomic_counter_bindings(paramarg0: number, paramarg1: number): void;
    static nmax_atomic_counter_buffer_size(paramarg0: number): number;
    static nmax_atomic_counter_buffer_size(paramarg0: number, paramarg1: number): void;
    static nmax_clip_distances(paramarg0: number): number;
    static nmax_clip_distances(paramarg0: number, paramarg1: number): void;
    static nmax_clip_planes(paramarg0: number): number;
    static nmax_clip_planes(paramarg0: number, paramarg1: number): void;
    static nmax_combined_atomic_counter_buffers(paramarg0: number): number;
    static nmax_combined_atomic_counter_buffers(paramarg0: number, paramarg1: number): void;
    static nmax_combined_atomic_counters(paramarg0: number): number;
    static nmax_combined_atomic_counters(paramarg0: number, paramarg1: number): void;
    static nmax_combined_clip_and_cull_distances(paramarg0: number): number;
    static nmax_combined_clip_and_cull_distances(paramarg0: number, paramarg1: number): void;
    static nmax_combined_image_uniforms(paramarg0: number): number;
    static nmax_combined_image_uniforms(paramarg0: number, paramarg1: number): void;
    static nmax_combined_image_units_and_fragment_outputs(paramarg0: number): number;
    static nmax_combined_image_units_and_fragment_outputs(paramarg0: number, paramarg1: number): void;
    static nmax_combined_shader_output_resources(paramarg0: number): number;
    static nmax_combined_shader_output_resources(paramarg0: number, paramarg1: number): void;
    static nmax_combined_texture_image_units(paramarg0: number): number;
    static nmax_combined_texture_image_units(paramarg0: number, paramarg1: number): void;
    static nmax_compute_atomic_counter_buffers(paramarg0: number): number;
    static nmax_compute_atomic_counter_buffers(paramarg0: number, paramarg1: number): void;
    static nmax_compute_atomic_counters(paramarg0: number): number;
    static nmax_compute_atomic_counters(paramarg0: number, paramarg1: number): void;
    static nmax_compute_image_uniforms(paramarg0: number): number;
    static nmax_compute_image_uniforms(paramarg0: number, paramarg1: number): void;
    static nmax_compute_texture_image_units(paramarg0: number): number;
    static nmax_compute_texture_image_units(paramarg0: number, paramarg1: number): void;
    static nmax_compute_uniform_components(paramarg0: number): number;
    static nmax_compute_uniform_components(paramarg0: number, paramarg1: number): void;
    static nmax_compute_work_group_count_x(paramarg0: number): number;
    static nmax_compute_work_group_count_x(paramarg0: number, paramarg1: number): void;
    static nmax_compute_work_group_count_y(paramarg0: number): number;
    static nmax_compute_work_group_count_y(paramarg0: number, paramarg1: number): void;
    static nmax_compute_work_group_count_z(paramarg0: number): number;
    static nmax_compute_work_group_count_z(paramarg0: number, paramarg1: number): void;
    static nmax_compute_work_group_size_x(paramarg0: number): number;
    static nmax_compute_work_group_size_x(paramarg0: number, paramarg1: number): void;
    static nmax_compute_work_group_size_y(paramarg0: number): number;
    static nmax_compute_work_group_size_y(paramarg0: number, paramarg1: number): void;
    static nmax_compute_work_group_size_z(paramarg0: number): number;
    static nmax_compute_work_group_size_z(paramarg0: number, paramarg1: number): void;
    static nmax_cull_distances(paramarg0: number): number;
    static nmax_cull_distances(paramarg0: number, paramarg1: number): void;
    static nmax_draw_buffers(paramarg0: number): number;
    static nmax_draw_buffers(paramarg0: number, paramarg1: number): void;
    static nmax_dual_source_draw_buffers_ext(paramarg0: number): number;
    static nmax_dual_source_draw_buffers_ext(paramarg0: number, paramarg1: number): void;
    static nmax_fragment_atomic_counter_buffers(paramarg0: number): number;
    static nmax_fragment_atomic_counter_buffers(paramarg0: number, paramarg1: number): void;
    static nmax_fragment_atomic_counters(paramarg0: number): number;
    static nmax_fragment_atomic_counters(paramarg0: number, paramarg1: number): void;
    static nmax_fragment_image_uniforms(paramarg0: number): number;
    static nmax_fragment_image_uniforms(paramarg0: number, paramarg1: number): void;
    static nmax_fragment_input_components(paramarg0: number): number;
    static nmax_fragment_input_components(paramarg0: number, paramarg1: number): void;
    static nmax_fragment_input_vectors(paramarg0: number): number;
    static nmax_fragment_input_vectors(paramarg0: number, paramarg1: number): void;
    static nmax_fragment_uniform_components(paramarg0: number): number;
    static nmax_fragment_uniform_components(paramarg0: number, paramarg1: number): void;
    static nmax_fragment_uniform_vectors(paramarg0: number): number;
    static nmax_fragment_uniform_vectors(paramarg0: number, paramarg1: number): void;
    static nmax_geometry_atomic_counter_buffers(paramarg0: number): number;
    static nmax_geometry_atomic_counter_buffers(paramarg0: number, paramarg1: number): void;
    static nmax_geometry_atomic_counters(paramarg0: number): number;
    static nmax_geometry_atomic_counters(paramarg0: number, paramarg1: number): void;
    static nmax_geometry_image_uniforms(paramarg0: number): number;
    static nmax_geometry_image_uniforms(paramarg0: number, paramarg1: number): void;
    static nmax_geometry_input_components(paramarg0: number): number;
    static nmax_geometry_input_components(paramarg0: number, paramarg1: number): void;
    static nmax_geometry_output_components(paramarg0: number): number;
    static nmax_geometry_output_components(paramarg0: number, paramarg1: number): void;
    static nmax_geometry_output_vertices(paramarg0: number): number;
    static nmax_geometry_output_vertices(paramarg0: number, paramarg1: number): void;
    static nmax_geometry_texture_image_units(paramarg0: number): number;
    static nmax_geometry_texture_image_units(paramarg0: number, paramarg1: number): void;
    static nmax_geometry_total_output_components(paramarg0: number): number;
    static nmax_geometry_total_output_components(paramarg0: number, paramarg1: number): void;
    static nmax_geometry_uniform_components(paramarg0: number): number;
    static nmax_geometry_uniform_components(paramarg0: number, paramarg1: number): void;
    static nmax_geometry_varying_components(paramarg0: number): number;
    static nmax_geometry_varying_components(paramarg0: number, paramarg1: number): void;
    static nmax_image_samples(paramarg0: number): number;
    static nmax_image_samples(paramarg0: number, paramarg1: number): void;
    static nmax_image_units(paramarg0: number): number;
    static nmax_image_units(paramarg0: number, paramarg1: number): void;
    static nmax_lights(paramarg0: number): number;
    static nmax_lights(paramarg0: number, paramarg1: number): void;
    static nmax_mesh_output_primitives_ext(paramarg0: number): number;
    static nmax_mesh_output_primitives_ext(paramarg0: number, paramarg1: number): void;
    static nmax_mesh_output_primitives_nv(paramarg0: number): number;
    static nmax_mesh_output_primitives_nv(paramarg0: number, paramarg1: number): void;
    static nmax_mesh_output_vertices_ext(paramarg0: number): number;
    static nmax_mesh_output_vertices_ext(paramarg0: number, paramarg1: number): void;
    static nmax_mesh_output_vertices_nv(paramarg0: number): number;
    static nmax_mesh_output_vertices_nv(paramarg0: number, paramarg1: number): void;
    static nmax_mesh_view_count_ext(paramarg0: number): number;
    static nmax_mesh_view_count_ext(paramarg0: number, paramarg1: number): void;
    static nmax_mesh_view_count_nv(paramarg0: number): number;
    static nmax_mesh_view_count_nv(paramarg0: number, paramarg1: number): void;
    static nmax_mesh_work_group_size_x_ext(paramarg0: number): number;
    static nmax_mesh_work_group_size_x_ext(paramarg0: number, paramarg1: number): void;
    static nmax_mesh_work_group_size_x_nv(paramarg0: number): number;
    static nmax_mesh_work_group_size_x_nv(paramarg0: number, paramarg1: number): void;
    static nmax_mesh_work_group_size_y_ext(paramarg0: number): number;
    static nmax_mesh_work_group_size_y_ext(paramarg0: number, paramarg1: number): void;
    static nmax_mesh_work_group_size_y_nv(paramarg0: number): number;
    static nmax_mesh_work_group_size_y_nv(paramarg0: number, paramarg1: number): void;
    static nmax_mesh_work_group_size_z_ext(paramarg0: number): number;
    static nmax_mesh_work_group_size_z_ext(paramarg0: number, paramarg1: number): void;
    static nmax_mesh_work_group_size_z_nv(paramarg0: number): number;
    static nmax_mesh_work_group_size_z_nv(paramarg0: number, paramarg1: number): void;
    static nmax_patch_vertices(paramarg0: number): number;
    static nmax_patch_vertices(paramarg0: number, paramarg1: number): void;
    static nmax_program_texel_offset(paramarg0: number): number;
    static nmax_program_texel_offset(paramarg0: number, paramarg1: number): void;
    static nmax_samples(paramarg0: number): number;
    static nmax_samples(paramarg0: number, paramarg1: number): void;
    static nmax_task_work_group_size_x_ext(paramarg0: number): number;
    static nmax_task_work_group_size_x_ext(paramarg0: number, paramarg1: number): void;
    static nmax_task_work_group_size_x_nv(paramarg0: number): number;
    static nmax_task_work_group_size_x_nv(paramarg0: number, paramarg1: number): void;
    static nmax_task_work_group_size_y_ext(paramarg0: number): number;
    static nmax_task_work_group_size_y_ext(paramarg0: number, paramarg1: number): void;
    static nmax_task_work_group_size_y_nv(paramarg0: number): number;
    static nmax_task_work_group_size_y_nv(paramarg0: number, paramarg1: number): void;
    static nmax_task_work_group_size_z_ext(paramarg0: number): number;
    static nmax_task_work_group_size_z_ext(paramarg0: number, paramarg1: number): void;
    static nmax_task_work_group_size_z_nv(paramarg0: number): number;
    static nmax_task_work_group_size_z_nv(paramarg0: number, paramarg1: number): void;
    static nmax_tess_control_atomic_counter_buffers(paramarg0: number): number;
    static nmax_tess_control_atomic_counter_buffers(paramarg0: number, paramarg1: number): void;
    static nmax_tess_control_atomic_counters(paramarg0: number): number;
    static nmax_tess_control_atomic_counters(paramarg0: number, paramarg1: number): void;
    static nmax_tess_control_image_uniforms(paramarg0: number): number;
    static nmax_tess_control_image_uniforms(paramarg0: number, paramarg1: number): void;
    static nmax_tess_control_input_components(paramarg0: number): number;
    static nmax_tess_control_input_components(paramarg0: number, paramarg1: number): void;
    static nmax_tess_control_output_components(paramarg0: number): number;
    static nmax_tess_control_output_components(paramarg0: number, paramarg1: number): void;
    static nmax_tess_control_texture_image_units(paramarg0: number): number;
    static nmax_tess_control_texture_image_units(paramarg0: number, paramarg1: number): void;
    static nmax_tess_control_total_output_components(paramarg0: number): number;
    static nmax_tess_control_total_output_components(paramarg0: number, paramarg1: number): void;
    static nmax_tess_control_uniform_components(paramarg0: number): number;
    static nmax_tess_control_uniform_components(paramarg0: number, paramarg1: number): void;
    static nmax_tess_evaluation_atomic_counter_buffers(paramarg0: number): number;
    static nmax_tess_evaluation_atomic_counter_buffers(paramarg0: number, paramarg1: number): void;
    static nmax_tess_evaluation_atomic_counters(paramarg0: number): number;
    static nmax_tess_evaluation_atomic_counters(paramarg0: number, paramarg1: number): void;
    static nmax_tess_evaluation_image_uniforms(paramarg0: number): number;
    static nmax_tess_evaluation_image_uniforms(paramarg0: number, paramarg1: number): void;
    static nmax_tess_evaluation_input_components(paramarg0: number): number;
    static nmax_tess_evaluation_input_components(paramarg0: number, paramarg1: number): void;
    static nmax_tess_evaluation_output_components(paramarg0: number): number;
    static nmax_tess_evaluation_output_components(paramarg0: number, paramarg1: number): void;
    static nmax_tess_evaluation_texture_image_units(paramarg0: number): number;
    static nmax_tess_evaluation_texture_image_units(paramarg0: number, paramarg1: number): void;
    static nmax_tess_evaluation_uniform_components(paramarg0: number): number;
    static nmax_tess_evaluation_uniform_components(paramarg0: number, paramarg1: number): void;
    static nmax_tess_gen_level(paramarg0: number): number;
    static nmax_tess_gen_level(paramarg0: number, paramarg1: number): void;
    static nmax_tess_patch_components(paramarg0: number): number;
    static nmax_tess_patch_components(paramarg0: number, paramarg1: number): void;
    static nmax_texture_coords(paramarg0: number): number;
    static nmax_texture_coords(paramarg0: number, paramarg1: number): void;
    static nmax_texture_image_units(paramarg0: number): number;
    static nmax_texture_image_units(paramarg0: number, paramarg1: number): void;
    static nmax_texture_units(paramarg0: number): number;
    static nmax_texture_units(paramarg0: number, paramarg1: number): void;
    static nmax_transform_feedback_buffers(paramarg0: number): number;
    static nmax_transform_feedback_buffers(paramarg0: number, paramarg1: number): void;
    static nmax_transform_feedback_interleaved_components(paramarg0: number): number;
    static nmax_transform_feedback_interleaved_components(paramarg0: number, paramarg1: number): void;
    static nmax_varying_components(paramarg0: number): number;
    static nmax_varying_components(paramarg0: number, paramarg1: number): void;
    static nmax_varying_floats(paramarg0: number): number;
    static nmax_varying_floats(paramarg0: number, paramarg1: number): void;
    static nmax_varying_vectors(paramarg0: number): number;
    static nmax_varying_vectors(paramarg0: number, paramarg1: number): void;
    static nmax_vertex_atomic_counter_buffers(paramarg0: number): number;
    static nmax_vertex_atomic_counter_buffers(paramarg0: number, paramarg1: number): void;
    static nmax_vertex_atomic_counters(paramarg0: number): number;
    static nmax_vertex_atomic_counters(paramarg0: number, paramarg1: number): void;
    static nmax_vertex_attribs(paramarg0: number): number;
    static nmax_vertex_attribs(paramarg0: number, paramarg1: number): void;
    static nmax_vertex_image_uniforms(paramarg0: number): number;
    static nmax_vertex_image_uniforms(paramarg0: number, paramarg1: number): void;
    static nmax_vertex_output_components(paramarg0: number): number;
    static nmax_vertex_output_components(paramarg0: number, paramarg1: number): void;
    static nmax_vertex_output_vectors(paramarg0: number): number;
    static nmax_vertex_output_vectors(paramarg0: number, paramarg1: number): void;
    static nmax_vertex_texture_image_units(paramarg0: number): number;
    static nmax_vertex_texture_image_units(paramarg0: number, paramarg1: number): void;
    static nmax_vertex_uniform_components(paramarg0: number): number;
    static nmax_vertex_uniform_components(paramarg0: number, paramarg1: number): void;
    static nmax_vertex_uniform_vectors(paramarg0: number): number;
    static nmax_vertex_uniform_vectors(paramarg0: number, paramarg1: number): void;
    static nmax_viewports(paramarg0: number): number;
    static nmax_viewports(paramarg0: number, paramarg1: number): void;
    static nmin_program_texel_offset(paramarg0: number): number;
    static nmin_program_texel_offset(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    close(): void;
    create(arg0: number, arg1: ByteBuffer): GLSLangResource;
    limits(): GLSLangLimits;
    limits(arg0: (param0: GLSLangLimits) => void): GLSLangResource;
    limits(arg0: GLSLangLimits): GLSLangResource;
    max_atomic_counter_bindings(): number;
    max_atomic_counter_bindings(arg0: number): GLSLangResource;
    max_atomic_counter_buffer_size(): number;
    max_atomic_counter_buffer_size(arg0: number): GLSLangResource;
    max_clip_distances(): number;
    max_clip_distances(arg0: number): GLSLangResource;
    max_clip_planes(): number;
    max_clip_planes(arg0: number): GLSLangResource;
    max_combined_atomic_counter_buffers(): number;
    max_combined_atomic_counter_buffers(arg0: number): GLSLangResource;
    max_combined_atomic_counters(): number;
    max_combined_atomic_counters(arg0: number): GLSLangResource;
    max_combined_clip_and_cull_distances(): number;
    max_combined_clip_and_cull_distances(arg0: number): GLSLangResource;
    max_combined_image_uniforms(): number;
    max_combined_image_uniforms(arg0: number): GLSLangResource;
    max_combined_image_units_and_fragment_outputs(): number;
    max_combined_image_units_and_fragment_outputs(arg0: number): GLSLangResource;
    max_combined_shader_output_resources(): number;
    max_combined_shader_output_resources(arg0: number): GLSLangResource;
    max_combined_texture_image_units(): number;
    max_combined_texture_image_units(arg0: number): GLSLangResource;
    max_compute_atomic_counter_buffers(): number;
    max_compute_atomic_counter_buffers(arg0: number): GLSLangResource;
    max_compute_atomic_counters(): number;
    max_compute_atomic_counters(arg0: number): GLSLangResource;
    max_compute_image_uniforms(): number;
    max_compute_image_uniforms(arg0: number): GLSLangResource;
    max_compute_texture_image_units(): number;
    max_compute_texture_image_units(arg0: number): GLSLangResource;
    max_compute_uniform_components(): number;
    max_compute_uniform_components(arg0: number): GLSLangResource;
    max_compute_work_group_count_x(): number;
    max_compute_work_group_count_x(arg0: number): GLSLangResource;
    max_compute_work_group_count_y(): number;
    max_compute_work_group_count_y(arg0: number): GLSLangResource;
    max_compute_work_group_count_z(): number;
    max_compute_work_group_count_z(arg0: number): GLSLangResource;
    max_compute_work_group_size_x(): number;
    max_compute_work_group_size_x(arg0: number): GLSLangResource;
    max_compute_work_group_size_y(): number;
    max_compute_work_group_size_y(arg0: number): GLSLangResource;
    max_compute_work_group_size_z(): number;
    max_compute_work_group_size_z(arg0: number): GLSLangResource;
    max_cull_distances(): number;
    max_cull_distances(arg0: number): GLSLangResource;
    max_draw_buffers(): number;
    max_draw_buffers(arg0: number): GLSLangResource;
    max_dual_source_draw_buffers_ext(): number;
    max_dual_source_draw_buffers_ext(arg0: number): GLSLangResource;
    max_fragment_atomic_counter_buffers(): number;
    max_fragment_atomic_counter_buffers(arg0: number): GLSLangResource;
    max_fragment_atomic_counters(): number;
    max_fragment_atomic_counters(arg0: number): GLSLangResource;
    max_fragment_image_uniforms(): number;
    max_fragment_image_uniforms(arg0: number): GLSLangResource;
    max_fragment_input_components(): number;
    max_fragment_input_components(arg0: number): GLSLangResource;
    max_fragment_input_vectors(): number;
    max_fragment_input_vectors(arg0: number): GLSLangResource;
    max_fragment_uniform_components(): number;
    max_fragment_uniform_components(arg0: number): GLSLangResource;
    max_fragment_uniform_vectors(): number;
    max_fragment_uniform_vectors(arg0: number): GLSLangResource;
    max_geometry_atomic_counter_buffers(): number;
    max_geometry_atomic_counter_buffers(arg0: number): GLSLangResource;
    max_geometry_atomic_counters(): number;
    max_geometry_atomic_counters(arg0: number): GLSLangResource;
    max_geometry_image_uniforms(): number;
    max_geometry_image_uniforms(arg0: number): GLSLangResource;
    max_geometry_input_components(): number;
    max_geometry_input_components(arg0: number): GLSLangResource;
    max_geometry_output_components(): number;
    max_geometry_output_components(arg0: number): GLSLangResource;
    max_geometry_output_vertices(): number;
    max_geometry_output_vertices(arg0: number): GLSLangResource;
    max_geometry_texture_image_units(): number;
    max_geometry_texture_image_units(arg0: number): GLSLangResource;
    max_geometry_total_output_components(): number;
    max_geometry_total_output_components(arg0: number): GLSLangResource;
    max_geometry_uniform_components(): number;
    max_geometry_uniform_components(arg0: number): GLSLangResource;
    max_geometry_varying_components(): number;
    max_geometry_varying_components(arg0: number): GLSLangResource;
    max_image_samples(): number;
    max_image_samples(arg0: number): GLSLangResource;
    max_image_units(): number;
    max_image_units(arg0: number): GLSLangResource;
    max_lights(): number;
    max_lights(arg0: number): GLSLangResource;
    max_mesh_output_primitives_ext(): number;
    max_mesh_output_primitives_ext(arg0: number): GLSLangResource;
    max_mesh_output_primitives_nv(): number;
    max_mesh_output_primitives_nv(arg0: number): GLSLangResource;
    max_mesh_output_vertices_ext(): number;
    max_mesh_output_vertices_ext(arg0: number): GLSLangResource;
    max_mesh_output_vertices_nv(): number;
    max_mesh_output_vertices_nv(arg0: number): GLSLangResource;
    max_mesh_view_count_ext(): number;
    max_mesh_view_count_ext(arg0: number): GLSLangResource;
    max_mesh_view_count_nv(): number;
    max_mesh_view_count_nv(arg0: number): GLSLangResource;
    max_mesh_work_group_size_x_ext(): number;
    max_mesh_work_group_size_x_ext(arg0: number): GLSLangResource;
    max_mesh_work_group_size_x_nv(): number;
    max_mesh_work_group_size_x_nv(arg0: number): GLSLangResource;
    max_mesh_work_group_size_y_ext(): number;
    max_mesh_work_group_size_y_ext(arg0: number): GLSLangResource;
    max_mesh_work_group_size_y_nv(): number;
    max_mesh_work_group_size_y_nv(arg0: number): GLSLangResource;
    max_mesh_work_group_size_z_ext(): number;
    max_mesh_work_group_size_z_ext(arg0: number): GLSLangResource;
    max_mesh_work_group_size_z_nv(): number;
    max_mesh_work_group_size_z_nv(arg0: number): GLSLangResource;
    max_patch_vertices(): number;
    max_patch_vertices(arg0: number): GLSLangResource;
    max_program_texel_offset(): number;
    max_program_texel_offset(arg0: number): GLSLangResource;
    max_samples(): number;
    max_samples(arg0: number): GLSLangResource;
    max_task_work_group_size_x_ext(): number;
    max_task_work_group_size_x_ext(arg0: number): GLSLangResource;
    max_task_work_group_size_x_nv(): number;
    max_task_work_group_size_x_nv(arg0: number): GLSLangResource;
    max_task_work_group_size_y_ext(): number;
    max_task_work_group_size_y_ext(arg0: number): GLSLangResource;
    max_task_work_group_size_y_nv(): number;
    max_task_work_group_size_y_nv(arg0: number): GLSLangResource;
    max_task_work_group_size_z_ext(): number;
    max_task_work_group_size_z_ext(arg0: number): GLSLangResource;
    max_task_work_group_size_z_nv(): number;
    max_task_work_group_size_z_nv(arg0: number): GLSLangResource;
    max_tess_control_atomic_counter_buffers(): number;
    max_tess_control_atomic_counter_buffers(arg0: number): GLSLangResource;
    max_tess_control_atomic_counters(): number;
    max_tess_control_atomic_counters(arg0: number): GLSLangResource;
    max_tess_control_image_uniforms(): number;
    max_tess_control_image_uniforms(arg0: number): GLSLangResource;
    max_tess_control_input_components(): number;
    max_tess_control_input_components(arg0: number): GLSLangResource;
    max_tess_control_output_components(): number;
    max_tess_control_output_components(arg0: number): GLSLangResource;
    max_tess_control_texture_image_units(): number;
    max_tess_control_texture_image_units(arg0: number): GLSLangResource;
    max_tess_control_total_output_components(): number;
    max_tess_control_total_output_components(arg0: number): GLSLangResource;
    max_tess_control_uniform_components(): number;
    max_tess_control_uniform_components(arg0: number): GLSLangResource;
    max_tess_evaluation_atomic_counter_buffers(): number;
    max_tess_evaluation_atomic_counter_buffers(arg0: number): GLSLangResource;
    max_tess_evaluation_atomic_counters(): number;
    max_tess_evaluation_atomic_counters(arg0: number): GLSLangResource;
    max_tess_evaluation_image_uniforms(): number;
    max_tess_evaluation_image_uniforms(arg0: number): GLSLangResource;
    max_tess_evaluation_input_components(): number;
    max_tess_evaluation_input_components(arg0: number): GLSLangResource;
    max_tess_evaluation_output_components(): number;
    max_tess_evaluation_output_components(arg0: number): GLSLangResource;
    max_tess_evaluation_texture_image_units(): number;
    max_tess_evaluation_texture_image_units(arg0: number): GLSLangResource;
    max_tess_evaluation_uniform_components(): number;
    max_tess_evaluation_uniform_components(arg0: number): GLSLangResource;
    max_tess_gen_level(): number;
    max_tess_gen_level(arg0: number): GLSLangResource;
    max_tess_patch_components(): number;
    max_tess_patch_components(arg0: number): GLSLangResource;
    max_texture_coords(): number;
    max_texture_coords(arg0: number): GLSLangResource;
    max_texture_image_units(): number;
    max_texture_image_units(arg0: number): GLSLangResource;
    max_texture_units(): number;
    max_texture_units(arg0: number): GLSLangResource;
    max_transform_feedback_buffers(): number;
    max_transform_feedback_buffers(arg0: number): GLSLangResource;
    max_transform_feedback_interleaved_components(): number;
    max_transform_feedback_interleaved_components(arg0: number): GLSLangResource;
    max_varying_components(): number;
    max_varying_components(arg0: number): GLSLangResource;
    max_varying_floats(): number;
    max_varying_floats(arg0: number): GLSLangResource;
    max_varying_vectors(): number;
    max_varying_vectors(arg0: number): GLSLangResource;
    max_vertex_atomic_counter_buffers(): number;
    max_vertex_atomic_counter_buffers(arg0: number): GLSLangResource;
    max_vertex_atomic_counters(): number;
    max_vertex_atomic_counters(arg0: number): GLSLangResource;
    max_vertex_attribs(): number;
    max_vertex_attribs(arg0: number): GLSLangResource;
    max_vertex_image_uniforms(): number;
    max_vertex_image_uniforms(arg0: number): GLSLangResource;
    max_vertex_output_components(): number;
    max_vertex_output_components(arg0: number): GLSLangResource;
    max_vertex_output_vectors(): number;
    max_vertex_output_vectors(arg0: number): GLSLangResource;
    max_vertex_texture_image_units(): number;
    max_vertex_texture_image_units(arg0: number): GLSLangResource;
    max_vertex_uniform_components(): number;
    max_vertex_uniform_components(arg0: number): GLSLangResource;
    max_vertex_uniform_vectors(): number;
    max_vertex_uniform_vectors(arg0: number): GLSLangResource;
    max_viewports(): number;
    max_viewports(arg0: number): GLSLangResource;
    min_program_texel_offset(): number;
    min_program_texel_offset(arg0: number): GLSLangResource;
    set(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number, arg15: number, arg16: number, arg17: number, arg18: number, arg19: number, arg20: number, arg21: number, arg22: number, arg23: number, arg24: number, arg25: number, arg26: number, arg27: number, arg28: number, arg29: number, arg30: number, arg31: number, arg32: number, arg33: number, arg34: number, arg35: number, arg36: number, arg37: number, arg38: number, arg39: number, arg40: number, arg41: number, arg42: number, arg43: number, arg44: number, arg45: number, arg46: number, arg47: number, arg48: number, arg49: number, arg50: number, arg51: number, arg52: number, arg53: number, arg54: number, arg55: number, arg56: number, arg57: number, arg58: number, arg59: number, arg60: number, arg61: number, arg62: number, arg63: number, arg64: number, arg65: number, arg66: number, arg67: number, arg68: number, arg69: number, arg70: number, arg71: number, arg72: number, arg73: number, arg74: number, arg75: number, arg76: number, arg77: number, arg78: number, arg79: number, arg80: number, arg81: number, arg82: number, arg83: number, arg84: number, arg85: number, arg86: number, arg87: number, arg88: number, arg89: number, arg90: number, arg91: number, arg92: number, arg93: number, arg94: number, arg95: number, arg96: number, arg97: number, arg98: number, arg99: number, arg100: number, arg101: number, arg102: GLSLangLimits): GLSLangResource;
    set(arg0: GLSLangResource): GLSLangResource;
    sizeof(): number;
}