import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { IntBuffer } from '../../../../java/nio/IntBuffer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../../java/lang/CharSequence.d.ts'
import type { PointerBuffer } from '../../../../org/lwjgl/PointerBuffer.d.ts'
import type { SharedLibrary } from '../../../../org/lwjgl/system/SharedLibrary.d.ts'
import type { GLSLangInput } from '../../../../org/lwjgl/util/shaderc/GLSLangInput.d.ts'
import type { GLSLangSPVOptions } from '../../../../org/lwjgl/util/shaderc/GLSLangSPVOptions.d.ts'
import type { GLSLangVersion } from '../../../../org/lwjgl/util/shaderc/GLSLangVersion.d.ts'
export class GLSLang extends Object {
    static GLSLANG_BAD_PROFILE: number;
    static GLSLANG_CLIENT_NONE: number;
    static GLSLANG_CLIENT_OPENGL: number;
    static GLSLANG_CLIENT_VULKAN: number;
    static GLSLANG_COMPATIBILITY_PROFILE: number;
    static GLSLANG_CORE_PROFILE: number;
    static GLSLANG_ES_PROFILE: number;
    static GLSLANG_EX_FRAGMENT: number;
    static GLSLANG_EX_VERTEX_FRAGMENT: number;
    static GLSLANG_MSG_ABSOLUTE_PATH: number;
    static GLSLANG_MSG_AST_BIT: number;
    static GLSLANG_MSG_BUILTIN_SYMBOL_TABLE_BIT: number;
    static GLSLANG_MSG_CASCADING_ERRORS_BIT: number;
    static GLSLANG_MSG_DEBUG_INFO_BIT: number;
    static GLSLANG_MSG_DEFAULT_BIT: number;
    static GLSLANG_MSG_DISPLAY_ERROR_COLUMN: number;
    static GLSLANG_MSG_ENHANCED: number;
    static GLSLANG_MSG_HLSL_DX9_COMPATIBLE_BIT: number;
    static GLSLANG_MSG_HLSL_ENABLE_16BIT_TYPES_BIT: number;
    static GLSLANG_MSG_HLSL_LEGALIZATION_BIT: number;
    static GLSLANG_MSG_HLSL_OFFSETS_BIT: number;
    static GLSLANG_MSG_KEEP_UNCALLED_BIT: number;
    static GLSLANG_MSG_LINK_TIME_OPTIMIZATION_BIT: number;
    static GLSLANG_MSG_ONLY_PREPROCESSOR_BIT: number;
    static GLSLANG_MSG_READ_HLSL_BIT: number;
    static GLSLANG_MSG_RELAXED_ERRORS_BIT: number;
    static GLSLANG_MSG_SPV_RULES_BIT: number;
    static GLSLANG_MSG_SUPPRESS_WARNINGS_BIT: number;
    static GLSLANG_MSG_VALIDATE_CROSS_STAGE_IO_BIT: number;
    static GLSLANG_MSG_VULKAN_RULES_BIT: number;
    static GLSLANG_NO_PROFILE: number;
    static GLSLANG_OPT_FULL: number;
    static GLSLANG_OPT_NONE: number;
    static GLSLANG_OPT_NO_GENERATION: number;
    static GLSLANG_OPT_SIMPLE: number;
    static GLSLANG_REFLECTION_ALL_BLOCK_VARIABLES_BIT: number;
    static GLSLANG_REFLECTION_ALL_IO_VARIABLES_BIT: number;
    static GLSLANG_REFLECTION_BASIC_ARRAY_SUFFIX_BIT: number;
    static GLSLANG_REFLECTION_DEFAULT_BIT: number;
    static GLSLANG_REFLECTION_INTERMEDIATE_IOO_BIT: number;
    static GLSLANG_REFLECTION_SEPARATE_BUFFERS_BIT: number;
    static GLSLANG_REFLECTION_SHARED_STD140_SSBO_BIT: number;
    static GLSLANG_REFLECTION_SHARED_STD140_UBO_BIT: number;
    static GLSLANG_REFLECTION_STRICT_ARRAY_SUFFIX_BIT: number;
    static GLSLANG_REFLECTION_UNWRAP_IO_BLOCKS_BIT: number;
    static GLSLANG_RESOURCE_TYPE_AS: number;
    static GLSLANG_RESOURCE_TYPE_COMBINED_SAMPLER: number;
    static GLSLANG_RESOURCE_TYPE_IMAGE: number;
    static GLSLANG_RESOURCE_TYPE_SAMPLER: number;
    static GLSLANG_RESOURCE_TYPE_SSBO: number;
    static GLSLANG_RESOURCE_TYPE_TENSOR: number;
    static GLSLANG_RESOURCE_TYPE_TEXTURE: number;
    static GLSLANG_RESOURCE_TYPE_UAV: number;
    static GLSLANG_RESOURCE_TYPE_UBO: number;
    static GLSLANG_SHADER_AUTO_MAP_BINDINGS: number;
    static GLSLANG_SHADER_AUTO_MAP_LOCATIONS: number;
    static GLSLANG_SHADER_BINDINGS_PER_RESOURCE_TYPE: number;
    static GLSLANG_SHADER_DEFAULT_BIT: number;
    static GLSLANG_SHADER_VULKAN_RULES_RELAXED: number;
    static GLSLANG_SOURCE_GLSL: number;
    static GLSLANG_SOURCE_HLSL: number;
    static GLSLANG_SOURCE_NONE: number;
    static GLSLANG_STAGE_ANYHIT: number;
    static GLSLANG_STAGE_ANYHIT_MASK: number;
    static GLSLANG_STAGE_ANYHIT_NV: number;
    static GLSLANG_STAGE_ANYHIT_NV_MASK: number;
    static GLSLANG_STAGE_CALLABLE: number;
    static GLSLANG_STAGE_CALLABLE_MASK: number;
    static GLSLANG_STAGE_CALLABLE_NV: number;
    static GLSLANG_STAGE_CALLABLE_NV_MASK: number;
    static GLSLANG_STAGE_CLOSESTHIT: number;
    static GLSLANG_STAGE_CLOSESTHIT_MASK: number;
    static GLSLANG_STAGE_CLOSESTHIT_NV: number;
    static GLSLANG_STAGE_CLOSESTHIT_NV_MASK: number;
    static GLSLANG_STAGE_COMPUTE: number;
    static GLSLANG_STAGE_COMPUTE_MASK: number;
    static GLSLANG_STAGE_FRAGMENT: number;
    static GLSLANG_STAGE_FRAGMENT_MASK: number;
    static GLSLANG_STAGE_GEOMETRY: number;
    static GLSLANG_STAGE_GEOMETRY_MASK: number;
    static GLSLANG_STAGE_INTERSECT: number;
    static GLSLANG_STAGE_INTERSECT_MASK: number;
    static GLSLANG_STAGE_INTERSECT_NV: number;
    static GLSLANG_STAGE_INTERSECT_NV_MASK: number;
    static GLSLANG_STAGE_MESH: number;
    static GLSLANG_STAGE_MESH_MASK: number;
    static GLSLANG_STAGE_MESH_NV: number;
    static GLSLANG_STAGE_MESH_NV_MASK: number;
    static GLSLANG_STAGE_MISS: number;
    static GLSLANG_STAGE_MISS_MASK: number;
    static GLSLANG_STAGE_MISS_NV: number;
    static GLSLANG_STAGE_MISS_NV_MASK: number;
    static GLSLANG_STAGE_RAYGEN: number;
    static GLSLANG_STAGE_RAYGEN_MASK: number;
    static GLSLANG_STAGE_RAYGEN_NV: number;
    static GLSLANG_STAGE_RAYGEN_NV_MASK: number;
    static GLSLANG_STAGE_TASK: number;
    static GLSLANG_STAGE_TASK_MASK: number;
    static GLSLANG_STAGE_TASK_NV: number;
    static GLSLANG_STAGE_TASK_NV_MASK: number;
    static GLSLANG_STAGE_TESSCONTROL: number;
    static GLSLANG_STAGE_TESSCONTROL_MASK: number;
    static GLSLANG_STAGE_TESSEVALUATION: number;
    static GLSLANG_STAGE_TESSEVALUATION_MASK: number;
    static GLSLANG_STAGE_VERTEX: number;
    static GLSLANG_STAGE_VERTEX_MASK: number;
    static GLSLANG_TARGET_NONE: number;
    static GLSLANG_TARGET_OPENGL_450: number;
    static GLSLANG_TARGET_SPV: number;
    static GLSLANG_TARGET_SPV_1_0: number;
    static GLSLANG_TARGET_SPV_1_1: number;
    static GLSLANG_TARGET_SPV_1_2: number;
    static GLSLANG_TARGET_SPV_1_3: number;
    static GLSLANG_TARGET_SPV_1_4: number;
    static GLSLANG_TARGET_SPV_1_5: number;
    static GLSLANG_TARGET_SPV_1_6: number;
    static GLSLANG_TARGET_VULKAN_1_0: number;
    static GLSLANG_TARGET_VULKAN_1_1: number;
    static GLSLANG_TARGET_VULKAN_1_2: number;
    static GLSLANG_TARGET_VULKAN_1_3: number;
    static GLSLANG_TARGET_VULKAN_1_4: number;
    static GLSLANG_TEX_SAMP_TRANS_KEEP: number;
    static GLSLANG_TEX_SAMP_TRANS_UPGRADE_TEXTURE_REMOVE_SAMPLER: number;
    static getLibrary(): SharedLibrary;
    static glslang_finalize_process(): void;
    static glslang_get_version(paramarg0: GLSLangVersion): void;
    static glslang_glsl_mapper_create(): number;
    static glslang_glsl_mapper_delete(paramarg0: number): void;
    static glslang_glsl_resolver_create(paramarg0: number, paramarg1: number): number;
    static glslang_glsl_resolver_delete(paramarg0: number): void;
    static glslang_initialize_process(): boolean;
    static glslang_program_SPIRV_generate(paramarg0: number, paramarg1: number): void;
    static glslang_program_SPIRV_generate_with_options(paramarg0: number, paramarg1: number, paramarg2: GLSLangSPVOptions): void;
    static glslang_program_SPIRV_get(paramarg0: number, paramarg1: IntBuffer): void;
    static glslang_program_SPIRV_get_messages(paramarg0: number): string;
    static glslang_program_SPIRV_get_ptr(paramarg0: number): IntBuffer;
    static glslang_program_SPIRV_get_ptr(paramarg0: number, paramarg1: number): IntBuffer;
    static glslang_program_SPIRV_get_size(paramarg0: number): number;
    static glslang_program_add_shader(paramarg0: number, paramarg1: number): void;
    static glslang_program_add_source_text(paramarg0: number, paramarg1: number, paramarg2: CharSequence): void;
    static glslang_program_add_source_text(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer): void;
    static glslang_program_create(): number;
    static glslang_program_delete(paramarg0: number): void;
    static glslang_program_get_info_debug_log(paramarg0: number): string;
    static glslang_program_get_info_log(paramarg0: number): string;
    static glslang_program_link(paramarg0: number, paramarg1: number): boolean;
    static glslang_program_map_io(paramarg0: number): boolean;
    static glslang_program_map_io_with_resolver_and_mapper(paramarg0: number, paramarg1: number, paramarg2: number): boolean;
    static glslang_program_set_source_file(paramarg0: number, paramarg1: number, paramarg2: CharSequence): void;
    static glslang_program_set_source_file(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer): void;
    static glslang_shader_create(paramarg0: GLSLangInput): number;
    static glslang_shader_delete(paramarg0: number): void;
    static glslang_shader_get_info_debug_log(paramarg0: number): string;
    static glslang_shader_get_info_log(paramarg0: number): string;
    static glslang_shader_get_preprocessed_code(paramarg0: number): string;
    static glslang_shader_parse(paramarg0: number, paramarg1: GLSLangInput): boolean;
    static glslang_shader_preprocess(paramarg0: number, paramarg1: GLSLangInput): boolean;
    static glslang_shader_set_default_uniform_block_name(paramarg0: number, paramarg1: CharSequence): void;
    static glslang_shader_set_default_uniform_block_name(paramarg0: number, paramarg1: ByteBuffer): void;
    static glslang_shader_set_default_uniform_block_set_and_binding(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glslang_shader_set_entry_point(paramarg0: number, paramarg1: CharSequence): void;
    static glslang_shader_set_entry_point(paramarg0: number, paramarg1: ByteBuffer): void;
    static glslang_shader_set_glsl_version(paramarg0: number, paramarg1: number): void;
    static glslang_shader_set_invert_y(paramarg0: number, paramarg1: boolean): void;
    static glslang_shader_set_options(paramarg0: number, paramarg1: number): void;
    static glslang_shader_set_preamble(paramarg0: number, paramarg1: CharSequence): void;
    static glslang_shader_set_preamble(paramarg0: number, paramarg1: ByteBuffer): void;
    static glslang_shader_set_preprocessed_code(paramarg0: number, paramarg1: CharSequence): void;
    static glslang_shader_set_preprocessed_code(paramarg0: number, paramarg1: ByteBuffer): void;
    static glslang_shader_set_resource_set_binding(paramarg0: number, paramarg1: PointerBuffer): void;
    static glslang_shader_shift_binding(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glslang_shader_shift_binding_for_set(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglslang_get_version(paramarg0: number): void;
    static nglslang_program_SPIRV_generate_with_options(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglslang_program_SPIRV_get(paramarg0: number, paramarg1: number): void;
    static nglslang_program_SPIRV_get_messages(paramarg0: number): number;
    static nglslang_program_SPIRV_get_ptr(paramarg0: number): number;
    static nglslang_program_add_source_text(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglslang_program_get_info_debug_log(paramarg0: number): number;
    static nglslang_program_get_info_log(paramarg0: number): number;
    static nglslang_program_set_source_file(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglslang_shader_create(paramarg0: number): number;
    static nglslang_shader_get_info_debug_log(paramarg0: number): number;
    static nglslang_shader_get_info_log(paramarg0: number): number;
    static nglslang_shader_get_preprocessed_code(paramarg0: number): number;
    static nglslang_shader_parse(paramarg0: number, paramarg1: number): number;
    static nglslang_shader_preprocess(paramarg0: number, paramarg1: number): number;
    static nglslang_shader_set_default_uniform_block_name(paramarg0: number, paramarg1: number): void;
    static nglslang_shader_set_entry_point(paramarg0: number, paramarg1: number): void;
    static nglslang_shader_set_preamble(paramarg0: number, paramarg1: number): void;
    static nglslang_shader_set_preprocessed_code(paramarg0: number, paramarg1: number): void;
    static nglslang_shader_set_resource_set_binding(paramarg0: number, paramarg1: number, paramarg2: number): void;
    constructor()
}