import type { Object } from '../../../../java/lang/Object.d.ts'
export class Shaderc$Functions extends Object {
    static assemble_into_spv: number;
    static compile_into_preprocessed_text: number;
    static compile_into_spv: number;
    static compile_into_spv_assembly: number;
    static compile_options_add_macro_definition: number;
    static compile_options_clone: number;
    static compile_options_initialize: number;
    static compile_options_release: number;
    static compile_options_set_auto_bind_uniforms: number;
    static compile_options_set_auto_combined_image_sampler: number;
    static compile_options_set_auto_map_locations: number;
    static compile_options_set_binding_base: number;
    static compile_options_set_binding_base_for_stage: number;
    static compile_options_set_forced_version_profile: number;
    static compile_options_set_generate_debug_info: number;
    static compile_options_set_hlsl_16bit_types: number;
    static compile_options_set_hlsl_functionality1: number;
    static compile_options_set_hlsl_io_mapping: number;
    static compile_options_set_hlsl_offsets: number;
    static compile_options_set_hlsl_register_set_and_binding: number;
    static compile_options_set_hlsl_register_set_and_binding_for_stage: number;
    static compile_options_set_include_callbacks: number;
    static compile_options_set_invert_y: number;
    static compile_options_set_limit: number;
    static compile_options_set_max_id_bound: number;
    static compile_options_set_nan_clamp: number;
    static compile_options_set_optimization_level: number;
    static compile_options_set_preserve_bindings: number;
    static compile_options_set_source_language: number;
    static compile_options_set_suppress_warnings: number;
    static compile_options_set_target_env: number;
    static compile_options_set_target_spirv: number;
    static compile_options_set_vulkan_rules_relaxed: number;
    static compile_options_set_warnings_as_errors: number;
    static compiler_initialize: number;
    static compiler_release: number;
    static get_spv_version: number;
    static parse_version_profile: number;
    static result_get_bytes: number;
    static result_get_compilation_status: number;
    static result_get_error_message: number;
    static result_get_length: number;
    static result_get_num_errors: number;
    static result_get_num_warnings: number;
    static result_release: number;
    private constructor()
}