import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { IntBuffer } from '../../../../java/nio/IntBuffer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../../java/lang/CharSequence.d.ts'
import type { PointerBuffer } from '../../../../org/lwjgl/PointerBuffer.d.ts'
import type { SharedLibrary } from '../../../../org/lwjgl/system/SharedLibrary.d.ts'
import type { SPVBinary } from '../../../../org/lwjgl/util/shaderc/SPVBinary.d.ts'
import type { SPVDiagnostic } from '../../../../org/lwjgl/util/shaderc/SPVDiagnostic.d.ts'
import type { SPVParsedHeaderFnI } from '../../../../org/lwjgl/util/shaderc/SPVParsedHeaderFnI.d.ts'
import type { SPVParsedInstructionFnI } from '../../../../org/lwjgl/util/shaderc/SPVParsedInstructionFnI.d.ts'
import type { SPVPosition } from '../../../../org/lwjgl/util/shaderc/SPVPosition.d.ts'
import type { SPVText } from '../../../../org/lwjgl/util/shaderc/SPVText.d.ts'
export class SPV extends Object {
    static SPV_BINARY_TO_TEXT_OPTION_COLOR: number;
    static SPV_BINARY_TO_TEXT_OPTION_COMMENT: number;
    static SPV_BINARY_TO_TEXT_OPTION_FRIENDLY_NAMES: number;
    static SPV_BINARY_TO_TEXT_OPTION_INDENT: number;
    static SPV_BINARY_TO_TEXT_OPTION_NESTED_INDENT: number;
    static SPV_BINARY_TO_TEXT_OPTION_NONE: number;
    static SPV_BINARY_TO_TEXT_OPTION_NO_HEADER: number;
    static SPV_BINARY_TO_TEXT_OPTION_PRINT: number;
    static SPV_BINARY_TO_TEXT_OPTION_REORDER_BLOCKS: number;
    static SPV_BINARY_TO_TEXT_OPTION_SHOW_BYTE_OFFSET: number;
    static SPV_ENDIANNESS_BIG: number;
    static SPV_ENDIANNESS_LITTLE: number;
    static SPV_END_OF_STREAM: number;
    static SPV_ENV_OPENCL_1_2: number;
    static SPV_ENV_OPENCL_2_0: number;
    static SPV_ENV_OPENCL_2_1: number;
    static SPV_ENV_OPENCL_2_2: number;
    static SPV_ENV_OPENCL_EMBEDDED_1_2: number;
    static SPV_ENV_OPENCL_EMBEDDED_2_0: number;
    static SPV_ENV_OPENCL_EMBEDDED_2_1: number;
    static SPV_ENV_OPENCL_EMBEDDED_2_2: number;
    static SPV_ENV_OPENGL_4_0: number;
    static SPV_ENV_OPENGL_4_1: number;
    static SPV_ENV_OPENGL_4_2: number;
    static SPV_ENV_OPENGL_4_3: number;
    static SPV_ENV_OPENGL_4_5: number;
    static SPV_ENV_UNIVERSAL_1_0: number;
    static SPV_ENV_UNIVERSAL_1_1: number;
    static SPV_ENV_UNIVERSAL_1_2: number;
    static SPV_ENV_UNIVERSAL_1_3: number;
    static SPV_ENV_UNIVERSAL_1_4: number;
    static SPV_ENV_UNIVERSAL_1_5: number;
    static SPV_ENV_UNIVERSAL_1_6: number;
    static SPV_ENV_VULKAN_1_0: number;
    static SPV_ENV_VULKAN_1_1: number;
    static SPV_ENV_VULKAN_1_1_SPIRV_1_4: number;
    static SPV_ENV_VULKAN_1_2: number;
    static SPV_ENV_VULKAN_1_3: number;
    static SPV_ENV_VULKAN_1_4: number;
    static SPV_ENV_WEBGPU_0: number;
    static SPV_ERROR_FNVAR: number;
    static SPV_ERROR_INTERNAL: number;
    static SPV_ERROR_INVALID_BINARY: number;
    static SPV_ERROR_INVALID_CAPABILITY: number;
    static SPV_ERROR_INVALID_CFG: number;
    static SPV_ERROR_INVALID_DATA: number;
    static SPV_ERROR_INVALID_DIAGNOSTIC: number;
    static SPV_ERROR_INVALID_ID: number;
    static SPV_ERROR_INVALID_LAYOUT: number;
    static SPV_ERROR_INVALID_LOOKUP: number;
    static SPV_ERROR_INVALID_POINTER: number;
    static SPV_ERROR_INVALID_TABLE: number;
    static SPV_ERROR_INVALID_TEXT: number;
    static SPV_ERROR_INVALID_VALUE: number;
    static SPV_ERROR_MISSING_EXTENSION: number;
    static SPV_ERROR_OUT_OF_MEMORY: number;
    static SPV_ERROR_WRONG_VERSION: number;
    static SPV_EXT_INST_TYPE_ARM_MOTION_ENGINE_100: number;
    static SPV_EXT_INST_TYPE_DEBUGINFO: number;
    static SPV_EXT_INST_TYPE_GLSL_STD_450: number;
    static SPV_EXT_INST_TYPE_NONE: number;
    static SPV_EXT_INST_TYPE_NONSEMANTIC_CLSPVREFLECTION: number;
    static SPV_EXT_INST_TYPE_NONSEMANTIC_SHADER_DEBUGINFO_100: number;
    static SPV_EXT_INST_TYPE_NONSEMANTIC_UNKNOWN: number;
    static SPV_EXT_INST_TYPE_NONSEMANTIC_VKSPREFLECTION: number;
    static SPV_EXT_INST_TYPE_OPENCL_DEBUGINFO_100: number;
    static SPV_EXT_INST_TYPE_OPENCL_STD: number;
    static SPV_EXT_INST_TYPE_SPV_AMD_GCN_SHADER: number;
    static SPV_EXT_INST_TYPE_SPV_AMD_SHADER_BALLOT: number;
    static SPV_EXT_INST_TYPE_SPV_AMD_SHADER_EXPLICIT_VERTEX_PARAMETER: number;
    static SPV_EXT_INST_TYPE_SPV_AMD_SHADER_TRINARY_MINMAX: number;
    static SPV_EXT_INST_TYPE_TOSA_001000_1: number;
    static SPV_FAILED_MATCH: number;
    static SPV_FP_ENCODING_BFLOAT16: number;
    static SPV_FP_ENCODING_FLOAT8_E4M3: number;
    static SPV_FP_ENCODING_FLOAT8_E5M2: number;
    static SPV_FP_ENCODING_IEEE754_BINARY16: number;
    static SPV_FP_ENCODING_IEEE754_BINARY32: number;
    static SPV_FP_ENCODING_IEEE754_BINARY64: number;
    static SPV_FP_ENCODING_UNKNOWN: number;
    static SPV_MSG_DEBUG: number;
    static SPV_MSG_ERROR: number;
    static SPV_MSG_FATAL: number;
    static SPV_MSG_INFO: number;
    static SPV_MSG_INTERNAL_ERROR: number;
    static SPV_MSG_WARNING: number;
    static SPV_NUMBER_FLOATING: number;
    static SPV_NUMBER_NONE: number;
    static SPV_NUMBER_SIGNED_INT: number;
    static SPV_NUMBER_UNSIGNED_INT: number;
    static SPV_OPERAND_TYPE_ACCESS_QUALIFIER: number;
    static SPV_OPERAND_TYPE_ADDRESSING_MODEL: number;
    static SPV_OPERAND_TYPE_BUILT_IN: number;
    static SPV_OPERAND_TYPE_CAPABILITY: number;
    static SPV_OPERAND_TYPE_CLDEBUG100_DEBUG_BASE_TYPE_ATTRIBUTE_ENCODING: number;
    static SPV_OPERAND_TYPE_CLDEBUG100_DEBUG_COMPOSITE_TYPE: number;
    static SPV_OPERAND_TYPE_CLDEBUG100_DEBUG_IMPORTED_ENTITY: number;
    static SPV_OPERAND_TYPE_CLDEBUG100_DEBUG_INFO_FLAGS: number;
    static SPV_OPERAND_TYPE_CLDEBUG100_DEBUG_OPERATION: number;
    static SPV_OPERAND_TYPE_CLDEBUG100_DEBUG_TYPE_QUALIFIER: number;
    static SPV_OPERAND_TYPE_COMPONENT_TYPE: number;
    static SPV_OPERAND_TYPE_COOPERATIVE_MATRIX_LAYOUT: number;
    static SPV_OPERAND_TYPE_COOPERATIVE_MATRIX_OPERANDS: number;
    static SPV_OPERAND_TYPE_COOPERATIVE_MATRIX_REDUCE: number;
    static SPV_OPERAND_TYPE_COOPERATIVE_MATRIX_USE: number;
    static SPV_OPERAND_TYPE_COOPERATIVE_VECTOR_MATRIX_LAYOUT: number;
    static SPV_OPERAND_TYPE_DEBUG_BASE_TYPE_ATTRIBUTE_ENCODING: number;
    static SPV_OPERAND_TYPE_DEBUG_COMPOSITE_TYPE: number;
    static SPV_OPERAND_TYPE_DEBUG_INFO_FLAGS: number;
    static SPV_OPERAND_TYPE_DEBUG_OPERATION: number;
    static SPV_OPERAND_TYPE_DEBUG_TYPE_QUALIFIER: number;
    static SPV_OPERAND_TYPE_DECORATION: number;
    static SPV_OPERAND_TYPE_DIMENSIONALITY: number;
    static SPV_OPERAND_TYPE_EXECUTION_MODE: number;
    static SPV_OPERAND_TYPE_EXECUTION_MODEL: number;
    static SPV_OPERAND_TYPE_EXTENSION_INSTRUCTION_NUMBER: number;
    static SPV_OPERAND_TYPE_FPDENORM_MODE: number;
    static SPV_OPERAND_TYPE_FPENCODING: number;
    static SPV_OPERAND_TYPE_FPOPERATION_MODE: number;
    static SPV_OPERAND_TYPE_FP_FAST_MATH_MODE: number;
    static SPV_OPERAND_TYPE_FP_ROUNDING_MODE: number;
    static SPV_OPERAND_TYPE_FRAGMENT_SHADING_RATE: number;
    static SPV_OPERAND_TYPE_FUNCTION_CONTROL: number;
    static SPV_OPERAND_TYPE_FUNCTION_PARAMETER_ATTRIBUTE: number;
    static SPV_OPERAND_TYPE_GROUP_OPERATION: number;
    static SPV_OPERAND_TYPE_HOST_ACCESS_QUALIFIER: number;
    static SPV_OPERAND_TYPE_ID: number;
    static SPV_OPERAND_TYPE_IMAGE: number;
    static SPV_OPERAND_TYPE_IMAGE_CHANNEL_DATA_TYPE: number;
    static SPV_OPERAND_TYPE_IMAGE_CHANNEL_ORDER: number;
    static SPV_OPERAND_TYPE_INITIALIZATION_MODE_QUALIFIER: number;
    static SPV_OPERAND_TYPE_KERNEL_ENQ_FLAGS: number;
    static SPV_OPERAND_TYPE_KERNEL_PROFILING_INFO: number;
    static SPV_OPERAND_TYPE_KERNEL_PROPERTY_FLAGS: number;
    static SPV_OPERAND_TYPE_LINKAGE_TYPE: number;
    static SPV_OPERAND_TYPE_LITERAL_FLOAT: number;
    static SPV_OPERAND_TYPE_LITERAL_INTEGER: number;
    static SPV_OPERAND_TYPE_LITERAL_STRING: number;
    static SPV_OPERAND_TYPE_LOAD_CACHE_CONTROL: number;
    static SPV_OPERAND_TYPE_LOOP_CONTROL: number;
    static SPV_OPERAND_TYPE_MATRIX_MULTIPLY_ACCUMULATE_OPERANDS: number;
    static SPV_OPERAND_TYPE_MEMORY_ACCESS: number;
    static SPV_OPERAND_TYPE_MEMORY_MODEL: number;
    static SPV_OPERAND_TYPE_MEMORY_SEMANTICS_ID: number;
    static SPV_OPERAND_TYPE_NAMED_MAXIMUM_NUMBER_OF_REGISTERS: number;
    static SPV_OPERAND_TYPE_NONE: number;
    static SPV_OPERAND_TYPE_NUM_OPERAND_TYPES: number;
    static SPV_OPERAND_TYPE_OPTIONAL_ACCESS_QUALIFIER: number;
    static SPV_OPERAND_TYPE_OPTIONAL_CAPABILITY: number;
    static SPV_OPERAND_TYPE_OPTIONAL_CIV: number;
    static SPV_OPERAND_TYPE_OPTIONAL_COOPERATIVE_MATRIX_OPERANDS: number;
    static SPV_OPERAND_TYPE_OPTIONAL_FPENCODING: number;
    static SPV_OPERAND_TYPE_OPTIONAL_ID: number;
    static SPV_OPERAND_TYPE_OPTIONAL_IMAGE: number;
    static SPV_OPERAND_TYPE_OPTIONAL_LITERAL_INTEGER: number;
    static SPV_OPERAND_TYPE_OPTIONAL_LITERAL_NUMBER: number;
    static SPV_OPERAND_TYPE_OPTIONAL_LITERAL_STRING: number;
    static SPV_OPERAND_TYPE_OPTIONAL_MATRIX_MULTIPLY_ACCUMULATE_OPERANDS: number;
    static SPV_OPERAND_TYPE_OPTIONAL_MEMORY_ACCESS: number;
    static SPV_OPERAND_TYPE_OPTIONAL_PACKED_VECTOR_FORMAT: number;
    static SPV_OPERAND_TYPE_OPTIONAL_RAW_ACCESS_CHAIN_OPERANDS: number;
    static SPV_OPERAND_TYPE_OPTIONAL_TENSOR_OPERANDS: number;
    static SPV_OPERAND_TYPE_OPTIONAL_TYPED_LITERAL_INTEGER: number;
    static SPV_OPERAND_TYPE_OVERFLOW_MODES: number;
    static SPV_OPERAND_TYPE_PACKED_VECTOR_FORMAT: number;
    static SPV_OPERAND_TYPE_QUANTIZATION_MODES: number;
    static SPV_OPERAND_TYPE_RAW_ACCESS_CHAIN_OPERANDS: number;
    static SPV_OPERAND_TYPE_RAY_FLAGS: number;
    static SPV_OPERAND_TYPE_RAY_QUERY_CANDIDATE_INTERSECTION_TYPE: number;
    static SPV_OPERAND_TYPE_RAY_QUERY_COMMITTED_INTERSECTION_TYPE: number;
    static SPV_OPERAND_TYPE_RAY_QUERY_INTERSECTION: number;
    static SPV_OPERAND_TYPE_RESULT_ID: number;
    static SPV_OPERAND_TYPE_SAMPLER_ADDRESSING_MODE: number;
    static SPV_OPERAND_TYPE_SAMPLER_FILTER_MODE: number;
    static SPV_OPERAND_TYPE_SAMPLER_IMAGE_FORMAT: number;
    static SPV_OPERAND_TYPE_SCOPE_ID: number;
    static SPV_OPERAND_TYPE_SELECTION_CONTROL: number;
    static SPV_OPERAND_TYPE_SHDEBUG100_BUILD_IDENTIFIER_FLAGS: number;
    static SPV_OPERAND_TYPE_SHDEBUG100_DEBUG_BASE_TYPE_ATTRIBUTE_ENCODING: number;
    static SPV_OPERAND_TYPE_SHDEBUG100_DEBUG_COMPOSITE_TYPE: number;
    static SPV_OPERAND_TYPE_SHDEBUG100_DEBUG_IMPORTED_ENTITY: number;
    static SPV_OPERAND_TYPE_SHDEBUG100_DEBUG_INFO_FLAGS: number;
    static SPV_OPERAND_TYPE_SHDEBUG100_DEBUG_OPERATION: number;
    static SPV_OPERAND_TYPE_SHDEBUG100_DEBUG_TYPE_QUALIFIER: number;
    static SPV_OPERAND_TYPE_SOURCE_LANGUAGE: number;
    static SPV_OPERAND_TYPE_SPEC_CONSTANT_OP_NUMBER: number;
    static SPV_OPERAND_TYPE_STORAGE_CLASS: number;
    static SPV_OPERAND_TYPE_STORE_CACHE_CONTROL: number;
    static SPV_OPERAND_TYPE_TENSOR_ADDRESSING_OPERANDS: number;
    static SPV_OPERAND_TYPE_TENSOR_CLAMP_MODE: number;
    static SPV_OPERAND_TYPE_TENSOR_OPERANDS: number;
    static SPV_OPERAND_TYPE_TYPED_LITERAL_NUMBER: number;
    static SPV_OPERAND_TYPE_TYPE_ID: number;
    static SPV_OPERAND_TYPE_VARIABLE_CAPABILITY: number;
    static SPV_OPERAND_TYPE_VARIABLE_ID: number;
    static SPV_OPERAND_TYPE_VARIABLE_ID_LITERAL_INTEGER: number;
    static SPV_OPERAND_TYPE_VARIABLE_LITERAL_INTEGER: number;
    static SPV_OPERAND_TYPE_VARIABLE_LITERAL_INTEGER_ID: number;
    static SPV_REQUESTED_TERMINATION: number;
    static SPV_SUCCESS: number;
    static SPV_TEXT_TO_BINARY_OPTION_NONE: number;
    static SPV_TEXT_TO_BINARY_OPTION_PRESERVE_NUMERIC_IDS: number;
    static SPV_UNSUPPORTED: number;
    static SPV_WARNING: number;
    static kDefaultMaxIdBound: number;
    static spv_validator_limit_max_access_chain_indexes: number;
    static spv_validator_limit_max_control_flow_nesting_depth: number;
    static spv_validator_limit_max_function_args: number;
    static spv_validator_limit_max_global_variables: number;
    static spv_validator_limit_max_id_bound: number;
    static spv_validator_limit_max_local_variables: number;
    static spv_validator_limit_max_struct_depth: number;
    static spv_validator_limit_max_struct_members: number;
    static spv_validator_limit_max_switch_branches: number;
    static getLibrary(): SharedLibrary;
    static nspvBinaryDestroy(paramarg0: number): void;
    static nspvBinaryParse(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): number;
    static nspvBinaryToText(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): number;
    static nspvDiagnosticCreate(paramarg0: number, paramarg1: number): number;
    static nspvDiagnosticDestroy(paramarg0: number): void;
    static nspvDiagnosticPrint(paramarg0: number): number;
    static nspvOpcodeString(paramarg0: number): number;
    static nspvParseTargetEnv(paramarg0: number, paramarg1: number): boolean;
    static nspvParseVulkanEnv(paramarg0: number, paramarg1: number, paramarg2: number): boolean;
    static nspvSoftwareVersionDetailsString(): number;
    static nspvSoftwareVersionString(): number;
    static nspvTargetEnvDescription(paramarg0: number): number;
    static nspvTextDestroy(paramarg0: number): void;
    static nspvTextToBinary(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nspvTextToBinaryWithOptions(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): number;
    static nspvValidate(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nspvValidateBinary(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nspvValidateWithOptions(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static spvBinaryDestroy(paramarg0: SPVBinary): void;
    static spvBinaryParse(paramarg0: number, paramarg1: number, paramarg2: IntBuffer, paramarg3: (param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number) => number, paramarg4: (param0: number, param1: number) => number, paramarg5: PointerBuffer): number;
    static spvBinaryToText(paramarg0: number, paramarg1: IntBuffer, paramarg2: number, paramarg3: PointerBuffer, paramarg4: PointerBuffer): number;
    static spvContextCreate(paramarg0: number): number;
    static spvContextDestroy(paramarg0: number): void;
    static spvDiagnosticCreate(paramarg0: SPVPosition, paramarg1: CharSequence): SPVDiagnostic;
    static spvDiagnosticCreate(paramarg0: SPVPosition, paramarg1: ByteBuffer): SPVDiagnostic;
    static spvDiagnosticDestroy(paramarg0: SPVDiagnostic): void;
    static spvDiagnosticPrint(paramarg0: SPVDiagnostic): number;
    static spvFuzzerOptionsCreate(): number;
    static spvFuzzerOptionsDestroy(paramarg0: number): void;
    static spvFuzzerOptionsEnableAllPasses(paramarg0: number): void;
    static spvFuzzerOptionsEnableFuzzerPassValidation(paramarg0: number): void;
    static spvFuzzerOptionsEnableReplayValidation(paramarg0: number): void;
    static spvFuzzerOptionsSetRandomSeed(paramarg0: number, paramarg1: number): void;
    static spvFuzzerOptionsSetReplayRange(paramarg0: number, paramarg1: number): void;
    static spvFuzzerOptionsSetShrinkerStepLimit(paramarg0: number, paramarg1: number): void;
    static spvOpcodeString(paramarg0: number): string;
    static spvOptimizerOptionsCreate(): number;
    static spvOptimizerOptionsDestroy(paramarg0: number): void;
    static spvOptimizerOptionsSetMaxIdBound(paramarg0: number, paramarg1: number): void;
    static spvOptimizerOptionsSetPreserveBindings(paramarg0: number, paramarg1: boolean): void;
    static spvOptimizerOptionsSetPreserveSpecConstants(paramarg0: number, paramarg1: boolean): void;
    static spvOptimizerOptionsSetRunValidator(paramarg0: number, paramarg1: boolean): void;
    static spvOptimizerOptionsSetValidatorOptions(paramarg0: number, paramarg1: number): void;
    static spvParseTargetEnv(paramarg0: CharSequence, paramarg1: IntBuffer): boolean;
    static spvParseTargetEnv(paramarg0: ByteBuffer, paramarg1: IntBuffer): boolean;
    static spvParseVulkanEnv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): boolean;
    static spvReducerOptionsCreate(): number;
    static spvReducerOptionsDestroy(paramarg0: number): void;
    static spvReducerOptionsSetFailOnValidationError(paramarg0: number, paramarg1: boolean): void;
    static spvReducerOptionsSetStepLimit(paramarg0: number, paramarg1: number): void;
    static spvReducerOptionsSetTargetFunction(paramarg0: number, paramarg1: number): void;
    static spvSoftwareVersionDetailsString(): string;
    static spvSoftwareVersionString(): string;
    static spvTargetEnvDescription(paramarg0: number): string;
    static spvTextDestroy(paramarg0: SPVText): void;
    static spvTextToBinary(paramarg0: number, paramarg1: CharSequence, paramarg2: PointerBuffer, paramarg3: PointerBuffer): number;
    static spvTextToBinary(paramarg0: number, paramarg1: ByteBuffer, paramarg2: PointerBuffer, paramarg3: PointerBuffer): number;
    static spvTextToBinaryWithOptions(paramarg0: number, paramarg1: CharSequence, paramarg2: number, paramarg3: PointerBuffer, paramarg4: PointerBuffer): number;
    static spvTextToBinaryWithOptions(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: PointerBuffer, paramarg4: PointerBuffer): number;
    static spvValidate(paramarg0: number, paramarg1: SPVBinary, paramarg2: PointerBuffer): number;
    static spvValidateBinary(paramarg0: number, paramarg1: IntBuffer, paramarg2: PointerBuffer): number;
    static spvValidateWithOptions(paramarg0: number, paramarg1: number, paramarg2: SPVBinary, paramarg3: PointerBuffer): number;
    static spvValidatorOptionsCreate(): number;
    static spvValidatorOptionsDestroy(paramarg0: number): void;
    static spvValidatorOptionsSetAllowLocalSizeId(paramarg0: number, paramarg1: boolean): void;
    static spvValidatorOptionsSetAllowOffsetTextureOperand(paramarg0: number, paramarg1: boolean): void;
    static spvValidatorOptionsSetAllowVulkan32BitBitwise(paramarg0: number, paramarg1: boolean): void;
    static spvValidatorOptionsSetBeforeHlslLegalization(paramarg0: number, paramarg1: boolean): void;
    static spvValidatorOptionsSetFriendlyNames(paramarg0: number, paramarg1: boolean): void;
    static spvValidatorOptionsSetRelaxBlockLayout(paramarg0: number, paramarg1: boolean): void;
    static spvValidatorOptionsSetRelaxLogicalPointer(paramarg0: number, paramarg1: boolean): void;
    static spvValidatorOptionsSetRelaxStoreStruct(paramarg0: number, paramarg1: boolean): void;
    static spvValidatorOptionsSetScalarBlockLayout(paramarg0: number, paramarg1: boolean): void;
    static spvValidatorOptionsSetSkipBlockLayout(paramarg0: number, paramarg1: boolean): void;
    static spvValidatorOptionsSetUniformBufferStandardLayout(paramarg0: number, paramarg1: boolean): void;
    static spvValidatorOptionsSetUniversalLimit(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static spvValidatorOptionsSetWorkgroupScalarBlockLayout(paramarg0: number, paramarg1: boolean): void;
    constructor()
}