import type { SCSU } from '../../../../com/ibm/icu/text/SCSU.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
export class UnicodeCompressor extends Object implements SCSU {
    static ARMENIANINDEX: number;
    static COMPRESSIONOFFSET: number;
    static GREEKINDEX: number;
    static HALFWIDTHKATAKANAINDEX: number;
    static HIRAGANAINDEX: number;
    static INVALIDCHAR: number;
    static INVALIDWINDOW: number;
    static IPAEXTENSIONINDEX: number;
    static KATAKANAINDEX: number;
    static LATININDEX: number;
    static MAXINDEX: number;
    static NUMSTATICWINDOWS: number;
    static NUMWINDOWS: number;
    static RESERVEDINDEX: number;
    static SCHANGE0: number;
    static SCHANGE1: number;
    static SCHANGE2: number;
    static SCHANGE3: number;
    static SCHANGE4: number;
    static SCHANGE5: number;
    static SCHANGE6: number;
    static SCHANGE7: number;
    static SCHANGEU: number;
    static SDEFINE0: number;
    static SDEFINE1: number;
    static SDEFINE2: number;
    static SDEFINE3: number;
    static SDEFINE4: number;
    static SDEFINE5: number;
    static SDEFINE6: number;
    static SDEFINE7: number;
    static SDEFINEX: number;
    static SINGLEBYTEMODE: number;
    static SQUOTE0: number;
    static SQUOTE1: number;
    static SQUOTE2: number;
    static SQUOTE3: number;
    static SQUOTE4: number;
    static SQUOTE5: number;
    static SQUOTE6: number;
    static SQUOTE7: number;
    static SQUOTEU: number;
    static SRESERVED: number;
    static UCHANGE0: number;
    static UCHANGE1: number;
    static UCHANGE2: number;
    static UCHANGE3: number;
    static UCHANGE4: number;
    static UCHANGE5: number;
    static UCHANGE6: number;
    static UCHANGE7: number;
    static UDEFINE0: number;
    static UDEFINE1: number;
    static UDEFINE2: number;
    static UDEFINE3: number;
    static UDEFINE4: number;
    static UDEFINE5: number;
    static UDEFINE6: number;
    static UDEFINE7: number;
    static UDEFINEX: number;
    static UNICODEMODE: number;
    static UQUOTEU: number;
    static URESERVED: number;
    static sOffsetTable: number[];
    static sOffsets: number[];
    static compress(paramarg0: string[], paramarg1: number, paramarg2: number): number[];
    static compress(paramarg0: string): number[];
    constructor()
    // private fCurrentWindow: number;
    // private fIndexCount: number[];
    // private fMode: number;
    // private fOffsets: number[];
    // private fTimeStamp: number;
    // private fTimeStamps: number[];
    compress(arg0: string[], arg1: number, arg2: number, arg3: number[], arg4: number[], arg5: number, arg6: number): number;
    // private findDynamicWindow(arg0: number): number;
    // private getLRDefinedWindow(): number;
    // private inDynamicWindow(arg0: number, arg1: number): boolean;
    reset(): void;
}