import type { Class } from '../../../../java/lang/Class.d.ts'
import type { BitSet } from '../../../../java/util/BitSet.d.ts'
import type { Comparator } from '../../../../java/util/Comparator.d.ts'
import type { Random } from '../../../../java/util/Random.d.ts'
import type { Function } from '../../../../java/util/function/Function.d.ts'
import type { IntFunction } from '../../../../java/util/function/IntFunction.d.ts'
import type { Supplier } from '../../../../java/util/function/Supplier.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
export class ArrayUtils extends Object {
    static EMPTY_BOOLEAN_ARRAY: (Object | null)[];
    static EMPTY_BOOLEAN_OBJECT_ARRAY: (Object | null)[];
    static EMPTY_BYTE_ARRAY: number[];
    static EMPTY_BYTE_OBJECT_ARRAY: (Object | null)[];
    static EMPTY_CHARACTER_OBJECT_ARRAY: (Object | null)[];
    static EMPTY_CHAR_ARRAY: string[];
    static EMPTY_CLASS_ARRAY: Object | null;
    static EMPTY_DOUBLE_ARRAY: number[];
    static EMPTY_DOUBLE_OBJECT_ARRAY: (Object | null)[];
    static EMPTY_FIELD_ARRAY: (Object | null)[];
    static EMPTY_FLOAT_ARRAY: number[];
    static EMPTY_FLOAT_OBJECT_ARRAY: (Object | null)[];
    static EMPTY_INTEGER_OBJECT_ARRAY: (Object | null)[];
    static EMPTY_INT_ARRAY: number[];
    static EMPTY_LONG_ARRAY: number[];
    static EMPTY_LONG_OBJECT_ARRAY: (Object | null)[];
    static EMPTY_METHOD_ARRAY: (Object | null)[];
    static EMPTY_OBJECT_ARRAY: (Object | null)[];
    static EMPTY_SHORT_ARRAY: number[];
    static EMPTY_SHORT_OBJECT_ARRAY: (Object | null)[];
    static EMPTY_STRING_ARRAY: (Object | null)[];
    static EMPTY_THROWABLE_ARRAY: (Object | null)[];
    static EMPTY_TYPE_ARRAY: (Object | null)[];
    static INDEX_NOT_FOUND: number;
    static SOFT_MAX_ARRAY_LENGTH: number;
    static add(paramarg0: Object | null, paramarg1: Object | null): Object | null;
    static add(paramarg0: Object | null, paramarg1: number, paramarg2: Object | null): Object | null;
    static add(paramarg0: (Object | null)[], paramarg1: boolean): (Object | null)[];
    static add(paramarg0: (Object | null)[], paramarg1: number, paramarg2: boolean): (Object | null)[];
    static add(paramarg0: number[], paramarg1: number): number[];
    static add(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static add(paramarg0: string[], paramarg1: string): string[];
    static add(paramarg0: string[], paramarg1: number, paramarg2: string): string[];
    static add(paramarg0: number[], paramarg1: number): number[];
    static add(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static add(paramarg0: number[], paramarg1: number): number[];
    static add(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static add(paramarg0: number[], paramarg1: number): number[];
    static add(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static add(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static add(paramarg0: number[], paramarg1: number): number[];
    static add(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static add(paramarg0: number[], paramarg1: number): number[];
    static addAll(paramarg0: Object | null, paramarg1: Object | null): Object | null;
    static addAll(paramarg0: (Object | null)[], paramarg1: (Object | null)[]): (Object | null)[];
    static addAll(paramarg0: number[], paramarg1: number[]): number[];
    static addAll(paramarg0: string[], paramarg1: string[]): string[];
    static addAll(paramarg0: number[], paramarg1: number[]): number[];
    static addAll(paramarg0: number[], paramarg1: number[]): number[];
    static addAll(paramarg0: number[], paramarg1: number[]): number[];
    static addAll(paramarg0: number[], paramarg1: number[]): number[];
    static addAll(paramarg0: number[], paramarg1: number[]): number[];
    static addFirst(paramarg0: Object | null, paramarg1: Object | null): Object | null;
    static addFirst(paramarg0: (Object | null)[], paramarg1: boolean): (Object | null)[];
    static addFirst(paramarg0: number[], paramarg1: number): number[];
    static addFirst(paramarg0: string[], paramarg1: string): string[];
    static addFirst(paramarg0: number[], paramarg1: number): number[];
    static addFirst(paramarg0: number[], paramarg1: number): number[];
    static addFirst(paramarg0: number[], paramarg1: number): number[];
    static addFirst(paramarg0: number[], paramarg1: number): number[];
    static addFirst(paramarg0: number[], paramarg1: number): number[];
    static arraycopy(paramarg0: Object | null, paramarg1: number, paramarg2: Object | null, paramarg3: number, paramarg4: number): Object | null;
    static arraycopy(paramarg0: Object | null, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: (param0: number) => Object | null): Object | null;
    static arraycopy(paramarg0: Object | null, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: () => Object | null): Object | null;
    static clone(paramarg0: Object | null): Object | null;
    static clone(paramarg0: (Object | null)[]): (Object | null)[];
    static clone(paramarg0: number[]): number[];
    static clone(paramarg0: string[]): string[];
    static clone(paramarg0: number[]): number[];
    static clone(paramarg0: number[]): number[];
    static clone(paramarg0: number[]): number[];
    static clone(paramarg0: number[]): number[];
    static clone(paramarg0: number[]): number[];
    static contains(paramarg0: (Object | null)[], paramarg1: boolean): boolean;
    static contains(paramarg0: number[], paramarg1: number): boolean;
    static contains(paramarg0: string[], paramarg1: string): boolean;
    static contains(paramarg0: number[], paramarg1: number): boolean;
    static contains(paramarg0: number[], paramarg1: number, paramarg2: number): boolean;
    static contains(paramarg0: number[], paramarg1: number): boolean;
    static contains(paramarg0: number[], paramarg1: number): boolean;
    static contains(paramarg0: (Object | null)[], paramarg1: Object): boolean;
    static contains(paramarg0: number[], paramarg1: number): boolean;
    static contains(paramarg0: number[], paramarg1: number): boolean;
    static containsAny(paramarg0: number[], paramarg1: number[]): boolean;
    static containsAny(paramarg0: (Object | null)[], paramarg1: (Object | null)[]): boolean;
    static get(paramarg0: Object | null, paramarg1: number): Object | null;
    static get(paramarg0: Object | null, paramarg1: number, paramarg2: Object | null): Object | null;
    static getComponentType(paramarg0: Object | null): Class<Object>;
    static getLength(paramarg0: Object): number;
    static hashCode(paramarg0: Object): number;
    static indexOf(paramarg0: (Object | null)[], paramarg1: boolean): number;
    static indexOf(paramarg0: (Object | null)[], paramarg1: boolean, paramarg2: number): number;
    static indexOf(paramarg0: number[], paramarg1: number): number;
    static indexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static indexOf(paramarg0: string[], paramarg1: string): number;
    static indexOf(paramarg0: string[], paramarg1: string, paramarg2: number): number;
    static indexOf(paramarg0: number[], paramarg1: number): number;
    static indexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static indexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static indexOf(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
    static indexOf(paramarg0: number[], paramarg1: number): number;
    static indexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static indexOf(paramarg0: number[], paramarg1: number): number;
    static indexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static indexOf(paramarg0: (Object | null)[], paramarg1: Object): number;
    static indexOf(paramarg0: (Object | null)[], paramarg1: Object, paramarg2: number): number;
    static indexOf(paramarg0: number[], paramarg1: number): number;
    static indexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static indexOf(paramarg0: number[], paramarg1: number): number;
    static indexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static indexesOf(paramarg0: (Object | null)[], paramarg1: boolean): BitSet;
    static indexesOf(paramarg0: (Object | null)[], paramarg1: boolean, paramarg2: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number, paramarg2: number): BitSet;
    static indexesOf(paramarg0: string[], paramarg1: string): BitSet;
    static indexesOf(paramarg0: string[], paramarg1: string, paramarg2: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number, paramarg2: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number, paramarg2: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number, paramarg2: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number, paramarg2: number): BitSet;
    static indexesOf(paramarg0: (Object | null)[], paramarg1: Object): BitSet;
    static indexesOf(paramarg0: (Object | null)[], paramarg1: Object, paramarg2: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number, paramarg2: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number, paramarg2: number): BitSet;
    static insert(paramarg0: number, paramarg1: Object | null, paramarg2: Object | null): Object | null;
    static insert(paramarg0: number, paramarg1: (Object | null)[], paramarg2: (Object | null)[]): (Object | null)[];
    static insert(paramarg0: number, paramarg1: number[], paramarg2: number[]): number[];
    static insert(paramarg0: number, paramarg1: string[], paramarg2: string[]): string[];
    static insert(paramarg0: number, paramarg1: number[], paramarg2: number[]): number[];
    static insert(paramarg0: number, paramarg1: number[], paramarg2: number[]): number[];
    static insert(paramarg0: number, paramarg1: number[], paramarg2: number[]): number[];
    static insert(paramarg0: number, paramarg1: number[], paramarg2: number[]): number[];
    static insert(paramarg0: number, paramarg1: number[], paramarg2: number[]): number[];
    static isArrayIndexValid(paramarg0: Object | null, paramarg1: number): boolean;
    static isEmpty(paramarg0: (Object | null)[]): boolean;
    static isEmpty(paramarg0: number[]): boolean;
    static isEmpty(paramarg0: string[]): boolean;
    static isEmpty(paramarg0: number[]): boolean;
    static isEmpty(paramarg0: number[]): boolean;
    static isEmpty(paramarg0: number[]): boolean;
    static isEmpty(paramarg0: (Object | null)[]): boolean;
    static isEmpty(paramarg0: number[]): boolean;
    static isEmpty(paramarg0: number[]): boolean;
    static isEquals(paramarg0: Object, paramarg1: Object): boolean;
    static isNotEmpty(paramarg0: Object | null): boolean;
    static isNotEmpty(paramarg0: (Object | null)[]): boolean;
    static isNotEmpty(paramarg0: number[]): boolean;
    static isNotEmpty(paramarg0: string[]): boolean;
    static isNotEmpty(paramarg0: number[]): boolean;
    static isNotEmpty(paramarg0: number[]): boolean;
    static isNotEmpty(paramarg0: number[]): boolean;
    static isNotEmpty(paramarg0: number[]): boolean;
    static isNotEmpty(paramarg0: number[]): boolean;
    static isSameLength(paramarg0: (Object | null)[], paramarg1: (Object | null)[]): boolean;
    static isSameLength(paramarg0: number[], paramarg1: number[]): boolean;
    static isSameLength(paramarg0: string[], paramarg1: string[]): boolean;
    static isSameLength(paramarg0: number[], paramarg1: number[]): boolean;
    static isSameLength(paramarg0: number[], paramarg1: number[]): boolean;
    static isSameLength(paramarg0: number[], paramarg1: number[]): boolean;
    static isSameLength(paramarg0: Object, paramarg1: Object): boolean;
    static isSameLength(paramarg0: (Object | null)[], paramarg1: (Object | null)[]): boolean;
    static isSameLength(paramarg0: number[], paramarg1: number[]): boolean;
    static isSameLength(paramarg0: number[], paramarg1: number[]): boolean;
    static isSameType(paramarg0: Object, paramarg1: Object): boolean;
    static isSorted(paramarg0: Object | null): boolean;
    static isSorted(paramarg0: Object | null, paramarg1: (param0: Object) => boolean): boolean;
    static isSorted(paramarg0: (Object | null)[]): boolean;
    static isSorted(paramarg0: number[]): boolean;
    static isSorted(paramarg0: string[]): boolean;
    static isSorted(paramarg0: number[]): boolean;
    static isSorted(paramarg0: number[]): boolean;
    static isSorted(paramarg0: number[]): boolean;
    static isSorted(paramarg0: number[]): boolean;
    static isSorted(paramarg0: number[]): boolean;
    static lastIndexOf(paramarg0: (Object | null)[], paramarg1: boolean): number;
    static lastIndexOf(paramarg0: (Object | null)[], paramarg1: boolean, paramarg2: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static lastIndexOf(paramarg0: string[], paramarg1: string): number;
    static lastIndexOf(paramarg0: string[], paramarg1: string, paramarg2: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static lastIndexOf(paramarg0: (Object | null)[], paramarg1: Object): number;
    static lastIndexOf(paramarg0: (Object | null)[], paramarg1: Object, paramarg2: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static newInstance(paramarg0: Class<Object>, paramarg1: number): Object | null;
    static nullTo(paramarg0: Object | null, paramarg1: Object | null): Object | null;
    static nullToEmpty(paramarg0: Object | null, paramarg1: Class<Object>): Object | null;
    static nullToEmpty(paramarg0: (Object | null)[]): (Object | null)[];
    static nullToEmpty(paramarg0: number[]): number[];
    static nullToEmpty(paramarg0: string[]): string[];
    static nullToEmpty(paramarg0: number[]): number[];
    static nullToEmpty(paramarg0: number[]): number[];
    static nullToEmpty(paramarg0: number[]): number[];
    static nullToEmpty(paramarg0: (Object | null)[]): (Object | null)[];
    static nullToEmpty(paramarg0: (Object | null)[]): (Object | null)[];
    static nullToEmpty(paramarg0: (Object | null)[]): (Object | null)[];
    static nullToEmpty(paramarg0: Object | null): Object | null;
    static nullToEmpty(paramarg0: (Object | null)[]): (Object | null)[];
    static nullToEmpty(paramarg0: (Object | null)[]): (Object | null)[];
    static nullToEmpty(paramarg0: (Object | null)[]): (Object | null)[];
    static nullToEmpty(paramarg0: (Object | null)[]): (Object | null)[];
    static nullToEmpty(paramarg0: (Object | null)[]): (Object | null)[];
    static nullToEmpty(paramarg0: (Object | null)[]): (Object | null)[];
    static nullToEmpty(paramarg0: (Object | null)[]): (Object | null)[];
    static nullToEmpty(paramarg0: number[]): number[];
    static nullToEmpty(paramarg0: number[]): number[];
    static remove(paramarg0: Object | null, paramarg1: number): Object | null;
    static remove(paramarg0: (Object | null)[], paramarg1: number): (Object | null)[];
    static remove(paramarg0: number[], paramarg1: number): number[];
    static remove(paramarg0: string[], paramarg1: number): string[];
    static remove(paramarg0: number[], paramarg1: number): number[];
    static remove(paramarg0: number[], paramarg1: number): number[];
    static remove(paramarg0: number[], paramarg1: number): number[];
    static remove(paramarg0: number[], paramarg1: number): number[];
    static remove(paramarg0: number[], paramarg1: number): number[];
    static removeAll(paramarg0: Object | null, paramarg1: number[]): Object | null;
    static removeAll(paramarg0: (Object | null)[], paramarg1: number[]): (Object | null)[];
    static removeAll(paramarg0: number[], paramarg1: number[]): number[];
    static removeAll(paramarg0: string[], paramarg1: number[]): string[];
    static removeAll(paramarg0: number[], paramarg1: number[]): number[];
    static removeAll(paramarg0: number[], paramarg1: number[]): number[];
    static removeAll(paramarg0: number[], paramarg1: number[]): number[];
    static removeAll(paramarg0: number[], paramarg1: number[]): number[];
    static removeAll(paramarg0: number[], paramarg1: number[]): number[];
    static removeAllOccurences(paramarg0: Object | null, paramarg1: Object | null): Object | null;
    static removeAllOccurences(paramarg0: (Object | null)[], paramarg1: boolean): (Object | null)[];
    static removeAllOccurences(paramarg0: number[], paramarg1: number): number[];
    static removeAllOccurences(paramarg0: string[], paramarg1: string): string[];
    static removeAllOccurences(paramarg0: number[], paramarg1: number): number[];
    static removeAllOccurences(paramarg0: number[], paramarg1: number): number[];
    static removeAllOccurences(paramarg0: number[], paramarg1: number): number[];
    static removeAllOccurences(paramarg0: number[], paramarg1: number): number[];
    static removeAllOccurences(paramarg0: number[], paramarg1: number): number[];
    static removeAllOccurrences(paramarg0: Object | null, paramarg1: Object | null): Object | null;
    static removeAllOccurrences(paramarg0: (Object | null)[], paramarg1: boolean): (Object | null)[];
    static removeAllOccurrences(paramarg0: number[], paramarg1: number): number[];
    static removeAllOccurrences(paramarg0: string[], paramarg1: string): string[];
    static removeAllOccurrences(paramarg0: number[], paramarg1: number): number[];
    static removeAllOccurrences(paramarg0: number[], paramarg1: number): number[];
    static removeAllOccurrences(paramarg0: number[], paramarg1: number): number[];
    static removeAllOccurrences(paramarg0: number[], paramarg1: number): number[];
    static removeAllOccurrences(paramarg0: number[], paramarg1: number): number[];
    static removeElement(paramarg0: Object | null, paramarg1: Object): Object | null;
    static removeElement(paramarg0: (Object | null)[], paramarg1: boolean): (Object | null)[];
    static removeElement(paramarg0: number[], paramarg1: number): number[];
    static removeElement(paramarg0: string[], paramarg1: string): string[];
    static removeElement(paramarg0: number[], paramarg1: number): number[];
    static removeElement(paramarg0: number[], paramarg1: number): number[];
    static removeElement(paramarg0: number[], paramarg1: number): number[];
    static removeElement(paramarg0: number[], paramarg1: number): number[];
    static removeElement(paramarg0: number[], paramarg1: number): number[];
    static removeElements(paramarg0: Object | null, paramarg1: Object | null): Object | null;
    static removeElements(paramarg0: (Object | null)[], paramarg1: (Object | null)[]): (Object | null)[];
    static removeElements(paramarg0: number[], paramarg1: number[]): number[];
    static removeElements(paramarg0: string[], paramarg1: string[]): string[];
    static removeElements(paramarg0: number[], paramarg1: number[]): number[];
    static removeElements(paramarg0: number[], paramarg1: number[]): number[];
    static removeElements(paramarg0: number[], paramarg1: number[]): number[];
    static removeElements(paramarg0: number[], paramarg1: number[]): number[];
    static removeElements(paramarg0: number[], paramarg1: number[]): number[];
    static reverse(paramarg0: (Object | null)[]): void;
    static reverse(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number): void;
    static reverse(paramarg0: number[]): void;
    static reverse(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static reverse(paramarg0: string[]): void;
    static reverse(paramarg0: string[], paramarg1: number, paramarg2: number): void;
    static reverse(paramarg0: number[]): void;
    static reverse(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static reverse(paramarg0: number[]): void;
    static reverse(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static reverse(paramarg0: number[]): void;
    static reverse(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static reverse(paramarg0: (Object | null)[]): void;
    static reverse(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number): void;
    static reverse(paramarg0: number[]): void;
    static reverse(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static reverse(paramarg0: number[]): void;
    static reverse(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static setAll(paramarg0: Object | null, paramarg1: (param0: number) => Object | null): Object | null;
    static setAll(paramarg0: Object | null, paramarg1: () => Object | null): Object | null;
    static shift(paramarg0: (Object | null)[], paramarg1: number): void;
    static shift(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static shift(paramarg0: number[], paramarg1: number): void;
    static shift(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static shift(paramarg0: string[], paramarg1: number): void;
    static shift(paramarg0: string[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static shift(paramarg0: number[], paramarg1: number): void;
    static shift(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static shift(paramarg0: number[], paramarg1: number): void;
    static shift(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static shift(paramarg0: number[], paramarg1: number): void;
    static shift(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static shift(paramarg0: (Object | null)[], paramarg1: number): void;
    static shift(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static shift(paramarg0: number[], paramarg1: number): void;
    static shift(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static shift(paramarg0: number[], paramarg1: number): void;
    static shift(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static shuffle(paramarg0: (Object | null)[]): void;
    static shuffle(paramarg0: (Object | null)[], paramarg1: Random): void;
    static shuffle(paramarg0: number[]): void;
    static shuffle(paramarg0: number[], paramarg1: Random): void;
    static shuffle(paramarg0: string[]): void;
    static shuffle(paramarg0: string[], paramarg1: Random): void;
    static shuffle(paramarg0: number[]): void;
    static shuffle(paramarg0: number[], paramarg1: Random): void;
    static shuffle(paramarg0: number[]): void;
    static shuffle(paramarg0: number[], paramarg1: Random): void;
    static shuffle(paramarg0: number[]): void;
    static shuffle(paramarg0: number[], paramarg1: Random): void;
    static shuffle(paramarg0: (Object | null)[]): void;
    static shuffle(paramarg0: (Object | null)[], paramarg1: Random): void;
    static shuffle(paramarg0: number[]): void;
    static shuffle(paramarg0: number[], paramarg1: Random): void;
    static shuffle(paramarg0: number[]): void;
    static shuffle(paramarg0: number[], paramarg1: Random): void;
    static startsWith(paramarg0: number[], paramarg1: number[]): boolean;
    static subarray(paramarg0: Object | null, paramarg1: number, paramarg2: number): Object | null;
    static subarray(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number): (Object | null)[];
    static subarray(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static subarray(paramarg0: string[], paramarg1: number, paramarg2: number): string[];
    static subarray(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static subarray(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static subarray(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static subarray(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static subarray(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static swap(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number): void;
    static swap(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static swap(paramarg0: string[], paramarg1: number, paramarg2: number): void;
    static swap(paramarg0: string[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static swap(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number): void;
    static swap(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static toArray(paramarg0: Object | null): Object | null;
    static toMap(paramarg0: (Object | null)[]): Map<Object, Object>;
    static toObject(paramarg0: (Object | null)[]): (Object | null)[];
    static toObject(paramarg0: number[]): (Object | null)[];
    static toObject(paramarg0: string[]): (Object | null)[];
    static toObject(paramarg0: number[]): (Object | null)[];
    static toObject(paramarg0: number[]): (Object | null)[];
    static toObject(paramarg0: number[]): (Object | null)[];
    static toObject(paramarg0: number[]): (Object | null)[];
    static toObject(paramarg0: number[]): (Object | null)[];
    static toPrimitive(paramarg0: (Object | null)[]): (Object | null)[];
    static toPrimitive(paramarg0: (Object | null)[], paramarg1: boolean): (Object | null)[];
    static toPrimitive(paramarg0: (Object | null)[]): number[];
    static toPrimitive(paramarg0: (Object | null)[], paramarg1: number): number[];
    static toPrimitive(paramarg0: (Object | null)[]): string[];
    static toPrimitive(paramarg0: (Object | null)[], paramarg1: string): string[];
    static toPrimitive(paramarg0: (Object | null)[]): number[];
    static toPrimitive(paramarg0: (Object | null)[], paramarg1: number): number[];
    static toPrimitive(paramarg0: (Object | null)[]): number[];
    static toPrimitive(paramarg0: (Object | null)[], paramarg1: number): number[];
    static toPrimitive(paramarg0: (Object | null)[]): number[];
    static toPrimitive(paramarg0: (Object | null)[], paramarg1: number): number[];
    static toPrimitive(paramarg0: Object): Object;
    static toPrimitive(paramarg0: (Object | null)[]): number[];
    static toPrimitive(paramarg0: (Object | null)[], paramarg1: number): number[];
    static toPrimitive(paramarg0: (Object | null)[]): number[];
    static toPrimitive(paramarg0: (Object | null)[], paramarg1: number): number[];
    static toString(paramarg0: Object): string;
    static toString(paramarg0: Object, paramarg1: string): string;
    static toStringArray(paramarg0: (Object | null)[]): (Object | null)[];
    static toStringArray(paramarg0: (Object | null)[], paramarg1: string): (Object | null)[];
    constructor()
}