import type { JavaMap } from '../../../../JavaMap.d.ts'
import type { Class } from '../../../../java/lang/Class.d.ts'
import type { Field } from '../../../../java/lang/reflect/Field.d.ts'
import type { Method } from '../../../../java/lang/reflect/Method.d.ts'
import type { Type } from '../../../../java/lang/reflect/Type.d.ts'
import type { BitSet } from '../../../../java/util/BitSet.d.ts'
import type { Comparator } from '../../../../java/util/Comparator.d.ts'
import type { Random } from '../../../../java/util/Random.d.ts'
import type { Function } from '../../../../java/util/function/Function.d.ts'
import type { IntFunction } from '../../../../java/util/function/IntFunction.d.ts'
import type { Supplier } from '../../../../java/util/function/Supplier.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { Comparable } from '../../../../java/lang/Comparable.d.ts'
import type { Throwable } from '../../../../java/lang/Throwable.d.ts'
export class ArrayUtils extends Object {
    static EMPTY_BOOLEAN_ARRAY: boolean[];
    static EMPTY_BOOLEAN_OBJECT_ARRAY: boolean[];
    static EMPTY_BYTE_ARRAY: number[];
    static EMPTY_BYTE_OBJECT_ARRAY: number[];
    static EMPTY_CHARACTER_OBJECT_ARRAY: string[];
    static EMPTY_CHAR_ARRAY: string[];
    static EMPTY_CLASS_ARRAY: Class<Object>[];
    static EMPTY_DOUBLE_ARRAY: number[];
    static EMPTY_DOUBLE_OBJECT_ARRAY: number[];
    static EMPTY_FIELD_ARRAY: Field[];
    static EMPTY_FLOAT_ARRAY: number[];
    static EMPTY_FLOAT_OBJECT_ARRAY: number[];
    static EMPTY_INTEGER_OBJECT_ARRAY: number[];
    static EMPTY_INT_ARRAY: number[];
    static EMPTY_LONG_ARRAY: number[];
    static EMPTY_LONG_OBJECT_ARRAY: number[];
    static EMPTY_METHOD_ARRAY: Method[];
    static EMPTY_OBJECT_ARRAY: Object[];
    static EMPTY_SHORT_ARRAY: number[];
    static EMPTY_SHORT_OBJECT_ARRAY: number[];
    static EMPTY_STRING_ARRAY: string[];
    static EMPTY_THROWABLE_ARRAY: Throwable[];
    static EMPTY_TYPE_ARRAY: Type[];
    static INDEX_NOT_FOUND: number;
    static SOFT_MAX_ARRAY_LENGTH: number;
    static add<T extends unknown>(paramarg0: T[], paramarg1: T): T[];
    static add<T extends unknown>(paramarg0: T[], paramarg1: number, paramarg2: T): T[];
    static add(paramarg0: boolean[], paramarg1: boolean): boolean[];
    static add(paramarg0: boolean[], paramarg1: number, paramarg2: boolean): boolean[];
    static add(paramarg0: number[], paramarg1: number): number[];
    static add(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static add(paramarg0: string[], paramarg1: string): string[];
    static add(paramarg0: string[], paramarg1: number, paramarg2: string): string[];
    static addAll<T extends unknown>(paramarg0: T[], ...paramarg1: T[]): T[];
    static addAll(paramarg0: boolean[], ...paramarg1: boolean[]): boolean[];
    static addAll(paramarg0: number[], ...paramarg1: number[]): number[];
    static addAll(paramarg0: string[], ...paramarg1: string[]): string[];
    static addFirst<T extends unknown>(paramarg0: T[], paramarg1: T): T[];
    static addFirst(paramarg0: boolean[], paramarg1: boolean): boolean[];
    static addFirst(paramarg0: number[], paramarg1: number): number[];
    static addFirst(paramarg0: string[], paramarg1: string): string[];
    static arraycopy<T extends unknown>(paramarg0: T, paramarg1: number, paramarg2: T, paramarg3: number, paramarg4: number): T;
    static arraycopy<T extends unknown>(paramarg0: T, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: (param0: number) => T): T;
    static arraycopy<T extends unknown>(paramarg0: T, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: () => T): T;
    static clone<T extends unknown>(paramarg0: T[]): T[];
    static clone(paramarg0: boolean[]): boolean[];
    static clone(paramarg0: number[]): number[];
    static clone(paramarg0: string[]): string[];
    static contains(paramarg0: boolean[], paramarg1: boolean): boolean;
    static contains(paramarg0: number[], paramarg1: number): boolean;
    static contains(paramarg0: string[], paramarg1: string): boolean;
    static contains(paramarg0: number[], paramarg1: number, paramarg2: number): boolean;
    static contains(paramarg0: Object[], paramarg1: Object): boolean;
    static containsAny(paramarg0: number[], ...paramarg1: number[]): boolean;
    static containsAny(paramarg0: Object[], ...paramarg1: Object[]): boolean;
    static get<T extends unknown>(paramarg0: T[], paramarg1: number): T;
    static get<T extends unknown>(paramarg0: T[], paramarg1: number, paramarg2: T): T;
    static getComponentType<T extends unknown>(paramarg0: T[]): Class<T>;
    static getLength(paramarg0: Object): number;
    static hashCode(paramarg0: Object): number;
    static indexOf(paramarg0: boolean[], paramarg1: boolean): number;
    static indexOf(paramarg0: boolean[], paramarg1: boolean, paramarg2: number): number;
    static indexOf(paramarg0: number[], paramarg1: number): number;
    static indexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static indexOf(paramarg0: string[], paramarg1: string): number;
    static indexOf(paramarg0: string[], paramarg1: string, paramarg2: number): number;
    static indexOf(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
    static indexOf(paramarg0: Object[], paramarg1: Object): number;
    static indexOf(paramarg0: Object[], paramarg1: Object, paramarg2: number): number;
    static indexesOf(paramarg0: boolean[], paramarg1: boolean): BitSet;
    static indexesOf(paramarg0: boolean[], paramarg1: boolean, paramarg2: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number, paramarg2: number): BitSet;
    static indexesOf(paramarg0: string[], paramarg1: string): BitSet;
    static indexesOf(paramarg0: string[], paramarg1: string, paramarg2: number): BitSet;
    static indexesOf(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): BitSet;
    static indexesOf(paramarg0: Object[], paramarg1: Object): BitSet;
    static indexesOf(paramarg0: Object[], paramarg1: Object, paramarg2: number): BitSet;
    static insert<T extends unknown>(paramarg0: number, paramarg1: T[], ...paramarg2: T[]): T[];
    static insert(paramarg0: number, paramarg1: boolean[], ...paramarg2: boolean[]): boolean[];
    static insert(paramarg0: number, paramarg1: number[], ...paramarg2: number[]): number[];
    static insert(paramarg0: number, paramarg1: string[], ...paramarg2: string[]): string[];
    static isArrayIndexValid<T extends unknown>(paramarg0: T[], paramarg1: number): boolean;
    static isEmpty(paramarg0: boolean[]): boolean;
    static isEmpty(paramarg0: number[]): boolean;
    static isEmpty(paramarg0: string[]): boolean;
    static isEmpty(paramarg0: Object[]): boolean;
    static isEquals(paramarg0: Object, paramarg1: Object): boolean;
    static isNotEmpty<T extends unknown>(paramarg0: T[]): boolean;
    static isNotEmpty(paramarg0: boolean[]): boolean;
    static isNotEmpty(paramarg0: number[]): boolean;
    static isNotEmpty(paramarg0: string[]): boolean;
    static isSameLength(paramarg0: boolean[], paramarg1: boolean[]): boolean;
    static isSameLength(paramarg0: number[], paramarg1: number[]): boolean;
    static isSameLength(paramarg0: string[], paramarg1: string[]): boolean;
    static isSameLength(paramarg0: Object, paramarg1: Object): boolean;
    static isSameLength(paramarg0: Object[], paramarg1: Object[]): boolean;
    static isSameType(paramarg0: Object, paramarg1: Object): boolean;
    static isSorted<T extends Comparable<Object>>(paramarg0: T[]): boolean;
    static isSorted<T extends unknown>(paramarg0: T[], paramarg1: (param0: T, param1: T) => number): boolean;
    static isSorted(paramarg0: boolean[]): boolean;
    static isSorted(paramarg0: number[]): boolean;
    static isSorted(paramarg0: string[]): boolean;
    static lastIndexOf(paramarg0: boolean[], paramarg1: boolean): number;
    static lastIndexOf(paramarg0: boolean[], paramarg1: boolean, paramarg2: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number, paramarg2: number): number;
    static lastIndexOf(paramarg0: string[], paramarg1: string): number;
    static lastIndexOf(paramarg0: string[], paramarg1: string, paramarg2: number): number;
    static lastIndexOf(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): number;
    static lastIndexOf(paramarg0: Object[], paramarg1: Object): number;
    static lastIndexOf(paramarg0: Object[], paramarg1: Object, paramarg2: number): number;
    static newInstance<T extends unknown>(paramarg0: Class<T>, paramarg1: number): T[];
    static nullTo<T extends unknown>(paramarg0: T[], paramarg1: T[]): T[];
    static nullToEmpty<T extends unknown>(paramarg0: T[], paramarg1: Class<T[]>): T[];
    static nullToEmpty(paramarg0: boolean[]): boolean[];
    static nullToEmpty(paramarg0: number[]): number[];
    static nullToEmpty(paramarg0: string[]): string[];
    static nullToEmpty(paramarg0: Class<Object>[]): Class<Object>[];
    static nullToEmpty(paramarg0: Object[]): Object[];
    static remove<T extends unknown>(paramarg0: T[], paramarg1: number): T[];
    static remove(paramarg0: boolean[], paramarg1: number): boolean[];
    static remove(paramarg0: number[], paramarg1: number): number[];
    static remove(paramarg0: string[], paramarg1: number): string[];
    static removeAll<T extends unknown>(paramarg0: T[], ...paramarg1: number[]): T[];
    static removeAll(paramarg0: boolean[], ...paramarg1: number[]): boolean[];
    static removeAll(paramarg0: number[], ...paramarg1: number[]): number[];
    static removeAll(paramarg0: string[], ...paramarg1: number[]): string[];
    static removeAllOccurences<T extends unknown>(paramarg0: T[], paramarg1: T): T[];
    static removeAllOccurences(paramarg0: boolean[], paramarg1: boolean): boolean[];
    static removeAllOccurences(paramarg0: number[], paramarg1: number): number[];
    static removeAllOccurences(paramarg0: string[], paramarg1: string): string[];
    static removeAllOccurrences<T extends unknown>(paramarg0: T[], paramarg1: T): T[];
    static removeAllOccurrences(paramarg0: boolean[], paramarg1: boolean): boolean[];
    static removeAllOccurrences(paramarg0: number[], paramarg1: number): number[];
    static removeAllOccurrences(paramarg0: string[], paramarg1: string): string[];
    static removeElement<T extends unknown>(paramarg0: T[], paramarg1: Object): T[];
    static removeElement(paramarg0: boolean[], paramarg1: boolean): boolean[];
    static removeElement(paramarg0: number[], paramarg1: number): number[];
    static removeElement(paramarg0: string[], paramarg1: string): string[];
    static removeElements<T extends unknown>(paramarg0: T[], ...paramarg1: T[]): T[];
    static removeElements(paramarg0: boolean[], ...paramarg1: boolean[]): boolean[];
    static removeElements(paramarg0: number[], ...paramarg1: number[]): number[];
    static removeElements(paramarg0: string[], ...paramarg1: string[]): string[];
    static reverse(paramarg0: boolean[]): void;
    static reverse(paramarg0: boolean[], paramarg1: number, paramarg2: number): void;
    static reverse(paramarg0: number[]): void;
    static reverse(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static reverse(paramarg0: string[]): void;
    static reverse(paramarg0: string[], paramarg1: number, paramarg2: number): void;
    static reverse(paramarg0: Object[]): void;
    static reverse(paramarg0: Object[], paramarg1: number, paramarg2: number): void;
    static setAll<T extends unknown>(paramarg0: T[], paramarg1: (param0: number) => T): T[];
    static setAll<T extends unknown>(paramarg0: T[], paramarg1: () => T): T[];
    static shift(paramarg0: boolean[], paramarg1: number): void;
    static shift(paramarg0: boolean[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static shift(paramarg0: number[], paramarg1: number): void;
    static shift(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static shift(paramarg0: string[], paramarg1: number): void;
    static shift(paramarg0: string[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static shift(paramarg0: Object[], paramarg1: number): void;
    static shift(paramarg0: Object[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static shuffle(paramarg0: boolean[]): void;
    static shuffle(paramarg0: boolean[], paramarg1: Random): void;
    static shuffle(paramarg0: number[]): void;
    static shuffle(paramarg0: number[], paramarg1: Random): void;
    static shuffle(paramarg0: string[]): void;
    static shuffle(paramarg0: string[], paramarg1: Random): void;
    static shuffle(paramarg0: Object[]): void;
    static shuffle(paramarg0: Object[], paramarg1: Random): void;
    static startsWith(paramarg0: number[], paramarg1: number[]): boolean;
    static subarray<T extends unknown>(paramarg0: T[], paramarg1: number, paramarg2: number): T[];
    static subarray(paramarg0: boolean[], paramarg1: number, paramarg2: number): boolean[];
    static subarray(paramarg0: number[], paramarg1: number, paramarg2: number): number[];
    static subarray(paramarg0: string[], paramarg1: number, paramarg2: number): string[];
    static swap(paramarg0: boolean[], paramarg1: number, paramarg2: number): void;
    static swap(paramarg0: boolean[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number): void;
    static swap(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static swap(paramarg0: string[], paramarg1: number, paramarg2: number): void;
    static swap(paramarg0: string[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static swap(paramarg0: Object[], paramarg1: number, paramarg2: number): void;
    static swap(paramarg0: Object[], paramarg1: number, paramarg2: number, paramarg3: number): void;
    static toArray<T extends unknown>(...paramarg0: T[]): T[];
    static toMap(paramarg0: Object[]): JavaMap<Object, Object>;
    static toObject(paramarg0: boolean[]): boolean[];
    static toObject(paramarg0: number[]): number[];
    static toObject(paramarg0: string[]): string[];
    static toPrimitive(paramarg0: boolean[]): boolean[];
    static toPrimitive(paramarg0: boolean[], paramarg1: boolean): boolean[];
    static toPrimitive(paramarg0: number[]): number[];
    static toPrimitive(paramarg0: number[], paramarg1: number): number[];
    static toPrimitive(paramarg0: string[]): string[];
    static toPrimitive(paramarg0: string[], paramarg1: string): string[];
    static toPrimitive(paramarg0: Object): Object;
    static toString(paramarg0: Object): string;
    static toString(paramarg0: Object, paramarg1: string): string;
    static toStringArray(paramarg0: Object[]): string[];
    static toStringArray(paramarg0: Object[], paramarg1: string): string[];
    constructor()
}