import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { FloatBuffer } from '../../../java/nio/FloatBuffer.d.ts'
import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { ShortBuffer } from '../../../java/nio/ShortBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
export class ARBImaging extends Object {
    static GL_BLEND_COLOR: number;
    static GL_BLEND_EQUATION: number;
    static GL_COLOR_MATRIX: number;
    static GL_COLOR_MATRIX_STACK_DEPTH: number;
    static GL_COLOR_TABLE: number;
    static GL_COLOR_TABLE_ALPHA_SIZE: number;
    static GL_COLOR_TABLE_BIAS: number;
    static GL_COLOR_TABLE_BLUE_SIZE: number;
    static GL_COLOR_TABLE_FORMAT: number;
    static GL_COLOR_TABLE_GREEN_SIZE: number;
    static GL_COLOR_TABLE_INTENSITY_SIZE: number;
    static GL_COLOR_TABLE_LUMINANCE_SIZE: number;
    static GL_COLOR_TABLE_RED_SIZE: number;
    static GL_COLOR_TABLE_SCALE: number;
    static GL_COLOR_TABLE_WIDTH: number;
    static GL_CONSTANT_ALPHA: number;
    static GL_CONSTANT_BORDER: number;
    static GL_CONSTANT_COLOR: number;
    static GL_CONVOLUTION_1D: number;
    static GL_CONVOLUTION_2D: number;
    static GL_CONVOLUTION_BORDER_COLOR: number;
    static GL_CONVOLUTION_BORDER_MODE: number;
    static GL_CONVOLUTION_FILTER_BIAS: number;
    static GL_CONVOLUTION_FILTER_SCALE: number;
    static GL_CONVOLUTION_FORMAT: number;
    static GL_CONVOLUTION_HEIGHT: number;
    static GL_CONVOLUTION_WIDTH: number;
    static GL_FUNC_ADD: number;
    static GL_FUNC_REVERSE_SUBTRACT: number;
    static GL_FUNC_SUBTRACT: number;
    static GL_HISTOGRAM: number;
    static GL_HISTOGRAM_ALPHA_SIZE: number;
    static GL_HISTOGRAM_BLUE_SIZE: number;
    static GL_HISTOGRAM_FORMAT: number;
    static GL_HISTOGRAM_GREEN_SIZE: number;
    static GL_HISTOGRAM_LUMINANCE_SIZE: number;
    static GL_HISTOGRAM_RED_SIZE: number;
    static GL_HISTOGRAM_SINK: number;
    static GL_HISTOGRAM_WIDTH: number;
    static GL_MAX: number;
    static GL_MAX_COLOR_MATRIX_STACK_DEPTH: number;
    static GL_MAX_CONVOLUTION_HEIGHT: number;
    static GL_MAX_CONVOLUTION_WIDTH: number;
    static GL_MIN: number;
    static GL_MINMAX: number;
    static GL_MINMAX_FORMAT: number;
    static GL_MINMAX_SINK: number;
    static GL_ONE_MINUS_CONSTANT_ALPHA: number;
    static GL_ONE_MINUS_CONSTANT_COLOR: number;
    static GL_POST_COLOR_MATRIX_ALPHA_BIAS: number;
    static GL_POST_COLOR_MATRIX_ALPHA_SCALE: number;
    static GL_POST_COLOR_MATRIX_BLUE_BIAS: number;
    static GL_POST_COLOR_MATRIX_BLUE_SCALE: number;
    static GL_POST_COLOR_MATRIX_COLOR_TABLE: number;
    static GL_POST_COLOR_MATRIX_GREEN_BIAS: number;
    static GL_POST_COLOR_MATRIX_GREEN_SCALE: number;
    static GL_POST_COLOR_MATRIX_RED_BIAS: number;
    static GL_POST_COLOR_MATRIX_RED_SCALE: number;
    static GL_POST_CONVOLUTION_ALPHA_BIAS: number;
    static GL_POST_CONVOLUTION_ALPHA_SCALE: number;
    static GL_POST_CONVOLUTION_BLUE_BIAS: number;
    static GL_POST_CONVOLUTION_BLUE_SCALE: number;
    static GL_POST_CONVOLUTION_COLOR_TABLE: number;
    static GL_POST_CONVOLUTION_GREEN_BIAS: number;
    static GL_POST_CONVOLUTION_GREEN_SCALE: number;
    static GL_POST_CONVOLUTION_RED_BIAS: number;
    static GL_POST_CONVOLUTION_RED_SCALE: number;
    static GL_PROXY_COLOR_TABLE: number;
    static GL_PROXY_HISTOGRAM: number;
    static GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE: number;
    static GL_PROXY_POST_CONVOLUTION_COLOR_TABLE: number;
    static GL_REDUCE: number;
    static GL_REPLICATE_BORDER: number;
    static GL_SEPARABLE_2D: number;
    static GL_TABLE_TOO_LARGE: number;
    static glBlendColor(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glBlendEquation(paramarg0: number): void;
    static glColorSubTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: ByteBuffer): void;
    static glColorSubTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number[]): void;
    static glColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: ByteBuffer): void;
    static glColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: FloatBuffer): void;
    static glColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: IntBuffer): void;
    static glColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: ShortBuffer): void;
    static glColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glColorTableParameterfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glColorTableParameterfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glColorTableParameteriv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glColorTableParameteriv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glConvolutionFilter1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: ByteBuffer): void;
    static glConvolutionFilter1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glConvolutionFilter2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: ByteBuffer): void;
    static glConvolutionFilter2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glConvolutionParameterf(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glConvolutionParameterfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glConvolutionParameterfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glConvolutionParameteri(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glConvolutionParameteriv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glConvolutionParameteriv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glCopyColorSubTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glCopyColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glCopyConvolutionFilter1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glCopyConvolutionFilter2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glGetColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer): void;
    static glGetColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glGetColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ShortBuffer): void;
    static glGetColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glGetColorTableParameterf(paramarg0: number, paramarg1: number): number;
    static glGetColorTableParameterfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetColorTableParameterfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetColorTableParameteri(paramarg0: number, paramarg1: number): number;
    static glGetColorTableParameteriv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetColorTableParameteriv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetConvolutionFilter(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer): void;
    static glGetConvolutionFilter(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glGetConvolutionParameterf(paramarg0: number, paramarg1: number): number;
    static glGetConvolutionParameterfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetConvolutionParameterfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetConvolutionParameteri(paramarg0: number, paramarg1: number): number;
    static glGetConvolutionParameteriv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetConvolutionParameteriv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetHistogram(paramarg0: number, paramarg1: boolean, paramarg2: number, paramarg3: number, paramarg4: ByteBuffer): void;
    static glGetHistogram(paramarg0: number, paramarg1: boolean, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glGetHistogramParameterf(paramarg0: number, paramarg1: number): number;
    static glGetHistogramParameterfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetHistogramParameterfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetHistogramParameteri(paramarg0: number, paramarg1: number): number;
    static glGetHistogramParameteriv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetHistogramParameteriv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetMinmax(paramarg0: number, paramarg1: boolean, paramarg2: number, paramarg3: number, paramarg4: ByteBuffer): void;
    static glGetMinmax(paramarg0: number, paramarg1: boolean, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glGetMinmaxParameterf(paramarg0: number, paramarg1: number): number;
    static glGetMinmaxParameterfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetMinmaxParameterfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetMinmaxParameteri(paramarg0: number, paramarg1: number): number;
    static glGetMinmaxParameteriv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetMinmaxParameteriv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetSeparableFilter(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer, paramarg4: ByteBuffer, paramarg5: ByteBuffer): void;
    static glGetSeparableFilter(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: ByteBuffer): void;
    static glHistogram(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean): void;
    static glMinmax(paramarg0: number, paramarg1: number, paramarg2: boolean): void;
    static glResetHistogram(paramarg0: number): void;
    static glResetMinmax(paramarg0: number): void;
    static glSeparableFilter2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: ByteBuffer, paramarg7: ByteBuffer): void;
    static glSeparableFilter2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nglColorSubTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nglColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nglColorTableParameterfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglColorTableParameteriv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglConvolutionFilter1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nglConvolutionFilter2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nglConvolutionParameterfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglConvolutionParameteriv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetColorTable(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetColorTableParameterfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetColorTableParameteriv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetConvolutionFilter(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetConvolutionParameterfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetConvolutionParameteriv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetHistogram(paramarg0: number, paramarg1: boolean, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglGetHistogramParameterfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetHistogramParameteriv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetMinmax(paramarg0: number, paramarg1: boolean, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglGetMinmaxParameterfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetMinmaxParameteriv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetSeparableFilter(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nglSeparableFilter2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    constructor()
}