import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { DoubleBuffer } from '../../../java/nio/DoubleBuffer.d.ts'
import type { FloatBuffer } from '../../../java/nio/FloatBuffer.d.ts'
import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../java/lang/CharSequence.d.ts'
import type { PointerBuffer } from '../../../org/lwjgl/PointerBuffer.d.ts'
export class ARBSeparateShaderObjects extends Object {
    static GL_ACTIVE_PROGRAM: number;
    static GL_ALL_SHADER_BITS: number;
    static GL_FRAGMENT_SHADER_BIT: number;
    static GL_GEOMETRY_SHADER_BIT: number;
    static GL_PROGRAM_PIPELINE_BINDING: number;
    static GL_PROGRAM_SEPARABLE: number;
    static GL_TESS_CONTROL_SHADER_BIT: number;
    static GL_TESS_EVALUATION_SHADER_BIT: number;
    static GL_VERTEX_SHADER_BIT: number;
    static glActiveShaderProgram(paramarg0: number, paramarg1: number): void;
    static glBindProgramPipeline(paramarg0: number): void;
    static glCreateShaderProgramv(paramarg0: number, paramarg1: CharSequence): number;
    static glCreateShaderProgramv(paramarg0: number, ...paramarg1: (Object | null)[]): number;
    static glCreateShaderProgramv(paramarg0: number, paramarg1: PointerBuffer): number;
    static glDeleteProgramPipelines(paramarg0: number): void;
    static glDeleteProgramPipelines(paramarg0: number[]): void;
    static glDeleteProgramPipelines(paramarg0: IntBuffer): void;
    static glGenProgramPipelines(): number;
    static glGenProgramPipelines(paramarg0: number[]): void;
    static glGenProgramPipelines(paramarg0: IntBuffer): void;
    static glGetProgramPipelineInfoLog(paramarg0: number): string;
    static glGetProgramPipelineInfoLog(paramarg0: number, paramarg1: number): string;
    static glGetProgramPipelineInfoLog(paramarg0: number, paramarg1: number[], paramarg2: ByteBuffer): void;
    static glGetProgramPipelineInfoLog(paramarg0: number, paramarg1: IntBuffer, paramarg2: ByteBuffer): void;
    static glGetProgramPipelinei(paramarg0: number, paramarg1: number): number;
    static glGetProgramPipelineiv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetProgramPipelineiv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glIsProgramPipeline(paramarg0: number): boolean;
    static glProgramParameteri(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glProgramUniform1d(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glProgramUniform1dv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform1dv(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glProgramUniform1f(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glProgramUniform1fv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform1fv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glProgramUniform1i(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glProgramUniform1iv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform1iv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform1ui(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glProgramUniform1uiv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform1uiv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform2d(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glProgramUniform2dv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform2dv(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glProgramUniform2f(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glProgramUniform2fv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform2fv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glProgramUniform2i(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glProgramUniform2iv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform2iv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform2ui(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glProgramUniform2uiv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform2uiv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform3d(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glProgramUniform3dv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform3dv(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glProgramUniform3f(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glProgramUniform3fv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform3fv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glProgramUniform3i(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glProgramUniform3iv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform3iv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform3ui(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glProgramUniform3uiv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform3uiv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform4d(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glProgramUniform4dv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform4dv(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glProgramUniform4f(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glProgramUniform4fv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform4fv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glProgramUniform4i(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glProgramUniform4iv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform4iv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform4ui(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glProgramUniform4uiv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform4uiv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniformMatrix2dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix2dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: DoubleBuffer): void;
    static glProgramUniformMatrix2fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix2fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix2x3dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix2x3dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: DoubleBuffer): void;
    static glProgramUniformMatrix2x3fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix2x3fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix2x4dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix2x4dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: DoubleBuffer): void;
    static glProgramUniformMatrix2x4fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix2x4fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix3dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix3dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: DoubleBuffer): void;
    static glProgramUniformMatrix3fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix3fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix3x2dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix3x2dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: DoubleBuffer): void;
    static glProgramUniformMatrix3x2fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix3x2fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix3x4dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix3x4dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: DoubleBuffer): void;
    static glProgramUniformMatrix3x4fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix3x4fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix4dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix4dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: DoubleBuffer): void;
    static glProgramUniformMatrix4fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix4fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix4x2dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix4x2dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: DoubleBuffer): void;
    static glProgramUniformMatrix4x2fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix4x2fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix4x3dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix4x3dv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: DoubleBuffer): void;
    static glProgramUniformMatrix4x3fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix4x3fv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glUseProgramStages(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glValidateProgramPipeline(paramarg0: number): void;
    static nglCreateShaderProgramv(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nglDeleteProgramPipelines(paramarg0: number, paramarg1: number): void;
    static nglGenProgramPipelines(paramarg0: number, paramarg1: number): void;
    static nglGetProgramPipelineInfoLog(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetProgramPipelineiv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglProgramUniform1dv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform1fv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform1iv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform1uiv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform2dv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform2fv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform2iv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform2uiv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform3dv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform3fv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform3iv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform3uiv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform4dv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform4fv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform4iv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform4uiv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniformMatrix2dv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix2fv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix2x3dv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix2x3fv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix2x4dv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix2x4fv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix3dv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix3fv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix3x2dv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix3x2fv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix3x4dv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix3x4fv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix4dv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix4fv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix4x2dv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix4x2fv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix4x3dv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix4x3fv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    constructor()
}