import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { DoubleBuffer } from '../../../java/nio/DoubleBuffer.d.ts'
import type { FloatBuffer } from '../../../java/nio/FloatBuffer.d.ts'
import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { ShortBuffer } from '../../../java/nio/ShortBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { PointerBuffer } from '../../../org/lwjgl/PointerBuffer.d.ts'
export class ARBVertexProgram extends Object {
    static GL_COLOR_SUM_ARB: number;
    static GL_CURRENT_MATRIX_ARB: number;
    static GL_CURRENT_MATRIX_STACK_DEPTH_ARB: number;
    static GL_CURRENT_VERTEX_ATTRIB_ARB: number;
    static GL_MATRIX0_ARB: number;
    static GL_MATRIX10_ARB: number;
    static GL_MATRIX11_ARB: number;
    static GL_MATRIX12_ARB: number;
    static GL_MATRIX13_ARB: number;
    static GL_MATRIX14_ARB: number;
    static GL_MATRIX15_ARB: number;
    static GL_MATRIX16_ARB: number;
    static GL_MATRIX17_ARB: number;
    static GL_MATRIX18_ARB: number;
    static GL_MATRIX19_ARB: number;
    static GL_MATRIX1_ARB: number;
    static GL_MATRIX20_ARB: number;
    static GL_MATRIX21_ARB: number;
    static GL_MATRIX22_ARB: number;
    static GL_MATRIX23_ARB: number;
    static GL_MATRIX24_ARB: number;
    static GL_MATRIX25_ARB: number;
    static GL_MATRIX26_ARB: number;
    static GL_MATRIX27_ARB: number;
    static GL_MATRIX28_ARB: number;
    static GL_MATRIX29_ARB: number;
    static GL_MATRIX2_ARB: number;
    static GL_MATRIX30_ARB: number;
    static GL_MATRIX31_ARB: number;
    static GL_MATRIX3_ARB: number;
    static GL_MATRIX4_ARB: number;
    static GL_MATRIX5_ARB: number;
    static GL_MATRIX6_ARB: number;
    static GL_MATRIX7_ARB: number;
    static GL_MATRIX8_ARB: number;
    static GL_MATRIX9_ARB: number;
    static GL_MAX_PROGRAM_ADDRESS_REGISTERS_ARB: number;
    static GL_MAX_PROGRAM_ATTRIBS_ARB: number;
    static GL_MAX_PROGRAM_ENV_PARAMETERS_ARB: number;
    static GL_MAX_PROGRAM_INSTRUCTIONS_ARB: number;
    static GL_MAX_PROGRAM_LOCAL_PARAMETERS_ARB: number;
    static GL_MAX_PROGRAM_MATRICES_ARB: number;
    static GL_MAX_PROGRAM_MATRIX_STACK_DEPTH_ARB: number;
    static GL_MAX_PROGRAM_NATIVE_ADDRESS_REGISTERS_ARB: number;
    static GL_MAX_PROGRAM_NATIVE_ATTRIBS_ARB: number;
    static GL_MAX_PROGRAM_NATIVE_INSTRUCTIONS_ARB: number;
    static GL_MAX_PROGRAM_NATIVE_PARAMETERS_ARB: number;
    static GL_MAX_PROGRAM_NATIVE_TEMPORARIES_ARB: number;
    static GL_MAX_PROGRAM_PARAMETERS_ARB: number;
    static GL_MAX_PROGRAM_TEMPORARIES_ARB: number;
    static GL_MAX_VERTEX_ATTRIBS_ARB: number;
    static GL_PROGRAM_ADDRESS_REGISTERS_ARB: number;
    static GL_PROGRAM_ATTRIBS_ARB: number;
    static GL_PROGRAM_BINDING_ARB: number;
    static GL_PROGRAM_ERROR_POSITION_ARB: number;
    static GL_PROGRAM_ERROR_STRING_ARB: number;
    static GL_PROGRAM_FORMAT_ARB: number;
    static GL_PROGRAM_FORMAT_ASCII_ARB: number;
    static GL_PROGRAM_INSTRUCTIONS_ARB: number;
    static GL_PROGRAM_LENGTH_ARB: number;
    static GL_PROGRAM_NATIVE_ADDRESS_REGISTERS_ARB: number;
    static GL_PROGRAM_NATIVE_ATTRIBS_ARB: number;
    static GL_PROGRAM_NATIVE_INSTRUCTIONS_ARB: number;
    static GL_PROGRAM_NATIVE_PARAMETERS_ARB: number;
    static GL_PROGRAM_NATIVE_TEMPORARIES_ARB: number;
    static GL_PROGRAM_PARAMETERS_ARB: number;
    static GL_PROGRAM_STRING_ARB: number;
    static GL_PROGRAM_TEMPORARIES_ARB: number;
    static GL_PROGRAM_UNDER_NATIVE_LIMITS_ARB: number;
    static GL_TRANSPOSE_CURRENT_MATRIX_ARB: number;
    static GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB: number;
    static GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB: number;
    static GL_VERTEX_ATTRIB_ARRAY_POINTER_ARB: number;
    static GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB: number;
    static GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB: number;
    static GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB: number;
    static GL_VERTEX_PROGRAM_ARB: number;
    static GL_VERTEX_PROGRAM_POINT_SIZE_ARB: number;
    static GL_VERTEX_PROGRAM_TWO_SIDE_ARB: number;
    static glBindProgramARB(paramarg0: number, paramarg1: number): void;
    static glDeleteProgramsARB(paramarg0: number[]): void;
    static glDeleteProgramsARB(paramarg0: IntBuffer): void;
    static glDisableVertexAttribArrayARB(paramarg0: number): void;
    static glEnableVertexAttribArrayARB(paramarg0: number): void;
    static glGenProgramsARB(): number;
    static glGenProgramsARB(paramarg0: number[]): void;
    static glGenProgramsARB(paramarg0: IntBuffer): void;
    static glGetProgramEnvParameterdvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetProgramEnvParameterdvARB(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glGetProgramEnvParameterfvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetProgramEnvParameterfvARB(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetProgramLocalParameterdvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetProgramLocalParameterdvARB(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glGetProgramLocalParameterfvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetProgramLocalParameterfvARB(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetProgramStringARB(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer): void;
    static glGetProgramiARB(paramarg0: number, paramarg1: number): number;
    static glGetProgramivARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetProgramivARB(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetVertexAttribPointerARB(paramarg0: number, paramarg1: number): number;
    static glGetVertexAttribPointervARB(paramarg0: number, paramarg1: number, paramarg2: PointerBuffer): void;
    static glGetVertexAttribdvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetVertexAttribdvARB(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glGetVertexAttribfvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetVertexAttribfvARB(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetVertexAttribiARB(paramarg0: number, paramarg1: number): number;
    static glGetVertexAttribivARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetVertexAttribivARB(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glIsProgramARB(paramarg0: number): boolean;
    static glProgramEnvParameter4dARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glProgramEnvParameter4dvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramEnvParameter4dvARB(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glProgramEnvParameter4fARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glProgramEnvParameter4fvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramEnvParameter4fvARB(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glProgramLocalParameter4dARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glProgramLocalParameter4dvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramLocalParameter4dvARB(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glProgramLocalParameter4fARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glProgramLocalParameter4fvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramLocalParameter4fvARB(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glProgramStringARB(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer): void;
    static glVertexAttrib1dARB(paramarg0: number, paramarg1: number): void;
    static glVertexAttrib1dvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib1dvARB(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glVertexAttrib1fARB(paramarg0: number, paramarg1: number): void;
    static glVertexAttrib1fvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib1fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glVertexAttrib1sARB(paramarg0: number, paramarg1: number): void;
    static glVertexAttrib1svARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib1svARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib2dARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glVertexAttrib2dvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib2dvARB(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glVertexAttrib2fARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glVertexAttrib2fvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib2fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glVertexAttrib2sARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glVertexAttrib2svARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib2svARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib3dARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glVertexAttrib3dvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib3dvARB(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glVertexAttrib3fARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glVertexAttrib3fvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib3fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glVertexAttrib3sARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glVertexAttrib3svARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib3svARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4NbvARB(paramarg0: number, paramarg1: ByteBuffer): void;
    static glVertexAttrib4NivARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4NivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glVertexAttrib4NsvARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib4NsvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4NubARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glVertexAttrib4NubvARB(paramarg0: number, paramarg1: ByteBuffer): void;
    static glVertexAttrib4NuivARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4NuivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glVertexAttrib4NusvARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib4NusvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4bvARB(paramarg0: number, paramarg1: ByteBuffer): void;
    static glVertexAttrib4dARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glVertexAttrib4dvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4dvARB(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glVertexAttrib4fARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glVertexAttrib4fvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glVertexAttrib4ivARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4ivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glVertexAttrib4sARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glVertexAttrib4svARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib4svARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4ubvARB(paramarg0: number, paramarg1: ByteBuffer): void;
    static glVertexAttrib4uivARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4uivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glVertexAttrib4usvARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib4usvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: number[]): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: number[]): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: ByteBuffer): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: FloatBuffer): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: IntBuffer): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: ShortBuffer): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: number): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: number[]): void;
    static nglDeleteProgramsARB(paramarg0: number, paramarg1: number): void;
    static nglGenProgramsARB(paramarg0: number, paramarg1: number): void;
    static nglGetProgramEnvParameterdvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetProgramEnvParameterfvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetProgramLocalParameterdvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetProgramLocalParameterfvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetProgramStringARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetProgramivARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetVertexAttribPointervARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetVertexAttribdvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetVertexAttribfvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetVertexAttribivARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglProgramEnvParameter4dvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglProgramEnvParameter4fvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglProgramLocalParameter4dvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglProgramLocalParameter4fvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglProgramStringARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglVertexAttrib1dvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib1fvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib1svARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib2dvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib2fvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib2svARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib3dvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib3fvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib3svARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4NbvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4NivARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4NsvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4NubvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4NuivARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4NusvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4bvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4dvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4fvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4ivARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4svARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4ubvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4uivARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4usvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: number): void;
    constructor()
}