import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
export class ARBVertexType2_10_10_10_REV extends Object {
    static GL_INT_2_10_10_10_REV: number;
    static glColorP3ui(paramarg0: number, paramarg1: number): void;
    static glColorP3uiv(paramarg0: number, paramarg1: number[]): void;
    static glColorP3uiv(paramarg0: number, paramarg1: IntBuffer): void;
    static glColorP4ui(paramarg0: number, paramarg1: number): void;
    static glColorP4uiv(paramarg0: number, paramarg1: number[]): void;
    static glColorP4uiv(paramarg0: number, paramarg1: IntBuffer): void;
    static glMultiTexCoordP1ui(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glMultiTexCoordP1uiv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glMultiTexCoordP1uiv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glMultiTexCoordP2ui(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glMultiTexCoordP2uiv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glMultiTexCoordP2uiv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glMultiTexCoordP3ui(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glMultiTexCoordP3uiv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glMultiTexCoordP3uiv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glMultiTexCoordP4ui(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glMultiTexCoordP4uiv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glMultiTexCoordP4uiv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glNormalP3ui(paramarg0: number, paramarg1: number): void;
    static glNormalP3uiv(paramarg0: number, paramarg1: number[]): void;
    static glNormalP3uiv(paramarg0: number, paramarg1: IntBuffer): void;
    static glSecondaryColorP3ui(paramarg0: number, paramarg1: number): void;
    static glSecondaryColorP3uiv(paramarg0: number, paramarg1: number[]): void;
    static glSecondaryColorP3uiv(paramarg0: number, paramarg1: IntBuffer): void;
    static glTexCoordP1ui(paramarg0: number, paramarg1: number): void;
    static glTexCoordP1uiv(paramarg0: number, paramarg1: number[]): void;
    static glTexCoordP1uiv(paramarg0: number, paramarg1: IntBuffer): void;
    static glTexCoordP2ui(paramarg0: number, paramarg1: number): void;
    static glTexCoordP2uiv(paramarg0: number, paramarg1: number[]): void;
    static glTexCoordP2uiv(paramarg0: number, paramarg1: IntBuffer): void;
    static glTexCoordP3ui(paramarg0: number, paramarg1: number): void;
    static glTexCoordP3uiv(paramarg0: number, paramarg1: number[]): void;
    static glTexCoordP3uiv(paramarg0: number, paramarg1: IntBuffer): void;
    static glTexCoordP4ui(paramarg0: number, paramarg1: number): void;
    static glTexCoordP4uiv(paramarg0: number, paramarg1: number[]): void;
    static glTexCoordP4uiv(paramarg0: number, paramarg1: IntBuffer): void;
    static glVertexAttribP1ui(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number): void;
    static glVertexAttribP1uiv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glVertexAttribP1uiv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: IntBuffer): void;
    static glVertexAttribP2ui(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number): void;
    static glVertexAttribP2uiv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glVertexAttribP2uiv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: IntBuffer): void;
    static glVertexAttribP3ui(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number): void;
    static glVertexAttribP3uiv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glVertexAttribP3uiv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: IntBuffer): void;
    static glVertexAttribP4ui(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number): void;
    static glVertexAttribP4uiv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glVertexAttribP4uiv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: IntBuffer): void;
    static glVertexP2ui(paramarg0: number, paramarg1: number): void;
    static glVertexP2uiv(paramarg0: number, paramarg1: number[]): void;
    static glVertexP2uiv(paramarg0: number, paramarg1: IntBuffer): void;
    static glVertexP3ui(paramarg0: number, paramarg1: number): void;
    static glVertexP3uiv(paramarg0: number, paramarg1: number[]): void;
    static glVertexP3uiv(paramarg0: number, paramarg1: IntBuffer): void;
    static glVertexP4ui(paramarg0: number, paramarg1: number): void;
    static glVertexP4uiv(paramarg0: number, paramarg1: number[]): void;
    static glVertexP4uiv(paramarg0: number, paramarg1: IntBuffer): void;
    static nglColorP3uiv(paramarg0: number, paramarg1: number): void;
    static nglColorP4uiv(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoordP1uiv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglMultiTexCoordP2uiv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglMultiTexCoordP3uiv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglMultiTexCoordP4uiv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglNormalP3uiv(paramarg0: number, paramarg1: number): void;
    static nglSecondaryColorP3uiv(paramarg0: number, paramarg1: number): void;
    static nglTexCoordP1uiv(paramarg0: number, paramarg1: number): void;
    static nglTexCoordP2uiv(paramarg0: number, paramarg1: number): void;
    static nglTexCoordP3uiv(paramarg0: number, paramarg1: number): void;
    static nglTexCoordP4uiv(paramarg0: number, paramarg1: number): void;
    static nglVertexAttribP1uiv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number): void;
    static nglVertexAttribP2uiv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number): void;
    static nglVertexAttribP3uiv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number): void;
    static nglVertexAttribP4uiv(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number): void;
    static nglVertexP2uiv(paramarg0: number, paramarg1: number): void;
    static nglVertexP3uiv(paramarg0: number, paramarg1: number): void;
    static nglVertexP4uiv(paramarg0: number, paramarg1: number): void;
    constructor()
}