import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { DoubleBuffer } from '../../../java/nio/DoubleBuffer.d.ts'
import type { FloatBuffer } from '../../../java/nio/FloatBuffer.d.ts'
import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { ShortBuffer } from '../../../java/nio/ShortBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { PointerBuffer } from '../../../org/lwjgl/PointerBuffer.d.ts'
export class EXTDirectStateAccess extends Object {
    static GL_PROGRAM_MATRIX_EXT: number;
    static GL_PROGRAM_MATRIX_STACK_DEPTH_EXT: number;
    static GL_TRANSPOSE_PROGRAM_MATRIX_EXT: number;
    static glBindMultiTextureEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glCheckNamedFramebufferStatusEXT(paramarg0: number, paramarg1: number): number;
    static glClientAttribDefaultEXT(paramarg0: number): void;
    static glCompressedMultiTexImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static glCompressedMultiTexImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: ByteBuffer): void;
    static glCompressedMultiTexImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static glCompressedMultiTexImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: ByteBuffer): void;
    static glCompressedMultiTexImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static glCompressedMultiTexImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: ByteBuffer): void;
    static glCompressedMultiTexSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static glCompressedMultiTexSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: ByteBuffer): void;
    static glCompressedMultiTexSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static glCompressedMultiTexSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: ByteBuffer): void;
    static glCompressedMultiTexSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number): void;
    static glCompressedMultiTexSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: ByteBuffer): void;
    static glCompressedTextureImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static glCompressedTextureImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: ByteBuffer): void;
    static glCompressedTextureImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static glCompressedTextureImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: ByteBuffer): void;
    static glCompressedTextureImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static glCompressedTextureImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: ByteBuffer): void;
    static glCompressedTextureSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static glCompressedTextureSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: ByteBuffer): void;
    static glCompressedTextureSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static glCompressedTextureSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: ByteBuffer): void;
    static glCompressedTextureSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number): void;
    static glCompressedTextureSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: ByteBuffer): void;
    static glCopyMultiTexImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static glCopyMultiTexImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static glCopyMultiTexSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glCopyMultiTexSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static glCopyMultiTexSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static glCopyTextureImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static glCopyTextureImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static glCopyTextureSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glCopyTextureSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static glCopyTextureSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static glDisableClientStateIndexedEXT(paramarg0: number, paramarg1: number): void;
    static glDisableClientStateiEXT(paramarg0: number, paramarg1: number): void;
    static glDisableIndexedEXT(paramarg0: number, paramarg1: number): void;
    static glDisableVertexArrayAttribEXT(paramarg0: number, paramarg1: number): void;
    static glDisableVertexArrayEXT(paramarg0: number, paramarg1: number): void;
    static glEnableClientStateIndexedEXT(paramarg0: number, paramarg1: number): void;
    static glEnableClientStateiEXT(paramarg0: number, paramarg1: number): void;
    static glEnableIndexedEXT(paramarg0: number, paramarg1: number): void;
    static glEnableVertexArrayAttribEXT(paramarg0: number, paramarg1: number): void;
    static glEnableVertexArrayEXT(paramarg0: number, paramarg1: number): void;
    static glFlushMappedNamedBufferRangeEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glFramebufferDrawBufferEXT(paramarg0: number, paramarg1: number): void;
    static glFramebufferDrawBuffersEXT(paramarg0: number, paramarg1: number[]): void;
    static glFramebufferDrawBuffersEXT(paramarg0: number, paramarg1: IntBuffer): void;
    static glFramebufferReadBufferEXT(paramarg0: number, paramarg1: number): void;
    static glGenerateMultiTexMipmapEXT(paramarg0: number, paramarg1: number): void;
    static glGenerateTextureMipmapEXT(paramarg0: number, paramarg1: number): void;
    static glGetBooleanIndexedEXT(paramarg0: number, paramarg1: number): boolean;
    static glGetBooleanIndexedvEXT(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer): void;
    static glGetCompressedMultiTexImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer): void;
    static glGetCompressedMultiTexImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glGetCompressedTextureImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer): void;
    static glGetCompressedTextureImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glGetDoubleIndexedEXT(paramarg0: number, paramarg1: number): number;
    static glGetDoubleIndexedvEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetDoubleIndexedvEXT(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glGetDoubleiEXT(paramarg0: number, paramarg1: number): number;
    static glGetDoublei_vEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetDoublei_vEXT(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glGetFloatIndexedEXT(paramarg0: number, paramarg1: number): number;
    static glGetFloatIndexedvEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetFloatIndexedvEXT(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetFloatiEXT(paramarg0: number, paramarg1: number): number;
    static glGetFloati_vEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetFloati_vEXT(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetFramebufferParameteriEXT(paramarg0: number, paramarg1: number): number;
    static glGetFramebufferParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetFramebufferParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetIntegerIndexedEXT(paramarg0: number, paramarg1: number): number;
    static glGetIntegerIndexedvEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetIntegerIndexedvEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetMultiTexEnvfEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetMultiTexEnvfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetMultiTexEnvfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glGetMultiTexEnviEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetMultiTexEnvivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetMultiTexEnvivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetMultiTexGendEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetMultiTexGendvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetMultiTexGendvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: DoubleBuffer): void;
    static glGetMultiTexGenfEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetMultiTexGenfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetMultiTexGenfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glGetMultiTexGeniEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetMultiTexGenivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetMultiTexGenivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetMultiTexImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number[]): void;
    static glGetMultiTexImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: ByteBuffer): void;
    static glGetMultiTexImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: DoubleBuffer): void;
    static glGetMultiTexImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: FloatBuffer): void;
    static glGetMultiTexImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: IntBuffer): void;
    static glGetMultiTexImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: ShortBuffer): void;
    static glGetMultiTexImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glGetMultiTexLevelParameterfEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static glGetMultiTexLevelParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[]): void;
    static glGetMultiTexLevelParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: FloatBuffer): void;
    static glGetMultiTexLevelParameteriEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static glGetMultiTexLevelParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[]): void;
    static glGetMultiTexLevelParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: IntBuffer): void;
    static glGetMultiTexParameterIiEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetMultiTexParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetMultiTexParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetMultiTexParameterIuiEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetMultiTexParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetMultiTexParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetMultiTexParameterfEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetMultiTexParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetMultiTexParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glGetMultiTexParameteriEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetMultiTexParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetMultiTexParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetNamedBufferParameteriEXT(paramarg0: number, paramarg1: number): number;
    static glGetNamedBufferParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetNamedBufferParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer): void;
    static glGetNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glGetNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: ShortBuffer): void;
    static glGetNamedFramebufferAttachmentParameteriEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetNamedFramebufferAttachmentParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetNamedFramebufferAttachmentParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetNamedProgramLocalParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetNamedProgramLocalParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetNamedProgramLocalParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetNamedProgramLocalParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetNamedProgramLocalParameterdvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetNamedProgramLocalParameterdvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: DoubleBuffer): void;
    static glGetNamedProgramLocalParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetNamedProgramLocalParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glGetNamedProgramStringEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer): void;
    static glGetNamedProgramiEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetNamedProgramivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetNamedProgramivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetNamedRenderbufferParameteriEXT(paramarg0: number, paramarg1: number): number;
    static glGetNamedRenderbufferParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetNamedRenderbufferParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetPointerIndexedEXT(paramarg0: number, paramarg1: number): number;
    static glGetPointerIndexedvEXT(paramarg0: number, paramarg1: number, paramarg2: PointerBuffer): void;
    static glGetPointeriEXT(paramarg0: number, paramarg1: number): number;
    static glGetPointeri_vEXT(paramarg0: number, paramarg1: number, paramarg2: PointerBuffer): void;
    static glGetTextureImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number[]): void;
    static glGetTextureImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: ByteBuffer): void;
    static glGetTextureImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: DoubleBuffer): void;
    static glGetTextureImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: FloatBuffer): void;
    static glGetTextureImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: IntBuffer): void;
    static glGetTextureImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: ShortBuffer): void;
    static glGetTextureImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glGetTextureLevelParameterfEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static glGetTextureLevelParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[]): void;
    static glGetTextureLevelParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: FloatBuffer): void;
    static glGetTextureLevelParameteriEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static glGetTextureLevelParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[]): void;
    static glGetTextureLevelParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: IntBuffer): void;
    static glGetTextureParameterIiEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetTextureParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetTextureParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetTextureParameterIuiEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetTextureParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetTextureParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetTextureParameterfEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetTextureParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetTextureParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glGetTextureParameteriEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetTextureParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetTextureParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetVertexArrayIntegerEXT(paramarg0: number, paramarg1: number): number;
    static glGetVertexArrayIntegeriEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetVertexArrayIntegeri_vEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetVertexArrayIntegeri_vEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetVertexArrayIntegervEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetVertexArrayIntegervEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetVertexArrayPointerEXT(paramarg0: number, paramarg1: number): number;
    static glGetVertexArrayPointeriEXT(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetVertexArrayPointeri_vEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: PointerBuffer): void;
    static glGetVertexArrayPointervEXT(paramarg0: number, paramarg1: number, paramarg2: PointerBuffer): void;
    static glIsEnabledIndexedEXT(paramarg0: number, paramarg1: number): boolean;
    static glMapNamedBufferEXT(paramarg0: number, paramarg1: number): ByteBuffer;
    static glMapNamedBufferEXT(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer): ByteBuffer;
    static glMapNamedBufferEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer): ByteBuffer;
    static glMapNamedBufferRangeEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): ByteBuffer;
    static glMapNamedBufferRangeEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: ByteBuffer): ByteBuffer;
    static glMatrixFrustumEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glMatrixLoadIdentityEXT(paramarg0: number): void;
    static glMatrixLoadTransposedEXT(paramarg0: number, paramarg1: number[]): void;
    static glMatrixLoadTransposedEXT(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glMatrixLoadTransposefEXT(paramarg0: number, paramarg1: number[]): void;
    static glMatrixLoadTransposefEXT(paramarg0: number, paramarg1: FloatBuffer): void;
    static glMatrixLoaddEXT(paramarg0: number, paramarg1: number[]): void;
    static glMatrixLoaddEXT(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glMatrixLoadfEXT(paramarg0: number, paramarg1: number[]): void;
    static glMatrixLoadfEXT(paramarg0: number, paramarg1: FloatBuffer): void;
    static glMatrixMultTransposedEXT(paramarg0: number, paramarg1: number[]): void;
    static glMatrixMultTransposedEXT(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glMatrixMultTransposefEXT(paramarg0: number, paramarg1: number[]): void;
    static glMatrixMultTransposefEXT(paramarg0: number, paramarg1: FloatBuffer): void;
    static glMatrixMultdEXT(paramarg0: number, paramarg1: number[]): void;
    static glMatrixMultdEXT(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glMatrixMultfEXT(paramarg0: number, paramarg1: number[]): void;
    static glMatrixMultfEXT(paramarg0: number, paramarg1: FloatBuffer): void;
    static glMatrixOrthoEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glMatrixPopEXT(paramarg0: number): void;
    static glMatrixPushEXT(paramarg0: number): void;
    static glMatrixRotatedEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glMatrixRotatefEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glMatrixScaledEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMatrixScalefEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMatrixTranslatedEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMatrixTranslatefEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexBufferEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexCoordPointerEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[]): void;
    static glMultiTexCoordPointerEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: ByteBuffer): void;
    static glMultiTexCoordPointerEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: FloatBuffer): void;
    static glMultiTexCoordPointerEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: IntBuffer): void;
    static glMultiTexCoordPointerEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: ShortBuffer): void;
    static glMultiTexCoordPointerEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glMultiTexEnvfEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexEnvfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glMultiTexEnvfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glMultiTexEnviEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexEnvivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glMultiTexEnvivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glMultiTexGendEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexGendvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glMultiTexGendvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: DoubleBuffer): void;
    static glMultiTexGenfEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexGenfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glMultiTexGenfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glMultiTexGeniEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexGenivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glMultiTexGenivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glMultiTexImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number[]): void;
    static glMultiTexImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: ByteBuffer): void;
    static glMultiTexImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: DoubleBuffer): void;
    static glMultiTexImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: FloatBuffer): void;
    static glMultiTexImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: IntBuffer): void;
    static glMultiTexImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: ShortBuffer): void;
    static glMultiTexImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static glMultiTexImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number[]): void;
    static glMultiTexImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: ByteBuffer): void;
    static glMultiTexImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: DoubleBuffer): void;
    static glMultiTexImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: FloatBuffer): void;
    static glMultiTexImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: IntBuffer): void;
    static glMultiTexImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: ShortBuffer): void;
    static glMultiTexImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static glMultiTexImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number[]): void;
    static glMultiTexImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: ByteBuffer): void;
    static glMultiTexImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: DoubleBuffer): void;
    static glMultiTexImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: FloatBuffer): void;
    static glMultiTexImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: IntBuffer): void;
    static glMultiTexImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: ShortBuffer): void;
    static glMultiTexImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number): void;
    static glMultiTexParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glMultiTexParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glMultiTexParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glMultiTexParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glMultiTexParameterfEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glMultiTexParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glMultiTexParameteriEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glMultiTexParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glMultiTexRenderbufferEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glMultiTexSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number[]): void;
    static glMultiTexSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: ByteBuffer): void;
    static glMultiTexSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: DoubleBuffer): void;
    static glMultiTexSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: FloatBuffer): void;
    static glMultiTexSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: IntBuffer): void;
    static glMultiTexSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: ShortBuffer): void;
    static glMultiTexSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static glMultiTexSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number[]): void;
    static glMultiTexSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: ByteBuffer): void;
    static glMultiTexSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: DoubleBuffer): void;
    static glMultiTexSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: FloatBuffer): void;
    static glMultiTexSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: IntBuffer): void;
    static glMultiTexSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: ShortBuffer): void;
    static glMultiTexSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static glMultiTexSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number[]): void;
    static glMultiTexSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: ByteBuffer): void;
    static glMultiTexSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: DoubleBuffer): void;
    static glMultiTexSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: FloatBuffer): void;
    static glMultiTexSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: IntBuffer): void;
    static glMultiTexSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: ShortBuffer): void;
    static glMultiTexSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number): void;
    static glNamedBufferDataEXT(paramarg0: number, paramarg1: number[], paramarg2: number): void;
    static glNamedBufferDataEXT(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number): void;
    static glNamedBufferDataEXT(paramarg0: number, paramarg1: DoubleBuffer, paramarg2: number): void;
    static glNamedBufferDataEXT(paramarg0: number, paramarg1: FloatBuffer, paramarg2: number): void;
    static glNamedBufferDataEXT(paramarg0: number, paramarg1: IntBuffer, paramarg2: number): void;
    static glNamedBufferDataEXT(paramarg0: number, paramarg1: ShortBuffer, paramarg2: number): void;
    static glNamedBufferDataEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer): void;
    static glNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: ShortBuffer): void;
    static glNamedCopyBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glNamedFramebufferRenderbufferEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glNamedFramebufferTexture1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glNamedFramebufferTexture2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glNamedFramebufferTexture3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glNamedFramebufferTextureEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glNamedFramebufferTextureFaceEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glNamedFramebufferTextureLayerEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glNamedProgramLocalParameter4dEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glNamedProgramLocalParameter4dvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glNamedProgramLocalParameter4dvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: DoubleBuffer): void;
    static glNamedProgramLocalParameter4fEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glNamedProgramLocalParameter4fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glNamedProgramLocalParameter4fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glNamedProgramLocalParameterI4iEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glNamedProgramLocalParameterI4ivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glNamedProgramLocalParameterI4ivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glNamedProgramLocalParameterI4uiEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glNamedProgramLocalParameterI4uivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glNamedProgramLocalParameterI4uivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glNamedProgramLocalParameters4fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glNamedProgramLocalParameters4fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glNamedProgramLocalParametersI4ivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glNamedProgramLocalParametersI4ivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glNamedProgramLocalParametersI4uivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glNamedProgramLocalParametersI4uivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glNamedProgramStringEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer): void;
    static glNamedRenderbufferStorageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glNamedRenderbufferStorageMultisampleCoverageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glNamedRenderbufferStorageMultisampleEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glProgramUniform1fEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glProgramUniform1fvEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform1fvEXT(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glProgramUniform1iEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glProgramUniform1ivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform1ivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform1uiEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glProgramUniform1uivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform1uivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform2fEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glProgramUniform2fvEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform2fvEXT(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glProgramUniform2iEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glProgramUniform2ivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform2ivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform2uiEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glProgramUniform2uivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform2uivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform3fEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glProgramUniform3fvEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform3fvEXT(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glProgramUniform3iEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glProgramUniform3ivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform3ivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform3uiEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glProgramUniform3uivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform3uivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform4fEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glProgramUniform4fvEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform4fvEXT(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glProgramUniform4iEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glProgramUniform4ivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform4ivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniform4uiEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glProgramUniform4uivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform4uivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glProgramUniformMatrix2fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix2fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix2x3fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix2x3fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix2x4fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix2x4fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix3fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix3fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix3x2fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix3x2fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix3x4fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix3x4fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix4fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix4fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix4x2fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix4x2fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glProgramUniformMatrix4x3fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number[]): void;
    static glProgramUniformMatrix4x3fvEXT(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: FloatBuffer): void;
    static glPushClientAttribDefaultEXT(paramarg0: number): void;
    static glTextureBufferEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glTextureImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number[]): void;
    static glTextureImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: ByteBuffer): void;
    static glTextureImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: DoubleBuffer): void;
    static glTextureImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: FloatBuffer): void;
    static glTextureImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: IntBuffer): void;
    static glTextureImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: ShortBuffer): void;
    static glTextureImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static glTextureImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number[]): void;
    static glTextureImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: ByteBuffer): void;
    static glTextureImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: DoubleBuffer): void;
    static glTextureImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: FloatBuffer): void;
    static glTextureImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: IntBuffer): void;
    static glTextureImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: ShortBuffer): void;
    static glTextureImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static glTextureImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number[]): void;
    static glTextureImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: ByteBuffer): void;
    static glTextureImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: DoubleBuffer): void;
    static glTextureImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: FloatBuffer): void;
    static glTextureImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: IntBuffer): void;
    static glTextureImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: ShortBuffer): void;
    static glTextureImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number): void;
    static glTextureParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glTextureParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glTextureParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glTextureParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glTextureParameterfEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glTextureParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glTextureParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glTextureParameteriEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glTextureParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glTextureParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glTextureRenderbufferEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glTextureSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number[]): void;
    static glTextureSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: ByteBuffer): void;
    static glTextureSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: DoubleBuffer): void;
    static glTextureSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: FloatBuffer): void;
    static glTextureSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: IntBuffer): void;
    static glTextureSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: ShortBuffer): void;
    static glTextureSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static glTextureSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number[]): void;
    static glTextureSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: ByteBuffer): void;
    static glTextureSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: DoubleBuffer): void;
    static glTextureSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: FloatBuffer): void;
    static glTextureSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: IntBuffer): void;
    static glTextureSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: ShortBuffer): void;
    static glTextureSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static glTextureSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number[]): void;
    static glTextureSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: ByteBuffer): void;
    static glTextureSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: DoubleBuffer): void;
    static glTextureSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: FloatBuffer): void;
    static glTextureSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: IntBuffer): void;
    static glTextureSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: ShortBuffer): void;
    static glTextureSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number): void;
    static glUnmapNamedBufferEXT(paramarg0: number): boolean;
    static glVertexArrayColorOffsetEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glVertexArrayEdgeFlagOffsetEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glVertexArrayFogCoordOffsetEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glVertexArrayIndexOffsetEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glVertexArrayMultiTexCoordOffsetEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glVertexArrayNormalOffsetEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glVertexArraySecondaryColorOffsetEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glVertexArrayTexCoordOffsetEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glVertexArrayVertexAttribIOffsetEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glVertexArrayVertexAttribOffsetEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: boolean, paramarg6: number, paramarg7: number): void;
    static glVertexArrayVertexOffsetEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nglCompressedMultiTexImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nglCompressedMultiTexImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static nglCompressedMultiTexImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static nglCompressedMultiTexSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nglCompressedMultiTexSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static nglCompressedMultiTexSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number): void;
    static nglCompressedTextureImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nglCompressedTextureImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static nglCompressedTextureImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static nglCompressedTextureSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nglCompressedTextureSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static nglCompressedTextureSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number): void;
    static nglFramebufferDrawBuffersEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetBooleanIndexedvEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetCompressedMultiTexImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetCompressedTextureImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetDoubleIndexedvEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetDoublei_vEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetFloatIndexedvEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetFloati_vEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetFramebufferParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetIntegerIndexedvEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetMultiTexEnvfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetMultiTexEnvivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetMultiTexGendvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetMultiTexGenfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetMultiTexGenivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetMultiTexImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nglGetMultiTexLevelParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglGetMultiTexLevelParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglGetMultiTexParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetMultiTexParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetMultiTexParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetMultiTexParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetNamedBufferParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetNamedFramebufferAttachmentParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetNamedProgramLocalParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetNamedProgramLocalParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetNamedProgramLocalParameterdvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetNamedProgramLocalParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetNamedProgramStringEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetNamedProgramivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetNamedRenderbufferParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetPointerIndexedvEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetPointeri_vEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetTextureImageEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nglGetTextureLevelParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglGetTextureLevelParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglGetTextureParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetTextureParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetTextureParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetTextureParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetVertexArrayIntegeri_vEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetVertexArrayIntegervEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetVertexArrayPointeri_vEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetVertexArrayPointervEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglMapNamedBufferEXT(paramarg0: number, paramarg1: number): number;
    static nglMapNamedBufferRangeEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nglMatrixLoadTransposedEXT(paramarg0: number, paramarg1: number): void;
    static nglMatrixLoadTransposefEXT(paramarg0: number, paramarg1: number): void;
    static nglMatrixLoaddEXT(paramarg0: number, paramarg1: number): void;
    static nglMatrixLoadfEXT(paramarg0: number, paramarg1: number): void;
    static nglMatrixMultTransposedEXT(paramarg0: number, paramarg1: number): void;
    static nglMatrixMultTransposefEXT(paramarg0: number, paramarg1: number): void;
    static nglMatrixMultdEXT(paramarg0: number, paramarg1: number): void;
    static nglMatrixMultfEXT(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoordPointerEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglMultiTexEnvfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglMultiTexEnvivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglMultiTexGendvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglMultiTexGenfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglMultiTexGenivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglMultiTexImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static nglMultiTexImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static nglMultiTexImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number): void;
    static nglMultiTexParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglMultiTexParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglMultiTexParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglMultiTexParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglMultiTexSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nglMultiTexSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static nglMultiTexSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number): void;
    static nglNamedBufferDataEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglNamedBufferSubDataEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglNamedProgramLocalParameter4dvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglNamedProgramLocalParameter4fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglNamedProgramLocalParameterI4ivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglNamedProgramLocalParameterI4uivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglNamedProgramLocalParameters4fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglNamedProgramLocalParametersI4ivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglNamedProgramLocalParametersI4uivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglNamedProgramStringEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglProgramUniform1fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform1ivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform1uivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform2fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform2ivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform2uivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform3fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform3ivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform3uivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform4fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform4ivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform4uivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniformMatrix2fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix2x3fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix2x4fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix3fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix3x2fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix3x4fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix4fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix4x2fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglProgramUniformMatrix4x3fvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number): void;
    static nglTextureImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static nglTextureImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static nglTextureImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number): void;
    static nglTextureParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglTextureParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglTextureParameterfvEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglTextureParameterivEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglTextureSubImage1DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nglTextureSubImage2DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static nglTextureSubImage3DEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number, paramarg10: number, paramarg11: number): void;
    constructor()
}