import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { DoubleBuffer } from '../../../java/nio/DoubleBuffer.d.ts'
import type { FloatBuffer } from '../../../java/nio/FloatBuffer.d.ts'
import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { ShortBuffer } from '../../../java/nio/ShortBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { PointerBuffer } from '../../../org/lwjgl/PointerBuffer.d.ts'
export class GL11C extends Object {
    static GL_ALPHA: number;
    static GL_ALWAYS: number;
    static GL_AND: number;
    static GL_AND_INVERTED: number;
    static GL_AND_REVERSE: number;
    static GL_BACK: number;
    static GL_BACK_LEFT: number;
    static GL_BACK_RIGHT: number;
    static GL_BLEND: number;
    static GL_BLEND_DST: number;
    static GL_BLEND_SRC: number;
    static GL_BLUE: number;
    static GL_BYTE: number;
    static GL_CCW: number;
    static GL_CLEAR: number;
    static GL_COLOR: number;
    static GL_COLOR_BUFFER_BIT: number;
    static GL_COLOR_CLEAR_VALUE: number;
    static GL_COLOR_LOGIC_OP: number;
    static GL_COLOR_WRITEMASK: number;
    static GL_COPY: number;
    static GL_COPY_INVERTED: number;
    static GL_CULL_FACE: number;
    static GL_CULL_FACE_MODE: number;
    static GL_CW: number;
    static GL_DECR: number;
    static GL_DEPTH: number;
    static GL_DEPTH_BUFFER_BIT: number;
    static GL_DEPTH_CLEAR_VALUE: number;
    static GL_DEPTH_COMPONENT: number;
    static GL_DEPTH_FUNC: number;
    static GL_DEPTH_RANGE: number;
    static GL_DEPTH_TEST: number;
    static GL_DEPTH_WRITEMASK: number;
    static GL_DITHER: number;
    static GL_DONT_CARE: number;
    static GL_DOUBLE: number;
    static GL_DOUBLEBUFFER: number;
    static GL_DRAW_BUFFER: number;
    static GL_DST_ALPHA: number;
    static GL_DST_COLOR: number;
    static GL_EQUAL: number;
    static GL_EQUIV: number;
    static GL_EXTENSIONS: number;
    static GL_FALSE: number;
    static GL_FASTEST: number;
    static GL_FILL: number;
    static GL_FLOAT: number;
    static GL_FRONT: number;
    static GL_FRONT_AND_BACK: number;
    static GL_FRONT_FACE: number;
    static GL_FRONT_LEFT: number;
    static GL_FRONT_RIGHT: number;
    static GL_GEQUAL: number;
    static GL_GREATER: number;
    static GL_GREEN: number;
    static GL_INCR: number;
    static GL_INT: number;
    static GL_INVALID_ENUM: number;
    static GL_INVALID_OPERATION: number;
    static GL_INVALID_VALUE: number;
    static GL_INVERT: number;
    static GL_KEEP: number;
    static GL_LEFT: number;
    static GL_LEQUAL: number;
    static GL_LESS: number;
    static GL_LINE: number;
    static GL_LINEAR: number;
    static GL_LINEAR_MIPMAP_LINEAR: number;
    static GL_LINEAR_MIPMAP_NEAREST: number;
    static GL_LINES: number;
    static GL_LINE_LOOP: number;
    static GL_LINE_SMOOTH: number;
    static GL_LINE_SMOOTH_HINT: number;
    static GL_LINE_STRIP: number;
    static GL_LINE_WIDTH: number;
    static GL_LINE_WIDTH_GRANULARITY: number;
    static GL_LINE_WIDTH_RANGE: number;
    static GL_LOGIC_OP_MODE: number;
    static GL_MAX_TEXTURE_SIZE: number;
    static GL_MAX_VIEWPORT_DIMS: number;
    static GL_NAND: number;
    static GL_NEAREST: number;
    static GL_NEAREST_MIPMAP_LINEAR: number;
    static GL_NEAREST_MIPMAP_NEAREST: number;
    static GL_NEVER: number;
    static GL_NICEST: number;
    static GL_NONE: number;
    static GL_NOOP: number;
    static GL_NOR: number;
    static GL_NOTEQUAL: number;
    static GL_NO_ERROR: number;
    static GL_ONE: number;
    static GL_ONE_MINUS_DST_ALPHA: number;
    static GL_ONE_MINUS_DST_COLOR: number;
    static GL_ONE_MINUS_SRC_ALPHA: number;
    static GL_ONE_MINUS_SRC_COLOR: number;
    static GL_OR: number;
    static GL_OR_INVERTED: number;
    static GL_OR_REVERSE: number;
    static GL_OUT_OF_MEMORY: number;
    static GL_PACK_ALIGNMENT: number;
    static GL_PACK_LSB_FIRST: number;
    static GL_PACK_ROW_LENGTH: number;
    static GL_PACK_SKIP_PIXELS: number;
    static GL_PACK_SKIP_ROWS: number;
    static GL_PACK_SWAP_BYTES: number;
    static GL_POINT: number;
    static GL_POINTS: number;
    static GL_POINT_SIZE: number;
    static GL_POINT_SIZE_GRANULARITY: number;
    static GL_POINT_SIZE_RANGE: number;
    static GL_POLYGON_MODE: number;
    static GL_POLYGON_OFFSET_FACTOR: number;
    static GL_POLYGON_OFFSET_FILL: number;
    static GL_POLYGON_OFFSET_LINE: number;
    static GL_POLYGON_OFFSET_POINT: number;
    static GL_POLYGON_OFFSET_UNITS: number;
    static GL_POLYGON_SMOOTH: number;
    static GL_POLYGON_SMOOTH_HINT: number;
    static GL_PROXY_TEXTURE_1D: number;
    static GL_PROXY_TEXTURE_2D: number;
    static GL_QUADS: number;
    static GL_R3_G3_B2: number;
    static GL_READ_BUFFER: number;
    static GL_RED: number;
    static GL_RENDERER: number;
    static GL_REPEAT: number;
    static GL_REPLACE: number;
    static GL_RGB: number;
    static GL_RGB10: number;
    static GL_RGB10_A2: number;
    static GL_RGB12: number;
    static GL_RGB16: number;
    static GL_RGB4: number;
    static GL_RGB5: number;
    static GL_RGB5_A1: number;
    static GL_RGB8: number;
    static GL_RGBA: number;
    static GL_RGBA12: number;
    static GL_RGBA16: number;
    static GL_RGBA2: number;
    static GL_RGBA4: number;
    static GL_RGBA8: number;
    static GL_RIGHT: number;
    static GL_SCISSOR_BOX: number;
    static GL_SCISSOR_TEST: number;
    static GL_SET: number;
    static GL_SHORT: number;
    static GL_SRC_ALPHA: number;
    static GL_SRC_ALPHA_SATURATE: number;
    static GL_SRC_COLOR: number;
    static GL_STACK_OVERFLOW: number;
    static GL_STACK_UNDERFLOW: number;
    static GL_STENCIL: number;
    static GL_STENCIL_BUFFER_BIT: number;
    static GL_STENCIL_CLEAR_VALUE: number;
    static GL_STENCIL_FAIL: number;
    static GL_STENCIL_FUNC: number;
    static GL_STENCIL_INDEX: number;
    static GL_STENCIL_PASS_DEPTH_FAIL: number;
    static GL_STENCIL_PASS_DEPTH_PASS: number;
    static GL_STENCIL_REF: number;
    static GL_STENCIL_TEST: number;
    static GL_STENCIL_VALUE_MASK: number;
    static GL_STENCIL_WRITEMASK: number;
    static GL_STEREO: number;
    static GL_SUBPIXEL_BITS: number;
    static GL_TEXTURE: number;
    static GL_TEXTURE_1D: number;
    static GL_TEXTURE_2D: number;
    static GL_TEXTURE_ALPHA_SIZE: number;
    static GL_TEXTURE_BINDING_1D: number;
    static GL_TEXTURE_BINDING_2D: number;
    static GL_TEXTURE_BLUE_SIZE: number;
    static GL_TEXTURE_BORDER_COLOR: number;
    static GL_TEXTURE_GREEN_SIZE: number;
    static GL_TEXTURE_HEIGHT: number;
    static GL_TEXTURE_INTERNAL_FORMAT: number;
    static GL_TEXTURE_MAG_FILTER: number;
    static GL_TEXTURE_MIN_FILTER: number;
    static GL_TEXTURE_RED_SIZE: number;
    static GL_TEXTURE_WIDTH: number;
    static GL_TEXTURE_WRAP_S: number;
    static GL_TEXTURE_WRAP_T: number;
    static GL_TRIANGLES: number;
    static GL_TRIANGLE_FAN: number;
    static GL_TRIANGLE_STRIP: number;
    static GL_TRUE: number;
    static GL_UNPACK_ALIGNMENT: number;
    static GL_UNPACK_LSB_FIRST: number;
    static GL_UNPACK_ROW_LENGTH: number;
    static GL_UNPACK_SKIP_PIXELS: number;
    static GL_UNPACK_SKIP_ROWS: number;
    static GL_UNPACK_SWAP_BYTES: number;
    static GL_UNSIGNED_BYTE: number;
    static GL_UNSIGNED_INT: number;
    static GL_UNSIGNED_SHORT: number;
    static GL_VENDOR: number;
    static GL_VERSION: number;
    static GL_VERTEX_ARRAY: number;
    static GL_VIEWPORT: number;
    static GL_XOR: number;
    static GL_ZERO: number;
    static glBindTexture(paramarg0: number, paramarg1: number): void;
    static glBlendFunc(paramarg0: number, paramarg1: number): void;
    static glClear(paramarg0: number): void;
    static glClearColor(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glClearDepth(paramarg0: number): void;
    static glClearStencil(paramarg0: number): void;
    static glColorMask(paramarg0: boolean, paramarg1: boolean, paramarg2: boolean, paramarg3: boolean): void;
    static glCopyTexImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glCopyTexImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static glCopyTexSubImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glCopyTexSubImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static glCullFace(paramarg0: number): void;
    static glDeleteTextures(paramarg0: number): void;
    static glDeleteTextures(paramarg0: number[]): void;
    static glDeleteTextures(paramarg0: IntBuffer): void;
    static glDepthFunc(paramarg0: number): void;
    static glDepthMask(paramarg0: boolean): void;
    static glDepthRange(paramarg0: number, paramarg1: number): void;
    static glDisable(paramarg0: number): void;
    static glDrawArrays(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glDrawBuffer(paramarg0: number): void;
    static glDrawElements(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glDrawElements(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer): void;
    static glDrawElements(paramarg0: number, paramarg1: ByteBuffer): void;
    static glDrawElements(paramarg0: number, paramarg1: IntBuffer): void;
    static glDrawElements(paramarg0: number, paramarg1: ShortBuffer): void;
    static glEnable(paramarg0: number): void;
    static glFinish(): void;
    static glFlush(): void;
    static glFrontFace(paramarg0: number): void;
    static glGenTextures(): number;
    static glGenTextures(paramarg0: number[]): void;
    static glGenTextures(paramarg0: IntBuffer): void;
    static glGetBoolean(paramarg0: number): boolean;
    static glGetBooleanv(paramarg0: number, paramarg1: ByteBuffer): void;
    static glGetDouble(paramarg0: number): number;
    static glGetDoublev(paramarg0: number, paramarg1: number[]): void;
    static glGetDoublev(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glGetError(): number;
    static glGetFloat(paramarg0: number): number;
    static glGetFloatv(paramarg0: number, paramarg1: number[]): void;
    static glGetFloatv(paramarg0: number, paramarg1: FloatBuffer): void;
    static glGetInteger(paramarg0: number): number;
    static glGetIntegerv(paramarg0: number, paramarg1: number[]): void;
    static glGetIntegerv(paramarg0: number, paramarg1: IntBuffer): void;
    static glGetPointer(paramarg0: number): number;
    static glGetPointerv(paramarg0: number, paramarg1: PointerBuffer): void;
    static glGetString(paramarg0: number): string;
    static glGetTexImage(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[]): void;
    static glGetTexImage(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[]): void;
    static glGetTexImage(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[]): void;
    static glGetTexImage(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: ByteBuffer): void;
    static glGetTexImage(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: DoubleBuffer): void;
    static glGetTexImage(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: FloatBuffer): void;
    static glGetTexImage(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: IntBuffer): void;
    static glGetTexImage(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: ShortBuffer): void;
    static glGetTexImage(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glGetTexImage(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[]): void;
    static glGetTexLevelParameterf(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetTexLevelParameterfv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetTexLevelParameterfv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glGetTexLevelParameteri(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetTexLevelParameteriv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glGetTexLevelParameteriv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer): void;
    static glGetTexParameterf(paramarg0: number, paramarg1: number): number;
    static glGetTexParameterfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetTexParameterfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetTexParameteri(paramarg0: number, paramarg1: number): number;
    static glGetTexParameteriv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetTexParameteriv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glHint(paramarg0: number, paramarg1: number): void;
    static glIsEnabled(paramarg0: number): boolean;
    static glIsTexture(paramarg0: number): boolean;
    static glLineWidth(paramarg0: number): void;
    static glLogicOp(paramarg0: number): void;
    static glPixelStoref(paramarg0: number, paramarg1: number): void;
    static glPixelStorei(paramarg0: number, paramarg1: number): void;
    static glPointSize(paramarg0: number): void;
    static glPolygonMode(paramarg0: number, paramarg1: number): void;
    static glPolygonOffset(paramarg0: number, paramarg1: number): void;
    static glReadBuffer(paramarg0: number): void;
    static glReadPixels(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[]): void;
    static glReadPixels(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[]): void;
    static glReadPixels(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: ByteBuffer): void;
    static glReadPixels(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: FloatBuffer): void;
    static glReadPixels(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: IntBuffer): void;
    static glReadPixels(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: ShortBuffer): void;
    static glReadPixels(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glReadPixels(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[]): void;
    static glScissor(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glStencilFunc(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glStencilMask(paramarg0: number): void;
    static glStencilOp(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glTexImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number[]): void;
    static glTexImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number[]): void;
    static glTexImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number[]): void;
    static glTexImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: ByteBuffer): void;
    static glTexImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: DoubleBuffer): void;
    static glTexImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: FloatBuffer): void;
    static glTexImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: IntBuffer): void;
    static glTexImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: ShortBuffer): void;
    static glTexImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static glTexImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number[]): void;
    static glTexImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number[]): void;
    static glTexImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number[]): void;
    static glTexImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number[]): void;
    static glTexImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: ByteBuffer): void;
    static glTexImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: DoubleBuffer): void;
    static glTexImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: FloatBuffer): void;
    static glTexImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: IntBuffer): void;
    static glTexImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: ShortBuffer): void;
    static glTexImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static glTexImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number[]): void;
    static glTexParameterf(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glTexParameterfv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glTexParameterfv(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glTexParameteri(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glTexParameteriv(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glTexParameteriv(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glTexSubImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[]): void;
    static glTexSubImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[]): void;
    static glTexSubImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[]): void;
    static glTexSubImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: ByteBuffer): void;
    static glTexSubImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: DoubleBuffer): void;
    static glTexSubImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: FloatBuffer): void;
    static glTexSubImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: IntBuffer): void;
    static glTexSubImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: ShortBuffer): void;
    static glTexSubImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glTexSubImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[]): void;
    static glTexSubImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number[]): void;
    static glTexSubImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number[]): void;
    static glTexSubImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number[]): void;
    static glTexSubImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: ByteBuffer): void;
    static glTexSubImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: DoubleBuffer): void;
    static glTexSubImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: FloatBuffer): void;
    static glTexSubImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: IntBuffer): void;
    static glTexSubImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: ShortBuffer): void;
    static glTexSubImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static glTexSubImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number[]): void;
    static glViewport(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglDeleteTextures(paramarg0: number, paramarg1: number): void;
    static nglDrawElements(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGenTextures(paramarg0: number, paramarg1: number): void;
    static nglGetBooleanv(paramarg0: number, paramarg1: number): void;
    static nglGetDoublev(paramarg0: number, paramarg1: number): void;
    static nglGetFloatv(paramarg0: number, paramarg1: number): void;
    static nglGetIntegerv(paramarg0: number, paramarg1: number): void;
    static nglGetPointerv(paramarg0: number, paramarg1: number): void;
    static nglGetString(paramarg0: number): number;
    static nglGetTexImage(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglGetTexLevelParameterfv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetTexLevelParameteriv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetTexParameterfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetTexParameteriv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglReadPixels(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nglTexImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nglTexImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static nglTexParameterfv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglTexParameteriv(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglTexSubImage1D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nglTexSubImage2D(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    constructor()
}