import type { JavaMap } from '../../../../JavaMap.d.ts'
import type { Optional } from '../../../../com/google/common/base/Optional.d.ts'
import type { ImmutableListMultimap } from '../../../../com/google/common/collect/ImmutableListMultimap.d.ts'
import type { Multimap } from '../../../../com/google/common/collect/Multimap.d.ts'
import type { Charset } from '../../../../java/nio/charset/Charset.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
export class MediaType extends Object {
    static AAC_AUDIO: MediaType;
    static ANY_APPLICATION_TYPE: MediaType;
    static ANY_AUDIO_TYPE: MediaType;
    static ANY_FONT_TYPE: MediaType;
    static ANY_IMAGE_TYPE: MediaType;
    static ANY_TEXT_TYPE: MediaType;
    static ANY_TYPE: MediaType;
    static ANY_VIDEO_TYPE: MediaType;
    static APPLE_MOBILE_CONFIG: MediaType;
    static APPLE_PASSBOOK: MediaType;
    static APPLICATION_BINARY: MediaType;
    static APPLICATION_XML_UTF_8: MediaType;
    static ATOM_UTF_8: MediaType;
    static AVIF: MediaType;
    static BASIC_AUDIO: MediaType;
    static BMP: MediaType;
    static BZIP2: MediaType;
    static CACHE_MANIFEST_UTF_8: MediaType;
    static CBOR: MediaType;
    static CRW: MediaType;
    static CSS_UTF_8: MediaType;
    static CSV_UTF_8: MediaType;
    static DART_UTF_8: MediaType;
    static EOT: MediaType;
    static EPUB: MediaType;
    static FLV_VIDEO: MediaType;
    static FONT_COLLECTION: MediaType;
    static FONT_OTF: MediaType;
    static FONT_SFNT: MediaType;
    static FONT_TTF: MediaType;
    static FONT_WOFF: MediaType;
    static FONT_WOFF2: MediaType;
    static FORM_DATA: MediaType;
    static GEO_JSON: MediaType;
    static GIF: MediaType;
    static GZIP: MediaType;
    static HAL_JSON: MediaType;
    static HEIF: MediaType;
    static HTML_UTF_8: MediaType;
    static ICO: MediaType;
    static I_CALENDAR_UTF_8: MediaType;
    static JAVASCRIPT_UTF_8: MediaType;
    static JOSE: MediaType;
    static JOSE_JSON: MediaType;
    static JP2K: MediaType;
    static JPEG: MediaType;
    static JSON_UTF_8: MediaType;
    static JWT: MediaType;
    static KEY_ARCHIVE: MediaType;
    static KML: MediaType;
    static KMZ: MediaType;
    static L16_AUDIO: MediaType;
    static L24_AUDIO: MediaType;
    static MANIFEST_JSON_UTF_8: MediaType;
    static MBOX: MediaType;
    static MD_UTF_8: MediaType;
    static MEDIA_PRESENTATION_DESCRIPTION: MediaType;
    static MICROSOFT_EXCEL: MediaType;
    static MICROSOFT_OUTLOOK: MediaType;
    static MICROSOFT_POWERPOINT: MediaType;
    static MICROSOFT_WORD: MediaType;
    static MP4_AUDIO: MediaType;
    static MP4_VIDEO: MediaType;
    static MPEG_AUDIO: MediaType;
    static MPEG_VIDEO: MediaType;
    static NACL_APPLICATION: MediaType;
    static NACL_PORTABLE_APPLICATION: MediaType;
    static OCTET_STREAM: MediaType;
    static OGG_AUDIO: MediaType;
    static OGG_CONTAINER: MediaType;
    static OGG_VIDEO: MediaType;
    static OOXML_DOCUMENT: MediaType;
    static OOXML_PRESENTATION: MediaType;
    static OOXML_SHEET: MediaType;
    static OPENDOCUMENT_GRAPHICS: MediaType;
    static OPENDOCUMENT_PRESENTATION: MediaType;
    static OPENDOCUMENT_SPREADSHEET: MediaType;
    static OPENDOCUMENT_TEXT: MediaType;
    static OPENSEARCH_DESCRIPTION_UTF_8: MediaType;
    static PDF: MediaType;
    static PLAIN_TEXT_UTF_8: MediaType;
    static PNG: MediaType;
    static POSTSCRIPT: MediaType;
    static PROTOBUF: MediaType;
    static PSD: MediaType;
    static QUICKTIME: MediaType;
    static RDF_XML_UTF_8: MediaType;
    static RTF_UTF_8: MediaType;
    static SFNT: MediaType;
    static SHOCKWAVE_FLASH: MediaType;
    static SKETCHUP: MediaType;
    static SOAP_XML_UTF_8: MediaType;
    static SVG_UTF_8: MediaType;
    static TAR: MediaType;
    static TEXT_JAVASCRIPT_UTF_8: MediaType;
    static THREE_GPP2_VIDEO: MediaType;
    static THREE_GPP_VIDEO: MediaType;
    static TIFF: MediaType;
    static TSV_UTF_8: MediaType;
    static VCARD_UTF_8: MediaType;
    static VND_REAL_AUDIO: MediaType;
    static VND_WAVE_AUDIO: MediaType;
    static VORBIS_AUDIO: MediaType;
    static VTT_UTF_8: MediaType;
    static WASM_APPLICATION: MediaType;
    static WAX_AUDIO: MediaType;
    static WEBM_AUDIO: MediaType;
    static WEBM_VIDEO: MediaType;
    static WEBP: MediaType;
    static WMA_AUDIO: MediaType;
    static WML_UTF_8: MediaType;
    static WMV: MediaType;
    static WOFF: MediaType;
    static WOFF2: MediaType;
    static XHTML_UTF_8: MediaType;
    static XML_UTF_8: MediaType;
    static XRD_UTF_8: MediaType;
    static ZIP: MediaType;
    static create(paramtype: string, paramsubtype: string): MediaType;
    static parse(paraminput: string): MediaType;
    private constructor(type: string, subtype: string, parameters: ImmutableListMultimap<string, string>)
    // private hashCode: number;
    // private parameters: ImmutableListMultimap<string, string>;
    // private parsedCharset: Optional<Charset>;
    // private subtype: string;
    // private toString: string;
    // private type: string;
    charset(): Optional<Charset>;
    // private computeToString(): string;
    equals(obj: Object | null): boolean;
    hasWildcard(): boolean;
    hashCode(): number;
    is(mediaTypeRange: MediaType): boolean;
    parameters(): ImmutableListMultimap<string, string>;
    // private parametersAsMap(): JavaMap<string, string[]>;
    subtype(): string;
    toString(): string;
    type(): string;
    withCharset(charset: Charset): MediaType;
    withParameter(attribute: string, value: string): MediaType;
    withParameters(parameters: Multimap<string, string>): MediaType;
    withParameters(attribute: string, values: string[]): MediaType;
    withoutParameters(): MediaType;
}