import type { Object } from '../../../java/lang/Object.d.ts'
export class AMDXDenseGeometryFormat extends Object {
    static VK_AMDX_DENSE_GEOMETRY_FORMAT_EXTENSION_NAME: string;
    static VK_AMDX_DENSE_GEOMETRY_FORMAT_SPEC_VERSION: number;
    static VK_BUFFER_USAGE_2_COMPRESSED_DATA_DGF1_BIT_AMDX: number;
    static VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_AMDX: number;
    static VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_BYTE_ALIGNMENT_AMDX: number;
    static VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_BYTE_STRIDE_AMDX: number;
    static VK_GEOMETRY_TYPE_DENSE_GEOMETRY_FORMAT_TRIANGLES_AMDX: number;
    static VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_DENSE_GEOMETRY_FORMAT_TRIANGLES_DATA_AMDX: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DENSE_GEOMETRY_FORMAT_FEATURES_AMDX: number;
    private constructor()
}