import type { Object } from '../../../java/lang/Object.d.ts'
export class ANDROIDExternalFormatResolve extends Object {
    static VK_ANDROID_EXTERNAL_FORMAT_RESOLVE_EXTENSION_NAME: string;
    static VK_ANDROID_EXTERNAL_FORMAT_RESOLVE_SPEC_VERSION: number;
    static VK_RESOLVE_MODE_EXTERNAL_FORMAT_DOWNSAMPLE_ANDROID: number;
    static VK_RESOLVE_MODE_EXTERNAL_FORMAT_DOWNSAMPLE_BIT_ANDROID: number;
    static VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_FORMAT_RESOLVE_PROPERTIES_ANDROID: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FORMAT_RESOLVE_FEATURES_ANDROID: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FORMAT_RESOLVE_PROPERTIES_ANDROID: number;
    private constructor()
}