import type { Object } from '../../../java/lang/Object.d.ts'
export class EXTConservativeRasterization extends Object {
    static VK_CONSERVATIVE_RASTERIZATION_MODE_DISABLED_EXT: number;
    static VK_CONSERVATIVE_RASTERIZATION_MODE_OVERESTIMATE_EXT: number;
    static VK_CONSERVATIVE_RASTERIZATION_MODE_UNDERESTIMATE_EXT: number;
    static VK_EXT_CONSERVATIVE_RASTERIZATION_EXTENSION_NAME: string;
    static VK_EXT_CONSERVATIVE_RASTERIZATION_SPEC_VERSION: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CONSERVATIVE_RASTERIZATION_PROPERTIES_EXT: number;
    static VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_CONSERVATIVE_STATE_CREATE_INFO_EXT: number;
    private constructor()
}