import type { Object } from '../../../java/lang/Object.d.ts'
export class EXTDeviceMemoryReport extends Object {
    static VK_DEVICE_MEMORY_REPORT_EVENT_TYPE_ALLOCATE_EXT: number;
    static VK_DEVICE_MEMORY_REPORT_EVENT_TYPE_ALLOCATION_FAILED_EXT: number;
    static VK_DEVICE_MEMORY_REPORT_EVENT_TYPE_FREE_EXT: number;
    static VK_DEVICE_MEMORY_REPORT_EVENT_TYPE_IMPORT_EXT: number;
    static VK_DEVICE_MEMORY_REPORT_EVENT_TYPE_UNIMPORT_EXT: number;
    static VK_EXT_DEVICE_MEMORY_REPORT_EXTENSION_NAME: string;
    static VK_EXT_DEVICE_MEMORY_REPORT_SPEC_VERSION: number;
    static VK_STRUCTURE_TYPE_DEVICE_DEVICE_MEMORY_REPORT_CREATE_INFO_EXT: number;
    static VK_STRUCTURE_TYPE_DEVICE_MEMORY_REPORT_CALLBACK_DATA_EXT: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEVICE_MEMORY_REPORT_FEATURES_EXT: number;
    private constructor()
}