import type { Object } from '../../../java/lang/Object.d.ts'
export class EXTDescriptorIndexing extends Object {
    static VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT: number;
    static VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT: number;
    static VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT_EXT: number;
    static VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT: number;
    static VK_DESCRIPTOR_POOL_CREATE_UPDATE_AFTER_BIND_BIT_EXT: number;
    static VK_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT_EXT: number;
    static VK_ERROR_FRAGMENTATION_EXT: number;
    static VK_EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME: string;
    static VK_EXT_DESCRIPTOR_INDEXING_SPEC_VERSION: number;
    static VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO_EXT: number;
    static VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO_EXT: number;
    static VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT_EXT: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES_EXT: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES_EXT: number;
    private constructor()
}