import type { Object } from '../../../java/lang/Object.d.ts'
export class EXTGraphicsPipelineLibrary extends Object {
    static VK_EXT_GRAPHICS_PIPELINE_LIBRARY_EXTENSION_NAME: string;
    static VK_EXT_GRAPHICS_PIPELINE_LIBRARY_SPEC_VERSION: number;
    static VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_OUTPUT_INTERFACE_BIT_EXT: number;
    static VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_SHADER_BIT_EXT: number;
    static VK_GRAPHICS_PIPELINE_LIBRARY_PRE_RASTERIZATION_SHADERS_BIT_EXT: number;
    static VK_GRAPHICS_PIPELINE_LIBRARY_VERTEX_INPUT_INTERFACE_BIT_EXT: number;
    static VK_PIPELINE_CREATE_LINK_TIME_OPTIMIZATION_BIT_EXT: number;
    static VK_PIPELINE_CREATE_RETAIN_LINK_TIME_OPTIMIZATION_INFO_BIT_EXT: number;
    static VK_PIPELINE_LAYOUT_CREATE_INDEPENDENT_SETS_BIT_EXT: number;
    static VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_LIBRARY_CREATE_INFO_EXT: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GRAPHICS_PIPELINE_LIBRARY_FEATURES_EXT: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GRAPHICS_PIPELINE_LIBRARY_PROPERTIES_EXT: number;
    private constructor()
}