import type { Object } from '../../../java/lang/Object.d.ts'
export class EXTSubgroupSizeControl extends Object {
    static VK_EXT_SUBGROUP_SIZE_CONTROL_EXTENSION_NAME: string;
    static VK_EXT_SUBGROUP_SIZE_CONTROL_SPEC_VERSION: number;
    static VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT: number;
    static VK_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT_EXT: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_SIZE_CONTROL_FEATURES_EXT: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_SIZE_CONTROL_PROPERTIES_EXT: number;
    static VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_REQUIRED_SUBGROUP_SIZE_CREATE_INFO_EXT: number;
    private constructor()
}