import type { Object } from '../../../java/lang/Object.d.ts'
export class EXTSubpassMergeFeedback extends Object {
    static VK_EXT_SUBPASS_MERGE_FEEDBACK_EXTENSION_NAME: string;
    static VK_EXT_SUBPASS_MERGE_FEEDBACK_SPEC_VERSION: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBPASS_MERGE_FEEDBACK_FEATURES_EXT: number;
    static VK_STRUCTURE_TYPE_RENDER_PASS_CREATION_CONTROL_EXT: number;
    static VK_STRUCTURE_TYPE_RENDER_PASS_CREATION_FEEDBACK_CREATE_INFO_EXT: number;
    static VK_STRUCTURE_TYPE_RENDER_PASS_SUBPASS_FEEDBACK_CREATE_INFO_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_DISALLOWED_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_MERGED_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_NOT_MERGED_ALIASING_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_NOT_MERGED_DEPENDENCIES_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_NOT_MERGED_DEPTH_STENCIL_COUNT_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_NOT_MERGED_INCOMPATIBLE_INPUT_ATTACHMENT_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_NOT_MERGED_INSUFFICIENT_STORAGE_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_NOT_MERGED_RESOLVE_ATTACHMENT_REUSE_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_NOT_MERGED_SAMPLES_MISMATCH_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_NOT_MERGED_SIDE_EFFECTS_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_NOT_MERGED_SINGLE_SUBPASS_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_NOT_MERGED_TOO_MANY_ATTACHMENTS_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_NOT_MERGED_UNSPECIFIED_EXT: number;
    static VK_SUBPASS_MERGE_STATUS_NOT_MERGED_VIEWS_MISMATCH_EXT: number;
    private constructor()
}