import type { Object } from '../../../java/lang/Object.d.ts'
export class KHRFormatFeatureFlags2 extends Object {
    static VK_FORMAT_FEATURE_2_BLIT_DST_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_BLIT_SRC_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BLEND_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_COSITED_CHROMA_SAMPLES_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_DEPTH_STENCIL_ATTACHMENT_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_DISJOINT_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_MIDPOINT_CHROMA_SAMPLES_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_DEPTH_COMPARISON_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_FILTER_CUBIC_BIT_EXT: number;
    static VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_FILTER_LINEAR_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_FILTER_MINMAX_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_STORAGE_IMAGE_ATOMIC_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_STORAGE_IMAGE_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_STORAGE_TEXEL_BUFFER_ATOMIC_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_STORAGE_TEXEL_BUFFER_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_TRANSFER_DST_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_TRANSFER_SRC_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_UNIFORM_TEXEL_BUFFER_BIT_KHR: number;
    static VK_FORMAT_FEATURE_2_VERTEX_BUFFER_BIT_KHR: number;
    static VK_KHR_FORMAT_FEATURE_FLAGS_2_EXTENSION_NAME: string;
    static VK_KHR_FORMAT_FEATURE_FLAGS_2_SPEC_VERSION: number;
    static VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_3_KHR: number;
    private constructor()
}