import type { Object } from '../../../java/lang/Object.d.ts'
export class KHRMaintenance2 extends Object {
    static VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT_KHR: number;
    static VK_IMAGE_CREATE_EXTENDED_USAGE_BIT_KHR: number;
    static VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR: number;
    static VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR: number;
    static VK_KHR_MAINTENANCE2_EXTENSION_NAME: string;
    static VK_KHR_MAINTENANCE2_SPEC_VERSION: number;
    static VK_KHR_MAINTENANCE_2_EXTENSION_NAME: string;
    static VK_KHR_MAINTENANCE_2_SPEC_VERSION: number;
    static VK_POINT_CLIPPING_BEHAVIOR_ALL_CLIP_PLANES_KHR: number;
    static VK_POINT_CLIPPING_BEHAVIOR_USER_CLIP_PLANES_ONLY_KHR: number;
    static VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO_KHR: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES_KHR: number;
    static VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO_KHR: number;
    static VK_STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO_KHR: number;
    static VK_TESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT_KHR: number;
    static VK_TESSELLATION_DOMAIN_ORIGIN_UPPER_LEFT_KHR: number;
    private constructor()
}