import type { Object } from '../../../java/lang/Object.d.ts'
export class KHRVideoDecodeH265 extends Object {
    static VK_KHR_VIDEO_DECODE_H265_EXTENSION_NAME: string;
    static VK_KHR_VIDEO_DECODE_H265_SPEC_VERSION: number;
    static VK_STRUCTURE_TYPE_VIDEO_DECODE_H265_CAPABILITIES_KHR: number;
    static VK_STRUCTURE_TYPE_VIDEO_DECODE_H265_DPB_SLOT_INFO_KHR: number;
    static VK_STRUCTURE_TYPE_VIDEO_DECODE_H265_PICTURE_INFO_KHR: number;
    static VK_STRUCTURE_TYPE_VIDEO_DECODE_H265_PROFILE_INFO_KHR: number;
    static VK_STRUCTURE_TYPE_VIDEO_DECODE_H265_SESSION_PARAMETERS_ADD_INFO_KHR: number;
    static VK_STRUCTURE_TYPE_VIDEO_DECODE_H265_SESSION_PARAMETERS_CREATE_INFO_KHR: number;
    static VK_VIDEO_CODEC_OPERATION_DECODE_H265_BIT_KHR: number;
    private constructor()
}