import type { Object } from '../../../java/lang/Object.d.ts'
export class KHRVideoMaintenance2 extends Object {
    static VK_KHR_VIDEO_MAINTENANCE_2_EXTENSION_NAME: string;
    static VK_KHR_VIDEO_MAINTENANCE_2_SPEC_VERSION: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VIDEO_MAINTENANCE_2_FEATURES_KHR: number;
    static VK_STRUCTURE_TYPE_VIDEO_DECODE_AV1_INLINE_SESSION_PARAMETERS_INFO_KHR: number;
    static VK_STRUCTURE_TYPE_VIDEO_DECODE_H264_INLINE_SESSION_PARAMETERS_INFO_KHR: number;
    static VK_STRUCTURE_TYPE_VIDEO_DECODE_H265_INLINE_SESSION_PARAMETERS_INFO_KHR: number;
    static VK_VIDEO_SESSION_CREATE_INLINE_SESSION_PARAMETERS_BIT_KHR: number;
    private constructor()
}