import type { Object } from '../../../java/lang/Object.d.ts'
export class NVDeviceDiagnosticsConfig extends Object {
    static VK_DEVICE_DIAGNOSTICS_CONFIG_ENABLE_AUTOMATIC_CHECKPOINTS_BIT_NV: number;
    static VK_DEVICE_DIAGNOSTICS_CONFIG_ENABLE_RESOURCE_TRACKING_BIT_NV: number;
    static VK_DEVICE_DIAGNOSTICS_CONFIG_ENABLE_SHADER_DEBUG_INFO_BIT_NV: number;
    static VK_DEVICE_DIAGNOSTICS_CONFIG_ENABLE_SHADER_ERROR_REPORTING_BIT_NV: number;
    static VK_NV_DEVICE_DIAGNOSTICS_CONFIG_EXTENSION_NAME: string;
    static VK_NV_DEVICE_DIAGNOSTICS_CONFIG_SPEC_VERSION: number;
    static VK_STRUCTURE_TYPE_DEVICE_DIAGNOSTICS_CONFIG_CREATE_INFO_NV: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DIAGNOSTICS_CONFIG_FEATURES_NV: number;
    private constructor()
}