import type { Object } from '../../../java/lang/Object.d.ts'
export class NVRayTracingMotionBlur extends Object {
    static VK_ACCELERATION_STRUCTURE_CREATE_MOTION_BIT_NV: number;
    static VK_ACCELERATION_STRUCTURE_MOTION_INSTANCE_TYPE_MATRIX_MOTION_NV: number;
    static VK_ACCELERATION_STRUCTURE_MOTION_INSTANCE_TYPE_SRT_MOTION_NV: number;
    static VK_ACCELERATION_STRUCTURE_MOTION_INSTANCE_TYPE_STATIC_NV: number;
    static VK_BUILD_ACCELERATION_STRUCTURE_MOTION_BIT_NV: number;
    static VK_NV_RAY_TRACING_MOTION_BLUR_EXTENSION_NAME: string;
    static VK_NV_RAY_TRACING_MOTION_BLUR_SPEC_VERSION: number;
    static VK_PIPELINE_CREATE_RAY_TRACING_ALLOW_MOTION_BIT_NV: number;
    static VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_MOTION_TRIANGLES_DATA_NV: number;
    static VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_MOTION_INFO_NV: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_MOTION_BLUR_FEATURES_NV: number;
    private constructor()
}