import type { Object } from '../../../java/lang/Object.d.ts'
export class NVRayTracingLinearSweptSpheres extends Object {
    static VK_FORMAT_FEATURE_2_ACCELERATION_STRUCTURE_RADIUS_BUFFER_BIT_NV: number;
    static VK_GEOMETRY_TYPE_LINEAR_SWEPT_SPHERES_NV: number;
    static VK_GEOMETRY_TYPE_SPHERES_NV: number;
    static VK_NV_RAY_TRACING_LINEAR_SWEPT_SPHERES_EXTENSION_NAME: string;
    static VK_NV_RAY_TRACING_LINEAR_SWEPT_SPHERES_SPEC_VERSION: number;
    static VK_PIPELINE_CREATE_2_RAY_TRACING_ALLOW_SPHERES_AND_LINEAR_SWEPT_SPHERES_BIT_NV: number;
    static VK_RAY_TRACING_LSS_INDEXING_MODE_LIST_NV: number;
    static VK_RAY_TRACING_LSS_INDEXING_MODE_SUCCESSIVE_NV: number;
    static VK_RAY_TRACING_LSS_PRIMITIVE_END_CAPS_MODE_CHAINED_NV: number;
    static VK_RAY_TRACING_LSS_PRIMITIVE_END_CAPS_MODE_NONE_NV: number;
    static VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_LINEAR_SWEPT_SPHERES_DATA_NV: number;
    static VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_SPHERES_DATA_NV: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_LINEAR_SWEPT_SPHERES_FEATURES_NV: number;
    private constructor()
}