import type { Object } from '../../../java/lang/Object.d.ts'
export class NVRayTracingInvocationReorder extends Object {
    static VK_NV_RAY_TRACING_INVOCATION_REORDER_EXTENSION_NAME: string;
    static VK_NV_RAY_TRACING_INVOCATION_REORDER_SPEC_VERSION: number;
    static VK_RAY_TRACING_INVOCATION_REORDER_MODE_NONE_EXT: number;
    static VK_RAY_TRACING_INVOCATION_REORDER_MODE_NONE_NV: number;
    static VK_RAY_TRACING_INVOCATION_REORDER_MODE_REORDER_EXT: number;
    static VK_RAY_TRACING_INVOCATION_REORDER_MODE_REORDER_NV: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_INVOCATION_REORDER_FEATURES_NV: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_INVOCATION_REORDER_PROPERTIES_NV: number;
    private constructor()
}