import type { Object } from '../../../java/lang/Object.d.ts'
export class QCOMDataGraphModel extends Object {
    static VK_DATA_GRAPH_MODEL_CACHE_TYPE_GENERIC_BINARY_QCOM: number;
    static VK_DATA_GRAPH_MODEL_TOOLCHAIN_VERSION_LENGTH_QCOM: number;
    static VK_PHYSICAL_DEVICE_DATA_GRAPH_OPERATION_TYPE_BUILTIN_MODEL_QCOM: number;
    static VK_PHYSICAL_DEVICE_DATA_GRAPH_OPERATION_TYPE_NEURAL_MODEL_QCOM: number;
    static VK_PHYSICAL_DEVICE_DATA_GRAPH_PROCESSING_ENGINE_TYPE_COMPUTE_QCOM: number;
    static VK_PHYSICAL_DEVICE_DATA_GRAPH_PROCESSING_ENGINE_TYPE_NEURAL_QCOM: number;
    static VK_PIPELINE_CACHE_HEADER_VERSION_DATA_GRAPH_QCOM: number;
    static VK_QCOM_DATA_GRAPH_MODEL_EXTENSION_NAME: string;
    static VK_QCOM_DATA_GRAPH_MODEL_SPEC_VERSION: number;
    static VK_STRUCTURE_TYPE_DATA_GRAPH_PIPELINE_BUILTIN_MODEL_CREATE_INFO_QCOM: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DATA_GRAPH_MODEL_FEATURES_QCOM: number;
    private constructor()
}