import type { Object } from '../../../java/lang/Object.d.ts'
export class VALVEFragmentDensityMapLayered extends Object {
    static VK_PIPELINE_CREATE_2_PER_LAYER_FRAGMENT_DENSITY_BIT_VALVE: number;
    static VK_RENDERING_PER_LAYER_FRAGMENT_DENSITY_BIT_VALVE: number;
    static VK_RENDER_PASS_CREATE_PER_LAYER_FRAGMENT_DENSITY_BIT_VALVE: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_LAYERED_FEATURES_VALVE: number;
    static VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_LAYERED_PROPERTIES_VALVE: number;
    static VK_STRUCTURE_TYPE_PIPELINE_FRAGMENT_DENSITY_MAP_LAYERED_CREATE_INFO_VALVE: number;
    static VK_VALVE_FRAGMENT_DENSITY_MAP_LAYERED_EXTENSION_NAME: string;
    static VK_VALVE_FRAGMENT_DENSITY_MAP_LAYERED_SPEC_VERSION: number;
    private constructor()
}