import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class VkPhysicalDeviceDescriptorIndexingProperties extends Struct<VkPhysicalDeviceDescriptorIndexingProperties> implements NativeResource {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static MAXDESCRIPTORSETUPDATEAFTERBINDINPUTATTACHMENTS: number;
    static MAXDESCRIPTORSETUPDATEAFTERBINDSAMPLEDIMAGES: number;
    static MAXDESCRIPTORSETUPDATEAFTERBINDSAMPLERS: number;
    static MAXDESCRIPTORSETUPDATEAFTERBINDSTORAGEBUFFERS: number;
    static MAXDESCRIPTORSETUPDATEAFTERBINDSTORAGEBUFFERSDYNAMIC: number;
    static MAXDESCRIPTORSETUPDATEAFTERBINDSTORAGEIMAGES: number;
    static MAXDESCRIPTORSETUPDATEAFTERBINDUNIFORMBUFFERS: number;
    static MAXDESCRIPTORSETUPDATEAFTERBINDUNIFORMBUFFERSDYNAMIC: number;
    static MAXPERSTAGEDESCRIPTORUPDATEAFTERBINDINPUTATTACHMENTS: number;
    static MAXPERSTAGEDESCRIPTORUPDATEAFTERBINDSAMPLEDIMAGES: number;
    static MAXPERSTAGEDESCRIPTORUPDATEAFTERBINDSAMPLERS: number;
    static MAXPERSTAGEDESCRIPTORUPDATEAFTERBINDSTORAGEBUFFERS: number;
    static MAXPERSTAGEDESCRIPTORUPDATEAFTERBINDSTORAGEIMAGES: number;
    static MAXPERSTAGEDESCRIPTORUPDATEAFTERBINDUNIFORMBUFFERS: number;
    static MAXPERSTAGEUPDATEAFTERBINDRESOURCES: number;
    static MAXUPDATEAFTERBINDDESCRIPTORSINALLPOOLS: number;
    static PNEXT: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static QUADDIVERGENTIMPLICITLOD: number;
    static ROBUSTBUFFERACCESSUPDATEAFTERBIND: number;
    static SHADERINPUTATTACHMENTARRAYNONUNIFORMINDEXINGNATIVE: number;
    static SHADERSAMPLEDIMAGEARRAYNONUNIFORMINDEXINGNATIVE: number;
    static SHADERSTORAGEBUFFERARRAYNONUNIFORMINDEXINGNATIVE: number;
    static SHADERSTORAGEIMAGEARRAYNONUNIFORMINDEXINGNATIVE: number;
    static SHADERUNIFORMBUFFERARRAYNONUNIFORMINDEXINGNATIVE: number;
    static SIZEOF: number;
    static STYPE: number;
    static calloc(): VkPhysicalDeviceDescriptorIndexingProperties;
    static calloc(paramarg0: MemoryStack): VkPhysicalDeviceDescriptorIndexingProperties;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): VkPhysicalDeviceDescriptorIndexingProperties;
    static create(paramarg0: number): VkPhysicalDeviceDescriptorIndexingProperties;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): VkPhysicalDeviceDescriptorIndexingProperties;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): VkPhysicalDeviceDescriptorIndexingProperties;
    static malloc(paramarg0: MemoryStack): VkPhysicalDeviceDescriptorIndexingProperties;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static nmaxDescriptorSetUpdateAfterBindInputAttachments(paramarg0: number): number;
    static nmaxDescriptorSetUpdateAfterBindSampledImages(paramarg0: number): number;
    static nmaxDescriptorSetUpdateAfterBindSamplers(paramarg0: number): number;
    static nmaxDescriptorSetUpdateAfterBindStorageBuffers(paramarg0: number): number;
    static nmaxDescriptorSetUpdateAfterBindStorageBuffersDynamic(paramarg0: number): number;
    static nmaxDescriptorSetUpdateAfterBindStorageImages(paramarg0: number): number;
    static nmaxDescriptorSetUpdateAfterBindUniformBuffers(paramarg0: number): number;
    static nmaxDescriptorSetUpdateAfterBindUniformBuffersDynamic(paramarg0: number): number;
    static nmaxPerStageDescriptorUpdateAfterBindInputAttachments(paramarg0: number): number;
    static nmaxPerStageDescriptorUpdateAfterBindSampledImages(paramarg0: number): number;
    static nmaxPerStageDescriptorUpdateAfterBindSamplers(paramarg0: number): number;
    static nmaxPerStageDescriptorUpdateAfterBindStorageBuffers(paramarg0: number): number;
    static nmaxPerStageDescriptorUpdateAfterBindStorageImages(paramarg0: number): number;
    static nmaxPerStageDescriptorUpdateAfterBindUniformBuffers(paramarg0: number): number;
    static nmaxPerStageUpdateAfterBindResources(paramarg0: number): number;
    static nmaxUpdateAfterBindDescriptorsInAllPools(paramarg0: number): number;
    static npNext(paramarg0: number): number;
    static npNext(paramarg0: number, paramarg1: number): void;
    static nquadDivergentImplicitLod(paramarg0: number): number;
    static nrobustBufferAccessUpdateAfterBind(paramarg0: number): number;
    static nsType(paramarg0: number): number;
    static nsType(paramarg0: number, paramarg1: number): void;
    static nshaderInputAttachmentArrayNonUniformIndexingNative(paramarg0: number): number;
    static nshaderSampledImageArrayNonUniformIndexingNative(paramarg0: number): number;
    static nshaderStorageBufferArrayNonUniformIndexingNative(paramarg0: number): number;
    static nshaderStorageImageArrayNonUniformIndexingNative(paramarg0: number): number;
    static nshaderUniformBufferArrayNonUniformIndexingNative(paramarg0: number): number;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    close(): void;
    create(arg0: number, arg1: ByteBuffer): VkPhysicalDeviceDescriptorIndexingProperties;
    maxDescriptorSetUpdateAfterBindInputAttachments(): number;
    maxDescriptorSetUpdateAfterBindSampledImages(): number;
    maxDescriptorSetUpdateAfterBindSamplers(): number;
    maxDescriptorSetUpdateAfterBindStorageBuffers(): number;
    maxDescriptorSetUpdateAfterBindStorageBuffersDynamic(): number;
    maxDescriptorSetUpdateAfterBindStorageImages(): number;
    maxDescriptorSetUpdateAfterBindUniformBuffers(): number;
    maxDescriptorSetUpdateAfterBindUniformBuffersDynamic(): number;
    maxPerStageDescriptorUpdateAfterBindInputAttachments(): number;
    maxPerStageDescriptorUpdateAfterBindSampledImages(): number;
    maxPerStageDescriptorUpdateAfterBindSamplers(): number;
    maxPerStageDescriptorUpdateAfterBindStorageBuffers(): number;
    maxPerStageDescriptorUpdateAfterBindStorageImages(): number;
    maxPerStageDescriptorUpdateAfterBindUniformBuffers(): number;
    maxPerStageUpdateAfterBindResources(): number;
    maxUpdateAfterBindDescriptorsInAllPools(): number;
    pNext(): number;
    pNext(arg0: number): VkPhysicalDeviceDescriptorIndexingProperties;
    quadDivergentImplicitLod(): boolean;
    robustBufferAccessUpdateAfterBind(): boolean;
    sType(): number;
    sType(arg0: number): VkPhysicalDeviceDescriptorIndexingProperties;
    sType$Default(): VkPhysicalDeviceDescriptorIndexingProperties;
    set(arg0: number, arg1: number): VkPhysicalDeviceDescriptorIndexingProperties;
    set(arg0: VkPhysicalDeviceDescriptorIndexingProperties): VkPhysicalDeviceDescriptorIndexingProperties;
    shaderInputAttachmentArrayNonUniformIndexingNative(): boolean;
    shaderSampledImageArrayNonUniformIndexingNative(): boolean;
    shaderStorageBufferArrayNonUniformIndexingNative(): boolean;
    shaderStorageImageArrayNonUniformIndexingNative(): boolean;
    shaderUniformBufferArrayNonUniformIndexingNative(): boolean;
    sizeof(): number;
}