import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { FloatBuffer } from '../../../java/nio/FloatBuffer.d.ts'
import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { Struct } from '../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class VkPhysicalDeviceLimits extends Struct<VkPhysicalDeviceLimits> {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static BUFFERIMAGEGRANULARITY: number;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static DISCRETEQUEUEPRIORITIES: number;
    static FRAMEBUFFERCOLORSAMPLECOUNTS: number;
    static FRAMEBUFFERDEPTHSAMPLECOUNTS: number;
    static FRAMEBUFFERNOATTACHMENTSSAMPLECOUNTS: number;
    static FRAMEBUFFERSTENCILSAMPLECOUNTS: number;
    static LINEWIDTHGRANULARITY: number;
    static LINEWIDTHRANGE: number;
    static MAXBOUNDDESCRIPTORSETS: number;
    static MAXCLIPDISTANCES: number;
    static MAXCOLORATTACHMENTS: number;
    static MAXCOMBINEDCLIPANDCULLDISTANCES: number;
    static MAXCOMPUTESHAREDMEMORYSIZE: number;
    static MAXCOMPUTEWORKGROUPCOUNT: number;
    static MAXCOMPUTEWORKGROUPINVOCATIONS: number;
    static MAXCOMPUTEWORKGROUPSIZE: number;
    static MAXCULLDISTANCES: number;
    static MAXDESCRIPTORSETINPUTATTACHMENTS: number;
    static MAXDESCRIPTORSETSAMPLEDIMAGES: number;
    static MAXDESCRIPTORSETSAMPLERS: number;
    static MAXDESCRIPTORSETSTORAGEBUFFERS: number;
    static MAXDESCRIPTORSETSTORAGEBUFFERSDYNAMIC: number;
    static MAXDESCRIPTORSETSTORAGEIMAGES: number;
    static MAXDESCRIPTORSETUNIFORMBUFFERS: number;
    static MAXDESCRIPTORSETUNIFORMBUFFERSDYNAMIC: number;
    static MAXDRAWINDEXEDINDEXVALUE: number;
    static MAXDRAWINDIRECTCOUNT: number;
    static MAXFRAGMENTCOMBINEDOUTPUTRESOURCES: number;
    static MAXFRAGMENTDUALSRCATTACHMENTS: number;
    static MAXFRAGMENTINPUTCOMPONENTS: number;
    static MAXFRAGMENTOUTPUTATTACHMENTS: number;
    static MAXFRAMEBUFFERHEIGHT: number;
    static MAXFRAMEBUFFERLAYERS: number;
    static MAXFRAMEBUFFERWIDTH: number;
    static MAXGEOMETRYINPUTCOMPONENTS: number;
    static MAXGEOMETRYOUTPUTCOMPONENTS: number;
    static MAXGEOMETRYOUTPUTVERTICES: number;
    static MAXGEOMETRYSHADERINVOCATIONS: number;
    static MAXGEOMETRYTOTALOUTPUTCOMPONENTS: number;
    static MAXIMAGEARRAYLAYERS: number;
    static MAXIMAGEDIMENSION1D: number;
    static MAXIMAGEDIMENSION2D: number;
    static MAXIMAGEDIMENSION3D: number;
    static MAXIMAGEDIMENSIONCUBE: number;
    static MAXINTERPOLATIONOFFSET: number;
    static MAXMEMORYALLOCATIONCOUNT: number;
    static MAXPERSTAGEDESCRIPTORINPUTATTACHMENTS: number;
    static MAXPERSTAGEDESCRIPTORSAMPLEDIMAGES: number;
    static MAXPERSTAGEDESCRIPTORSAMPLERS: number;
    static MAXPERSTAGEDESCRIPTORSTORAGEBUFFERS: number;
    static MAXPERSTAGEDESCRIPTORSTORAGEIMAGES: number;
    static MAXPERSTAGEDESCRIPTORUNIFORMBUFFERS: number;
    static MAXPERSTAGERESOURCES: number;
    static MAXPUSHCONSTANTSSIZE: number;
    static MAXSAMPLEMASKWORDS: number;
    static MAXSAMPLERALLOCATIONCOUNT: number;
    static MAXSAMPLERANISOTROPY: number;
    static MAXSAMPLERLODBIAS: number;
    static MAXSTORAGEBUFFERRANGE: number;
    static MAXTESSELLATIONCONTROLPERPATCHOUTPUTCOMPONENTS: number;
    static MAXTESSELLATIONCONTROLPERVERTEXINPUTCOMPONENTS: number;
    static MAXTESSELLATIONCONTROLPERVERTEXOUTPUTCOMPONENTS: number;
    static MAXTESSELLATIONCONTROLTOTALOUTPUTCOMPONENTS: number;
    static MAXTESSELLATIONEVALUATIONINPUTCOMPONENTS: number;
    static MAXTESSELLATIONEVALUATIONOUTPUTCOMPONENTS: number;
    static MAXTESSELLATIONGENERATIONLEVEL: number;
    static MAXTESSELLATIONPATCHSIZE: number;
    static MAXTEXELBUFFERELEMENTS: number;
    static MAXTEXELGATHEROFFSET: number;
    static MAXTEXELOFFSET: number;
    static MAXUNIFORMBUFFERRANGE: number;
    static MAXVERTEXINPUTATTRIBUTEOFFSET: number;
    static MAXVERTEXINPUTATTRIBUTES: number;
    static MAXVERTEXINPUTBINDINGS: number;
    static MAXVERTEXINPUTBINDINGSTRIDE: number;
    static MAXVERTEXOUTPUTCOMPONENTS: number;
    static MAXVIEWPORTDIMENSIONS: number;
    static MAXVIEWPORTS: number;
    static MININTERPOLATIONOFFSET: number;
    static MINMEMORYMAPALIGNMENT: number;
    static MINSTORAGEBUFFEROFFSETALIGNMENT: number;
    static MINTEXELBUFFEROFFSETALIGNMENT: number;
    static MINTEXELGATHEROFFSET: number;
    static MINTEXELOFFSET: number;
    static MINUNIFORMBUFFEROFFSETALIGNMENT: number;
    static MIPMAPPRECISIONBITS: number;
    static NONCOHERENTATOMSIZE: number;
    static OPTIMALBUFFERCOPYOFFSETALIGNMENT: number;
    static OPTIMALBUFFERCOPYROWPITCHALIGNMENT: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static POINTSIZEGRANULARITY: number;
    static POINTSIZERANGE: number;
    static SAMPLEDIMAGECOLORSAMPLECOUNTS: number;
    static SAMPLEDIMAGEDEPTHSAMPLECOUNTS: number;
    static SAMPLEDIMAGEINTEGERSAMPLECOUNTS: number;
    static SAMPLEDIMAGESTENCILSAMPLECOUNTS: number;
    static SIZEOF: number;
    static SPARSEADDRESSSPACESIZE: number;
    static STANDARDSAMPLELOCATIONS: number;
    static STORAGEIMAGESAMPLECOUNTS: number;
    static STRICTLINES: number;
    static SUBPIXELINTERPOLATIONOFFSETBITS: number;
    static SUBPIXELPRECISIONBITS: number;
    static SUBTEXELPRECISIONBITS: number;
    static TIMESTAMPCOMPUTEANDGRAPHICS: number;
    static TIMESTAMPPERIOD: number;
    static VIEWPORTBOUNDSRANGE: number;
    static VIEWPORTSUBPIXELBITS: number;
    static create(paramarg0: number): VkPhysicalDeviceLimits;
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): VkPhysicalDeviceLimits;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static nbufferImageGranularity(paramarg0: number): number;
    static ndiscreteQueuePriorities(paramarg0: number): number;
    static nframebufferColorSampleCounts(paramarg0: number): number;
    static nframebufferDepthSampleCounts(paramarg0: number): number;
    static nframebufferNoAttachmentsSampleCounts(paramarg0: number): number;
    static nframebufferStencilSampleCounts(paramarg0: number): number;
    static nlineWidthGranularity(paramarg0: number): number;
    static nlineWidthRange(paramarg0: number, paramarg1: number): number;
    static nlineWidthRange(paramarg0: number): FloatBuffer;
    static nmaxBoundDescriptorSets(paramarg0: number): number;
    static nmaxClipDistances(paramarg0: number): number;
    static nmaxColorAttachments(paramarg0: number): number;
    static nmaxCombinedClipAndCullDistances(paramarg0: number): number;
    static nmaxComputeSharedMemorySize(paramarg0: number): number;
    static nmaxComputeWorkGroupCount(paramarg0: number, paramarg1: number): number;
    static nmaxComputeWorkGroupCount(paramarg0: number): IntBuffer;
    static nmaxComputeWorkGroupInvocations(paramarg0: number): number;
    static nmaxComputeWorkGroupSize(paramarg0: number, paramarg1: number): number;
    static nmaxComputeWorkGroupSize(paramarg0: number): IntBuffer;
    static nmaxCullDistances(paramarg0: number): number;
    static nmaxDescriptorSetInputAttachments(paramarg0: number): number;
    static nmaxDescriptorSetSampledImages(paramarg0: number): number;
    static nmaxDescriptorSetSamplers(paramarg0: number): number;
    static nmaxDescriptorSetStorageBuffers(paramarg0: number): number;
    static nmaxDescriptorSetStorageBuffersDynamic(paramarg0: number): number;
    static nmaxDescriptorSetStorageImages(paramarg0: number): number;
    static nmaxDescriptorSetUniformBuffers(paramarg0: number): number;
    static nmaxDescriptorSetUniformBuffersDynamic(paramarg0: number): number;
    static nmaxDrawIndexedIndexValue(paramarg0: number): number;
    static nmaxDrawIndirectCount(paramarg0: number): number;
    static nmaxFragmentCombinedOutputResources(paramarg0: number): number;
    static nmaxFragmentDualSrcAttachments(paramarg0: number): number;
    static nmaxFragmentInputComponents(paramarg0: number): number;
    static nmaxFragmentOutputAttachments(paramarg0: number): number;
    static nmaxFramebufferHeight(paramarg0: number): number;
    static nmaxFramebufferLayers(paramarg0: number): number;
    static nmaxFramebufferWidth(paramarg0: number): number;
    static nmaxGeometryInputComponents(paramarg0: number): number;
    static nmaxGeometryOutputComponents(paramarg0: number): number;
    static nmaxGeometryOutputVertices(paramarg0: number): number;
    static nmaxGeometryShaderInvocations(paramarg0: number): number;
    static nmaxGeometryTotalOutputComponents(paramarg0: number): number;
    static nmaxImageArrayLayers(paramarg0: number): number;
    static nmaxImageDimension1D(paramarg0: number): number;
    static nmaxImageDimension2D(paramarg0: number): number;
    static nmaxImageDimension3D(paramarg0: number): number;
    static nmaxImageDimensionCube(paramarg0: number): number;
    static nmaxInterpolationOffset(paramarg0: number): number;
    static nmaxMemoryAllocationCount(paramarg0: number): number;
    static nmaxPerStageDescriptorInputAttachments(paramarg0: number): number;
    static nmaxPerStageDescriptorSampledImages(paramarg0: number): number;
    static nmaxPerStageDescriptorSamplers(paramarg0: number): number;
    static nmaxPerStageDescriptorStorageBuffers(paramarg0: number): number;
    static nmaxPerStageDescriptorStorageImages(paramarg0: number): number;
    static nmaxPerStageDescriptorUniformBuffers(paramarg0: number): number;
    static nmaxPerStageResources(paramarg0: number): number;
    static nmaxPushConstantsSize(paramarg0: number): number;
    static nmaxSampleMaskWords(paramarg0: number): number;
    static nmaxSamplerAllocationCount(paramarg0: number): number;
    static nmaxSamplerAnisotropy(paramarg0: number): number;
    static nmaxSamplerLodBias(paramarg0: number): number;
    static nmaxStorageBufferRange(paramarg0: number): number;
    static nmaxTessellationControlPerPatchOutputComponents(paramarg0: number): number;
    static nmaxTessellationControlPerVertexInputComponents(paramarg0: number): number;
    static nmaxTessellationControlPerVertexOutputComponents(paramarg0: number): number;
    static nmaxTessellationControlTotalOutputComponents(paramarg0: number): number;
    static nmaxTessellationEvaluationInputComponents(paramarg0: number): number;
    static nmaxTessellationEvaluationOutputComponents(paramarg0: number): number;
    static nmaxTessellationGenerationLevel(paramarg0: number): number;
    static nmaxTessellationPatchSize(paramarg0: number): number;
    static nmaxTexelBufferElements(paramarg0: number): number;
    static nmaxTexelGatherOffset(paramarg0: number): number;
    static nmaxTexelOffset(paramarg0: number): number;
    static nmaxUniformBufferRange(paramarg0: number): number;
    static nmaxVertexInputAttributeOffset(paramarg0: number): number;
    static nmaxVertexInputAttributes(paramarg0: number): number;
    static nmaxVertexInputBindingStride(paramarg0: number): number;
    static nmaxVertexInputBindings(paramarg0: number): number;
    static nmaxVertexOutputComponents(paramarg0: number): number;
    static nmaxViewportDimensions(paramarg0: number, paramarg1: number): number;
    static nmaxViewportDimensions(paramarg0: number): IntBuffer;
    static nmaxViewports(paramarg0: number): number;
    static nminInterpolationOffset(paramarg0: number): number;
    static nminMemoryMapAlignment(paramarg0: number): number;
    static nminStorageBufferOffsetAlignment(paramarg0: number): number;
    static nminTexelBufferOffsetAlignment(paramarg0: number): number;
    static nminTexelGatherOffset(paramarg0: number): number;
    static nminTexelOffset(paramarg0: number): number;
    static nminUniformBufferOffsetAlignment(paramarg0: number): number;
    static nmipmapPrecisionBits(paramarg0: number): number;
    static nnonCoherentAtomSize(paramarg0: number): number;
    static noptimalBufferCopyOffsetAlignment(paramarg0: number): number;
    static noptimalBufferCopyRowPitchAlignment(paramarg0: number): number;
    static npointSizeGranularity(paramarg0: number): number;
    static npointSizeRange(paramarg0: number, paramarg1: number): number;
    static npointSizeRange(paramarg0: number): FloatBuffer;
    static nsampledImageColorSampleCounts(paramarg0: number): number;
    static nsampledImageDepthSampleCounts(paramarg0: number): number;
    static nsampledImageIntegerSampleCounts(paramarg0: number): number;
    static nsampledImageStencilSampleCounts(paramarg0: number): number;
    static nsparseAddressSpaceSize(paramarg0: number): number;
    static nstandardSampleLocations(paramarg0: number): number;
    static nstorageImageSampleCounts(paramarg0: number): number;
    static nstrictLines(paramarg0: number): number;
    static nsubPixelInterpolationOffsetBits(paramarg0: number): number;
    static nsubPixelPrecisionBits(paramarg0: number): number;
    static nsubTexelPrecisionBits(paramarg0: number): number;
    static ntimestampComputeAndGraphics(paramarg0: number): number;
    static ntimestampPeriod(paramarg0: number): number;
    static nviewportBoundsRange(paramarg0: number, paramarg1: number): number;
    static nviewportBoundsRange(paramarg0: number): FloatBuffer;
    static nviewportSubPixelBits(paramarg0: number): number;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    bufferImageGranularity(): number;
    create(arg0: number, arg1: ByteBuffer): VkPhysicalDeviceLimits;
    discreteQueuePriorities(): number;
    framebufferColorSampleCounts(): number;
    framebufferDepthSampleCounts(): number;
    framebufferNoAttachmentsSampleCounts(): number;
    framebufferStencilSampleCounts(): number;
    lineWidthGranularity(): number;
    lineWidthRange(): FloatBuffer;
    lineWidthRange(arg0: number): number;
    maxBoundDescriptorSets(): number;
    maxClipDistances(): number;
    maxColorAttachments(): number;
    maxCombinedClipAndCullDistances(): number;
    maxComputeSharedMemorySize(): number;
    maxComputeWorkGroupCount(): IntBuffer;
    maxComputeWorkGroupCount(arg0: number): number;
    maxComputeWorkGroupInvocations(): number;
    maxComputeWorkGroupSize(): IntBuffer;
    maxComputeWorkGroupSize(arg0: number): number;
    maxCullDistances(): number;
    maxDescriptorSetInputAttachments(): number;
    maxDescriptorSetSampledImages(): number;
    maxDescriptorSetSamplers(): number;
    maxDescriptorSetStorageBuffers(): number;
    maxDescriptorSetStorageBuffersDynamic(): number;
    maxDescriptorSetStorageImages(): number;
    maxDescriptorSetUniformBuffers(): number;
    maxDescriptorSetUniformBuffersDynamic(): number;
    maxDrawIndexedIndexValue(): number;
    maxDrawIndirectCount(): number;
    maxFragmentCombinedOutputResources(): number;
    maxFragmentDualSrcAttachments(): number;
    maxFragmentInputComponents(): number;
    maxFragmentOutputAttachments(): number;
    maxFramebufferHeight(): number;
    maxFramebufferLayers(): number;
    maxFramebufferWidth(): number;
    maxGeometryInputComponents(): number;
    maxGeometryOutputComponents(): number;
    maxGeometryOutputVertices(): number;
    maxGeometryShaderInvocations(): number;
    maxGeometryTotalOutputComponents(): number;
    maxImageArrayLayers(): number;
    maxImageDimension1D(): number;
    maxImageDimension2D(): number;
    maxImageDimension3D(): number;
    maxImageDimensionCube(): number;
    maxInterpolationOffset(): number;
    maxMemoryAllocationCount(): number;
    maxPerStageDescriptorInputAttachments(): number;
    maxPerStageDescriptorSampledImages(): number;
    maxPerStageDescriptorSamplers(): number;
    maxPerStageDescriptorStorageBuffers(): number;
    maxPerStageDescriptorStorageImages(): number;
    maxPerStageDescriptorUniformBuffers(): number;
    maxPerStageResources(): number;
    maxPushConstantsSize(): number;
    maxSampleMaskWords(): number;
    maxSamplerAllocationCount(): number;
    maxSamplerAnisotropy(): number;
    maxSamplerLodBias(): number;
    maxStorageBufferRange(): number;
    maxTessellationControlPerPatchOutputComponents(): number;
    maxTessellationControlPerVertexInputComponents(): number;
    maxTessellationControlPerVertexOutputComponents(): number;
    maxTessellationControlTotalOutputComponents(): number;
    maxTessellationEvaluationInputComponents(): number;
    maxTessellationEvaluationOutputComponents(): number;
    maxTessellationGenerationLevel(): number;
    maxTessellationPatchSize(): number;
    maxTexelBufferElements(): number;
    maxTexelGatherOffset(): number;
    maxTexelOffset(): number;
    maxUniformBufferRange(): number;
    maxVertexInputAttributeOffset(): number;
    maxVertexInputAttributes(): number;
    maxVertexInputBindingStride(): number;
    maxVertexInputBindings(): number;
    maxVertexOutputComponents(): number;
    maxViewportDimensions(): IntBuffer;
    maxViewportDimensions(arg0: number): number;
    maxViewports(): number;
    minInterpolationOffset(): number;
    minMemoryMapAlignment(): number;
    minStorageBufferOffsetAlignment(): number;
    minTexelBufferOffsetAlignment(): number;
    minTexelGatherOffset(): number;
    minTexelOffset(): number;
    minUniformBufferOffsetAlignment(): number;
    mipmapPrecisionBits(): number;
    nonCoherentAtomSize(): number;
    optimalBufferCopyOffsetAlignment(): number;
    optimalBufferCopyRowPitchAlignment(): number;
    pointSizeGranularity(): number;
    pointSizeRange(): FloatBuffer;
    pointSizeRange(arg0: number): number;
    sampledImageColorSampleCounts(): number;
    sampledImageDepthSampleCounts(): number;
    sampledImageIntegerSampleCounts(): number;
    sampledImageStencilSampleCounts(): number;
    sizeof(): number;
    sparseAddressSpaceSize(): number;
    standardSampleLocations(): boolean;
    storageImageSampleCounts(): number;
    strictLines(): boolean;
    subPixelInterpolationOffsetBits(): number;
    subPixelPrecisionBits(): number;
    subTexelPrecisionBits(): number;
    timestampComputeAndGraphics(): boolean;
    timestampPeriod(): number;
    viewportBoundsRange(): FloatBuffer;
    viewportBoundsRange(arg0: number): number;
    viewportSubPixelBits(): number;
}