import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class VkPhysicalDeviceVulkan14Features extends Struct<VkPhysicalDeviceVulkan14Features> implements NativeResource {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static BRESENHAMLINES: number;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static DYNAMICRENDERINGLOCALREAD: number;
    static GLOBALPRIORITYQUERY: number;
    static HOSTIMAGECOPY: number;
    static INDEXTYPEUINT8: number;
    static MAINTENANCE5: number;
    static MAINTENANCE6: number;
    static PIPELINEPROTECTEDACCESS: number;
    static PIPELINEROBUSTNESS: number;
    static PNEXT: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static PUSHDESCRIPTOR: number;
    static RECTANGULARLINES: number;
    static SHADEREXPECTASSUME: number;
    static SHADERFLOATCONTROLS2: number;
    static SHADERSUBGROUPROTATE: number;
    static SHADERSUBGROUPROTATECLUSTERED: number;
    static SIZEOF: number;
    static SMOOTHLINES: number;
    static STIPPLEDBRESENHAMLINES: number;
    static STIPPLEDRECTANGULARLINES: number;
    static STIPPLEDSMOOTHLINES: number;
    static STYPE: number;
    static VERTEXATTRIBUTEINSTANCERATEDIVISOR: number;
    static VERTEXATTRIBUTEINSTANCERATEZERODIVISOR: number;
    static calloc(): VkPhysicalDeviceVulkan14Features;
    static calloc(paramarg0: MemoryStack): VkPhysicalDeviceVulkan14Features;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): VkPhysicalDeviceVulkan14Features;
    static create(paramarg0: number): VkPhysicalDeviceVulkan14Features;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): VkPhysicalDeviceVulkan14Features;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): VkPhysicalDeviceVulkan14Features;
    static malloc(paramarg0: MemoryStack): VkPhysicalDeviceVulkan14Features;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static nbresenhamLines(paramarg0: number): number;
    static nbresenhamLines(paramarg0: number, paramarg1: number): void;
    static ndynamicRenderingLocalRead(paramarg0: number): number;
    static ndynamicRenderingLocalRead(paramarg0: number, paramarg1: number): void;
    static nglobalPriorityQuery(paramarg0: number): number;
    static nglobalPriorityQuery(paramarg0: number, paramarg1: number): void;
    static nhostImageCopy(paramarg0: number): number;
    static nhostImageCopy(paramarg0: number, paramarg1: number): void;
    static nindexTypeUint8(paramarg0: number): number;
    static nindexTypeUint8(paramarg0: number, paramarg1: number): void;
    static nmaintenance5(paramarg0: number): number;
    static nmaintenance5(paramarg0: number, paramarg1: number): void;
    static nmaintenance6(paramarg0: number): number;
    static nmaintenance6(paramarg0: number, paramarg1: number): void;
    static npNext(paramarg0: number): number;
    static npNext(paramarg0: number, paramarg1: number): void;
    static npipelineProtectedAccess(paramarg0: number): number;
    static npipelineProtectedAccess(paramarg0: number, paramarg1: number): void;
    static npipelineRobustness(paramarg0: number): number;
    static npipelineRobustness(paramarg0: number, paramarg1: number): void;
    static npushDescriptor(paramarg0: number): number;
    static npushDescriptor(paramarg0: number, paramarg1: number): void;
    static nrectangularLines(paramarg0: number): number;
    static nrectangularLines(paramarg0: number, paramarg1: number): void;
    static nsType(paramarg0: number): number;
    static nsType(paramarg0: number, paramarg1: number): void;
    static nshaderExpectAssume(paramarg0: number): number;
    static nshaderExpectAssume(paramarg0: number, paramarg1: number): void;
    static nshaderFloatControls2(paramarg0: number): number;
    static nshaderFloatControls2(paramarg0: number, paramarg1: number): void;
    static nshaderSubgroupRotate(paramarg0: number): number;
    static nshaderSubgroupRotate(paramarg0: number, paramarg1: number): void;
    static nshaderSubgroupRotateClustered(paramarg0: number): number;
    static nshaderSubgroupRotateClustered(paramarg0: number, paramarg1: number): void;
    static nsmoothLines(paramarg0: number): number;
    static nsmoothLines(paramarg0: number, paramarg1: number): void;
    static nstippledBresenhamLines(paramarg0: number): number;
    static nstippledBresenhamLines(paramarg0: number, paramarg1: number): void;
    static nstippledRectangularLines(paramarg0: number): number;
    static nstippledRectangularLines(paramarg0: number, paramarg1: number): void;
    static nstippledSmoothLines(paramarg0: number): number;
    static nstippledSmoothLines(paramarg0: number, paramarg1: number): void;
    static nvertexAttributeInstanceRateDivisor(paramarg0: number): number;
    static nvertexAttributeInstanceRateDivisor(paramarg0: number, paramarg1: number): void;
    static nvertexAttributeInstanceRateZeroDivisor(paramarg0: number): number;
    static nvertexAttributeInstanceRateZeroDivisor(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    bresenhamLines(): boolean;
    bresenhamLines(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    close(): void;
    create(arg0: number, arg1: ByteBuffer): VkPhysicalDeviceVulkan14Features;
    dynamicRenderingLocalRead(): boolean;
    dynamicRenderingLocalRead(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    globalPriorityQuery(): boolean;
    globalPriorityQuery(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    hostImageCopy(): boolean;
    hostImageCopy(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    indexTypeUint8(): boolean;
    indexTypeUint8(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    maintenance5(): boolean;
    maintenance5(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    maintenance6(): boolean;
    maintenance6(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    pNext(): number;
    pNext(arg0: number): VkPhysicalDeviceVulkan14Features;
    pipelineProtectedAccess(): boolean;
    pipelineProtectedAccess(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    pipelineRobustness(): boolean;
    pipelineRobustness(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    pushDescriptor(): boolean;
    pushDescriptor(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    rectangularLines(): boolean;
    rectangularLines(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    sType(): number;
    sType(arg0: number): VkPhysicalDeviceVulkan14Features;
    sType$Default(): VkPhysicalDeviceVulkan14Features;
    set(arg0: number, arg1: number, arg2: boolean, arg3: boolean, arg4: boolean, arg5: boolean, arg6: boolean, arg7: boolean, arg8: boolean, arg9: boolean, arg10: boolean, arg11: boolean, arg12: boolean, arg13: boolean, arg14: boolean, arg15: boolean, arg16: boolean, arg17: boolean, arg18: boolean, arg19: boolean, arg20: boolean, arg21: boolean, arg22: boolean): VkPhysicalDeviceVulkan14Features;
    set(arg0: VkPhysicalDeviceVulkan14Features): VkPhysicalDeviceVulkan14Features;
    shaderExpectAssume(): boolean;
    shaderExpectAssume(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    shaderFloatControls2(): boolean;
    shaderFloatControls2(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    shaderSubgroupRotate(): boolean;
    shaderSubgroupRotate(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    shaderSubgroupRotateClustered(): boolean;
    shaderSubgroupRotateClustered(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    sizeof(): number;
    smoothLines(): boolean;
    smoothLines(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    stippledBresenhamLines(): boolean;
    stippledBresenhamLines(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    stippledRectangularLines(): boolean;
    stippledRectangularLines(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    stippledSmoothLines(): boolean;
    stippledSmoothLines(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    vertexAttributeInstanceRateDivisor(): boolean;
    vertexAttributeInstanceRateDivisor(arg0: boolean): VkPhysicalDeviceVulkan14Features;
    vertexAttributeInstanceRateZeroDivisor(): boolean;
    vertexAttributeInstanceRateZeroDivisor(arg0: boolean): VkPhysicalDeviceVulkan14Features;
}