import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class VkPhysicalDeviceVulkan13Features extends Struct<VkPhysicalDeviceVulkan13Features> implements NativeResource {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static COMPUTEFULLSUBGROUPS: number;
    static DESCRIPTORBINDINGINLINEUNIFORMBLOCKUPDATEAFTERBIND: number;
    static DYNAMICRENDERING: number;
    static INLINEUNIFORMBLOCK: number;
    static MAINTENANCE4: number;
    static PIPELINECREATIONCACHECONTROL: number;
    static PNEXT: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static PRIVATEDATA: number;
    static ROBUSTIMAGEACCESS: number;
    static SHADERDEMOTETOHELPERINVOCATION: number;
    static SHADERINTEGERDOTPRODUCT: number;
    static SHADERTERMINATEINVOCATION: number;
    static SHADERZEROINITIALIZEWORKGROUPMEMORY: number;
    static SIZEOF: number;
    static STYPE: number;
    static SUBGROUPSIZECONTROL: number;
    static SYNCHRONIZATION2: number;
    static TEXTURECOMPRESSIONASTC_HDR: number;
    static calloc(): VkPhysicalDeviceVulkan13Features;
    static calloc(paramarg0: MemoryStack): VkPhysicalDeviceVulkan13Features;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): VkPhysicalDeviceVulkan13Features;
    static create(paramarg0: number): VkPhysicalDeviceVulkan13Features;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): VkPhysicalDeviceVulkan13Features;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): VkPhysicalDeviceVulkan13Features;
    static malloc(paramarg0: MemoryStack): VkPhysicalDeviceVulkan13Features;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static ncomputeFullSubgroups(paramarg0: number): number;
    static ncomputeFullSubgroups(paramarg0: number, paramarg1: number): void;
    static ndescriptorBindingInlineUniformBlockUpdateAfterBind(paramarg0: number): number;
    static ndescriptorBindingInlineUniformBlockUpdateAfterBind(paramarg0: number, paramarg1: number): void;
    static ndynamicRendering(paramarg0: number): number;
    static ndynamicRendering(paramarg0: number, paramarg1: number): void;
    static ninlineUniformBlock(paramarg0: number): number;
    static ninlineUniformBlock(paramarg0: number, paramarg1: number): void;
    static nmaintenance4(paramarg0: number): number;
    static nmaintenance4(paramarg0: number, paramarg1: number): void;
    static npNext(paramarg0: number): number;
    static npNext(paramarg0: number, paramarg1: number): void;
    static npipelineCreationCacheControl(paramarg0: number): number;
    static npipelineCreationCacheControl(paramarg0: number, paramarg1: number): void;
    static nprivateData(paramarg0: number): number;
    static nprivateData(paramarg0: number, paramarg1: number): void;
    static nrobustImageAccess(paramarg0: number): number;
    static nrobustImageAccess(paramarg0: number, paramarg1: number): void;
    static nsType(paramarg0: number): number;
    static nsType(paramarg0: number, paramarg1: number): void;
    static nshaderDemoteToHelperInvocation(paramarg0: number): number;
    static nshaderDemoteToHelperInvocation(paramarg0: number, paramarg1: number): void;
    static nshaderIntegerDotProduct(paramarg0: number): number;
    static nshaderIntegerDotProduct(paramarg0: number, paramarg1: number): void;
    static nshaderTerminateInvocation(paramarg0: number): number;
    static nshaderTerminateInvocation(paramarg0: number, paramarg1: number): void;
    static nshaderZeroInitializeWorkgroupMemory(paramarg0: number): number;
    static nshaderZeroInitializeWorkgroupMemory(paramarg0: number, paramarg1: number): void;
    static nsubgroupSizeControl(paramarg0: number): number;
    static nsubgroupSizeControl(paramarg0: number, paramarg1: number): void;
    static nsynchronization2(paramarg0: number): number;
    static nsynchronization2(paramarg0: number, paramarg1: number): void;
    static ntextureCompressionASTC_HDR(paramarg0: number): number;
    static ntextureCompressionASTC_HDR(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    close(): void;
    computeFullSubgroups(): boolean;
    computeFullSubgroups(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    create(arg0: number, arg1: ByteBuffer): VkPhysicalDeviceVulkan13Features;
    descriptorBindingInlineUniformBlockUpdateAfterBind(): boolean;
    descriptorBindingInlineUniformBlockUpdateAfterBind(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    dynamicRendering(): boolean;
    dynamicRendering(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    inlineUniformBlock(): boolean;
    inlineUniformBlock(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    maintenance4(): boolean;
    maintenance4(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    pNext(): number;
    pNext(arg0: number): VkPhysicalDeviceVulkan13Features;
    pipelineCreationCacheControl(): boolean;
    pipelineCreationCacheControl(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    privateData(): boolean;
    privateData(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    robustImageAccess(): boolean;
    robustImageAccess(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    sType(): number;
    sType(arg0: number): VkPhysicalDeviceVulkan13Features;
    sType$Default(): VkPhysicalDeviceVulkan13Features;
    set(arg0: number, arg1: number, arg2: boolean, arg3: boolean, arg4: boolean, arg5: boolean, arg6: boolean, arg7: boolean, arg8: boolean, arg9: boolean, arg10: boolean, arg11: boolean, arg12: boolean, arg13: boolean, arg14: boolean, arg15: boolean, arg16: boolean): VkPhysicalDeviceVulkan13Features;
    set(arg0: VkPhysicalDeviceVulkan13Features): VkPhysicalDeviceVulkan13Features;
    shaderDemoteToHelperInvocation(): boolean;
    shaderDemoteToHelperInvocation(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    shaderIntegerDotProduct(): boolean;
    shaderIntegerDotProduct(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    shaderTerminateInvocation(): boolean;
    shaderTerminateInvocation(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    shaderZeroInitializeWorkgroupMemory(): boolean;
    shaderZeroInitializeWorkgroupMemory(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    sizeof(): number;
    subgroupSizeControl(): boolean;
    subgroupSizeControl(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    synchronization2(): boolean;
    synchronization2(arg0: boolean): VkPhysicalDeviceVulkan13Features;
    textureCompressionASTC_HDR(): boolean;
    textureCompressionASTC_HDR(arg0: boolean): VkPhysicalDeviceVulkan13Features;
}