import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class VkPhysicalDeviceTileShadingFeaturesQCOM extends Struct<VkPhysicalDeviceTileShadingFeaturesQCOM> implements NativeResource {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static PNEXT: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static SIZEOF: number;
    static STYPE: number;
    static TILESHADING: number;
    static TILESHADINGANISOTROPICAPRON: number;
    static TILESHADINGAPRON: number;
    static TILESHADINGATOMICOPS: number;
    static TILESHADINGCOLORATTACHMENTS: number;
    static TILESHADINGDEPTHATTACHMENTS: number;
    static TILESHADINGDISPATCHTILE: number;
    static TILESHADINGFRAGMENTSTAGE: number;
    static TILESHADINGIMAGEPROCESSING: number;
    static TILESHADINGINPUTATTACHMENTS: number;
    static TILESHADINGPERTILEDISPATCH: number;
    static TILESHADINGPERTILEDRAW: number;
    static TILESHADINGSAMPLEDATTACHMENTS: number;
    static TILESHADINGSTENCILATTACHMENTS: number;
    static calloc(): VkPhysicalDeviceTileShadingFeaturesQCOM;
    static calloc(paramarg0: MemoryStack): VkPhysicalDeviceTileShadingFeaturesQCOM;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): VkPhysicalDeviceTileShadingFeaturesQCOM;
    static create(paramarg0: number): VkPhysicalDeviceTileShadingFeaturesQCOM;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): VkPhysicalDeviceTileShadingFeaturesQCOM;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): VkPhysicalDeviceTileShadingFeaturesQCOM;
    static malloc(paramarg0: MemoryStack): VkPhysicalDeviceTileShadingFeaturesQCOM;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static npNext(paramarg0: number): number;
    static npNext(paramarg0: number, paramarg1: number): void;
    static nsType(paramarg0: number): number;
    static nsType(paramarg0: number, paramarg1: number): void;
    static ntileShading(paramarg0: number): number;
    static ntileShading(paramarg0: number, paramarg1: number): void;
    static ntileShadingAnisotropicApron(paramarg0: number): number;
    static ntileShadingAnisotropicApron(paramarg0: number, paramarg1: number): void;
    static ntileShadingApron(paramarg0: number): number;
    static ntileShadingApron(paramarg0: number, paramarg1: number): void;
    static ntileShadingAtomicOps(paramarg0: number): number;
    static ntileShadingAtomicOps(paramarg0: number, paramarg1: number): void;
    static ntileShadingColorAttachments(paramarg0: number): number;
    static ntileShadingColorAttachments(paramarg0: number, paramarg1: number): void;
    static ntileShadingDepthAttachments(paramarg0: number): number;
    static ntileShadingDepthAttachments(paramarg0: number, paramarg1: number): void;
    static ntileShadingDispatchTile(paramarg0: number): number;
    static ntileShadingDispatchTile(paramarg0: number, paramarg1: number): void;
    static ntileShadingFragmentStage(paramarg0: number): number;
    static ntileShadingFragmentStage(paramarg0: number, paramarg1: number): void;
    static ntileShadingImageProcessing(paramarg0: number): number;
    static ntileShadingImageProcessing(paramarg0: number, paramarg1: number): void;
    static ntileShadingInputAttachments(paramarg0: number): number;
    static ntileShadingInputAttachments(paramarg0: number, paramarg1: number): void;
    static ntileShadingPerTileDispatch(paramarg0: number): number;
    static ntileShadingPerTileDispatch(paramarg0: number, paramarg1: number): void;
    static ntileShadingPerTileDraw(paramarg0: number): number;
    static ntileShadingPerTileDraw(paramarg0: number, paramarg1: number): void;
    static ntileShadingSampledAttachments(paramarg0: number): number;
    static ntileShadingSampledAttachments(paramarg0: number, paramarg1: number): void;
    static ntileShadingStencilAttachments(paramarg0: number): number;
    static ntileShadingStencilAttachments(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    close(): void;
    create(arg0: number, arg1: ByteBuffer): VkPhysicalDeviceTileShadingFeaturesQCOM;
    pNext(): number;
    pNext(arg0: number): VkPhysicalDeviceTileShadingFeaturesQCOM;
    sType(): number;
    sType(arg0: number): VkPhysicalDeviceTileShadingFeaturesQCOM;
    sType$Default(): VkPhysicalDeviceTileShadingFeaturesQCOM;
    set(arg0: number, arg1: number, arg2: boolean, arg3: boolean, arg4: boolean, arg5: boolean, arg6: boolean, arg7: boolean, arg8: boolean, arg9: boolean, arg10: boolean, arg11: boolean, arg12: boolean, arg13: boolean, arg14: boolean, arg15: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    set(arg0: VkPhysicalDeviceTileShadingFeaturesQCOM): VkPhysicalDeviceTileShadingFeaturesQCOM;
    sizeof(): number;
    tileShading(): boolean;
    tileShading(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    tileShadingAnisotropicApron(): boolean;
    tileShadingAnisotropicApron(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    tileShadingApron(): boolean;
    tileShadingApron(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    tileShadingAtomicOps(): boolean;
    tileShadingAtomicOps(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    tileShadingColorAttachments(): boolean;
    tileShadingColorAttachments(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    tileShadingDepthAttachments(): boolean;
    tileShadingDepthAttachments(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    tileShadingDispatchTile(): boolean;
    tileShadingDispatchTile(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    tileShadingFragmentStage(): boolean;
    tileShadingFragmentStage(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    tileShadingImageProcessing(): boolean;
    tileShadingImageProcessing(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    tileShadingInputAttachments(): boolean;
    tileShadingInputAttachments(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    tileShadingPerTileDispatch(): boolean;
    tileShadingPerTileDispatch(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    tileShadingPerTileDraw(): boolean;
    tileShadingPerTileDraw(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    tileShadingSampledAttachments(): boolean;
    tileShadingSampledAttachments(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
    tileShadingStencilAttachments(): boolean;
    tileShadingStencilAttachments(arg0: boolean): VkPhysicalDeviceTileShadingFeaturesQCOM;
}