import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class VkPhysicalDeviceDescriptorBufferPropertiesEXT extends Struct<VkPhysicalDeviceDescriptorBufferPropertiesEXT> implements NativeResource {
    static ACCELERATIONSTRUCTURECAPTUREREPLAYDESCRIPTORDATASIZE: number;
    static ACCELERATIONSTRUCTUREDESCRIPTORSIZE: number;
    static ALIGNOF: number;
    static ALLOWSAMPLERIMAGEVIEWPOSTSUBMITCREATION: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static BUFFERCAPTUREREPLAYDESCRIPTORDATASIZE: number;
    static BUFFERLESSPUSHDESCRIPTORS: number;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static COMBINEDIMAGESAMPLERDESCRIPTORSINGLEARRAY: number;
    static COMBINEDIMAGESAMPLERDESCRIPTORSIZE: number;
    static DESCRIPTORBUFFERADDRESSSPACESIZE: number;
    static DESCRIPTORBUFFEROFFSETALIGNMENT: number;
    static IMAGECAPTUREREPLAYDESCRIPTORDATASIZE: number;
    static IMAGEVIEWCAPTUREREPLAYDESCRIPTORDATASIZE: number;
    static INPUTATTACHMENTDESCRIPTORSIZE: number;
    static MAXDESCRIPTORBUFFERBINDINGS: number;
    static MAXEMBEDDEDIMMUTABLESAMPLERBINDINGS: number;
    static MAXEMBEDDEDIMMUTABLESAMPLERS: number;
    static MAXRESOURCEDESCRIPTORBUFFERBINDINGS: number;
    static MAXRESOURCEDESCRIPTORBUFFERRANGE: number;
    static MAXSAMPLERDESCRIPTORBUFFERBINDINGS: number;
    static MAXSAMPLERDESCRIPTORBUFFERRANGE: number;
    static PNEXT: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static RESOURCEDESCRIPTORBUFFERADDRESSSPACESIZE: number;
    static ROBUSTSTORAGEBUFFERDESCRIPTORSIZE: number;
    static ROBUSTSTORAGETEXELBUFFERDESCRIPTORSIZE: number;
    static ROBUSTUNIFORMBUFFERDESCRIPTORSIZE: number;
    static ROBUSTUNIFORMTEXELBUFFERDESCRIPTORSIZE: number;
    static SAMPLEDIMAGEDESCRIPTORSIZE: number;
    static SAMPLERCAPTUREREPLAYDESCRIPTORDATASIZE: number;
    static SAMPLERDESCRIPTORBUFFERADDRESSSPACESIZE: number;
    static SAMPLERDESCRIPTORSIZE: number;
    static SIZEOF: number;
    static STORAGEBUFFERDESCRIPTORSIZE: number;
    static STORAGEIMAGEDESCRIPTORSIZE: number;
    static STORAGETEXELBUFFERDESCRIPTORSIZE: number;
    static STYPE: number;
    static UNIFORMBUFFERDESCRIPTORSIZE: number;
    static UNIFORMTEXELBUFFERDESCRIPTORSIZE: number;
    static calloc(): VkPhysicalDeviceDescriptorBufferPropertiesEXT;
    static calloc(paramarg0: MemoryStack): VkPhysicalDeviceDescriptorBufferPropertiesEXT;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): VkPhysicalDeviceDescriptorBufferPropertiesEXT;
    static create(paramarg0: number): VkPhysicalDeviceDescriptorBufferPropertiesEXT;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): VkPhysicalDeviceDescriptorBufferPropertiesEXT;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): VkPhysicalDeviceDescriptorBufferPropertiesEXT;
    static malloc(paramarg0: MemoryStack): VkPhysicalDeviceDescriptorBufferPropertiesEXT;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static naccelerationStructureCaptureReplayDescriptorDataSize(paramarg0: number): number;
    static naccelerationStructureDescriptorSize(paramarg0: number): number;
    static nallowSamplerImageViewPostSubmitCreation(paramarg0: number): number;
    static nbufferCaptureReplayDescriptorDataSize(paramarg0: number): number;
    static nbufferlessPushDescriptors(paramarg0: number): number;
    static ncombinedImageSamplerDescriptorSingleArray(paramarg0: number): number;
    static ncombinedImageSamplerDescriptorSize(paramarg0: number): number;
    static ndescriptorBufferAddressSpaceSize(paramarg0: number): number;
    static ndescriptorBufferOffsetAlignment(paramarg0: number): number;
    static nimageCaptureReplayDescriptorDataSize(paramarg0: number): number;
    static nimageViewCaptureReplayDescriptorDataSize(paramarg0: number): number;
    static ninputAttachmentDescriptorSize(paramarg0: number): number;
    static nmaxDescriptorBufferBindings(paramarg0: number): number;
    static nmaxEmbeddedImmutableSamplerBindings(paramarg0: number): number;
    static nmaxEmbeddedImmutableSamplers(paramarg0: number): number;
    static nmaxResourceDescriptorBufferBindings(paramarg0: number): number;
    static nmaxResourceDescriptorBufferRange(paramarg0: number): number;
    static nmaxSamplerDescriptorBufferBindings(paramarg0: number): number;
    static nmaxSamplerDescriptorBufferRange(paramarg0: number): number;
    static npNext(paramarg0: number): number;
    static npNext(paramarg0: number, paramarg1: number): void;
    static nresourceDescriptorBufferAddressSpaceSize(paramarg0: number): number;
    static nrobustStorageBufferDescriptorSize(paramarg0: number): number;
    static nrobustStorageTexelBufferDescriptorSize(paramarg0: number): number;
    static nrobustUniformBufferDescriptorSize(paramarg0: number): number;
    static nrobustUniformTexelBufferDescriptorSize(paramarg0: number): number;
    static nsType(paramarg0: number): number;
    static nsType(paramarg0: number, paramarg1: number): void;
    static nsampledImageDescriptorSize(paramarg0: number): number;
    static nsamplerCaptureReplayDescriptorDataSize(paramarg0: number): number;
    static nsamplerDescriptorBufferAddressSpaceSize(paramarg0: number): number;
    static nsamplerDescriptorSize(paramarg0: number): number;
    static nstorageBufferDescriptorSize(paramarg0: number): number;
    static nstorageImageDescriptorSize(paramarg0: number): number;
    static nstorageTexelBufferDescriptorSize(paramarg0: number): number;
    static nuniformBufferDescriptorSize(paramarg0: number): number;
    static nuniformTexelBufferDescriptorSize(paramarg0: number): number;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    accelerationStructureCaptureReplayDescriptorDataSize(): number;
    accelerationStructureDescriptorSize(): number;
    allowSamplerImageViewPostSubmitCreation(): boolean;
    bufferCaptureReplayDescriptorDataSize(): number;
    bufferlessPushDescriptors(): boolean;
    close(): void;
    combinedImageSamplerDescriptorSingleArray(): boolean;
    combinedImageSamplerDescriptorSize(): number;
    create(arg0: number, arg1: ByteBuffer): VkPhysicalDeviceDescriptorBufferPropertiesEXT;
    descriptorBufferAddressSpaceSize(): number;
    descriptorBufferOffsetAlignment(): number;
    imageCaptureReplayDescriptorDataSize(): number;
    imageViewCaptureReplayDescriptorDataSize(): number;
    inputAttachmentDescriptorSize(): number;
    maxDescriptorBufferBindings(): number;
    maxEmbeddedImmutableSamplerBindings(): number;
    maxEmbeddedImmutableSamplers(): number;
    maxResourceDescriptorBufferBindings(): number;
    maxResourceDescriptorBufferRange(): number;
    maxSamplerDescriptorBufferBindings(): number;
    maxSamplerDescriptorBufferRange(): number;
    pNext(): number;
    pNext(arg0: number): VkPhysicalDeviceDescriptorBufferPropertiesEXT;
    resourceDescriptorBufferAddressSpaceSize(): number;
    robustStorageBufferDescriptorSize(): number;
    robustStorageTexelBufferDescriptorSize(): number;
    robustUniformBufferDescriptorSize(): number;
    robustUniformTexelBufferDescriptorSize(): number;
    sType(): number;
    sType(arg0: number): VkPhysicalDeviceDescriptorBufferPropertiesEXT;
    sType$Default(): VkPhysicalDeviceDescriptorBufferPropertiesEXT;
    sampledImageDescriptorSize(): number;
    samplerCaptureReplayDescriptorDataSize(): number;
    samplerDescriptorBufferAddressSpaceSize(): number;
    samplerDescriptorSize(): number;
    set(arg0: number, arg1: number): VkPhysicalDeviceDescriptorBufferPropertiesEXT;
    set(arg0: VkPhysicalDeviceDescriptorBufferPropertiesEXT): VkPhysicalDeviceDescriptorBufferPropertiesEXT;
    sizeof(): number;
    storageBufferDescriptorSize(): number;
    storageImageDescriptorSize(): number;
    storageTexelBufferDescriptorSize(): number;
    uniformBufferDescriptorSize(): number;
    uniformTexelBufferDescriptorSize(): number;
}