import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class VkPhysicalDeviceExtendedDynamicState3FeaturesEXT extends Struct<VkPhysicalDeviceExtendedDynamicState3FeaturesEXT> implements NativeResource {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static EXTENDEDDYNAMICSTATE3ALPHATOCOVERAGEENABLE: number;
    static EXTENDEDDYNAMICSTATE3ALPHATOONEENABLE: number;
    static EXTENDEDDYNAMICSTATE3COLORBLENDADVANCED: number;
    static EXTENDEDDYNAMICSTATE3COLORBLENDENABLE: number;
    static EXTENDEDDYNAMICSTATE3COLORBLENDEQUATION: number;
    static EXTENDEDDYNAMICSTATE3COLORWRITEMASK: number;
    static EXTENDEDDYNAMICSTATE3CONSERVATIVERASTERIZATIONMODE: number;
    static EXTENDEDDYNAMICSTATE3COVERAGEMODULATIONMODE: number;
    static EXTENDEDDYNAMICSTATE3COVERAGEMODULATIONTABLE: number;
    static EXTENDEDDYNAMICSTATE3COVERAGEMODULATIONTABLEENABLE: number;
    static EXTENDEDDYNAMICSTATE3COVERAGEREDUCTIONMODE: number;
    static EXTENDEDDYNAMICSTATE3COVERAGETOCOLORENABLE: number;
    static EXTENDEDDYNAMICSTATE3COVERAGETOCOLORLOCATION: number;
    static EXTENDEDDYNAMICSTATE3DEPTHCLAMPENABLE: number;
    static EXTENDEDDYNAMICSTATE3DEPTHCLIPENABLE: number;
    static EXTENDEDDYNAMICSTATE3DEPTHCLIPNEGATIVEONETOONE: number;
    static EXTENDEDDYNAMICSTATE3EXTRAPRIMITIVEOVERESTIMATIONSIZE: number;
    static EXTENDEDDYNAMICSTATE3LINERASTERIZATIONMODE: number;
    static EXTENDEDDYNAMICSTATE3LINESTIPPLEENABLE: number;
    static EXTENDEDDYNAMICSTATE3LOGICOPENABLE: number;
    static EXTENDEDDYNAMICSTATE3POLYGONMODE: number;
    static EXTENDEDDYNAMICSTATE3PROVOKINGVERTEXMODE: number;
    static EXTENDEDDYNAMICSTATE3RASTERIZATIONSAMPLES: number;
    static EXTENDEDDYNAMICSTATE3RASTERIZATIONSTREAM: number;
    static EXTENDEDDYNAMICSTATE3REPRESENTATIVEFRAGMENTTESTENABLE: number;
    static EXTENDEDDYNAMICSTATE3SAMPLELOCATIONSENABLE: number;
    static EXTENDEDDYNAMICSTATE3SAMPLEMASK: number;
    static EXTENDEDDYNAMICSTATE3SHADINGRATEIMAGEENABLE: number;
    static EXTENDEDDYNAMICSTATE3TESSELLATIONDOMAINORIGIN: number;
    static EXTENDEDDYNAMICSTATE3VIEWPORTSWIZZLE: number;
    static EXTENDEDDYNAMICSTATE3VIEWPORTWSCALINGENABLE: number;
    static PNEXT: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static SIZEOF: number;
    static STYPE: number;
    static calloc(): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    static calloc(paramarg0: MemoryStack): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    static create(paramarg0: number): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    static malloc(paramarg0: MemoryStack): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static nextendedDynamicState3AlphaToCoverageEnable(paramarg0: number): number;
    static nextendedDynamicState3AlphaToCoverageEnable(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3AlphaToOneEnable(paramarg0: number): number;
    static nextendedDynamicState3AlphaToOneEnable(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3ColorBlendAdvanced(paramarg0: number): number;
    static nextendedDynamicState3ColorBlendAdvanced(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3ColorBlendEnable(paramarg0: number): number;
    static nextendedDynamicState3ColorBlendEnable(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3ColorBlendEquation(paramarg0: number): number;
    static nextendedDynamicState3ColorBlendEquation(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3ColorWriteMask(paramarg0: number): number;
    static nextendedDynamicState3ColorWriteMask(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3ConservativeRasterizationMode(paramarg0: number): number;
    static nextendedDynamicState3ConservativeRasterizationMode(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3CoverageModulationMode(paramarg0: number): number;
    static nextendedDynamicState3CoverageModulationMode(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3CoverageModulationTable(paramarg0: number): number;
    static nextendedDynamicState3CoverageModulationTable(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3CoverageModulationTableEnable(paramarg0: number): number;
    static nextendedDynamicState3CoverageModulationTableEnable(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3CoverageReductionMode(paramarg0: number): number;
    static nextendedDynamicState3CoverageReductionMode(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3CoverageToColorEnable(paramarg0: number): number;
    static nextendedDynamicState3CoverageToColorEnable(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3CoverageToColorLocation(paramarg0: number): number;
    static nextendedDynamicState3CoverageToColorLocation(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3DepthClampEnable(paramarg0: number): number;
    static nextendedDynamicState3DepthClampEnable(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3DepthClipEnable(paramarg0: number): number;
    static nextendedDynamicState3DepthClipEnable(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3DepthClipNegativeOneToOne(paramarg0: number): number;
    static nextendedDynamicState3DepthClipNegativeOneToOne(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3ExtraPrimitiveOverestimationSize(paramarg0: number): number;
    static nextendedDynamicState3ExtraPrimitiveOverestimationSize(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3LineRasterizationMode(paramarg0: number): number;
    static nextendedDynamicState3LineRasterizationMode(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3LineStippleEnable(paramarg0: number): number;
    static nextendedDynamicState3LineStippleEnable(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3LogicOpEnable(paramarg0: number): number;
    static nextendedDynamicState3LogicOpEnable(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3PolygonMode(paramarg0: number): number;
    static nextendedDynamicState3PolygonMode(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3ProvokingVertexMode(paramarg0: number): number;
    static nextendedDynamicState3ProvokingVertexMode(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3RasterizationSamples(paramarg0: number): number;
    static nextendedDynamicState3RasterizationSamples(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3RasterizationStream(paramarg0: number): number;
    static nextendedDynamicState3RasterizationStream(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3RepresentativeFragmentTestEnable(paramarg0: number): number;
    static nextendedDynamicState3RepresentativeFragmentTestEnable(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3SampleLocationsEnable(paramarg0: number): number;
    static nextendedDynamicState3SampleLocationsEnable(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3SampleMask(paramarg0: number): number;
    static nextendedDynamicState3SampleMask(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3ShadingRateImageEnable(paramarg0: number): number;
    static nextendedDynamicState3ShadingRateImageEnable(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3TessellationDomainOrigin(paramarg0: number): number;
    static nextendedDynamicState3TessellationDomainOrigin(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3ViewportSwizzle(paramarg0: number): number;
    static nextendedDynamicState3ViewportSwizzle(paramarg0: number, paramarg1: number): void;
    static nextendedDynamicState3ViewportWScalingEnable(paramarg0: number): number;
    static nextendedDynamicState3ViewportWScalingEnable(paramarg0: number, paramarg1: number): void;
    static npNext(paramarg0: number): number;
    static npNext(paramarg0: number, paramarg1: number): void;
    static nsType(paramarg0: number): number;
    static nsType(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    close(): void;
    create(arg0: number, arg1: ByteBuffer): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3AlphaToCoverageEnable(): boolean;
    extendedDynamicState3AlphaToCoverageEnable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3AlphaToOneEnable(): boolean;
    extendedDynamicState3AlphaToOneEnable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3ColorBlendAdvanced(): boolean;
    extendedDynamicState3ColorBlendAdvanced(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3ColorBlendEnable(): boolean;
    extendedDynamicState3ColorBlendEnable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3ColorBlendEquation(): boolean;
    extendedDynamicState3ColorBlendEquation(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3ColorWriteMask(): boolean;
    extendedDynamicState3ColorWriteMask(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3ConservativeRasterizationMode(): boolean;
    extendedDynamicState3ConservativeRasterizationMode(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3CoverageModulationMode(): boolean;
    extendedDynamicState3CoverageModulationMode(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3CoverageModulationTable(): boolean;
    extendedDynamicState3CoverageModulationTable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3CoverageModulationTableEnable(): boolean;
    extendedDynamicState3CoverageModulationTableEnable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3CoverageReductionMode(): boolean;
    extendedDynamicState3CoverageReductionMode(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3CoverageToColorEnable(): boolean;
    extendedDynamicState3CoverageToColorEnable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3CoverageToColorLocation(): boolean;
    extendedDynamicState3CoverageToColorLocation(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3DepthClampEnable(): boolean;
    extendedDynamicState3DepthClampEnable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3DepthClipEnable(): boolean;
    extendedDynamicState3DepthClipEnable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3DepthClipNegativeOneToOne(): boolean;
    extendedDynamicState3DepthClipNegativeOneToOne(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3ExtraPrimitiveOverestimationSize(): boolean;
    extendedDynamicState3ExtraPrimitiveOverestimationSize(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3LineRasterizationMode(): boolean;
    extendedDynamicState3LineRasterizationMode(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3LineStippleEnable(): boolean;
    extendedDynamicState3LineStippleEnable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3LogicOpEnable(): boolean;
    extendedDynamicState3LogicOpEnable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3PolygonMode(): boolean;
    extendedDynamicState3PolygonMode(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3ProvokingVertexMode(): boolean;
    extendedDynamicState3ProvokingVertexMode(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3RasterizationSamples(): boolean;
    extendedDynamicState3RasterizationSamples(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3RasterizationStream(): boolean;
    extendedDynamicState3RasterizationStream(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3RepresentativeFragmentTestEnable(): boolean;
    extendedDynamicState3RepresentativeFragmentTestEnable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3SampleLocationsEnable(): boolean;
    extendedDynamicState3SampleLocationsEnable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3SampleMask(): boolean;
    extendedDynamicState3SampleMask(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3ShadingRateImageEnable(): boolean;
    extendedDynamicState3ShadingRateImageEnable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3TessellationDomainOrigin(): boolean;
    extendedDynamicState3TessellationDomainOrigin(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3ViewportSwizzle(): boolean;
    extendedDynamicState3ViewportSwizzle(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    extendedDynamicState3ViewportWScalingEnable(): boolean;
    extendedDynamicState3ViewportWScalingEnable(arg0: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    pNext(): number;
    pNext(arg0: number): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    sType(): number;
    sType(arg0: number): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    sType$Default(): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    set(arg0: number, arg1: number, arg2: boolean, arg3: boolean, arg4: boolean, arg5: boolean, arg6: boolean, arg7: boolean, arg8: boolean, arg9: boolean, arg10: boolean, arg11: boolean, arg12: boolean, arg13: boolean, arg14: boolean, arg15: boolean, arg16: boolean, arg17: boolean, arg18: boolean, arg19: boolean, arg20: boolean, arg21: boolean, arg22: boolean, arg23: boolean, arg24: boolean, arg25: boolean, arg26: boolean, arg27: boolean, arg28: boolean, arg29: boolean, arg30: boolean, arg31: boolean, arg32: boolean): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    set(arg0: VkPhysicalDeviceExtendedDynamicState3FeaturesEXT): VkPhysicalDeviceExtendedDynamicState3FeaturesEXT;
    sizeof(): number;
}