import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../org/lwjgl/system/MemoryStack.d.ts'
import type { Struct$StructValidation } from '../../../org/lwjgl/system/Struct$StructValidation.d.ts'
import type { VkPhysicalDeviceShaderIntegerDotProductProperties } from '../../../org/lwjgl/vulkan/VkPhysicalDeviceShaderIntegerDotProductProperties.d.ts'
export class VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR extends VkPhysicalDeviceShaderIntegerDotProductProperties {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static INTEGERDOTPRODUCT16BITMIXEDSIGNEDNESSACCELERATED: number;
    static INTEGERDOTPRODUCT16BITSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCT16BITUNSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCT32BITMIXEDSIGNEDNESSACCELERATED: number;
    static INTEGERDOTPRODUCT32BITSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCT32BITUNSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCT4X8BITPACKEDMIXEDSIGNEDNESSACCELERATED: number;
    static INTEGERDOTPRODUCT4X8BITPACKEDSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCT4X8BITPACKEDUNSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCT64BITMIXEDSIGNEDNESSACCELERATED: number;
    static INTEGERDOTPRODUCT64BITSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCT64BITUNSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCT8BITMIXEDSIGNEDNESSACCELERATED: number;
    static INTEGERDOTPRODUCT8BITSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCT8BITUNSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING16BITMIXEDSIGNEDNESSACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING16BITSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING16BITUNSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING32BITMIXEDSIGNEDNESSACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING32BITSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING32BITUNSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING4X8BITPACKEDMIXEDSIGNEDNESSACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING4X8BITPACKEDSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING4X8BITPACKEDUNSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING64BITMIXEDSIGNEDNESSACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING64BITSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING64BITUNSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING8BITMIXEDSIGNEDNESSACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING8BITSIGNEDACCELERATED: number;
    static INTEGERDOTPRODUCTACCUMULATINGSATURATING8BITUNSIGNEDACCELERATED: number;
    static PNEXT: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static SIZEOF: number;
    static STYPE: number;
    static calloc(): VkPhysicalDeviceShaderIntegerDotProductProperties;
    static calloc(paramarg0: MemoryStack): VkPhysicalDeviceShaderIntegerDotProductProperties;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static calloc(): VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR;
    static calloc(paramarg0: MemoryStack): VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR;
    static create(): VkPhysicalDeviceShaderIntegerDotProductProperties;
    static create(paramarg0: number): VkPhysicalDeviceShaderIntegerDotProductProperties;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static create(): VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR;
    static create(paramarg0: number): VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR;
    static createSafe(paramarg0: number): VkPhysicalDeviceShaderIntegerDotProductProperties;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR;
    static malloc(): VkPhysicalDeviceShaderIntegerDotProductProperties;
    static malloc(paramarg0: MemoryStack): VkPhysicalDeviceShaderIntegerDotProductProperties;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static malloc(): VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR;
    static malloc(paramarg0: MemoryStack): VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR;
    static nintegerDotProduct16BitMixedSignednessAccelerated(paramarg0: number): number;
    static nintegerDotProduct16BitSignedAccelerated(paramarg0: number): number;
    static nintegerDotProduct16BitUnsignedAccelerated(paramarg0: number): number;
    static nintegerDotProduct32BitMixedSignednessAccelerated(paramarg0: number): number;
    static nintegerDotProduct32BitSignedAccelerated(paramarg0: number): number;
    static nintegerDotProduct32BitUnsignedAccelerated(paramarg0: number): number;
    static nintegerDotProduct4x8BitPackedMixedSignednessAccelerated(paramarg0: number): number;
    static nintegerDotProduct4x8BitPackedSignedAccelerated(paramarg0: number): number;
    static nintegerDotProduct4x8BitPackedUnsignedAccelerated(paramarg0: number): number;
    static nintegerDotProduct64BitMixedSignednessAccelerated(paramarg0: number): number;
    static nintegerDotProduct64BitSignedAccelerated(paramarg0: number): number;
    static nintegerDotProduct64BitUnsignedAccelerated(paramarg0: number): number;
    static nintegerDotProduct8BitMixedSignednessAccelerated(paramarg0: number): number;
    static nintegerDotProduct8BitSignedAccelerated(paramarg0: number): number;
    static nintegerDotProduct8BitUnsignedAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating16BitSignedAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating16BitUnsignedAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating32BitSignedAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating32BitUnsignedAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating64BitSignedAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating64BitUnsignedAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating8BitSignedAccelerated(paramarg0: number): number;
    static nintegerDotProductAccumulatingSaturating8BitUnsignedAccelerated(paramarg0: number): number;
    static npNext(paramarg0: number): number;
    static npNext(paramarg0: number, paramarg1: number): void;
    static nsType(paramarg0: number): number;
    static nsType(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    create(arg0: number, arg1: ByteBuffer): VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR;
    pNext(): number;
    pNext(arg0: number): VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR;
    sType(): number;
    sType(arg0: number): VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR;
    sType$Default(): VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR;
    set(arg0: number, arg1: number): VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR;
    set(arg0: VkPhysicalDeviceShaderIntegerDotProductProperties): VkPhysicalDeviceShaderIntegerDotProductProperties;
    set(arg0: VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR): VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR;
}