import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class VkPhysicalDeviceMeshShaderPropertiesEXT extends Struct<VkPhysicalDeviceMeshShaderPropertiesEXT> implements NativeResource {
    static ALIGNOF: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static MAXMESHMULTIVIEWVIEWCOUNT: number;
    static MAXMESHOUTPUTCOMPONENTS: number;
    static MAXMESHOUTPUTLAYERS: number;
    static MAXMESHOUTPUTMEMORYSIZE: number;
    static MAXMESHOUTPUTPRIMITIVES: number;
    static MAXMESHOUTPUTVERTICES: number;
    static MAXMESHPAYLOADANDOUTPUTMEMORYSIZE: number;
    static MAXMESHPAYLOADANDSHAREDMEMORYSIZE: number;
    static MAXMESHSHAREDMEMORYSIZE: number;
    static MAXMESHWORKGROUPCOUNT: number;
    static MAXMESHWORKGROUPINVOCATIONS: number;
    static MAXMESHWORKGROUPSIZE: number;
    static MAXMESHWORKGROUPTOTALCOUNT: number;
    static MAXPREFERREDMESHWORKGROUPINVOCATIONS: number;
    static MAXPREFERREDTASKWORKGROUPINVOCATIONS: number;
    static MAXTASKPAYLOADANDSHAREDMEMORYSIZE: number;
    static MAXTASKPAYLOADSIZE: number;
    static MAXTASKSHAREDMEMORYSIZE: number;
    static MAXTASKWORKGROUPCOUNT: number;
    static MAXTASKWORKGROUPINVOCATIONS: number;
    static MAXTASKWORKGROUPSIZE: number;
    static MAXTASKWORKGROUPTOTALCOUNT: number;
    static MESHOUTPUTPERPRIMITIVEGRANULARITY: number;
    static MESHOUTPUTPERVERTEXGRANULARITY: number;
    static PNEXT: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static PREFERSCOMPACTPRIMITIVEOUTPUT: number;
    static PREFERSCOMPACTVERTEXOUTPUT: number;
    static PREFERSLOCALINVOCATIONPRIMITIVEOUTPUT: number;
    static PREFERSLOCALINVOCATIONVERTEXOUTPUT: number;
    static SIZEOF: number;
    static STYPE: number;
    static calloc(): VkPhysicalDeviceMeshShaderPropertiesEXT;
    static calloc(paramarg0: MemoryStack): VkPhysicalDeviceMeshShaderPropertiesEXT;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): VkPhysicalDeviceMeshShaderPropertiesEXT;
    static create(paramarg0: number): VkPhysicalDeviceMeshShaderPropertiesEXT;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): VkPhysicalDeviceMeshShaderPropertiesEXT;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): VkPhysicalDeviceMeshShaderPropertiesEXT;
    static malloc(paramarg0: MemoryStack): VkPhysicalDeviceMeshShaderPropertiesEXT;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static nmaxMeshMultiviewViewCount(paramarg0: number): number;
    static nmaxMeshOutputComponents(paramarg0: number): number;
    static nmaxMeshOutputLayers(paramarg0: number): number;
    static nmaxMeshOutputMemorySize(paramarg0: number): number;
    static nmaxMeshOutputPrimitives(paramarg0: number): number;
    static nmaxMeshOutputVertices(paramarg0: number): number;
    static nmaxMeshPayloadAndOutputMemorySize(paramarg0: number): number;
    static nmaxMeshPayloadAndSharedMemorySize(paramarg0: number): number;
    static nmaxMeshSharedMemorySize(paramarg0: number): number;
    static nmaxMeshWorkGroupCount(paramarg0: number, paramarg1: number): number;
    static nmaxMeshWorkGroupCount(paramarg0: number): IntBuffer;
    static nmaxMeshWorkGroupInvocations(paramarg0: number): number;
    static nmaxMeshWorkGroupSize(paramarg0: number, paramarg1: number): number;
    static nmaxMeshWorkGroupSize(paramarg0: number): IntBuffer;
    static nmaxMeshWorkGroupTotalCount(paramarg0: number): number;
    static nmaxPreferredMeshWorkGroupInvocations(paramarg0: number): number;
    static nmaxPreferredTaskWorkGroupInvocations(paramarg0: number): number;
    static nmaxTaskPayloadAndSharedMemorySize(paramarg0: number): number;
    static nmaxTaskPayloadSize(paramarg0: number): number;
    static nmaxTaskSharedMemorySize(paramarg0: number): number;
    static nmaxTaskWorkGroupCount(paramarg0: number, paramarg1: number): number;
    static nmaxTaskWorkGroupCount(paramarg0: number): IntBuffer;
    static nmaxTaskWorkGroupInvocations(paramarg0: number): number;
    static nmaxTaskWorkGroupSize(paramarg0: number, paramarg1: number): number;
    static nmaxTaskWorkGroupSize(paramarg0: number): IntBuffer;
    static nmaxTaskWorkGroupTotalCount(paramarg0: number): number;
    static nmeshOutputPerPrimitiveGranularity(paramarg0: number): number;
    static nmeshOutputPerVertexGranularity(paramarg0: number): number;
    static npNext(paramarg0: number): number;
    static npNext(paramarg0: number, paramarg1: number): void;
    static nprefersCompactPrimitiveOutput(paramarg0: number): number;
    static nprefersCompactVertexOutput(paramarg0: number): number;
    static nprefersLocalInvocationPrimitiveOutput(paramarg0: number): number;
    static nprefersLocalInvocationVertexOutput(paramarg0: number): number;
    static nsType(paramarg0: number): number;
    static nsType(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    close(): void;
    create(arg0: number, arg1: ByteBuffer): VkPhysicalDeviceMeshShaderPropertiesEXT;
    maxMeshMultiviewViewCount(): number;
    maxMeshOutputComponents(): number;
    maxMeshOutputLayers(): number;
    maxMeshOutputMemorySize(): number;
    maxMeshOutputPrimitives(): number;
    maxMeshOutputVertices(): number;
    maxMeshPayloadAndOutputMemorySize(): number;
    maxMeshPayloadAndSharedMemorySize(): number;
    maxMeshSharedMemorySize(): number;
    maxMeshWorkGroupCount(): IntBuffer;
    maxMeshWorkGroupCount(arg0: number): number;
    maxMeshWorkGroupInvocations(): number;
    maxMeshWorkGroupSize(): IntBuffer;
    maxMeshWorkGroupSize(arg0: number): number;
    maxMeshWorkGroupTotalCount(): number;
    maxPreferredMeshWorkGroupInvocations(): number;
    maxPreferredTaskWorkGroupInvocations(): number;
    maxTaskPayloadAndSharedMemorySize(): number;
    maxTaskPayloadSize(): number;
    maxTaskSharedMemorySize(): number;
    maxTaskWorkGroupCount(): IntBuffer;
    maxTaskWorkGroupCount(arg0: number): number;
    maxTaskWorkGroupInvocations(): number;
    maxTaskWorkGroupSize(): IntBuffer;
    maxTaskWorkGroupSize(arg0: number): number;
    maxTaskWorkGroupTotalCount(): number;
    meshOutputPerPrimitiveGranularity(): number;
    meshOutputPerVertexGranularity(): number;
    pNext(): number;
    pNext(arg0: number): VkPhysicalDeviceMeshShaderPropertiesEXT;
    prefersCompactPrimitiveOutput(): boolean;
    prefersCompactVertexOutput(): boolean;
    prefersLocalInvocationPrimitiveOutput(): boolean;
    prefersLocalInvocationVertexOutput(): boolean;
    sType(): number;
    sType(arg0: number): VkPhysicalDeviceMeshShaderPropertiesEXT;
    sType$Default(): VkPhysicalDeviceMeshShaderPropertiesEXT;
    set(arg0: number, arg1: number): VkPhysicalDeviceMeshShaderPropertiesEXT;
    set(arg0: VkPhysicalDeviceMeshShaderPropertiesEXT): VkPhysicalDeviceMeshShaderPropertiesEXT;
    sizeof(): number;
}