import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class VkSRTDataNV extends Struct<VkSRTDataNV> implements NativeResource {
    static A: number;
    static ALIGNOF: number;
    static B: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static C: number;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static PVX: number;
    static PVY: number;
    static PVZ: number;
    static QW: number;
    static QX: number;
    static QY: number;
    static QZ: number;
    static SIZEOF: number;
    static SX: number;
    static SY: number;
    static SZ: number;
    static TX: number;
    static TY: number;
    static TZ: number;
    static calloc(): VkSRTDataNV;
    static calloc(paramarg0: MemoryStack): VkSRTDataNV;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): VkSRTDataNV;
    static create(paramarg0: number): VkSRTDataNV;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): VkSRTDataNV;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): VkSRTDataNV;
    static malloc(paramarg0: MemoryStack): VkSRTDataNV;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static na(paramarg0: number): number;
    static na(paramarg0: number, paramarg1: number): void;
    static nb(paramarg0: number): number;
    static nb(paramarg0: number, paramarg1: number): void;
    static nc(paramarg0: number): number;
    static nc(paramarg0: number, paramarg1: number): void;
    static npvx(paramarg0: number): number;
    static npvx(paramarg0: number, paramarg1: number): void;
    static npvy(paramarg0: number): number;
    static npvy(paramarg0: number, paramarg1: number): void;
    static npvz(paramarg0: number): number;
    static npvz(paramarg0: number, paramarg1: number): void;
    static nqw(paramarg0: number): number;
    static nqw(paramarg0: number, paramarg1: number): void;
    static nqx(paramarg0: number): number;
    static nqx(paramarg0: number, paramarg1: number): void;
    static nqy(paramarg0: number): number;
    static nqy(paramarg0: number, paramarg1: number): void;
    static nqz(paramarg0: number): number;
    static nqz(paramarg0: number, paramarg1: number): void;
    static nsx(paramarg0: number): number;
    static nsx(paramarg0: number, paramarg1: number): void;
    static nsy(paramarg0: number): number;
    static nsy(paramarg0: number, paramarg1: number): void;
    static nsz(paramarg0: number): number;
    static nsz(paramarg0: number, paramarg1: number): void;
    static ntx(paramarg0: number): number;
    static ntx(paramarg0: number, paramarg1: number): void;
    static nty(paramarg0: number): number;
    static nty(paramarg0: number, paramarg1: number): void;
    static ntz(paramarg0: number): number;
    static ntz(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    a(): number;
    a(arg0: number): VkSRTDataNV;
    b(): number;
    b(arg0: number): VkSRTDataNV;
    c(): number;
    c(arg0: number): VkSRTDataNV;
    close(): void;
    create(arg0: number, arg1: ByteBuffer): VkSRTDataNV;
    pvx(): number;
    pvx(arg0: number): VkSRTDataNV;
    pvy(): number;
    pvy(arg0: number): VkSRTDataNV;
    pvz(): number;
    pvz(arg0: number): VkSRTDataNV;
    qw(): number;
    qw(arg0: number): VkSRTDataNV;
    qx(): number;
    qx(arg0: number): VkSRTDataNV;
    qy(): number;
    qy(arg0: number): VkSRTDataNV;
    qz(): number;
    qz(arg0: number): VkSRTDataNV;
    set(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number, arg15: number): VkSRTDataNV;
    set(arg0: VkSRTDataNV): VkSRTDataNV;
    sizeof(): number;
    sx(): number;
    sx(arg0: number): VkSRTDataNV;
    sy(): number;
    sy(arg0: number): VkSRTDataNV;
    sz(): number;
    sz(arg0: number): VkSRTDataNV;
    tx(): number;
    tx(arg0: number): VkSRTDataNV;
    ty(): number;
    ty(arg0: number): VkSRTDataNV;
    tz(): number;
    tz(arg0: number): VkSRTDataNV;
}