import type { Serializable } from '../../../../../../../java/io/Serializable.d.ts'
import type { Object } from '../../../../../../../java/lang/Object.d.ts'
import type { MeasureUnitImpl } from '../../../../../../../org/graalvm/shadowed/com/ibm/icu/impl/units/MeasureUnitImpl.d.ts'
import type { SingleUnitImpl } from '../../../../../../../org/graalvm/shadowed/com/ibm/icu/impl/units/SingleUnitImpl.d.ts'
import type { MeasureUnit$Complexity } from '../../../../../../../org/graalvm/shadowed/com/ibm/icu/util/MeasureUnit$Complexity.d.ts'
import type { MeasureUnit$MeasurePrefix } from '../../../../../../../org/graalvm/shadowed/com/ibm/icu/util/MeasureUnit$MeasurePrefix.d.ts'
import type { TimeUnit } from '../../../../../../../org/graalvm/shadowed/com/ibm/icu/util/TimeUnit.d.ts'
export class MeasureUnit extends Object implements Serializable {
    static ACRE: MeasureUnit;
    static ACRE_FOOT: MeasureUnit;
    static AMPERE: MeasureUnit;
    static ARC_MINUTE: MeasureUnit;
    static ARC_SECOND: MeasureUnit;
    static ASTRONOMICAL_UNIT: MeasureUnit;
    static ATMOSPHERE: MeasureUnit;
    static BAR: MeasureUnit;
    static BARREL: MeasureUnit;
    static BEAUFORT: MeasureUnit;
    static BIT: MeasureUnit;
    static BRITISH_THERMAL_UNIT: MeasureUnit;
    static BUSHEL: MeasureUnit;
    static BYTE: MeasureUnit;
    static CALORIE: MeasureUnit;
    static CANDELA: MeasureUnit;
    static CARAT: MeasureUnit;
    static CELSIUS: MeasureUnit;
    static CENTILITER: MeasureUnit;
    static CENTIMETER: MeasureUnit;
    static CENTURY: MeasureUnit;
    static CUBIC_CENTIMETER: MeasureUnit;
    static CUBIC_FOOT: MeasureUnit;
    static CUBIC_INCH: MeasureUnit;
    static CUBIC_KILOMETER: MeasureUnit;
    static CUBIC_METER: MeasureUnit;
    static CUBIC_MILE: MeasureUnit;
    static CUBIC_YARD: MeasureUnit;
    static CUP: MeasureUnit;
    static CUP_METRIC: MeasureUnit;
    static DALTON: MeasureUnit;
    static DAY: TimeUnit;
    static DAY_PERSON: MeasureUnit;
    static DECADE: MeasureUnit;
    static DECILITER: MeasureUnit;
    static DECIMETER: MeasureUnit;
    static DEGREE: MeasureUnit;
    static DESSERT_SPOON: MeasureUnit;
    static DESSERT_SPOON_IMPERIAL: MeasureUnit;
    static DOT: MeasureUnit;
    static DOT_PER_CENTIMETER: MeasureUnit;
    static DOT_PER_INCH: MeasureUnit;
    static DRAM: MeasureUnit;
    static DROP: MeasureUnit;
    static DUNAM: MeasureUnit;
    static EARTH_MASS: MeasureUnit;
    static EARTH_RADIUS: MeasureUnit;
    static ELECTRONVOLT: MeasureUnit;
    static EM: MeasureUnit;
    static FAHRENHEIT: MeasureUnit;
    static FATHOM: MeasureUnit;
    static FLUID_OUNCE: MeasureUnit;
    static FLUID_OUNCE_IMPERIAL: MeasureUnit;
    static FOODCALORIE: MeasureUnit;
    static FOOT: MeasureUnit;
    static FURLONG: MeasureUnit;
    static GALLON: MeasureUnit;
    static GALLON_IMPERIAL: MeasureUnit;
    static GASOLINE_ENERGY_DENSITY: MeasureUnit;
    static GENERIC_TEMPERATURE: MeasureUnit;
    static GIGABIT: MeasureUnit;
    static GIGABYTE: MeasureUnit;
    static GIGAHERTZ: MeasureUnit;
    static GIGAWATT: MeasureUnit;
    static GRAIN: MeasureUnit;
    static GRAM: MeasureUnit;
    static G_FORCE: MeasureUnit;
    static HECTARE: MeasureUnit;
    static HECTOLITER: MeasureUnit;
    static HECTOPASCAL: MeasureUnit;
    static HERTZ: MeasureUnit;
    static HORSEPOWER: MeasureUnit;
    static HOUR: TimeUnit;
    static INCH: MeasureUnit;
    static INCH_HG: MeasureUnit;
    static ITEM: MeasureUnit;
    static JIGGER: MeasureUnit;
    static JOULE: MeasureUnit;
    static KARAT: MeasureUnit;
    static KELVIN: MeasureUnit;
    static KILOBIT: MeasureUnit;
    static KILOBYTE: MeasureUnit;
    static KILOCALORIE: MeasureUnit;
    static KILOGRAM: MeasureUnit;
    static KILOHERTZ: MeasureUnit;
    static KILOJOULE: MeasureUnit;
    static KILOMETER: MeasureUnit;
    static KILOMETER_PER_HOUR: MeasureUnit;
    static KILOPASCAL: MeasureUnit;
    static KILOWATT: MeasureUnit;
    static KILOWATT_HOUR: MeasureUnit;
    static KILOWATT_HOUR_PER_100_KILOMETER: MeasureUnit;
    static KNOT: MeasureUnit;
    static LIGHT_SPEED: MeasureUnit;
    static LIGHT_YEAR: MeasureUnit;
    static LITER: MeasureUnit;
    static LITER_PER_100KILOMETERS: MeasureUnit;
    static LITER_PER_KILOMETER: MeasureUnit;
    static LUMEN: MeasureUnit;
    static LUX: MeasureUnit;
    static MEGABIT: MeasureUnit;
    static MEGABYTE: MeasureUnit;
    static MEGAHERTZ: MeasureUnit;
    static MEGALITER: MeasureUnit;
    static MEGAPASCAL: MeasureUnit;
    static MEGAPIXEL: MeasureUnit;
    static MEGAWATT: MeasureUnit;
    static METER: MeasureUnit;
    static METER_PER_SECOND: MeasureUnit;
    static METER_PER_SECOND_SQUARED: MeasureUnit;
    static METRIC_TON: MeasureUnit;
    static MICROGRAM: MeasureUnit;
    static MICROMETER: MeasureUnit;
    static MICROSECOND: MeasureUnit;
    static MILE: MeasureUnit;
    static MILE_PER_GALLON: MeasureUnit;
    static MILE_PER_GALLON_IMPERIAL: MeasureUnit;
    static MILE_PER_HOUR: MeasureUnit;
    static MILE_SCANDINAVIAN: MeasureUnit;
    static MILLIAMPERE: MeasureUnit;
    static MILLIBAR: MeasureUnit;
    static MILLIGRAM: MeasureUnit;
    static MILLIGRAM_OFGLUCOSE_PER_DECILITER: MeasureUnit;
    static MILLIGRAM_PER_DECILITER: MeasureUnit;
    static MILLILITER: MeasureUnit;
    static MILLIMETER: MeasureUnit;
    static MILLIMETER_OF_MERCURY: MeasureUnit;
    static MILLIMOLE_PER_LITER: MeasureUnit;
    static MILLISECOND: MeasureUnit;
    static MILLIWATT: MeasureUnit;
    static MINUTE: TimeUnit;
    static MOLE: MeasureUnit;
    static MONTH: TimeUnit;
    static MONTH_PERSON: MeasureUnit;
    static NANOMETER: MeasureUnit;
    static NANOSECOND: MeasureUnit;
    static NAUTICAL_MILE: MeasureUnit;
    static NEWTON: MeasureUnit;
    static NEWTON_METER: MeasureUnit;
    static NIGHT: MeasureUnit;
    static OHM: MeasureUnit;
    static OUNCE: MeasureUnit;
    static OUNCE_TROY: MeasureUnit;
    static PARSEC: MeasureUnit;
    static PART_PER_MILLION: MeasureUnit;
    static PASCAL: MeasureUnit;
    static PERCENT: MeasureUnit;
    static PERMILLE: MeasureUnit;
    static PERMYRIAD: MeasureUnit;
    static PETABYTE: MeasureUnit;
    static PICOMETER: MeasureUnit;
    static PINCH: MeasureUnit;
    static PINT: MeasureUnit;
    static PINT_METRIC: MeasureUnit;
    static PIXEL: MeasureUnit;
    static PIXEL_PER_CENTIMETER: MeasureUnit;
    static PIXEL_PER_INCH: MeasureUnit;
    static POINT: MeasureUnit;
    static POUND: MeasureUnit;
    static POUND_FOOT: MeasureUnit;
    static POUND_FORCE: MeasureUnit;
    static POUND_PER_SQUARE_INCH: MeasureUnit;
    static QUART: MeasureUnit;
    static QUARTER: MeasureUnit;
    static QUART_IMPERIAL: MeasureUnit;
    static RADIAN: MeasureUnit;
    static REVOLUTION_ANGLE: MeasureUnit;
    static SECOND: TimeUnit;
    static SOLAR_LUMINOSITY: MeasureUnit;
    static SOLAR_MASS: MeasureUnit;
    static SOLAR_RADIUS: MeasureUnit;
    static SQUARE_CENTIMETER: MeasureUnit;
    static SQUARE_FOOT: MeasureUnit;
    static SQUARE_INCH: MeasureUnit;
    static SQUARE_KILOMETER: MeasureUnit;
    static SQUARE_METER: MeasureUnit;
    static SQUARE_MILE: MeasureUnit;
    static SQUARE_YARD: MeasureUnit;
    static STONE: MeasureUnit;
    static TABLESPOON: MeasureUnit;
    static TEASPOON: MeasureUnit;
    static TERABIT: MeasureUnit;
    static TERABYTE: MeasureUnit;
    static THERM_US: MeasureUnit;
    static TON: MeasureUnit;
    static TONNE: MeasureUnit;
    static VOLT: MeasureUnit;
    static WATT: MeasureUnit;
    static WEEK: TimeUnit;
    static WEEK_PERSON: MeasureUnit;
    static YARD: MeasureUnit;
    static YEAR: TimeUnit;
    static YEAR_PERSON: MeasureUnit;
    static findBySubType(paramsubType: string): MeasureUnit;
    static forIdentifier(paramidentifier: string): MeasureUnit;
    static fromMeasureUnitImpl(parammeasureUnitImpl: MeasureUnitImpl): MeasureUnit;
    static getAvailable(paramtype: string): MeasureUnit[];
    static getAvailable(): MeasureUnit[];
    static getAvailableTypes(): string[];
    static internalGetInstance(paramtype: string, paramsubType: string): MeasureUnit;
    constructor(type: string, subType: string)
    private constructor(measureUnitImpl: MeasureUnitImpl)
    // private measureUnitImpl: MeasureUnitImpl;
    // private subType: string;
    readonly type: string;
    equals(rhs: Object | null): boolean;
    getComplexity(): MeasureUnit$Complexity;
    getCopyOfMeasureUnitImpl(): MeasureUnitImpl;
    getDimensionality(): number;
    getIdentifier(): string;
    // private getMaybeReferenceOfMeasureUnitImpl(): MeasureUnitImpl;
    getPrefix(): MeasureUnit$MeasurePrefix;
    // private getSingleUnitImpl(): SingleUnitImpl;
    getSubtype(): string;
    getType(): string;
    hashCode(): number;
    product(other: MeasureUnit): MeasureUnit;
    reciprocal(): MeasureUnit;
    splitToSingleUnits(): MeasureUnit[];
    toString(): string;
    withDimensionality(dimensionality: number): MeasureUnit;
    withPrefix(prefix: MeasureUnit$MeasurePrefix): MeasureUnit;
    // private writeReplace(): Object;
}