import type { App } from '../../../com/mojang/datafixers/kinds/App.d.ts'
import type { Applicative } from '../../../com/mojang/datafixers/kinds/Applicative.d.ts'
import type { Applicative$Mu } from '../../../com/mojang/datafixers/kinds/Applicative$Mu.d.ts'
import type { K1 } from '../../../com/mojang/datafixers/kinds/K1.d.ts'
import type { Function10 } from '../../../com/mojang/datafixers/util/Function10.d.ts'
import type { Function11 } from '../../../com/mojang/datafixers/util/Function11.d.ts'
import type { Function12 } from '../../../com/mojang/datafixers/util/Function12.d.ts'
import type { Function13 } from '../../../com/mojang/datafixers/util/Function13.d.ts'
import type { Function14 } from '../../../com/mojang/datafixers/util/Function14.d.ts'
import type { Function15 } from '../../../com/mojang/datafixers/util/Function15.d.ts'
import type { Function16 } from '../../../com/mojang/datafixers/util/Function16.d.ts'
import type { Function3 } from '../../../com/mojang/datafixers/util/Function3.d.ts'
import type { Function4 } from '../../../com/mojang/datafixers/util/Function4.d.ts'
import type { Function5 } from '../../../com/mojang/datafixers/util/Function5.d.ts'
import type { Function6 } from '../../../com/mojang/datafixers/util/Function6.d.ts'
import type { Function7 } from '../../../com/mojang/datafixers/util/Function7.d.ts'
import type { Function8 } from '../../../com/mojang/datafixers/util/Function8.d.ts'
import type { Function9 } from '../../../com/mojang/datafixers/util/Function9.d.ts'
import type { DataResult$Instance$Mu } from '../../../com/mojang/serialization/DataResult$Instance$Mu.d.ts'
import type { DataResult$Mu } from '../../../com/mojang/serialization/DataResult$Mu.d.ts'
import type { Class } from '../../../java/lang/Class.d.ts'
import type { BiFunction } from '../../../java/util/function/BiFunction.d.ts'
import type { Function } from '../../../java/util/function/Function.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { Enum } from '../../../java/lang/Enum.d.ts'
export class DataResult$Instance extends Enum<DataResult$Instance> implements Applicative<DataResult$Mu, DataResult$Instance$Mu> {
    static INSTANCE: DataResult$Instance;
    static unbox(paramarg0: App<Applicative$Mu, K1>): Applicative<K1, Applicative$Mu>;
    static valueOf(paramarg0: Class<Object>, paramarg1: string): Object | null;
    static valueOf(paramarg0: string): DataResult$Instance;
    static values(): DataResult$Instance[];
    private constructor()
    ap<R extends unknown, A extends unknown>(arg0: App<DataResult$Mu, (param0: A) => R>, arg1: App<DataResult$Mu, A>): App<DataResult$Mu, R>;
    ap<R extends unknown, A extends unknown>(arg0: (param0: A) => R, arg1: App<DataResult$Mu, A>): App<DataResult$Mu, R>;
    ap10<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown>(arg0: App<DataResult$Mu, Function10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>, arg7: App<DataResult$Mu, T7>, arg8: App<DataResult$Mu, T8>, arg9: App<DataResult$Mu, T9>, arg10: App<DataResult$Mu, T10>): App<DataResult$Mu, R>;
    ap11<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown>(arg0: App<DataResult$Mu, Function11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>, arg7: App<DataResult$Mu, T7>, arg8: App<DataResult$Mu, T8>, arg9: App<DataResult$Mu, T9>, arg10: App<DataResult$Mu, T10>, arg11: App<DataResult$Mu, T11>): App<DataResult$Mu, R>;
    ap12<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown, T12 extends unknown>(arg0: App<DataResult$Mu, Function12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>, arg7: App<DataResult$Mu, T7>, arg8: App<DataResult$Mu, T8>, arg9: App<DataResult$Mu, T9>, arg10: App<DataResult$Mu, T10>, arg11: App<DataResult$Mu, T11>, arg12: App<DataResult$Mu, T12>): App<DataResult$Mu, R>;
    ap13<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown, T12 extends unknown, T13 extends unknown>(arg0: App<DataResult$Mu, Function13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>, arg7: App<DataResult$Mu, T7>, arg8: App<DataResult$Mu, T8>, arg9: App<DataResult$Mu, T9>, arg10: App<DataResult$Mu, T10>, arg11: App<DataResult$Mu, T11>, arg12: App<DataResult$Mu, T12>, arg13: App<DataResult$Mu, T13>): App<DataResult$Mu, R>;
    ap14<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown, T12 extends unknown, T13 extends unknown, T14 extends unknown>(arg0: App<DataResult$Mu, Function14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>, arg7: App<DataResult$Mu, T7>, arg8: App<DataResult$Mu, T8>, arg9: App<DataResult$Mu, T9>, arg10: App<DataResult$Mu, T10>, arg11: App<DataResult$Mu, T11>, arg12: App<DataResult$Mu, T12>, arg13: App<DataResult$Mu, T13>, arg14: App<DataResult$Mu, T14>): App<DataResult$Mu, R>;
    ap15<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown, T12 extends unknown, T13 extends unknown, T14 extends unknown, T15 extends unknown>(arg0: App<DataResult$Mu, Function15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>, arg7: App<DataResult$Mu, T7>, arg8: App<DataResult$Mu, T8>, arg9: App<DataResult$Mu, T9>, arg10: App<DataResult$Mu, T10>, arg11: App<DataResult$Mu, T11>, arg12: App<DataResult$Mu, T12>, arg13: App<DataResult$Mu, T13>, arg14: App<DataResult$Mu, T14>, arg15: App<DataResult$Mu, T15>): App<DataResult$Mu, R>;
    ap16<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown, T12 extends unknown, T13 extends unknown, T14 extends unknown, T15 extends unknown, T16 extends unknown>(arg0: App<DataResult$Mu, Function16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>, arg7: App<DataResult$Mu, T7>, arg8: App<DataResult$Mu, T8>, arg9: App<DataResult$Mu, T9>, arg10: App<DataResult$Mu, T10>, arg11: App<DataResult$Mu, T11>, arg12: App<DataResult$Mu, T12>, arg13: App<DataResult$Mu, T13>, arg14: App<DataResult$Mu, T14>, arg15: App<DataResult$Mu, T15>, arg16: App<DataResult$Mu, T16>): App<DataResult$Mu, R>;
    ap2<R extends unknown, A extends unknown, B extends unknown>(arg0: App<DataResult$Mu, (param0: A, param1: B) => R>, arg1: App<DataResult$Mu, A>, arg2: App<DataResult$Mu, B>): App<DataResult$Mu, R>;
    ap3<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown>(arg0: App<DataResult$Mu, Function3<T1, T2, T3, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>): App<DataResult$Mu, R>;
    ap4<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown>(arg0: App<DataResult$Mu, Function4<T1, T2, T3, T4, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>): App<DataResult$Mu, R>;
    ap5<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown>(arg0: App<DataResult$Mu, Function5<T1, T2, T3, T4, T5, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>): App<DataResult$Mu, R>;
    ap6<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown>(arg0: App<DataResult$Mu, Function6<T1, T2, T3, T4, T5, T6, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>): App<DataResult$Mu, R>;
    ap7<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown>(arg0: App<DataResult$Mu, Function7<T1, T2, T3, T4, T5, T6, T7, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>, arg7: App<DataResult$Mu, T7>): App<DataResult$Mu, R>;
    ap8<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown>(arg0: App<DataResult$Mu, Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>, arg7: App<DataResult$Mu, T7>, arg8: App<DataResult$Mu, T8>): App<DataResult$Mu, R>;
    ap9<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown>(arg0: App<DataResult$Mu, Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>, arg7: App<DataResult$Mu, T7>, arg8: App<DataResult$Mu, T8>, arg9: App<DataResult$Mu, T9>): App<DataResult$Mu, R>;
    apply2<R extends unknown, A extends unknown, B extends unknown>(arg0: (param0: A, param1: B) => R, arg1: App<DataResult$Mu, A>, arg2: App<DataResult$Mu, B>): App<DataResult$Mu, R>;
    apply3<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown>(arg0: Function3<T1, T2, T3, R>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>): App<DataResult$Mu, R>;
    apply4<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown>(arg0: Function4<T1, T2, T3, T4, R>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>): App<DataResult$Mu, R>;
    apply5<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown>(arg0: Function5<T1, T2, T3, T4, T5, R>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>): App<DataResult$Mu, R>;
    apply6<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown>(arg0: Function6<T1, T2, T3, T4, T5, T6, R>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>): App<DataResult$Mu, R>;
    apply7<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown>(arg0: Function7<T1, T2, T3, T4, T5, T6, T7, R>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>, arg7: App<DataResult$Mu, T7>): App<DataResult$Mu, R>;
    apply8<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown>(arg0: Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>, arg7: App<DataResult$Mu, T7>, arg8: App<DataResult$Mu, T8>): App<DataResult$Mu, R>;
    apply9<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown>(arg0: Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>, arg1: App<DataResult$Mu, T1>, arg2: App<DataResult$Mu, T2>, arg3: App<DataResult$Mu, T3>, arg4: App<DataResult$Mu, T4>, arg5: App<DataResult$Mu, T5>, arg6: App<DataResult$Mu, T6>, arg7: App<DataResult$Mu, T7>, arg8: App<DataResult$Mu, T8>, arg9: App<DataResult$Mu, T9>): App<DataResult$Mu, R>;
    lift1<A extends unknown, R extends unknown>(arg0: App<DataResult$Mu, (param0: A) => R>): (param0: App<DataResult$Mu, A>) => App<DataResult$Mu, R>;
    lift2<A extends unknown, B extends unknown, R extends unknown>(arg0: App<DataResult$Mu, (param0: A, param1: B) => R>): (param0: App<DataResult$Mu, A>, param1: App<DataResult$Mu, B>) => App<DataResult$Mu, R>;
    lift3<T1 extends unknown, T2 extends unknown, T3 extends unknown, R extends unknown>(arg0: App<DataResult$Mu, Function3<T1, T2, T3, R>>): Function3<App<DataResult$Mu, T1>, App<DataResult$Mu, T2>, App<DataResult$Mu, T3>, App<DataResult$Mu, R>>;
    lift4<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, R extends unknown>(arg0: App<DataResult$Mu, Function4<T1, T2, T3, T4, R>>): Function4<App<DataResult$Mu, T1>, App<DataResult$Mu, T2>, App<DataResult$Mu, T3>, App<DataResult$Mu, T4>, App<DataResult$Mu, R>>;
    lift5<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, R extends unknown>(arg0: App<DataResult$Mu, Function5<T1, T2, T3, T4, T5, R>>): Function5<App<DataResult$Mu, T1>, App<DataResult$Mu, T2>, App<DataResult$Mu, T3>, App<DataResult$Mu, T4>, App<DataResult$Mu, T5>, App<DataResult$Mu, R>>;
    lift6<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, R extends unknown>(arg0: App<DataResult$Mu, Function6<T1, T2, T3, T4, T5, T6, R>>): Function6<App<DataResult$Mu, T1>, App<DataResult$Mu, T2>, App<DataResult$Mu, T3>, App<DataResult$Mu, T4>, App<DataResult$Mu, T5>, App<DataResult$Mu, T6>, App<DataResult$Mu, R>>;
    lift7<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, R extends unknown>(arg0: App<DataResult$Mu, Function7<T1, T2, T3, T4, T5, T6, T7, R>>): Function7<App<DataResult$Mu, T1>, App<DataResult$Mu, T2>, App<DataResult$Mu, T3>, App<DataResult$Mu, T4>, App<DataResult$Mu, T5>, App<DataResult$Mu, T6>, App<DataResult$Mu, T7>, App<DataResult$Mu, R>>;
    lift8<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, R extends unknown>(arg0: App<DataResult$Mu, Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>>): Function8<App<DataResult$Mu, T1>, App<DataResult$Mu, T2>, App<DataResult$Mu, T3>, App<DataResult$Mu, T4>, App<DataResult$Mu, T5>, App<DataResult$Mu, T6>, App<DataResult$Mu, T7>, App<DataResult$Mu, T8>, App<DataResult$Mu, R>>;
    lift9<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, R extends unknown>(arg0: App<DataResult$Mu, Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>>): Function9<App<DataResult$Mu, T1>, App<DataResult$Mu, T2>, App<DataResult$Mu, T3>, App<DataResult$Mu, T4>, App<DataResult$Mu, T5>, App<DataResult$Mu, T6>, App<DataResult$Mu, T7>, App<DataResult$Mu, T8>, App<DataResult$Mu, T9>, App<DataResult$Mu, R>>;
    map<R extends unknown, T extends unknown>(arg0: (param0: T) => R, arg1: App<DataResult$Mu, T>): App<DataResult$Mu, R>;
    point<A extends unknown>(arg0: A): App<DataResult$Mu, A>;
    name(): "INSTANCE";
}