import type { BooleanIterator } from '../../../../../it/unimi/dsi/fastutil/booleans/BooleanIterator.d.ts'
import type { ByteIterator } from '../../../../../it/unimi/dsi/fastutil/bytes/ByteIterator.d.ts'
import type { CharIterator } from '../../../../../it/unimi/dsi/fastutil/chars/CharIterator.d.ts'
import type { DoubleIterator } from '../../../../../it/unimi/dsi/fastutil/doubles/DoubleIterator.d.ts'
import type { FloatIterator } from '../../../../../it/unimi/dsi/fastutil/floats/FloatIterator.d.ts'
import type { IntIterator } from '../../../../../it/unimi/dsi/fastutil/ints/IntIterator.d.ts'
import type { LongIterator } from '../../../../../it/unimi/dsi/fastutil/longs/LongIterator.d.ts'
import type { ShortIterator } from '../../../../../it/unimi/dsi/fastutil/shorts/ShortIterator.d.ts'
import type { DataInput } from '../../../../../java/io/DataInput.d.ts'
import type { DataOutput } from '../../../../../java/io/DataOutput.d.ts'
import type { File } from '../../../../../java/io/File.d.ts'
import type { InputStream } from '../../../../../java/io/InputStream.d.ts'
import type { OutputStream } from '../../../../../java/io/OutputStream.d.ts'
import type { ByteOrder } from '../../../../../java/nio/ByteOrder.d.ts'
import type { ReadableByteChannel } from '../../../../../java/nio/channels/ReadableByteChannel.d.ts'
import type { WritableByteChannel } from '../../../../../java/nio/channels/WritableByteChannel.d.ts'
import type { Object } from '../../../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../../../java/lang/CharSequence.d.ts'
export class BinIO extends Object {
    static BUFFER_SIZE: number;
    static asBooleanIterable(paramarg0: File): boolean[];
    static asBooleanIterable(paramarg0: CharSequence): boolean[];
    static asBooleanIterator(paramarg0: DataInput): BooleanIterator;
    static asBooleanIterator(paramarg0: File): BooleanIterator;
    static asBooleanIterator(paramarg0: CharSequence): BooleanIterator;
    static asByteIterable(paramarg0: File): number[];
    static asByteIterable(paramarg0: CharSequence): number[];
    static asByteIterator(paramarg0: DataInput): ByteIterator;
    static asByteIterator(paramarg0: File): ByteIterator;
    static asByteIterator(paramarg0: CharSequence): ByteIterator;
    static asCharIterable(paramarg0: File): string[];
    static asCharIterable(paramarg0: File, paramarg1: ByteOrder): string[];
    static asCharIterable(paramarg0: CharSequence): string[];
    static asCharIterable(paramarg0: CharSequence, paramarg1: ByteOrder): string[];
    static asCharIterator(paramarg0: DataInput): CharIterator;
    static asCharIterator(paramarg0: File): CharIterator;
    static asCharIterator(paramarg0: File, paramarg1: ByteOrder): CharIterator;
    static asCharIterator(paramarg0: CharSequence): CharIterator;
    static asCharIterator(paramarg0: CharSequence, paramarg1: ByteOrder): CharIterator;
    static asCharIterator(paramarg0: ReadableByteChannel, paramarg1: ByteOrder): CharIterator;
    static asDoubleIterable(paramarg0: File): number[];
    static asDoubleIterable(paramarg0: File, paramarg1: ByteOrder): number[];
    static asDoubleIterable(paramarg0: CharSequence): number[];
    static asDoubleIterable(paramarg0: CharSequence, paramarg1: ByteOrder): number[];
    static asDoubleIterator(paramarg0: DataInput): DoubleIterator;
    static asDoubleIterator(paramarg0: File): DoubleIterator;
    static asDoubleIterator(paramarg0: File, paramarg1: ByteOrder): DoubleIterator;
    static asDoubleIterator(paramarg0: CharSequence): DoubleIterator;
    static asDoubleIterator(paramarg0: CharSequence, paramarg1: ByteOrder): DoubleIterator;
    static asDoubleIterator(paramarg0: ReadableByteChannel, paramarg1: ByteOrder): DoubleIterator;
    static asFloatIterable(paramarg0: File): number[];
    static asFloatIterable(paramarg0: File, paramarg1: ByteOrder): number[];
    static asFloatIterable(paramarg0: CharSequence): number[];
    static asFloatIterable(paramarg0: CharSequence, paramarg1: ByteOrder): number[];
    static asFloatIterator(paramarg0: DataInput): FloatIterator;
    static asFloatIterator(paramarg0: File): FloatIterator;
    static asFloatIterator(paramarg0: File, paramarg1: ByteOrder): FloatIterator;
    static asFloatIterator(paramarg0: CharSequence): FloatIterator;
    static asFloatIterator(paramarg0: CharSequence, paramarg1: ByteOrder): FloatIterator;
    static asFloatIterator(paramarg0: ReadableByteChannel, paramarg1: ByteOrder): FloatIterator;
    static asIntIterable(paramarg0: File): number[];
    static asIntIterable(paramarg0: File, paramarg1: ByteOrder): number[];
    static asIntIterable(paramarg0: CharSequence): number[];
    static asIntIterable(paramarg0: CharSequence, paramarg1: ByteOrder): number[];
    static asIntIterator(paramarg0: DataInput): IntIterator;
    static asIntIterator(paramarg0: File): IntIterator;
    static asIntIterator(paramarg0: File, paramarg1: ByteOrder): IntIterator;
    static asIntIterator(paramarg0: CharSequence): IntIterator;
    static asIntIterator(paramarg0: CharSequence, paramarg1: ByteOrder): IntIterator;
    static asIntIterator(paramarg0: ReadableByteChannel, paramarg1: ByteOrder): IntIterator;
    static asLongIterable(paramarg0: File): number[];
    static asLongIterable(paramarg0: File, paramarg1: ByteOrder): number[];
    static asLongIterable(paramarg0: CharSequence): number[];
    static asLongIterable(paramarg0: CharSequence, paramarg1: ByteOrder): number[];
    static asLongIterator(paramarg0: DataInput): LongIterator;
    static asLongIterator(paramarg0: File): LongIterator;
    static asLongIterator(paramarg0: File, paramarg1: ByteOrder): LongIterator;
    static asLongIterator(paramarg0: CharSequence): LongIterator;
    static asLongIterator(paramarg0: CharSequence, paramarg1: ByteOrder): LongIterator;
    static asLongIterator(paramarg0: ReadableByteChannel, paramarg1: ByteOrder): LongIterator;
    static asShortIterable(paramarg0: File): number[];
    static asShortIterable(paramarg0: File, paramarg1: ByteOrder): number[];
    static asShortIterable(paramarg0: CharSequence): number[];
    static asShortIterable(paramarg0: CharSequence, paramarg1: ByteOrder): number[];
    static asShortIterator(paramarg0: DataInput): ShortIterator;
    static asShortIterator(paramarg0: File): ShortIterator;
    static asShortIterator(paramarg0: File, paramarg1: ByteOrder): ShortIterator;
    static asShortIterator(paramarg0: CharSequence): ShortIterator;
    static asShortIterator(paramarg0: CharSequence, paramarg1: ByteOrder): ShortIterator;
    static asShortIterator(paramarg0: ReadableByteChannel, paramarg1: ByteOrder): ShortIterator;
    static loadBooleans(paramarg0: File): (Object | null)[];
    static loadBooleans(paramarg0: CharSequence): (Object | null)[];
    static loadBooleans(paramarg0: DataInput, paramarg1: (Object | null)[]): number;
    static loadBooleans(paramarg0: DataInput, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadBooleans(paramarg0: File, paramarg1: (Object | null)[]): number;
    static loadBooleans(paramarg0: File, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadBooleans(paramarg0: CharSequence, paramarg1: (Object | null)[]): number;
    static loadBooleans(paramarg0: CharSequence, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadBooleans(paramarg0: DataInput, paramarg1: (Object | null)[]): number;
    static loadBooleans(paramarg0: DataInput, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadBooleans(paramarg0: File, paramarg1: (Object | null)[]): number;
    static loadBooleans(paramarg0: File, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadBooleans(paramarg0: CharSequence, paramarg1: (Object | null)[]): number;
    static loadBooleans(paramarg0: CharSequence, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadBooleansBig(paramarg0: File): (Object | null)[];
    static loadBooleansBig(paramarg0: CharSequence): (Object | null)[];
    static loadBytes(paramarg0: File): number[];
    static loadBytes(paramarg0: CharSequence): number[];
    static loadBytes(paramarg0: DataInput, paramarg1: number[]): number;
    static loadBytes(paramarg0: DataInput, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: File, paramarg1: number[]): number;
    static loadBytes(paramarg0: File, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: InputStream, paramarg1: number[]): number;
    static loadBytes(paramarg0: InputStream, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: CharSequence, paramarg1: number[]): number;
    static loadBytes(paramarg0: CharSequence, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: ReadableByteChannel, paramarg1: number[]): number;
    static loadBytes(paramarg0: ReadableByteChannel, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: DataInput, paramarg1: (Object | null)[]): number;
    static loadBytes(paramarg0: DataInput, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: File, paramarg1: (Object | null)[]): number;
    static loadBytes(paramarg0: File, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: InputStream, paramarg1: (Object | null)[]): number;
    static loadBytes(paramarg0: InputStream, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: CharSequence, paramarg1: (Object | null)[]): number;
    static loadBytes(paramarg0: CharSequence, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: ReadableByteChannel, paramarg1: (Object | null)[]): number;
    static loadBytes(paramarg0: ReadableByteChannel, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadBytesBig(paramarg0: File): (Object | null)[];
    static loadBytesBig(paramarg0: CharSequence): (Object | null)[];
    static loadChars(paramarg0: File): string[];
    static loadChars(paramarg0: File, paramarg1: ByteOrder): string[];
    static loadChars(paramarg0: CharSequence): string[];
    static loadChars(paramarg0: CharSequence, paramarg1: ByteOrder): string[];
    static loadChars(paramarg0: DataInput, paramarg1: string[]): number;
    static loadChars(paramarg0: DataInput, paramarg1: string[], paramarg2: number, paramarg3: number): number;
    static loadChars(paramarg0: File, paramarg1: string[]): number;
    static loadChars(paramarg0: File, paramarg1: string[], paramarg2: number, paramarg3: number): number;
    static loadChars(paramarg0: File, paramarg1: ByteOrder, paramarg2: string[]): number;
    static loadChars(paramarg0: File, paramarg1: ByteOrder, paramarg2: string[], paramarg3: number, paramarg4: number): number;
    static loadChars(paramarg0: CharSequence, paramarg1: string[]): number;
    static loadChars(paramarg0: CharSequence, paramarg1: string[], paramarg2: number, paramarg3: number): number;
    static loadChars(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: string[]): number;
    static loadChars(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: string[], paramarg3: number, paramarg4: number): number;
    static loadChars(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: string[]): number;
    static loadChars(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: string[], paramarg3: number, paramarg4: number): number;
    static loadChars(paramarg0: DataInput, paramarg1: (Object | null)[]): number;
    static loadChars(paramarg0: DataInput, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadChars(paramarg0: File, paramarg1: (Object | null)[]): number;
    static loadChars(paramarg0: File, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadChars(paramarg0: File, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadChars(paramarg0: File, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadChars(paramarg0: CharSequence, paramarg1: (Object | null)[]): number;
    static loadChars(paramarg0: CharSequence, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadChars(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadChars(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadChars(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadChars(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadCharsBig(paramarg0: File): (Object | null)[];
    static loadCharsBig(paramarg0: File, paramarg1: ByteOrder): (Object | null)[];
    static loadCharsBig(paramarg0: CharSequence): (Object | null)[];
    static loadCharsBig(paramarg0: CharSequence, paramarg1: ByteOrder): (Object | null)[];
    static loadDoubles(paramarg0: File): number[];
    static loadDoubles(paramarg0: File, paramarg1: ByteOrder): number[];
    static loadDoubles(paramarg0: CharSequence): number[];
    static loadDoubles(paramarg0: CharSequence, paramarg1: ByteOrder): number[];
    static loadDoubles(paramarg0: DataInput, paramarg1: number[]): number;
    static loadDoubles(paramarg0: DataInput, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadDoubles(paramarg0: File, paramarg1: number[]): number;
    static loadDoubles(paramarg0: File, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadDoubles(paramarg0: File, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadDoubles(paramarg0: File, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadDoubles(paramarg0: CharSequence, paramarg1: number[]): number;
    static loadDoubles(paramarg0: CharSequence, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadDoubles(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadDoubles(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadDoubles(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadDoubles(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadDoubles(paramarg0: DataInput, paramarg1: (Object | null)[]): number;
    static loadDoubles(paramarg0: DataInput, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadDoubles(paramarg0: File, paramarg1: (Object | null)[]): number;
    static loadDoubles(paramarg0: File, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadDoubles(paramarg0: File, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadDoubles(paramarg0: File, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadDoubles(paramarg0: CharSequence, paramarg1: (Object | null)[]): number;
    static loadDoubles(paramarg0: CharSequence, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadDoubles(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadDoubles(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadDoubles(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadDoubles(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadDoublesBig(paramarg0: File): (Object | null)[];
    static loadDoublesBig(paramarg0: File, paramarg1: ByteOrder): (Object | null)[];
    static loadDoublesBig(paramarg0: CharSequence): (Object | null)[];
    static loadDoublesBig(paramarg0: CharSequence, paramarg1: ByteOrder): (Object | null)[];
    static loadFloats(paramarg0: File): number[];
    static loadFloats(paramarg0: File, paramarg1: ByteOrder): number[];
    static loadFloats(paramarg0: CharSequence): number[];
    static loadFloats(paramarg0: CharSequence, paramarg1: ByteOrder): number[];
    static loadFloats(paramarg0: DataInput, paramarg1: number[]): number;
    static loadFloats(paramarg0: DataInput, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadFloats(paramarg0: File, paramarg1: number[]): number;
    static loadFloats(paramarg0: File, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadFloats(paramarg0: File, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadFloats(paramarg0: File, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadFloats(paramarg0: CharSequence, paramarg1: number[]): number;
    static loadFloats(paramarg0: CharSequence, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadFloats(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadFloats(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadFloats(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadFloats(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadFloats(paramarg0: DataInput, paramarg1: (Object | null)[]): number;
    static loadFloats(paramarg0: DataInput, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadFloats(paramarg0: File, paramarg1: (Object | null)[]): number;
    static loadFloats(paramarg0: File, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadFloats(paramarg0: File, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadFloats(paramarg0: File, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadFloats(paramarg0: CharSequence, paramarg1: (Object | null)[]): number;
    static loadFloats(paramarg0: CharSequence, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadFloats(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadFloats(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadFloats(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadFloats(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadFloatsBig(paramarg0: File): (Object | null)[];
    static loadFloatsBig(paramarg0: File, paramarg1: ByteOrder): (Object | null)[];
    static loadFloatsBig(paramarg0: CharSequence): (Object | null)[];
    static loadFloatsBig(paramarg0: CharSequence, paramarg1: ByteOrder): (Object | null)[];
    static loadInts(paramarg0: DataInput, paramarg1: number[]): number;
    static loadInts(paramarg0: DataInput, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadInts(paramarg0: File, paramarg1: number[]): number;
    static loadInts(paramarg0: File, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadInts(paramarg0: File, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadInts(paramarg0: File, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadInts(paramarg0: CharSequence, paramarg1: number[]): number;
    static loadInts(paramarg0: CharSequence, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadInts(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadInts(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadInts(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadInts(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadInts(paramarg0: File): number[];
    static loadInts(paramarg0: File, paramarg1: ByteOrder): number[];
    static loadInts(paramarg0: CharSequence): number[];
    static loadInts(paramarg0: CharSequence, paramarg1: ByteOrder): number[];
    static loadInts(paramarg0: DataInput, paramarg1: (Object | null)[]): number;
    static loadInts(paramarg0: DataInput, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadInts(paramarg0: File, paramarg1: (Object | null)[]): number;
    static loadInts(paramarg0: File, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadInts(paramarg0: File, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadInts(paramarg0: File, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadInts(paramarg0: CharSequence, paramarg1: (Object | null)[]): number;
    static loadInts(paramarg0: CharSequence, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadInts(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadInts(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadInts(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadInts(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadIntsBig(paramarg0: File): (Object | null)[];
    static loadIntsBig(paramarg0: File, paramarg1: ByteOrder): (Object | null)[];
    static loadIntsBig(paramarg0: CharSequence): (Object | null)[];
    static loadIntsBig(paramarg0: CharSequence, paramarg1: ByteOrder): (Object | null)[];
    static loadLongs(paramarg0: DataInput, paramarg1: number[]): number;
    static loadLongs(paramarg0: DataInput, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadLongs(paramarg0: File, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadLongs(paramarg0: File, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadLongs(paramarg0: File, paramarg1: number[]): number;
    static loadLongs(paramarg0: File, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadLongs(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadLongs(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadLongs(paramarg0: CharSequence, paramarg1: number[]): number;
    static loadLongs(paramarg0: CharSequence, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadLongs(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadLongs(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadLongs(paramarg0: DataInput, paramarg1: (Object | null)[]): number;
    static loadLongs(paramarg0: DataInput, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadLongs(paramarg0: File, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadLongs(paramarg0: File, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadLongs(paramarg0: File, paramarg1: (Object | null)[]): number;
    static loadLongs(paramarg0: File, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadLongs(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadLongs(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadLongs(paramarg0: CharSequence, paramarg1: (Object | null)[]): number;
    static loadLongs(paramarg0: CharSequence, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadLongs(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadLongs(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadLongs(paramarg0: File): number[];
    static loadLongs(paramarg0: File, paramarg1: ByteOrder): number[];
    static loadLongs(paramarg0: CharSequence): number[];
    static loadLongs(paramarg0: CharSequence, paramarg1: ByteOrder): number[];
    static loadLongsBig(paramarg0: File): (Object | null)[];
    static loadLongsBig(paramarg0: File, paramarg1: ByteOrder): (Object | null)[];
    static loadLongsBig(paramarg0: CharSequence): (Object | null)[];
    static loadLongsBig(paramarg0: CharSequence, paramarg1: ByteOrder): (Object | null)[];
    static loadObject(paramarg0: File): Object;
    static loadObject(paramarg0: InputStream): Object;
    static loadObject(paramarg0: CharSequence): Object;
    static loadShorts(paramarg0: DataInput, paramarg1: number[]): number;
    static loadShorts(paramarg0: DataInput, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadShorts(paramarg0: File, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadShorts(paramarg0: File, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadShorts(paramarg0: File, paramarg1: number[]): number;
    static loadShorts(paramarg0: File, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadShorts(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadShorts(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadShorts(paramarg0: CharSequence, paramarg1: number[]): number;
    static loadShorts(paramarg0: CharSequence, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadShorts(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: number[]): number;
    static loadShorts(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: number[], paramarg3: number, paramarg4: number): number;
    static loadShorts(paramarg0: DataInput, paramarg1: (Object | null)[]): number;
    static loadShorts(paramarg0: DataInput, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadShorts(paramarg0: File, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadShorts(paramarg0: File, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadShorts(paramarg0: File, paramarg1: (Object | null)[]): number;
    static loadShorts(paramarg0: File, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadShorts(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadShorts(paramarg0: CharSequence, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadShorts(paramarg0: CharSequence, paramarg1: (Object | null)[]): number;
    static loadShorts(paramarg0: CharSequence, paramarg1: (Object | null)[], paramarg2: number, paramarg3: number): number;
    static loadShorts(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: (Object | null)[]): number;
    static loadShorts(paramarg0: ReadableByteChannel, paramarg1: ByteOrder, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): number;
    static loadShorts(paramarg0: File): number[];
    static loadShorts(paramarg0: File, paramarg1: ByteOrder): number[];
    static loadShorts(paramarg0: CharSequence): number[];
    static loadShorts(paramarg0: CharSequence, paramarg1: ByteOrder): number[];
    static loadShortsBig(paramarg0: File): (Object | null)[];
    static loadShortsBig(paramarg0: File, paramarg1: ByteOrder): (Object | null)[];
    static loadShortsBig(paramarg0: CharSequence): (Object | null)[];
    static loadShortsBig(paramarg0: CharSequence, paramarg1: ByteOrder): (Object | null)[];
    static storeBooleans(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeBooleans(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeBooleans(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeBooleans(paramarg0: (Object | null)[], paramarg1: DataOutput): void;
    static storeBooleans(paramarg0: (Object | null)[], paramarg1: File): void;
    static storeBooleans(paramarg0: (Object | null)[], paramarg1: CharSequence): void;
    static storeBooleans(paramarg0: (Object | null)[], paramarg1: DataOutput): void;
    static storeBooleans(paramarg0: (Object | null)[], paramarg1: File): void;
    static storeBooleans(paramarg0: (Object | null)[], paramarg1: CharSequence): void;
    static storeBooleans(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeBooleans(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeBooleans(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeBooleans(paramarg0: BooleanIterator, paramarg1: DataOutput): void;
    static storeBooleans(paramarg0: BooleanIterator, paramarg1: File): void;
    static storeBooleans(paramarg0: BooleanIterator, paramarg1: CharSequence): void;
    static storeBytes(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeBytes(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeBytes(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: OutputStream): void;
    static storeBytes(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeBytes(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel): void;
    static storeBytes(paramarg0: number[], paramarg1: DataOutput): void;
    static storeBytes(paramarg0: number[], paramarg1: File): void;
    static storeBytes(paramarg0: number[], paramarg1: OutputStream): void;
    static storeBytes(paramarg0: number[], paramarg1: CharSequence): void;
    static storeBytes(paramarg0: number[], paramarg1: WritableByteChannel): void;
    static storeBytes(paramarg0: (Object | null)[], paramarg1: DataOutput): void;
    static storeBytes(paramarg0: (Object | null)[], paramarg1: File): void;
    static storeBytes(paramarg0: (Object | null)[], paramarg1: OutputStream): void;
    static storeBytes(paramarg0: (Object | null)[], paramarg1: CharSequence): void;
    static storeBytes(paramarg0: (Object | null)[], paramarg1: WritableByteChannel): void;
    static storeBytes(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeBytes(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeBytes(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: OutputStream): void;
    static storeBytes(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeBytes(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel): void;
    static storeBytes(paramarg0: ByteIterator, paramarg1: DataOutput): void;
    static storeBytes(paramarg0: ByteIterator, paramarg1: File): void;
    static storeBytes(paramarg0: ByteIterator, paramarg1: CharSequence): void;
    static storeChars(paramarg0: string[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeChars(paramarg0: string[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeChars(paramarg0: string[], paramarg1: number, paramarg2: number, paramarg3: File, paramarg4: ByteOrder): void;
    static storeChars(paramarg0: string[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeChars(paramarg0: string[], paramarg1: number, paramarg2: number, paramarg3: CharSequence, paramarg4: ByteOrder): void;
    static storeChars(paramarg0: string[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel, paramarg4: ByteOrder): void;
    static storeChars(paramarg0: string[], paramarg1: DataOutput): void;
    static storeChars(paramarg0: string[], paramarg1: File): void;
    static storeChars(paramarg0: string[], paramarg1: File, paramarg2: ByteOrder): void;
    static storeChars(paramarg0: string[], paramarg1: CharSequence): void;
    static storeChars(paramarg0: string[], paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeChars(paramarg0: string[], paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeChars(paramarg0: (Object | null)[], paramarg1: DataOutput): void;
    static storeChars(paramarg0: (Object | null)[], paramarg1: File): void;
    static storeChars(paramarg0: (Object | null)[], paramarg1: File, paramarg2: ByteOrder): void;
    static storeChars(paramarg0: (Object | null)[], paramarg1: CharSequence): void;
    static storeChars(paramarg0: (Object | null)[], paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeChars(paramarg0: (Object | null)[], paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeChars(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeChars(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeChars(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File, paramarg4: ByteOrder): void;
    static storeChars(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeChars(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence, paramarg4: ByteOrder): void;
    static storeChars(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel, paramarg4: ByteOrder): void;
    static storeChars(paramarg0: CharIterator, paramarg1: DataOutput): void;
    static storeChars(paramarg0: CharIterator, paramarg1: File): void;
    static storeChars(paramarg0: CharIterator, paramarg1: File, paramarg2: ByteOrder): void;
    static storeChars(paramarg0: CharIterator, paramarg1: CharSequence): void;
    static storeChars(paramarg0: CharIterator, paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeChars(paramarg0: CharIterator, paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeDoubles(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeDoubles(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeDoubles(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File, paramarg4: ByteOrder): void;
    static storeDoubles(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeDoubles(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence, paramarg4: ByteOrder): void;
    static storeDoubles(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel, paramarg4: ByteOrder): void;
    static storeDoubles(paramarg0: number[], paramarg1: DataOutput): void;
    static storeDoubles(paramarg0: number[], paramarg1: File): void;
    static storeDoubles(paramarg0: number[], paramarg1: File, paramarg2: ByteOrder): void;
    static storeDoubles(paramarg0: number[], paramarg1: CharSequence): void;
    static storeDoubles(paramarg0: number[], paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeDoubles(paramarg0: number[], paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeDoubles(paramarg0: (Object | null)[], paramarg1: DataOutput): void;
    static storeDoubles(paramarg0: (Object | null)[], paramarg1: File): void;
    static storeDoubles(paramarg0: (Object | null)[], paramarg1: File, paramarg2: ByteOrder): void;
    static storeDoubles(paramarg0: (Object | null)[], paramarg1: CharSequence): void;
    static storeDoubles(paramarg0: (Object | null)[], paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeDoubles(paramarg0: (Object | null)[], paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeDoubles(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeDoubles(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeDoubles(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File, paramarg4: ByteOrder): void;
    static storeDoubles(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeDoubles(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence, paramarg4: ByteOrder): void;
    static storeDoubles(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel, paramarg4: ByteOrder): void;
    static storeDoubles(paramarg0: DoubleIterator, paramarg1: DataOutput): void;
    static storeDoubles(paramarg0: DoubleIterator, paramarg1: File): void;
    static storeDoubles(paramarg0: DoubleIterator, paramarg1: File, paramarg2: ByteOrder): void;
    static storeDoubles(paramarg0: DoubleIterator, paramarg1: CharSequence): void;
    static storeDoubles(paramarg0: DoubleIterator, paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeDoubles(paramarg0: DoubleIterator, paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeFloats(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeFloats(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeFloats(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File, paramarg4: ByteOrder): void;
    static storeFloats(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeFloats(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence, paramarg4: ByteOrder): void;
    static storeFloats(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel, paramarg4: ByteOrder): void;
    static storeFloats(paramarg0: number[], paramarg1: DataOutput): void;
    static storeFloats(paramarg0: number[], paramarg1: File): void;
    static storeFloats(paramarg0: number[], paramarg1: File, paramarg2: ByteOrder): void;
    static storeFloats(paramarg0: number[], paramarg1: CharSequence): void;
    static storeFloats(paramarg0: number[], paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeFloats(paramarg0: number[], paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeFloats(paramarg0: (Object | null)[], paramarg1: DataOutput): void;
    static storeFloats(paramarg0: (Object | null)[], paramarg1: File): void;
    static storeFloats(paramarg0: (Object | null)[], paramarg1: File, paramarg2: ByteOrder): void;
    static storeFloats(paramarg0: (Object | null)[], paramarg1: CharSequence): void;
    static storeFloats(paramarg0: (Object | null)[], paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeFloats(paramarg0: (Object | null)[], paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeFloats(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeFloats(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeFloats(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File, paramarg4: ByteOrder): void;
    static storeFloats(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeFloats(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence, paramarg4: ByteOrder): void;
    static storeFloats(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel, paramarg4: ByteOrder): void;
    static storeFloats(paramarg0: FloatIterator, paramarg1: DataOutput): void;
    static storeFloats(paramarg0: FloatIterator, paramarg1: File): void;
    static storeFloats(paramarg0: FloatIterator, paramarg1: File, paramarg2: ByteOrder): void;
    static storeFloats(paramarg0: FloatIterator, paramarg1: CharSequence): void;
    static storeFloats(paramarg0: FloatIterator, paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeFloats(paramarg0: FloatIterator, paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeInts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeInts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeInts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File, paramarg4: ByteOrder): void;
    static storeInts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeInts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence, paramarg4: ByteOrder): void;
    static storeInts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel, paramarg4: ByteOrder): void;
    static storeInts(paramarg0: number[], paramarg1: DataOutput): void;
    static storeInts(paramarg0: number[], paramarg1: File): void;
    static storeInts(paramarg0: number[], paramarg1: File, paramarg2: ByteOrder): void;
    static storeInts(paramarg0: number[], paramarg1: CharSequence): void;
    static storeInts(paramarg0: number[], paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeInts(paramarg0: number[], paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeInts(paramarg0: (Object | null)[], paramarg1: DataOutput): void;
    static storeInts(paramarg0: (Object | null)[], paramarg1: File): void;
    static storeInts(paramarg0: (Object | null)[], paramarg1: File, paramarg2: ByteOrder): void;
    static storeInts(paramarg0: (Object | null)[], paramarg1: CharSequence): void;
    static storeInts(paramarg0: (Object | null)[], paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeInts(paramarg0: (Object | null)[], paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeInts(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeInts(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeInts(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File, paramarg4: ByteOrder): void;
    static storeInts(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeInts(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence, paramarg4: ByteOrder): void;
    static storeInts(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel, paramarg4: ByteOrder): void;
    static storeInts(paramarg0: IntIterator, paramarg1: DataOutput): void;
    static storeInts(paramarg0: IntIterator, paramarg1: File): void;
    static storeInts(paramarg0: IntIterator, paramarg1: File, paramarg2: ByteOrder): void;
    static storeInts(paramarg0: IntIterator, paramarg1: CharSequence): void;
    static storeInts(paramarg0: IntIterator, paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeInts(paramarg0: IntIterator, paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeLongs(paramarg0: LongIterator, paramarg1: DataOutput): void;
    static storeLongs(paramarg0: LongIterator, paramarg1: File): void;
    static storeLongs(paramarg0: LongIterator, paramarg1: File, paramarg2: ByteOrder): void;
    static storeLongs(paramarg0: LongIterator, paramarg1: CharSequence): void;
    static storeLongs(paramarg0: LongIterator, paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeLongs(paramarg0: LongIterator, paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeLongs(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeLongs(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeLongs(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File, paramarg4: ByteOrder): void;
    static storeLongs(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeLongs(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence, paramarg4: ByteOrder): void;
    static storeLongs(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel, paramarg4: ByteOrder): void;
    static storeLongs(paramarg0: number[], paramarg1: DataOutput): void;
    static storeLongs(paramarg0: number[], paramarg1: File): void;
    static storeLongs(paramarg0: number[], paramarg1: File, paramarg2: ByteOrder): void;
    static storeLongs(paramarg0: number[], paramarg1: CharSequence): void;
    static storeLongs(paramarg0: number[], paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeLongs(paramarg0: number[], paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeLongs(paramarg0: (Object | null)[], paramarg1: DataOutput): void;
    static storeLongs(paramarg0: (Object | null)[], paramarg1: File): void;
    static storeLongs(paramarg0: (Object | null)[], paramarg1: File, paramarg2: ByteOrder): void;
    static storeLongs(paramarg0: (Object | null)[], paramarg1: CharSequence): void;
    static storeLongs(paramarg0: (Object | null)[], paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeLongs(paramarg0: (Object | null)[], paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeLongs(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeLongs(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeLongs(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File, paramarg4: ByteOrder): void;
    static storeLongs(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeLongs(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence, paramarg4: ByteOrder): void;
    static storeLongs(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel, paramarg4: ByteOrder): void;
    static storeObject(paramarg0: Object, paramarg1: File): void;
    static storeObject(paramarg0: Object, paramarg1: OutputStream): void;
    static storeObject(paramarg0: Object, paramarg1: CharSequence): void;
    static storeShorts(paramarg0: ShortIterator, paramarg1: DataOutput): void;
    static storeShorts(paramarg0: ShortIterator, paramarg1: File): void;
    static storeShorts(paramarg0: ShortIterator, paramarg1: File, paramarg2: ByteOrder): void;
    static storeShorts(paramarg0: ShortIterator, paramarg1: CharSequence): void;
    static storeShorts(paramarg0: ShortIterator, paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeShorts(paramarg0: ShortIterator, paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeShorts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeShorts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeShorts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File, paramarg4: ByteOrder): void;
    static storeShorts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeShorts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence, paramarg4: ByteOrder): void;
    static storeShorts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel, paramarg4: ByteOrder): void;
    static storeShorts(paramarg0: number[], paramarg1: DataOutput): void;
    static storeShorts(paramarg0: number[], paramarg1: File): void;
    static storeShorts(paramarg0: number[], paramarg1: File, paramarg2: ByteOrder): void;
    static storeShorts(paramarg0: number[], paramarg1: CharSequence): void;
    static storeShorts(paramarg0: number[], paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeShorts(paramarg0: number[], paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeShorts(paramarg0: (Object | null)[], paramarg1: DataOutput): void;
    static storeShorts(paramarg0: (Object | null)[], paramarg1: File): void;
    static storeShorts(paramarg0: (Object | null)[], paramarg1: File, paramarg2: ByteOrder): void;
    static storeShorts(paramarg0: (Object | null)[], paramarg1: CharSequence): void;
    static storeShorts(paramarg0: (Object | null)[], paramarg1: CharSequence, paramarg2: ByteOrder): void;
    static storeShorts(paramarg0: (Object | null)[], paramarg1: WritableByteChannel, paramarg2: ByteOrder): void;
    static storeShorts(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: DataOutput): void;
    static storeShorts(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeShorts(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: File, paramarg4: ByteOrder): void;
    static storeShorts(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeShorts(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: CharSequence, paramarg4: ByteOrder): void;
    static storeShorts(paramarg0: (Object | null)[], paramarg1: number, paramarg2: number, paramarg3: WritableByteChannel, paramarg4: ByteOrder): void;
    private constructor()
}