import type { Appendable } from '../../java/lang/Appendable.d.ts'
import type { StringBuilder } from '../../java/lang/StringBuilder.d.ts'
import type { BigDecimal } from '../../java/math/BigDecimal.d.ts'
import type { BigInteger } from '../../java/math/BigInteger.d.ts'
import type { MathContext } from '../../java/math/MathContext.d.ts'
import type { Comparator } from '../../java/util/Comparator.d.ts'
import type { Locale } from '../../java/util/Locale.d.ts'
import type { Pattern } from '../../java/util/regex/Pattern.d.ts'
import type { Object } from '../../java/lang/Object.d.ts'
import type { CharSequence } from '../../java/lang/CharSequence.d.ts'
import type { Pair } from '../../kotlin/Pair.d.ts'
import type { StringCompanionObject } from '../../kotlin/jvm/internal/StringCompanionObject.d.ts'
import type { CharIterator } from '../../kotlin/collections/CharIterator.d.ts'
import type { Grouping } from '../../kotlin/collections/Grouping.d.ts'
import type { IndexedValue } from '../../kotlin/collections/IndexedValue.d.ts'
import type { Random } from '../../kotlin/random/Random.d.ts'
import type { Sequence } from '../../kotlin/sequences/Sequence.d.ts'
import type { StringsKt___StringsKt } from '../../kotlin/text/StringsKt___StringsKt.d.ts'
export class StringsKt extends StringsKt___StringsKt {
    static all(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): boolean;
    static any(paramarg0: CharSequence): boolean;
    static any(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): boolean;
    static append(paramarg0: Appendable | null, paramarg1: (Object | null)[]): Appendable | null;
    static append(paramarg0: StringBuilder, paramarg1: (Object | null)[]): StringBuilder;
    static append(paramarg0: StringBuilder, paramarg1: (Object | null)[]): StringBuilder;
    static appendElement(paramarg0: Appendable, paramarg1: Object | null, paramarg2: (param0: Object) => CharSequence): void;
    static appendRange(paramarg0: Appendable | null, paramarg1: CharSequence, paramarg2: number, paramarg3: number): Appendable | null;
    static appendln(paramarg0: Appendable): Appendable;
    static appendln(paramarg0: StringBuilder): StringBuilder;
    static asIterable(paramarg0: CharSequence): string[];
    static asSequence(paramarg0: CharSequence): Sequence<string>;
    static associate(paramarg0: CharSequence, paramarg1: (param0: Object) => Pair<Object, Object>): Map<Object | null, Object | null>;
    static associateBy(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null, paramarg2: (param0: Object) => Object | null): Map<Object | null, Object | null>;
    static associateBy(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null): Map<Object | null, string>;
    static associateByTo(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object) => Object | null): Object | null;
    static associateByTo(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object) => Object | null, paramarg3: (param0: Object) => Object | null): Object | null;
    static associateTo(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object) => Pair<Object, Object>): Object | null;
    static associateWith(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null): { [key: string]: Object | null };
    static associateWithTo(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object) => Object | null): Object | null;
    static capitalize(paramarg0: string): string;
    static capitalize(paramarg0: string, paramarg1: Locale): string;
    static chunked(paramarg0: CharSequence, paramarg1: number, paramarg2: (param0: Object) => Object | null): (Object | null)[];
    static chunked(paramarg0: CharSequence, paramarg1: number): string[];
    static chunkedSequence(paramarg0: CharSequence, paramarg1: number, paramarg2: (param0: Object) => Object | null): Sequence<Object>;
    static chunkedSequence(paramarg0: CharSequence, paramarg1: number): Sequence<string>;
    static clear(paramarg0: StringBuilder): StringBuilder;
    static commonPrefixWith(paramarg0: CharSequence, paramarg1: CharSequence, paramarg2: boolean): string;
    static commonSuffixWith(paramarg0: CharSequence, paramarg1: CharSequence, paramarg2: boolean): string;
    static compareTo(paramarg0: string, paramarg1: string, paramarg2: boolean): number;
    static concatToString(paramarg0: string[]): string;
    static concatToString(paramarg0: string[], paramarg1: number, paramarg2: number): string;
    static contains(paramarg0: CharSequence, paramarg1: string, paramarg2: boolean): boolean;
    static contains(paramarg0: CharSequence, paramarg1: CharSequence, paramarg2: boolean): boolean;
    static contentEquals(paramarg0: CharSequence, paramarg1: CharSequence): boolean;
    static contentEquals(paramarg0: CharSequence, paramarg1: CharSequence, paramarg2: boolean): boolean;
    static contentEqualsIgnoreCaseImpl(paramarg0: CharSequence, paramarg1: CharSequence): boolean;
    static contentEqualsImpl(paramarg0: CharSequence, paramarg1: CharSequence): boolean;
    static count(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): number;
    static decapitalize(paramarg0: string): string;
    static decapitalize(paramarg0: string, paramarg1: Locale): string;
    static decodeToString(paramarg0: number[]): string;
    static decodeToString(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: boolean): string;
    static drop(paramarg0: CharSequence, paramarg1: number): CharSequence;
    static drop(paramarg0: string, paramarg1: number): string;
    static dropLast(paramarg0: CharSequence, paramarg1: number): CharSequence;
    static dropLast(paramarg0: string, paramarg1: number): string;
    static dropLastWhile(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): CharSequence;
    static dropLastWhile(paramarg0: string, paramarg1: (param0: Object) => boolean): string;
    static dropWhile(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): CharSequence;
    static dropWhile(paramarg0: string, paramarg1: (param0: Object) => boolean): string;
    static encodeToByteArray(paramarg0: string): number[];
    static encodeToByteArray(paramarg0: string, paramarg1: number, paramarg2: number, paramarg3: boolean): number[];
    static endsWith(paramarg0: string, paramarg1: string, paramarg2: boolean): boolean;
    static endsWith(paramarg0: CharSequence, paramarg1: string, paramarg2: boolean): boolean;
    static endsWith(paramarg0: CharSequence, paramarg1: CharSequence, paramarg2: boolean): boolean;
    static equals(paramarg0: string, paramarg1: string, paramarg2: boolean): boolean;
    static filter(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): CharSequence;
    static filter(paramarg0: string, paramarg1: (param0: Object) => boolean): string;
    static filterIndexed(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object) => boolean): CharSequence;
    static filterIndexed(paramarg0: string, paramarg1: (param0: Object, param1: Object) => boolean): string;
    static filterIndexedTo(paramarg0: CharSequence, paramarg1: Appendable | null, paramarg2: (param0: Object, param1: Object) => boolean): Appendable | null;
    static filterNot(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): CharSequence;
    static filterNot(paramarg0: string, paramarg1: (param0: Object) => boolean): string;
    static filterNotTo(paramarg0: CharSequence, paramarg1: Appendable | null, paramarg2: (param0: Object) => boolean): Appendable | null;
    static filterTo(paramarg0: CharSequence, paramarg1: Appendable | null, paramarg2: (param0: Object) => boolean): Appendable | null;
    static findAnyOf(paramarg0: CharSequence, paramarg1: string[], paramarg2: number, paramarg3: boolean): Pair<number, string>;
    static findLastAnyOf(paramarg0: CharSequence, paramarg1: string[], paramarg2: number, paramarg3: boolean): Pair<number, string>;
    static first(paramarg0: CharSequence): string;
    static first(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): string;
    static firstOrNull(paramarg0: CharSequence): string;
    static firstOrNull(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): string;
    static flatMap(paramarg0: CharSequence, paramarg1: (param0: Object) => (Object | null)[]): (Object | null)[];
    static flatMapTo(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object) => (Object | null)[]): Object | null;
    static fold(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => Object | null): Object | null;
    static foldIndexed(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object, param1: Object, param2: Object) => Object | null): Object | null;
    static foldRight(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => Object | null): Object | null;
    static foldRightIndexed(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object, param1: Object, param2: Object) => Object | null): Object | null;
    static forEach(paramarg0: CharSequence, paramarg1: (param0: Object) => void): void;
    static forEachIndexed(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object) => void): void;
    static getCASE_INSENSITIVE_ORDER(paramarg0: StringCompanionObject): (param0: Object) => boolean;
    static getIndices(paramarg0: CharSequence): { start: number; endInclusive: number; step: number };
    static getLastIndex(paramarg0: CharSequence): number;
    static getOrNull(paramarg0: CharSequence, paramarg1: number): string;
    static groupBy(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null, paramarg2: (param0: Object) => Object | null): Map<Object | null, (Object | null)[]>;
    static groupBy(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null): Map<Object | null, string[]>;
    static groupByTo(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object) => Object | null): Object | null;
    static groupByTo(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object) => Object | null, paramarg3: (param0: Object) => Object | null): Object | null;
    static groupingBy(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null): Grouping<string, Object>;
    static hasSurrogatePairAt(paramarg0: CharSequence, paramarg1: number): boolean;
    static indexOf(paramarg0: CharSequence, paramarg1: string, paramarg2: number, paramarg3: boolean): number;
    static indexOf(paramarg0: CharSequence, paramarg1: string, paramarg2: number, paramarg3: boolean): number;
    static indexOfAny(paramarg0: CharSequence, paramarg1: string[], paramarg2: number, paramarg3: boolean): number;
    static indexOfAny(paramarg0: CharSequence, paramarg1: string[], paramarg2: number, paramarg3: boolean): number;
    static indexOfFirst(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): number;
    static indexOfLast(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): number;
    static isBlank(paramarg0: CharSequence): boolean;
    static iterator(paramarg0: CharSequence): CharIterator;
    static last(paramarg0: CharSequence): string;
    static last(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): string;
    static lastIndexOf(paramarg0: CharSequence, paramarg1: string, paramarg2: number, paramarg3: boolean): number;
    static lastIndexOf(paramarg0: CharSequence, paramarg1: string, paramarg2: number, paramarg3: boolean): number;
    static lastIndexOfAny(paramarg0: CharSequence, paramarg1: string[], paramarg2: number, paramarg3: boolean): number;
    static lastIndexOfAny(paramarg0: CharSequence, paramarg1: string[], paramarg2: number, paramarg3: boolean): number;
    static lastOrNull(paramarg0: CharSequence): string;
    static lastOrNull(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): string;
    static lineSequence(paramarg0: CharSequence): Sequence<string>;
    static lines(paramarg0: CharSequence): string[];
    static map(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null): (Object | null)[];
    static mapIndexed(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static mapIndexedNotNull(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static mapIndexedNotNullTo(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => Object | null): Object | null;
    static mapIndexedTo(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => Object | null): Object | null;
    static mapNotNull(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null): (Object | null)[];
    static mapNotNullTo(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object) => Object | null): Object | null;
    static mapTo(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object) => Object | null): Object | null;
    static max(paramarg0: CharSequence): string;
    static maxBy(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null): string;
    static maxByOrNull(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null): string;
    static maxByOrThrow(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null): string;
    static maxOrNull(paramarg0: CharSequence): string;
    static maxOrThrow(paramarg0: CharSequence): string;
    static maxWith(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): string;
    static maxWithOrNull(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): string;
    static maxWithOrThrow(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): string;
    static min(paramarg0: CharSequence): string;
    static minBy(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null): string;
    static minByOrNull(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null): string;
    static minByOrThrow(paramarg0: CharSequence, paramarg1: (param0: Object) => Object | null): string;
    static minOrNull(paramarg0: CharSequence): string;
    static minOrThrow(paramarg0: CharSequence): string;
    static minWith(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): string;
    static minWithOrNull(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): string;
    static minWithOrThrow(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): string;
    static none(paramarg0: CharSequence): boolean;
    static none(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): boolean;
    static numberFormatError(paramarg0: string): void;
    static onEach(paramarg0: CharSequence | null, paramarg1: (param0: Object) => void): CharSequence | null;
    static onEachIndexed(paramarg0: CharSequence | null, paramarg1: (param0: Object, param1: Object) => void): CharSequence | null;
    static padEnd(paramarg0: CharSequence, paramarg1: number, paramarg2: string): CharSequence;
    static padEnd(paramarg0: string, paramarg1: number, paramarg2: string): string;
    static padStart(paramarg0: CharSequence, paramarg1: number, paramarg2: string): CharSequence;
    static padStart(paramarg0: string, paramarg1: number, paramarg2: string): string;
    static partition(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): Pair<CharSequence, CharSequence>;
    static partition(paramarg0: string, paramarg1: (param0: Object) => boolean): Pair<string, string>;
    static prependIndent(paramarg0: string, paramarg1: string): string;
    static random(paramarg0: CharSequence, paramarg1: Random): string;
    static randomOrNull(paramarg0: CharSequence, paramarg1: Random): string;
    static reduce(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object) => string): string;
    static reduceIndexed(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object, param2: Object) => string): string;
    static reduceIndexedOrNull(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object, param2: Object) => string): string;
    static reduceOrNull(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object) => string): string;
    static reduceRight(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object) => string): string;
    static reduceRightIndexed(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object, param2: Object) => string): string;
    static reduceRightIndexedOrNull(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object, param2: Object) => string): string;
    static reduceRightOrNull(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object) => string): string;
    static regionMatches(paramarg0: CharSequence, paramarg1: number, paramarg2: CharSequence, paramarg3: number, paramarg4: number, paramarg5: boolean): boolean;
    static regionMatches(paramarg0: string, paramarg1: number, paramarg2: string, paramarg3: number, paramarg4: number, paramarg5: boolean): boolean;
    static regionMatchesImpl(paramarg0: CharSequence, paramarg1: number, paramarg2: CharSequence, paramarg3: number, paramarg4: number, paramarg5: boolean): boolean;
    static removePrefix(paramarg0: CharSequence, paramarg1: CharSequence): CharSequence;
    static removePrefix(paramarg0: string, paramarg1: CharSequence): string;
    static removeRange(paramarg0: CharSequence, paramarg1: number, paramarg2: number): CharSequence;
    static removeRange(paramarg0: CharSequence, paramarg1: { start: number; endInclusive: number; step: number }): CharSequence;
    static removeSuffix(paramarg0: CharSequence, paramarg1: CharSequence): CharSequence;
    static removeSuffix(paramarg0: string, paramarg1: CharSequence): string;
    static removeSurrounding(paramarg0: CharSequence, paramarg1: CharSequence): CharSequence;
    static removeSurrounding(paramarg0: CharSequence, paramarg1: CharSequence, paramarg2: CharSequence): CharSequence;
    static removeSurrounding(paramarg0: string, paramarg1: CharSequence): string;
    static removeSurrounding(paramarg0: string, paramarg1: CharSequence, paramarg2: CharSequence): string;
    static repeat(paramarg0: CharSequence, paramarg1: number): string;
    static replace(paramarg0: string, paramarg1: string, paramarg2: string, paramarg3: boolean): string;
    static replace(paramarg0: string, paramarg1: string, paramarg2: string, paramarg3: boolean): string;
    static replaceAfter(paramarg0: string, paramarg1: string, paramarg2: string, paramarg3: string): string;
    static replaceAfter(paramarg0: string, paramarg1: string, paramarg2: string, paramarg3: string): string;
    static replaceAfterLast(paramarg0: string, paramarg1: string, paramarg2: string, paramarg3: string): string;
    static replaceAfterLast(paramarg0: string, paramarg1: string, paramarg2: string, paramarg3: string): string;
    static replaceBefore(paramarg0: string, paramarg1: string, paramarg2: string, paramarg3: string): string;
    static replaceBefore(paramarg0: string, paramarg1: string, paramarg2: string, paramarg3: string): string;
    static replaceBeforeLast(paramarg0: string, paramarg1: string, paramarg2: string, paramarg3: string): string;
    static replaceBeforeLast(paramarg0: string, paramarg1: string, paramarg2: string, paramarg3: string): string;
    static replaceFirst(paramarg0: string, paramarg1: string, paramarg2: string, paramarg3: boolean): string;
    static replaceFirst(paramarg0: string, paramarg1: string, paramarg2: string, paramarg3: boolean): string;
    static replaceIndent(paramarg0: string, paramarg1: string): string;
    static replaceIndentByMargin(paramarg0: string, paramarg1: string, paramarg2: string): string;
    static replaceRange(paramarg0: CharSequence, paramarg1: number, paramarg2: number, paramarg3: CharSequence): CharSequence;
    static replaceRange(paramarg0: CharSequence, paramarg1: { start: number; endInclusive: number; step: number }, paramarg2: CharSequence): CharSequence;
    static requireNonNegativeLimit(paramarg0: number): void;
    static reversed(paramarg0: CharSequence): CharSequence;
    static runningFold(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static runningFoldIndexed(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object, param1: Object, param2: Object) => Object | null): (Object | null)[];
    static runningReduce(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object) => string): string[];
    static runningReduceIndexed(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object, param2: Object) => string): string[];
    static scan(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static scanIndexed(paramarg0: CharSequence, paramarg1: Object | null, paramarg2: (param0: Object, param1: Object, param2: Object) => Object | null): (Object | null)[];
    static single(paramarg0: CharSequence): string;
    static single(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): string;
    static singleOrNull(paramarg0: CharSequence): string;
    static singleOrNull(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): string;
    static skipWhile(paramarg0: string, paramarg1: number, paramarg2: (param0: Object) => boolean): number;
    static slice(paramarg0: CharSequence, paramarg1: number[]): CharSequence;
    static slice(paramarg0: CharSequence, paramarg1: { start: number; endInclusive: number; step: number }): CharSequence;
    static slice(paramarg0: string, paramarg1: { start: number; endInclusive: number; step: number }): string;
    static split(paramarg0: CharSequence, paramarg1: Pattern, paramarg2: number): string[];
    static split(paramarg0: CharSequence, paramarg1: string[], paramarg2: boolean, paramarg3: number): string[];
    static split(paramarg0: CharSequence, paramarg1: (Object | null)[], paramarg2: boolean, paramarg3: number): string[];
    static splitToSequence(paramarg0: CharSequence, paramarg1: string[], paramarg2: boolean, paramarg3: number): Sequence<string>;
    static splitToSequence(paramarg0: CharSequence, paramarg1: (Object | null)[], paramarg2: boolean, paramarg3: number): Sequence<string>;
    static startsWith(paramarg0: string, paramarg1: string, paramarg2: boolean): boolean;
    static startsWith(paramarg0: string, paramarg1: string, paramarg2: number, paramarg3: boolean): boolean;
    static startsWith(paramarg0: CharSequence, paramarg1: string, paramarg2: boolean): boolean;
    static startsWith(paramarg0: CharSequence, paramarg1: CharSequence, paramarg2: boolean): boolean;
    static startsWith(paramarg0: CharSequence, paramarg1: CharSequence, paramarg2: number, paramarg3: boolean): boolean;
    static subSequence(paramarg0: CharSequence, paramarg1: { start: number; endInclusive: number; step: number }): CharSequence;
    static substring(paramarg0: CharSequence, paramarg1: { start: number; endInclusive: number; step: number }): string;
    static substring(paramarg0: string, paramarg1: { start: number; endInclusive: number; step: number }): string;
    static substringAfter(paramarg0: string, paramarg1: string, paramarg2: string): string;
    static substringAfter(paramarg0: string, paramarg1: string, paramarg2: string): string;
    static substringAfterLast(paramarg0: string, paramarg1: string, paramarg2: string): string;
    static substringAfterLast(paramarg0: string, paramarg1: string, paramarg2: string): string;
    static substringBefore(paramarg0: string, paramarg1: string, paramarg2: string): string;
    static substringBefore(paramarg0: string, paramarg1: string, paramarg2: string): string;
    static substringBeforeLast(paramarg0: string, paramarg1: string, paramarg2: string): string;
    static substringBeforeLast(paramarg0: string, paramarg1: string, paramarg2: string): string;
    static sumBy(paramarg0: CharSequence, paramarg1: (param0: Object) => number): number;
    static sumByDouble(paramarg0: CharSequence, paramarg1: (param0: Object) => number): number;
    static take(paramarg0: CharSequence, paramarg1: number): CharSequence;
    static take(paramarg0: string, paramarg1: number): string;
    static takeLast(paramarg0: CharSequence, paramarg1: number): CharSequence;
    static takeLast(paramarg0: string, paramarg1: number): string;
    static takeLastWhile(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): CharSequence;
    static takeLastWhile(paramarg0: string, paramarg1: (param0: Object) => boolean): string;
    static takeWhile(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): CharSequence;
    static takeWhile(paramarg0: string, paramarg1: (param0: Object) => boolean): string;
    static toBigDecimalOrNull(paramarg0: string): BigDecimal;
    static toBigDecimalOrNull(paramarg0: string, paramarg1: MathContext): BigDecimal;
    static toBigIntegerOrNull(paramarg0: string): BigInteger;
    static toBigIntegerOrNull(paramarg0: string, paramarg1: number): BigInteger;
    static toBooleanStrict(paramarg0: string): boolean;
    static toBooleanStrictOrNull(paramarg0: string): boolean;
    static toByteOrNull(paramarg0: string): number;
    static toByteOrNull(paramarg0: string, paramarg1: number): number;
    static toCharArray(paramarg0: string, paramarg1: number, paramarg2: number): string[];
    static toCollection(paramarg0: CharSequence, paramarg1: Object | null): Object | null;
    static toDoubleOrNull(paramarg0: string): number;
    static toFloatOrNull(paramarg0: string): number;
    static toHashSet(paramarg0: CharSequence): string[];
    static toIntOrNull(paramarg0: string): number;
    static toIntOrNull(paramarg0: string, paramarg1: number): number;
    static toList(paramarg0: CharSequence): string[];
    static toLongOrNull(paramarg0: string): number;
    static toLongOrNull(paramarg0: string, paramarg1: number): number;
    static toMutableList(paramarg0: CharSequence): string[];
    static toSet(paramarg0: CharSequence): string[];
    static toShortOrNull(paramarg0: string): number;
    static toShortOrNull(paramarg0: string, paramarg1: number): number;
    static toSortedSet(paramarg0: CharSequence): string[];
    static trim(paramarg0: CharSequence): CharSequence;
    static trim(paramarg0: CharSequence, paramarg1: string[]): CharSequence;
    static trim(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): CharSequence;
    static trim(paramarg0: string, paramarg1: string[]): string;
    static trim(paramarg0: string, paramarg1: (param0: Object) => boolean): string;
    static trimEnd(paramarg0: CharSequence): CharSequence;
    static trimEnd(paramarg0: CharSequence, paramarg1: string[]): CharSequence;
    static trimEnd(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): CharSequence;
    static trimEnd(paramarg0: string, paramarg1: string[]): string;
    static trimEnd(paramarg0: string, paramarg1: (param0: Object) => boolean): string;
    static trimIndent(paramarg0: string): string;
    static trimMargin(paramarg0: string, paramarg1: string): string;
    static trimStart(paramarg0: CharSequence): CharSequence;
    static trimStart(paramarg0: CharSequence, paramarg1: string[]): CharSequence;
    static trimStart(paramarg0: CharSequence, paramarg1: (param0: Object) => boolean): CharSequence;
    static trimStart(paramarg0: string, paramarg1: string[]): string;
    static trimStart(paramarg0: string, paramarg1: (param0: Object) => boolean): string;
    static windowed(paramarg0: CharSequence, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: (param0: Object) => Object | null): (Object | null)[];
    static windowed(paramarg0: CharSequence, paramarg1: number, paramarg2: number, paramarg3: boolean): string[];
    static windowedSequence(paramarg0: CharSequence, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: (param0: Object) => Object | null): Sequence<Object>;
    static windowedSequence(paramarg0: CharSequence, paramarg1: number, paramarg2: number, paramarg3: boolean): Sequence<string>;
    static withIndex(paramarg0: CharSequence): IndexedValue<string>[];
    static zip(paramarg0: CharSequence, paramarg1: CharSequence, paramarg2: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static zip(paramarg0: CharSequence, paramarg1: CharSequence): Pair<string, string>[];
    static zipWithNext(paramarg0: CharSequence, paramarg1: (param0: Object, param1: Object) => Object | null): (Object | null)[];
    static zipWithNext(paramarg0: CharSequence): Pair<string, string>[];
}