import type { ToggleableValueGroup } from '../../../../../net/ccbluex/liquidbounce/config/types/group/ToggleableValueGroup.d.ts'
/**
 * "Spoofs" the fingerprint of the client
 * that can be generated by the server using Server Resource Packs.
 *
 * More details about this can be read here: https://alaggydev.github.io/posts/cytooxien/
 *
 * To combat this, we simply use a new cache directory for each UUID that we use.
 *
 * Source: {@link https://github.com/CCBlueX/LiquidBounce/blob/b7cc679e71b1bc95d19a1e1535f79a1c2164149e/src/main/kotlin/net/ccbluex/liquidbounce/features/spoofer/SpooferFingerprint.kt#L31 | src/main/kotlin/net/ccbluex/liquidbounce/features/spoofer/SpooferFingerprint.kt:31}
 */
export class SpooferFingerprint extends ToggleableValueGroup {
    static INSTANCE: SpooferFingerprint;
}