import type { LongBuffer } from '../../../java/nio/LongBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
export class ARBGPUShaderInt64 extends Object {
    static GL_INT64_ARB: number;
    static GL_INT64_VEC2_ARB: number;
    static GL_INT64_VEC3_ARB: number;
    static GL_INT64_VEC4_ARB: number;
    static GL_UNSIGNED_INT64_ARB: number;
    static GL_UNSIGNED_INT64_VEC2_ARB: number;
    static GL_UNSIGNED_INT64_VEC3_ARB: number;
    static GL_UNSIGNED_INT64_VEC4_ARB: number;
    static glGetUniformi64vARB(paramarg0: number, paramarg1: number): number;
    static glGetUniformi64vARB(paramarg0: number, paramarg1: number, paramarg2: LongBuffer): void;
    static glGetUniformi64vARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetUniformui64vARB(paramarg0: number, paramarg1: number): number;
    static glGetUniformui64vARB(paramarg0: number, paramarg1: number, paramarg2: LongBuffer): void;
    static glGetUniformui64vARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetnUniformi64vARB(paramarg0: number, paramarg1: number): number;
    static glGetnUniformi64vARB(paramarg0: number, paramarg1: number, paramarg2: LongBuffer): void;
    static glGetnUniformi64vARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetnUniformui64vARB(paramarg0: number, paramarg1: number): number;
    static glGetnUniformui64vARB(paramarg0: number, paramarg1: number, paramarg2: LongBuffer): void;
    static glGetnUniformui64vARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform1i64ARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glProgramUniform1i64vARB(paramarg0: number, paramarg1: number, paramarg2: LongBuffer): void;
    static glProgramUniform1i64vARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform1ui64ARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glProgramUniform1ui64vARB(paramarg0: number, paramarg1: number, paramarg2: LongBuffer): void;
    static glProgramUniform1ui64vARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform2i64ARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glProgramUniform2i64vARB(paramarg0: number, paramarg1: number, paramarg2: LongBuffer): void;
    static glProgramUniform2i64vARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform2ui64ARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glProgramUniform2ui64vARB(paramarg0: number, paramarg1: number, paramarg2: LongBuffer): void;
    static glProgramUniform2ui64vARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform3i64ARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glProgramUniform3i64vARB(paramarg0: number, paramarg1: number, paramarg2: LongBuffer): void;
    static glProgramUniform3i64vARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform3ui64ARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glProgramUniform3ui64vARB(paramarg0: number, paramarg1: number, paramarg2: LongBuffer): void;
    static glProgramUniform3ui64vARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform4i64ARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glProgramUniform4i64vARB(paramarg0: number, paramarg1: number, paramarg2: LongBuffer): void;
    static glProgramUniform4i64vARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glProgramUniform4ui64ARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static glProgramUniform4ui64vARB(paramarg0: number, paramarg1: number, paramarg2: LongBuffer): void;
    static glProgramUniform4ui64vARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glUniform1i64ARB(paramarg0: number, paramarg1: number): void;
    static glUniform1i64vARB(paramarg0: number, paramarg1: LongBuffer): void;
    static glUniform1i64vARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform1ui64ARB(paramarg0: number, paramarg1: number): void;
    static glUniform1ui64vARB(paramarg0: number, paramarg1: LongBuffer): void;
    static glUniform1ui64vARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform2i64ARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glUniform2i64vARB(paramarg0: number, paramarg1: LongBuffer): void;
    static glUniform2i64vARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform2ui64ARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glUniform2ui64vARB(paramarg0: number, paramarg1: LongBuffer): void;
    static glUniform2ui64vARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform3i64ARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glUniform3i64vARB(paramarg0: number, paramarg1: LongBuffer): void;
    static glUniform3i64vARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform3ui64ARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glUniform3ui64vARB(paramarg0: number, paramarg1: LongBuffer): void;
    static glUniform3ui64vARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform4i64ARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glUniform4i64vARB(paramarg0: number, paramarg1: LongBuffer): void;
    static glUniform4i64vARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform4ui64ARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glUniform4ui64vARB(paramarg0: number, paramarg1: LongBuffer): void;
    static glUniform4ui64vARB(paramarg0: number, paramarg1: number[]): void;
    static nglGetUniformi64vARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetUniformui64vARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetnUniformi64vARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetnUniformui64vARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform1i64vARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform1ui64vARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform2i64vARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform2ui64vARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform3i64vARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform3ui64vARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform4i64vARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglProgramUniform4ui64vARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglUniform1i64vARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform1ui64vARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform2i64vARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform2ui64vARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform3i64vARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform3ui64vARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform4i64vARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform4ui64vARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    constructor()
}