import type { DoubleBuffer } from '../../../java/nio/DoubleBuffer.d.ts'
import type { FloatBuffer } from '../../../java/nio/FloatBuffer.d.ts'
import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { ShortBuffer } from '../../../java/nio/ShortBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
export class ARBMultitexture extends Object {
    static GL_ACTIVE_TEXTURE_ARB: number;
    static GL_CLIENT_ACTIVE_TEXTURE_ARB: number;
    static GL_MAX_TEXTURE_UNITS_ARB: number;
    static GL_TEXTURE0_ARB: number;
    static GL_TEXTURE10_ARB: number;
    static GL_TEXTURE11_ARB: number;
    static GL_TEXTURE12_ARB: number;
    static GL_TEXTURE13_ARB: number;
    static GL_TEXTURE14_ARB: number;
    static GL_TEXTURE15_ARB: number;
    static GL_TEXTURE16_ARB: number;
    static GL_TEXTURE17_ARB: number;
    static GL_TEXTURE18_ARB: number;
    static GL_TEXTURE19_ARB: number;
    static GL_TEXTURE1_ARB: number;
    static GL_TEXTURE20_ARB: number;
    static GL_TEXTURE21_ARB: number;
    static GL_TEXTURE22_ARB: number;
    static GL_TEXTURE23_ARB: number;
    static GL_TEXTURE24_ARB: number;
    static GL_TEXTURE25_ARB: number;
    static GL_TEXTURE26_ARB: number;
    static GL_TEXTURE27_ARB: number;
    static GL_TEXTURE28_ARB: number;
    static GL_TEXTURE29_ARB: number;
    static GL_TEXTURE2_ARB: number;
    static GL_TEXTURE30_ARB: number;
    static GL_TEXTURE31_ARB: number;
    static GL_TEXTURE3_ARB: number;
    static GL_TEXTURE4_ARB: number;
    static GL_TEXTURE5_ARB: number;
    static GL_TEXTURE6_ARB: number;
    static GL_TEXTURE7_ARB: number;
    static GL_TEXTURE8_ARB: number;
    static GL_TEXTURE9_ARB: number;
    static glActiveTextureARB(paramarg0: number): void;
    static glClientActiveTextureARB(paramarg0: number): void;
    static glMultiTexCoord1dARB(paramarg0: number, paramarg1: number): void;
    static glMultiTexCoord1dvARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord1dvARB(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glMultiTexCoord1fARB(paramarg0: number, paramarg1: number): void;
    static glMultiTexCoord1fvARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord1fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glMultiTexCoord1iARB(paramarg0: number, paramarg1: number): void;
    static glMultiTexCoord1ivARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord1ivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glMultiTexCoord1sARB(paramarg0: number, paramarg1: number): void;
    static glMultiTexCoord1svARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glMultiTexCoord1svARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord2dARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glMultiTexCoord2dvARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord2dvARB(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glMultiTexCoord2fARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glMultiTexCoord2fvARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord2fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glMultiTexCoord2iARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glMultiTexCoord2ivARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord2ivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glMultiTexCoord2sARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glMultiTexCoord2svARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glMultiTexCoord2svARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord3dARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexCoord3dvARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord3dvARB(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glMultiTexCoord3fARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexCoord3fvARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord3fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glMultiTexCoord3iARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexCoord3ivARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord3ivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glMultiTexCoord3sARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexCoord3svARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glMultiTexCoord3svARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord4dARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glMultiTexCoord4dvARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord4dvARB(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glMultiTexCoord4fARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glMultiTexCoord4fvARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord4fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glMultiTexCoord4iARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glMultiTexCoord4ivARB(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord4ivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glMultiTexCoord4sARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glMultiTexCoord4svARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glMultiTexCoord4svARB(paramarg0: number, paramarg1: number[]): void;
    static nglMultiTexCoord1dvARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord1fvARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord1ivARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord1svARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord2dvARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord2fvARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord2ivARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord2svARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord3dvARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord3fvARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord3ivARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord3svARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord4dvARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord4fvARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord4ivARB(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord4svARB(paramarg0: number, paramarg1: number): void;
    constructor()
}