import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { FloatBuffer } from '../../../java/nio/FloatBuffer.d.ts'
import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../java/lang/CharSequence.d.ts'
import type { PointerBuffer } from '../../../org/lwjgl/PointerBuffer.d.ts'
export class ARBShaderObjects extends Object {
    static GL_BOOL_ARB: number;
    static GL_BOOL_VEC2_ARB: number;
    static GL_BOOL_VEC3_ARB: number;
    static GL_BOOL_VEC4_ARB: number;
    static GL_FLOAT_MAT2_ARB: number;
    static GL_FLOAT_MAT3_ARB: number;
    static GL_FLOAT_MAT4_ARB: number;
    static GL_FLOAT_VEC2_ARB: number;
    static GL_FLOAT_VEC3_ARB: number;
    static GL_FLOAT_VEC4_ARB: number;
    static GL_INT_VEC2_ARB: number;
    static GL_INT_VEC3_ARB: number;
    static GL_INT_VEC4_ARB: number;
    static GL_OBJECT_ACTIVE_UNIFORMS_ARB: number;
    static GL_OBJECT_ACTIVE_UNIFORM_MAX_LENGTH_ARB: number;
    static GL_OBJECT_ATTACHED_OBJECTS_ARB: number;
    static GL_OBJECT_COMPILE_STATUS_ARB: number;
    static GL_OBJECT_DELETE_STATUS_ARB: number;
    static GL_OBJECT_INFO_LOG_LENGTH_ARB: number;
    static GL_OBJECT_LINK_STATUS_ARB: number;
    static GL_OBJECT_SHADER_SOURCE_LENGTH_ARB: number;
    static GL_OBJECT_SUBTYPE_ARB: number;
    static GL_OBJECT_TYPE_ARB: number;
    static GL_OBJECT_VALIDATE_STATUS_ARB: number;
    static GL_PROGRAM_OBJECT_ARB: number;
    static GL_SAMPLER_1D_ARB: number;
    static GL_SAMPLER_1D_SHADOW_ARB: number;
    static GL_SAMPLER_2D_ARB: number;
    static GL_SAMPLER_2D_RECT_ARB: number;
    static GL_SAMPLER_2D_RECT_SHADOW_ARB: number;
    static GL_SAMPLER_2D_SHADOW_ARB: number;
    static GL_SAMPLER_3D_ARB: number;
    static GL_SAMPLER_CUBE_ARB: number;
    static GL_SHADER_OBJECT_ARB: number;
    static glAttachObjectARB(paramarg0: number, paramarg1: number): void;
    static glCompileShaderARB(paramarg0: number): void;
    static glCreateProgramObjectARB(): number;
    static glCreateShaderObjectARB(paramarg0: number): number;
    static glDeleteObjectARB(paramarg0: number): void;
    static glDetachObjectARB(paramarg0: number, paramarg1: number): void;
    static glGetActiveUniformARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer, paramarg4: IntBuffer): string;
    static glGetActiveUniformARB(paramarg0: number, paramarg1: number, paramarg2: IntBuffer, paramarg3: IntBuffer): string;
    static glGetActiveUniformARB(paramarg0: number, paramarg1: number, paramarg2: number[], paramarg3: number[], paramarg4: number[], paramarg5: ByteBuffer): void;
    static glGetActiveUniformARB(paramarg0: number, paramarg1: number, paramarg2: IntBuffer, paramarg3: IntBuffer, paramarg4: IntBuffer, paramarg5: ByteBuffer): void;
    static glGetAttachedObjectsARB(paramarg0: number, paramarg1: number[], paramarg2: number[]): void;
    static glGetAttachedObjectsARB(paramarg0: number, paramarg1: IntBuffer, paramarg2: IntBuffer): void;
    static glGetHandleARB(paramarg0: number): number;
    static glGetInfoLogARB(paramarg0: number): string;
    static glGetInfoLogARB(paramarg0: number, paramarg1: number): string;
    static glGetInfoLogARB(paramarg0: number, paramarg1: number[], paramarg2: ByteBuffer): void;
    static glGetInfoLogARB(paramarg0: number, paramarg1: IntBuffer, paramarg2: ByteBuffer): void;
    static glGetObjectParameterfvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetObjectParameterfvARB(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetObjectParameteriARB(paramarg0: number, paramarg1: number): number;
    static glGetObjectParameterivARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetObjectParameterivARB(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetShaderSourceARB(paramarg0: number): string;
    static glGetShaderSourceARB(paramarg0: number, paramarg1: number): string;
    static glGetShaderSourceARB(paramarg0: number, paramarg1: number[], paramarg2: ByteBuffer): void;
    static glGetShaderSourceARB(paramarg0: number, paramarg1: IntBuffer, paramarg2: ByteBuffer): void;
    static glGetUniformLocationARB(paramarg0: number, paramarg1: CharSequence): number;
    static glGetUniformLocationARB(paramarg0: number, paramarg1: ByteBuffer): number;
    static glGetUniformfARB(paramarg0: number, paramarg1: number): number;
    static glGetUniformfvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetUniformfvARB(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetUniformiARB(paramarg0: number, paramarg1: number): number;
    static glGetUniformivARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetUniformivARB(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glLinkProgramARB(paramarg0: number): void;
    static glShaderSourceARB(paramarg0: number, paramarg1: CharSequence): void;
    static glShaderSourceARB(paramarg0: number, paramarg1: (Object | null)[]): void;
    static glShaderSourceARB(paramarg0: number, paramarg1: PointerBuffer, paramarg2: number[]): void;
    static glShaderSourceARB(paramarg0: number, paramarg1: PointerBuffer, paramarg2: IntBuffer): void;
    static glUniform1fARB(paramarg0: number, paramarg1: number): void;
    static glUniform1fvARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform1fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glUniform1iARB(paramarg0: number, paramarg1: number): void;
    static glUniform1ivARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform1ivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glUniform2fARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glUniform2fvARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform2fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glUniform2iARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glUniform2ivARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform2ivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glUniform3fARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glUniform3fvARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform3fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glUniform3iARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glUniform3ivARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform3ivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glUniform4fARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glUniform4fvARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform4fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glUniform4iARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glUniform4ivARB(paramarg0: number, paramarg1: number[]): void;
    static glUniform4ivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glUniformMatrix2fvARB(paramarg0: number, paramarg1: boolean, paramarg2: number[]): void;
    static glUniformMatrix2fvARB(paramarg0: number, paramarg1: boolean, paramarg2: FloatBuffer): void;
    static glUniformMatrix3fvARB(paramarg0: number, paramarg1: boolean, paramarg2: number[]): void;
    static glUniformMatrix3fvARB(paramarg0: number, paramarg1: boolean, paramarg2: FloatBuffer): void;
    static glUniformMatrix4fvARB(paramarg0: number, paramarg1: boolean, paramarg2: number[]): void;
    static glUniformMatrix4fvARB(paramarg0: number, paramarg1: boolean, paramarg2: FloatBuffer): void;
    static glUseProgramObjectARB(paramarg0: number): void;
    static glValidateProgramARB(paramarg0: number): void;
    static nglGetActiveUniformARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nglGetAttachedObjectsARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetInfoLogARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetObjectParameterfvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetObjectParameterivARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetShaderSourceARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglGetUniformLocationARB(paramarg0: number, paramarg1: number): number;
    static nglGetUniformfvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetUniformivARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglShaderSourceARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglUniform1fvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform1ivARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform2fvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform2ivARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform3fvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform3ivARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform4fvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniform4ivARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglUniformMatrix2fvARB(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number): void;
    static nglUniformMatrix3fvARB(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number): void;
    static nglUniformMatrix4fvARB(paramarg0: number, paramarg1: number, paramarg2: boolean, paramarg3: number): void;
    constructor()
}