import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { DoubleBuffer } from '../../../java/nio/DoubleBuffer.d.ts'
import type { FloatBuffer } from '../../../java/nio/FloatBuffer.d.ts'
import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { ShortBuffer } from '../../../java/nio/ShortBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../java/lang/CharSequence.d.ts'
import type { PointerBuffer } from '../../../org/lwjgl/PointerBuffer.d.ts'
export class ARBVertexShader extends Object {
    static GL_CURRENT_VERTEX_ATTRIB_ARB: number;
    static GL_FLOAT_MAT2_ARB: number;
    static GL_FLOAT_MAT3_ARB: number;
    static GL_FLOAT_MAT4_ARB: number;
    static GL_FLOAT_VEC2_ARB: number;
    static GL_FLOAT_VEC3_ARB: number;
    static GL_FLOAT_VEC4_ARB: number;
    static GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS_ARB: number;
    static GL_MAX_TEXTURE_COORDS_ARB: number;
    static GL_MAX_TEXTURE_IMAGE_UNITS_ARB: number;
    static GL_MAX_VARYING_FLOATS_ARB: number;
    static GL_MAX_VERTEX_ATTRIBS_ARB: number;
    static GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS_ARB: number;
    static GL_MAX_VERTEX_UNIFORM_COMPONENTS_ARB: number;
    static GL_OBJECT_ACTIVE_ATTRIBUTES_ARB: number;
    static GL_OBJECT_ACTIVE_ATTRIBUTE_MAX_LENGTH_ARB: number;
    static GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB: number;
    static GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB: number;
    static GL_VERTEX_ATTRIB_ARRAY_POINTER_ARB: number;
    static GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB: number;
    static GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB: number;
    static GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB: number;
    static GL_VERTEX_PROGRAM_POINT_SIZE_ARB: number;
    static GL_VERTEX_PROGRAM_TWO_SIDE_ARB: number;
    static GL_VERTEX_SHADER_ARB: number;
    static glBindAttribLocationARB(paramarg0: number, paramarg1: number, paramarg2: CharSequence): void;
    static glBindAttribLocationARB(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer): void;
    static glDisableVertexAttribArrayARB(paramarg0: number): void;
    static glEnableVertexAttribArrayARB(paramarg0: number): void;
    static glGetActiveAttribARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer, paramarg4: IntBuffer): string;
    static glGetActiveAttribARB(paramarg0: number, paramarg1: number, paramarg2: IntBuffer, paramarg3: IntBuffer): string;
    static glGetActiveAttribARB(paramarg0: number, paramarg1: number, paramarg2: number[], paramarg3: number[], paramarg4: number[], paramarg5: ByteBuffer): void;
    static glGetActiveAttribARB(paramarg0: number, paramarg1: number, paramarg2: IntBuffer, paramarg3: IntBuffer, paramarg4: IntBuffer, paramarg5: ByteBuffer): void;
    static glGetAttribLocationARB(paramarg0: number, paramarg1: CharSequence): number;
    static glGetAttribLocationARB(paramarg0: number, paramarg1: ByteBuffer): number;
    static glGetVertexAttribPointerARB(paramarg0: number, paramarg1: number): number;
    static glGetVertexAttribPointervARB(paramarg0: number, paramarg1: number, paramarg2: PointerBuffer): void;
    static glGetVertexAttribdvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetVertexAttribdvARB(paramarg0: number, paramarg1: number, paramarg2: DoubleBuffer): void;
    static glGetVertexAttribfvARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetVertexAttribfvARB(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetVertexAttribiARB(paramarg0: number, paramarg1: number): number;
    static glGetVertexAttribivARB(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetVertexAttribivARB(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glVertexAttrib1dARB(paramarg0: number, paramarg1: number): void;
    static glVertexAttrib1dvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib1dvARB(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glVertexAttrib1fARB(paramarg0: number, paramarg1: number): void;
    static glVertexAttrib1fvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib1fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glVertexAttrib1sARB(paramarg0: number, paramarg1: number): void;
    static glVertexAttrib1svARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib1svARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib2dARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glVertexAttrib2dvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib2dvARB(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glVertexAttrib2fARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glVertexAttrib2fvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib2fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glVertexAttrib2sARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glVertexAttrib2svARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib2svARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib3dARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glVertexAttrib3dvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib3dvARB(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glVertexAttrib3fARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glVertexAttrib3fvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib3fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glVertexAttrib3sARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glVertexAttrib3svARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib3svARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4NbvARB(paramarg0: number, paramarg1: ByteBuffer): void;
    static glVertexAttrib4NivARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4NivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glVertexAttrib4NsvARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib4NsvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4NubARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glVertexAttrib4NubvARB(paramarg0: number, paramarg1: ByteBuffer): void;
    static glVertexAttrib4NuivARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4NuivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glVertexAttrib4NusvARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib4NusvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4bvARB(paramarg0: number, paramarg1: ByteBuffer): void;
    static glVertexAttrib4dARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glVertexAttrib4dvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4dvARB(paramarg0: number, paramarg1: DoubleBuffer): void;
    static glVertexAttrib4fARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glVertexAttrib4fvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4fvARB(paramarg0: number, paramarg1: FloatBuffer): void;
    static glVertexAttrib4ivARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4ivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glVertexAttrib4sARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glVertexAttrib4svARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib4svARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4ubvARB(paramarg0: number, paramarg1: ByteBuffer): void;
    static glVertexAttrib4uivARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4uivARB(paramarg0: number, paramarg1: IntBuffer): void;
    static glVertexAttrib4usvARB(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib4usvARB(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: number[]): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: number[]): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: ByteBuffer): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: FloatBuffer): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: IntBuffer): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: ShortBuffer): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: number): void;
    static glVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: number[]): void;
    static nglBindAttribLocationARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetActiveAttribARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nglGetAttribLocationARB(paramarg0: number, paramarg1: number): number;
    static nglGetVertexAttribPointervARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetVertexAttribdvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetVertexAttribfvARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetVertexAttribivARB(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglVertexAttrib1dvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib1fvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib1svARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib2dvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib2fvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib2svARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib3dvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib3fvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib3svARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4NbvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4NivARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4NsvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4NubvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4NuivARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4NusvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4bvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4dvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4fvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4ivARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4svARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4ubvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4uivARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4usvARB(paramarg0: number, paramarg1: number): void;
    static nglVertexAttribPointerARB(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: number): void;
    constructor()
}