import type { Object } from '../../../java/lang/Object.d.ts'
export class EXTMeshShader extends Object {
    static GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_MESH_SHADER_EXT: number;
    static GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TASK_SHADER_EXT: number;
    static GL_MAX_COMBINED_MESH_UNIFORM_COMPONENTS_EXT: number;
    static GL_MAX_COMBINED_TASK_UNIFORM_COMPONENTS_EXT: number;
    static GL_MAX_MESH_ATOMIC_COUNTERS_EXT: number;
    static GL_MAX_MESH_ATOMIC_COUNTER_BUFFERS_EXT: number;
    static GL_MAX_MESH_IMAGE_UNIFORMS_EXT: number;
    static GL_MAX_MESH_MULTIVIEW_VIEW_COUNT_EXT: number;
    static GL_MAX_MESH_OUTPUT_COMPONENTS_EXT: number;
    static GL_MAX_MESH_OUTPUT_LAYERS_EXT: number;
    static GL_MAX_MESH_OUTPUT_MEMORY_SIZE_EXT: number;
    static GL_MAX_MESH_OUTPUT_PRIMITIVES_EXT: number;
    static GL_MAX_MESH_OUTPUT_VERTICES_EXT: number;
    static GL_MAX_MESH_PAYLOAD_AND_OUTPUT_MEMORY_SIZE_EXT: number;
    static GL_MAX_MESH_PAYLOAD_AND_SHARED_MEMORY_SIZE_EXT: number;
    static GL_MAX_MESH_SHADER_STORAGE_BLOCKS_EXT: number;
    static GL_MAX_MESH_SHARED_MEMORY_SIZE_EXT: number;
    static GL_MAX_MESH_TEXTURE_IMAGE_UNITS_EXT: number;
    static GL_MAX_MESH_UNIFORM_BLOCKS_EXT: number;
    static GL_MAX_MESH_UNIFORM_COMPONENTS_EXT: number;
    static GL_MAX_MESH_WORK_GROUP_COUNT_EXT: number;
    static GL_MAX_MESH_WORK_GROUP_INVOCATIONS_EXT: number;
    static GL_MAX_MESH_WORK_GROUP_SIZE_EXT: number;
    static GL_MAX_MESH_WORK_GROUP_TOTAL_COUNT_EXT: number;
    static GL_MAX_PREFERRED_MESH_WORK_GROUP_INVOCATIONS_EXT: number;
    static GL_MAX_PREFERRED_TASK_WORK_GROUP_INVOCATIONS_EXT: number;
    static GL_MAX_TASK_ATOMIC_COUNTERS_EXT: number;
    static GL_MAX_TASK_ATOMIC_COUNTER_BUFFERS_EXT: number;
    static GL_MAX_TASK_IMAGE_UNIFORMS_EXT: number;
    static GL_MAX_TASK_PAYLOAD_AND_SHARED_MEMORY_SIZE_EXT: number;
    static GL_MAX_TASK_PAYLOAD_SIZE_EXT: number;
    static GL_MAX_TASK_SHADER_STORAGE_BLOCKS_EXT: number;
    static GL_MAX_TASK_SHARED_MEMORY_SIZE_EXT: number;
    static GL_MAX_TASK_TEXTURE_IMAGE_UNITS_EXT: number;
    static GL_MAX_TASK_UNIFORM_BLOCKS_EXT: number;
    static GL_MAX_TASK_UNIFORM_COMPONENTS_EXT: number;
    static GL_MAX_TASK_WORK_GROUP_COUNT_EXT: number;
    static GL_MAX_TASK_WORK_GROUP_INVOCATIONS_EXT: number;
    static GL_MAX_TASK_WORK_GROUP_SIZE_EXT: number;
    static GL_MAX_TASK_WORK_GROUP_TOTAL_COUNT_EXT: number;
    static GL_MESH_OUTPUT_PER_PRIMITIVE_GRANULARITY_EXT: number;
    static GL_MESH_OUTPUT_PER_VERTEX_GRANULARITY_EXT: number;
    static GL_MESH_OUTPUT_TYPE_EXT: number;
    static GL_MESH_PREFERS_COMPACT_PRIMITIVE_OUTPUT_EXT: number;
    static GL_MESH_PREFERS_COMPACT_VERTEX_OUTPUT_EXT: number;
    static GL_MESH_PREFERS_LOCAL_INVOCATION_PRIMITIVE_OUTPUT_EXT: number;
    static GL_MESH_PREFERS_LOCAL_INVOCATION_VERTEX_OUTPUT_EXT: number;
    static GL_MESH_PRIMITIVES_GENERATED_EXT: number;
    static GL_MESH_PRIMITIVES_OUT_EXT: number;
    static GL_MESH_SHADER_BIT_EXT: number;
    static GL_MESH_SHADER_EXT: number;
    static GL_MESH_SHADER_INVOCATIONS_EXT: number;
    static GL_MESH_SUBROUTINE_EXT: number;
    static GL_MESH_SUBROUTINE_UNIFORM_EXT: number;
    static GL_MESH_VERTICES_OUT_EXT: number;
    static GL_MESH_WORK_GROUP_SIZE_EXT: number;
    static GL_REFERENCED_BY_MESH_SHADER_EXT: number;
    static GL_REFERENCED_BY_TASK_SHADER_EXT: number;
    static GL_TASK_SHADER_BIT_EXT: number;
    static GL_TASK_SHADER_EXT: number;
    static GL_TASK_SHADER_INVOCATIONS_EXT: number;
    static GL_TASK_SUBROUTINE_EXT: number;
    static GL_TASK_SUBROUTINE_UNIFORM_EXT: number;
    static GL_TASK_WORK_GROUP_SIZE_EXT: number;
    static GL_UNIFORM_BLOCK_REFERENCED_BY_MESH_SHADER_EXT: number;
    static GL_UNIFORM_BLOCK_REFERENCED_BY_TASK_SHADER_EXT: number;
    static glDrawMeshTasksEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glDrawMeshTasksIndirectEXT(paramarg0: number): void;
    static glMultiDrawMeshTasksIndirectCountEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiDrawMeshTasksIndirectEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    constructor()
}