import type { Object } from '../../../java/lang/Object.d.ts'
export class EXTShaderImageLoadStore extends Object {
    static GL_ALL_BARRIER_BITS_EXT: number;
    static GL_ATOMIC_COUNTER_BARRIER_BIT_EXT: number;
    static GL_BUFFER_UPDATE_BARRIER_BIT_EXT: number;
    static GL_COMMAND_BARRIER_BIT_EXT: number;
    static GL_ELEMENT_ARRAY_BARRIER_BIT_EXT: number;
    static GL_FRAMEBUFFER_BARRIER_BIT_EXT: number;
    static GL_IMAGE_1D_ARRAY_EXT: number;
    static GL_IMAGE_1D_EXT: number;
    static GL_IMAGE_2D_ARRAY_EXT: number;
    static GL_IMAGE_2D_EXT: number;
    static GL_IMAGE_2D_MULTISAMPLE_ARRAY_EXT: number;
    static GL_IMAGE_2D_MULTISAMPLE_EXT: number;
    static GL_IMAGE_2D_RECT_EXT: number;
    static GL_IMAGE_3D_EXT: number;
    static GL_IMAGE_BINDING_ACCESS_EXT: number;
    static GL_IMAGE_BINDING_FORMAT_EXT: number;
    static GL_IMAGE_BINDING_LAYERED_EXT: number;
    static GL_IMAGE_BINDING_LAYER_EXT: number;
    static GL_IMAGE_BINDING_LEVEL_EXT: number;
    static GL_IMAGE_BINDING_NAME_EXT: number;
    static GL_IMAGE_BUFFER_EXT: number;
    static GL_IMAGE_CUBE_EXT: number;
    static GL_IMAGE_CUBE_MAP_ARRAY_EXT: number;
    static GL_INT_IMAGE_1D_ARRAY_EXT: number;
    static GL_INT_IMAGE_1D_EXT: number;
    static GL_INT_IMAGE_2D_ARRAY_EXT: number;
    static GL_INT_IMAGE_2D_EXT: number;
    static GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT: number;
    static GL_INT_IMAGE_2D_MULTISAMPLE_EXT: number;
    static GL_INT_IMAGE_2D_RECT_EXT: number;
    static GL_INT_IMAGE_3D_EXT: number;
    static GL_INT_IMAGE_BUFFER_EXT: number;
    static GL_INT_IMAGE_CUBE_EXT: number;
    static GL_INT_IMAGE_CUBE_MAP_ARRAY_EXT: number;
    static GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS_EXT: number;
    static GL_MAX_IMAGE_SAMPLES_EXT: number;
    static GL_MAX_IMAGE_UNITS_EXT: number;
    static GL_PIXEL_BUFFER_BARRIER_BIT_EXT: number;
    static GL_SHADER_IMAGE_ACCESS_BARRIER_BIT_EXT: number;
    static GL_TEXTURE_FETCH_BARRIER_BIT_EXT: number;
    static GL_TEXTURE_UPDATE_BARRIER_BIT_EXT: number;
    static GL_TRANSFORM_FEEDBACK_BARRIER_BIT_EXT: number;
    static GL_UNIFORM_BARRIER_BIT_EXT: number;
    static GL_UNSIGNED_INT_IMAGE_1D_ARRAY_EXT: number;
    static GL_UNSIGNED_INT_IMAGE_1D_EXT: number;
    static GL_UNSIGNED_INT_IMAGE_2D_ARRAY_EXT: number;
    static GL_UNSIGNED_INT_IMAGE_2D_EXT: number;
    static GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT: number;
    static GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_EXT: number;
    static GL_UNSIGNED_INT_IMAGE_2D_RECT_EXT: number;
    static GL_UNSIGNED_INT_IMAGE_3D_EXT: number;
    static GL_UNSIGNED_INT_IMAGE_BUFFER_EXT: number;
    static GL_UNSIGNED_INT_IMAGE_CUBE_EXT: number;
    static GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY_EXT: number;
    static GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT_EXT: number;
    static glBindImageTextureEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: boolean, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static glMemoryBarrierEXT(paramarg0: number): void;
    constructor()
}