import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
export class EXTTextureInteger extends Object {
    static GL_ALPHA16I_EXT: number;
    static GL_ALPHA16UI_EXT: number;
    static GL_ALPHA32I_EXT: number;
    static GL_ALPHA32UI_EXT: number;
    static GL_ALPHA8I_EXT: number;
    static GL_ALPHA8UI_EXT: number;
    static GL_ALPHA_INTEGER_EXT: number;
    static GL_BGRA_INTEGER_EXT: number;
    static GL_BGR_INTEGER_EXT: number;
    static GL_BLUE_INTEGER_EXT: number;
    static GL_GREEN_INTEGER_EXT: number;
    static GL_INTENSITY16I_EXT: number;
    static GL_INTENSITY16UI_EXT: number;
    static GL_INTENSITY32I_EXT: number;
    static GL_INTENSITY32UI_EXT: number;
    static GL_INTENSITY8I_EXT: number;
    static GL_INTENSITY8UI_EXT: number;
    static GL_LUMINANCE16I_EXT: number;
    static GL_LUMINANCE16UI_EXT: number;
    static GL_LUMINANCE32I_EXT: number;
    static GL_LUMINANCE32UI_EXT: number;
    static GL_LUMINANCE8I_EXT: number;
    static GL_LUMINANCE8UI_EXT: number;
    static GL_LUMINANCE_ALPHA16I_EXT: number;
    static GL_LUMINANCE_ALPHA16UI_EXT: number;
    static GL_LUMINANCE_ALPHA32I_EXT: number;
    static GL_LUMINANCE_ALPHA32UI_EXT: number;
    static GL_LUMINANCE_ALPHA8I_EXT: number;
    static GL_LUMINANCE_ALPHA8UI_EXT: number;
    static GL_LUMINANCE_ALPHA_INTEGER_EXT: number;
    static GL_LUMINANCE_INTEGER_EXT: number;
    static GL_RED_INTEGER_EXT: number;
    static GL_RGB16I_EXT: number;
    static GL_RGB16UI_EXT: number;
    static GL_RGB32I_EXT: number;
    static GL_RGB32UI_EXT: number;
    static GL_RGB8I_EXT: number;
    static GL_RGB8UI_EXT: number;
    static GL_RGBA16I_EXT: number;
    static GL_RGBA16UI_EXT: number;
    static GL_RGBA32I_EXT: number;
    static GL_RGBA32UI_EXT: number;
    static GL_RGBA8I_EXT: number;
    static GL_RGBA8UI_EXT: number;
    static GL_RGBA_INTEGER_EXT: number;
    static GL_RGBA_INTEGER_MODE_EXT: number;
    static GL_RGB_INTEGER_EXT: number;
    static glClearColorIiEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glClearColorIuiEXT(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glGetTexParameterIiEXT(paramarg0: number, paramarg1: number): number;
    static glGetTexParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetTexParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetTexParameterIuiEXT(paramarg0: number, paramarg1: number): number;
    static glGetTexParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetTexParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glTexParameterIiEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glTexParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glTexParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glTexParameterIuiEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glTexParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glTexParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static nglGetTexParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetTexParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglTexParameterIivEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglTexParameterIuivEXT(paramarg0: number, paramarg1: number, paramarg2: number): void;
    constructor()
}