import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { GLX11 } from '../../../org/lwjgl/opengl/GLX11.d.ts'
import type { XVisualInfo } from '../../../org/lwjgl/system/linux/XVisualInfo.d.ts'
export class GLX12 extends GLX11 {
    static GLXBadContext: number;
    static GLXBadContextState: number;
    static GLXBadContextTag: number;
    static GLXBadCurrentDrawable: number;
    static GLXBadCurrentWindow: number;
    static GLXBadDrawable: number;
    static GLXBadFBConfig: number;
    static GLXBadLargeRequest: number;
    static GLXBadPbuffer: number;
    static GLXBadPixmap: number;
    static GLXBadRenderRequest: number;
    static GLXBadWindow: number;
    static GLXUnsupportedPrivateRequest: number;
    static GLX_ACCUM_ALPHA_SIZE: number;
    static GLX_ACCUM_BLUE_SIZE: number;
    static GLX_ACCUM_GREEN_SIZE: number;
    static GLX_ACCUM_RED_SIZE: number;
    static GLX_ALPHA_SIZE: number;
    static GLX_AUX_BUFFERS: number;
    static GLX_BAD_ATTRIBUTE: number;
    static GLX_BAD_CONTEXT: number;
    static GLX_BAD_ENUM: number;
    static GLX_BAD_SCREEN: number;
    static GLX_BAD_VALUE: number;
    static GLX_BAD_VISUAL: number;
    static GLX_BLUE_SIZE: number;
    static GLX_BUFFER_SIZE: number;
    static GLX_DEPTH_SIZE: number;
    static GLX_DOUBLEBUFFER: number;
    static GLX_EXTENSIONS: number;
    static GLX_GREEN_SIZE: number;
    static GLX_LEVEL: number;
    static GLX_NO_EXTENSION: number;
    static GLX_RED_SIZE: number;
    static GLX_RGBA: number;
    static GLX_STENCIL_SIZE: number;
    static GLX_STEREO: number;
    static GLX_USE_GL: number;
    static GLX_VENDOR: number;
    static GLX_VERSION: number;
    static glXChooseVisual(paramarg0: number, paramarg1: number, paramarg2: number[]): XVisualInfo;
    static glXChooseVisual(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): XVisualInfo;
    static glXCopyContext(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glXCreateContext(paramarg0: number, paramarg1: XVisualInfo, paramarg2: number, paramarg3: boolean): number;
    static glXCreateGLXPixmap(paramarg0: number, paramarg1: XVisualInfo, paramarg2: number): number;
    static glXDestroyContext(paramarg0: number, paramarg1: number): void;
    static glXDestroyGLXPixmap(paramarg0: number, paramarg1: number): void;
    static glXGetClientString(paramarg0: number, paramarg1: number): string;
    static glXGetConfig(paramarg0: number, paramarg1: XVisualInfo, paramarg2: number, paramarg3: number[]): number;
    static glXGetConfig(paramarg0: number, paramarg1: XVisualInfo, paramarg2: number, paramarg3: IntBuffer): number;
    static glXGetCurrentContext(): number;
    static glXGetCurrentDisplay(): number;
    static glXGetCurrentDrawable(): number;
    static glXIsDirect(paramarg0: number, paramarg1: number): boolean;
    static glXMakeCurrent(paramarg0: number, paramarg1: number, paramarg2: number): boolean;
    static glXQueryExtension(paramarg0: number, paramarg1: number[], paramarg2: number[]): boolean;
    static glXQueryExtension(paramarg0: number, paramarg1: IntBuffer, paramarg2: IntBuffer): boolean;
    static glXQueryExtensionsString(paramarg0: number, paramarg1: number): string;
    static glXQueryServerString(paramarg0: number, paramarg1: number, paramarg2: number): string;
    static glXQueryVersion(paramarg0: number, paramarg1: number[], paramarg2: number[]): boolean;
    static glXQueryVersion(paramarg0: number, paramarg1: IntBuffer, paramarg2: IntBuffer): boolean;
    static glXSwapBuffers(paramarg0: number, paramarg1: number): void;
    static glXUseXFont(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glXWaitGL(): void;
    static glXWaitX(): void;
    static nglXChooseVisual(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nglXCreateContext(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nglXCreateGLXPixmap(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nglXGetClientString(paramarg0: number, paramarg1: number): number;
    static nglXGetConfig(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nglXQueryExtension(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nglXQueryExtensionsString(paramarg0: number, paramarg1: number): number;
    static nglXQueryServerString(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nglXQueryVersion(paramarg0: number, paramarg1: number, paramarg2: number): number;
    constructor()
}