import type { ShortBuffer } from '../../../java/nio/ShortBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
export class NVHalfFloat extends Object {
    static GL_HALF_FLOAT_NV: number;
    static glColor3hNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glColor3hvNV(paramarg0: ShortBuffer): void;
    static glColor3hvNV(paramarg0: number[]): void;
    static glColor4hNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glColor4hvNV(paramarg0: ShortBuffer): void;
    static glColor4hvNV(paramarg0: number[]): void;
    static glFogCoordhNV(paramarg0: number): void;
    static glFogCoordhvNV(paramarg0: ShortBuffer): void;
    static glFogCoordhvNV(paramarg0: number[]): void;
    static glMultiTexCoord1hNV(paramarg0: number, paramarg1: number): void;
    static glMultiTexCoord1hvNV(paramarg0: number, paramarg1: ShortBuffer): void;
    static glMultiTexCoord1hvNV(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord2hNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glMultiTexCoord2hvNV(paramarg0: number, paramarg1: ShortBuffer): void;
    static glMultiTexCoord2hvNV(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord3hNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glMultiTexCoord3hvNV(paramarg0: number, paramarg1: ShortBuffer): void;
    static glMultiTexCoord3hvNV(paramarg0: number, paramarg1: number[]): void;
    static glMultiTexCoord4hNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glMultiTexCoord4hvNV(paramarg0: number, paramarg1: ShortBuffer): void;
    static glMultiTexCoord4hvNV(paramarg0: number, paramarg1: number[]): void;
    static glNormal3hNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glNormal3hvNV(paramarg0: ShortBuffer): void;
    static glNormal3hvNV(paramarg0: number[]): void;
    static glSecondaryColor3hNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glSecondaryColor3hvNV(paramarg0: ShortBuffer): void;
    static glSecondaryColor3hvNV(paramarg0: number[]): void;
    static glTexCoord1hNV(paramarg0: number): void;
    static glTexCoord1hvNV(paramarg0: ShortBuffer): void;
    static glTexCoord1hvNV(paramarg0: number[]): void;
    static glTexCoord2hNV(paramarg0: number, paramarg1: number): void;
    static glTexCoord2hvNV(paramarg0: ShortBuffer): void;
    static glTexCoord2hvNV(paramarg0: number[]): void;
    static glTexCoord3hNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glTexCoord3hvNV(paramarg0: ShortBuffer): void;
    static glTexCoord3hvNV(paramarg0: number[]): void;
    static glTexCoord4hNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glTexCoord4hvNV(paramarg0: ShortBuffer): void;
    static glTexCoord4hvNV(paramarg0: number[]): void;
    static glVertex2hNV(paramarg0: number, paramarg1: number): void;
    static glVertex2hvNV(paramarg0: ShortBuffer): void;
    static glVertex2hvNV(paramarg0: number[]): void;
    static glVertex3hNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glVertex3hvNV(paramarg0: ShortBuffer): void;
    static glVertex3hvNV(paramarg0: number[]): void;
    static glVertex4hNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glVertex4hvNV(paramarg0: ShortBuffer): void;
    static glVertex4hvNV(paramarg0: number[]): void;
    static glVertexAttrib1hNV(paramarg0: number, paramarg1: number): void;
    static glVertexAttrib1hvNV(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib1hvNV(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib2hNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glVertexAttrib2hvNV(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib2hvNV(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib3hNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glVertexAttrib3hvNV(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib3hvNV(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttrib4hNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static glVertexAttrib4hvNV(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttrib4hvNV(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttribs1hvNV(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttribs1hvNV(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttribs2hvNV(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttribs2hvNV(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttribs3hvNV(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttribs3hvNV(paramarg0: number, paramarg1: number[]): void;
    static glVertexAttribs4hvNV(paramarg0: number, paramarg1: ShortBuffer): void;
    static glVertexAttribs4hvNV(paramarg0: number, paramarg1: number[]): void;
    static glVertexWeighthNV(paramarg0: number): void;
    static glVertexWeighthvNV(paramarg0: ShortBuffer): void;
    static glVertexWeighthvNV(paramarg0: number[]): void;
    static nglColor3hvNV(paramarg0: number): void;
    static nglColor4hvNV(paramarg0: number): void;
    static nglFogCoordhvNV(paramarg0: number): void;
    static nglMultiTexCoord1hvNV(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord2hvNV(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord3hvNV(paramarg0: number, paramarg1: number): void;
    static nglMultiTexCoord4hvNV(paramarg0: number, paramarg1: number): void;
    static nglNormal3hvNV(paramarg0: number): void;
    static nglSecondaryColor3hvNV(paramarg0: number): void;
    static nglTexCoord1hvNV(paramarg0: number): void;
    static nglTexCoord2hvNV(paramarg0: number): void;
    static nglTexCoord3hvNV(paramarg0: number): void;
    static nglTexCoord4hvNV(paramarg0: number): void;
    static nglVertex2hvNV(paramarg0: number): void;
    static nglVertex3hvNV(paramarg0: number): void;
    static nglVertex4hvNV(paramarg0: number): void;
    static nglVertexAttrib1hvNV(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib2hvNV(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib3hvNV(paramarg0: number, paramarg1: number): void;
    static nglVertexAttrib4hvNV(paramarg0: number, paramarg1: number): void;
    static nglVertexAttribs1hvNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglVertexAttribs2hvNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglVertexAttribs3hvNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglVertexAttribs4hvNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglVertexWeighthvNV(paramarg0: number): void;
    constructor()
}