import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { FloatBuffer } from '../../../java/nio/FloatBuffer.d.ts'
import type { IntBuffer } from '../../../java/nio/IntBuffer.d.ts'
import type { ShortBuffer } from '../../../java/nio/ShortBuffer.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
export class NVPathRendering extends Object {
    static GL_2_BYTES_NV: number;
    static GL_3_BYTES_NV: number;
    static GL_4_BYTES_NV: number;
    static GL_ACCUM_ADJACENT_PAIRS_NV: number;
    static GL_ADJACENT_PAIRS_NV: number;
    static GL_AFFINE_2D_NV: number;
    static GL_AFFINE_3D_NV: number;
    static GL_ARC_TO_NV: number;
    static GL_BEVEL_NV: number;
    static GL_BOLD_BIT_NV: number;
    static GL_BOUNDING_BOX_NV: number;
    static GL_BOUNDING_BOX_OF_BOUNDING_BOXES_NV: number;
    static GL_CIRCULAR_CCW_ARC_TO_NV: number;
    static GL_CIRCULAR_CW_ARC_TO_NV: number;
    static GL_CIRCULAR_TANGENT_ARC_TO_NV: number;
    static GL_CLOSE_PATH_NV: number;
    static GL_CONIC_CURVE_TO_NV: number;
    static GL_CONSTANT_NV: number;
    static GL_CONVEX_HULL_NV: number;
    static GL_COUNT_DOWN_NV: number;
    static GL_COUNT_UP_NV: number;
    static GL_CUBIC_CURVE_TO_NV: number;
    static GL_DUP_FIRST_CUBIC_CURVE_TO_NV: number;
    static GL_DUP_LAST_CUBIC_CURVE_TO_NV: number;
    static GL_EYE_LINEAR_NV: number;
    static GL_FILE_NAME_NV: number;
    static GL_FIRST_TO_REST_NV: number;
    static GL_FONT_ASCENDER_BIT_NV: number;
    static GL_FONT_DESCENDER_BIT_NV: number;
    static GL_FONT_GLYPHS_AVAILABLE_NV: number;
    static GL_FONT_HAS_KERNING_BIT_NV: number;
    static GL_FONT_HEIGHT_BIT_NV: number;
    static GL_FONT_MAX_ADVANCE_HEIGHT_BIT_NV: number;
    static GL_FONT_MAX_ADVANCE_WIDTH_BIT_NV: number;
    static GL_FONT_NUM_GLYPH_INDICES_BIT_NV: number;
    static GL_FONT_TARGET_UNAVAILABLE_NV: number;
    static GL_FONT_UNAVAILABLE_NV: number;
    static GL_FONT_UNDERLINE_POSITION_BIT_NV: number;
    static GL_FONT_UNDERLINE_THICKNESS_BIT_NV: number;
    static GL_FONT_UNINTELLIGIBLE_NV: number;
    static GL_FONT_UNITS_PER_EM_BIT_NV: number;
    static GL_FONT_X_MAX_BOUNDS_BIT_NV: number;
    static GL_FONT_X_MIN_BOUNDS_BIT_NV: number;
    static GL_FONT_Y_MAX_BOUNDS_BIT_NV: number;
    static GL_FONT_Y_MIN_BOUNDS_BIT_NV: number;
    static GL_FRAGMENT_INPUT_NV: number;
    static GL_GLYPH_HAS_KERNING_BIT_NV: number;
    static GL_GLYPH_HEIGHT_BIT_NV: number;
    static GL_GLYPH_HORIZONTAL_BEARING_ADVANCE_BIT_NV: number;
    static GL_GLYPH_HORIZONTAL_BEARING_X_BIT_NV: number;
    static GL_GLYPH_HORIZONTAL_BEARING_Y_BIT_NV: number;
    static GL_GLYPH_VERTICAL_BEARING_ADVANCE_BIT_NV: number;
    static GL_GLYPH_VERTICAL_BEARING_X_BIT_NV: number;
    static GL_GLYPH_VERTICAL_BEARING_Y_BIT_NV: number;
    static GL_GLYPH_WIDTH_BIT_NV: number;
    static GL_HORIZONTAL_LINE_TO_NV: number;
    static GL_ITALIC_BIT_NV: number;
    static GL_LARGE_CCW_ARC_TO_NV: number;
    static GL_LARGE_CW_ARC_TO_NV: number;
    static GL_LINE_TO_NV: number;
    static GL_MITER_REVERT_NV: number;
    static GL_MITER_TRUNCATE_NV: number;
    static GL_MOVE_TO_CONTINUES_NV: number;
    static GL_MOVE_TO_NV: number;
    static GL_MOVE_TO_RESETS_NV: number;
    static GL_OBJECT_LINEAR_NV: number;
    static GL_PATH_CLIENT_LENGTH_NV: number;
    static GL_PATH_COMMAND_COUNT_NV: number;
    static GL_PATH_COMPUTED_LENGTH_NV: number;
    static GL_PATH_COORD_COUNT_NV: number;
    static GL_PATH_COVER_DEPTH_FUNC_NV: number;
    static GL_PATH_DASH_ARRAY_COUNT_NV: number;
    static GL_PATH_DASH_CAPS_NV: number;
    static GL_PATH_DASH_OFFSET_NV: number;
    static GL_PATH_DASH_OFFSET_RESET_NV: number;
    static GL_PATH_END_CAPS_NV: number;
    static GL_PATH_ERROR_POSITION_NV: number;
    static GL_PATH_FILL_BOUNDING_BOX_NV: number;
    static GL_PATH_FILL_COVER_MODE_NV: number;
    static GL_PATH_FILL_MASK_NV: number;
    static GL_PATH_FILL_MODE_NV: number;
    static GL_PATH_FOG_GEN_MODE_NV: number;
    static GL_PATH_FORMAT_PS_NV: number;
    static GL_PATH_FORMAT_SVG_NV: number;
    static GL_PATH_GEN_COEFF_NV: number;
    static GL_PATH_GEN_COLOR_FORMAT_NV: number;
    static GL_PATH_GEN_COMPONENTS_NV: number;
    static GL_PATH_GEN_MODE_NV: number;
    static GL_PATH_INITIAL_DASH_CAP_NV: number;
    static GL_PATH_INITIAL_END_CAP_NV: number;
    static GL_PATH_JOIN_STYLE_NV: number;
    static GL_PATH_MAX_MODELVIEW_STACK_DEPTH_NV: number;
    static GL_PATH_MAX_PROJECTION_STACK_DEPTH_NV: number;
    static GL_PATH_MITER_LIMIT_NV: number;
    static GL_PATH_MODELVIEW_MATRIX_NV: number;
    static GL_PATH_MODELVIEW_NV: number;
    static GL_PATH_MODELVIEW_STACK_DEPTH_NV: number;
    static GL_PATH_OBJECT_BOUNDING_BOX_NV: number;
    static GL_PATH_PROJECTION_MATRIX_NV: number;
    static GL_PATH_PROJECTION_NV: number;
    static GL_PATH_PROJECTION_STACK_DEPTH_NV: number;
    static GL_PATH_STENCIL_DEPTH_OFFSET_FACTOR_NV: number;
    static GL_PATH_STENCIL_DEPTH_OFFSET_UNITS_NV: number;
    static GL_PATH_STENCIL_FUNC_NV: number;
    static GL_PATH_STENCIL_REF_NV: number;
    static GL_PATH_STENCIL_VALUE_MASK_NV: number;
    static GL_PATH_STROKE_BOUNDING_BOX_NV: number;
    static GL_PATH_STROKE_BOUND_NV: number;
    static GL_PATH_STROKE_COVER_MODE_NV: number;
    static GL_PATH_STROKE_MASK_NV: number;
    static GL_PATH_STROKE_WIDTH_NV: number;
    static GL_PATH_TERMINAL_DASH_CAP_NV: number;
    static GL_PATH_TERMINAL_END_CAP_NV: number;
    static GL_PATH_TRANSPOSE_MODELVIEW_MATRIX_NV: number;
    static GL_PATH_TRANSPOSE_PROJECTION_MATRIX_NV: number;
    static GL_PRIMARY_COLOR_NV: number;
    static GL_QUADRATIC_CURVE_TO_NV: number;
    static GL_RECT_NV: number;
    static GL_RELATIVE_ARC_TO_NV: number;
    static GL_RELATIVE_CONIC_CURVE_TO_NV: number;
    static GL_RELATIVE_CUBIC_CURVE_TO_NV: number;
    static GL_RELATIVE_HORIZONTAL_LINE_TO_NV: number;
    static GL_RELATIVE_LARGE_CCW_ARC_TO_NV: number;
    static GL_RELATIVE_LARGE_CW_ARC_TO_NV: number;
    static GL_RELATIVE_LINE_TO_NV: number;
    static GL_RELATIVE_MOVE_TO_NV: number;
    static GL_RELATIVE_QUADRATIC_CURVE_TO_NV: number;
    static GL_RELATIVE_RECT_NV: number;
    static GL_RELATIVE_ROUNDED_RECT2_NV: number;
    static GL_RELATIVE_ROUNDED_RECT4_NV: number;
    static GL_RELATIVE_ROUNDED_RECT8_NV: number;
    static GL_RELATIVE_ROUNDED_RECT_NV: number;
    static GL_RELATIVE_SMALL_CCW_ARC_TO_NV: number;
    static GL_RELATIVE_SMALL_CW_ARC_TO_NV: number;
    static GL_RELATIVE_SMOOTH_CUBIC_CURVE_TO_NV: number;
    static GL_RELATIVE_SMOOTH_QUADRATIC_CURVE_TO_NV: number;
    static GL_RELATIVE_VERTICAL_LINE_TO_NV: number;
    static GL_RESTART_PATH_NV: number;
    static GL_ROUNDED_RECT2_NV: number;
    static GL_ROUNDED_RECT4_NV: number;
    static GL_ROUNDED_RECT8_NV: number;
    static GL_ROUNDED_RECT_NV: number;
    static GL_ROUND_NV: number;
    static GL_SECONDARY_COLOR_NV: number;
    static GL_SKIP_MISSING_GLYPH_NV: number;
    static GL_SMALL_CCW_ARC_TO_NV: number;
    static GL_SMALL_CW_ARC_TO_NV: number;
    static GL_SMOOTH_CUBIC_CURVE_TO_NV: number;
    static GL_SMOOTH_QUADRATIC_CURVE_TO_NV: number;
    static GL_SQUARE_NV: number;
    static GL_STANDARD_FONT_FORMAT_NV: number;
    static GL_STANDARD_FONT_NAME_NV: number;
    static GL_SYSTEM_FONT_NAME_NV: number;
    static GL_TRANSLATE_2D_NV: number;
    static GL_TRANSLATE_3D_NV: number;
    static GL_TRANSLATE_X_NV: number;
    static GL_TRANSLATE_Y_NV: number;
    static GL_TRANSPOSE_AFFINE_2D_NV: number;
    static GL_TRANSPOSE_AFFINE_3D_NV: number;
    static GL_TRIANGULAR_NV: number;
    static GL_USE_MISSING_GLYPH_NV: number;
    static GL_UTF16_NV: number;
    static GL_UTF8_NV: number;
    static GL_VERTICAL_LINE_TO_NV: number;
    static glCopyPathNV(paramarg0: number, paramarg1: number): void;
    static glCoverFillPathInstancedNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number[]): void;
    static glCoverFillPathInstancedNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: FloatBuffer): void;
    static glCoverFillPathNV(paramarg0: number, paramarg1: number): void;
    static glCoverStrokePathInstancedNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number[]): void;
    static glCoverStrokePathInstancedNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: FloatBuffer): void;
    static glCoverStrokePathNV(paramarg0: number, paramarg1: number): void;
    static glDeletePathsNV(paramarg0: number, paramarg1: number): void;
    static glGenPathsNV(paramarg0: number): number;
    static glGetPathColorGenfNV(paramarg0: number, paramarg1: number): number;
    static glGetPathColorGenfvNV(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetPathColorGenfvNV(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetPathColorGeniNV(paramarg0: number, paramarg1: number): number;
    static glGetPathColorGenivNV(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetPathColorGenivNV(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetPathCommandsNV(paramarg0: number, paramarg1: ByteBuffer): void;
    static glGetPathCoordsNV(paramarg0: number, paramarg1: number[]): void;
    static glGetPathCoordsNV(paramarg0: number, paramarg1: FloatBuffer): void;
    static glGetPathDashArrayNV(paramarg0: number, paramarg1: number[]): void;
    static glGetPathDashArrayNV(paramarg0: number, paramarg1: FloatBuffer): void;
    static glGetPathLengthNV(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static glGetPathMetricRangeNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[]): void;
    static glGetPathMetricRangeNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: FloatBuffer): void;
    static glGetPathMetricsNV(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number, paramarg5: number[]): void;
    static glGetPathMetricsNV(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number, paramarg5: FloatBuffer): void;
    static glGetPathParameterfNV(paramarg0: number, paramarg1: number): number;
    static glGetPathParameterfvNV(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetPathParameterfvNV(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetPathParameteriNV(paramarg0: number, paramarg1: number): number;
    static glGetPathParameterivNV(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetPathParameterivNV(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetPathSpacingNV(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number[]): void;
    static glGetPathSpacingNV(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: FloatBuffer): void;
    static glGetPathTexGenfNV(paramarg0: number, paramarg1: number): number;
    static glGetPathTexGenfvNV(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetPathTexGenfvNV(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glGetPathTexGeniNV(paramarg0: number, paramarg1: number): number;
    static glGetPathTexGenivNV(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glGetPathTexGenivNV(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glGetProgramResourcefvNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[], paramarg4: number[], paramarg5: number[]): void;
    static glGetProgramResourcefvNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: IntBuffer, paramarg4: IntBuffer, paramarg5: FloatBuffer): void;
    static glInterpolatePathsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glIsPathNV(paramarg0: number): boolean;
    static glIsPointInFillPathNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static glIsPointInStrokePathNV(paramarg0: number, paramarg1: number, paramarg2: number): boolean;
    static glMatrixLoad3x2fNV(paramarg0: number, paramarg1: number[]): void;
    static glMatrixLoad3x2fNV(paramarg0: number, paramarg1: FloatBuffer): void;
    static glMatrixLoad3x3fNV(paramarg0: number, paramarg1: number[]): void;
    static glMatrixLoad3x3fNV(paramarg0: number, paramarg1: FloatBuffer): void;
    static glMatrixLoadTranspose3x3fNV(paramarg0: number, paramarg1: number[]): void;
    static glMatrixLoadTranspose3x3fNV(paramarg0: number, paramarg1: FloatBuffer): void;
    static glMatrixMult3x2fNV(paramarg0: number, paramarg1: number[]): void;
    static glMatrixMult3x2fNV(paramarg0: number, paramarg1: FloatBuffer): void;
    static glMatrixMult3x3fNV(paramarg0: number, paramarg1: number[]): void;
    static glMatrixMult3x3fNV(paramarg0: number, paramarg1: FloatBuffer): void;
    static glMatrixMultTranspose3x3fNV(paramarg0: number, paramarg1: number[]): void;
    static glMatrixMultTranspose3x3fNV(paramarg0: number, paramarg1: FloatBuffer): void;
    static glPathColorGenNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glPathColorGenNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glPathCommandsNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number[]): void;
    static glPathCommandsNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: ByteBuffer): void;
    static glPathCommandsNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: FloatBuffer): void;
    static glPathCommandsNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: ShortBuffer): void;
    static glPathCommandsNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number[]): void;
    static glPathCoordsNV(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glPathCoordsNV(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer): void;
    static glPathCoordsNV(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glPathCoordsNV(paramarg0: number, paramarg1: number, paramarg2: ShortBuffer): void;
    static glPathCoordsNV(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glPathCoverDepthFuncNV(paramarg0: number): void;
    static glPathDashArrayNV(paramarg0: number, paramarg1: number[]): void;
    static glPathDashArrayNV(paramarg0: number, paramarg1: FloatBuffer): void;
    static glPathFogGenNV(paramarg0: number): void;
    static glPathGlyphIndexArrayNV(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): number;
    static glPathGlyphIndexRangeNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number[]): number;
    static glPathGlyphIndexRangeNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: IntBuffer): number;
    static glPathGlyphRangeNV(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static glPathGlyphsNV(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number, paramarg5: ByteBuffer, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static glPathMemoryGlyphIndexArrayNV(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): number;
    static glPathParameterfNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glPathParameterfvNV(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glPathParameterfvNV(paramarg0: number, paramarg1: number, paramarg2: FloatBuffer): void;
    static glPathParameteriNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glPathParameterivNV(paramarg0: number, paramarg1: number, paramarg2: number[]): void;
    static glPathParameterivNV(paramarg0: number, paramarg1: number, paramarg2: IntBuffer): void;
    static glPathStencilDepthOffsetNV(paramarg0: number, paramarg1: number): void;
    static glPathStencilFuncNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glPathStringNV(paramarg0: number, paramarg1: number, paramarg2: ByteBuffer): void;
    static glPathSubCommandsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer, paramarg4: number, paramarg5: number[]): void;
    static glPathSubCommandsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer, paramarg4: number, paramarg5: ByteBuffer): void;
    static glPathSubCommandsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer, paramarg4: number, paramarg5: FloatBuffer): void;
    static glPathSubCommandsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer, paramarg4: number, paramarg5: ShortBuffer): void;
    static glPathSubCommandsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer, paramarg4: number, paramarg5: number[]): void;
    static glPathSubCoordsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glPathSubCoordsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ByteBuffer): void;
    static glPathSubCoordsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glPathSubCoordsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: ShortBuffer): void;
    static glPathSubCoordsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glPathTexGenNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glPathTexGenNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glPointAlongPathNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[], paramarg5: number[], paramarg6: number[], paramarg7: number[]): boolean;
    static glPointAlongPathNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: FloatBuffer, paramarg5: FloatBuffer, paramarg6: FloatBuffer, paramarg7: FloatBuffer): boolean;
    static glProgramPathFragmentInputGenNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number[]): void;
    static glProgramPathFragmentInputGenNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: FloatBuffer): void;
    static glStencilFillPathInstancedNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[]): void;
    static glStencilFillPathInstancedNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: FloatBuffer): void;
    static glStencilFillPathNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glStencilStrokePathInstancedNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number[]): void;
    static glStencilStrokePathInstancedNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: FloatBuffer): void;
    static glStencilStrokePathNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static glStencilThenCoverFillPathInstancedNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number[]): void;
    static glStencilThenCoverFillPathInstancedNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: FloatBuffer): void;
    static glStencilThenCoverFillPathNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glStencilThenCoverStrokePathInstancedNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number[]): void;
    static glStencilThenCoverStrokePathInstancedNV(paramarg0: number, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: FloatBuffer): void;
    static glStencilThenCoverStrokePathNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static glTransformPathNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number[]): void;
    static glTransformPathNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: FloatBuffer): void;
    static glWeightPathsNV(paramarg0: number, paramarg1: number[], paramarg2: number[]): void;
    static glWeightPathsNV(paramarg0: number, paramarg1: IntBuffer, paramarg2: FloatBuffer): void;
    static nglCoverFillPathInstancedNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nglCoverStrokePathInstancedNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nglGetPathColorGenfvNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetPathColorGenivNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetPathCommandsNV(paramarg0: number, paramarg1: number): void;
    static nglGetPathCoordsNV(paramarg0: number, paramarg1: number): void;
    static nglGetPathDashArrayNV(paramarg0: number, paramarg1: number): void;
    static nglGetPathMetricRangeNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglGetPathMetricsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nglGetPathParameterfvNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetPathParameterivNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetPathSpacingNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static nglGetPathTexGenfvNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetPathTexGenivNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglGetProgramResourcefvNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nglMatrixLoad3x2fNV(paramarg0: number, paramarg1: number): void;
    static nglMatrixLoad3x3fNV(paramarg0: number, paramarg1: number): void;
    static nglMatrixLoadTranspose3x3fNV(paramarg0: number, paramarg1: number): void;
    static nglMatrixMult3x2fNV(paramarg0: number, paramarg1: number): void;
    static nglMatrixMult3x3fNV(paramarg0: number, paramarg1: number): void;
    static nglMatrixMultTranspose3x3fNV(paramarg0: number, paramarg1: number): void;
    static nglPathColorGenNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglPathCommandsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nglPathCoordsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglPathDashArrayNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglPathGlyphIndexArrayNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): number;
    static nglPathGlyphIndexRangeNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): number;
    static nglPathGlyphRangeNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static nglPathGlyphsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number, paramarg9: number): void;
    static nglPathMemoryGlyphIndexArrayNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): number;
    static nglPathParameterfvNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglPathParameterivNV(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nglPathStringNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglPathSubCommandsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nglPathSubCoordsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglPathTexGenNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglPointAlongPathNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): boolean;
    static nglProgramPathFragmentInputGenNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nglStencilFillPathInstancedNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nglStencilStrokePathInstancedNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number): void;
    static nglStencilThenCoverFillPathInstancedNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static nglStencilThenCoverStrokePathInstancedNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number, paramarg7: number, paramarg8: number): void;
    static nglTransformPathNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nglWeightPathsNV(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    constructor()
}