import type { Codec } from '../../../../../../../../com/viaversion/viaversion/libs/mcstructs/converter/codec/Codec.d.ts'
import type { MapCodecMerger$I1 } from '../../../../../../../../com/viaversion/viaversion/libs/mcstructs/converter/codec/map/MapCodecMerger$I1.d.ts'
import type { MapCodecMerger$I10 } from '../../../../../../../../com/viaversion/viaversion/libs/mcstructs/converter/codec/map/MapCodecMerger$I10.d.ts'
import type { MapCodecMerger$I11 } from '../../../../../../../../com/viaversion/viaversion/libs/mcstructs/converter/codec/map/MapCodecMerger$I11.d.ts'
import type { MapCodecMerger$I2 } from '../../../../../../../../com/viaversion/viaversion/libs/mcstructs/converter/codec/map/MapCodecMerger$I2.d.ts'
import type { MapCodecMerger$I3 } from '../../../../../../../../com/viaversion/viaversion/libs/mcstructs/converter/codec/map/MapCodecMerger$I3.d.ts'
import type { MapCodecMerger$I4 } from '../../../../../../../../com/viaversion/viaversion/libs/mcstructs/converter/codec/map/MapCodecMerger$I4.d.ts'
import type { MapCodecMerger$I5 } from '../../../../../../../../com/viaversion/viaversion/libs/mcstructs/converter/codec/map/MapCodecMerger$I5.d.ts'
import type { MapCodecMerger$I6 } from '../../../../../../../../com/viaversion/viaversion/libs/mcstructs/converter/codec/map/MapCodecMerger$I6.d.ts'
import type { MapCodecMerger$I7 } from '../../../../../../../../com/viaversion/viaversion/libs/mcstructs/converter/codec/map/MapCodecMerger$I7.d.ts'
import type { MapCodecMerger$I8 } from '../../../../../../../../com/viaversion/viaversion/libs/mcstructs/converter/codec/map/MapCodecMerger$I8.d.ts'
import type { MapCodecMerger$I9 } from '../../../../../../../../com/viaversion/viaversion/libs/mcstructs/converter/codec/map/MapCodecMerger$I9.d.ts'
import type { MapCodec } from '../../../../../../../../com/viaversion/viaversion/libs/mcstructs/converter/mapcodec/MapCodec.d.ts'
import type { Function } from '../../../../../../../../java/util/function/Function.d.ts'
import type { Object } from '../../../../../../../../java/lang/Object.d.ts'
export class MapCodecMerger extends Object {
    static codec<T1 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: (param0: T1) => O): Codec<O>;
    static codec<T1 extends unknown, T2 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: (param0: T1, param1: T2) => O): Codec<O>;
    static codec<T1 extends unknown, T2 extends unknown, T3 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: (param0: T1, param1: T2, param2: T3) => O): Codec<O>;
    static codec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: (param0: T1, param1: T2, param2: T3, param3: T4) => O): Codec<O>;
    static codec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5) => O): Codec<O>;
    static codec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: MapCodec<T6>, paramarg11: (param0: O) => T6, paramarg12: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5, param5: T6) => O): Codec<O>;
    static codec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: MapCodec<T6>, paramarg11: (param0: O) => T6, paramarg12: MapCodec<T7>, paramarg13: (param0: O) => T7, paramarg14: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5, param5: T6, param6: T7) => O): Codec<O>;
    static codec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: MapCodec<T6>, paramarg11: (param0: O) => T6, paramarg12: MapCodec<T7>, paramarg13: (param0: O) => T7, paramarg14: MapCodec<T8>, paramarg15: (param0: O) => T8, paramarg16: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5, param5: T6, param6: T7, param7: T8) => O): Codec<O>;
    static codec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: MapCodec<T6>, paramarg11: (param0: O) => T6, paramarg12: MapCodec<T7>, paramarg13: (param0: O) => T7, paramarg14: MapCodec<T8>, paramarg15: (param0: O) => T8, paramarg16: MapCodec<T9>, paramarg17: (param0: O) => T9, paramarg18: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5, param5: T6, param6: T7, param7: T8, param8: T9) => O): Codec<O>;
    static codec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: MapCodec<T6>, paramarg11: (param0: O) => T6, paramarg12: MapCodec<T7>, paramarg13: (param0: O) => T7, paramarg14: MapCodec<T8>, paramarg15: (param0: O) => T8, paramarg16: MapCodec<T9>, paramarg17: (param0: O) => T9, paramarg18: MapCodec<T10>, paramarg19: (param0: O) => T10, paramarg20: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5, param5: T6, param6: T7, param7: T8, param8: T9, param9: T10) => O): Codec<O>;
    static codec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: MapCodec<T6>, paramarg11: (param0: O) => T6, paramarg12: MapCodec<T7>, paramarg13: (param0: O) => T7, paramarg14: MapCodec<T8>, paramarg15: (param0: O) => T8, paramarg16: MapCodec<T9>, paramarg17: (param0: O) => T9, paramarg18: MapCodec<T10>, paramarg19: (param0: O) => T10, paramarg20: MapCodec<T11>, paramarg21: (param0: O) => T11, paramarg22: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5, param5: T6, param6: T7, param7: T8, param8: T9, param9: T10, param10: T11) => O): Codec<O>;
    static mapCodec<T1 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: (param0: T1) => O): MapCodec<O>;
    static mapCodec<T1 extends unknown, T2 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: (param0: T1, param1: T2) => O): MapCodec<O>;
    static mapCodec<T1 extends unknown, T2 extends unknown, T3 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: (param0: T1, param1: T2, param2: T3) => O): MapCodec<O>;
    static mapCodec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: (param0: T1, param1: T2, param2: T3, param3: T4) => O): MapCodec<O>;
    static mapCodec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5) => O): MapCodec<O>;
    static mapCodec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: MapCodec<T6>, paramarg11: (param0: O) => T6, paramarg12: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5, param5: T6) => O): MapCodec<O>;
    static mapCodec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: MapCodec<T6>, paramarg11: (param0: O) => T6, paramarg12: MapCodec<T7>, paramarg13: (param0: O) => T7, paramarg14: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5, param5: T6, param6: T7) => O): MapCodec<O>;
    static mapCodec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: MapCodec<T6>, paramarg11: (param0: O) => T6, paramarg12: MapCodec<T7>, paramarg13: (param0: O) => T7, paramarg14: MapCodec<T8>, paramarg15: (param0: O) => T8, paramarg16: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5, param5: T6, param6: T7, param7: T8) => O): MapCodec<O>;
    static mapCodec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: MapCodec<T6>, paramarg11: (param0: O) => T6, paramarg12: MapCodec<T7>, paramarg13: (param0: O) => T7, paramarg14: MapCodec<T8>, paramarg15: (param0: O) => T8, paramarg16: MapCodec<T9>, paramarg17: (param0: O) => T9, paramarg18: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5, param5: T6, param6: T7, param7: T8, param8: T9) => O): MapCodec<O>;
    static mapCodec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: MapCodec<T6>, paramarg11: (param0: O) => T6, paramarg12: MapCodec<T7>, paramarg13: (param0: O) => T7, paramarg14: MapCodec<T8>, paramarg15: (param0: O) => T8, paramarg16: MapCodec<T9>, paramarg17: (param0: O) => T9, paramarg18: MapCodec<T10>, paramarg19: (param0: O) => T10, paramarg20: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5, param5: T6, param6: T7, param7: T8, param8: T9, param9: T10) => O): MapCodec<O>;
    static mapCodec<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown, O extends unknown>(paramarg0: MapCodec<T1>, paramarg1: (param0: O) => T1, paramarg2: MapCodec<T2>, paramarg3: (param0: O) => T2, paramarg4: MapCodec<T3>, paramarg5: (param0: O) => T3, paramarg6: MapCodec<T4>, paramarg7: (param0: O) => T4, paramarg8: MapCodec<T5>, paramarg9: (param0: O) => T5, paramarg10: MapCodec<T6>, paramarg11: (param0: O) => T6, paramarg12: MapCodec<T7>, paramarg13: (param0: O) => T7, paramarg14: MapCodec<T8>, paramarg15: (param0: O) => T8, paramarg16: MapCodec<T9>, paramarg17: (param0: O) => T9, paramarg18: MapCodec<T10>, paramarg19: (param0: O) => T10, paramarg20: MapCodec<T11>, paramarg21: (param0: O) => T11, paramarg22: (param0: T1, param1: T2, param2: T3, param3: T4, param4: T5, param5: T6, param6: T7, param7: T8, param8: T9, param9: T10, param10: T11) => O): MapCodec<O>;
    constructor()
}