import type { Class } from '../../../../java/lang/Class.d.ts'
import type { ClassLoader } from '../../../../java/lang/ClassLoader.d.ts'
import type { Field } from '../../../../java/lang/reflect/Field.d.ts'
import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { ProtectionDomain } from '../../../../java/security/ProtectionDomain.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { Throwable } from '../../../../java/lang/Throwable.d.ts'
export class UnsafeAccess extends Object {
    static addressSize(): number;
    static allocateInstance(paramarg0: Class<Object>): Object;
    static allocateMemory(paramarg0: number): number;
    static allocateUninitializedArray(paramarg0: Class<Object>, paramarg1: number): Object;
    static arrayBaseOffset(paramarg0: Class<Object>): number;
    static arrayBaseOffsetInt(paramarg0: Class<Object>): number;
    static arrayBaseOffsetLong(paramarg0: Class<Object>): number;
    static arrayIndexScale(paramarg0: Class<Object>): number;
    static compareAndExchangeBoolean(paramarg0: Object, paramarg1: number, paramarg2: boolean, paramarg3: boolean): boolean;
    static compareAndExchangeBooleanAcquire(paramarg0: Object, paramarg1: number, paramarg2: boolean, paramarg3: boolean): boolean;
    static compareAndExchangeBooleanRelease(paramarg0: Object, paramarg1: number, paramarg2: boolean, paramarg3: boolean): boolean;
    static compareAndExchangeByte(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeByteAcquire(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeByteRelease(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeChar(paramarg0: Object, paramarg1: number, paramarg2: string, paramarg3: string): string;
    static compareAndExchangeCharAcquire(paramarg0: Object, paramarg1: number, paramarg2: string, paramarg3: string): string;
    static compareAndExchangeCharRelease(paramarg0: Object, paramarg1: number, paramarg2: string, paramarg3: string): string;
    static compareAndExchangeDouble(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeDoubleAcquire(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeDoubleRelease(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeFloat(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeFloatAcquire(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeFloatRelease(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeInt(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeIntAcquire(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeIntRelease(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeLong(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeLongAcquire(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeLongRelease(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeObject(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): Object;
    static compareAndExchangeObjectAcquire(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): Object;
    static compareAndExchangeObjectRelease(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): Object;
    static compareAndExchangeReference(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): Object;
    static compareAndExchangeReferenceAcquire(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): Object;
    static compareAndExchangeReferenceRelease(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): Object;
    static compareAndExchangeShort(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeShortAcquire(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndExchangeShortRelease(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static compareAndSetBoolean(paramarg0: Object, paramarg1: number, paramarg2: boolean, paramarg3: boolean): boolean;
    static compareAndSetByte(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static compareAndSetChar(paramarg0: Object, paramarg1: number, paramarg2: string, paramarg3: string): boolean;
    static compareAndSetDouble(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static compareAndSetFloat(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static compareAndSetInt(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static compareAndSetLong(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static compareAndSetObject(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): boolean;
    static compareAndSetReference(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): boolean;
    static compareAndSetShort(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static compareAndSwapInt(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static compareAndSwapLong(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static compareAndSwapObject(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): boolean;
    static copyMemory(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: number, paramarg4: number): void;
    static copyMemory(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static copySwapMemory(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static copySwapMemory(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static dataCacheLineAlignDown(paramarg0: number): number;
    static dataCacheLineFlushSize(): number;
    static defineClass(paramarg0: string, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: ClassLoader, paramarg5: ProtectionDomain): Class<Object>;
    static defineClass0(paramarg0: string, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: ClassLoader, paramarg5: ProtectionDomain): Class<Object>;
    static ensureClassInitialized(paramarg0: Class<Object>): void;
    static freeMemory(paramarg0: number): void;
    static fullFence(): void;
    static getAddress(paramarg0: Object, paramarg1: number): number;
    static getAddress(paramarg0: number): number;
    static getAndAddByte(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddByteAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddByteRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddChar(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndAddCharAcquire(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndAddCharRelease(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndAddDouble(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddDoubleAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddDoubleRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddFloat(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddFloatAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddFloatRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddInt(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddIntAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddIntRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddLong(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddLongAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddLongRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddShort(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddShortAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndAddShortRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseAndBoolean(paramarg0: Object, paramarg1: number, paramarg2: boolean): boolean;
    static getAndBitwiseAndBooleanAcquire(paramarg0: Object, paramarg1: number, paramarg2: boolean): boolean;
    static getAndBitwiseAndBooleanRelease(paramarg0: Object, paramarg1: number, paramarg2: boolean): boolean;
    static getAndBitwiseAndByte(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseAndByteAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseAndByteRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseAndChar(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndBitwiseAndCharAcquire(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndBitwiseAndCharRelease(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndBitwiseAndInt(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseAndIntAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseAndIntRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseAndLong(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseAndLongAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseAndLongRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseAndShort(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseAndShortAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseAndShortRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseOrBoolean(paramarg0: Object, paramarg1: number, paramarg2: boolean): boolean;
    static getAndBitwiseOrBooleanAcquire(paramarg0: Object, paramarg1: number, paramarg2: boolean): boolean;
    static getAndBitwiseOrBooleanRelease(paramarg0: Object, paramarg1: number, paramarg2: boolean): boolean;
    static getAndBitwiseOrByte(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseOrByteAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseOrByteRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseOrChar(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndBitwiseOrCharAcquire(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndBitwiseOrCharRelease(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndBitwiseOrInt(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseOrIntAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseOrIntRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseOrLong(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseOrLongAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseOrLongRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseOrShort(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseOrShortAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseOrShortRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseXorBoolean(paramarg0: Object, paramarg1: number, paramarg2: boolean): boolean;
    static getAndBitwiseXorBooleanAcquire(paramarg0: Object, paramarg1: number, paramarg2: boolean): boolean;
    static getAndBitwiseXorBooleanRelease(paramarg0: Object, paramarg1: number, paramarg2: boolean): boolean;
    static getAndBitwiseXorByte(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseXorByteAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseXorByteRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseXorChar(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndBitwiseXorCharAcquire(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndBitwiseXorCharRelease(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndBitwiseXorInt(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseXorIntAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseXorIntRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseXorLong(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseXorLongAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseXorLongRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseXorShort(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseXorShortAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndBitwiseXorShortRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetBoolean(paramarg0: Object, paramarg1: number, paramarg2: boolean): boolean;
    static getAndSetBooleanAcquire(paramarg0: Object, paramarg1: number, paramarg2: boolean): boolean;
    static getAndSetBooleanRelease(paramarg0: Object, paramarg1: number, paramarg2: boolean): boolean;
    static getAndSetByte(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetByteAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetByteRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetChar(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndSetCharAcquire(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndSetCharRelease(paramarg0: Object, paramarg1: number, paramarg2: string): string;
    static getAndSetDouble(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetDoubleAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetDoubleRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetFloat(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetFloatAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetFloatRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetInt(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetIntAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetIntRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetLong(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetLongAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetLongRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetObject(paramarg0: Object, paramarg1: number, paramarg2: Object): Object;
    static getAndSetObjectAcquire(paramarg0: Object, paramarg1: number, paramarg2: Object): Object;
    static getAndSetObjectRelease(paramarg0: Object, paramarg1: number, paramarg2: Object): Object;
    static getAndSetReference(paramarg0: Object, paramarg1: number, paramarg2: Object): Object;
    static getAndSetReferenceAcquire(paramarg0: Object, paramarg1: number, paramarg2: Object): Object;
    static getAndSetReferenceRelease(paramarg0: Object, paramarg1: number, paramarg2: Object): Object;
    static getAndSetShort(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetShortAcquire(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getAndSetShortRelease(paramarg0: Object, paramarg1: number, paramarg2: number): number;
    static getBoolean(paramarg0: Object, paramarg1: number): boolean;
    static getBooleanAcquire(paramarg0: Object, paramarg1: number): boolean;
    static getBooleanOpaque(paramarg0: Object, paramarg1: number): boolean;
    static getBooleanVolatile(paramarg0: Object, paramarg1: number): boolean;
    static getByte(paramarg0: Object, paramarg1: number): number;
    static getByte(paramarg0: number): number;
    static getByteAcquire(paramarg0: Object, paramarg1: number): number;
    static getByteOpaque(paramarg0: Object, paramarg1: number): number;
    static getByteVolatile(paramarg0: Object, paramarg1: number): number;
    static getChar(paramarg0: Object, paramarg1: number): string;
    static getChar(paramarg0: number): string;
    static getCharAcquire(paramarg0: Object, paramarg1: number): string;
    static getCharOpaque(paramarg0: Object, paramarg1: number): string;
    static getCharUnaligned(paramarg0: Object, paramarg1: number): string;
    static getCharUnaligned(paramarg0: Object, paramarg1: number, paramarg2: boolean): string;
    static getCharVolatile(paramarg0: Object, paramarg1: number): string;
    static getDouble(paramarg0: Object, paramarg1: number): number;
    static getDouble(paramarg0: number): number;
    static getDoubleAcquire(paramarg0: Object, paramarg1: number): number;
    static getDoubleOpaque(paramarg0: Object, paramarg1: number): number;
    static getDoubleVolatile(paramarg0: Object, paramarg1: number): number;
    static getFloat(paramarg0: Object, paramarg1: number): number;
    static getFloat(paramarg0: number): number;
    static getFloatAcquire(paramarg0: Object, paramarg1: number): number;
    static getFloatOpaque(paramarg0: Object, paramarg1: number): number;
    static getFloatVolatile(paramarg0: Object, paramarg1: number): number;
    static getInt(paramarg0: Object, paramarg1: number): number;
    static getInt(paramarg0: number): number;
    static getIntAcquire(paramarg0: Object, paramarg1: number): number;
    static getIntOpaque(paramarg0: Object, paramarg1: number): number;
    static getIntUnaligned(paramarg0: Object, paramarg1: number): number;
    static getIntUnaligned(paramarg0: Object, paramarg1: number, paramarg2: boolean): number;
    static getIntVolatile(paramarg0: Object, paramarg1: number): number;
    static getLoadAverage(paramarg0: number, paramarg1: number): number;
    static getLong(paramarg0: Object, paramarg1: number): number;
    static getLong(paramarg0: number): number;
    static getLongAcquire(paramarg0: Object, paramarg1: number): number;
    static getLongOpaque(paramarg0: Object, paramarg1: number): number;
    static getLongUnaligned(paramarg0: Object, paramarg1: number): number;
    static getLongUnaligned(paramarg0: Object, paramarg1: number, paramarg2: boolean): number;
    static getLongVolatile(paramarg0: Object, paramarg1: number): number;
    static getObject(paramarg0: Object, paramarg1: number): Object;
    static getObjectAcquire(paramarg0: Object, paramarg1: number): Object;
    static getObjectOpaque(paramarg0: Object, paramarg1: number): Object;
    static getObjectVolatile(paramarg0: Object, paramarg1: number): Object;
    static getReference(paramarg0: Object, paramarg1: number): Object;
    static getReferenceAcquire(paramarg0: Object, paramarg1: number): Object;
    static getReferenceOpaque(paramarg0: Object, paramarg1: number): Object;
    static getReferenceVolatile(paramarg0: Object, paramarg1: number): Object;
    static getShort(paramarg0: Object, paramarg1: number): number;
    static getShort(paramarg0: number): number;
    static getShortAcquire(paramarg0: Object, paramarg1: number): number;
    static getShortOpaque(paramarg0: Object, paramarg1: number): number;
    static getShortUnaligned(paramarg0: Object, paramarg1: number): number;
    static getShortUnaligned(paramarg0: Object, paramarg1: number, paramarg2: boolean): number;
    static getShortVolatile(paramarg0: Object, paramarg1: number): number;
    static getUncompressedObject(paramarg0: number): Object;
    static invokeCleaner(paramarg0: ByteBuffer): void;
    static isBigEndian(): boolean;
    static loadFence(): void;
    static loadLoadFence(): void;
    static objectFieldOffset(paramarg0: Class<Object>, paramarg1: string): number;
    static objectFieldOffset(paramarg0: Field): number;
    static pageSize(): number;
    static park(paramarg0: boolean, paramarg1: number): void;
    static putAddress(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putAddress(paramarg0: number, paramarg1: number): void;
    static putBoolean(paramarg0: Object, paramarg1: number, paramarg2: boolean): void;
    static putBooleanOpaque(paramarg0: Object, paramarg1: number, paramarg2: boolean): void;
    static putBooleanRelease(paramarg0: Object, paramarg1: number, paramarg2: boolean): void;
    static putBooleanVolatile(paramarg0: Object, paramarg1: number, paramarg2: boolean): void;
    static putByte(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putByte(paramarg0: number, paramarg1: number): void;
    static putByteOpaque(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putByteRelease(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putByteVolatile(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putChar(paramarg0: Object, paramarg1: number, paramarg2: string): void;
    static putChar(paramarg0: number, paramarg1: string): void;
    static putCharOpaque(paramarg0: Object, paramarg1: number, paramarg2: string): void;
    static putCharRelease(paramarg0: Object, paramarg1: number, paramarg2: string): void;
    static putCharUnaligned(paramarg0: Object, paramarg1: number, paramarg2: string): void;
    static putCharUnaligned(paramarg0: Object, paramarg1: number, paramarg2: string, paramarg3: boolean): void;
    static putCharVolatile(paramarg0: Object, paramarg1: number, paramarg2: string): void;
    static putDouble(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putDouble(paramarg0: number, paramarg1: number): void;
    static putDoubleOpaque(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putDoubleRelease(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putDoubleVolatile(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putFloat(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putFloat(paramarg0: number, paramarg1: number): void;
    static putFloatOpaque(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putFloatRelease(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putFloatVolatile(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putInt(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putInt(paramarg0: number, paramarg1: number): void;
    static putIntOpaque(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putIntRelease(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putIntUnaligned(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putIntUnaligned(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: boolean): void;
    static putIntVolatile(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putLong(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putLong(paramarg0: number, paramarg1: number): void;
    static putLongOpaque(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putLongRelease(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putLongUnaligned(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putLongUnaligned(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: boolean): void;
    static putLongVolatile(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putObject(paramarg0: Object, paramarg1: number, paramarg2: Object): void;
    static putObjectOpaque(paramarg0: Object, paramarg1: number, paramarg2: Object): void;
    static putObjectRelease(paramarg0: Object, paramarg1: number, paramarg2: Object): void;
    static putObjectVolatile(paramarg0: Object, paramarg1: number, paramarg2: Object): void;
    static putOrderedInt(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putOrderedLong(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putOrderedObject(paramarg0: Object, paramarg1: number, paramarg2: Object): void;
    static putReference(paramarg0: Object, paramarg1: number, paramarg2: Object): void;
    static putReferenceOpaque(paramarg0: Object, paramarg1: number, paramarg2: Object): void;
    static putReferenceRelease(paramarg0: Object, paramarg1: number, paramarg2: Object): void;
    static putReferenceVolatile(paramarg0: Object, paramarg1: number, paramarg2: Object): void;
    static putShort(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putShort(paramarg0: number, paramarg1: number): void;
    static putShortOpaque(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putShortRelease(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putShortUnaligned(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static putShortUnaligned(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: boolean): void;
    static putShortVolatile(paramarg0: Object, paramarg1: number, paramarg2: number): void;
    static reallocateMemory(paramarg0: number, paramarg1: number): number;
    static setMemory(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static setMemory(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static shouldBeInitialized(paramarg0: Class<Object>): boolean;
    static staticFieldBase(paramarg0: Field): Object;
    static staticFieldOffset(paramarg0: Field): number;
    static storeFence(): void;
    static storeStoreFence(): void;
    static throwException(paramarg0: Throwable): void;
    static unalignedAccess(): boolean;
    static unpark(paramarg0: Object): void;
    static weakCompareAndSetBoolean(paramarg0: Object, paramarg1: number, paramarg2: boolean, paramarg3: boolean): boolean;
    static weakCompareAndSetBooleanAcquire(paramarg0: Object, paramarg1: number, paramarg2: boolean, paramarg3: boolean): boolean;
    static weakCompareAndSetBooleanPlain(paramarg0: Object, paramarg1: number, paramarg2: boolean, paramarg3: boolean): boolean;
    static weakCompareAndSetBooleanRelease(paramarg0: Object, paramarg1: number, paramarg2: boolean, paramarg3: boolean): boolean;
    static weakCompareAndSetByte(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetByteAcquire(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetBytePlain(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetByteRelease(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetChar(paramarg0: Object, paramarg1: number, paramarg2: string, paramarg3: string): boolean;
    static weakCompareAndSetCharAcquire(paramarg0: Object, paramarg1: number, paramarg2: string, paramarg3: string): boolean;
    static weakCompareAndSetCharPlain(paramarg0: Object, paramarg1: number, paramarg2: string, paramarg3: string): boolean;
    static weakCompareAndSetCharRelease(paramarg0: Object, paramarg1: number, paramarg2: string, paramarg3: string): boolean;
    static weakCompareAndSetDouble(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetDoubleAcquire(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetDoublePlain(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetDoubleRelease(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetFloat(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetFloatAcquire(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetFloatPlain(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetFloatRelease(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetInt(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetIntAcquire(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetIntPlain(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetIntRelease(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetLong(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetLongAcquire(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetLongPlain(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetLongRelease(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetObject(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): boolean;
    static weakCompareAndSetObjectAcquire(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): boolean;
    static weakCompareAndSetObjectPlain(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): boolean;
    static weakCompareAndSetObjectRelease(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): boolean;
    static weakCompareAndSetReference(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): boolean;
    static weakCompareAndSetReferenceAcquire(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): boolean;
    static weakCompareAndSetReferencePlain(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): boolean;
    static weakCompareAndSetReferenceRelease(paramarg0: Object, paramarg1: number, paramarg2: Object, paramarg3: Object): boolean;
    static weakCompareAndSetShort(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetShortAcquire(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetShortPlain(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static weakCompareAndSetShortRelease(paramarg0: Object, paramarg1: number, paramarg2: number, paramarg3: number): boolean;
    static writebackMemory(paramarg0: number, paramarg1: number): void;
    constructor()
}