import type { Object } from '../../java/lang/Object.d.ts'
import type { Comparable } from '../../java/lang/Comparable.d.ts'
import type { Duration$Companion } from '../../kotlin/time/Duration$Companion.d.ts'
import type { DurationUnit } from '../../kotlin/time/DurationUnit.d.ts'
export class Duration extends Object implements Comparable<Duration> {
    static Companion: Duration$Companion;
    static INVALID_RAW_VALUE: number;
// (invalid TS: name contains '-')     static box-impl(paramarg0: number): Duration;
// (invalid TS: name contains '-')     static compareTo-LRDsOJo(paramarg0: number, paramarg1: number): number;
// (invalid TS: name contains '-')     static constructor-impl(paramarg0: number): number;
// (invalid TS: name contains '-')     static div-LRDsOJo(paramarg0: number, paramarg1: number): number;
// (invalid TS: name contains '-')     static div-UwyO8pc(paramarg0: number, paramarg1: number): number;
// (invalid TS: name contains '-')     static equals-impl(paramarg0: number, paramarg1: Object): boolean;
// (invalid TS: name contains '-')     static equals-impl0(paramarg0: number, paramarg1: number): boolean;
// (invalid TS: name contains '-')     static getAbsoluteValue-UwyO8pc(paramarg0: number): number;
// (invalid TS: name contains '-')     static getHoursComponent-impl(paramarg0: number): number;
// (invalid TS: name contains '-')     static getInWholeDays-impl(paramarg0: number): number;
// (invalid TS: name contains '-')     static getInWholeHours-impl(paramarg0: number): number;
// (invalid TS: name contains '-')     static getInWholeMicroseconds-impl(paramarg0: number): number;
// (invalid TS: name contains '-')     static getInWholeMilliseconds-impl(paramarg0: number): number;
// (invalid TS: name contains '-')     static getInWholeMinutes-impl(paramarg0: number): number;
// (invalid TS: name contains '-')     static getInWholeNanoseconds-impl(paramarg0: number): number;
// (invalid TS: name contains '-')     static getInWholeSeconds-impl(paramarg0: number): number;
// (invalid TS: name contains '-')     static getMinutesComponent-impl(paramarg0: number): number;
// (invalid TS: name contains '-')     static getNanosecondsComponent-impl(paramarg0: number): number;
// (invalid TS: name contains '-')     static getSecondsComponent-impl(paramarg0: number): number;
// (invalid TS: name contains '-')     static hashCode-impl(paramarg0: number): number;
// (invalid TS: name contains '-')     static isFinite-impl(paramarg0: number): boolean;
// (invalid TS: name contains '-')     static isInfinite-impl(paramarg0: number): boolean;
// (invalid TS: name contains '-')     static isNegative-impl(paramarg0: number): boolean;
// (invalid TS: name contains '-')     static isPositive-impl(paramarg0: number): boolean;
// (invalid TS: name contains '-')     static minus-LRDsOJo(paramarg0: number, paramarg1: number): number;
// (invalid TS: name contains '-')     static plus-LRDsOJo(paramarg0: number, paramarg1: number): number;
// (invalid TS: name contains '-')     static times-UwyO8pc(paramarg0: number, paramarg1: number): number;
// (invalid TS: name contains '-')     static toComponents-impl(paramarg0: number, paramarg1: (param0: Object, param1: Object) => Object | null): Object | null;
// (invalid TS: name contains '-')     static toComponents-impl(paramarg0: number, paramarg1: (param0: Object, param1: Object, param2: Object) => Object | null): Object | null;
// (invalid TS: name contains '-')     static toComponents-impl(paramarg0: number, paramarg1: (param0: Object, param1: Object, param2: Object, param3: Object) => Object | null): Object | null;
// (invalid TS: name contains '-')     static toComponents-impl(paramarg0: number, paramarg1: (param0: Object, param1: Object, param2: Object, param3: Object, param4: Object) => Object | null): Object | null;
// (invalid TS: name contains '-')     static toDouble-impl(paramarg0: number, paramarg1: DurationUnit): number;
// (invalid TS: name contains '-')     static toInt-impl(paramarg0: number, paramarg1: DurationUnit): number;
// (invalid TS: name contains '-')     static toIsoString-impl(paramarg0: number): string;
// (invalid TS: name contains '-')     static toLong-impl(paramarg0: number, paramarg1: DurationUnit): number;
// (invalid TS: name contains '-')     static toString-impl(paramarg0: number, paramarg1: DurationUnit, paramarg2: number): string;
// (invalid TS: name contains '-')     static toString-impl(paramarg0: number): string;
// (invalid TS: name contains '-')     static truncateTo-UwyO8pc$kotlin_stdlib(paramarg0: number, paramarg1: DurationUnit): number;
// (invalid TS: name contains '-')     static unaryMinus-UwyO8pc(paramarg0: number): number;
    constructor(rawValue: number)
// (invalid TS: name contains '-')     /*not mapped: */ getAbsoluteValue-UwyO8pc(): Duration;
// (invalid TS: name contains '-')     /*not mapped: */ getHoursComponent-impl(): number;
// (invalid TS: name contains '-')     /*not mapped: */ getInWholeDays-impl(): number;
// (invalid TS: name contains '-')     /*not mapped: */ getInWholeHours-impl(): number;
// (invalid TS: name contains '-')     /*not mapped: */ getInWholeMicroseconds-impl(): number;
// (invalid TS: name contains '-')     /*not mapped: */ getInWholeMilliseconds-impl(): number;
// (invalid TS: name contains '-')     /*not mapped: */ getInWholeMinutes-impl(): number;
// (invalid TS: name contains '-')     /*not mapped: */ getInWholeNanoseconds-impl(): number;
// (invalid TS: name contains '-')     /*not mapped: */ getInWholeSeconds-impl(): number;
// (invalid TS: name contains '-')     /*not mapped: */ getMinutesComponent-impl(): number;
// (invalid TS: name contains '-')     /*not mapped: */ getNanosecondsComponent-impl(): number;
    // private rawValue: number;
// (invalid TS: name contains '-')     /*not mapped: */ getSecondsComponent-impl(): number;
// (invalid TS: name contains '-')     // private /*not mapped: */ getStorageUnit-impl(): DurationUnit;
// (invalid TS: name contains '-')     // private /*not mapped: */ getUnitDiscriminator-impl(): number;
// (invalid TS: name contains '-')     // private /*not mapped: */ getValue-impl(): number;
    // private addValuesMixedRanges(thisMillis: number, otherNanos: number): Duration;
    compareTo(other: Duration): number;
    div(scale: number): Duration;
    div(other: Duration): number;
    equals(other: Object | null): boolean;
    hashCode(): number;
    isFinite(): boolean;
    // private isInMillis(): boolean;
    // private isInNanos(): boolean;
    isInfinite(): boolean;
    isNegative(): boolean;
    isPositive(): boolean;
    minus(other: Duration): Duration;
    plus(other: Duration): Duration;
    times(scale: number): Duration;
    toComponents<T extends unknown>(action: (param0: number, param1: number) => T): T;
    toComponents<T extends unknown>(action: (param0: number, param1: number, param2: number) => T): T;
    toComponents<T extends unknown>(action: (param0: number, param1: number, param2: number, param3: number) => T): T;
    toComponents<T extends unknown>(action: (param0: number, param1: number, param2: number, param3: number, param4: number) => T): T;
    toDouble(unit: DurationUnit): number;
    toInt(unit: DurationUnit): number;
    toIsoString(): string;
    toLong(unit: DurationUnit): number;
    toString(): string;
    toString(unit: DurationUnit, decimals: number): string;
    truncateTo(unit: DurationUnit): Duration;
    unaryMinus(): Duration;
}