import type { ByteBuffer } from '../../java/nio/ByteBuffer.d.ts'
import type { DoubleBuffer } from '../../java/nio/DoubleBuffer.d.ts'
import type { FloatBuffer } from '../../java/nio/FloatBuffer.d.ts'
import type { Object } from '../../java/lang/Object.d.ts'
import type { AxisAngle4d } from '../../org/joml/AxisAngle4d.d.ts'
import type { AxisAngle4f } from '../../org/joml/AxisAngle4f.d.ts'
import type { Matrix3d } from '../../org/joml/Matrix3d.d.ts'
import type { Matrix3x2dc } from '../../org/joml/Matrix3x2dc.d.ts'
import type { Matrix3x2fc } from '../../org/joml/Matrix3x2fc.d.ts'
import type { Matrix4d } from '../../org/joml/Matrix4d.d.ts'
import type { Matrix4fc } from '../../org/joml/Matrix4fc.d.ts'
import type { Matrix4x3d } from '../../org/joml/Matrix4x3d.d.ts'
import type { Matrix4x3dc } from '../../org/joml/Matrix4x3dc.d.ts'
import type { Matrix4x3fc } from '../../org/joml/Matrix4x3fc.d.ts'
import type { Quaterniond } from '../../org/joml/Quaterniond.d.ts'
import type { Quaterniondc } from '../../org/joml/Quaterniondc.d.ts'
import type { Quaternionf } from '../../org/joml/Quaternionf.d.ts'
import type { Quaternionfc } from '../../org/joml/Quaternionfc.d.ts'
import type { Vector2dc } from '../../org/joml/Vector2dc.d.ts'
import type { Vector3d } from '../../org/joml/Vector3d.d.ts'
import type { Vector3dc } from '../../org/joml/Vector3dc.d.ts'
import type { Vector3f } from '../../org/joml/Vector3f.d.ts'
import type { Vector3fc } from '../../org/joml/Vector3fc.d.ts'
import type { Vector4d } from '../../org/joml/Vector4d.d.ts'
import type { Vector4dc } from '../../org/joml/Vector4dc.d.ts'
export interface Matrix4dc extends Object{
    add(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    add4x3(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    add4x3(arg0: Matrix4fc, arg1: Matrix4d): Matrix4d;
    arcball(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4d): Matrix4d;
    arcball(arg0: number, arg1: Vector3dc, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    cofactor3x3(arg0: Matrix3d): Matrix3d;
    cofactor3x3(arg0: Matrix4d): Matrix4d;
    determinant(): number;
    determinant3x3(): number;
    determinantAffine(): number;
    equals(arg0: Matrix4dc, arg1: number): boolean;
    fma4x3(arg0: Matrix4dc, arg1: number, arg2: Matrix4d): Matrix4d;
    frustum(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4d): Matrix4d;
    frustum(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4d): Matrix4d;
    frustumCorner(arg0: number, arg1: Vector3d): Vector3d;
    frustumLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4d): Matrix4d;
    frustumLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4d): Matrix4d;
    frustumPlane(arg0: number, arg1: Vector4d): Vector4d;
    frustumRayDir(arg0: number, arg1: number, arg2: Vector3d): Vector3d;
    get(arg0: ByteBuffer): ByteBuffer;
    get(arg0: DoubleBuffer): DoubleBuffer;
    get(arg0: FloatBuffer): FloatBuffer;
    get(arg0: number[]): number[];
    get(arg0: number[], arg1: number): number[];
    get(arg0: number[]): number[];
    get(arg0: number[], arg1: number): number[];
    get(arg0: number, arg1: ByteBuffer): ByteBuffer;
    get(arg0: number, arg1: DoubleBuffer): DoubleBuffer;
    get(arg0: number, arg1: FloatBuffer): FloatBuffer;
    get(arg0: number, arg1: number): number;
    get(arg0: Matrix4d): Matrix4d;
    get3x3(arg0: Matrix3d): Matrix3d;
    get4x3(arg0: Matrix4x3d): Matrix4x3d;
    get4x3Transposed(arg0: ByteBuffer): ByteBuffer;
    get4x3Transposed(arg0: DoubleBuffer): DoubleBuffer;
    get4x3Transposed(arg0: number, arg1: ByteBuffer): ByteBuffer;
    get4x3Transposed(arg0: number, arg1: DoubleBuffer): DoubleBuffer;
    getColumn(arg0: number, arg1: Vector3d): Vector3d;
    getColumn(arg0: number, arg1: Vector4d): Vector4d;
    getEulerAnglesXYZ(arg0: Vector3d): Vector3d;
    getEulerAnglesYXZ(arg0: Vector3d): Vector3d;
    getEulerAnglesZYX(arg0: Vector3d): Vector3d;
    getFloats(arg0: ByteBuffer): ByteBuffer;
    getFloats(arg0: number, arg1: ByteBuffer): ByteBuffer;
    getNormalizedRotation(arg0: Quaterniond): Quaterniond;
    getNormalizedRotation(arg0: Quaternionf): Quaternionf;
    getRow(arg0: number, arg1: Vector3d): Vector3d;
    getRow(arg0: number, arg1: Vector4d): Vector4d;
    getRowColumn(arg0: number, arg1: number): number;
    getScale(arg0: Vector3d): Vector3d;
    getToAddress(arg0: number): Matrix4dc;
    getTranslation(arg0: Vector3d): Vector3d;
    getTransposed(arg0: ByteBuffer): ByteBuffer;
    getTransposed(arg0: DoubleBuffer): DoubleBuffer;
    getTransposed(arg0: FloatBuffer): FloatBuffer;
    getTransposed(arg0: number, arg1: ByteBuffer): ByteBuffer;
    getTransposed(arg0: number, arg1: DoubleBuffer): DoubleBuffer;
    getTransposed(arg0: number, arg1: FloatBuffer): FloatBuffer;
    getTransposedFloats(arg0: ByteBuffer): ByteBuffer;
    getTransposedFloats(arg0: number, arg1: ByteBuffer): ByteBuffer;
    getTransposedToAddress(arg0: number): Matrix4dc;
    getUnnormalizedRotation(arg0: Quaterniond): Quaterniond;
    getUnnormalizedRotation(arg0: Quaternionf): Quaternionf;
    invert(arg0: Matrix4d): Matrix4d;
    invertAffine(arg0: Matrix4d): Matrix4d;
    invertFrustum(arg0: Matrix4d): Matrix4d;
    invertOrtho(arg0: Matrix4d): Matrix4d;
    invertPerspective(arg0: Matrix4d): Matrix4d;
    invertPerspectiveView(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    invertPerspectiveView(arg0: Matrix4x3dc, arg1: Matrix4d): Matrix4d;
    isAffine(): boolean;
    isFinite(): boolean;
    lerp(arg0: Matrix4dc, arg1: number, arg2: Matrix4d): Matrix4d;
    lookAlong(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4d): Matrix4d;
    lookAlong(arg0: Vector3dc, arg1: Vector3dc, arg2: Matrix4d): Matrix4d;
    lookAt(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4d): Matrix4d;
    lookAt(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3dc, arg3: Matrix4d): Matrix4d;
    lookAtLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4d): Matrix4d;
    lookAtLH(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3dc, arg3: Matrix4d): Matrix4d;
    lookAtPerspective(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4d): Matrix4d;
    lookAtPerspectiveLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4d): Matrix4d;
    m00(): number;
    m01(): number;
    m02(): number;
    m03(): number;
    m10(): number;
    m11(): number;
    m12(): number;
    m13(): number;
    m20(): number;
    m21(): number;
    m22(): number;
    m23(): number;
    m30(): number;
    m31(): number;
    m32(): number;
    m33(): number;
    mapXZY(arg0: Matrix4d): Matrix4d;
    mapXZnY(arg0: Matrix4d): Matrix4d;
    mapXnYnZ(arg0: Matrix4d): Matrix4d;
    mapXnZY(arg0: Matrix4d): Matrix4d;
    mapXnZnY(arg0: Matrix4d): Matrix4d;
    mapYXZ(arg0: Matrix4d): Matrix4d;
    mapYXnZ(arg0: Matrix4d): Matrix4d;
    mapYZX(arg0: Matrix4d): Matrix4d;
    mapYZnX(arg0: Matrix4d): Matrix4d;
    mapYnXZ(arg0: Matrix4d): Matrix4d;
    mapYnXnZ(arg0: Matrix4d): Matrix4d;
    mapYnZX(arg0: Matrix4d): Matrix4d;
    mapYnZnX(arg0: Matrix4d): Matrix4d;
    mapZXY(arg0: Matrix4d): Matrix4d;
    mapZXnY(arg0: Matrix4d): Matrix4d;
    mapZYX(arg0: Matrix4d): Matrix4d;
    mapZYnX(arg0: Matrix4d): Matrix4d;
    mapZnXY(arg0: Matrix4d): Matrix4d;
    mapZnXnY(arg0: Matrix4d): Matrix4d;
    mapZnYX(arg0: Matrix4d): Matrix4d;
    mapZnYnX(arg0: Matrix4d): Matrix4d;
    mapnXYnZ(arg0: Matrix4d): Matrix4d;
    mapnXZY(arg0: Matrix4d): Matrix4d;
    mapnXZnY(arg0: Matrix4d): Matrix4d;
    mapnXnYZ(arg0: Matrix4d): Matrix4d;
    mapnXnYnZ(arg0: Matrix4d): Matrix4d;
    mapnXnZY(arg0: Matrix4d): Matrix4d;
    mapnXnZnY(arg0: Matrix4d): Matrix4d;
    mapnYXZ(arg0: Matrix4d): Matrix4d;
    mapnYXnZ(arg0: Matrix4d): Matrix4d;
    mapnYZX(arg0: Matrix4d): Matrix4d;
    mapnYZnX(arg0: Matrix4d): Matrix4d;
    mapnYnXZ(arg0: Matrix4d): Matrix4d;
    mapnYnXnZ(arg0: Matrix4d): Matrix4d;
    mapnYnZX(arg0: Matrix4d): Matrix4d;
    mapnYnZnX(arg0: Matrix4d): Matrix4d;
    mapnZXY(arg0: Matrix4d): Matrix4d;
    mapnZXnY(arg0: Matrix4d): Matrix4d;
    mapnZYX(arg0: Matrix4d): Matrix4d;
    mapnZYnX(arg0: Matrix4d): Matrix4d;
    mapnZnXY(arg0: Matrix4d): Matrix4d;
    mapnZnXnY(arg0: Matrix4d): Matrix4d;
    mapnZnYX(arg0: Matrix4d): Matrix4d;
    mapnZnYnX(arg0: Matrix4d): Matrix4d;
    mul(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number, arg15: number, arg16: Matrix4d): Matrix4d;
    mul(arg0: Matrix3x2dc, arg1: Matrix4d): Matrix4d;
    mul(arg0: Matrix3x2fc, arg1: Matrix4d): Matrix4d;
    mul(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    mul(arg0: Matrix4fc, arg1: Matrix4d): Matrix4d;
    mul(arg0: Matrix4x3dc, arg1: Matrix4d): Matrix4d;
    mul(arg0: Matrix4x3fc, arg1: Matrix4d): Matrix4d;
    mul0(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    mul3x3(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: Matrix4d): Matrix4d;
    mul4x3ComponentWise(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    mulAffine(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    mulAffineR(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    mulComponentWise(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    mulLocal(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    mulLocalAffine(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    mulOrthoAffine(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    mulPerspectiveAffine(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    mulPerspectiveAffine(arg0: Matrix4x3dc, arg1: Matrix4d): Matrix4d;
    mulTranslationAffine(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    negateX(arg0: Matrix4d): Matrix4d;
    negateY(arg0: Matrix4d): Matrix4d;
    negateZ(arg0: Matrix4d): Matrix4d;
    normal(arg0: Matrix3d): Matrix3d;
    normal(arg0: Matrix4d): Matrix4d;
    normalize3x3(arg0: Matrix3d): Matrix3d;
    normalize3x3(arg0: Matrix4d): Matrix4d;
    normalizedPositiveX(arg0: Vector3d): Vector3d;
    normalizedPositiveY(arg0: Vector3d): Vector3d;
    normalizedPositiveZ(arg0: Vector3d): Vector3d;
    obliqueZ(arg0: number, arg1: number, arg2: Matrix4d): Matrix4d;
    origin(arg0: Vector3d): Vector3d;
    originAffine(arg0: Vector3d): Vector3d;
    ortho(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4d): Matrix4d;
    ortho(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4d): Matrix4d;
    ortho2D(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    ortho2DLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    orthoCrop(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    orthoLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4d): Matrix4d;
    orthoLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4d): Matrix4d;
    orthoSymmetric(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean, arg5: Matrix4d): Matrix4d;
    orthoSymmetric(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    orthoSymmetricLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean, arg5: Matrix4d): Matrix4d;
    orthoSymmetricLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    perspective(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean, arg5: Matrix4d): Matrix4d;
    perspective(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    perspectiveFar(): number;
    perspectiveFov(): number;
    perspectiveFrustumSlice(arg0: number, arg1: number, arg2: Matrix4d): Matrix4d;
    perspectiveInvOrigin(arg0: Vector3d): Vector3d;
    perspectiveLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean, arg5: Matrix4d): Matrix4d;
    perspectiveLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    perspectiveNear(): number;
    perspectiveOffCenter(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4d): Matrix4d;
    perspectiveOffCenter(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4d): Matrix4d;
    perspectiveOffCenterFov(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4d): Matrix4d;
    perspectiveOffCenterFov(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4d): Matrix4d;
    perspectiveOffCenterFovLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean, arg7: Matrix4d): Matrix4d;
    perspectiveOffCenterFovLH(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4d): Matrix4d;
    perspectiveOrigin(arg0: Vector3d): Vector3d;
    perspectiveRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean, arg5: Matrix4d): Matrix4d;
    perspectiveRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    pick(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number[], arg5: Matrix4d): Matrix4d;
    positiveX(arg0: Vector3d): Vector3d;
    positiveY(arg0: Vector3d): Vector3d;
    positiveZ(arg0: Vector3d): Vector3d;
    project(arg0: number, arg1: number, arg2: number, arg3: number[], arg4: Vector3d): Vector3d;
    project(arg0: number, arg1: number, arg2: number, arg3: number[], arg4: Vector4d): Vector4d;
    project(arg0: Vector3dc, arg1: number[], arg2: Vector3d): Vector3d;
    project(arg0: Vector3dc, arg1: number[], arg2: Vector4d): Vector4d;
    projectedGridRange(arg0: Matrix4dc, arg1: number, arg2: number, arg3: Matrix4d): Matrix4d;
    properties(): number;
    reflect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4d): Matrix4d;
    reflect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    reflect(arg0: Quaterniondc, arg1: Vector3dc, arg2: Matrix4d): Matrix4d;
    reflect(arg0: Vector3dc, arg1: Vector3dc, arg2: Matrix4d): Matrix4d;
    rotate(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    rotate(arg0: number, arg1: Vector3dc, arg2: Matrix4d): Matrix4d;
    rotate(arg0: number, arg1: Vector3fc, arg2: Matrix4d): Matrix4d;
    rotate(arg0: AxisAngle4d, arg1: Matrix4d): Matrix4d;
    rotate(arg0: AxisAngle4f, arg1: Matrix4d): Matrix4d;
    rotate(arg0: Quaterniondc, arg1: Matrix4d): Matrix4d;
    rotate(arg0: Quaternionfc, arg1: Matrix4d): Matrix4d;
    rotateAffine(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    rotateAffine(arg0: Quaterniondc, arg1: Matrix4d): Matrix4d;
    rotateAffine(arg0: Quaternionfc, arg1: Matrix4d): Matrix4d;
    rotateAffineXYZ(arg0: number, arg1: number, arg2: number, arg3: Matrix4d): Matrix4d;
    rotateAffineYXZ(arg0: number, arg1: number, arg2: number, arg3: Matrix4d): Matrix4d;
    rotateAffineZYX(arg0: number, arg1: number, arg2: number, arg3: Matrix4d): Matrix4d;
    rotateAround(arg0: Quaterniondc, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    rotateAroundAffine(arg0: Quaterniondc, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    rotateAroundLocal(arg0: Quaterniondc, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    rotateLocal(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    rotateLocal(arg0: Quaterniondc, arg1: Matrix4d): Matrix4d;
    rotateLocal(arg0: Quaternionfc, arg1: Matrix4d): Matrix4d;
    rotateLocalX(arg0: number, arg1: Matrix4d): Matrix4d;
    rotateLocalY(arg0: number, arg1: Matrix4d): Matrix4d;
    rotateLocalZ(arg0: number, arg1: Matrix4d): Matrix4d;
    rotateTowards(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4d): Matrix4d;
    rotateTowards(arg0: Vector3dc, arg1: Vector3dc, arg2: Matrix4d): Matrix4d;
    rotateTowardsXY(arg0: number, arg1: number, arg2: Matrix4d): Matrix4d;
    rotateTranslation(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    rotateTranslation(arg0: Quaterniondc, arg1: Matrix4d): Matrix4d;
    rotateTranslation(arg0: Quaternionfc, arg1: Matrix4d): Matrix4d;
    rotateX(arg0: number, arg1: Matrix4d): Matrix4d;
    rotateXYZ(arg0: number, arg1: number, arg2: number, arg3: Matrix4d): Matrix4d;
    rotateY(arg0: number, arg1: Matrix4d): Matrix4d;
    rotateYXZ(arg0: number, arg1: number, arg2: number, arg3: Matrix4d): Matrix4d;
    rotateZ(arg0: number, arg1: Matrix4d): Matrix4d;
    rotateZYX(arg0: number, arg1: number, arg2: number, arg3: Matrix4d): Matrix4d;
    scale(arg0: number, arg1: number, arg2: number, arg3: Matrix4d): Matrix4d;
    scale(arg0: number, arg1: Matrix4d): Matrix4d;
    scale(arg0: Vector3dc, arg1: Matrix4d): Matrix4d;
    scaleAround(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4d): Matrix4d;
    scaleAround(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    scaleAroundLocal(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Matrix4d): Matrix4d;
    scaleAroundLocal(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    scaleLocal(arg0: number, arg1: number, arg2: number, arg3: Matrix4d): Matrix4d;
    scaleLocal(arg0: number, arg1: Matrix4d): Matrix4d;
    scaleXY(arg0: number, arg1: number, arg2: Matrix4d): Matrix4d;
    shadow(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: Matrix4d): Matrix4d;
    shadow(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4dc, arg5: Matrix4d): Matrix4d;
    shadow(arg0: Vector4dc, arg1: number, arg2: number, arg3: number, arg4: number, arg5: Matrix4d): Matrix4d;
    shadow(arg0: Vector4dc, arg1: Matrix4dc, arg2: Matrix4d): Matrix4d;
    sub(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    sub4x3(arg0: Matrix4dc, arg1: Matrix4d): Matrix4d;
    testAab(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): boolean;
    testPoint(arg0: number, arg1: number, arg2: number): boolean;
    testSphere(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
    tile(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Matrix4d): Matrix4d;
    transform(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Vector4d): Vector4d;
    transform(arg0: Vector4d): Vector4d;
    transform(arg0: Vector4dc, arg1: Vector4d): Vector4d;
    transformAab(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: Vector3d, arg7: Vector3d): Matrix4d;
    transformAab(arg0: Vector3dc, arg1: Vector3dc, arg2: Vector3d, arg3: Vector3d): Matrix4d;
    transformAffine(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Vector4d): Vector4d;
    transformAffine(arg0: Vector4d): Vector4d;
    transformAffine(arg0: Vector4dc, arg1: Vector4d): Vector4d;
    transformDirection(arg0: number, arg1: number, arg2: number, arg3: Vector3d): Vector3d;
    transformDirection(arg0: number, arg1: number, arg2: number, arg3: Vector3f): Vector3f;
    transformDirection(arg0: Vector3d): Vector3d;
    transformDirection(arg0: Vector3dc, arg1: Vector3d): Vector3d;
    transformDirection(arg0: Vector3f): Vector3f;
    transformDirection(arg0: Vector3fc, arg1: Vector3f): Vector3f;
    transformPosition(arg0: number, arg1: number, arg2: number, arg3: Vector3d): Vector3d;
    transformPosition(arg0: Vector3d): Vector3d;
    transformPosition(arg0: Vector3dc, arg1: Vector3d): Vector3d;
    transformProject(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Vector3d): Vector3d;
    transformProject(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Vector4d): Vector4d;
    transformProject(arg0: number, arg1: number, arg2: number, arg3: Vector3d): Vector3d;
    transformProject(arg0: Vector3d): Vector3d;
    transformProject(arg0: Vector3dc, arg1: Vector3d): Vector3d;
    transformProject(arg0: Vector4d): Vector4d;
    transformProject(arg0: Vector4dc, arg1: Vector3d): Vector3d;
    transformProject(arg0: Vector4dc, arg1: Vector4d): Vector4d;
    transformTranspose(arg0: number, arg1: number, arg2: number, arg3: number, arg4: Vector4d): Vector4d;
    transformTranspose(arg0: Vector4d): Vector4d;
    transformTranspose(arg0: Vector4dc, arg1: Vector4d): Vector4d;
    translate(arg0: number, arg1: number, arg2: number, arg3: Matrix4d): Matrix4d;
    translate(arg0: Vector3dc, arg1: Matrix4d): Matrix4d;
    translate(arg0: Vector3fc, arg1: Matrix4d): Matrix4d;
    translateLocal(arg0: number, arg1: number, arg2: number, arg3: Matrix4d): Matrix4d;
    translateLocal(arg0: Vector3dc, arg1: Matrix4d): Matrix4d;
    translateLocal(arg0: Vector3fc, arg1: Matrix4d): Matrix4d;
    transpose(arg0: Matrix4d): Matrix4d;
    transpose3x3(arg0: Matrix3d): Matrix3d;
    transpose3x3(arg0: Matrix4d): Matrix4d;
    unproject(arg0: number, arg1: number, arg2: number, arg3: number[], arg4: Vector3d): Vector3d;
    unproject(arg0: number, arg1: number, arg2: number, arg3: number[], arg4: Vector4d): Vector4d;
    unproject(arg0: Vector3dc, arg1: number[], arg2: Vector3d): Vector3d;
    unproject(arg0: Vector3dc, arg1: number[], arg2: Vector4d): Vector4d;
    unprojectInv(arg0: number, arg1: number, arg2: number, arg3: number[], arg4: Vector3d): Vector3d;
    unprojectInv(arg0: number, arg1: number, arg2: number, arg3: number[], arg4: Vector4d): Vector4d;
    unprojectInv(arg0: Vector3dc, arg1: number[], arg2: Vector3d): Vector3d;
    unprojectInv(arg0: Vector3dc, arg1: number[], arg2: Vector4d): Vector4d;
    unprojectInvRay(arg0: number, arg1: number, arg2: number[], arg3: Vector3d, arg4: Vector3d): Matrix4d;
    unprojectInvRay(arg0: Vector2dc, arg1: number[], arg2: Vector3d, arg3: Vector3d): Matrix4d;
    unprojectRay(arg0: number, arg1: number, arg2: number[], arg3: Vector3d, arg4: Vector3d): Matrix4d;
    unprojectRay(arg0: Vector2dc, arg1: number[], arg2: Vector3d, arg3: Vector3d): Matrix4d;
    withLookAtUp(arg0: number, arg1: number, arg2: number, arg3: Matrix4d): Matrix4d;
    withLookAtUp(arg0: Vector3dc, arg1: Matrix4d): Matrix4d;
}