import type { App } from '../../../../com/mojang/datafixers/kinds/App.d.ts'
import type { Applicative } from '../../../../com/mojang/datafixers/kinds/Applicative.d.ts'
import type { Function10 } from '../../../../com/mojang/datafixers/util/Function10.d.ts'
import type { Function11 } from '../../../../com/mojang/datafixers/util/Function11.d.ts'
import type { Function12 } from '../../../../com/mojang/datafixers/util/Function12.d.ts'
import type { Function13 } from '../../../../com/mojang/datafixers/util/Function13.d.ts'
import type { Function14 } from '../../../../com/mojang/datafixers/util/Function14.d.ts'
import type { Function15 } from '../../../../com/mojang/datafixers/util/Function15.d.ts'
import type { Function16 } from '../../../../com/mojang/datafixers/util/Function16.d.ts'
import type { Function3 } from '../../../../com/mojang/datafixers/util/Function3.d.ts'
import type { Function4 } from '../../../../com/mojang/datafixers/util/Function4.d.ts'
import type { Function5 } from '../../../../com/mojang/datafixers/util/Function5.d.ts'
import type { Function6 } from '../../../../com/mojang/datafixers/util/Function6.d.ts'
import type { Function7 } from '../../../../com/mojang/datafixers/util/Function7.d.ts'
import type { Function8 } from '../../../../com/mojang/datafixers/util/Function8.d.ts'
import type { Function9 } from '../../../../com/mojang/datafixers/util/Function9.d.ts'
import type { Lifecycle } from '../../../../com/mojang/serialization/Lifecycle.d.ts'
import type { RecordCodecBuilder$Instance$Mu } from '../../../../com/mojang/serialization/codecs/RecordCodecBuilder$Instance$Mu.d.ts'
import type { RecordCodecBuilder$Mu } from '../../../../com/mojang/serialization/codecs/RecordCodecBuilder$Mu.d.ts'
import type { BiFunction } from '../../../../java/util/function/BiFunction.d.ts'
import type { Function } from '../../../../java/util/function/Function.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
export class RecordCodecBuilder$Instance<O extends unknown> extends Object implements Applicative<RecordCodecBuilder$Mu<O>, RecordCodecBuilder$Instance$Mu<O>> {
    constructor()
    ap<R extends unknown, A extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, (param0: A) => R>, arg1: App<RecordCodecBuilder$Mu<O>, A>): App<RecordCodecBuilder$Mu<O>, R>;
    ap<R extends unknown, A extends unknown>(arg0: (param0: A) => R, arg1: App<RecordCodecBuilder$Mu<O>, A>): App<RecordCodecBuilder$Mu<O>, R>;
    ap10<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>, arg7: App<RecordCodecBuilder$Mu<O>, T7>, arg8: App<RecordCodecBuilder$Mu<O>, T8>, arg9: App<RecordCodecBuilder$Mu<O>, T9>, arg10: App<RecordCodecBuilder$Mu<O>, T10>): App<RecordCodecBuilder$Mu<O>, R>;
    ap11<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>, arg7: App<RecordCodecBuilder$Mu<O>, T7>, arg8: App<RecordCodecBuilder$Mu<O>, T8>, arg9: App<RecordCodecBuilder$Mu<O>, T9>, arg10: App<RecordCodecBuilder$Mu<O>, T10>, arg11: App<RecordCodecBuilder$Mu<O>, T11>): App<RecordCodecBuilder$Mu<O>, R>;
    ap12<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown, T12 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>, arg7: App<RecordCodecBuilder$Mu<O>, T7>, arg8: App<RecordCodecBuilder$Mu<O>, T8>, arg9: App<RecordCodecBuilder$Mu<O>, T9>, arg10: App<RecordCodecBuilder$Mu<O>, T10>, arg11: App<RecordCodecBuilder$Mu<O>, T11>, arg12: App<RecordCodecBuilder$Mu<O>, T12>): App<RecordCodecBuilder$Mu<O>, R>;
    ap13<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown, T12 extends unknown, T13 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>, arg7: App<RecordCodecBuilder$Mu<O>, T7>, arg8: App<RecordCodecBuilder$Mu<O>, T8>, arg9: App<RecordCodecBuilder$Mu<O>, T9>, arg10: App<RecordCodecBuilder$Mu<O>, T10>, arg11: App<RecordCodecBuilder$Mu<O>, T11>, arg12: App<RecordCodecBuilder$Mu<O>, T12>, arg13: App<RecordCodecBuilder$Mu<O>, T13>): App<RecordCodecBuilder$Mu<O>, R>;
    ap14<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown, T12 extends unknown, T13 extends unknown, T14 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>, arg7: App<RecordCodecBuilder$Mu<O>, T7>, arg8: App<RecordCodecBuilder$Mu<O>, T8>, arg9: App<RecordCodecBuilder$Mu<O>, T9>, arg10: App<RecordCodecBuilder$Mu<O>, T10>, arg11: App<RecordCodecBuilder$Mu<O>, T11>, arg12: App<RecordCodecBuilder$Mu<O>, T12>, arg13: App<RecordCodecBuilder$Mu<O>, T13>, arg14: App<RecordCodecBuilder$Mu<O>, T14>): App<RecordCodecBuilder$Mu<O>, R>;
    ap15<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown, T12 extends unknown, T13 extends unknown, T14 extends unknown, T15 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>, arg7: App<RecordCodecBuilder$Mu<O>, T7>, arg8: App<RecordCodecBuilder$Mu<O>, T8>, arg9: App<RecordCodecBuilder$Mu<O>, T9>, arg10: App<RecordCodecBuilder$Mu<O>, T10>, arg11: App<RecordCodecBuilder$Mu<O>, T11>, arg12: App<RecordCodecBuilder$Mu<O>, T12>, arg13: App<RecordCodecBuilder$Mu<O>, T13>, arg14: App<RecordCodecBuilder$Mu<O>, T14>, arg15: App<RecordCodecBuilder$Mu<O>, T15>): App<RecordCodecBuilder$Mu<O>, R>;
    ap16<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, T10 extends unknown, T11 extends unknown, T12 extends unknown, T13 extends unknown, T14 extends unknown, T15 extends unknown, T16 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>, arg7: App<RecordCodecBuilder$Mu<O>, T7>, arg8: App<RecordCodecBuilder$Mu<O>, T8>, arg9: App<RecordCodecBuilder$Mu<O>, T9>, arg10: App<RecordCodecBuilder$Mu<O>, T10>, arg11: App<RecordCodecBuilder$Mu<O>, T11>, arg12: App<RecordCodecBuilder$Mu<O>, T12>, arg13: App<RecordCodecBuilder$Mu<O>, T13>, arg14: App<RecordCodecBuilder$Mu<O>, T14>, arg15: App<RecordCodecBuilder$Mu<O>, T15>, arg16: App<RecordCodecBuilder$Mu<O>, T16>): App<RecordCodecBuilder$Mu<O>, R>;
    ap2<R extends unknown, A extends unknown, B extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, (param0: A, param1: B) => R>, arg1: App<RecordCodecBuilder$Mu<O>, A>, arg2: App<RecordCodecBuilder$Mu<O>, B>): App<RecordCodecBuilder$Mu<O>, R>;
    ap3<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function3<T1, T2, T3, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>): App<RecordCodecBuilder$Mu<O>, R>;
    ap4<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function4<T1, T2, T3, T4, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>): App<RecordCodecBuilder$Mu<O>, R>;
    ap5<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function5<T1, T2, T3, T4, T5, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>): App<RecordCodecBuilder$Mu<O>, R>;
    ap6<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function6<T1, T2, T3, T4, T5, T6, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>): App<RecordCodecBuilder$Mu<O>, R>;
    ap7<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function7<T1, T2, T3, T4, T5, T6, T7, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>, arg7: App<RecordCodecBuilder$Mu<O>, T7>): App<RecordCodecBuilder$Mu<O>, R>;
    ap8<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>, arg7: App<RecordCodecBuilder$Mu<O>, T7>, arg8: App<RecordCodecBuilder$Mu<O>, T8>): App<RecordCodecBuilder$Mu<O>, R>;
    ap9<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>, arg7: App<RecordCodecBuilder$Mu<O>, T7>, arg8: App<RecordCodecBuilder$Mu<O>, T8>, arg9: App<RecordCodecBuilder$Mu<O>, T9>): App<RecordCodecBuilder$Mu<O>, R>;
    apply2<R extends unknown, A extends unknown, B extends unknown>(arg0: (param0: A, param1: B) => R, arg1: App<RecordCodecBuilder$Mu<O>, A>, arg2: App<RecordCodecBuilder$Mu<O>, B>): App<RecordCodecBuilder$Mu<O>, R>;
    apply3<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown>(arg0: Function3<T1, T2, T3, R>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>): App<RecordCodecBuilder$Mu<O>, R>;
    apply4<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown>(arg0: Function4<T1, T2, T3, T4, R>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>): App<RecordCodecBuilder$Mu<O>, R>;
    apply5<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown>(arg0: Function5<T1, T2, T3, T4, T5, R>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>): App<RecordCodecBuilder$Mu<O>, R>;
    apply6<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown>(arg0: Function6<T1, T2, T3, T4, T5, T6, R>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>): App<RecordCodecBuilder$Mu<O>, R>;
    apply7<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown>(arg0: Function7<T1, T2, T3, T4, T5, T6, T7, R>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>, arg7: App<RecordCodecBuilder$Mu<O>, T7>): App<RecordCodecBuilder$Mu<O>, R>;
    apply8<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown>(arg0: Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>, arg7: App<RecordCodecBuilder$Mu<O>, T7>, arg8: App<RecordCodecBuilder$Mu<O>, T8>): App<RecordCodecBuilder$Mu<O>, R>;
    apply9<R extends unknown, T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown>(arg0: Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>, arg1: App<RecordCodecBuilder$Mu<O>, T1>, arg2: App<RecordCodecBuilder$Mu<O>, T2>, arg3: App<RecordCodecBuilder$Mu<O>, T3>, arg4: App<RecordCodecBuilder$Mu<O>, T4>, arg5: App<RecordCodecBuilder$Mu<O>, T5>, arg6: App<RecordCodecBuilder$Mu<O>, T6>, arg7: App<RecordCodecBuilder$Mu<O>, T7>, arg8: App<RecordCodecBuilder$Mu<O>, T8>, arg9: App<RecordCodecBuilder$Mu<O>, T9>): App<RecordCodecBuilder$Mu<O>, R>;
    deprecated<A extends unknown>(arg0: A, arg1: number): App<RecordCodecBuilder$Mu<O>, A>;
    lift1<A extends unknown, R extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, (param0: A) => R>): (param0: App<RecordCodecBuilder$Mu<O>, A>) => App<RecordCodecBuilder$Mu<O>, R>;
    lift2<A extends unknown, B extends unknown, R extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, (param0: A, param1: B) => R>): (param0: App<RecordCodecBuilder$Mu<O>, A>, param1: App<RecordCodecBuilder$Mu<O>, B>) => App<RecordCodecBuilder$Mu<O>, R>;
    lift3<T1 extends unknown, T2 extends unknown, T3 extends unknown, R extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function3<T1, T2, T3, R>>): Function3<App<RecordCodecBuilder$Mu<O>, T1>, App<RecordCodecBuilder$Mu<O>, T2>, App<RecordCodecBuilder$Mu<O>, T3>, App<RecordCodecBuilder$Mu<O>, R>>;
    lift4<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, R extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function4<T1, T2, T3, T4, R>>): Function4<App<RecordCodecBuilder$Mu<O>, T1>, App<RecordCodecBuilder$Mu<O>, T2>, App<RecordCodecBuilder$Mu<O>, T3>, App<RecordCodecBuilder$Mu<O>, T4>, App<RecordCodecBuilder$Mu<O>, R>>;
    lift5<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, R extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function5<T1, T2, T3, T4, T5, R>>): Function5<App<RecordCodecBuilder$Mu<O>, T1>, App<RecordCodecBuilder$Mu<O>, T2>, App<RecordCodecBuilder$Mu<O>, T3>, App<RecordCodecBuilder$Mu<O>, T4>, App<RecordCodecBuilder$Mu<O>, T5>, App<RecordCodecBuilder$Mu<O>, R>>;
    lift6<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, R extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function6<T1, T2, T3, T4, T5, T6, R>>): Function6<App<RecordCodecBuilder$Mu<O>, T1>, App<RecordCodecBuilder$Mu<O>, T2>, App<RecordCodecBuilder$Mu<O>, T3>, App<RecordCodecBuilder$Mu<O>, T4>, App<RecordCodecBuilder$Mu<O>, T5>, App<RecordCodecBuilder$Mu<O>, T6>, App<RecordCodecBuilder$Mu<O>, R>>;
    lift7<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, R extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function7<T1, T2, T3, T4, T5, T6, T7, R>>): Function7<App<RecordCodecBuilder$Mu<O>, T1>, App<RecordCodecBuilder$Mu<O>, T2>, App<RecordCodecBuilder$Mu<O>, T3>, App<RecordCodecBuilder$Mu<O>, T4>, App<RecordCodecBuilder$Mu<O>, T5>, App<RecordCodecBuilder$Mu<O>, T6>, App<RecordCodecBuilder$Mu<O>, T7>, App<RecordCodecBuilder$Mu<O>, R>>;
    lift8<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, R extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function8<T1, T2, T3, T4, T5, T6, T7, T8, R>>): Function8<App<RecordCodecBuilder$Mu<O>, T1>, App<RecordCodecBuilder$Mu<O>, T2>, App<RecordCodecBuilder$Mu<O>, T3>, App<RecordCodecBuilder$Mu<O>, T4>, App<RecordCodecBuilder$Mu<O>, T5>, App<RecordCodecBuilder$Mu<O>, T6>, App<RecordCodecBuilder$Mu<O>, T7>, App<RecordCodecBuilder$Mu<O>, T8>, App<RecordCodecBuilder$Mu<O>, R>>;
    lift9<T1 extends unknown, T2 extends unknown, T3 extends unknown, T4 extends unknown, T5 extends unknown, T6 extends unknown, T7 extends unknown, T8 extends unknown, T9 extends unknown, R extends unknown>(arg0: App<RecordCodecBuilder$Mu<O>, Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R>>): Function9<App<RecordCodecBuilder$Mu<O>, T1>, App<RecordCodecBuilder$Mu<O>, T2>, App<RecordCodecBuilder$Mu<O>, T3>, App<RecordCodecBuilder$Mu<O>, T4>, App<RecordCodecBuilder$Mu<O>, T5>, App<RecordCodecBuilder$Mu<O>, T6>, App<RecordCodecBuilder$Mu<O>, T7>, App<RecordCodecBuilder$Mu<O>, T8>, App<RecordCodecBuilder$Mu<O>, T9>, App<RecordCodecBuilder$Mu<O>, R>>;
    map<R extends unknown, T extends unknown>(arg0: (param0: T) => R, arg1: App<RecordCodecBuilder$Mu<O>, T>): App<RecordCodecBuilder$Mu<O>, R>;
    point<A extends unknown>(arg0: A): App<RecordCodecBuilder$Mu<O>, A>;
    point<A extends unknown>(arg0: A, arg1: Lifecycle): App<RecordCodecBuilder$Mu<O>, A>;
    stable<A extends unknown>(arg0: A): App<RecordCodecBuilder$Mu<O>, A>;
}