import type { Device } from '../../../../ai/djl/Device.d.ts'
import type { NDArray } from '../../../../ai/djl/ndarray/NDArray.d.ts'
import type { NDManager } from '../../../../ai/djl/ndarray/NDManager.d.ts'
import type { NDIndex } from '../../../../ai/djl/ndarray/index/NDIndex.d.ts'
import type { DataType } from '../../../../ai/djl/ndarray/types/DataType.d.ts'
import type { Shape } from '../../../../ai/djl/ndarray/types/Shape.d.ts'
import type { SparseFormat } from '../../../../ai/djl/ndarray/types/SparseFormat.d.ts'
import type { PtNDArrayEx } from '../../../../ai/djl/pytorch/engine/PtNDArrayEx.d.ts'
import type { PtNDManager } from '../../../../ai/djl/pytorch/engine/PtNDManager.d.ts'
import type { NativeResource } from '../../../../ai/djl/util/NativeResource.d.ts'
import type { Buffer } from '../../../../java/nio/Buffer.d.ts'
import type { ByteBuffer } from '../../../../java/nio/ByteBuffer.d.ts'
import type { Charset } from '../../../../java/nio/charset/Charset.d.ts'
import type { Function } from '../../../../java/util/function/Function.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { Number } from '../../../../java/lang/Number.d.ts'
export class PtNDArray extends NativeResource<number> implements NDArray {
    static decode(paramarg0: NDManager, paramarg1: number[]): NDArray;
    constructor(arg0: PtNDManager, arg1: string[], arg2: Shape)
    constructor(arg0: PtNDManager, arg1: number)
    constructor(arg0: PtNDManager, arg1: number, arg2: ByteBuffer)
    // private dataRef: ByteBuffer;
    readonly dataType: DataType;
    readonly device: Device;
    // private hasGradient: boolean;
    readonly manager: PtNDManager;
    readonly name: string;
    // private ptNDArrayEx: PtNDArrayEx;
    readonly shape: Shape;
    readonly sparseFormat: SparseFormat;
    // private strs: string[];
    abs(): PtNDArray;
    acos(): PtNDArray;
    acosh(): PtNDArray;
    add(arg0: NDArray): PtNDArray;
    add(arg0: Number): PtNDArray;
    addi(arg0: NDArray): PtNDArray;
    addi(arg0: Number): PtNDArray;
    all(): NDArray;
    all(): PtNDArray;
    allClose(arg0: NDArray): boolean;
    allClose(arg0: NDArray, arg1: number, arg2: number, arg3: boolean): boolean;
    any(): NDArray;
    any(): PtNDArray;
    argMax(): PtNDArray;
    argMax(arg0: number): PtNDArray;
    argMin(): PtNDArray;
    argMin(arg0: number): PtNDArray;
    argSort(): NDArray;
    argSort(arg0: number): NDArray;
    argSort(arg0: number, arg1: boolean): PtNDArray;
    asin(): PtNDArray;
    asinh(): PtNDArray;
    atan(): PtNDArray;
    atan2(arg0: NDArray): PtNDArray;
    atanh(): PtNDArray;
    attach(arg0: NDManager): void;
    batchDot(arg0: NDArray): NDArray;
    batchMatMul(arg0: NDArray): NDArray;
    booleanMask(arg0: NDArray): NDArray;
    booleanMask(arg0: NDArray, arg1: number): PtNDArray;
    broadcast(...arg0: number[]): NDArray;
    broadcast(arg0: Shape): PtNDArray;
    cbrt(): PtNDArray;
    ceil(): PtNDArray;
    clip(arg0: Number, arg1: Number): PtNDArray;
    close(): void;
    complex(): NDArray;
    concat(arg0: NDArray): NDArray;
    concat(arg0: NDArray, arg1: number): NDArray;
    conj(): NDArray;
    contentEquals(arg0: NDArray): boolean;
    contentEquals(arg0: Number): boolean;
    copyTo(arg0: NDArray): void;
    cos(): PtNDArray;
    cosh(): PtNDArray;
    countNonzero(): NDArray;
    countNonzero(arg0: number): NDArray;
    cumProd(arg0: number): NDArray;
    cumProd(arg0: number, arg1: DataType): NDArray;
    cumSum(): PtNDArray;
    cumSum(arg0: number): PtNDArray;
    detach(): void;
    diagonal(): NDArray;
    diagonal(arg0: number): NDArray;
    diagonal(arg0: number, arg1: number, arg2: number): NDArray;
    diff(arg0: number, arg1: number): NDArray;
    div(arg0: NDArray): PtNDArray;
    div(arg0: Number): PtNDArray;
    divi(arg0: NDArray): PtNDArray;
    divi(arg0: Number): PtNDArray;
    dot(arg0: NDArray): PtNDArray;
    duplicate(): NDArray;
    encode(): number[];
    eq(arg0: NDArray): PtNDArray;
    eq(arg0: Number): PtNDArray;
    equals(arg0: Object | null): boolean;
    erf(): PtNDArray;
    erfinv(): PtNDArray;
    exp(): PtNDArray;
    expandDims(arg0: number): PtNDArray;
    fft(arg0: number): NDArray;
    fft(arg0: number, arg1: number): NDArray;
    fft2(arg0: number[]): NDArray;
    fft2(arg0: number[], arg1: number[]): NDArray;
    flatten(): PtNDArray;
    flatten(arg0: number, arg1: number): NDArray;
    flip(...arg0: number[]): NDArray;
    floor(): PtNDArray;
    gammaln(): NDArray;
    gather(arg0: NDArray, arg1: number): NDArray;
    gatherNd(arg0: NDArray): NDArray;
    get(arg0: NDArray): NDArray;
    get(arg0: NDManager, arg1: NDIndex): NDArray;
    get(arg0: NDManager, ...arg1: number[]): NDArray;
    get(arg0: NDIndex): NDArray;
    get(...arg0: number[]): NDArray;
    get(arg0: string, ...arg1: Object[]): NDArray;
    getBoolean(...arg0: number[]): boolean;
    getByte(...arg0: number[]): number;
    getDataType(): DataType;
    getDevice(): Device;
    getDouble(...arg0: number[]): number;
    getFloat(...arg0: number[]): number;
    getGradient(): PtNDArray;
    getInt(...arg0: number[]): number;
    getLong(...arg0: number[]): number;
    getManager(): PtNDManager;
    getNDArrayInternal(): PtNDArrayEx;
    getName(): string;
    getResourceNDArrays(): NDArray[];
    getScalar(...arg0: number[]): NDArray;
    getShape(): Shape;
    getSparseFormat(): SparseFormat;
    getUint8(...arg0: number[]): number;
    gt(arg0: NDArray): PtNDArray;
    gt(arg0: Number): PtNDArray;
    gte(arg0: NDArray): PtNDArray;
    gte(arg0: Number): PtNDArray;
    hasGradient(): boolean;
    hashCode(): number;
    ifft(arg0: number): NDArray;
    ifft(arg0: number, arg1: number): NDArray;
    ifft2(arg0: number[]): NDArray;
    ifft2(arg0: number[], arg1: number[]): NDArray;
    intern(arg0: NDArray): void;
    inverse(): PtNDArray;
    irfft(arg0: number): NDArray;
    irfft(arg0: number, arg1: number): NDArray;
    isEmpty(): boolean;
    isInfinite(): PtNDArray;
    isNaN(): PtNDArray;
    isScalar(): boolean;
    isSparse(): boolean;
    like(): NDArray;
    log(): PtNDArray;
    log10(): PtNDArray;
    log2(): PtNDArray;
    logSoftmax(arg0: number): PtNDArray;
    logicalAnd(arg0: NDArray): PtNDArray;
    logicalNot(): PtNDArray;
    logicalOr(arg0: NDArray): PtNDArray;
    logicalXor(arg0: NDArray): PtNDArray;
    lt(arg0: NDArray): PtNDArray;
    lt(arg0: Number): PtNDArray;
    lte(arg0: NDArray): PtNDArray;
    lte(arg0: Number): PtNDArray;
    matMul(arg0: NDArray): NDArray;
    max(arg0: number[]): NDArray;
    max(): PtNDArray;
    max(arg0: number[], arg1: boolean): PtNDArray;
    maximum(arg0: NDArray): PtNDArray;
    maximum(arg0: Number): PtNDArray;
    mean(arg0: number[]): NDArray;
    mean(): PtNDArray;
    mean(arg0: number[], arg1: boolean): PtNDArray;
    median(): PtNDArray;
    median(arg0: number[]): PtNDArray;
    min(arg0: number[]): NDArray;
    min(): PtNDArray;
    min(arg0: number[], arg1: boolean): PtNDArray;
    minimum(arg0: NDArray): PtNDArray;
    minimum(arg0: Number): PtNDArray;
    mod(arg0: NDArray): PtNDArray;
    mod(arg0: Number): PtNDArray;
    modi(arg0: NDArray): PtNDArray;
    modi(arg0: Number): PtNDArray;
    mul(arg0: NDArray): PtNDArray;
    mul(arg0: Number): PtNDArray;
    muli(arg0: NDArray): PtNDArray;
    muli(arg0: Number): PtNDArray;
    neg(): PtNDArray;
    negi(): PtNDArray;
    neq(arg0: NDArray): PtNDArray;
    neq(arg0: Number): PtNDArray;
    none(): NDArray;
    none(): PtNDArray;
    nonzero(): PtNDArray;
    norm(): NDArray;
    norm(arg0: number[]): NDArray;
    norm(arg0: number[], arg1: boolean): NDArray;
    norm(arg0: boolean): NDArray;
    norm(arg0: number, arg1: number[], arg2: boolean): NDArray;
    normalize(): NDArray;
    normalize(arg0: number, arg1: number): NDArray;
    normalize(arg0: number, arg1: number, arg2: number): PtNDArray;
    oneHot(arg0: number): NDArray;
    oneHot(arg0: number, arg1: DataType): NDArray;
    oneHot(arg0: number, arg1: number, arg2: number, arg3: DataType): NDArray;
    onesLike(): NDArray;
    pad(arg0: Shape, arg1: number): NDArray;
    percentile(arg0: Number): PtNDArray;
    percentile(arg0: Number, arg1: number[]): PtNDArray;
    pow(arg0: NDArray): PtNDArray;
    pow(arg0: Number): PtNDArray;
    powi(arg0: NDArray): PtNDArray;
    powi(arg0: Number): PtNDArray;
    prod(arg0: number[]): NDArray;
    prod(): PtNDArray;
    prod(arg0: number[], arg1: boolean): PtNDArray;
    put(arg0: NDArray, arg1: NDArray): NDArray;
    real(): NDArray;
    repeat(arg0: Shape): PtNDArray;
    repeat(arg0: number, arg1: number): PtNDArray;
    repeat(arg0: number): PtNDArray;
    repeat(arg0: number[]): PtNDArray;
    // private repeatsToMatchShape(arg0: Shape): number[];
    reshape(...arg0: number[]): NDArray;
    reshape(arg0: Shape): PtNDArray;
    returnResource(arg0: NDManager): void;
    rfft(arg0: number): NDArray;
    rfft(arg0: number, arg1: number): NDArray;
    rotate90(arg0: number, arg1: number[]): PtNDArray;
    round(): PtNDArray;
    scaleGradient(arg0: number): NDArray;
    scatter(arg0: NDArray, arg1: NDArray, arg2: number): NDArray;
    sequenceMask(arg0: NDArray): NDArray;
    sequenceMask(arg0: NDArray, arg1: number): NDArray;
    set(arg0: NDArray, arg1: Number): void;
    set(arg0: NDIndex, arg1: NDArray): void;
    set(arg0: NDIndex, arg1: (param0: NDArray) => NDArray): void;
    set(arg0: NDIndex, arg1: Number): void;
    set(arg0: number[]): void;
    set(arg0: Buffer): void;
    setName(arg0: string): void;
    setRequiresGradient(arg0: boolean): void;
    setScalar(arg0: NDIndex, arg1: Number): void;
    shapeEquals(arg0: NDArray): boolean;
    sign(): PtNDArray;
    signi(): PtNDArray;
    sin(): PtNDArray;
    sinh(): PtNDArray;
    size(): number;
    size(arg0: number): number;
    softmax(arg0: number): PtNDArray;
    sort(): PtNDArray;
    sort(arg0: number): PtNDArray;
    split(arg0: number): (Object | null)[];
    split(arg0: number, arg1: number): (Object | null)[];
    split(arg0: number[]): (Object | null)[];
    split(arg0: number[], arg1: number): (Object | null)[];
    sqrt(): NDArray;
    square(): PtNDArray;
    squeeze(): NDArray;
    squeeze(arg0: number): NDArray;
    squeeze(): PtNDArray;
    squeeze(arg0: number): PtNDArray;
    squeeze(arg0: number[]): PtNDArray;
    stack(arg0: NDArray): NDArray;
    stack(arg0: NDArray, arg1: number): NDArray;
    stft(arg0: number, arg1: number, arg2: boolean, arg3: NDArray, arg4: boolean): NDArray;
    stft(arg0: number, arg1: number, arg2: boolean, arg3: NDArray, arg4: boolean, arg5: boolean): NDArray;
    stopGradient(): NDArray;
    sub(arg0: NDArray): PtNDArray;
    sub(arg0: Number): PtNDArray;
    subi(arg0: NDArray): PtNDArray;
    subi(arg0: Number): PtNDArray;
    sum(arg0: number[]): NDArray;
    sum(): PtNDArray;
    sum(arg0: number[], arg1: boolean): PtNDArray;
    swapAxes(arg0: number, arg1: number): NDArray;
    swapAxes(arg0: number, arg1: number): PtNDArray;
    take(arg0: NDArray): NDArray;
    take(arg0: NDManager, arg1: NDArray): NDArray;
    tan(): PtNDArray;
    tanh(): PtNDArray;
    tempAttach(arg0: NDManager): void;
    tile(arg0: Shape): PtNDArray;
    tile(arg0: number, arg1: number): PtNDArray;
    tile(arg0: number): PtNDArray;
    tile(arg0: number[]): PtNDArray;
    toArray(): Number[];
    toBooleanArray(): boolean[];
    toByteArray(): number[];
    toByteBuffer(): ByteBuffer;
    toByteBuffer(arg0: boolean): ByteBuffer;
    toDebugString(): string;
    toDebugString(arg0: boolean): string;
    toDebugString(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean): string;
    toDegrees(): PtNDArray;
    toDense(): PtNDArray;
    toDevice(arg0: Device, arg1: boolean): PtNDArray;
    toDoubleArray(): number[];
    toFloatArray(): number[];
    toIntArray(): number[];
    toLongArray(): number[];
    toRadians(): PtNDArray;
    toShortArray(): number[];
    toSparse(arg0: SparseFormat): PtNDArray;
    toString(): string;
    toStringArray(): string[];
    toStringArray(arg0: Charset): string[];
    toType(arg0: DataType, arg1: boolean): PtNDArray;
    toUint8Array(): number[];
    toUnsignedIntArray(): number[];
    toUnsignedShortArray(): number[];
    topK(arg0: number, arg1: number): (Object | null)[];
    topK(arg0: number, arg1: number, arg2: boolean, arg3: boolean): (Object | null)[];
    trace(): NDArray;
    trace(arg0: number): NDArray;
    trace(arg0: number, arg1: number, arg2: number): PtNDArray;
    transpose(): PtNDArray;
    transpose(...arg0: number[]): PtNDArray;
    trunc(): PtNDArray;
    unique(): (Object | null)[];
    unique(arg0: boolean, arg1: boolean, arg2: boolean): (Object | null)[];
    unique(arg0: number, arg1: boolean, arg2: boolean, arg3: boolean): (Object | null)[];
    xlogy(arg0: NDArray): NDArray;
    zerosLike(): NDArray;
}