import type { ByteBuffer } from '../../../../../java/nio/ByteBuffer.d.ts'
import type { LongBuffer } from '../../../../../java/nio/LongBuffer.d.ts'
import type { ShortBuffer } from '../../../../../java/nio/ShortBuffer.d.ts'
import type { Object } from '../../../../../java/lang/Object.d.ts'
import type { MemoryStack } from '../../../../../org/lwjgl/system/MemoryStack.d.ts'
import type { NativeResource } from '../../../../../org/lwjgl/system/NativeResource.d.ts'
import type { Struct } from '../../../../../org/lwjgl/system/Struct.d.ts'
import type { Struct$StructValidation } from '../../../../../org/lwjgl/system/Struct$StructValidation.d.ts'
export class IOURingSQE extends Struct<IOURingSQE> implements NativeResource {
    static ACCEPT_FLAGS: number;
    static ADDR: number;
    static ADDR2: number;
    static ADDR3: number;
    static ADDR_LEN: number;
    static ALIGNOF: number;
    static ATTR_PTR: number;
    static ATTR_TYPE_MASK: number;
    static BITS32: boolean;
    static BITS64: boolean;
    static BUF_GROUP: number;
    static BUF_INDEX: number;
    static CANCEL_FLAGS: number;
    static CLONG_SHIFT: number;
    static CLONG_SIZE: number;
    static CMD: number;
    static CMD_OP: number;
    static FADVISE_ADVICE: number;
    static FD: number;
    static FILE_INDEX: number;
    static FLAGS: number;
    static FSYNC_FLAGS: number;
    static FUTEX_FLAGS: number;
    static HARDLINK_FLAGS: number;
    static INSTALL_FD_FLAGS: number;
    static IOPRIO: number;
    static LEN: number;
    static LEVEL: number;
    static MSG_FLAGS: number;
    static MSG_RING_FLAGS: number;
    static NOP_FLAGS: number;
    static OFF: number;
    static OPCODE: number;
    static OPEN_FLAGS: number;
    static OPTLEN: number;
    static OPTNAME: number;
    static OPTVAL: number;
    static PERSONALITY: number;
    static PIPE_FLAGS: number;
    static POINTER_SHIFT: number;
    static POINTER_SIZE: number;
    static POLL32_EVENTS: number;
    static POLL_EVENTS: number;
    static RENAME_FLAGS: number;
    static RW_FLAGS: number;
    static SIZEOF: number;
    static SPLICE_FD_IN: number;
    static SPLICE_FLAGS: number;
    static SPLICE_OFF_IN: number;
    static STATX_FLAGS: number;
    static SYNC_RANGE_FLAGS: number;
    static TIMEOUT_FLAGS: number;
    static UNLINK_FLAGS: number;
    static URING_CMD_FLAGS: number;
    static USER_DATA: number;
    static WAITID_FLAGS: number;
    static XATTR_FLAGS: number;
    static ZCRX_IFQ_IDX: number;
    static __PAD1: number;
    static __PAD2: number;
    static __PAD3: number;
    static calloc(): IOURingSQE;
    static calloc(paramarg0: MemoryStack): IOURingSQE;
    static calloc(paramarg0: number): (Object | null)[];
    static calloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static create(): IOURingSQE;
    static create(paramarg0: number): IOURingSQE;
    static create(paramarg0: number): (Object | null)[];
    static create(paramarg0: number, paramarg1: number): (Object | null)[];
    static createSafe(paramarg0: number): IOURingSQE;
    static createSafe(paramarg0: number, paramarg1: number): (Object | null)[];
    static malloc(): IOURingSQE;
    static malloc(paramarg0: MemoryStack): IOURingSQE;
    static malloc(paramarg0: number): (Object | null)[];
    static malloc(paramarg0: number, paramarg1: MemoryStack): (Object | null)[];
    static n__pad1(paramarg0: number): number;
    static n__pad1(paramarg0: number, paramarg1: number): void;
    static n__pad2(paramarg0: number): LongBuffer;
    static n__pad2(paramarg0: number, paramarg1: number): number;
    static n__pad2(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static n__pad2(paramarg0: number, paramarg1: LongBuffer): void;
    static n__pad3(paramarg0: number): ShortBuffer;
    static n__pad3(paramarg0: number, paramarg1: number): number;
    static n__pad3(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static n__pad3(paramarg0: number, paramarg1: ShortBuffer): void;
    static naccept_flags(paramarg0: number): number;
    static naccept_flags(paramarg0: number, paramarg1: number): void;
    static naddr(paramarg0: number): number;
    static naddr(paramarg0: number, paramarg1: number): void;
    static naddr2(paramarg0: number): number;
    static naddr2(paramarg0: number, paramarg1: number): void;
    static naddr3(paramarg0: number): number;
    static naddr3(paramarg0: number, paramarg1: number): void;
    static naddr_len(paramarg0: number): number;
    static naddr_len(paramarg0: number, paramarg1: number): void;
    static nattr_ptr(paramarg0: number): number;
    static nattr_ptr(paramarg0: number, paramarg1: number): void;
    static nattr_type_mask(paramarg0: number): number;
    static nattr_type_mask(paramarg0: number, paramarg1: number): void;
    static nbuf_group(paramarg0: number): number;
    static nbuf_group(paramarg0: number, paramarg1: number): void;
    static nbuf_index(paramarg0: number): number;
    static nbuf_index(paramarg0: number, paramarg1: number): void;
    static ncancel_flags(paramarg0: number): number;
    static ncancel_flags(paramarg0: number, paramarg1: number): void;
    static ncmd(paramarg0: number, paramarg1: number): number;
    static ncmd(paramarg0: number): ByteBuffer;
    static ncmd(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static ncmd(paramarg0: number, paramarg1: ByteBuffer): void;
    static ncmd_op(paramarg0: number): number;
    static ncmd_op(paramarg0: number, paramarg1: number): void;
    static nfadvise_advice(paramarg0: number): number;
    static nfadvise_advice(paramarg0: number, paramarg1: number): void;
    static nfd(paramarg0: number): number;
    static nfd(paramarg0: number, paramarg1: number): void;
    static nfile_index(paramarg0: number): number;
    static nfile_index(paramarg0: number, paramarg1: number): void;
    static nflags(paramarg0: number): number;
    static nflags(paramarg0: number, paramarg1: number): void;
    static nfsync_flags(paramarg0: number): number;
    static nfsync_flags(paramarg0: number, paramarg1: number): void;
    static nfutex_flags(paramarg0: number): number;
    static nfutex_flags(paramarg0: number, paramarg1: number): void;
    static nhardlink_flags(paramarg0: number): number;
    static nhardlink_flags(paramarg0: number, paramarg1: number): void;
    static ninstall_fd_flags(paramarg0: number): number;
    static ninstall_fd_flags(paramarg0: number, paramarg1: number): void;
    static nioprio(paramarg0: number): number;
    static nioprio(paramarg0: number, paramarg1: number): void;
    static nlen(paramarg0: number): number;
    static nlen(paramarg0: number, paramarg1: number): void;
    static nlevel(paramarg0: number): number;
    static nlevel(paramarg0: number, paramarg1: number): void;
    static nmsg_flags(paramarg0: number): number;
    static nmsg_flags(paramarg0: number, paramarg1: number): void;
    static nmsg_ring_flags(paramarg0: number): number;
    static nmsg_ring_flags(paramarg0: number, paramarg1: number): void;
    static nnop_flags(paramarg0: number): number;
    static nnop_flags(paramarg0: number, paramarg1: number): void;
    static noff(paramarg0: number): number;
    static noff(paramarg0: number, paramarg1: number): void;
    static nopcode(paramarg0: number): number;
    static nopcode(paramarg0: number, paramarg1: number): void;
    static nopen_flags(paramarg0: number): number;
    static nopen_flags(paramarg0: number, paramarg1: number): void;
    static noptlen(paramarg0: number): number;
    static noptlen(paramarg0: number, paramarg1: number): void;
    static noptname(paramarg0: number): number;
    static noptname(paramarg0: number, paramarg1: number): void;
    static noptval(paramarg0: number): number;
    static noptval(paramarg0: number, paramarg1: number): void;
    static npersonality(paramarg0: number): number;
    static npersonality(paramarg0: number, paramarg1: number): void;
    static npipe_flags(paramarg0: number): number;
    static npipe_flags(paramarg0: number, paramarg1: number): void;
    static npoll32_events(paramarg0: number): number;
    static npoll32_events(paramarg0: number, paramarg1: number): void;
    static npoll_events(paramarg0: number): number;
    static npoll_events(paramarg0: number, paramarg1: number): void;
    static nrename_flags(paramarg0: number): number;
    static nrename_flags(paramarg0: number, paramarg1: number): void;
    static nrw_flags(paramarg0: number): number;
    static nrw_flags(paramarg0: number, paramarg1: number): void;
    static nsplice_fd_in(paramarg0: number): number;
    static nsplice_fd_in(paramarg0: number, paramarg1: number): void;
    static nsplice_flags(paramarg0: number): number;
    static nsplice_flags(paramarg0: number, paramarg1: number): void;
    static nsplice_off_in(paramarg0: number): number;
    static nsplice_off_in(paramarg0: number, paramarg1: number): void;
    static nstatx_flags(paramarg0: number): number;
    static nstatx_flags(paramarg0: number, paramarg1: number): void;
    static nsync_range_flags(paramarg0: number): number;
    static nsync_range_flags(paramarg0: number, paramarg1: number): void;
    static ntimeout_flags(paramarg0: number): number;
    static ntimeout_flags(paramarg0: number, paramarg1: number): void;
    static nunlink_flags(paramarg0: number): number;
    static nunlink_flags(paramarg0: number, paramarg1: number): void;
    static nuring_cmd_flags(paramarg0: number): number;
    static nuring_cmd_flags(paramarg0: number, paramarg1: number): void;
    static nuser_data(paramarg0: number): number;
    static nuser_data(paramarg0: number, paramarg1: number): void;
    static nwaitid_flags(paramarg0: number): number;
    static nwaitid_flags(paramarg0: number, paramarg1: number): void;
    static nxattr_flags(paramarg0: number): number;
    static nxattr_flags(paramarg0: number, paramarg1: number): void;
    static nzcrx_ifq_idx(paramarg0: number): number;
    static nzcrx_ifq_idx(paramarg0: number, paramarg1: number): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    static validate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: (param0: number) => void): void;
    constructor(arg0: ByteBuffer)
    constructor(arg0: number, arg1: ByteBuffer)
    __pad1(): number;
    __pad1(arg0: number): IOURingSQE;
    __pad2(): LongBuffer;
    __pad2(arg0: LongBuffer): IOURingSQE;
    __pad2(arg0: number): number;
    __pad2(arg0: number, arg1: number): IOURingSQE;
    __pad3(): ShortBuffer;
    __pad3(arg0: ShortBuffer): IOURingSQE;
    __pad3(arg0: number): number;
    __pad3(arg0: number, arg1: number): IOURingSQE;
    accept_flags(): number;
    accept_flags(arg0: number): IOURingSQE;
    addr(): number;
    addr(arg0: number): IOURingSQE;
    addr2(): number;
    addr2(arg0: number): IOURingSQE;
    addr3(): number;
    addr3(arg0: number): IOURingSQE;
    addr_len(): number;
    addr_len(arg0: number): IOURingSQE;
    attr_ptr(): number;
    attr_ptr(arg0: number): IOURingSQE;
    attr_type_mask(): number;
    attr_type_mask(arg0: number): IOURingSQE;
    buf_group(): number;
    buf_group(arg0: number): IOURingSQE;
    buf_index(): number;
    buf_index(arg0: number): IOURingSQE;
    cancel_flags(): number;
    cancel_flags(arg0: number): IOURingSQE;
    close(): void;
    cmd(): ByteBuffer;
    cmd(arg0: ByteBuffer): IOURingSQE;
    cmd(arg0: number): number;
    cmd(arg0: number, arg1: number): IOURingSQE;
    cmd_op(): number;
    cmd_op(arg0: number): IOURingSQE;
    create(arg0: number, arg1: ByteBuffer): IOURingSQE;
    fadvise_advice(): number;
    fadvise_advice(arg0: number): IOURingSQE;
    fd(): number;
    fd(arg0: number): IOURingSQE;
    file_index(): number;
    file_index(arg0: number): IOURingSQE;
    flags(): number;
    flags(arg0: number): IOURingSQE;
    fsync_flags(): number;
    fsync_flags(arg0: number): IOURingSQE;
    futex_flags(): number;
    futex_flags(arg0: number): IOURingSQE;
    hardlink_flags(): number;
    hardlink_flags(arg0: number): IOURingSQE;
    install_fd_flags(): number;
    install_fd_flags(arg0: number): IOURingSQE;
    ioprio(): number;
    ioprio(arg0: number): IOURingSQE;
    len(): number;
    len(arg0: number): IOURingSQE;
    level(): number;
    level(arg0: number): IOURingSQE;
    msg_flags(): number;
    msg_flags(arg0: number): IOURingSQE;
    msg_ring_flags(): number;
    msg_ring_flags(arg0: number): IOURingSQE;
    nop_flags(): number;
    nop_flags(arg0: number): IOURingSQE;
    off(): number;
    off(arg0: number): IOURingSQE;
    opcode(): number;
    opcode(arg0: number): IOURingSQE;
    open_flags(): number;
    open_flags(arg0: number): IOURingSQE;
    optlen(): number;
    optlen(arg0: number): IOURingSQE;
    optname(): number;
    optname(arg0: number): IOURingSQE;
    optval(): number;
    optval(arg0: number): IOURingSQE;
    personality(): number;
    personality(arg0: number): IOURingSQE;
    pipe_flags(): number;
    pipe_flags(arg0: number): IOURingSQE;
    poll32_events(): number;
    poll32_events(arg0: number): IOURingSQE;
    poll_events(): number;
    poll_events(arg0: number): IOURingSQE;
    rename_flags(): number;
    rename_flags(arg0: number): IOURingSQE;
    rw_flags(): number;
    rw_flags(arg0: number): IOURingSQE;
    set(arg0: IOURingSQE): IOURingSQE;
    sizeof(): number;
    splice_fd_in(): number;
    splice_fd_in(arg0: number): IOURingSQE;
    splice_flags(): number;
    splice_flags(arg0: number): IOURingSQE;
    splice_off_in(): number;
    splice_off_in(arg0: number): IOURingSQE;
    statx_flags(): number;
    statx_flags(arg0: number): IOURingSQE;
    sync_range_flags(): number;
    sync_range_flags(arg0: number): IOURingSQE;
    timeout_flags(): number;
    timeout_flags(arg0: number): IOURingSQE;
    unlink_flags(): number;
    unlink_flags(arg0: number): IOURingSQE;
    uring_cmd_flags(): number;
    uring_cmd_flags(arg0: number): IOURingSQE;
    user_data(): number;
    user_data(arg0: number): IOURingSQE;
    waitid_flags(): number;
    waitid_flags(arg0: number): IOURingSQE;
    xattr_flags(): number;
    xattr_flags(arg0: number): IOURingSQE;
    zcrx_ifq_idx(): number;
    zcrx_ifq_idx(arg0: number): IOURingSQE;
}