import type { ByteBuffer } from '../../../../../java/nio/ByteBuffer.d.ts'
import type { IntBuffer } from '../../../../../java/nio/IntBuffer.d.ts'
import type { LongBuffer } from '../../../../../java/nio/LongBuffer.d.ts'
import type { ShortBuffer } from '../../../../../java/nio/ShortBuffer.d.ts'
import type { Object } from '../../../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../../../java/lang/CharSequence.d.ts'
import type { PointerBuffer } from '../../../../../org/lwjgl/PointerBuffer.d.ts'
import type { CMsghdr } from '../../../../../org/lwjgl/system/linux/CMsghdr.d.ts'
import type { EpollEvent } from '../../../../../org/lwjgl/system/linux/EpollEvent.d.ts'
import type { KernelTimespec } from '../../../../../org/lwjgl/system/linux/KernelTimespec.d.ts'
import type { Msghdr } from '../../../../../org/lwjgl/system/linux/Msghdr.d.ts'
import type { OpenHow } from '../../../../../org/lwjgl/system/linux/OpenHow.d.ts'
import type { Sockaddr } from '../../../../../org/lwjgl/system/linux/Sockaddr.d.ts'
import type { Statx } from '../../../../../org/lwjgl/system/linux/Statx.d.ts'
import type { IOURing } from '../../../../../org/lwjgl/system/linux/liburing/IOURing.d.ts'
import type { IOURingBufReg } from '../../../../../org/lwjgl/system/linux/liburing/IOURingBufReg.d.ts'
import type { IOURingBufRing } from '../../../../../org/lwjgl/system/linux/liburing/IOURingBufRing.d.ts'
import type { IOURingCQE } from '../../../../../org/lwjgl/system/linux/liburing/IOURingCQE.d.ts'
import type { IOURingClockRegister } from '../../../../../org/lwjgl/system/linux/liburing/IOURingClockRegister.d.ts'
import type { IOURingMemRegionReg } from '../../../../../org/lwjgl/system/linux/liburing/IOURingMemRegionReg.d.ts'
import type { IOURingNAPI } from '../../../../../org/lwjgl/system/linux/liburing/IOURingNAPI.d.ts'
import type { IOURingParams } from '../../../../../org/lwjgl/system/linux/liburing/IOURingParams.d.ts'
import type { IOURingProbe } from '../../../../../org/lwjgl/system/linux/liburing/IOURingProbe.d.ts'
import type { IOURingRecvmsgOut } from '../../../../../org/lwjgl/system/linux/liburing/IOURingRecvmsgOut.d.ts'
import type { IOURingRegWait } from '../../../../../org/lwjgl/system/linux/liburing/IOURingRegWait.d.ts'
import type { IOURingSQE } from '../../../../../org/lwjgl/system/linux/liburing/IOURingSQE.d.ts'
import type { IOURingSyncCancelReg } from '../../../../../org/lwjgl/system/linux/liburing/IOURingSyncCancelReg.d.ts'
import type { IOURingZCRXIfqReg } from '../../../../../org/lwjgl/system/linux/liburing/IOURingZCRXIfqReg.d.ts'
export class LibURing extends Object {
    static LIBURING_UDATA_TIMEOUT: number;
    static __io_uring_sqring_wait(paramarg0: IOURing): number;
    static io_uring_buf_ring_add(paramarg0: IOURingBufRing, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_buf_ring_advance(paramarg0: IOURingBufRing, paramarg1: number): void;
    static io_uring_buf_ring_available(paramarg0: IOURing, paramarg1: IOURingBufRing, paramarg2: number): number;
    static io_uring_buf_ring_cq_advance(paramarg0: IOURing, paramarg1: IOURingBufRing, paramarg2: number): void;
    static io_uring_buf_ring_head(paramarg0: IOURing, paramarg1: number, paramarg2: ShortBuffer): number;
    static io_uring_buf_ring_init(paramarg0: IOURingBufRing): void;
    static io_uring_buf_ring_mask(paramarg0: number): number;
    static io_uring_check_version(paramarg0: number, paramarg1: number): boolean;
    static io_uring_clone_buffers(paramarg0: IOURing, paramarg1: IOURing): number;
    static io_uring_clone_buffers_offset(paramarg0: IOURing, paramarg1: IOURing, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): number;
    static io_uring_close_ring_fd(paramarg0: IOURing): number;
    static io_uring_cq_advance(paramarg0: IOURing, paramarg1: number): void;
    static io_uring_cq_eventfd_enabled(paramarg0: IOURing): boolean;
    static io_uring_cq_eventfd_toggle(paramarg0: IOURing, paramarg1: boolean): number;
    static io_uring_cq_has_overflow(paramarg0: IOURing): boolean;
    static io_uring_cq_ready(paramarg0: IOURing): number;
    static io_uring_cqe_get_data(paramarg0: IOURingCQE): number;
    static io_uring_cqe_get_data64(paramarg0: IOURingCQE): number;
    static io_uring_cqe_nr(paramarg0: IOURingCQE): number;
    static io_uring_cqe_seen(paramarg0: IOURing, paramarg1: IOURingCQE): void;
    static io_uring_cqe_shift(paramarg0: IOURing): number;
    static io_uring_cqe_shift_from_flags(paramarg0: number): number;
    static io_uring_enable_rings(paramarg0: IOURing): number;
    static io_uring_enter(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static io_uring_enter2(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: ByteBuffer): number;
    static io_uring_free_buf_ring(paramarg0: IOURing, paramarg1: IOURingBufRing, paramarg2: number, paramarg3: number): number;
    static io_uring_free_probe(paramarg0: IOURingProbe): void;
    static io_uring_get_events(paramarg0: IOURing): number;
    static io_uring_get_probe(): IOURingProbe;
    static io_uring_get_probe_ring(paramarg0: IOURing): IOURingProbe;
    static io_uring_get_sqe(paramarg0: IOURing): IOURingSQE;
    static io_uring_get_sqe128(paramarg0: IOURing): IOURingSQE;
    static io_uring_initialize_sqe(paramarg0: IOURingSQE): void;
    static io_uring_load_sq_head(paramarg0: IOURing): number;
    static io_uring_major_version(): number;
    static io_uring_memory_size(paramarg0: number, paramarg1: number): number;
    static io_uring_memory_size_params(paramarg0: number, paramarg1: IOURingParams): number;
    static io_uring_minor_version(): number;
    static io_uring_mlock_size(paramarg0: number, paramarg1: number): number;
    static io_uring_mlock_size_params(paramarg0: number, paramarg1: IOURingParams): number;
    static io_uring_opcode_supported(paramarg0: IOURingProbe, paramarg1: number): number;
    static io_uring_peek_batch_cqe(paramarg0: IOURing, paramarg1: PointerBuffer): number;
    static io_uring_peek_cqe(paramarg0: IOURing, paramarg1: PointerBuffer): number;
    static io_uring_prep_accept(paramarg0: IOURingSQE, paramarg1: number, paramarg2: Sockaddr, paramarg3: IntBuffer, paramarg4: number): void;
    static io_uring_prep_accept_direct(paramarg0: IOURingSQE, paramarg1: number, paramarg2: Sockaddr, paramarg3: IntBuffer, paramarg4: number, paramarg5: number): void;
    static io_uring_prep_bind(paramarg0: IOURingSQE, paramarg1: number, paramarg2: Sockaddr, paramarg3: number): void;
    static io_uring_prep_cancel(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_cancel64(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_cancel_fd(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_close(paramarg0: IOURingSQE, paramarg1: number): void;
    static io_uring_prep_close_direct(paramarg0: IOURingSQE, paramarg1: number): void;
    static io_uring_prep_cmd_discard(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static io_uring_prep_cmd_getsockname(paramarg0: IOURingSQE, paramarg1: number, paramarg2: Sockaddr, paramarg3: IntBuffer, paramarg4: number): void;
    static io_uring_prep_cmd_sock(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: ByteBuffer): void;
    static io_uring_prep_connect(paramarg0: IOURingSQE, paramarg1: number, paramarg2: Sockaddr, paramarg3: number): void;
    static io_uring_prep_epoll_ctl(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: EpollEvent): void;
    static io_uring_prep_epoll_wait(paramarg0: IOURingSQE, paramarg1: number, paramarg2: (Object | null)[], paramarg3: number): void;
    static io_uring_prep_fadvise(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_fadvise64(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_fallocate(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_fgetxattr(paramarg0: IOURingSQE, paramarg1: number, paramarg2: CharSequence, paramarg3: ByteBuffer): void;
    static io_uring_prep_fgetxattr(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: ByteBuffer): void;
    static io_uring_prep_files_update(paramarg0: IOURingSQE, paramarg1: IntBuffer, paramarg2: number): void;
    static io_uring_prep_fixed_fd_install(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_fsetxattr(paramarg0: IOURingSQE, paramarg1: number, paramarg2: CharSequence, paramarg3: ByteBuffer, paramarg4: number): void;
    static io_uring_prep_fsetxattr(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: ByteBuffer, paramarg4: number): void;
    static io_uring_prep_fsync(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_ftruncate(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_futex_wait(paramarg0: IOURingSQE, paramarg1: IntBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static io_uring_prep_futex_waitv(paramarg0: IOURingSQE, paramarg1: PointerBuffer, paramarg2: number): void;
    static io_uring_prep_futex_wake(paramarg0: IOURingSQE, paramarg1: IntBuffer, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static io_uring_prep_getxattr(paramarg0: IOURingSQE, paramarg1: CharSequence, paramarg2: ByteBuffer, paramarg3: CharSequence): void;
    static io_uring_prep_getxattr(paramarg0: IOURingSQE, paramarg1: ByteBuffer, paramarg2: ByteBuffer, paramarg3: ByteBuffer): void;
    static io_uring_prep_link(paramarg0: IOURingSQE, paramarg1: CharSequence, paramarg2: CharSequence, paramarg3: number): void;
    static io_uring_prep_link(paramarg0: IOURingSQE, paramarg1: ByteBuffer, paramarg2: ByteBuffer, paramarg3: number): void;
    static io_uring_prep_link_timeout(paramarg0: IOURingSQE, paramarg1: KernelTimespec, paramarg2: number): void;
    static io_uring_prep_linkat(paramarg0: IOURingSQE, paramarg1: number, paramarg2: CharSequence, paramarg3: number, paramarg4: CharSequence, paramarg5: number): void;
    static io_uring_prep_linkat(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: ByteBuffer, paramarg5: number): void;
    static io_uring_prep_listen(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_madvise(paramarg0: IOURingSQE, paramarg1: ByteBuffer, paramarg2: number): void;
    static io_uring_prep_madvise64(paramarg0: IOURingSQE, paramarg1: ByteBuffer, paramarg2: number): void;
    static io_uring_prep_mkdir(paramarg0: IOURingSQE, paramarg1: CharSequence, paramarg2: number): void;
    static io_uring_prep_mkdir(paramarg0: IOURingSQE, paramarg1: ByteBuffer, paramarg2: number): void;
    static io_uring_prep_mkdirat(paramarg0: IOURingSQE, paramarg1: number, paramarg2: CharSequence, paramarg3: number): void;
    static io_uring_prep_mkdirat(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number): void;
    static io_uring_prep_msg_ring(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_msg_ring_cqe_flags(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static io_uring_prep_msg_ring_fd(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static io_uring_prep_msg_ring_fd_alloc(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_multishot_accept(paramarg0: IOURingSQE, paramarg1: number, paramarg2: Sockaddr, paramarg3: IntBuffer, paramarg4: number): void;
    static io_uring_prep_multishot_accept_direct(paramarg0: IOURingSQE, paramarg1: number, paramarg2: Sockaddr, paramarg3: IntBuffer, paramarg4: number): void;
    static io_uring_prep_nop(paramarg0: IOURingSQE): void;
    static io_uring_prep_nop128(paramarg0: IOURingSQE): void;
    static io_uring_prep_open(paramarg0: IOURingSQE, paramarg1: CharSequence, paramarg2: number, paramarg3: number): void;
    static io_uring_prep_open(paramarg0: IOURingSQE, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number): void;
    static io_uring_prep_open_direct(paramarg0: IOURingSQE, paramarg1: CharSequence, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_open_direct(paramarg0: IOURingSQE, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_openat(paramarg0: IOURingSQE, paramarg1: number, paramarg2: CharSequence, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_openat(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_openat2(paramarg0: IOURingSQE, paramarg1: number, paramarg2: CharSequence, paramarg3: OpenHow): void;
    static io_uring_prep_openat2(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: OpenHow): void;
    static io_uring_prep_openat2_direct(paramarg0: IOURingSQE, paramarg1: number, paramarg2: CharSequence, paramarg3: OpenHow, paramarg4: number): void;
    static io_uring_prep_openat2_direct(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: OpenHow, paramarg4: number): void;
    static io_uring_prep_openat_direct(paramarg0: IOURingSQE, paramarg1: number, paramarg2: CharSequence, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static io_uring_prep_openat_direct(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static io_uring_prep_pipe(paramarg0: IOURingSQE, paramarg1: IntBuffer, paramarg2: number): void;
    static io_uring_prep_pipe_direct(paramarg0: IOURingSQE, paramarg1: IntBuffer, paramarg2: number, paramarg3: number): void;
    static io_uring_prep_poll_add(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_poll_multishot(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_poll_remove(paramarg0: IOURingSQE, paramarg1: number): void;
    static io_uring_prep_poll_update(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_provide_buffers(paramarg0: IOURingSQE, paramarg1: ByteBuffer, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_read(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number): void;
    static io_uring_prep_read_fixed(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_read_multishot(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_readv(paramarg0: IOURingSQE, paramarg1: number, paramarg2: (Object | null)[], paramarg3: number): void;
    static io_uring_prep_readv2(paramarg0: IOURingSQE, paramarg1: number, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): void;
    static io_uring_prep_readv_fixed(paramarg0: IOURingSQE, paramarg1: number, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number, paramarg5: number): void;
    static io_uring_prep_recv(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number): void;
    static io_uring_prep_recv_multishot(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number): void;
    static io_uring_prep_recvmsg(paramarg0: IOURingSQE, paramarg1: number, paramarg2: Msghdr, paramarg3: number): void;
    static io_uring_prep_recvmsg_multishot(paramarg0: IOURingSQE, paramarg1: number, paramarg2: Msghdr, paramarg3: number): void;
    static io_uring_prep_remove_buffers(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_rename(paramarg0: IOURingSQE, paramarg1: CharSequence, paramarg2: CharSequence): void;
    static io_uring_prep_rename(paramarg0: IOURingSQE, paramarg1: ByteBuffer, paramarg2: ByteBuffer): void;
    static io_uring_prep_renameat(paramarg0: IOURingSQE, paramarg1: number, paramarg2: CharSequence, paramarg3: number, paramarg4: CharSequence, paramarg5: number): void;
    static io_uring_prep_renameat(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: ByteBuffer, paramarg5: number): void;
    static io_uring_prep_send(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number): void;
    static io_uring_prep_send_bundle(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static io_uring_prep_send_set_addr(paramarg0: IOURingSQE, paramarg1: Sockaddr, paramarg2: number): void;
    static io_uring_prep_send_zc(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_send_zc_fixed(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static io_uring_prep_sendmsg(paramarg0: IOURingSQE, paramarg1: number, paramarg2: Msghdr, paramarg3: number): void;
    static io_uring_prep_sendmsg_zc(paramarg0: IOURingSQE, paramarg1: number, paramarg2: Msghdr, paramarg3: number): void;
    static io_uring_prep_sendmsg_zc_fixed(paramarg0: IOURingSQE, paramarg1: number, paramarg2: Msghdr, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_sendto(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: Sockaddr, paramarg5: number): void;
    static io_uring_prep_setxattr(paramarg0: IOURingSQE, paramarg1: CharSequence, paramarg2: ByteBuffer, paramarg3: CharSequence, paramarg4: number): void;
    static io_uring_prep_setxattr(paramarg0: IOURingSQE, paramarg1: ByteBuffer, paramarg2: ByteBuffer, paramarg3: ByteBuffer, paramarg4: number): void;
    static io_uring_prep_shutdown(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_socket(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_socket_direct(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static io_uring_prep_socket_direct_alloc(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_splice(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static io_uring_prep_statx(paramarg0: IOURingSQE, paramarg1: number, paramarg2: CharSequence, paramarg3: number, paramarg4: number, paramarg5: Statx): void;
    static io_uring_prep_statx(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number, paramarg5: Statx): void;
    static io_uring_prep_symlink(paramarg0: IOURingSQE, paramarg1: CharSequence, paramarg2: CharSequence): void;
    static io_uring_prep_symlink(paramarg0: IOURingSQE, paramarg1: ByteBuffer, paramarg2: ByteBuffer): void;
    static io_uring_prep_symlinkat(paramarg0: IOURingSQE, paramarg1: CharSequence, paramarg2: number, paramarg3: CharSequence): void;
    static io_uring_prep_symlinkat(paramarg0: IOURingSQE, paramarg1: ByteBuffer, paramarg2: number, paramarg3: ByteBuffer): void;
    static io_uring_prep_sync_file_range(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_tee(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_timeout(paramarg0: IOURingSQE, paramarg1: KernelTimespec, paramarg2: number, paramarg3: number): void;
    static io_uring_prep_timeout_remove(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_timeout_update(paramarg0: IOURingSQE, paramarg1: KernelTimespec, paramarg2: number, paramarg3: number): void;
    static io_uring_prep_unlink(paramarg0: IOURingSQE, paramarg1: CharSequence, paramarg2: number): void;
    static io_uring_prep_unlink(paramarg0: IOURingSQE, paramarg1: ByteBuffer, paramarg2: number): void;
    static io_uring_prep_unlinkat(paramarg0: IOURingSQE, paramarg1: number, paramarg2: CharSequence, paramarg3: number): void;
    static io_uring_prep_unlinkat(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number): void;
    static io_uring_prep_uring_cmd(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_uring_cmd128(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number): void;
    static io_uring_prep_waitid(paramarg0: IOURingSQE, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static io_uring_prep_write(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number): void;
    static io_uring_prep_write_fixed(paramarg0: IOURingSQE, paramarg1: number, paramarg2: ByteBuffer, paramarg3: number, paramarg4: number): void;
    static io_uring_prep_writev(paramarg0: IOURingSQE, paramarg1: number, paramarg2: (Object | null)[], paramarg3: number): void;
    static io_uring_prep_writev2(paramarg0: IOURingSQE, paramarg1: number, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number): void;
    static io_uring_prep_writev_fixed(paramarg0: IOURingSQE, paramarg1: number, paramarg2: (Object | null)[], paramarg3: number, paramarg4: number, paramarg5: number): void;
    static io_uring_queue_exit(paramarg0: IOURing): void;
    static io_uring_queue_init(paramarg0: number, paramarg1: IOURing, paramarg2: number): number;
    static io_uring_queue_init_mem(paramarg0: number, paramarg1: IOURing, paramarg2: IOURingParams, paramarg3: ByteBuffer): number;
    static io_uring_queue_init_params(paramarg0: number, paramarg1: IOURing, paramarg2: IOURingParams): number;
    static io_uring_queue_mmap(paramarg0: number, paramarg1: IOURingParams, paramarg2: IOURing): number;
    static io_uring_recvmsg_cmsg_firsthdr(paramarg0: IOURingRecvmsgOut, paramarg1: Msghdr): CMsghdr;
    static io_uring_recvmsg_cmsg_nexthdr(paramarg0: IOURingRecvmsgOut, paramarg1: Msghdr, paramarg2: CMsghdr): CMsghdr;
    static io_uring_recvmsg_name(paramarg0: IOURingRecvmsgOut): number;
    static io_uring_recvmsg_payload(paramarg0: IOURingRecvmsgOut, paramarg1: Msghdr): number;
    static io_uring_recvmsg_payload_length(paramarg0: IOURingRecvmsgOut, paramarg1: number, paramarg2: Msghdr): number;
    static io_uring_recvmsg_validate(paramarg0: ByteBuffer, paramarg1: Msghdr): IOURingRecvmsgOut;
    static io_uring_register(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static io_uring_register_buf_ring(paramarg0: IOURing, paramarg1: IOURingBufReg, paramarg2: number): number;
    static io_uring_register_buffers(paramarg0: IOURing, paramarg1: (Object | null)[]): number;
    static io_uring_register_buffers_sparse(paramarg0: IOURing, paramarg1: number): number;
    static io_uring_register_buffers_tags(paramarg0: IOURing, paramarg1: (Object | null)[], paramarg2: LongBuffer): number;
    static io_uring_register_buffers_update_tag(paramarg0: IOURing, paramarg1: number, paramarg2: (Object | null)[], paramarg3: LongBuffer): number;
    static io_uring_register_clock(paramarg0: IOURing, paramarg1: IOURingClockRegister): number;
    static io_uring_register_eventfd(paramarg0: IOURing, paramarg1: number): number;
    static io_uring_register_eventfd_async(paramarg0: IOURing, paramarg1: number): number;
    static io_uring_register_file_alloc_range(paramarg0: IOURing, paramarg1: number, paramarg2: number): number;
    static io_uring_register_files(paramarg0: IOURing, paramarg1: IntBuffer): number;
    static io_uring_register_files_sparse(paramarg0: IOURing, paramarg1: number): number;
    static io_uring_register_files_tags(paramarg0: IOURing, paramarg1: IntBuffer, paramarg2: LongBuffer): number;
    static io_uring_register_files_update(paramarg0: IOURing, paramarg1: number, paramarg2: IntBuffer): number;
    static io_uring_register_files_update_tag(paramarg0: IOURing, paramarg1: number, paramarg2: IntBuffer, paramarg3: LongBuffer): number;
    static io_uring_register_ifq(paramarg0: IOURing, paramarg1: IOURingZCRXIfqReg): number;
    static io_uring_register_iowq_aff(paramarg0: IOURing, paramarg1: number, paramarg2: number): number;
    static io_uring_register_iowq_max_workers(paramarg0: IOURing, paramarg1: IntBuffer): number;
    static io_uring_register_napi(paramarg0: IOURing, paramarg1: IOURingNAPI): number;
    static io_uring_register_personality(paramarg0: IOURing): number;
    static io_uring_register_probe(paramarg0: IOURing, paramarg1: IOURingProbe, paramarg2: number): number;
    static io_uring_register_region(paramarg0: IOURing, paramarg1: IOURingMemRegionReg): number;
    static io_uring_register_restrictions(paramarg0: IOURing, paramarg1: (Object | null)[]): number;
    static io_uring_register_ring_fd(paramarg0: IOURing): number;
    static io_uring_register_sync_cancel(paramarg0: IOURing, paramarg1: IOURingSyncCancelReg): number;
    static io_uring_register_wait_reg(paramarg0: IOURing, paramarg1: IOURingRegWait, paramarg2: number): number;
    static io_uring_resize_rings(paramarg0: IOURing, paramarg1: IOURingParams): number;
    static io_uring_ring_dontfork(paramarg0: IOURing): number;
    static io_uring_set_iowait(paramarg0: IOURing, paramarg1: boolean): number;
    static io_uring_setup(paramarg0: number, paramarg1: IOURingParams): number;
    static io_uring_setup_buf_ring(paramarg0: IOURing, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: IntBuffer): IOURingBufRing;
    static io_uring_sq_ready(paramarg0: IOURing): number;
    static io_uring_sq_space_left(paramarg0: IOURing): number;
    static io_uring_sqe_set_buf_group(paramarg0: IOURingSQE, paramarg1: number): void;
    static io_uring_sqe_set_data(paramarg0: IOURingSQE, paramarg1: number): void;
    static io_uring_sqe_set_data64(paramarg0: IOURingSQE, paramarg1: number): void;
    static io_uring_sqe_set_flags(paramarg0: IOURingSQE, paramarg1: number): void;
    static io_uring_sqe_shift(paramarg0: IOURing): number;
    static io_uring_sqe_shift_from_flags(paramarg0: number): number;
    static io_uring_sqring_wait(paramarg0: IOURing): number;
    static io_uring_submit(paramarg0: IOURing): number;
    static io_uring_submit_and_get_events(paramarg0: IOURing): number;
    static io_uring_submit_and_wait(paramarg0: IOURing, paramarg1: number): number;
    static io_uring_submit_and_wait_min_timeout(paramarg0: IOURing, paramarg1: PointerBuffer, paramarg2: KernelTimespec, paramarg3: number, paramarg4: number): number;
    static io_uring_submit_and_wait_reg(paramarg0: IOURing, paramarg1: PointerBuffer, paramarg2: number): number;
    static io_uring_submit_and_wait_timeout(paramarg0: IOURing, paramarg1: PointerBuffer, paramarg2: KernelTimespec, paramarg3: number): number;
    static io_uring_unregister_buf_ring(paramarg0: IOURing, paramarg1: number): number;
    static io_uring_unregister_buffers(paramarg0: IOURing): number;
    static io_uring_unregister_eventfd(paramarg0: IOURing): number;
    static io_uring_unregister_files(paramarg0: IOURing): number;
    static io_uring_unregister_iowq_aff(paramarg0: IOURing): number;
    static io_uring_unregister_napi(paramarg0: IOURing, paramarg1: IOURingNAPI): number;
    static io_uring_unregister_personality(paramarg0: IOURing, paramarg1: number): number;
    static io_uring_unregister_ring_fd(paramarg0: IOURing): number;
    static io_uring_wait_cqe(paramarg0: IOURing, paramarg1: PointerBuffer): number;
    static io_uring_wait_cqe_nr(paramarg0: IOURing, paramarg1: PointerBuffer): number;
    static io_uring_wait_cqe_timeout(paramarg0: IOURing, paramarg1: PointerBuffer, paramarg2: KernelTimespec): number;
    static io_uring_wait_cqes(paramarg0: IOURing, paramarg1: PointerBuffer, paramarg2: KernelTimespec, paramarg3: number): number;
    static io_uring_wait_cqes_min_timeout(paramarg0: IOURing, paramarg1: PointerBuffer, paramarg2: KernelTimespec, paramarg3: number, paramarg4: number): number;
    static n__io_uring_sqring_wait(paramarg0: number): number;
    static nio_uring_buf_ring_advance(paramarg0: number, paramarg1: number): void;
    static nio_uring_buf_ring_available(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_buf_ring_cq_advance(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_buf_ring_head(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_clone_buffers(paramarg0: number, paramarg1: number): number;
    static nio_uring_clone_buffers_offset(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): number;
    static nio_uring_close_ring_fd(paramarg0: number): number;
    static nio_uring_cq_advance(paramarg0: number, paramarg1: number): void;
    static nio_uring_cq_eventfd_enabled(paramarg0: number): boolean;
    static nio_uring_cq_eventfd_toggle(paramarg0: number, paramarg1: boolean): number;
    static nio_uring_cq_has_overflow(paramarg0: number): boolean;
    static nio_uring_cq_ready(paramarg0: number): number;
    static nio_uring_cqe_get_data(paramarg0: number): number;
    static nio_uring_cqe_get_data64(paramarg0: number): number;
    static nio_uring_cqe_nr(paramarg0: number): number;
    static nio_uring_cqe_seen(paramarg0: number, paramarg1: number): void;
    static nio_uring_cqe_shift(paramarg0: number): number;
    static nio_uring_enable_rings(paramarg0: number): number;
    static nio_uring_enter(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nio_uring_enter2(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): number;
    static nio_uring_free_buf_ring(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nio_uring_free_probe(paramarg0: number): void;
    static nio_uring_get_events(paramarg0: number): number;
    static nio_uring_get_probe(): number;
    static nio_uring_get_probe_ring(paramarg0: number): number;
    static nio_uring_get_sqe(paramarg0: number): number;
    static nio_uring_get_sqe128(paramarg0: number): number;
    static nio_uring_initialize_sqe(paramarg0: number): void;
    static nio_uring_load_sq_head(paramarg0: number): number;
    static nio_uring_memory_size_params(paramarg0: number, paramarg1: number): number;
    static nio_uring_mlock_size_params(paramarg0: number, paramarg1: number): number;
    static nio_uring_opcode_supported(paramarg0: number, paramarg1: number): number;
    static nio_uring_peek_batch_cqe(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_peek_cqe(paramarg0: number, paramarg1: number): number;
    static nio_uring_prep_accept(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_accept_direct(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_bind(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_cancel(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_cancel64(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_cancel_fd(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_close(paramarg0: number, paramarg1: number): void;
    static nio_uring_prep_close_direct(paramarg0: number, paramarg1: number): void;
    static nio_uring_prep_cmd_discard(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_cmd_getsockname(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_cmd_sock(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nio_uring_prep_connect(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_epoll_ctl(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_epoll_wait(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_fadvise(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_fadvise64(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_fallocate(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_fgetxattr(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_files_update(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_fixed_fd_install(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_fsetxattr(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_fsync(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_ftruncate(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_futex_wait(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_futex_waitv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_futex_wake(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_getxattr(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_link(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_link_timeout(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_linkat(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_listen(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_madvise(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_madvise64(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_mkdir(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_mkdirat(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_msg_ring(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_msg_ring_cqe_flags(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_msg_ring_fd(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_msg_ring_fd_alloc(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_multishot_accept(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_multishot_accept_direct(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_nop(paramarg0: number): void;
    static nio_uring_prep_nop128(paramarg0: number): void;
    static nio_uring_prep_open(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_open_direct(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_openat(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_openat2(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_openat2_direct(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_openat_direct(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_pipe(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_pipe_direct(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_poll_add(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_poll_multishot(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_poll_remove(paramarg0: number, paramarg1: number): void;
    static nio_uring_prep_poll_update(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_provide_buffers(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_read(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_read_fixed(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_read_multishot(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_readv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_readv2(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_readv_fixed(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nio_uring_prep_recv(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_recv_multishot(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_recvmsg(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_recvmsg_multishot(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_remove_buffers(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_rename(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_renameat(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_send(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_send_bundle(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_send_set_addr(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_send_zc(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_send_zc_fixed(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nio_uring_prep_sendmsg(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_sendmsg_zc(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_sendmsg_zc_fixed(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_sendto(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nio_uring_prep_setxattr(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_shutdown(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_socket(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_socket_direct(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_socket_direct_alloc(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_splice(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nio_uring_prep_statx(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_symlink(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_symlinkat(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_sync_file_range(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_tee(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_timeout(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_timeout_remove(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_timeout_update(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_unlink(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_unlinkat(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): void;
    static nio_uring_prep_uring_cmd(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_uring_cmd128(paramarg0: number, paramarg1: number, paramarg2: number): void;
    static nio_uring_prep_waitid(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_write(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_write_fixed(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_writev(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): void;
    static nio_uring_prep_writev2(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): void;
    static nio_uring_prep_writev_fixed(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number, paramarg6: number): void;
    static nio_uring_queue_exit(paramarg0: number): void;
    static nio_uring_queue_init(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_queue_init_mem(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nio_uring_queue_init_params(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_queue_mmap(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_recvmsg_cmsg_firsthdr(paramarg0: number, paramarg1: number): number;
    static nio_uring_recvmsg_cmsg_nexthdr(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_recvmsg_name(paramarg0: number): number;
    static nio_uring_recvmsg_payload(paramarg0: number, paramarg1: number): number;
    static nio_uring_recvmsg_payload_length(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_recvmsg_validate(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_register_buf_ring(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_register_buffers(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_register_buffers_sparse(paramarg0: number, paramarg1: number): number;
    static nio_uring_register_buffers_tags(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nio_uring_register_buffers_update_tag(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nio_uring_register_clock(paramarg0: number, paramarg1: number): number;
    static nio_uring_register_eventfd(paramarg0: number, paramarg1: number): number;
    static nio_uring_register_eventfd_async(paramarg0: number, paramarg1: number): number;
    static nio_uring_register_file_alloc_range(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_register_files(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_register_files_sparse(paramarg0: number, paramarg1: number): number;
    static nio_uring_register_files_tags(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nio_uring_register_files_update(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nio_uring_register_files_update_tag(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nio_uring_register_ifq(paramarg0: number, paramarg1: number): number;
    static nio_uring_register_iowq_aff(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_register_iowq_max_workers(paramarg0: number, paramarg1: number): number;
    static nio_uring_register_napi(paramarg0: number, paramarg1: number): number;
    static nio_uring_register_personality(paramarg0: number): number;
    static nio_uring_register_probe(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_register_region(paramarg0: number, paramarg1: number): number;
    static nio_uring_register_restrictions(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_register_ring_fd(paramarg0: number): number;
    static nio_uring_register_sync_cancel(paramarg0: number, paramarg1: number): number;
    static nio_uring_register_wait_reg(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_resize_rings(paramarg0: number, paramarg1: number): number;
    static nio_uring_ring_dontfork(paramarg0: number): number;
    static nio_uring_set_iowait(paramarg0: number, paramarg1: boolean): number;
    static nio_uring_setup(paramarg0: number, paramarg1: number): number;
    static nio_uring_setup_buf_ring(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nio_uring_sq_ready(paramarg0: number): number;
    static nio_uring_sq_space_left(paramarg0: number): number;
    static nio_uring_sqe_set_buf_group(paramarg0: number, paramarg1: number): void;
    static nio_uring_sqe_set_data(paramarg0: number, paramarg1: number): void;
    static nio_uring_sqe_set_data64(paramarg0: number, paramarg1: number): void;
    static nio_uring_sqe_set_flags(paramarg0: number, paramarg1: number): void;
    static nio_uring_sqe_shift(paramarg0: number): number;
    static nio_uring_sqring_wait(paramarg0: number): number;
    static nio_uring_submit(paramarg0: number): number;
    static nio_uring_submit_and_get_events(paramarg0: number): number;
    static nio_uring_submit_and_wait(paramarg0: number, paramarg1: number): number;
    static nio_uring_submit_and_wait_min_timeout(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): number;
    static nio_uring_submit_and_wait_reg(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number): number;
    static nio_uring_submit_and_wait_timeout(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nio_uring_unregister_buf_ring(paramarg0: number, paramarg1: number): number;
    static nio_uring_unregister_buffers(paramarg0: number): number;
    static nio_uring_unregister_eventfd(paramarg0: number): number;
    static nio_uring_unregister_files(paramarg0: number): number;
    static nio_uring_unregister_iowq_aff(paramarg0: number): number;
    static nio_uring_unregister_napi(paramarg0: number, paramarg1: number): number;
    static nio_uring_unregister_personality(paramarg0: number, paramarg1: number): number;
    static nio_uring_unregister_ring_fd(paramarg0: number): number;
    static nio_uring_wait_cqe(paramarg0: number, paramarg1: number): number;
    static nio_uring_wait_cqe_nr(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_wait_cqe_timeout(paramarg0: number, paramarg1: number, paramarg2: number): number;
    static nio_uring_wait_cqes(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number): number;
    static nio_uring_wait_cqes_min_timeout(paramarg0: number, paramarg1: number, paramarg2: number, paramarg3: number, paramarg4: number, paramarg5: number): number;
    constructor()
}