import type { Device } from '../../../ai/djl/Device.d.ts'
import type { NDArray } from '../../../ai/djl/ndarray/NDArray.d.ts'
import type { NDManager } from '../../../ai/djl/ndarray/NDManager.d.ts'
import type { NDIndex } from '../../../ai/djl/ndarray/index/NDIndex.d.ts'
import type { NDArrayEx } from '../../../ai/djl/ndarray/internal/NDArrayEx.d.ts'
import type { DataType } from '../../../ai/djl/ndarray/types/DataType.d.ts'
import type { Shape } from '../../../ai/djl/ndarray/types/Shape.d.ts'
import type { SparseFormat } from '../../../ai/djl/ndarray/types/SparseFormat.d.ts'
import type { ByteBuffer } from '../../../java/nio/ByteBuffer.d.ts'
import type { Function } from '../../../java/util/function/Function.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { Number } from '../../../java/lang/Number.d.ts'
export interface LazyNDArray extends NDArray, Object {
    abs(): NDArray;
    acos(): NDArray;
    acosh(): NDArray;
    add(arg0: NDArray): NDArray;
    add(arg0: Number): NDArray;
    addi(arg0: NDArray): NDArray;
    addi(arg0: Number): NDArray;
    all(): NDArray;
    allClose(arg0: NDArray): boolean;
    allClose(arg0: NDArray, arg1: number, arg2: number, arg3: boolean): boolean;
    any(): NDArray;
    argMax(): NDArray;
    argMax(arg0: number): NDArray;
    argMin(): NDArray;
    argMin(arg0: number): NDArray;
    argSort(): NDArray;
    argSort(arg0: number): NDArray;
    argSort(arg0: number, arg1: boolean): NDArray;
    asin(): NDArray;
    asinh(): NDArray;
    atan(): NDArray;
    atan2(arg0: NDArray): NDArray;
    atanh(): NDArray;
    attach(arg0: NDManager): void;
    batchDot(arg0: NDArray): NDArray;
    batchMatMul(arg0: NDArray): NDArray;
    booleanMask(arg0: NDArray): NDArray;
    booleanMask(arg0: NDArray, arg1: number): NDArray;
    broadcast(...arg0: number[]): NDArray;
    cbrt(): NDArray;
    ceil(): NDArray;
    clip(arg0: Number, arg1: Number): NDArray;
    close(): void;
    complex(): NDArray;
    concat(arg0: NDArray): NDArray;
    concat(arg0: NDArray, arg1: number): NDArray;
    conj(): NDArray;
    contentEquals(arg0: NDArray): boolean;
    contentEquals(arg0: Number): boolean;
    copyTo(arg0: NDArray): void;
    cos(): NDArray;
    cosh(): NDArray;
    countNonzero(): NDArray;
    countNonzero(arg0: number): NDArray;
    cumProd(arg0: number): NDArray;
    cumProd(arg0: number, arg1: DataType): NDArray;
    cumSum(): NDArray;
    cumSum(arg0: number): NDArray;
    detach(): void;
    diagonal(): NDArray;
    diagonal(arg0: number): NDArray;
    diagonal(arg0: number, arg1: number, arg2: number): NDArray;
    diff(arg0: number, arg1: number): NDArray;
    div(arg0: NDArray): NDArray;
    div(arg0: Number): NDArray;
    divi(arg0: NDArray): NDArray;
    divi(arg0: Number): NDArray;
    dot(arg0: NDArray): NDArray;
    duplicate(): NDArray;
    encode(): number[];
    eq(arg0: NDArray): NDArray;
    eq(arg0: Number): NDArray;
    erf(): NDArray;
    erfinv(): NDArray;
    exp(): NDArray;
    expandDims(arg0: number): NDArray;
    fft(arg0: number): NDArray;
    fft(arg0: number, arg1: number): NDArray;
    fft2(arg0: number[]): NDArray;
    flatten(): NDArray;
    flatten(arg0: number, arg1: number): NDArray;
    floor(): NDArray;
    gammaln(): NDArray;
    gather(arg0: NDArray, arg1: number): NDArray;
    gatherNd(arg0: NDArray): NDArray;
    get(arg0: NDArray): NDArray;
    get(arg0: NDManager, arg1: NDIndex): NDArray;
    get(arg0: NDManager, ...arg1: number[]): NDArray;
    get(arg0: NDIndex): NDArray;
    get(...arg0: number[]): NDArray;
    get(arg0: string, ...arg1: Object[]): NDArray;
    getBoolean(...arg0: number[]): boolean;
    getByte(...arg0: number[]): number;
    getDataType(): DataType;
    getDevice(): Device;
    getDouble(...arg0: number[]): number;
    getFloat(...arg0: number[]): number;
    getGradient(): NDArray;
    getInt(...arg0: number[]): number;
    getLong(...arg0: number[]): number;
    getManager(): NDManager;
    getNDArrayInternal(): NDArrayEx;
    getName(): string;
    getResourceNDArrays(): NDArray[];
    getScalar(...arg0: number[]): NDArray;
    getShape(): Shape;
    getSparseFormat(): SparseFormat;
    getUid(): string;
    getUint8(...arg0: number[]): number;
    gt(arg0: NDArray): NDArray;
    gt(arg0: Number): NDArray;
    gte(arg0: NDArray): NDArray;
    gte(arg0: Number): NDArray;
    hasGradient(): boolean;
    ifft(arg0: number): NDArray;
    ifft(arg0: number, arg1: number): NDArray;
    ifft2(arg0: number[]): NDArray;
    intern(arg0: NDArray): void;
    inverse(): NDArray;
    irfft(arg0: number): NDArray;
    irfft(arg0: number, arg1: number): NDArray;
    isEmpty(): boolean;
    isInfinite(): NDArray;
    isNaN(): NDArray;
    isReleased(): boolean;
    isScalar(): boolean;
    isSparse(): boolean;
    like(): NDArray;
    log(): NDArray;
    log10(): NDArray;
    log2(): NDArray;
    logSoftmax(arg0: number): NDArray;
    logicalAnd(arg0: NDArray): NDArray;
    logicalNot(): NDArray;
    logicalOr(arg0: NDArray): NDArray;
    logicalXor(arg0: NDArray): NDArray;
    lt(arg0: NDArray): NDArray;
    lt(arg0: Number): NDArray;
    lte(arg0: NDArray): NDArray;
    lte(arg0: Number): NDArray;
    matMul(arg0: NDArray): NDArray;
    max(): NDArray;
    max(arg0: number[]): NDArray;
    maximum(arg0: NDArray): NDArray;
    maximum(arg0: Number): NDArray;
    mean(): NDArray;
    mean(arg0: number[]): NDArray;
    median(): NDArray;
    min(): NDArray;
    min(arg0: number[]): NDArray;
    minimum(arg0: NDArray): NDArray;
    minimum(arg0: Number): NDArray;
    mod(arg0: NDArray): NDArray;
    mod(arg0: Number): NDArray;
    modi(arg0: NDArray): NDArray;
    modi(arg0: Number): NDArray;
    mul(arg0: NDArray): NDArray;
    mul(arg0: Number): NDArray;
    muli(arg0: NDArray): NDArray;
    muli(arg0: Number): NDArray;
    neg(): NDArray;
    negi(): NDArray;
    neq(arg0: NDArray): NDArray;
    neq(arg0: Number): NDArray;
    none(): NDArray;
    nonzero(): NDArray;
    norm(): NDArray;
    norm(arg0: number[]): NDArray;
    norm(arg0: number[], arg1: boolean): NDArray;
    normalize(): NDArray;
    normalize(arg0: number, arg1: number): NDArray;
    normalize(arg0: number, arg1: number, arg2: number): NDArray;
    oneHot(arg0: number): NDArray;
    oneHot(arg0: number, arg1: DataType): NDArray;
    oneHot(arg0: number, arg1: number, arg2: number, arg3: DataType): NDArray;
    onesLike(): NDArray;
    pad(arg0: Shape, arg1: number): NDArray;
    percentile(arg0: Number): NDArray;
    pow(arg0: NDArray): NDArray;
    pow(arg0: Number): NDArray;
    powi(arg0: NDArray): NDArray;
    powi(arg0: Number): NDArray;
    prod(): NDArray;
    prod(arg0: number[]): NDArray;
    put(arg0: NDArray, arg1: NDArray): NDArray;
    real(): NDArray;
    repeat(arg0: Shape): NDArray;
    repeat(arg0: number, arg1: number): NDArray;
    repeat(arg0: number): NDArray;
    reshape(...arg0: number[]): NDArray;
    rfft(arg0: number): NDArray;
    rfft(arg0: number, arg1: number): NDArray;
    round(): NDArray;
    scaleGradient(arg0: number): NDArray;
    scatter(arg0: NDArray, arg1: NDArray, arg2: number): NDArray;
    sequenceMask(arg0: NDArray): NDArray;
    sequenceMask(arg0: NDArray, arg1: number): NDArray;
    set(arg0: NDArray, arg1: Number): void;
    set(arg0: NDIndex, arg1: NDArray): void;
    set(arg0: NDIndex, arg1: (param0: NDArray) => NDArray): void;
    set(arg0: NDIndex, arg1: Number): void;
    set(arg0: number[]): void;
    setName(arg0: string): void;
    setRequiresGradient(arg0: boolean): void;
    setScalar(arg0: NDIndex, arg1: Number): void;
    shapeEquals(arg0: NDArray): boolean;
    sign(): NDArray;
    signi(): NDArray;
    sin(): NDArray;
    sinh(): NDArray;
    size(): number;
    size(arg0: number): number;
    softmax(arg0: number): NDArray;
    sort(): NDArray;
    sort(arg0: number): NDArray;
    split(arg0: number): (Object | null)[];
    split(arg0: number, arg1: number): (Object | null)[];
    split(arg0: number[]): (Object | null)[];
    sqrt(): NDArray;
    square(): NDArray;
    squeeze(): NDArray;
    squeeze(arg0: number): NDArray;
    stack(arg0: NDArray): NDArray;
    stack(arg0: NDArray, arg1: number): NDArray;
    stft(arg0: number, arg1: number, arg2: boolean, arg3: NDArray, arg4: boolean): NDArray;
    stft(arg0: number, arg1: number, arg2: boolean, arg3: NDArray, arg4: boolean, arg5: boolean): NDArray;
    stopGradient(): NDArray;
    sub(arg0: NDArray): NDArray;
    sub(arg0: Number): NDArray;
    subi(arg0: NDArray): NDArray;
    subi(arg0: Number): NDArray;
    sum(): NDArray;
    sum(arg0: number[]): NDArray;
    swapAxes(arg0: number, arg1: number): NDArray;
    take(arg0: NDArray): NDArray;
    take(arg0: NDManager, arg1: NDArray): NDArray;
    tan(): NDArray;
    tanh(): NDArray;
    tempAttach(arg0: NDManager): void;
    tile(arg0: Shape): NDArray;
    tile(arg0: number, arg1: number): NDArray;
    tile(arg0: number): NDArray;
    toArray(): Number[];
    toBooleanArray(): (Object | null)[];
    toByteArray(): number[];
    toByteBuffer(): ByteBuffer;
    toByteBuffer(arg0: boolean): ByteBuffer;
    toDebugString(): string;
    toDebugString(arg0: boolean): string;
    toDebugString(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean): string;
    toDegrees(): NDArray;
    toDense(): NDArray;
    toDevice(arg0: Device, arg1: boolean): NDArray;
    toDoubleArray(): number[];
    toFloatArray(): number[];
    toIntArray(): number[];
    toLongArray(): number[];
    toRadians(): NDArray;
    toShortArray(): number[];
    toSparse(arg0: SparseFormat): NDArray;
    toStringArray(): string[];
    toType(arg0: DataType, arg1: boolean): NDArray;
    toUint8Array(): number[];
    toUnsignedIntArray(): number[];
    toUnsignedShortArray(): number[];
    topK(arg0: number, arg1: number): (Object | null)[];
    trace(): NDArray;
    trace(arg0: number): NDArray;
    trace(arg0: number, arg1: number, arg2: number): NDArray;
    transpose(): NDArray;
    trunc(): NDArray;
    unique(): (Object | null)[];
    unique(arg0: boolean, arg1: boolean, arg2: boolean): (Object | null)[];
    waitAll(): void;
    waitToRead(): void;
    waitToWrite(): void;
    xlogy(arg0: NDArray): NDArray;
    zerosLike(): NDArray;
}