import type { NDArray } from '../../../ai/djl/ndarray/NDArray.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { Number } from '../../../java/lang/Number.d.ts'
export class NDArrays extends Object {
    static add(paramarg0: NDArray, paramarg1: Number): NDArray;
    static add(paramarg0: (Object | null)[]): NDArray;
    static add(paramarg0: Number, paramarg1: NDArray): NDArray;
    static addi(paramarg0: NDArray, paramarg1: Number): NDArray;
    static addi(paramarg0: (Object | null)[]): NDArray;
    static addi(paramarg0: Number, paramarg1: NDArray): NDArray;
    static allClose(paramarg0: NDArray, paramarg1: NDArray): boolean;
    static allClose(paramarg0: NDArray, paramarg1: NDArray, paramarg2: number, paramarg3: number, paramarg4: boolean): boolean;
    static booleanMask(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static booleanMask(paramarg0: NDArray, paramarg1: NDArray, paramarg2: number): NDArray;
    static concat(paramarg0: (Object | null)[]): NDArray;
    static concat(paramarg0: (Object | null)[], paramarg1: number): NDArray;
    static contentEquals(paramarg0: NDArray, paramarg1: NDArray): boolean;
    static contentEquals(paramarg0: NDArray, paramarg1: Number): boolean;
    static div(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static div(paramarg0: NDArray, paramarg1: Number): NDArray;
    static div(paramarg0: Number, paramarg1: NDArray): NDArray;
    static divi(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static divi(paramarg0: NDArray, paramarg1: Number): NDArray;
    static divi(paramarg0: Number, paramarg1: NDArray): NDArray;
    static dot(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static eq(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static eq(paramarg0: NDArray, paramarg1: Number): NDArray;
    static eq(paramarg0: Number, paramarg1: NDArray): NDArray;
    static erf(paramarg0: NDArray): NDArray;
    static erfinv(paramarg0: NDArray): NDArray;
    static gt(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static gt(paramarg0: NDArray, paramarg1: Number): NDArray;
    static gt(paramarg0: Number, paramarg1: NDArray): NDArray;
    static gte(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static gte(paramarg0: NDArray, paramarg1: Number): NDArray;
    static gte(paramarg0: Number, paramarg1: NDArray): NDArray;
    static logicalAnd(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static logicalOr(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static logicalXor(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static lt(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static lt(paramarg0: NDArray, paramarg1: Number): NDArray;
    static lt(paramarg0: Number, paramarg1: NDArray): NDArray;
    static lte(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static lte(paramarg0: NDArray, paramarg1: Number): NDArray;
    static lte(paramarg0: Number, paramarg1: NDArray): NDArray;
    static matMul(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static maximum(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static maximum(paramarg0: NDArray, paramarg1: Number): NDArray;
    static maximum(paramarg0: Number, paramarg1: NDArray): NDArray;
    static minimum(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static minimum(paramarg0: NDArray, paramarg1: Number): NDArray;
    static minimum(paramarg0: Number, paramarg1: NDArray): NDArray;
    static mod(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static mod(paramarg0: NDArray, paramarg1: Number): NDArray;
    static mod(paramarg0: Number, paramarg1: NDArray): NDArray;
    static modi(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static modi(paramarg0: NDArray, paramarg1: Number): NDArray;
    static modi(paramarg0: Number, paramarg1: NDArray): NDArray;
    static mul(paramarg0: NDArray, paramarg1: Number): NDArray;
    static mul(paramarg0: (Object | null)[]): NDArray;
    static mul(paramarg0: Number, paramarg1: NDArray): NDArray;
    static muli(paramarg0: NDArray, paramarg1: Number): NDArray;
    static muli(paramarg0: (Object | null)[]): NDArray;
    static muli(paramarg0: Number, paramarg1: NDArray): NDArray;
    static neq(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static neq(paramarg0: NDArray, paramarg1: Number): NDArray;
    static neq(paramarg0: Number, paramarg1: NDArray): NDArray;
    static pow(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static pow(paramarg0: NDArray, paramarg1: Number): NDArray;
    static pow(paramarg0: Number, paramarg1: NDArray): NDArray;
    static powi(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static powi(paramarg0: NDArray, paramarg1: Number): NDArray;
    static powi(paramarg0: Number, paramarg1: NDArray): NDArray;
    static sequenceMask(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static sequenceMask(paramarg0: NDArray, paramarg1: NDArray, paramarg2: number): NDArray;
    static shapeEquals(paramarg0: NDArray, paramarg1: NDArray): boolean;
    static stack(paramarg0: (Object | null)[]): NDArray;
    static stack(paramarg0: (Object | null)[], paramarg1: number): NDArray;
    static sub(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static sub(paramarg0: NDArray, paramarg1: Number): NDArray;
    static sub(paramarg0: Number, paramarg1: NDArray): NDArray;
    static subi(paramarg0: NDArray, paramarg1: NDArray): NDArray;
    static subi(paramarg0: NDArray, paramarg1: Number): NDArray;
    static subi(paramarg0: Number, paramarg1: NDArray): NDArray;
    static where(paramarg0: NDArray, paramarg1: NDArray, paramarg2: NDArray): NDArray;
    private constructor()
}