import type { File } from '../../../java/io/File.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
import type { OptionsAccessor } from '../../../net/caffeinemc/mods/sodium/mixin/features/gui/OptionsAccessor.d.ts'
import type { AttackIndicatorStatus } from '../../../net/minecraft/client/AttackIndicatorStatus.d.ts'
import type { CameraType } from '../../../net/minecraft/client/CameraType.d.ts'
import type { CloudStatus } from '../../../net/minecraft/client/CloudStatus.d.ts'
import type { GraphicsPreset } from '../../../net/minecraft/client/GraphicsPreset.d.ts'
import type { InactivityFpsLimit } from '../../../net/minecraft/client/InactivityFpsLimit.d.ts'
import type { KeyMapping } from '../../../net/minecraft/client/KeyMapping.d.ts'
import type { Minecraft } from '../../../net/minecraft/client/Minecraft.d.ts'
import type { MusicToastDisplayState } from '../../../net/minecraft/client/MusicToastDisplayState.d.ts'
import type { NarratorStatus } from '../../../net/minecraft/client/NarratorStatus.d.ts'
import type { OptionInstance } from '../../../net/minecraft/client/OptionInstance.d.ts'
import type { Options$FieldAccess } from '../../../net/minecraft/client/Options$FieldAccess.d.ts'
import type { Options$OptionAccess } from '../../../net/minecraft/client/Options$OptionAccess.d.ts'
import type { PreferredGraphicsApi } from '../../../net/minecraft/client/PreferredGraphicsApi.d.ts'
import type { PresenceSharing } from '../../../net/minecraft/client/PresenceSharing.d.ts'
import type { PrioritizeChunkUpdates } from '../../../net/minecraft/client/PrioritizeChunkUpdates.d.ts'
import type { TextureFilteringMethod } from '../../../net/minecraft/client/TextureFilteringMethod.d.ts'
import type { MusicManager$MusicFrequency } from '../../../net/minecraft/client/sounds/MusicManager$MusicFrequency.d.ts'
import type { TutorialSteps } from '../../../net/minecraft/client/tutorial/TutorialSteps.d.ts'
import type { CompoundTag } from '../../../net/minecraft/nbt/CompoundTag.d.ts'
import type { Component } from '../../../net/minecraft/network/chat/Component.d.ts'
import type { ClientInformation } from '../../../net/minecraft/server/level/ClientInformation.d.ts'
import type { ParticleStatus } from '../../../net/minecraft/server/level/ParticleStatus.d.ts'
import type { PackRepository } from '../../../net/minecraft/server/packs/repository/PackRepository.d.ts'
import type { SoundSource } from '../../../net/minecraft/sounds/SoundSource.d.ts'
import type { HumanoidArm } from '../../../net/minecraft/world/entity/HumanoidArm.d.ts'
import type { ChatVisiblity } from '../../../net/minecraft/world/entity/player/ChatVisiblity.d.ts'
import type { PlayerModelPart } from '../../../net/minecraft/world/entity/player/PlayerModelPart.d.ts'
export class Options extends Object implements OptionsAccessor {
    static AUTO_GUI_SCALE: number;
    static RENDER_DISTANCE_EXTREME: number;
    static RENDER_DISTANCE_FAR: number;
    static RENDER_DISTANCE_REALLY_FAR: number;
    static RENDER_DISTANCE_SHORT: number;
    static UNLIMITED_FRAMERATE_CUTOFF: number;
    static genericValueLabel(paramcaption: Component, paramvalue: number): Component;
    static genericValueLabel(paramcaption: Component, paramvalue: Component): Component;
    static genericValueOrOffLabel(paramcaption: Component, paramvalue: number): Component;
    static isSoundDeviceDefault(paramdeviceName: string): boolean;
    constructor(minecraft: Minecraft, workingDirectory: File)
    advancedItemTooltips: boolean;
    // private allowCursorChanges: OptionInstance<boolean>;
    // private allowServerListing: OptionInstance<boolean>;
    // private ambientOcclusion: OptionInstance<boolean>;
    // private attackIndicator: OptionInstance<AttackIndicatorStatus>;
    // private autoJump: OptionInstance<boolean>;
    // private autoSuggestions: OptionInstance<boolean>;
    // private backgroundForChatOnly: OptionInstance<boolean>;
    // private biomeBlendRadius: OptionInstance<number>;
    // private bobView: OptionInstance<boolean>;
    readonly cameraType: CameraType;
    // private chatColors: OptionInstance<boolean>;
    // private chatDelay: OptionInstance<number>;
    // private chatHeightFocused: OptionInstance<number>;
    // private chatHeightUnfocused: OptionInstance<number>;
    // private chatLineSpacing: OptionInstance<number>;
    // private chatLinks: OptionInstance<boolean>;
    // private chatLinksPrompt: OptionInstance<boolean>;
    // private chatOpacity: OptionInstance<number>;
    // private chatScale: OptionInstance<number>;
    // private chatVisibility: OptionInstance<ChatVisiblity>;
    // private chatWidth: OptionInstance<number>;
    // private chunkSectionFadeInTime: OptionInstance<number>;
    // private cloudRange: OptionInstance<number>;
    // private cutoutLeaves: OptionInstance<boolean>;
    // private damageTiltStrength: OptionInstance<number>;
    // private darkMojangStudiosBackground: OptionInstance<boolean>;
    // private darknessEffectScale: OptionInstance<number>;
    debugKeys: KeyMapping[];
    // private directionalAudio: OptionInstance<boolean>;
    // private discreteMouseScroll: OptionInstance<boolean>;
    // private enableVsync: OptionInstance<boolean>;
    // private entityDistanceScaling: OptionInstance<number>;
    // private entityShadows: OptionInstance<boolean>;
    // private exclusiveFullscreen: OptionInstance<boolean>;
    // private exclusiveFullscreenFromStartup: boolean;
    // private forceUnicodeFont: OptionInstance<boolean>;
    // private fov: OptionInstance<number>;
    // private fovEffectScale: OptionInstance<number>;
    // private framerateLimit: OptionInstance<number>;
    // private fullscreen: OptionInstance<boolean>;
    fullscreenVideoModeString: string;
    // private gamma: OptionInstance<number>;
    glDebugVerbosity: number;
    // private glintSpeed: OptionInstance<number>;
    // private glintStrength: OptionInstance<number>;
    // private graphicsPreset: OptionInstance<GraphicsPreset>;
    // private guiScale: OptionInstance<number>;
    // private hideLightningFlash: OptionInstance<boolean>;
    // private hideMatchedNames: OptionInstance<boolean>;
    hideServerAddress: boolean;
    // private hideSplashTexts: OptionInstance<boolean>;
    // private highContrast: OptionInstance<boolean>;
    // private highContrastBlockOutline: OptionInstance<boolean>;
    // private improvedTransparency: OptionInstance<boolean>;
    // private inGameNotification: OptionInstance<boolean>;
    // private inactivityFpsLimit: OptionInstance<InactivityFpsLimit>;
    incompatibleResourcePacks: string[];
    // private invertXMouse: OptionInstance<boolean>;
    // private invertYMouse: OptionInstance<boolean>;
    // private isApplyingGraphicsPreset: boolean;
    // private japaneseGlyphVariants: OptionInstance<boolean>;
    joinedFirstServer: boolean;
    keyAdvancements: KeyMapping;
    keyAttack: KeyMapping;
    keyChat: KeyMapping;
    keyCommand: KeyMapping;
    keyDebugClearChat: KeyMapping;
    keyDebugCopyLocation: KeyMapping;
    keyDebugCopyRecreateCommand: KeyMapping;
    keyDebugCrash: KeyMapping;
    keyDebugDebugOptions: KeyMapping;
    keyDebugDumpDynamicTextures: KeyMapping;
    keyDebugDumpVersion: KeyMapping;
    keyDebugFocusPause: KeyMapping;
    keyDebugFpsCharts: KeyMapping;
    keyDebugLightmapTexture: KeyMapping;
    keyDebugModifier: KeyMapping;
    keyDebugNetworkCharts: KeyMapping;
    keyDebugOverlay: KeyMapping;
    keyDebugPofilingChart: KeyMapping;
    keyDebugProfiling: KeyMapping;
    keyDebugReloadChunk: KeyMapping;
    keyDebugReloadResourcePacks: KeyMapping;
    keyDebugShowAdvancedTooltips: KeyMapping;
    keyDebugShowChunkBorders: KeyMapping;
    keyDebugShowHitboxes: KeyMapping;
    keyDebugSpectate: KeyMapping;
    keyDebugSwitchGameMode: KeyMapping;
    keyDown: KeyMapping;
    keyDrop: KeyMapping;
    keyFriends: KeyMapping;
    keyFullscreen: KeyMapping;
    keyHotbarSlots: KeyMapping[];
    keyInventory: KeyMapping;
    keyJump: KeyMapping;
    keyLeft: KeyMapping;
    keyLoadHotbarActivator: KeyMapping;
    keyMappings: KeyMapping[];
    keyPickItem: KeyMapping;
    keyPlayerList: KeyMapping;
    keyQuickActions: KeyMapping;
    keyRight: KeyMapping;
    keySaveHotbarActivator: KeyMapping;
    keyScreenshot: KeyMapping;
    keyShift: KeyMapping;
    keySmoothCamera: KeyMapping;
    keySocialInteractions: KeyMapping;
    keySpectatorHotbar: KeyMapping;
    keySpectatorOutlines: KeyMapping;
    keySprint: KeyMapping;
    keySwapOffhand: KeyMapping;
    keyToggleGui: KeyMapping;
    keyTogglePerspective: KeyMapping;
    keyToggleSpectatorShaderEffects: KeyMapping;
    keyUp: KeyMapping;
    keyUse: KeyMapping;
    languageCode: string;
    lastMpIp: string;
    // private mainHand: OptionInstance<HumanoidArm>;
    // private maxAnisotropyBit: OptionInstance<number>;
    // private minecraft: Minecraft;
    // private mipmapLevels: OptionInstance<number>;
    modelParts: PlayerModelPart[];
    // private mouseWheelSensitivity: OptionInstance<number>;
    // private musicFrequency: OptionInstance<MusicManager$MusicFrequency>;
    // private musicToast: OptionInstance<MusicToastDisplayState>;
    // private narrator: OptionInstance<NarratorStatus>;
    // private narratorHotkey: OptionInstance<boolean>;
    // private notificationDisplayTime: OptionInstance<number>;
    onboardAccessibility: boolean;
    // private onlyShowSecureChat: OptionInstance<boolean>;
    // private operatorItemsTab: OptionInstance<boolean>;
    // private optionsFile: File;
    overrideHeight: number;
    overrideWidth: number;
    // private panoramaSpeed: OptionInstance<number>;
    // private particles: OptionInstance<ParticleStatus>;
    pauseOnLostFocus: boolean;
    // private preferredGraphicsBackend: OptionInstance<PreferredGraphicsApi>;
    // private preferredGraphicsBackendFromStartup: PreferredGraphicsApi;
    // private prioritizeChunkUpdates: OptionInstance<PrioritizeChunkUpdates>;
    // private rawMouseInput: OptionInstance<boolean>;
    // private realmsNotifications: OptionInstance<boolean>;
    // private reducedDebugInfo: OptionInstance<boolean>;
    // private renderDistance: OptionInstance<number>;
    resourcePacks: string[];
    // private rotateWithMinecart: OptionInstance<boolean>;
    // private saveChatDrafts: OptionInstance<boolean>;
    // private screenEffectScale: OptionInstance<number>;
    // private sensitivity: OptionInstance<number>;
    readonly serverRenderDistance: number;
    // private sharePresence: OptionInstance<PresenceSharing>;
    // private showAutosaveIndicator: OptionInstance<boolean>;
    // private showSubtitles: OptionInstance<boolean>;
    // private simulationDistance: OptionInstance<number>;
    skipMultiplayerWarning: boolean;
    smoothCamera: boolean;
    // private soundDevice: OptionInstance<string>;
    // private soundSourceVolumes: { [key in SoundSource]: OptionInstance<number> };
    // private sprintWindow: OptionInstance<number>;
    startedCleanly: boolean;
    syncWrites: boolean;
    // private telemetryOptInExtra: OptionInstance<boolean>;
    // private textBackgroundOpacity: OptionInstance<number>;
    // private textureFiltering: OptionInstance<TextureFilteringMethod>;
    // private toggleAttack: OptionInstance<boolean>;
    // private toggleCrouch: OptionInstance<boolean>;
    // private toggleSprint: OptionInstance<boolean>;
    // private toggleUse: OptionInstance<boolean>;
    tutorialStep: TutorialSteps;
    // private useNativeTransport: boolean;
    // private vignette: OptionInstance<boolean>;
    // private weatherRadius: OptionInstance<number>;
    allowCursorChanges(): OptionInstance<boolean>;
    allowServerListing(): OptionInstance<boolean>;
    ambientOcclusion(): OptionInstance<boolean>;
    applyGraphicsPreset(value: GraphicsPreset): void;
    attackIndicator(): OptionInstance<AttackIndicatorStatus>;
    autoJump(): OptionInstance<boolean>;
    autoSuggestions(): OptionInstance<boolean>;
    backgroundForChatOnly(): OptionInstance<boolean>;
    biomeBlendRadius(): OptionInstance<number>;
    bobView(): OptionInstance<boolean>;
    broadcastOptions(): void;
    buildPlayerInformation(): ClientInformation;
    chatColors(): OptionInstance<boolean>;
    chatDelay(): OptionInstance<number>;
    chatHeightFocused(): OptionInstance<number>;
    chatHeightUnfocused(): OptionInstance<number>;
    chatLineSpacing(): OptionInstance<number>;
    chatLinks(): OptionInstance<boolean>;
    chatLinksPrompt(): OptionInstance<boolean>;
    chatOpacity(): OptionInstance<number>;
    chatScale(): OptionInstance<number>;
    chatVisibility(): OptionInstance<ChatVisiblity>;
    chatWidth(): OptionInstance<number>;
    chunkSectionFadeInTime(): OptionInstance<number>;
    cloudRange(): OptionInstance<number>;
    cloudStatus(): OptionInstance<CloudStatus>;
    // private createSoundSliderOptionInstance(captionId: string, category: SoundSource): OptionInstance<number>;
    cutoutLeaves(): OptionInstance<boolean>;
    damageTiltStrength(): OptionInstance<number>;
    darkMojangStudiosBackground(): OptionInstance<boolean>;
    darknessEffectScale(): OptionInstance<number>;
    // private dataFix(tag: CompoundTag): CompoundTag;
    directionalAudio(): OptionInstance<boolean>;
    discreteMouseScroll(): OptionInstance<boolean>;
    dumpOptionsForReport(): string;
    enableVsync(): OptionInstance<boolean>;
    entityDistanceScaling(): OptionInstance<number>;
    entityShadows(): OptionInstance<boolean>;
    exclusiveFullscreen(): OptionInstance<boolean>;
    forceUnicodeFont(): OptionInstance<boolean>;
    fov(): OptionInstance<number>;
    fovEffectScale(): OptionInstance<number>;
    framerateLimit(): OptionInstance<number>;
    fullscreen(): OptionInstance<boolean>;
    gamma(): OptionInstance<number>;
    getBackgroundColor(defaultOpacity: number): number;
    getBackgroundColor(defaultColor: number): number;
    getBackgroundOpacity(defaultOpacity: number): number;
    getCameraType(): CameraType;
    getCloudStatus(): CloudStatus;
    getEffectiveRenderDistance(): number;
    getFile(): File;
    getFinalSoundSourceVolume(source: SoundSource): number;
    // private getFullscreenVideoModeString(): string;
    getMenuBackgroundBlurriness(): number;
    getSoundSourceOptionInstance(source: SoundSource): OptionInstance<number>;
    getSoundSourceVolume(source: SoundSource): number;
    glintSpeed(): OptionInstance<number>;
    glintStrength(): OptionInstance<number>;
    graphicsPreset(): OptionInstance<GraphicsPreset>;
    guiScale(): OptionInstance<number>;
    hideLightningFlash(): OptionInstance<boolean>;
    hideMatchedNames(): OptionInstance<boolean>;
    hideSplashTexts(): OptionInstance<boolean>;
    highContrast(): OptionInstance<boolean>;
    highContrastBlockOutline(): OptionInstance<boolean>;
    improvedTransparency(): OptionInstance<boolean>;
    inGameNotification(): OptionInstance<boolean>;
    inactivityFpsLimit(): OptionInstance<InactivityFpsLimit>;
    invertMouseX(): OptionInstance<boolean>;
    invertMouseY(): OptionInstance<boolean>;
    // private iris$resetFramerateLimit(arg0: Options$FieldAccess, arg1: string, arg2: OptionInstance<Object>): void;
    isModelPartEnabled(part: PlayerModelPart): boolean;
    isRestartRequiredToApplyVideoSettings(): boolean;
    japaneseGlyphVariants(): OptionInstance<boolean>;
    load(): void;
    loadSelectedResourcePacks(repository: PackRepository): void;
    mainHand(): OptionInstance<HumanoidArm>;
    maxAnisotropyBit(): OptionInstance<number>;
    maxAnisotropyValue(): number;
    menuBackgroundBlurriness(): OptionInstance<number>;
    mipmapLevels(): OptionInstance<number>;
    mouseWheelSensitivity(): OptionInstance<number>;
    musicFrequency(): OptionInstance<MusicManager$MusicFrequency>;
    musicToast(): OptionInstance<MusicToastDisplayState>;
    narrator(): OptionInstance<NarratorStatus>;
    narratorHotkey(): OptionInstance<boolean>;
    notificationDisplayTime(): OptionInstance<number>;
    onboardingAccessibilityFinished(): void;
    onlyShowSecureChat(): OptionInstance<boolean>;
    operatorItemsTab(): OptionInstance<boolean>;
    panoramaSpeed(): OptionInstance<number>;
    particles(): OptionInstance<ParticleStatus>;
    preferredGraphicsBackend(): OptionInstance<PreferredGraphicsApi>;
    prioritizeChunkUpdates(): OptionInstance<PrioritizeChunkUpdates>;
    // private processDumpedOptions(access: Options$OptionAccess): void;
    // private processOptions(access: Options$FieldAccess): void;
    rawMouseInput(): OptionInstance<boolean>;
    realmsNotifications(): OptionInstance<boolean>;
    reducedDebugInfo(): OptionInstance<boolean>;
    renderDistance(): OptionInstance<number>;
    rotateWithMinecart(): OptionInstance<boolean>;
    save(): void;
    saveChatDrafts(): OptionInstance<boolean>;
    screenEffectScale(): OptionInstance<number>;
    sensitivity(): OptionInstance<number>;
    setCameraType(cameraType: CameraType): void;
    // private setGraphicsPresetToCustom(): void;
    setModelPart(part: PlayerModelPart, visible: boolean): void;
    setServerRenderDistance(serverRenderDistance: number): void;
    sharePresence(): OptionInstance<PresenceSharing>;
    showAutosaveIndicator(): OptionInstance<boolean>;
    showSubtitles(): OptionInstance<boolean>;
    simulationDistance(): OptionInstance<number>;
    sodium$initialExclusiveFullscreen(): boolean;
    soundDevice(): OptionInstance<string>;
    sprintWindow(): OptionInstance<number>;
    telemetryOptInExtra(): OptionInstance<boolean>;
    textBackgroundOpacity(): OptionInstance<number>;
    textureFiltering(): OptionInstance<TextureFilteringMethod>;
    toggleAttack(): OptionInstance<boolean>;
    toggleCrouch(): OptionInstance<boolean>;
    toggleSprint(): OptionInstance<boolean>;
    toggleUse(): OptionInstance<boolean>;
    updateResourcePacks(packRepository: PackRepository): void;
    useNativeTransport(): boolean;
    vignette(): OptionInstance<boolean>;
    weatherRadius(): OptionInstance<number>;
}