import type { Object } from '../../../java/lang/Object.d.ts'
export class HttpHeaders extends Object {
    static ALPN: string;
    static Accept: string;
    static AcceptCharset: string;
    static AcceptEncoding: string;
    static AcceptLanguage: string;
    static AcceptRanges: string;
    static AccessControlAllowCredentials: string;
    static AccessControlAllowHeaders: string;
    static AccessControlAllowMethods: string;
    static AccessControlAllowOrigin: string;
    static AccessControlExposeHeaders: string;
    static AccessControlMaxAge: string;
    static AccessControlRequestHeaders: string;
    static AccessControlRequestMethod: string;
    static Age: string;
    static Allow: string;
    static AuthenticationInfo: string;
    static Authorization: string;
    static CacheControl: string;
    static Connection: string;
    static ContentDisposition: string;
    static ContentEncoding: string;
    static ContentLanguage: string;
    static ContentLength: string;
    static ContentLocation: string;
    static ContentRange: string;
    static ContentType: string;
    static Cookie: string;
    static DASL: string;
    static DAV: string;
    static Date: string;
    static Depth: string;
    static Destination: string;
    static ETag: string;
    static Expect: string;
    static Expires: string;
    static Forwarded: string;
    static From: string;
    static HTTP2Settings: string;
    static Host: string;
    static INSTANCE: HttpHeaders;
    static If: string;
    static IfMatch: string;
    static IfModifiedSince: string;
    static IfNoneMatch: string;
    static IfRange: string;
    static IfScheduleTagMatch: string;
    static IfUnmodifiedSince: string;
    static LastEventID: string;
    static LastModified: string;
    static Link: string;
    static Location: string;
    static LockToken: string;
    static MIMEVersion: string;
    static MaxForwards: string;
    static OrderingType: string;
    static Origin: string;
    static Overwrite: string;
    static Position: string;
    static Pragma: string;
    static Prefer: string;
    static PreferenceApplied: string;
    static ProxyAuthenticate: string;
    static ProxyAuthenticationInfo: string;
    static ProxyAuthorization: string;
    static PublicKeyPins: string;
    static PublicKeyPinsReportOnly: string;
    static Range: string;
    static Referrer: string;
    static RetryAfter: string;
    static SLUG: string;
    static ScheduleReply: string;
    static ScheduleTag: string;
    static SecWebSocketAccept: string;
    static SecWebSocketExtensions: string;
    static SecWebSocketKey: string;
    static SecWebSocketProtocol: string;
    static SecWebSocketVersion: string;
    static Server: string;
    static SetCookie: string;
    static StrictTransportSecurity: string;
    static TDMPolicy: string;
    static TDMReservation: string;
    static TE: string;
    static Timeout: string;
    static Trailer: string;
    static TransferEncoding: string;
    static Upgrade: string;
    static UserAgent: string;
    static Vary: string;
    static Via: string;
    static WWWAuthenticate: string;
    static Warning: string;
    static XCorrelationId: string;
    static XForwardedFor: string;
    static XForwardedHost: string;
    static XForwardedPort: string;
    static XForwardedProto: string;
    static XForwardedServer: string;
    static XHttpMethodOverride: string;
    static XRequestId: string;
    static XTotalCount: string;
    readonly ALPN: string;
    Accept: string;
    AcceptCharset: string;
    AcceptEncoding: string;
    AcceptLanguage: string;
    AcceptRanges: string;
    AccessControlAllowCredentials: string;
    AccessControlAllowHeaders: string;
    AccessControlAllowMethods: string;
    AccessControlAllowOrigin: string;
    AccessControlExposeHeaders: string;
    AccessControlMaxAge: string;
    AccessControlRequestHeaders: string;
    AccessControlRequestMethod: string;
    Age: string;
    Allow: string;
    AuthenticationInfo: string;
    Authorization: string;
    CacheControl: string;
    Connection: string;
    ContentDisposition: string;
    ContentEncoding: string;
    ContentLanguage: string;
    ContentLength: string;
    ContentLocation: string;
    ContentRange: string;
    ContentType: string;
    Cookie: string;
    readonly DASL: string;
    readonly DAV: string;
    Date: string;
    Depth: string;
    Destination: string;
    readonly ETag: string;
    Expect: string;
    Expires: string;
    Forwarded: string;
    From: string;
    readonly HTTP2Settings: string;
    Host: string;
    If: string;
    IfMatch: string;
    IfModifiedSince: string;
    IfNoneMatch: string;
    IfRange: string;
    IfScheduleTagMatch: string;
    IfUnmodifiedSince: string;
    LastEventID: string;
    LastModified: string;
    Link: string;
    Location: string;
    LockToken: string;
    readonly MIMEVersion: string;
    MaxForwards: string;
    OrderingType: string;
    Origin: string;
    Overwrite: string;
    Position: string;
    Pragma: string;
    Prefer: string;
    PreferenceApplied: string;
    ProxyAuthenticate: string;
    ProxyAuthenticationInfo: string;
    ProxyAuthorization: string;
    PublicKeyPins: string;
    PublicKeyPinsReportOnly: string;
    Range: string;
    Referrer: string;
    RetryAfter: string;
    readonly SLUG: string;
    ScheduleReply: string;
    ScheduleTag: string;
    SecWebSocketAccept: string;
    SecWebSocketExtensions: string;
    SecWebSocketKey: string;
    SecWebSocketProtocol: string;
    SecWebSocketVersion: string;
    Server: string;
    SetCookie: string;
    StrictTransportSecurity: string;
    TDMPolicy: string;
    TDMReservation: string;
    readonly TE: string;
    Timeout: string;
    Trailer: string;
    TransferEncoding: string;
    /*not mapped: */ getUnsafeHeaders(): string[];
    // private UnsafeHeadersArray: string[];
    // private UnsafeHeadersList: string[];
    /*not mapped: */ getUnsafeHeadersList(): string[];
    Upgrade: string;
    UserAgent: string;
    Vary: string;
    Via: string;
    readonly WWWAuthenticate: string;
    Warning: string;
    readonly XCorrelationId: string;
    readonly XForwardedFor: string;
    readonly XForwardedHost: string;
    readonly XForwardedPort: string;
    readonly XForwardedProto: string;
    readonly XForwardedServer: string;
    readonly XHttpMethodOverride: string;
    readonly XRequestId: string;
    readonly XTotalCount: string;
    checkHeaderName(name: string): void;
    checkHeaderValue(value: string): void;
    getALPN(): string;
    getAccept(): string;
    getAcceptCharset(): string;
    getAcceptEncoding(): string;
    getAcceptLanguage(): string;
    getAcceptRanges(): string;
    getAccessControlAllowCredentials(): string;
    getAccessControlAllowHeaders(): string;
    getAccessControlAllowMethods(): string;
    getAccessControlAllowOrigin(): string;
    getAccessControlExposeHeaders(): string;
    getAccessControlMaxAge(): string;
    getAccessControlRequestHeaders(): string;
    getAccessControlRequestMethod(): string;
    getAge(): string;
    getAllow(): string;
    getAuthenticationInfo(): string;
    getAuthorization(): string;
    getCacheControl(): string;
    getConnection(): string;
    getContentDisposition(): string;
    getContentEncoding(): string;
    getContentLanguage(): string;
    getContentLength(): string;
    getContentLocation(): string;
    getContentRange(): string;
    getContentType(): string;
    getCookie(): string;
    getDASL(): string;
    getDAV(): string;
    getDate(): string;
    getDepth(): string;
    getDestination(): string;
    getETag(): string;
    getExpect(): string;
    getExpires(): string;
    getForwarded(): string;
    getFrom(): string;
    getHTTP2Settings(): string;
    getHost(): string;
    getIf(): string;
    getIfMatch(): string;
    getIfModifiedSince(): string;
    getIfNoneMatch(): string;
    getIfRange(): string;
    getIfScheduleTagMatch(): string;
    getIfUnmodifiedSince(): string;
    getLastEventID(): string;
    getLastModified(): string;
    getLink(): string;
    getLocation(): string;
    getLockToken(): string;
    getMIMEVersion(): string;
    getMaxForwards(): string;
    getOrderingType(): string;
    getOrigin(): string;
    getOverwrite(): string;
    getPosition(): string;
    getPragma(): string;
    getPrefer(): string;
    getPreferenceApplied(): string;
    getProxyAuthenticate(): string;
    getProxyAuthenticationInfo(): string;
    getProxyAuthorization(): string;
    getPublicKeyPins(): string;
    getPublicKeyPinsReportOnly(): string;
    getRange(): string;
    getReferrer(): string;
    getRetryAfter(): string;
    getSLUG(): string;
    getScheduleReply(): string;
    getScheduleTag(): string;
    getSecWebSocketAccept(): string;
    getSecWebSocketExtensions(): string;
    getSecWebSocketKey(): string;
    getSecWebSocketProtocol(): string;
    getSecWebSocketVersion(): string;
    getServer(): string;
    getSetCookie(): string;
    getStrictTransportSecurity(): string;
    getTE(): string;
    getTimeout(): string;
    getTrailer(): string;
    getTransferEncoding(): string;
    getUpgrade(): string;
    getUserAgent(): string;
    getVary(): string;
    getVia(): string;
    getWWWAuthenticate(): string;
    getWarning(): string;
    getXCorrelationId(): string;
    getXForwardedFor(): string;
    getXForwardedHost(): string;
    getXForwardedPort(): string;
    getXForwardedProto(): string;
    getXForwardedServer(): string;
    getXHttpMethodOverride(): string;
    getXRequestId(): string;
    getXTotalCount(): string;
    isUnsafe(header: string): boolean;
}