import type { JavaMap } from '../../../JavaMap.d.ts'
import type { HttpStatusCode } from '../../../io/ktor/http/HttpStatusCode.d.ts'
import type { Object } from '../../../java/lang/Object.d.ts'
export class HttpStatusCode$Companion extends Object {
    // private Accepted: HttpStatusCode;
    /*not mapped: */ getAccepted(): HttpStatusCode;
    // private BadGateway: HttpStatusCode;
    /*not mapped: */ getBadGateway(): HttpStatusCode;
    // private BadRequest: HttpStatusCode;
    /*not mapped: */ getBadRequest(): HttpStatusCode;
    // private Conflict: HttpStatusCode;
    /*not mapped: */ getConflict(): HttpStatusCode;
    // private Continue: HttpStatusCode;
    /*not mapped: */ getContinue(): HttpStatusCode;
    // private Created: HttpStatusCode;
    /*not mapped: */ getCreated(): HttpStatusCode;
    // private ExpectationFailed: HttpStatusCode;
    /*not mapped: */ getExpectationFailed(): HttpStatusCode;
    // private FailedDependency: HttpStatusCode;
    /*not mapped: */ getFailedDependency(): HttpStatusCode;
    // private Forbidden: HttpStatusCode;
    /*not mapped: */ getForbidden(): HttpStatusCode;
    // private Found: HttpStatusCode;
    /*not mapped: */ getFound(): HttpStatusCode;
    // private GatewayTimeout: HttpStatusCode;
    /*not mapped: */ getGatewayTimeout(): HttpStatusCode;
    // private Gone: HttpStatusCode;
    /*not mapped: */ getGone(): HttpStatusCode;
    // private InsufficientStorage: HttpStatusCode;
    /*not mapped: */ getInsufficientStorage(): HttpStatusCode;
    // private InternalServerError: HttpStatusCode;
    /*not mapped: */ getInternalServerError(): HttpStatusCode;
    // private LengthRequired: HttpStatusCode;
    /*not mapped: */ getLengthRequired(): HttpStatusCode;
    // private Locked: HttpStatusCode;
    /*not mapped: */ getLocked(): HttpStatusCode;
    // private MethodNotAllowed: HttpStatusCode;
    /*not mapped: */ getMethodNotAllowed(): HttpStatusCode;
    // private MovedPermanently: HttpStatusCode;
    /*not mapped: */ getMovedPermanently(): HttpStatusCode;
    // private MultiStatus: HttpStatusCode;
    /*not mapped: */ getMultiStatus(): HttpStatusCode;
    // private MultipleChoices: HttpStatusCode;
    /*not mapped: */ getMultipleChoices(): HttpStatusCode;
    // private NoContent: HttpStatusCode;
    /*not mapped: */ getNoContent(): HttpStatusCode;
    // private NonAuthoritativeInformation: HttpStatusCode;
    /*not mapped: */ getNonAuthoritativeInformation(): HttpStatusCode;
    // private NotAcceptable: HttpStatusCode;
    /*not mapped: */ getNotAcceptable(): HttpStatusCode;
    // private NotFound: HttpStatusCode;
    /*not mapped: */ getNotFound(): HttpStatusCode;
    // private NotImplemented: HttpStatusCode;
    /*not mapped: */ getNotImplemented(): HttpStatusCode;
    // private NotModified: HttpStatusCode;
    /*not mapped: */ getNotModified(): HttpStatusCode;
    readonly OK: HttpStatusCode;
    // private PartialContent: HttpStatusCode;
    /*not mapped: */ getPartialContent(): HttpStatusCode;
    // private PayloadTooLarge: HttpStatusCode;
    /*not mapped: */ getPayloadTooLarge(): HttpStatusCode;
    // private PaymentRequired: HttpStatusCode;
    /*not mapped: */ getPaymentRequired(): HttpStatusCode;
    // private PermanentRedirect: HttpStatusCode;
    /*not mapped: */ getPermanentRedirect(): HttpStatusCode;
    // private PreconditionFailed: HttpStatusCode;
    /*not mapped: */ getPreconditionFailed(): HttpStatusCode;
    // private Processing: HttpStatusCode;
    /*not mapped: */ getProcessing(): HttpStatusCode;
    // private ProxyAuthenticationRequired: HttpStatusCode;
    /*not mapped: */ getProxyAuthenticationRequired(): HttpStatusCode;
    // private RequestHeaderFieldTooLarge: HttpStatusCode;
    /*not mapped: */ getRequestHeaderFieldTooLarge(): HttpStatusCode;
    // private RequestTimeout: HttpStatusCode;
    /*not mapped: */ getRequestTimeout(): HttpStatusCode;
    // private RequestURITooLong: HttpStatusCode;
    /*not mapped: */ getRequestURITooLong(): HttpStatusCode;
    // private RequestedRangeNotSatisfiable: HttpStatusCode;
    /*not mapped: */ getRequestedRangeNotSatisfiable(): HttpStatusCode;
    // private ResetContent: HttpStatusCode;
    /*not mapped: */ getResetContent(): HttpStatusCode;
    // private SeeOther: HttpStatusCode;
    /*not mapped: */ getSeeOther(): HttpStatusCode;
    // private ServiceUnavailable: HttpStatusCode;
    /*not mapped: */ getServiceUnavailable(): HttpStatusCode;
    // private SwitchProxy: HttpStatusCode;
    /*not mapped: */ getSwitchProxy(): HttpStatusCode;
    // private SwitchingProtocols: HttpStatusCode;
    /*not mapped: */ getSwitchingProtocols(): HttpStatusCode;
    // private TemporaryRedirect: HttpStatusCode;
    /*not mapped: */ getTemporaryRedirect(): HttpStatusCode;
    // private TooEarly: HttpStatusCode;
    /*not mapped: */ getTooEarly(): HttpStatusCode;
    // private TooManyRequests: HttpStatusCode;
    /*not mapped: */ getTooManyRequests(): HttpStatusCode;
    // private Unauthorized: HttpStatusCode;
    /*not mapped: */ getUnauthorized(): HttpStatusCode;
    // private UnprocessableEntity: HttpStatusCode;
    /*not mapped: */ getUnprocessableEntity(): HttpStatusCode;
    // private UnsupportedMediaType: HttpStatusCode;
    /*not mapped: */ getUnsupportedMediaType(): HttpStatusCode;
    // private UpgradeRequired: HttpStatusCode;
    /*not mapped: */ getUpgradeRequired(): HttpStatusCode;
    // private UseProxy: HttpStatusCode;
    /*not mapped: */ getUseProxy(): HttpStatusCode;
    // private VariantAlsoNegotiates: HttpStatusCode;
    /*not mapped: */ getVariantAlsoNegotiates(): HttpStatusCode;
    // private VersionNotSupported: HttpStatusCode;
    /*not mapped: */ getVersionNotSupported(): HttpStatusCode;
    readonly allStatusCodes: HttpStatusCode[];
    // private statusCodesMap: JavaMap<number, HttpStatusCode>;
    fromValue(value: number): HttpStatusCode;
}