import type { Object } from '../../../../../../../java/lang/Object.d.ts'
import type { Segment } from '../../../../../../../org/apache/commons/compress/harmony/unpack200/Segment.d.ts'
import type { SegmentConstantPool } from '../../../../../../../org/apache/commons/compress/harmony/unpack200/SegmentConstantPool.d.ts'
export class OperandManager extends Object {
    constructor(arg0: number[], arg1: number[], arg2: number[], arg3: number[], arg4: number[], arg5: number[], arg6: number[], arg7: number[], arg8: number[], arg9: number[], arg10: number[], arg11: number[], arg12: number[], arg13: number[], arg14: number[], arg15: number[], arg16: number[], arg17: number[], arg18: number[], arg19: number[], arg20: number[])
    // private bcByte: number[];
    // private bcByteIndex: number;
    // private bcCaseCount: number[];
    // private bcCaseCountIndex: number;
    // private bcCaseValue: number[];
    // private bcCaseValueIndex: number;
    // private bcClassRef: number[];
    // private bcClassRefIndex: number;
    // private bcDoubleRef: number[];
    // private bcDoubleRefIndex: number;
    // private bcFieldRef: number[];
    // private bcFieldRefIndex: number;
    // private bcFloatRef: number[];
    // private bcFloatRefIndex: number;
    // private bcIMethodRef: number[];
    // private bcIMethodRefIndex: number;
    // private bcInitRef: number[];
    // private bcInitRefIndex: number;
    // private bcIntRef: number[];
    // private bcIntRefIndex: number;
    // private bcLabel: number[];
    // private bcLabelIndex: number;
    // private bcLocal: number[];
    // private bcLocalIndex: number;
    // private bcLongRef: number[];
    // private bcLongRefIndex: number;
    // private bcMethodRef: number[];
    // private bcMethodRefIndex: number;
    // private bcShort: number[];
    // private bcShortIndex: number;
    // private bcStringRef: number[];
    // private bcStringRefIndex: number;
    // private bcSuperField: number[];
    // private bcSuperFieldIndex: number;
    // private bcSuperMethod: number[];
    // private bcSuperMethodIndex: number;
    // private bcThisField: number[];
    // private bcThisFieldIndex: number;
    // private bcThisMethod: number[];
    // private bcThisMethodIndex: number;
    currentClass: string;
    newClass: string;
    segment: Segment;
    superClass: string;
    // private wideByteCodeIndex: number;
    // private wideByteCodes: number[];
    getCurrentClass(): string;
    getNewClass(): string;
    getSuperClass(): string;
    globalConstantPool(): SegmentConstantPool;
    nextByte(): number;
    nextCaseCount(): number;
    nextCaseValues(): number;
    nextClassRef(): number;
    nextDoubleRef(): number;
    nextFieldRef(): number;
    nextFloatRef(): number;
    nextIMethodRef(): number;
    nextInitRef(): number;
    nextIntRef(): number;
    nextLabel(): number;
    nextLocal(): number;
    nextLongRef(): number;
    nextMethodRef(): number;
    nextShort(): number;
    nextStringRef(): number;
    nextSuperFieldRef(): number;
    nextSuperMethodRef(): number;
    nextThisFieldRef(): number;
    nextThisMethodRef(): number;
    nextWideByteCode(): number;
    setCurrentClass(arg0: string): void;
    setNewClass(arg0: string): void;
    setSegment(arg0: Segment): void;
    setSuperClass(arg0: string): void;
}