import type { ParsePosition } from '../../../../../../../../java/text/ParsePosition.d.ts'
import type { Currency } from '../../../../../../../../java/util/Currency.d.ts'
import type { Date } from '../../../../../../../../java/util/Date.d.ts'
import type { Locale } from '../../../../../../../../java/util/Locale.d.ts'
import type { Object } from '../../../../../../../../java/lang/Object.d.ts'
import type { TextTrieMap } from '../../../../../../../../org/graalvm/shadowed/com/ibm/icu/impl/TextTrieMap.d.ts'
import type { MeasureUnitImpl } from '../../../../../../../../org/graalvm/shadowed/com/ibm/icu/impl/units/MeasureUnitImpl.d.ts'
import type { DecimalFormatSymbols } from '../../../../../../../../org/graalvm/shadowed/com/ibm/icu/text/DecimalFormatSymbols.d.ts'
import type { Currency as Currency_2 } from '../../../../../../../../org/graalvm/shadowed/com/ibm/icu/util/Currency.d.ts'
import type { Currency$CurrencyStringInfo } from '../../../../../../../../org/graalvm/shadowed/com/ibm/icu/util/Currency$CurrencyStringInfo.d.ts'
import type { MeasureUnit } from '../../../../../../../../org/graalvm/shadowed/com/ibm/icu/util/MeasureUnit.d.ts'
import type { TimeUnit } from '../../../../../../../../org/graalvm/shadowed/com/ibm/icu/util/TimeUnit.d.ts'
import type { ULocale } from '../../../../../../../../org/graalvm/shadowed/com/ibm/icu/util/ULocale.d.ts'
export class CustomSymbolCurrency extends Currency_2 {
    static ACRE: MeasureUnit;
    static ACRE_FOOT: MeasureUnit;
    static AMPERE: MeasureUnit;
    static ARC_MINUTE: MeasureUnit;
    static ARC_SECOND: MeasureUnit;
    static ASTRONOMICAL_UNIT: MeasureUnit;
    static ATMOSPHERE: MeasureUnit;
    static BAR: MeasureUnit;
    static BARREL: MeasureUnit;
    static BEAUFORT: MeasureUnit;
    static BECQUEREL: MeasureUnit;
    static BIT: MeasureUnit;
    static BRITISH_THERMAL_UNIT: MeasureUnit;
    static BRITISH_THERMAL_UNIT_IT: MeasureUnit;
    static BUSHEL: MeasureUnit;
    static BU_JP: MeasureUnit;
    static BYTE: MeasureUnit;
    static CALORIE: MeasureUnit;
    static CALORIE_IT: MeasureUnit;
    static CANDELA: MeasureUnit;
    static CARAT: MeasureUnit;
    static CELSIUS: MeasureUnit;
    static CENTILITER: MeasureUnit;
    static CENTIMETER: MeasureUnit;
    static CENTURY: MeasureUnit;
    static CHAIN: MeasureUnit;
    static CHO: MeasureUnit;
    static COULOMB: MeasureUnit;
    static CUBIC_CENTIMETER: MeasureUnit;
    static CUBIC_FOOT: MeasureUnit;
    static CUBIC_INCH: MeasureUnit;
    static CUBIC_KILOMETER: MeasureUnit;
    static CUBIC_METER: MeasureUnit;
    static CUBIC_MILE: MeasureUnit;
    static CUBIC_YARD: MeasureUnit;
    static CUP: MeasureUnit;
    static CUP_IMPERIAL: MeasureUnit;
    static CUP_JP: MeasureUnit;
    static CUP_METRIC: MeasureUnit;
    static DALTON: MeasureUnit;
    static DAY: TimeUnit;
    static DAY_PERSON: MeasureUnit;
    static DECADE: MeasureUnit;
    static DECILITER: MeasureUnit;
    static DECIMETER: MeasureUnit;
    static DEGREE: MeasureUnit;
    static DESSERT_SPOON: MeasureUnit;
    static DESSERT_SPOON_IMPERIAL: MeasureUnit;
    static DOT: MeasureUnit;
    static DOT_PER_CENTIMETER: MeasureUnit;
    static DOT_PER_INCH: MeasureUnit;
    static DRAM: MeasureUnit;
    static DROP: MeasureUnit;
    static DUNAM: MeasureUnit;
    static EARTH_MASS: MeasureUnit;
    static EARTH_RADIUS: MeasureUnit;
    static ELECTRONVOLT: MeasureUnit;
    static EM: MeasureUnit;
    static FAHRENHEIT: MeasureUnit;
    static FARAD: MeasureUnit;
    static FATHOM: MeasureUnit;
    static FLUID_OUNCE: MeasureUnit;
    static FLUID_OUNCE_IMPERIAL: MeasureUnit;
    static FLUID_OUNCE_METRIC: MeasureUnit;
    static FOODCALORIE: MeasureUnit;
    static FOOT: MeasureUnit;
    static FORMAL_SYMBOL_NAME: number;
    static FORTNIGHT: MeasureUnit;
    static FUN: MeasureUnit;
    static FURLONG: MeasureUnit;
    static GALLON: MeasureUnit;
    static GALLON_IMPERIAL: MeasureUnit;
    static GASOLINE_ENERGY_DENSITY: MeasureUnit;
    static GENERIC_TEMPERATURE: MeasureUnit;
    static GIGABIT: MeasureUnit;
    static GIGABYTE: MeasureUnit;
    static GIGAHERTZ: MeasureUnit;
    static GIGAWATT: MeasureUnit;
    static GRAIN: MeasureUnit;
    static GRAM: MeasureUnit;
    static GRAY: MeasureUnit;
    static G_FORCE: MeasureUnit;
    static HECTARE: MeasureUnit;
    static HECTOLITER: MeasureUnit;
    static HECTOPASCAL: MeasureUnit;
    static HENRY: MeasureUnit;
    static HERTZ: MeasureUnit;
    static HORSEPOWER: MeasureUnit;
    static HOUR: TimeUnit;
    static INCH: MeasureUnit;
    static INCH_HG: MeasureUnit;
    static ITEM: MeasureUnit;
    static JIGGER: MeasureUnit;
    static JOULE: MeasureUnit;
    static JO_JP: MeasureUnit;
    static KARAT: MeasureUnit;
    static KATAL: MeasureUnit;
    static KELVIN: MeasureUnit;
    static KEN: MeasureUnit;
    static KILOBIT: MeasureUnit;
    static KILOBYTE: MeasureUnit;
    static KILOCALORIE: MeasureUnit;
    static KILOGRAM: MeasureUnit;
    static KILOGRAM_FORCE: MeasureUnit;
    static KILOHERTZ: MeasureUnit;
    static KILOJOULE: MeasureUnit;
    static KILOMETER: MeasureUnit;
    static KILOMETER_PER_HOUR: MeasureUnit;
    static KILOPASCAL: MeasureUnit;
    static KILOWATT: MeasureUnit;
    static KILOWATT_HOUR: MeasureUnit;
    static KILOWATT_HOUR_PER_100_KILOMETER: MeasureUnit;
    static KNOT: MeasureUnit;
    static KOKU: MeasureUnit;
    static KOSAJI: MeasureUnit;
    static LIGHT_SPEED: MeasureUnit;
    static LIGHT_YEAR: MeasureUnit;
    static LITER: MeasureUnit;
    static LITER_PER_100KILOMETERS: MeasureUnit;
    static LITER_PER_KILOMETER: MeasureUnit;
    static LONG_NAME: number;
    static LUMEN: MeasureUnit;
    static LUX: MeasureUnit;
    static MEGABIT: MeasureUnit;
    static MEGABYTE: MeasureUnit;
    static MEGAHERTZ: MeasureUnit;
    static MEGALITER: MeasureUnit;
    static MEGAPASCAL: MeasureUnit;
    static MEGAPIXEL: MeasureUnit;
    static MEGAWATT: MeasureUnit;
    static METER: MeasureUnit;
    static METER_PER_SECOND: MeasureUnit;
    static METER_PER_SECOND_SQUARED: MeasureUnit;
    static METRIC_TON: MeasureUnit;
    static MICROGRAM: MeasureUnit;
    static MICROMETER: MeasureUnit;
    static MICROSECOND: MeasureUnit;
    static MILE: MeasureUnit;
    static MILE_PER_GALLON: MeasureUnit;
    static MILE_PER_GALLON_IMPERIAL: MeasureUnit;
    static MILE_PER_HOUR: MeasureUnit;
    static MILE_SCANDINAVIAN: MeasureUnit;
    static MILLIAMPERE: MeasureUnit;
    static MILLIBAR: MeasureUnit;
    static MILLIGRAM: MeasureUnit;
    static MILLIGRAM_OFGLUCOSE_PER_DECILITER: MeasureUnit;
    static MILLIGRAM_PER_DECILITER: MeasureUnit;
    static MILLILITER: MeasureUnit;
    static MILLIMETER: MeasureUnit;
    static MILLIMETER_OF_MERCURY: MeasureUnit;
    static MILLIMOLE_PER_LITER: MeasureUnit;
    static MILLISECOND: MeasureUnit;
    static MILLIWATT: MeasureUnit;
    static MINUTE: TimeUnit;
    static MOLE: MeasureUnit;
    static MONTH: TimeUnit;
    static MONTH_PERSON: MeasureUnit;
    static NANOMETER: MeasureUnit;
    static NANOSECOND: MeasureUnit;
    static NARROW_SYMBOL_NAME: number;
    static NAUTICAL_MILE: MeasureUnit;
    static NEWTON: MeasureUnit;
    static NEWTON_METER: MeasureUnit;
    static NIGHT: MeasureUnit;
    static OFGLUCOSE: MeasureUnit;
    static OFHG: MeasureUnit;
    static OHM: MeasureUnit;
    static OSAJI: MeasureUnit;
    static OUNCE: MeasureUnit;
    static OUNCE_TROY: MeasureUnit;
    static PARSEC: MeasureUnit;
    static PART: MeasureUnit;
    static PART_PER_1E6: MeasureUnit;
    static PART_PER_1E9: MeasureUnit;
    static PART_PER_MILLION: MeasureUnit;
    static PASCAL: MeasureUnit;
    static PERCENT: MeasureUnit;
    static PERMILLE: MeasureUnit;
    static PERMYRIAD: MeasureUnit;
    static PETABYTE: MeasureUnit;
    static PICOMETER: MeasureUnit;
    static PINCH: MeasureUnit;
    static PINT: MeasureUnit;
    static PINT_IMPERIAL: MeasureUnit;
    static PINT_METRIC: MeasureUnit;
    static PIXEL: MeasureUnit;
    static PIXEL_PER_CENTIMETER: MeasureUnit;
    static PIXEL_PER_INCH: MeasureUnit;
    static PLURAL_LONG_NAME: number;
    static POINT: MeasureUnit;
    static POUND: MeasureUnit;
    static POUND_FOOT: MeasureUnit;
    static POUND_FORCE: MeasureUnit;
    static POUND_PER_SQUARE_INCH: MeasureUnit;
    static QUART: MeasureUnit;
    static QUARTER: MeasureUnit;
    static QUART_IMPERIAL: MeasureUnit;
    static RADIAN: MeasureUnit;
    static RANKINE: MeasureUnit;
    static REVOLUTION_ANGLE: MeasureUnit;
    static RIN: MeasureUnit;
    static RI_JP: MeasureUnit;
    static ROD: MeasureUnit;
    static SAI: MeasureUnit;
    static SECOND: TimeUnit;
    static SE_JP: MeasureUnit;
    static SHAKU: MeasureUnit;
    static SHAKU_CLOTH: MeasureUnit;
    static SHAKU_LENGTH: MeasureUnit;
    static SIEMENS: MeasureUnit;
    static SIEVERT: MeasureUnit;
    static SLUG: MeasureUnit;
    static SOLAR_LUMINOSITY: MeasureUnit;
    static SOLAR_MASS: MeasureUnit;
    static SOLAR_RADIUS: MeasureUnit;
    static SQUARE_CENTIMETER: MeasureUnit;
    static SQUARE_FOOT: MeasureUnit;
    static SQUARE_INCH: MeasureUnit;
    static SQUARE_KILOMETER: MeasureUnit;
    static SQUARE_METER: MeasureUnit;
    static SQUARE_MILE: MeasureUnit;
    static SQUARE_YARD: MeasureUnit;
    static STERADIAN: MeasureUnit;
    static STONE: MeasureUnit;
    static SUN: MeasureUnit;
    static SYMBOL_NAME: number;
    static TABLESPOON: MeasureUnit;
    static TEASPOON: MeasureUnit;
    static TERABIT: MeasureUnit;
    static TERABYTE: MeasureUnit;
    static TESLA: MeasureUnit;
    static THERM_US: MeasureUnit;
    static TON: MeasureUnit;
    static TONNE: MeasureUnit;
    static TO_JP: MeasureUnit;
    static VARIANT_SYMBOL_NAME: number;
    static VOLT: MeasureUnit;
    static WATT: MeasureUnit;
    static WEBER: MeasureUnit;
    static WEEK: TimeUnit;
    static WEEK_PERSON: MeasureUnit;
    static YARD: MeasureUnit;
    static YEAR: TimeUnit;
    static YEAR_PERSON: MeasureUnit;
    static findBySubType(paramsubType: string): MeasureUnit;
    static forIdentifier(paramidentifier: string): MeasureUnit;
    static fromJavaCurrency(paramcurrency: Currency): Currency_2;
    static fromMeasureUnitImpl(parammeasureUnitImpl: MeasureUnitImpl): MeasureUnit;
    static getAvailable(paramtype: string): MeasureUnit[];
    static getAvailable(): MeasureUnit[];
    static getAvailableCurrencies(): Currency_2[];
    static getAvailableCurrencyCodes(paramloc: Locale, paramd: Date): string[];
    static getAvailableCurrencyCodes(paramloc: ULocale, paramd: Date): string[];
    static getAvailableLocales(): Locale[];
    static getAvailableTypes(): string[];
    static getAvailableULocales(): ULocale[];
    static getInstance(paramtheISOCode: string): Currency_2;
    static getInstance(paramlocale: Locale): Currency_2;
    static getInstance(paramlocale: ULocale): Currency_2;
    static getKeywordValuesForLocale(paramkey: string, paramlocale: ULocale, paramcommonlyUsed: boolean): string[];
    static getParsingTrie(paramlocale: ULocale, paramtype: number): TextTrieMap<Currency$CurrencyStringInfo>;
    static internalGetInstance(paramtype: string, paramsubType: string): MeasureUnit;
    static isAvailable(paramcode: string, paramfrom: Date, paramto: Date): boolean;
    static parse(paramlocale: ULocale, paramtext: string, paramtype: number, parampos: ParsePosition): string;
    static registerInstance(paramcurrency: Currency_2, paramlocale: ULocale): Object;
    static resolve(paramcurrency: Currency_2, paramlocale: ULocale, paramsymbols: DecimalFormatSymbols): Currency_2;
    static unregister(paramregistryKey: Object): boolean;
    constructor(isoCode: string, currency1Sym: string, currency2Sym: string)
    // private symbol1: string;
    // private symbol2: string;
    equals(other: Object | null): boolean;
    getCurrencyCode(): string;
    getName(locale: Locale, nameStyle: number, isChoiceFormat: boolean[]): string;
    getName(locale: Locale, nameStyle: number, pluralCount: string, isChoiceFormat: boolean[]): string;
    getName(locale: ULocale, nameStyle: number, isChoiceFormat: boolean[]): string;
    getName(locale: ULocale, nameStyle: number, pluralCount: string, isChoiceFormat: boolean[]): string;
    hashCode(): number;
}