import type { BooleanIterator } from '../../../../../it/unimi/dsi/fastutil/booleans/BooleanIterator.d.ts'
import type { ByteIterator } from '../../../../../it/unimi/dsi/fastutil/bytes/ByteIterator.d.ts'
import type { DoubleIterator } from '../../../../../it/unimi/dsi/fastutil/doubles/DoubleIterator.d.ts'
import type { FloatIterator } from '../../../../../it/unimi/dsi/fastutil/floats/FloatIterator.d.ts'
import type { IntIterator } from '../../../../../it/unimi/dsi/fastutil/ints/IntIterator.d.ts'
import type { LongIterator } from '../../../../../it/unimi/dsi/fastutil/longs/LongIterator.d.ts'
import type { ShortIterator } from '../../../../../it/unimi/dsi/fastutil/shorts/ShortIterator.d.ts'
import type { BufferedReader } from '../../../../../java/io/BufferedReader.d.ts'
import type { File } from '../../../../../java/io/File.d.ts'
import type { PrintStream } from '../../../../../java/io/PrintStream.d.ts'
import type { Object } from '../../../../../java/lang/Object.d.ts'
import type { CharSequence } from '../../../../../java/lang/CharSequence.d.ts'
export class TextIO extends Object {
    static BUFFER_SIZE: number;
    static asBooleanIterable(paramarg0: File): boolean[];
    static asBooleanIterable(paramarg0: CharSequence): boolean[];
    static asBooleanIterator(paramarg0: BufferedReader): BooleanIterator;
    static asBooleanIterator(paramarg0: File): BooleanIterator;
    static asBooleanIterator(paramarg0: CharSequence): BooleanIterator;
    static asByteIterable(paramarg0: File): number[];
    static asByteIterable(paramarg0: CharSequence): number[];
    static asByteIterator(paramarg0: BufferedReader): ByteIterator;
    static asByteIterator(paramarg0: File): ByteIterator;
    static asByteIterator(paramarg0: CharSequence): ByteIterator;
    static asDoubleIterable(paramarg0: File): number[];
    static asDoubleIterable(paramarg0: CharSequence): number[];
    static asDoubleIterator(paramarg0: BufferedReader): DoubleIterator;
    static asDoubleIterator(paramarg0: File): DoubleIterator;
    static asDoubleIterator(paramarg0: CharSequence): DoubleIterator;
    static asFloatIterable(paramarg0: File): number[];
    static asFloatIterable(paramarg0: CharSequence): number[];
    static asFloatIterator(paramarg0: BufferedReader): FloatIterator;
    static asFloatIterator(paramarg0: File): FloatIterator;
    static asFloatIterator(paramarg0: CharSequence): FloatIterator;
    static asIntIterable(paramarg0: File): number[];
    static asIntIterable(paramarg0: CharSequence): number[];
    static asIntIterator(paramarg0: BufferedReader): IntIterator;
    static asIntIterator(paramarg0: File): IntIterator;
    static asIntIterator(paramarg0: CharSequence): IntIterator;
    static asLongIterable(paramarg0: File): number[];
    static asLongIterable(paramarg0: CharSequence): number[];
    static asLongIterator(paramarg0: BufferedReader): LongIterator;
    static asLongIterator(paramarg0: File): LongIterator;
    static asLongIterator(paramarg0: CharSequence): LongIterator;
    static asShortIterable(paramarg0: File): number[];
    static asShortIterable(paramarg0: CharSequence): number[];
    static asShortIterator(paramarg0: BufferedReader): ShortIterator;
    static asShortIterator(paramarg0: File): ShortIterator;
    static asShortIterator(paramarg0: CharSequence): ShortIterator;
    static loadBooleans(paramarg0: BufferedReader, paramarg1: boolean[]): number;
    static loadBooleans(paramarg0: BufferedReader, paramarg1: boolean[], paramarg2: number, paramarg3: number): number;
    static loadBooleans(paramarg0: File, paramarg1: boolean[]): number;
    static loadBooleans(paramarg0: File, paramarg1: boolean[], paramarg2: number, paramarg3: number): number;
    static loadBooleans(paramarg0: CharSequence, paramarg1: boolean[]): number;
    static loadBooleans(paramarg0: CharSequence, paramarg1: boolean[], paramarg2: number, paramarg3: number): number;
    static loadBooleans(paramarg0: BufferedReader, paramarg1: boolean[][]): number;
    static loadBooleans(paramarg0: BufferedReader, paramarg1: boolean[][], paramarg2: number, paramarg3: number): number;
    static loadBooleans(paramarg0: File, paramarg1: boolean[][]): number;
    static loadBooleans(paramarg0: File, paramarg1: boolean[][], paramarg2: number, paramarg3: number): number;
    static loadBooleans(paramarg0: CharSequence, paramarg1: boolean[][]): number;
    static loadBooleans(paramarg0: CharSequence, paramarg1: boolean[][], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: BufferedReader, paramarg1: number[]): number;
    static loadBytes(paramarg0: BufferedReader, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: File, paramarg1: number[]): number;
    static loadBytes(paramarg0: File, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: CharSequence, paramarg1: number[]): number;
    static loadBytes(paramarg0: CharSequence, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: BufferedReader, paramarg1: number[][]): number;
    static loadBytes(paramarg0: BufferedReader, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: File, paramarg1: number[][]): number;
    static loadBytes(paramarg0: File, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadBytes(paramarg0: CharSequence, paramarg1: number[][]): number;
    static loadBytes(paramarg0: CharSequence, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadDoubles(paramarg0: BufferedReader, paramarg1: number[]): number;
    static loadDoubles(paramarg0: BufferedReader, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadDoubles(paramarg0: File, paramarg1: number[]): number;
    static loadDoubles(paramarg0: File, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadDoubles(paramarg0: CharSequence, paramarg1: number[]): number;
    static loadDoubles(paramarg0: CharSequence, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadDoubles(paramarg0: BufferedReader, paramarg1: number[][]): number;
    static loadDoubles(paramarg0: BufferedReader, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadDoubles(paramarg0: File, paramarg1: number[][]): number;
    static loadDoubles(paramarg0: File, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadDoubles(paramarg0: CharSequence, paramarg1: number[][]): number;
    static loadDoubles(paramarg0: CharSequence, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadFloats(paramarg0: BufferedReader, paramarg1: number[]): number;
    static loadFloats(paramarg0: BufferedReader, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadFloats(paramarg0: File, paramarg1: number[]): number;
    static loadFloats(paramarg0: File, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadFloats(paramarg0: CharSequence, paramarg1: number[]): number;
    static loadFloats(paramarg0: CharSequence, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadFloats(paramarg0: BufferedReader, paramarg1: number[][]): number;
    static loadFloats(paramarg0: BufferedReader, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadFloats(paramarg0: File, paramarg1: number[][]): number;
    static loadFloats(paramarg0: File, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadFloats(paramarg0: CharSequence, paramarg1: number[][]): number;
    static loadFloats(paramarg0: CharSequence, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadInts(paramarg0: BufferedReader, paramarg1: number[]): number;
    static loadInts(paramarg0: BufferedReader, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadInts(paramarg0: File, paramarg1: number[]): number;
    static loadInts(paramarg0: File, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadInts(paramarg0: CharSequence, paramarg1: number[]): number;
    static loadInts(paramarg0: CharSequence, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadInts(paramarg0: BufferedReader, paramarg1: number[][]): number;
    static loadInts(paramarg0: BufferedReader, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadInts(paramarg0: File, paramarg1: number[][]): number;
    static loadInts(paramarg0: File, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadInts(paramarg0: CharSequence, paramarg1: number[][]): number;
    static loadInts(paramarg0: CharSequence, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadLongs(paramarg0: BufferedReader, paramarg1: number[]): number;
    static loadLongs(paramarg0: BufferedReader, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadLongs(paramarg0: File, paramarg1: number[]): number;
    static loadLongs(paramarg0: File, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadLongs(paramarg0: CharSequence, paramarg1: number[]): number;
    static loadLongs(paramarg0: CharSequence, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadLongs(paramarg0: BufferedReader, paramarg1: number[][]): number;
    static loadLongs(paramarg0: BufferedReader, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadLongs(paramarg0: File, paramarg1: number[][]): number;
    static loadLongs(paramarg0: File, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadLongs(paramarg0: CharSequence, paramarg1: number[][]): number;
    static loadLongs(paramarg0: CharSequence, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadShorts(paramarg0: BufferedReader, paramarg1: number[]): number;
    static loadShorts(paramarg0: BufferedReader, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadShorts(paramarg0: File, paramarg1: number[]): number;
    static loadShorts(paramarg0: File, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadShorts(paramarg0: CharSequence, paramarg1: number[]): number;
    static loadShorts(paramarg0: CharSequence, paramarg1: number[], paramarg2: number, paramarg3: number): number;
    static loadShorts(paramarg0: BufferedReader, paramarg1: number[][]): number;
    static loadShorts(paramarg0: BufferedReader, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadShorts(paramarg0: File, paramarg1: number[][]): number;
    static loadShorts(paramarg0: File, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static loadShorts(paramarg0: CharSequence, paramarg1: number[][]): number;
    static loadShorts(paramarg0: CharSequence, paramarg1: number[][], paramarg2: number, paramarg3: number): number;
    static storeBooleans(paramarg0: boolean[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeBooleans(paramarg0: boolean[], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeBooleans(paramarg0: boolean[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeBooleans(paramarg0: boolean[], paramarg1: File): void;
    static storeBooleans(paramarg0: boolean[], paramarg1: PrintStream): void;
    static storeBooleans(paramarg0: boolean[], paramarg1: CharSequence): void;
    static storeBooleans(paramarg0: boolean[][], paramarg1: File): void;
    static storeBooleans(paramarg0: boolean[][], paramarg1: PrintStream): void;
    static storeBooleans(paramarg0: boolean[][], paramarg1: CharSequence): void;
    static storeBooleans(paramarg0: boolean[][], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeBooleans(paramarg0: boolean[][], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeBooleans(paramarg0: boolean[][], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeBooleans(paramarg0: BooleanIterator, paramarg1: File): void;
    static storeBooleans(paramarg0: BooleanIterator, paramarg1: PrintStream): void;
    static storeBooleans(paramarg0: BooleanIterator, paramarg1: CharSequence): void;
    static storeBytes(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeBytes(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeBytes(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeBytes(paramarg0: number[], paramarg1: File): void;
    static storeBytes(paramarg0: number[], paramarg1: PrintStream): void;
    static storeBytes(paramarg0: number[], paramarg1: CharSequence): void;
    static storeBytes(paramarg0: number[][], paramarg1: File): void;
    static storeBytes(paramarg0: number[][], paramarg1: PrintStream): void;
    static storeBytes(paramarg0: number[][], paramarg1: CharSequence): void;
    static storeBytes(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeBytes(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeBytes(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeBytes(paramarg0: ByteIterator, paramarg1: File): void;
    static storeBytes(paramarg0: ByteIterator, paramarg1: PrintStream): void;
    static storeBytes(paramarg0: ByteIterator, paramarg1: CharSequence): void;
    static storeDoubles(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeDoubles(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeDoubles(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeDoubles(paramarg0: number[], paramarg1: File): void;
    static storeDoubles(paramarg0: number[], paramarg1: PrintStream): void;
    static storeDoubles(paramarg0: number[], paramarg1: CharSequence): void;
    static storeDoubles(paramarg0: number[][], paramarg1: File): void;
    static storeDoubles(paramarg0: number[][], paramarg1: PrintStream): void;
    static storeDoubles(paramarg0: number[][], paramarg1: CharSequence): void;
    static storeDoubles(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeDoubles(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeDoubles(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeDoubles(paramarg0: DoubleIterator, paramarg1: File): void;
    static storeDoubles(paramarg0: DoubleIterator, paramarg1: PrintStream): void;
    static storeDoubles(paramarg0: DoubleIterator, paramarg1: CharSequence): void;
    static storeFloats(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeFloats(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeFloats(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeFloats(paramarg0: number[], paramarg1: File): void;
    static storeFloats(paramarg0: number[], paramarg1: PrintStream): void;
    static storeFloats(paramarg0: number[], paramarg1: CharSequence): void;
    static storeFloats(paramarg0: number[][], paramarg1: File): void;
    static storeFloats(paramarg0: number[][], paramarg1: PrintStream): void;
    static storeFloats(paramarg0: number[][], paramarg1: CharSequence): void;
    static storeFloats(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeFloats(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeFloats(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeFloats(paramarg0: FloatIterator, paramarg1: File): void;
    static storeFloats(paramarg0: FloatIterator, paramarg1: PrintStream): void;
    static storeFloats(paramarg0: FloatIterator, paramarg1: CharSequence): void;
    static storeInts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeInts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeInts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeInts(paramarg0: number[], paramarg1: File): void;
    static storeInts(paramarg0: number[], paramarg1: PrintStream): void;
    static storeInts(paramarg0: number[], paramarg1: CharSequence): void;
    static storeInts(paramarg0: number[][], paramarg1: File): void;
    static storeInts(paramarg0: number[][], paramarg1: PrintStream): void;
    static storeInts(paramarg0: number[][], paramarg1: CharSequence): void;
    static storeInts(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeInts(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeInts(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeInts(paramarg0: IntIterator, paramarg1: File): void;
    static storeInts(paramarg0: IntIterator, paramarg1: PrintStream): void;
    static storeInts(paramarg0: IntIterator, paramarg1: CharSequence): void;
    static storeLongs(paramarg0: LongIterator, paramarg1: File): void;
    static storeLongs(paramarg0: LongIterator, paramarg1: PrintStream): void;
    static storeLongs(paramarg0: LongIterator, paramarg1: CharSequence): void;
    static storeLongs(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeLongs(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeLongs(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeLongs(paramarg0: number[], paramarg1: File): void;
    static storeLongs(paramarg0: number[], paramarg1: PrintStream): void;
    static storeLongs(paramarg0: number[], paramarg1: CharSequence): void;
    static storeLongs(paramarg0: number[][], paramarg1: File): void;
    static storeLongs(paramarg0: number[][], paramarg1: PrintStream): void;
    static storeLongs(paramarg0: number[][], paramarg1: CharSequence): void;
    static storeLongs(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeLongs(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeLongs(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeShorts(paramarg0: ShortIterator, paramarg1: File): void;
    static storeShorts(paramarg0: ShortIterator, paramarg1: PrintStream): void;
    static storeShorts(paramarg0: ShortIterator, paramarg1: CharSequence): void;
    static storeShorts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeShorts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeShorts(paramarg0: number[], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    static storeShorts(paramarg0: number[], paramarg1: File): void;
    static storeShorts(paramarg0: number[], paramarg1: PrintStream): void;
    static storeShorts(paramarg0: number[], paramarg1: CharSequence): void;
    static storeShorts(paramarg0: number[][], paramarg1: File): void;
    static storeShorts(paramarg0: number[][], paramarg1: PrintStream): void;
    static storeShorts(paramarg0: number[][], paramarg1: CharSequence): void;
    static storeShorts(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: File): void;
    static storeShorts(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: PrintStream): void;
    static storeShorts(paramarg0: number[][], paramarg1: number, paramarg2: number, paramarg3: CharSequence): void;
    private constructor()
}