import type { JavaMap } from '../../../../../../JavaMap.d.ts'
import type { Object } from '../../../../../../java/lang/Object.d.ts'
import type { PrimitiveType } from '../../../../../../kotlin/reflect/jvm/internal/impl/builtins/PrimitiveType.d.ts'
import type { ClassId } from '../../../../../../kotlin/reflect/jvm/internal/impl/name/ClassId.d.ts'
import type { FqName } from '../../../../../../kotlin/reflect/jvm/internal/impl/name/FqName.d.ts'
import type { FqNameUnsafe } from '../../../../../../kotlin/reflect/jvm/internal/impl/name/FqNameUnsafe.d.ts'
import type { Name } from '../../../../../../kotlin/reflect/jvm/internal/impl/name/Name.d.ts'
export class StandardNames$FqNames extends Object {
    static INSTANCE: StandardNames$FqNames;
    static _boolean: FqNameUnsafe;
    static _byte: FqNameUnsafe;
    static _char: FqNameUnsafe;
    static _double: FqNameUnsafe;
    static _enum: FqNameUnsafe;
    static _float: FqNameUnsafe;
    static _int: FqNameUnsafe;
    static _long: FqNameUnsafe;
    static _short: FqNameUnsafe;
    static accessibleLateinitPropertyLiteral: FqName;
    static annotation: FqName;
    static annotationRetention: FqName;
    static annotationTarget: FqName;
    static any: FqNameUnsafe;
    static array: FqNameUnsafe;
    static arrayClassFqNameToPrimitiveType: JavaMap<FqNameUnsafe, PrimitiveType>;
    static atomicArray: FqName;
    static atomicBoolean: FqName;
    static atomicInt: FqName;
    static atomicIntArray: FqName;
    static atomicLong: FqName;
    static atomicLongArray: FqName;
    static atomicReference: FqName;
    static charSequence: FqNameUnsafe;
    static cloneable: FqNameUnsafe;
    static collection: FqName;
    static comparable: FqName;
    static contextFunctionTypeParams: FqName;
    static deprecated: FqName;
    static deprecatedSinceKotlin: FqName;
    static deprecationLevel: FqName;
    static extensionFunctionType: FqName;
    static findAssociatedObject: FqNameUnsafe;
    static fqNameToPrimitiveType: JavaMap<FqNameUnsafe, PrimitiveType>;
    static functionSupertype: FqNameUnsafe;
    static intRange: FqNameUnsafe;
    static introducedAt: FqName;
    static iterable: FqName;
    static iterator: FqName;
    static kCallable: FqNameUnsafe;
    static kClass: FqNameUnsafe;
    static kDeclarationContainer: FqNameUnsafe;
    static kMutableProperty0: FqNameUnsafe;
    static kMutableProperty1: FqNameUnsafe;
    static kMutableProperty2: FqNameUnsafe;
    static kMutablePropertyFqName: FqNameUnsafe;
    static kProperty: ClassId;
    static kProperty0: FqNameUnsafe;
    static kProperty1: FqNameUnsafe;
    static kProperty2: FqNameUnsafe;
    static kPropertyFqName: FqNameUnsafe;
    static kType: FqNameUnsafe;
    static list: FqName;
    static listIterator: FqName;
    static longRange: FqNameUnsafe;
    static map: FqName;
    static mapEntry: FqName;
    static mustBeDocumented: FqName;
    static mutableCollection: FqName;
    static mutableIterable: FqName;
    static mutableIterator: FqName;
    static mutableList: FqName;
    static mutableListIterator: FqName;
    static mutableMap: FqName;
    static mutableMapEntry: FqName;
    static mutableSet: FqName;
    static nothing: FqNameUnsafe;
    static number: FqNameUnsafe;
    static parameterName: FqName;
    static parameterNameClassId: ClassId;
    static platformDependent: FqName;
    static platformDependentClassId: ClassId;
    static primitiveArrayTypeShortNames: Name[];
    static primitiveTypeShortNames: Name[];
    static publishedApi: FqName;
    static repeatable: FqName;
    static repeatableClassId: ClassId;
    static replaceWith: FqName;
    static retention: FqName;
    static retentionClassId: ClassId;
    static set: FqName;
    static string: FqNameUnsafe;
    static suppress: FqName;
    static target: FqName;
    static targetClassId: ClassId;
    static throwable: FqName;
    static uByte: ClassId;
    static uByteArrayFqName: FqName;
    static uByteFqName: FqName;
    static uInt: ClassId;
    static uIntArrayFqName: FqName;
    static uIntFqName: FqName;
    static uLong: ClassId;
    static uLongArrayFqName: FqName;
    static uLongFqName: FqName;
    static uShort: ClassId;
    static uShortArrayFqName: FqName;
    static uShortFqName: FqName;
    static unit: FqNameUnsafe;
    static unsafeVariance: FqName;
    static reflect(paramarg0: string): FqNameUnsafe;
    private constructor()
    // private annotationName(arg0: string): FqName;
    // private collectionsFqName(arg0: string): FqName;
    // private concurrentAtomics(arg0: string): FqName;
    // private fqName(arg0: string): FqName;
    // private fqNameUnsafe(arg0: string): FqNameUnsafe;
    // private internalName(arg0: string): FqName;
    // private rangesFqName(arg0: string): FqNameUnsafe;
}