import type { VersionedGLSLLexer } from '../../../../io/github/douira/glsl_transformer/parser/VersionedGLSLLexer.d.ts'
import type { Object } from '../../../../java/lang/Object.d.ts'
import type { CharStream } from '../../../../org/antlr/v4/runtime/CharStream.d.ts'
import type { RuleContext } from '../../../../org/antlr/v4/runtime/RuleContext.d.ts'
import type { Vocabulary } from '../../../../org/antlr/v4/runtime/Vocabulary.d.ts'
import type { ATN } from '../../../../org/antlr/v4/runtime/atn/ATN.d.ts'
export class GLSLLexer extends VersionedGLSLLexer {
    static ACCELERATION_STRUCTURE_EXT: number;
    static ADD_ASSIGN: number;
    static AND_ASSIGN: number;
    static ASSIGN_OP: number;
    static ATOMIC_UINT: number;
    static ATTRIBUTE: number;
    static BITWISE_AND_OP: number;
    static BITWISE_NEG_OP: number;
    static BITWISE_OR_OP: number;
    static BITWISE_XOR_OP: number;
    static BLOCK_COMMENT: number;
    static BOOL: number;
    static BOOLCONSTANT: number;
    static BREAK: number;
    static BUFFER: number;
    static BVEC2: number;
    static BVEC3: number;
    static BVEC4: number;
    static CALLABLE_DATA_EXT: number;
    static CALLABLE_DATA_IN_EXT: number;
    static CASE: number;
    static CENTROID: number;
    static COHERENT: number;
    static COLON: number;
    static COMMA: number;
    static COMMENTS: number;
    static CONST: number;
    static CONTINUE: number;
    static C_BLOCK_COMMENT: number;
    static C_CONTENT: number;
    static C_EOL: number;
    static C_LINE_COMMENT: number;
    static C_WS: number;
    static CustomDirective: number;
    static DEC_OP: number;
    static DEFAULT: number;
    static DEFAULT_MODE: number;
    static DEFAULT_TOKEN_CHANNEL: number;
    static DEMOTE: number;
    static DEVICECOHERENT: number;
    static DISCARD: number;
    static DIV_ASSIGN: number;
    static DIV_OP: number;
    static DO: number;
    static DOT: number;
    static DOT_LENGTH_METHOD_CALL: number;
    static ELSE: number;
    static EOF: number;
    static EOL: number;
    static EQ_OP: number;
    static F16MAT2X2: number;
    static F16MAT2X3: number;
    static F16MAT2X4: number;
    static F16MAT3X2: number;
    static F16MAT3X3: number;
    static F16MAT3X4: number;
    static F16MAT4X2: number;
    static F16MAT4X3: number;
    static F16MAT4X4: number;
    static F16VEC2: number;
    static F16VEC3: number;
    static F16VEC4: number;
    static F32MAT2X2: number;
    static F32MAT2X3: number;
    static F32MAT2X4: number;
    static F32MAT3X2: number;
    static F32MAT3X3: number;
    static F32MAT3X4: number;
    static F32MAT4X2: number;
    static F32MAT4X3: number;
    static F32MAT4X4: number;
    static F32VEC2: number;
    static F32VEC3: number;
    static F32VEC4: number;
    static F64MAT2X2: number;
    static F64MAT2X3: number;
    static F64MAT2X4: number;
    static F64MAT3X2: number;
    static F64MAT3X3: number;
    static F64MAT3X4: number;
    static F64MAT4X2: number;
    static F64MAT4X3: number;
    static F64MAT4X4: number;
    static F64VEC2: number;
    static F64VEC3: number;
    static F64VEC4: number;
    static FLAT: number;
    static FLOAT16: number;
    static FLOAT16CONSTANT: number;
    static FLOAT32: number;
    static FLOAT32CONSTANT: number;
    static FLOAT64: number;
    static FLOAT64CONSTANT: number;
    static FOR: number;
    static GE_OP: number;
    static GT_OP: number;
    static HIDDEN: number;
    static HIGHP: number;
    static HIT_ATTRIBUTE_EXT: number;
    static I16VEC2: number;
    static I16VEC3: number;
    static I16VEC4: number;
    static I32VEC2: number;
    static I32VEC3: number;
    static I32VEC4: number;
    static I64VEC2: number;
    static I64VEC3: number;
    static I64VEC4: number;
    static I8VEC2: number;
    static I8VEC3: number;
    static I8VEC4: number;
    static IDENTIFIER: number;
    static IF: number;
    static IGNORE_INTERSECTION_EXT: number;
    static IIMAGE1D: number;
    static IIMAGE1DARRAY: number;
    static IIMAGE2D: number;
    static IIMAGE2DARRAY: number;
    static IIMAGE2DMS: number;
    static IIMAGE2DMSARRAY: number;
    static IIMAGE2DRECT: number;
    static IIMAGE3D: number;
    static IIMAGEBUFFER: number;
    static IIMAGECUBE: number;
    static IIMAGECUBEARRAY: number;
    static IMAGE1D: number;
    static IMAGE1DARRAY: number;
    static IMAGE2D: number;
    static IMAGE2DARRAY: number;
    static IMAGE2DMS: number;
    static IMAGE2DMSARRAY: number;
    static IMAGE2DRECT: number;
    static IMAGE3D: number;
    static IMAGEBUFFER: number;
    static IMAGECUBE: number;
    static IMAGECUBEARRAY: number;
    static IN: number;
    static INC_OP: number;
    static INOUT: number;
    static INT16: number;
    static INT16CONSTANT: number;
    static INT32: number;
    static INT32CONSTANT: number;
    static INT64: number;
    static INT64CONSTANT: number;
    static INT8: number;
    static INVARIANT: number;
    static ISAMPLER1D: number;
    static ISAMPLER1DARRAY: number;
    static ISAMPLER2D: number;
    static ISAMPLER2DARRAY: number;
    static ISAMPLER2DMS: number;
    static ISAMPLER2DMSARRAY: number;
    static ISAMPLER2DRECT: number;
    static ISAMPLER3D: number;
    static ISAMPLERBUFFER: number;
    static ISAMPLERCUBE: number;
    static ISAMPLERCUBEARRAY: number;
    static LAYOUT: number;
    static LBRACE: number;
    static LBRACKET: number;
    static LEFT_ASSIGN: number;
    static LEFT_OP: number;
    static LE_OP: number;
    static LINE_COMMENT: number;
    static LINE_CONTINUE: number;
    static LOGICAL_AND_OP: number;
    static LOGICAL_NOT_OP: number;
    static LOGICAL_OR_OP: number;
    static LOGICAL_XOR_OP: number;
    static LOWP: number;
    static LPAREN: number;
    static LT_OP: number;
    static MAX_CHAR_VALUE: number;
    static MEDIUMP: number;
    static MINUS_OP: number;
    static MIN_CHAR_VALUE: number;
    static MOD_ASSIGN: number;
    static MOD_OP: number;
    static MORE: number;
    static MUL_ASSIGN: number;
    static NE_OP: number;
    static NONPRIVATE: number;
    static NOPERSPECTIVE: number;
    static NR: number;
    static NR_ALL: number;
    static NR_BLOCK_COMMENT: number;
    static NR_COLON: number;
    static NR_COMPATIBILITY: number;
    static NR_CORE: number;
    static NR_CUSTOM: number;
    static NR_DISABLE: number;
    static NR_ENABLE: number;
    static NR_EOL: number;
    static NR_ES: number;
    static NR_EXTENSION: number;
    static NR_FASTMATH: number;
    static NR_FASTPRECISION: number;
    static NR_GLSLES_100: number;
    static NR_GLSLES_300: number;
    static NR_GLSLES_310: number;
    static NR_GLSLES_320: number;
    static NR_GLSL_110: number;
    static NR_GLSL_120: number;
    static NR_GLSL_130: number;
    static NR_GLSL_140: number;
    static NR_GLSL_150: number;
    static NR_GLSL_330: number;
    static NR_GLSL_400: number;
    static NR_GLSL_410: number;
    static NR_GLSL_420: number;
    static NR_GLSL_430: number;
    static NR_GLSL_440: number;
    static NR_GLSL_450: number;
    static NR_GLSL_460: number;
    static NR_IDENTIFIER: number;
    static NR_IFCVT: number;
    static NR_INCLUDE: number;
    static NR_INLINE: number;
    static NR_INTCONSTANT: number;
    static NR_LINE: number;
    static NR_LINE_COMMENT: number;
    static NR_LINE_CONTINUE: number;
    static NR_LPAREN: number;
    static NR_Mode: number;
    static NR_NONE: number;
    static NR_OFF: number;
    static NR_ON: number;
    static NR_PRAGMA: number;
    static NR_PRAGMA_DEBUG: number;
    static NR_PRAGMA_INVARIANT: number;
    static NR_PRAGMA_OPTIMIZE: number;
    static NR_PRAGMA_OPTIONNV: number;
    static NR_REQUIRE: number;
    static NR_RPAREN: number;
    static NR_SA_CONTENT: number;
    static NR_SA_STRING_END: number;
    static NR_STDGL: number;
    static NR_STRICT: number;
    static NR_STRING_START: number;
    static NR_STRING_START_ANGLE: number;
    static NR_S_CONTENT: number;
    static NR_S_STRING_END: number;
    static NR_UNROLL: number;
    static NR_VERSION: number;
    static NR_WARN: number;
    static NR_WS: number;
    static OR_ASSIGN: number;
    static OUT: number;
    static PATCH: number;
    static PLUS_OP: number;
    static PP_BLOCK_COMMENT: number;
    static PP_CONTENT: number;
    static PP_EMPTY: number;
    static PP_ENTER_MODE: number;
    static PP_EOL: number;
    static PP_LINE_COMMENT: number;
    static PP_LINE_CONTINUE: number;
    static PRECISE: number;
    static PRECISION: number;
    static PREPROCESSOR: number;
    static Preprocessor: number;
    static QUERY_OP: number;
    static QUEUEFAMILYCOHERENT: number;
    static RAY_PAYLOAD_EXT: number;
    static RAY_PAYLOAD_IN_EXT: number;
    static RBRACE: number;
    static RBRACKET: number;
    static READONLY: number;
    static RESTRICT: number;
    static RETURN: number;
    static RIGHT_ASSIGN: number;
    static RIGHT_OP: number;
    static RPAREN: number;
    static SAMPLE: number;
    static SAMPLER1D: number;
    static SAMPLER1DARRAY: number;
    static SAMPLER1DARRAYSHADOW: number;
    static SAMPLER1DSHADOW: number;
    static SAMPLER2D: number;
    static SAMPLER2DARRAY: number;
    static SAMPLER2DARRAYSHADOW: number;
    static SAMPLER2DMS: number;
    static SAMPLER2DMSARRAY: number;
    static SAMPLER2DRECT: number;
    static SAMPLER2DRECTSHADOW: number;
    static SAMPLER2DSHADOW: number;
    static SAMPLER3D: number;
    static SAMPLERBUFFER: number;
    static SAMPLERCUBE: number;
    static SAMPLERCUBEARRAY: number;
    static SAMPLERCUBEARRAYSHADOW: number;
    static SAMPLERCUBESHADOW: number;
    static SEMICOLON: number;
    static SHARED: number;
    static SKIP: number;
    static SL_CONTENT: number;
    static SL_STRING_END: number;
    static SMOOTH: number;
    static STRING_START: number;
    static STRUCT: number;
    static SUBGROUPCOHERENT: number;
    static SUBROUTINE: number;
    static SUB_ASSIGN: number;
    static SWITCH: number;
    static String: number;
    static StringAngle: number;
    static StringLiteral: number;
    static TASKNV: number;
    static TERMINATE_RAY_EXT: number;
    static TIMES_OP: number;
    static U16VEC2: number;
    static U16VEC3: number;
    static U16VEC4: number;
    static U32VEC2: number;
    static U32VEC3: number;
    static U32VEC4: number;
    static U64VEC2: number;
    static U64VEC3: number;
    static U64VEC4: number;
    static U8VEC2: number;
    static U8VEC3: number;
    static U8VEC4: number;
    static UIMAGE1D: number;
    static UIMAGE1DARRAY: number;
    static UIMAGE2D: number;
    static UIMAGE2DARRAY: number;
    static UIMAGE2DMS: number;
    static UIMAGE2DMSARRAY: number;
    static UIMAGE2DRECT: number;
    static UIMAGE3D: number;
    static UIMAGEBUFFER: number;
    static UIMAGECUBE: number;
    static UIMAGECUBEARRAY: number;
    static UINT16: number;
    static UINT16CONSTANT: number;
    static UINT32: number;
    static UINT32CONSTANT: number;
    static UINT64: number;
    static UINT64CONSTANT: number;
    static UINT8: number;
    static UNIFORM: number;
    static USAMPLER1D: number;
    static USAMPLER1DARRAY: number;
    static USAMPLER2D: number;
    static USAMPLER2DARRAY: number;
    static USAMPLER2DMS: number;
    static USAMPLER2DMSARRAY: number;
    static USAMPLER2DRECT: number;
    static USAMPLER3D: number;
    static USAMPLERBUFFER: number;
    static USAMPLERCUBE: number;
    static USAMPLERCUBEARRAY: number;
    static VARYING: number;
    static VOCABULARY: Vocabulary;
    static VOID: number;
    static VOLATILE: number;
    static WHILE: number;
    static WHITESPACE: number;
    static WORKGROUPCOHERENT: number;
    static WRITEONLY: number;
    static WS: number;
    static XOR_ASSIGN: number;
    static _ATN: ATN;
    static _serializedATN: string;
    static channelNames: (Object | null)[];
    static modeNames: (Object | null)[];
    static ruleNames: (Object | null)[];
    static tokenNames: (Object | null)[];
    constructor(arg0: CharStream)
    // private ATOMIC_UINT_sempred(arg0: RuleContext, arg1: number): boolean;
    // private COHERENT_sempred(arg0: RuleContext, arg1: number): boolean;
    // private DEVICECOHERENT_sempred(arg0: RuleContext, arg1: number): boolean;
    // private ISAMPLER1DARRAY_sempred(arg0: RuleContext, arg1: number): boolean;
    // private ISAMPLER1D_sempred(arg0: RuleContext, arg1: number): boolean;
    // private ISAMPLER2DMSARRAY_sempred(arg0: RuleContext, arg1: number): boolean;
    // private ISAMPLER2DMS_sempred(arg0: RuleContext, arg1: number): boolean;
    // private ISAMPLER2DRECT_sempred(arg0: RuleContext, arg1: number): boolean;
    // private ISAMPLERBUFFER_sempred(arg0: RuleContext, arg1: number): boolean;
    // private NONPRIVATE_sempred(arg0: RuleContext, arg1: number): boolean;
    // private NOPERSPECTIVE_sempred(arg0: RuleContext, arg1: number): boolean;
    // private NR_CUSTOM_sempred(arg0: RuleContext, arg1: number): boolean;
    // private NR_INCLUDE_sempred(arg0: RuleContext, arg1: number): boolean;
    // private NR_STRING_START_ANGLE_sempred(arg0: RuleContext, arg1: number): boolean;
    // private NR_STRING_START_sempred(arg0: RuleContext, arg1: number): boolean;
    // private PATCH_sempred(arg0: RuleContext, arg1: number): boolean;
    // private QUEUEFAMILYCOHERENT_sempred(arg0: RuleContext, arg1: number): boolean;
    // private READONLY_sempred(arg0: RuleContext, arg1: number): boolean;
    // private RESTRICT_sempred(arg0: RuleContext, arg1: number): boolean;
    // private SAMPLER1DARRAYSHADOW_sempred(arg0: RuleContext, arg1: number): boolean;
    // private SAMPLER2DMSARRAY_sempred(arg0: RuleContext, arg1: number): boolean;
    // private SAMPLER2DMS_sempred(arg0: RuleContext, arg1: number): boolean;
    // private SAMPLERBUFFER_sempred(arg0: RuleContext, arg1: number): boolean;
    // private SAMPLE_sempred(arg0: RuleContext, arg1: number): boolean;
    // private STRING_START_sempred(arg0: RuleContext, arg1: number): boolean;
    // private SUBGROUPCOHERENT_sempred(arg0: RuleContext, arg1: number): boolean;
    // private SUBROUTINE_sempred(arg0: RuleContext, arg1: number): boolean;
    // private TASKNV_sempred(arg0: RuleContext, arg1: number): boolean;
    // private USAMPLER1DARRAY_sempred(arg0: RuleContext, arg1: number): boolean;
    // private USAMPLER1D_sempred(arg0: RuleContext, arg1: number): boolean;
    // private USAMPLER2DMSARRAY_sempred(arg0: RuleContext, arg1: number): boolean;
    // private USAMPLER2DMS_sempred(arg0: RuleContext, arg1: number): boolean;
    // private USAMPLER2DRECT_sempred(arg0: RuleContext, arg1: number): boolean;
    // private USAMPLERBUFFER_sempred(arg0: RuleContext, arg1: number): boolean;
    // private WORKGROUPCOHERENT_sempred(arg0: RuleContext, arg1: number): boolean;
    // private WRITEONLY_sempred(arg0: RuleContext, arg1: number): boolean;
    getATN(): ATN;
    getChannelNames(): string[];
    getGrammarFileName(): string;
    getModeNames(): string[];
    getRuleNames(): string[];
    getSerializedATN(): string;
    getTokenNames(): string[];
    getVocabulary(): Vocabulary;
    sempred(arg0: RuleContext, arg1: number, arg2: number): boolean;
}